<?php
namespace JetShopModule\Admin\Payment\Methods;

use JetShop\Payment_Method;

use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use JetShop\Payment_Method_ShopData;
use JetShop\Shops;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Payment_Method     $payment_method
 */

$payment_method = $this->getRaw( 'payment_method' );
?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>

		<?php if(!$payment_method->getIsNew()):
			foreach(Shops::getListSorted() as $shop):
				echo $payment_method->getShopData( $shop )->renderImageWidgets( Payment_Method_ShopData::getImageClasses(), $payment_method->getEditForm()->getIsReadonly() );
			endforeach;
		endif; ?>
	</div>
</div>



