<?php
namespace JetShopModule\Admin\Payment\Methods;

use JetShop\Payment_Method;

use Jet\UI;
use Jet\Mvc_View;
use Jet\Form;
use JetShop\Payment_Method_ShopData;
use JetShop\Shops;

/**
 * @var Mvc_View $this
 * @var Form     $form
 * @var Payment_Method     $payment_method
 */

$payment_method = $this->getRaw( 'payment_method' );
?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>

		<?php if(!$payment_method->getIsNew()): ?>
			<?php foreach(Shops::getList() as $shop):
				$shop_id= $shop->getId();

				$shop_data = $payment_method->getShopData( $shop_id );
				?>
				<?=$shop_data->renderImageWidgets( Payment_Method_ShopData::getImageClasses() )?>
			<?php endforeach; ?>
		<?php endif; ?>
	</div>
</div>



