<?php
namespace JetApplicationModule\Admin\Payment\Methods;

use JetApplication\Payment_Method;

use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use JetApplication\Shops;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Payment_Method     $payment_method
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 1 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );

$payment_method = $this->getRaw( 'payment_method' );

$form->field( 'delivery_methods' )->input()->addCustomCssStyle('height: 300px');
$form->field( 'services' )->input()->addCustomCssStyle('height: 200px');
?>

<?=$form->start()?>
<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()?>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>
		<br/>

		<?=$form->field( 'internal_name' )?>
		<?=$form->field( 'code' )?>
		<?=$form->field( 'kind' )?>
		<?=$form->field( 'delivery_methods' )?>
		<?=$form->field( 'services' )?>
		<?=$form->field( 'internal_description' )?>


		<?php foreach(Shops::getListSorted() as $shop):
			$shop_key= $shop->getKey();

			$shop_data = $payment_method->getShopData( $shop );
			?>
			<?=$shop_data->renderShopDataBlock_start()?>

			<fieldset>
				<legend class="sub"><?=Tr::_('Main data')?></legend>

				<?=$form->field('/shop_data/'.$shop_key.'/is_active')?>
				<?=$form->field('/shop_data/'.$shop_key.'/default_price')?>
				<?=$form->field('/shop_data/'.$shop_key.'/discount_is_not_allowed')?>
				<?=$form->field('/shop_data/'.$shop_key.'/vat_rate')?>
				<?=$form->field('/shop_data/'.$shop_key.'/priority')?>
				<?=$form->field('/shop_data/'.$shop_key.'/title')?>
				<?=$form->field('/shop_data/'.$shop_key.'/description')?>
				<?=$form->field('/shop_data/'.$shop_key.'/description_short')?>
				<?=$form->field('/shop_data/'.$shop_key.'/confirmation_email_info_text')?>


			</fieldset>

			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach; ?>
	</div>
</div>

<?=$form->end()?>
