<?php
namespace JetShopModule\Admin\Payment\Methods;

use JetShop\Payment_Method;

use Jet\UI;
use Jet\Mvc_View;
use Jet\Form;
use Jet\Tr;
use JetShop\Shops;

/**
 * @var Mvc_View $this
 * @var Form     $form
 * @var Payment_Method     $payment_method
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 1 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 4 ] );

$payment_method = $this->getRaw( 'payment_method' );

$form->field( 'delivery_methods' )->input()->addCustomCssStyle('height: 300px');
$form->field( 'services' )->input()->addCustomCssStyle('height: 200px');
?>

<?=$form->start()?>
<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()?>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>
		<br/>

		<?=$form->field( 'internal_name' )?>
		<?=$form->field( 'code' )?>
		<?=$form->field( 'kind' )?>
		<?=$form->field( 'delivery_methods' )?>
		<?=$form->field( 'services' )?>
		<?=$form->field( 'internal_description' )?>


		<?php foreach(Shops::getList() as $shop):
			$shop_code= $shop->getCode();

			$shop_data = $payment_method->getShopData( $shop_code );
			?>
			<?=$shop_data->renderShopDataBlock_start()?>

			<fieldset>
				<legend class="sub"><?=Tr::_('Main data')?></legend>

				<?=$form->field('/shop_data/'.$shop_code.'/is_active')?>
				<?=$form->field('/shop_data/'.$shop_code.'/default_price')?>
				<?=$form->field('/shop_data/'.$shop_code.'/vat_rate')?>
				<?=$form->field('/shop_data/'.$shop_code.'/priority')?>
				<?=$form->field('/shop_data/'.$shop_code.'/title')?>
				<?=$form->field('/shop_data/'.$shop_code.'/description')?>
				<?=$form->field('/shop_data/'.$shop_code.'/description_short')?>

			</fieldset>

			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach; ?>
	</div>
</div>

<?=$form->end()?>
