<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Payment\Methods;


use Jet\Form;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Admin_Managers;
use JetApplication\EShops;
use JetApplication\Payment_Method;
use JetApplication\Payment_Method_Option;

/**
 * @var MVC_View   $this
 * @var Payment_Method $method
 * @var Payment_Method_Option $new_option
 * @var Form $form
 * @var Controller_Main $controller
 */
$method = $this->getRaw('method');
$controller = $this->getController();

$new_option = $this->getRaw('new_option');

$router = $this->getController()->getControllerRouter();

echo $this->controller->getEditorManager()->renderToolbar();

?>
<div id="main-col">
		<?=$this->getRaw('tabs')?>

			<table class="table table-striped">
				<thead>
					<tr>
						<th style="width: 120px"></th>
						<th style="width: 200px"></th>
						<th style="width: 250px"><?=Tr::_('Code')?></th>
						<th style="width: 250px"><?=Tr::_('Internal name')?></th>
						<th><?=Tr::_('Internal notes')?></th>
					</tr>
				</thead>
				<tbody class="sortable" id="sort_items">
				<?php foreach( $method->getOptions() as $option):
					$edit_uri = $router->getAction('edit_option_main')->URI($option->getInternalCode());
					?>
					<tr class="sortable-item" data-id="<?=$option->getInternalCode()?>">
						<td>
							<i class="option-move"><?=UI::icon('up-down')?></i>
							<?=UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);?>
						</td>
						<td>
							<?php
							if($option->isActive()):
								?><span class="badge badge-success"> <?=Tr::_('Active', dictionary: Admin_Managers::EntityListing()->getModuleManifest()->getName())?> </span> <?php
							else:
								?><span class="badge badge-danger"><?=Tr::_('Inactive', dictionary: Admin_Managers::EntityListing()->getModuleManifest()->getName())?></span> <?php
							endif;
							
							if( count(EShops::getListSorted())>1 ):
								foreach( EShops::getListSorted() as $eshop):
									if($option->getEshopData($eshop)->isActiveForShop()):
										?><span class="badge badge-success"><?=$eshop->getName()?></span> <?php
									else:
										?><span class="badge badge-danger"><?=$eshop->getName()?></span> <?php
									endif;
								endforeach;
							endif;
							?>
						</td>
						<td><a href="<?=$edit_uri?>"><?=$option->getInternalCode()?></a></td>
						<td><a href="<?=$edit_uri?>"><?=$option->getInternalName()?></a></td>
						<td><?=nl2br($option->getInternalNotes())?></td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		
		


</div>

<?php if(!$method->getEditForm()->getIsReadonly()): ?>
<form action="<?=Http_Request::currentURI(['action'=>'sort_options'])?>" method="post" id="sort_form">
	<input type="hidden" name="sort_order" id="sort_order" />
</form>

<script type="text/javascript">

	const optionSort = {
		init: function () {
			$('#sort_items')['sortable']({
				stop: function () {
					optionSort.setSort();
				}
			});
		},

		setSort: function () {
			const values = [];

			$('#sort_items').find('.sortable-item').each(function (i, item) {
				values.push($(item).data('id'));
			});

			$('#sort_order').val(values.join('|'));
			$('#sort_form').submit();

		}
	};

	optionSort.init();
</script>
<?php endif; ?>