<?php
namespace JetApplicationModule\Admin\Payment\Methods;

use Jet\Tr;
use Jet\MVC_View;
use Jet\UI;
use Jet\UI_button;
use Jet\UI_tabs;
use Jet\Form;
use JetApplication\Payment_Method;

/**
 * @var MVC_View $this
 * @var Payment_Method $item
 * @var UI_tabs $tabs
 * @var Form $set_price_form
 */

$item = $this->getRaw('item');
$tabs = $this->getRaw('tabs');

$set_price_form = $this->getRaw('set_price_form');

if($set_price_form):
	echo UI::button( Tr::_('Set price'))
		->setClass(UI_button::CLASS_DANGER)
		->setOnClick("$('#set_price_dialog').modal('show')");
endif;

