<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Form;
use Jet\MVC_View;
use JetShop\Shops;
use JetShop\Parametrization_Group;

/**
 * @var MVC_View   $this
 * @var Parametrization_Group $new_group
 * @var Form $form
 */
$new_group = $this->getRaw('new_group');

$form = $new_group->getAddForm();
$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 1
]);

echo $this->render('lj_start');
	?><br/><?php
	echo $form->start();

		echo $form->field('is_active');
		echo $form->field('allow_display');
		echo $form->field('allow_filter');
		echo $form->field('allow_compare');

		foreach(Shops::getList() as $shop):
			$shop_key= $shop->getKey();
			$shop_data = $new_group->getShopData($shop);

			echo $shop_data->renderShopDataBlock_start();
				echo $form->field('/shop_data/'.$shop_key.'/is_active');
				echo $form->field('/shop_data/'.$shop_key.'/label');
				echo $form->field('/shop_data/'.$shop_key.'/description');
			echo $shop_data->renderShopDataBlock_end();
		endforeach;

	echo $form->end();

echo $this->render('lj_end');
