<?php
namespace JetShop;

use Jet\Mvc_View;
use Jet\UI;
use Jet\Tr;
use Jet\Form;

/**
 * @var Mvc_View   $this
 * @var Form $upload_form
 * @var Images_ShopDataInterface $shop_data
 */
$image_class = $this->getString('image_class');
$shop_id = $this->getString('shop_id');
$shop_data = $this->getRaw('shop_data');

$entity = $shop_data->getImageEntity();

$upload_form = $shop_data->getImageUploadForm( $image_class );

if($upload_form) {
	$image_field = $upload_form->field('image');
	$image_field->input()
		->addJsAction('onchange', "Images.uploadImage(this.form.id, '{$entity}', '{$image_class}', '{$shop_id}')");
}
?>

<td style="padding: 10px;">
	<legend class="sub"><?=$this->getRaw('title')?></legend>

	<div id="image_<?=$entity?>_<?=$image_class?>_<?=$shop_id?>">
		<?=$this->render('imageWidget/image')?>
	</div>


	<?php if($upload_form && !$upload_form->getIsReadonly()): ?>
		<?=$upload_form->start()?>
		<div class="btn btn-light btn-upload">
			<?=UI::icon('upload')?>&nbsp;<span><?=Tr::_('Select and upload image', [], Tr::COMMON_NAMESPACE)?></span>
			<?=$image_field->input()?>
		</div>
		<?=$upload_form->end()?>
	<?php endif; ?>
</td>


