<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\OrderDispatch\Overview;


use Jet\Locale;
use Jet\MVC_View;
use JetApplication\OrderDispatch;

/**
 * @var MVC_View $this
 * @var OrderDispatch $item
 */

$item = $this->getRaw('item');
?>
<?=Locale::date( $item->getDispatchDate() );?>

