<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\OrderDispatch\Overview;


use Jet\MVC_View;
use JetApplication\Application_Service_Admin;
use JetApplication\Application_Service_Admin_EShopEntity_Listing;
use JetApplication\OrderDispatch;

/**
 * @var MVC_View $this
 * @var Application_Service_Admin_EShopEntity_Listing $listing
 * @var OrderDispatch $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');

echo Application_Service_Admin::Order()->renderItemName( $item->getOrderId() );
