<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\OrderDispatch\Overview;


use Jet\MVC_View;
use JetApplication\WarehouseManagement_Warehouse;
use JetApplication\OrderDispatch;

/**
 * @var MVC_View $this
 * @var OrderDispatch $item
 */

$item = $this->getRaw('item');
?>
<?=WarehouseManagement_Warehouse::getScope()[$item->getWarehouseId()]?>
