<?php
namespace JetApplicationModule\Admin\DeliveryNotes;

use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View $this
 * @var DeliveryNote[] $invoices
 */

$invoices = $this->getRaw('invoices');
if(!count($invoices)) {
	return;
}

$price_formatter = Admin_Managers::PriceFormatter();
?>
<table class="table table-striped">
	<thead>
	<tr>
		<th style="width: 200px"></th>
		<th style="width: 200px"><?=Tr::_('Number')?></th>
		<th style="width: 200px"><?=Tr::_('Date')?></th>
		<th style="width: 200px"><?=Tr::_('Total')?></th>
		<th></th>
	</tr>
	</thead>
	<tbody>
	<?php foreach($invoices as $invoice): ?>
		<tr>
			<td><?=Tr::_('Delivery note')?></td>
			<td>
				<?php if(!$invoice->isCancelled()): ?>
					<a href="<?=Main::getEditUrl( $invoice->getId() );?>"><?=$invoice->getNumber();?></a>
				<?php else: ?>
					<a href="<?=Main::getEditUrl( $invoice->getId() );?>" style="text-decoration: line-through;color: red;"><?=$invoice->getNumber();?></a>
				<?php endif; ?>
			</td>
			<td>
				<?=Locale::date(  $invoice->getInvoiceDate() ); ?>
			</td>
			<td>
				<?php if($invoice->hasVAT()):
					echo $price_formatter->formatWithCurrency_WithVAT($invoice->getCurrency(), $invoice->getTotal());
				else:
					echo $price_formatter->formatWithCurrency_WithoutVAT($invoice->getCurrency(), $invoice->getTotal());
				endif; ?>
			</td>
			<td></td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
