<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ReturnsOfGoods;


use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use Jet\UI_dialog;
use Jet\MVC_View;

use JetApplication\Complaint;
use JetApplication\Order;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Complaint $complaint
 */

$complaint = $this->getRaw('item');
if(!$complaint->isEditable()) {
	return;
}
$order = Order::get( $complaint->getOrderId() );

$form = $this->getRaw('money_refund_form');

$dialog = new UI_dialog( 'money_refund_dialog', Tr::_('Money refundation'), UI_dialog::SIZE_LARGE );

$form->field('internal_summary')->input()->addCustomCssStyle("height:400px");
$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 8
]);
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 4
]);

$form->field('amount_to_be_refunded')->input()->setCustomRenderer( function() use ($form, $order, $complaint) {
	$field = $form->field('amount_to_be_refunded');
	
	if($order) {
		$currency = $order->getCurrency();
	} else {
		$currency = $complaint->getEshop()->getDefaultPricelist()->getCurrency();
	}
	?>
	<div style="display: grid;align-items: center;gap: 5px;grid-template-columns: auto 1fr auto;">
		<div><?=$currency->getSymbolLeft_WithVAT()?></div>
		<?=$field->input()->renderByView()?>
		<div><?=$currency->getSymbolRight_WithVAT()?></div>
	</div>
	<?php
	
} );


echo $dialog->start();
echo $form->start();

foreach($form->getFields() as $field) {
	echo $field;
}

echo $dialog->footer();
	echo UI::button_delete(Tr::_('Place money refundation request'))->setType(UI_button::TYPE_SUBMIT);
echo $form->end();
echo $dialog->end();
