<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ImageManager;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use Jet\UI;
use JetApplication\Application_Service_Admin;
use JetApplication\EShop;
use JetApplication\EShopEntity_HasImageGallery_Interface;

/**
 * @var MVC_View $this
 * @var EShop $eshop
 * @var Form $images_form
 * @var Form $image_delete_form
 * @var EShopEntity_HasImageGallery_Interface $item
 */

$image_manager = Application_Service_Admin::Image();

$editable = $this->getBool('editable');

$item = $this->getRaw('item');


foreach( $item->getImages() as $image):
	$id = $image->getId();

	$url = $image_manager->getImageGalleryImageURL( $image );
	$thb_url = $image_manager->getImageGalleryImageThumbnailUrl($image, 150,150);
	
	if($editable):
	?>

	<div style="width: 180px;height: 250px;float: left;margin: 5px;border: 1px solid #c9c9c9;border-radius: 5px;background-color:#ffffff;">
		<div class="image-thumbnail" data-image="<?=$id?>" style="background-image: url(<?=$thb_url?>);width: 160px;height: 160px;position: relative">
			<div style="position: absolute;bottom: 5px;right: 5px;">
				<input type="checkbox" value="<?=$id?>" data-url="<?=$url?>" class="select_image_checkbox"/>
			</div>
		</div>
		<div style="font-size: 12px;padding-left:8px;padding-right:8px;line-height: 14px; height: 2.4lh;overflow: hidden;word-wrap: break-word;text-align: center" title="<?=$image->getImageFileName()?>">
			<?=$image->getImageFileName()?>
		</div>
		<div style="width: 180px;padding: 5px;display: grid;grid-template-columns: 30px 30px 1fr; gap: 2px;align-items: center">
			<div>
				<?=UI::icon('exchange-alt')?>
			</div>
			<div>
				<a href="<?=$url?>" download target="_blank"><?=UI::icon('download')->setTitle(Tr::_('Download image'))?></a>
			</div>
			<div style="padding-right: 5px; text-align: right">
				<a href="javascript:ImageGalleryHandler.deleteImage('<?=$id?>', '<?=$url?>');"><?=UI::icon('trash')->setTitle(Tr::_('Delete image'))?></a>
			</div>
		</div>
	</div>
	<?php
	else:
    ?>
	<div style="width: 180px;height: 210px;float: left;margin: 5px;border: 1px solid #c9c9c9;border-radius: 5px;background-color:#ffffff;">
		<div class="image-thumbnail" data-image="<?=$id?>" style="background-image: url(<?=$thb_url?>);width: 160px;height: 160px;position: relative">
		</div>
		<div style="width: 180px;height: 55px;padding: 5px;">
			<table style="width: 100%">
				<tr>
					<td style="width: 30px;">
					</td>
					<td style="width: 30px;">
						<a href="<?=$url?>" download target="_blank"><?=UI::icon('download')->setTitle(Tr::_('Download image'))?></a>
					</td>
					<td style="padding-right: 5px; text-align: right">
					</td>
				</tr>
			</table>
		</div>
	</div>

	<?php
	endif;
endforeach; ?>

