<?php
namespace JetApplicationModule\Shop\ReturnsOfGoods;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Order;
use JetApplication\Product_ShopData;
use JetApplication\ReturnOfGoods;

/**
 * @var MVC_View   $this
 * @var Order $order
 */

$order = $this->getRaw('order');

$showProduct = function( Product_ShopData $product ) use ($order) {
	
	$returns_of_goods = ReturnOfGoods::getByOrderItem( $order, $product->getId() );
	?>
	<tr>
		<td>
			<?php if(count($returns_of_goods)): ?>
				<?php foreach($returns_of_goods as $return): ?>
					<a href="<?=$return->getURL()?>"><?=$return->getNumber()?></a><br>
				<?php endforeach; ?>
				<br>
				<?=UI::button( Tr::_('Create next return of goods request') )->setUrl(Http_Request::currentURL(['product_id'=>$product->getId()]))->setClass(UI_button::CLASS_LINK)?>
			<?php else: ?>
				<?=UI::button( Tr::_('Create return of goods request') )->setUrl(Http_Request::currentURL(['product_id'=>$product->getId()]))->setClass(UI_button::CLASS_INFO)?>
			<?php endif; ?>
		</td>
		<td>
			<?php if($product->getImg(0)): ?>
				<a href="<?=$product->getURL()?>"><img src="<?=$product->getImgThumbnailUrl(0, 150, 150)?>"></a>
			<?php endif; ?>
		</td>
		<td><a href="<?=$product->getURL()?>"><?=$product->getName()?></a></td>
	</tr>
	<?php
};
?>
<table class="table table-striped">
	<thead>
	<tr>
		<th style="width: 220px;"></th>
		<th style="width: 150px;"></th>
		<th></th>
	</tr>
	</thead>
	<?php foreach($order->getPhysicalProductOverview() as $item):
		$showProduct( $item->getProduct() );
	endforeach; ?>
</table>
