<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Complaints;


use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Application_Service_EShop;
use JetApplication\Product_EShopData;

/**
 * @var MVC_View   $this
 * @var Form $enter_problem_form
 * @var Product_EShopData $product
 */

$enter_problem_form = $this->getRaw('enter_problem_form');
$product = $this->getRaw('product');
$enter_problem_form->field('problem_description')->input()->addCustomCssStyle('width:100%;height:300px');

echo Application_Service_EShop::CustomerSection()?->showMenu('complaints');
?>
<div class="customer-section-container">
<?=$enter_problem_form->start()?>
	
	<div class="card">
		<div class="card-body">
			<h5 class="card-title"><?=Tr::_('New complaint')?></h5>


			<div class="complaints-product">
				<div>
					<?php if($product->getImage(0)): ?>
						<a href="<?=$product->getURL()?>"><img src="<?=$product->getImageThumbnailUrl(0, 50, 50)?>"></a>
					<?php endif; ?>
				</div>
				<div><a href="<?=$product->getURL()?>"><?=$product->getName()?></a></div>
			</div>

			<div style="justify-content:left;display: grid;grid-template-columns: auto auto;gap: 10px;align-items: center;margin: 10px;">
				<?=$enter_problem_form->field('delivery_of_claimed_goods_code')?>
				<?=$enter_problem_form->field('complaint_type_code')?>
				<?=$enter_problem_form->field('preferred_solution_code')?>
			</div>

			<div>
				<?=$enter_problem_form->field('problem_description')?>
			</div>
			<br>
			<div>
				<?=UI::button( Tr::_('Continue') )->setType(UI_button::TYPE_SUBMIT)->setClass(UI_button::CLASS_PRIMARY)?>
			</div>

		</div>
	</div>

<?=$enter_problem_form->end()?>
</div>
