<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\Content\Email\Templates;

use Jet\MVC_View;
use JetApplication\EMail_Layout;
use JetApplication\EMail_TemplateText;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 
 * @var EMail_TemplateText $item
 */

$item = $this->getRaw('item');

if(EShops::isMultiEShopMode()):
	foreach( EShops::getList() as $eshop):
		$sd = $item->getEshopData( $eshop );
		
		echo $eshop->getName().': '.(EMail_Layout::getScope()[$sd->getLayoutId()]??'').'<br>';
	endforeach;
else:
	$sd = $item->getEshopData( EShops::getCurrent() );
	
	echo EMail_Layout::getScope()[$sd->getLayoutId()]??'';
endif;
