<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Content\Email\Templates;


use Jet\MVC_View;
use JetApplication\EMail_Layout;
use JetApplication\EMail_TemplateText;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 
 * @var EMail_TemplateText $item
 */

$item = $this->getRaw('item');

if(EShops::isMultiEShopMode()):
	foreach( EShops::getList() as $eshop):
		$sd = $item->getEshopData( $eshop );
		
		echo $eshop->getName().': '.(EMail_Layout::getScope()[$sd->getLayoutId()]??'').'<br>';
	endforeach;
else:
	$sd = $item->getEshopData( EShops::getCurrent() );
	
	echo EMail_Layout::getScope()[$sd->getLayoutId()]??'';
endif;
