<?php
namespace JetApplicationModule\Admin\Customers;

use Jet\MVC_View;
use JetApplication\Customer_Address;
use JetApplication\Shops_Shop;

/**
 * @var MVC_View $this
 * @var string $code
 * @var Customer_Address $address
 * @var Shops_Shop $shop
 */

$shop = $this->getRaw('shop');
$address = $this->getRaw('address');
?>
<?php if($address->getCompanyName()): ?>
	<?=$address->getCompanyName()?><br>
	<?=$address->getCompanyId()?><br>
	<?=$address->getCompanyVatId()?><br>
<?php endif?>

<?=$address->getFirstName()?> <?=$address->getSurname()?><br>
<?=$address->getAddressStreetNo()?><br/>
<?=$address->getAddressZip()?> <?=$address->getAddressTown()?><br>
<?=$address->getAddressCountry()?>

