<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Customers;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Customer_Address;
use JetApplication\DataList;
use JetApplication\EShop;

/**
 * @var MVC_View $this
 * @var string $code
 * @var Customer_Address $address
 * @var EShop $eshop
 */

$eshop = $this->getRaw('eshop');
$address = $this->getRaw('address');
?>
<?php if($address->getCompanyName()): ?>
	<?=$address->getCompanyName()?><br>
	<?php if($address->getCompanyId()): ?>
	<?=Tr::_('Company ID:')?> <?=$address->getCompanyId()?><br>
	<?php endif; ?>
	<?php if($address->getCompanyVatId()): ?>
	<?=Tr::_('VAT ID:')?> <?=$address->getCompanyVatId()?><br>
	<?php endif; ?>
<?php endif?>

<?=$address->getFirstName()?> <?=$address->getSurname()?><br>
<?=$address->getAddressStreetNo()?><br/>
<?=$address->getAddressZip()?> <?=$address->getAddressTown()?><br>
<?=DataList::countries()[$address->getAddressCountry()]??''?>

