<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Carrier\Zasilkovna;


use Jet\Form;
use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\UI;
use Jet\UI_messages;

/**
 * @var MVC_View $this
 * @var Form $form
 */

$form = $this->getRaw('form');

$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 10
]);
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 2
]);


foreach( UI_messages::get(context: 'CC') as $message ):
	echo $message;
endforeach;

echo $form->getCommonMessage();

echo $form->start();

echo $form->field('API_key');
echo $form->field('API_password');
echo $form->field('sender_id');
echo $form->field('eshop_id');
echo $form->field('allow_public_tracking');
echo $form->field('tracking_API_keys');
echo $form->field('SOAP_API_URL');
echo $form->field('labels_format');

?>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<?=UI::button_save()?>
	</div>
</div>
<?php
echo $form->end();