<?php
namespace JetApplicationModule\Admin\Marketing\DeliveryFeeDiscount;

use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );


echo $form->field( 'relevance_mode' );
echo $form->field( 'delivery_method_id' );
echo $form->field( 'discount_percentage' );
echo $form->field( 'amount_limit' );
echo $form->field( 'promo_html' );

