<?php
namespace JetApplicationModule\Admin\Marketing\ProductStickers;

use Jet\MVC_View;
use Jet\Form;
use JetApplication\Marketing_ProductSticker;


/**
 * @var MVC_View $this
 * @var Form $form
 * @var Marketing_ProductSticker $item
 */
$form = $this->getRaw('form');
$item = $this->getRaw('item');

echo $form->field( 'priority' );
echo $form->field( 'relevance_mode' );

echo $form->field( 'color_text' );
echo $form->field( 'color_background' );
echo $form->field( 'priority' );
echo $form->field( 'text' );


