<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Marketing\ProductStickers;


use Jet\MVC_View;
use Jet\Form;
use JetApplication\Marketing_ProductSticker;


/**
 * @var MVC_View $this
 * @var Form $form
 * @var Marketing_ProductSticker $item
 */
$form = $this->getRaw('form');
$item = $this->getRaw('item');

echo $form->field( 'priority' );
echo $form->field( 'relevance_mode' );

echo $form->field( 'color_text' );
echo $form->field( 'color_background' );
echo $form->field( 'priority' );
echo $form->field( 'text' );


