<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Products;


use Jet\Locale;
use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;

use Jet\UI;
use Jet\UI_button;
use JetApplication\Application_Service_Admin;
use JetApplication\Availabilities;
use JetApplication\EShops;
use JetApplication\Pricelists;
use JetApplication\Product_Availability;
use JetApplication\Product_PriceHistory;
use JetApplication\Product;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Product $item
 *
 */
$item = $this->getRaw('item');
$form = $this->getRaw('form');
$editable = !$form->getIsReadonly();

if($form->fieldExists('kind_of_product_id')) {
	$kind_id_field = $form->field('kind_of_product_id');
	
	$kind_id_field->input()->setCustomRenderer(function() use ($kind_id_field) {
		?>
		<div style="display:none;">
			<?=$this->renderByView()?>
		</div>
		<?=Application_Service_Admin::KindOfProduct()->renderSelectWidget(
			on_select: "document.getElementById('{$kind_id_field->getId()}').value=selected_item.id",
			selected_kind_of_product_id: $kind_id_field->getValue()?:0
		);?>
		<?php
	});
} else {
	$kind_id_field = '';
}

?>
<?php if( $form->fieldExists('internal_name_of_variant') ): ?>
	<?=$form->field('internal_name_of_variant')?>
<?php endif; ?>

<?=$kind_id_field?>

<?=$form->field( 'creation_in_progress' )?>
<?=$form->field( 'archived' )?>

<?=$form->field('ean')?>
<?=$form->field('brand_id')?>
<?=$form->field('supplier_id')?>
<?=$form->field('supplier_code')?>
<?=$form->field('delivery_class_id')?>

<div class="form-group row">
	<label class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?=Tr::_('Allow to order when sold out')?></label>
	<div class="col-md-8">
		<?php foreach(EShops::getListSorted() as $eshop):
			$field = $form->field('/eshop_data/'.$eshop->getKey().'/allow_to_order_when_sold_out');
			$field->setLabel( UI::flag($eshop->getLocale()).' '.$eshop->getName() );
			$field->setDoNotTranslateLabel( true );
		
			echo $field->input();
		endforeach; ?>
	</div>
</div>

<?php if(
	$item->isPhysicalProduct() &&
	$item->isRegular()
): ?>

<hr>
<?=$form->field('is_sale')?>
<?=$form->field('non_sale_product_id')?>

<div class="form-group row">
	<label class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?=Tr::_('Non-sale product relation:')?></label>
	<div class="col-md-8">
		<?=Application_Service_Admin::Product()->renderSelectWidget(
				on_select: "$('#{$form->field('non_sale_product_id')->getId()}').val(selected_item.id)",
				selected_product_id: $item->getNonSaleProductId(),
				name: 'non_sale_product_select'
		)?>
	</div>
</div>
<?=$form->field('deactivate_after_sell_out')?>

<?php endif; ?>

<hr>

<div class="form-group row">
	<label class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?=Tr::_('Price:')?></label>
	<div class="col-md-8">
		<?php foreach( Pricelists::getList() as $pricelist):
			$price = $item->getPriceEntity($pricelist);
			?>
		
			<div>
				<div class="card card-body">
					<?=Application_Service_Admin::PriceFormatter()->showPriceInfo( $price )?>
					
					<div style="padding: 10px;">
						<?=UI::button(Tr::_('Price history'))->setClass(UI_button::CLASS_LINK)->setOnClick("$('#price_history_{$pricelist->getCode()}').toggle();")?>
					</div>

					<div id="price_history_<?=$pricelist->getCode()?>" style="display: none">
						<table class="table table-striped">
							<?php foreach( Product_PriceHistory::get( $pricelist, $item->getId() ) as $hi): ?>
								<tr>
									<td nowrap=""><?=Locale::date( $hi->getDateTime() )?></td>
									<td nowrap=""><?=Locale::time( $hi->getDateTime() )?></td>
									<td style="width: 100%"><?=Application_Service_Admin::PriceFormatter()->formatWithCurrency( $pricelist, $hi->getPrice() )?></td>
								</tr>
							<?php endforeach; ?>
						</table>
					</div>
					
				</div>
				
				<br><br>
				
				
			</div>
		<?php endforeach; ?>
	</div>
</div>
<hr>
<div class="form-group row">
	<label class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?=Tr::_('Availability:')?></label>
	<div class="col-md-8">
		<?php foreach( Availabilities::getList() as $availability):
			$product_availability = Product_Availability::get( $availability, $item->getId() );
			?>
			<fieldset>
				<legend class="sub"><?=$availability->getName()?></legend>
				
				<table class="table table-striped">
					<tr>
						<td style="width: 200px;"><?=Tr::_('Available units:');?></td>
						<td><b><?=Locale::float( $product_availability->getNumberOfAvailable() )?> <?=$item->getKindOfProduct()?->getMeasureUnit()?->getName()?></b></td>
					</tr>
					<tr>
						<td><?=Tr::_('Length of delivery:');?></td>
						<td><b><?=Locale::int( $product_availability->getLengthOfDelivery() )?></b></td>
					</tr>
					<tr>
						<td><?=Tr::_('Available from:');?></td>
						<td><?=Locale::date( $product_availability->getAvailableFrom() )?></td>
					</tr>
				</table>

			</fieldset>
			<br><br>
		<?php endforeach; ?>

	</div>
</div>

<?php if(
	$item->isPhysicalProduct() &&
	Application_Service_Admin::WarehouseManagementOverview()
): ?>
<hr>
<div class="form-group row">
	<label class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?=Tr::_('Stock status:')?></label>
	<div class="col-md-8">
		<?=Application_Service_Admin::WarehouseManagementOverview()?->renderProductStockStatusInfo( $item )?>
	</div>
</div>
<?php endif;

