<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Catalog\Products;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Product;

/**
 * @var MVC_View   $this
 * @var Product $product
 */

$product = $this->getRaw('item');
$form = $this->getRaw('form');
$locale_str = $this->getRaw('locale_str');

?>
<fieldset>
	<?=$form->field('/description/'.$locale_str.'/name')?>
	<?php if($form->fieldExists('/description/'.$locale_str.'/variant_name')): ?>
		<?=$form->field('/description/'.$locale_str.'/variant_name')?>
	<?php endif; ?>
	<?=$form->field('/description/'.$locale_str.'/description')?>
	<?=$form->field('/description/'.$locale_str.'/short_description')?>
</fieldset>

<fieldset>
	<legend class="sub"><?=Tr::_('SEO')?></legend>
	<?=$form->field('/description/'.$locale_str.'/seo_title')?>
	<?=$form->field('/description/'.$locale_str.'/seo_description')?>
	<?=$form->field('/description/'.$locale_str.'/seo_keywords')?>
</fieldset>
