<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;

use Jet\UI;
use Jet\UI_dialog;
use JetApplication\Availabilities;
use JetApplication\Pricelists;
use JetApplication\Product;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Product $item
 * @var Form $set_price_form
 * @var Form $set_availability_form
 *
 */

$set_price_form = $this->getRaw('set_price_form');
$set_availability_form = $this->getRaw('set_availability_form');

if($set_price_form):
	
	$set_price_dialog = UI::dialog('set_price_dialog', Tr::_('Set price'), UI_dialog::SIZE_DEFAULT );
	
	echo $set_price_dialog->start();
	echo $set_price_form->start();
	
	foreach(Pricelists::getList() as $pricelist):
		?>
		<fieldset>
			<?php if(count(Pricelists::getList())>1): ?>
				<legend><?=$pricelist->getName()?> - <?=$pricelist->getCurrency()->getCode()?></legend>
			<?php endif; ?>
			<?php
			$field_name_prefix = '/'.$pricelist->getCode().'/';
			
			echo $set_price_form->field( $field_name_prefix.'vat_rate' );
			echo $set_price_form->field( $field_name_prefix.'price' );
			?>
		</fieldset>
	<?php endforeach;
	
	
	echo $set_price_dialog->footer();
	echo UI::button_save( Tr::_('Set') );
	echo $set_price_form->end();
	echo $set_price_dialog->end();
endif;



if($set_availability_form):
	$set_availability_dialog = UI::dialog('set_availability_dialog', Tr::_('Set price'), UI_dialog::SIZE_DEFAULT );
	
	echo $set_availability_dialog->start();
	echo $set_availability_form->start();
	
	foreach(Availabilities::getList() as $availability):
		?>
		<fieldset>
			<?php if(count(Availabilities::getList())>1): ?>
				<legend><?=$availability->getName()?></legend>
			<?php endif; ?>
			<?php
			$field_name_prefix = '/'.$availability->getCode().'/';
			
			echo $set_availability_form->field( $field_name_prefix.'available_from' );
			echo $set_availability_form->field( $field_name_prefix.'length_of_delivery' );
			?>
		</fieldset>
	<?php endforeach;
	
	echo $set_availability_dialog->footer();
	echo UI::button_save( Tr::_('Set') );
	echo $set_availability_form->end();
	echo $set_availability_dialog->end();

endif;