<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Products;


use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;

use Jet\UI;
use Jet\UI_dialog;
use JetApplication\Availabilities;
use JetApplication\Product;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Product $item
 * @var Form $set_price_form
 * @var Form $set_availability_form
 *
 */

$set_availability_form = $this->getRaw('set_availability_form');

if(!$set_availability_form):
	return;
endif;


$set_availability_dialog = UI::dialog('set_availability_dialog', Tr::_('Set price'), UI_dialog::SIZE_DEFAULT );

echo $set_availability_dialog->start();
echo $set_availability_form->start();

foreach(Availabilities::getList() as $availability):
	?>
	<fieldset>
		<?php if(count(Availabilities::getList())>1): ?>
			<legend><?=$availability->getName()?></legend>
		<?php endif; ?>
		<?php
		$field_name_prefix = '/'.$availability->getCode().'/';
		
		echo $set_availability_form->field( $field_name_prefix.'available_from' );
		echo $set_availability_form->field( $field_name_prefix.'length_of_delivery' );
		?>
	</fieldset>
<?php endforeach;

echo $set_availability_dialog->footer();
echo UI::button_save( Tr::_('Set') );
echo $set_availability_form->end();
echo $set_availability_dialog->end();
