<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\Locale;
use JetApplication\Admin_Managers;
use JetApplication\Shops_Shop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Shops_Shop $shop
 * @var Product $item
 */
$form = $this->getRaw('form');
$item = $this->getRaw('item');
$shop = $this->getRaw('shop');
$shop_key = $shop->getKey();

$form->field('/shop_data/'.$shop_key.'/description')->input()->addCustomCssStyle('height:600px');
?>
<fieldset>
	<legend class="sub"><?=Tr::_('Main data')?></legend>

	
	<?=$form->field('/shop_data/'.$shop_key.'/allow_to_order_when_sold_out')?>
	
	<?=$form->field('/shop_data/'.$shop_key.'/name')?>
	<?php if($form->fieldExists('/shop_data/'.$shop_key.'/variant_name')): ?>
	<?=$form->field('/shop_data/'.$shop_key.'/variant_name')?>
	<?php endif; ?>
	<?=$form->field('/shop_data/'.$shop_key.'/description')?>
	<?=$form->field('/shop_data/'.$shop_key.'/short_description')?>
</fieldset>

<fieldset>
	<legend class="sub"><?=Tr::_('SEO')?></legend>
	<?=$form->field('/shop_data/'.$shop_key.'/seo_title')?>
	<?=$form->field('/shop_data/'.$shop_key.'/seo_description')?>
	<?=$form->field('/shop_data/'.$shop_key.'/seo_keywords')?>
</fieldset>

<?php foreach($shop->getPricelists() as $pricelist): ?>

<fieldset>
	<legend class="sub"><?=Tr::_('Price')?> - <?=$pricelist->getName()?></legend>
	<?php if( $item->isPhysicalProduct() ): ?>
	<div class="row">
		<label class="col-md-2 col-form-label" style="font-weight: bolder;font-size: 18px;margin-top: -3px;"><?=Tr::_('VAT rate:')?></label>
		<div class="col-md-8" style="font-weight: bolder;font-size: 20px;">
			<?=$item->getVatRate( $pricelist )?>%
		</div>
	</div>
	<?php endif; ?>
	
	<div class="row">
		<label class="col-md-2 col-form-label" style="font-weight: bolder;font-size: 20px;margin-top: -3px;"><?=Tr::_('Price:')?></label>
		<div class="col-md-8" style="font-weight: bolder;font-size: 25px;"><?=Admin_Managers::PriceFormatter()->formatWithCurrency( $pricelist->getCurrency(), $item->getShopData($shop)->getPrice( $pricelist ) )?></div>
	</div>
	
	<?php if($item->getShopData($shop)->getDiscountPercentage( $pricelist )>0): ?>
		<div class="row" style="opacity: 0.5">
			<label class="col-md-2 col-form-label" style="font-weight: bolder;font-size: 15px;margin-top: -3px;"><?=Tr::_('Discount:')?></label>
			<div class="col-md-8" style="font-weight: bolder;font-size: 20px;"><?=$item->getShopData($shop)->getDiscountPercentage( $pricelist );?>%</div>
		</div>
	<?php endif; ?>
	
	<div class="row">
		<div class="col-md-2 col-form-label" style="font-weight: bolder;"></div>
		<div class="col-md-8">
			<b><?=Tr::_('Price history:')?></b><br>
			
			<table class="table table-striped">
			<?php foreach($item->getPriceHistory( $pricelist ) as $hi): ?>
			<tr>
				<td style="width: 150px;"><?=Locale::dateAndTime( $hi->getDateTime() )?></td>
				<td><?=Admin_Managers::PriceFormatter()->formatWithCurrency( $pricelist->getCurrency(), $hi->getPrice() )?></td>
			</tr>
			<?php endforeach; ?>
			</table>
		</div>
	</div>
</fieldset>
<?php endforeach; ?>


<?php foreach($shop->getAvailabilities() as $availability): ?>
	<fieldset>
		<legend class="sub"><?=Tr::_('Availability')?> - <?=$availability->getName()?></legend>
		
		<div class="row">
			<div class="col-md-2 col-form-label" style="font-weight: bolder;"></div>
			<div class="col-md-8">
			
				<table class="table table-striped">
				<tr>
					<td style="width: 200px;"><?=Tr::_('Available units:');?></td>
					<td><b><?=Locale::float( $item->getShopData($shop)->getNumberOfAvailable($availability) )?> <?=$item->getKindOfProduct()?->getMeasureUnit()?->getName()?></b></td>
				</tr>
				<tr>
					<td><?=Tr::_('Length of delivery:');?></td>
					<td><b><?=Locale::int( $item->getShopData($shop)->getLengthOfDelivery($availability) )?></b></td>
				</tr>
				<tr>
					<td><?=Tr::_('Available from:');?></td>
					<td><?=Locale::date( $item->getShopData($shop)->getAvailableFrom($availability) )?></td>
				</tr>
			</table>
			</div>
		</div>
	
	</fieldset>
<?php endforeach; ?>

