<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Products;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\EShop;
use JetApplication\Product;

/**
 * @var MVC_View   $this
 * @var Product $product
 * @var EShop $eshop
 */

$product = $this->getRaw('item');
$form = $this->getRaw('form');
$eshop = $this->getRaw('eshop');
$eshop_key = $eshop->getKey();

?>
<fieldset>
	<?=$form->field('/eshop_data/'.$eshop_key.'/name')?>
	<?php if($form->fieldExists('/eshop_data/'.$eshop_key.'/variant_name')): ?>
		<?=$form->field('/eshop_data/'.$eshop_key.'/variant_name')?>
	<?php endif; ?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/description')?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/short_description')?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/video_URLs')?>
</fieldset>

<fieldset>
	<legend class="sub"><?=Tr::_('SEO')?></legend>
	<?=$form->field('/eshop_data/'.$eshop_key.'/seo_title')?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/seo_description')?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/seo_keywords')?>
</fieldset>