<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\Locale;
use JetApplication\Admin_Managers;
use JetApplication\Shops_Shop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Shops_Shop $shop
 * @var Product $item
 */
$form = $this->getRaw('form');
$item = $this->getRaw('item');
$shop = $this->getRaw('shop');
$shop_key = $shop->getKey();

$form->field('/shop_data/'.$shop_key.'/description')->input()->addCustomCssStyle('height:600px');
?>
<fieldset>
	<legend class="sub"><?=Tr::_('Main data')?></legend>
	
	<?=$form->field('/shop_data/'.$shop_key.'/name')?>
	<?php if($form->fieldExists('/shop_data/'.$shop_key.'/variant_name')): ?>
	<?=$form->field('/shop_data/'.$shop_key.'/variant_name')?>
	<?php endif; ?>
	<?=$form->field('/shop_data/'.$shop_key.'/description')?>
	<?=$form->field('/shop_data/'.$shop_key.'/short_description')?>
</fieldset>

<fieldset>
	<legend class="sub"><?=Tr::_('SEO')?></legend>
	<?=$form->field('/shop_data/'.$shop_key.'/seo_title')?>
	<?=$form->field('/shop_data/'.$shop_key.'/seo_description')?>
	<?=$form->field('/shop_data/'.$shop_key.'/seo_keywords')?>
</fieldset>

<fieldset>
	<legend class="sub"><?=Tr::_('Price')?></legend>
	
	<?=$form->field('/shop_data/'.$shop_key.'/vat_rate')?>
	<?=$form->field('/shop_data/'.$shop_key.'/standard_price')?>
	<?=$form->field('/shop_data/'.$shop_key.'/price')?>
	
	<div class="row">
		<label class="col-md-2 col-form-label" style="font-weight: bolder;font-size: 20px;margin-top: -3px;"><?=Tr::_('Price:')?></label>
		<div class="col-md-8" style="font-weight: bolder;font-size: 25px;"><?=Admin_Managers::PriceFormatter()->formatWithCurrency( $shop, $item->getShopData($shop)->getPrice() )?></div>
	</div>
	
	<?php if($item->getShopData($shop)->getDiscountPercentage()>0): ?>
		<div class="row" style="opacity: 0.5">
			<label class="col-md-2 col-form-label" style="font-weight: bolder;font-size: 15px;margin-top: -3px;"><?=Tr::_('Discount:')?></label>
			<div class="col-md-8" style="font-weight: bolder;font-size: 20px;"><?=$item->getShopData($shop)->getDiscountPercentage();?>%</div>
		</div>
	<?php endif; ?>
	
	<div class="row">
		<div class="col-md-2 col-form-label" style="font-weight: bolder;"></div>
		<div class="col-md-8">
			<b><?=Tr::_('Price history:')?></b><br>
			
			<table class="table table-striped">
			<?php foreach($item->getShopData($shop)->getPriceHistory() as $hi): ?>
			<tr>
				<td style="width: 150px;"><?=Locale::dateAndTime( $hi->getDateTime() )?></td>
				<td><?=Admin_Managers::PriceFormatter()->formatWithCurrency( $shop, $hi->getPrice() )?></td>
			</tr>
			<?php endforeach; ?>
			</table>
		</div>
	</div>
	
	
</fieldset>
<fieldset>
	<legend class="sub"><?=Tr::_('Availability')?></legend>
	
	<?=$form->field('/shop_data/'.$shop_key.'/in_stock_qty')?>
	<?=$form->field('/shop_data/'.$shop_key.'/length_of_delivery')?>
	<?=$form->field('/shop_data/'.$shop_key.'/available_from')?>
	
</fieldset>