<?php
namespace JetApplicationModule\Admin\Orders;

use Jet\Form;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

use Jet\MVC_View;


/**
 * @var MVC_View $this
 * @var Form $form
 * @var Order $order
 */

$order = $this->getRaw('order');
if(!$order->isEditable()) {
	return;
}

echo UI::button(Tr::_('Change delivery method'))
	->setClass(UI_button::CLASS_SECONDARY)
	->setIcon('truck-moving')
	->addCustomCssClass('dropdown-item')
	->setOnClick("$('#change_delivery_method_dialog').modal('show');");
	