<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Orders;


use Jet\Form;
use Jet\Mvc_View;
use JetApplication\Order;

/**
 * @var Mvc_View $this
 * @var Order $order
 * @var Form $form
 */
$order = $this->getRaw( 'order' );

$form = $this->getRaw('change_delivery_method_form');
if(!$form) {
	return;
}


foreach($form->getFields() as $field) {
	echo $field;
}
