<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use JetApplication\ProductListing;
use JetApplication\Property_Options_Option_ShopData;
use JetApplication\Property_ShopData;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 * @var Property_ShopData $property
 * @var Property_Options_Option_ShopData[] $_options
 */

$listing = $this->getRaw('listing');

$initial_map = $listing->getInitialMap();
$filtered_map = $listing->getFilteredMap();

$property = $this->getRaw('property');
$option_ids = $initial_map->getPropertyOptionIds( $property->getId() );
if(!$option_ids) {
	return;
}

$all_property_options = $this->getRaw('property_options');

$options = [];
foreach($option_ids as $option_id) {
	$option_id = (int)$option_id;
	
	if(isset($all_property_options[$option_id])) {
		$options[$option_id] = $all_property_options[$option_id];
	}
	
}

if(!$options) {
	return;
}


$options_filter = $listing->getFilter()->getPropertyOptionsFilter();
$property_id = $property->getId();


?>


<div style="display: grid;grid-template-columns: repeat(5, 1fr)">
	<?php foreach($options as $option_id=>$option):
		$selected = $options_filter->getOptionIsSelected( $property_id, $option_id );
		
		if(!$selected) {
			$count = $listing->getPropertyOptionCount( $property_id, $option_id );
			$disabled = $count==0;
		}
		
		if($selected):
		?>
		<div>
			<label><input
					type="checkbox"
					class="lf-option"
					data-property="<?=$property_id?>"
					value="<?=$option_id?>"
					checked
					onchange="listing.submitFilter()"
				> <?=$option->getFilterLabel()?></label>
		</div>
		<?php
		else:
			if($disabled):
				?>
				<div>
					<label><input
							type="checkbox"
							class="lf-option"
							data-property="<?=$property_id?>"
							value="<?=$option_id?>"
							disabled
							onchange="listing.submitFilter()"
						> <?=$option->getFilterLabel()?></label>
				</div>
			<?php
			else:
				?>
				<div>
					<label><input
							type="checkbox"
							class="lf-option"
							data-property="<?=$property_id?>"
							value="<?=$option_id?>"
							onchange="listing.submitFilter()"
						> <?=$option->getFilterLabel()?> (<?=$count?>)</label>
				</div>
			<?php
			endif;
	    endif;
	endforeach; ?>
</div>