<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\Marketing\LandingPage;


use Jet\MVC_View;
use JetApplication\Marketing_LandingPage;

/**
 * @var MVC_View   $this
 * @var Marketing_LandingPage $lp
 */
$lp = $this->getRaw('lp');


echo $lp->getLandingPageHtml();
