<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Catalog\Categories;


use Jet\Form;
use Jet\Form_Renderer;
use Jet\Locale;
use Jet\Tr;
use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\EShop;

/**
 * @var MVC_View   $this
 * @var Controller_Main $controller
 * @var Form $form
 */
$controller = $this->controller;

$form = $this->getRaw('form');

$category = $controller->getCurrentItem();

$form->renderer()->setDefaultLabelWidth([Form_Renderer::LJ_SIZE_MEDIUM=>2]);
$form->renderer()->setDefaultFieldWidth([Form_Renderer::LJ_SIZE_MEDIUM=>8]);

$editable = !$form->getIsReadonly();
?>
<?=$this->render('lj_start')?>
<br>

<?=Admin_Managers::Image()->commonImageManager( $category::getEntityType(), $category->getId() );?>

<?=$form->start();?>


<?php if($category->getDescriptionMode()):
		echo Admin_Managers::EntityEdit()->renderDescriptionBlocks(
			form: $form,
			renderer: function( Locale $locale ) use ($category, $form) : void {
				
				?>
					<fieldset>
						<div class="container-fluid">
						<?=$form->field('/description/'.$locale.'/name')?>
						<?=$form->field('/description/'.$locale.'/second_name')?>
						<?=$form->field('/description/'.$locale.'/description')?>
						</div>
					</fieldset>

					<fieldset>
						<legend class="sub"><?=Tr::_('SEO')?></legend>
						<div class="container-fluid">
						<?=$form->field('/description/'.$locale.'/seo_title')?>
						<?=$form->field('/description/'.$locale.'/seo_description')?>
						<?=$form->field('/description/'.$locale.'/seo_keywords')?>
						</div>
					</fieldset>
			<?php });
	else:
		echo Admin_Managers::EntityEdit()->renderShopDataBlocks(
			form: $form,
			renderer: function( EShop $eshop, string $eshop_key ) use ($category, $form) : void {
				?>
					<fieldset>
						<?=$form->field('/eshop_data/'.$eshop_key.'/name')?>
						<?=$form->field('/eshop_data/'.$eshop_key.'/second_name')?>
						<?=$form->field('/eshop_data/'.$eshop_key.'/description')?>
					</fieldset>

					<fieldset>
						<legend class="sub"><?=Tr::_('SEO')?></legend>
						<?=$form->field('/eshop_data/'.$eshop_key.'/seo_title')?>
						<?=$form->field('/eshop_data/'.$eshop_key.'/seo_description')?>
						<?=$form->field('/eshop_data/'.$eshop_key.'/seo_keywords')?>
					</fieldset>
			<?php });
	endif; ?>


<?=$form->end();?>


<?=$this->render('lj_end')?>






