<?php
namespace JetApplicationModule\Admin\Catalog\Categories;

use Jet\MVC_View;
use JetApplication\Category_ShopData;
use JetApplication\Shops;

/**
 * @var MVC_View   $this
 */

$category = Controller_Main::getCurrentCategory();

$image_classes = Category_ShopData::getImageClasses();

echo $this->render('lj_start');
	foreach(Shops::getListSorted() as $shop):
		echo $category->getShopData( $shop )->renderImageWidgets( $image_classes, !$category->getEditForm()->getIsReadonly() );
	endforeach;
echo $this->render('lj_end');