<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Catalog\Categories;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Admin_Managers;
use JetApplication\Product;

/**
 * @var MVC_View   $this
 * @var Controller_Main $controller
 */
$controller = $this->controller;
$category = $controller->getCurrentItem();
$form = $category->getEditForm();
$editable = !$form->getIsReadonly();
$auto_append = $category->getAutoAppendProducts();

$p_manager = Admin_Managers::Product();


echo $this->render('lj_start');
?>

	
	<?php if($editable): ?>
		<?php if(!$auto_append): ?>
		
			<div class="toolbar" style="display: grid;grid-template-columns: 150px 300px 1fr;align-items: center">
				<div style="padding-left: 20px;">
					<?=UI::icon('plus')?>
					<?=Tr::_('Add product:')?>
				</div>
				<div>
					<?=Admin_Managers::Product()->renderSelectWidget(
					on_select: "location='".Http_Request::currentURI()."&add_product='+selected_item.id",
					only_type_filter:[
							Product::PRODUCT_TYPE_REGULAR,
							Product::PRODUCT_TYPE_VARIANT_MASTER,
							Product::PRODUCT_TYPE_SET
					] )?>
				</div>
				<div style="padding-left: 40px;">
					<?=UI::button(Tr::_('Add products by filter'))
						->setClass(UI_button::CLASS_INFO)
						->setOnClick("$('#manual_product_append_area').toggle()");
					?>
					<?=UI::button(Tr::_('Remove all products'))
						->setUrl( Http_Request::currentURI(['action'=>'remove_all_products']) )
						->setClass(UI_button::CLASS_DANGER)
					?>
					<?=UI::button(Tr::_('Enable auto append mode'))
						->setUrl( Http_Request::currentURI(['action'=>'enable_auto_append_mode']) )
						->setClass(UI_button::CLASS_SUCCESS)
					?>
				</div>
			</div>

			
		<?php else: ?>
			<div class="toolbar">
					<?=UI::button(Tr::_('Disable auto append mode'))
						->setUrl( Http_Request::currentURI(['action'=>'disable_auto_append_mode']) )
						->setClass(UI_button::CLASS_DANGER)
					?>
			</div>

		<?php endif; ?>

	<div id="manual_product_append_area" class="card card-body" style="display: <?=$auto_append?'block':'none'?>">

		<div  id="toolbar" class="toolbar">
			<div style="padding-left: 20px;padding-right: 20px;"><b><?=Tr::_('Automatic product appending filter')?></b></div>
			<div>
				<?=UI::button_save( Tr::_('Save filter settings and append products') )->setOnClick("document.getElementById('{}').submit();")?>
			</div>
		</div>

		<?=Admin_Managers::ProductFilter()->renderFilterForm(); ?>
	</div>
	<?php endif; ?>

	


	<br>
	<div id="products_sort_area" class="card card-body">
		<?php foreach($category->getProductIds() as $p_id):

			$product = Product::load( $p_id );
			if(!$product) {
				continue;
			}
			?>
		<div
			class="sort_item"
			style="display: grid;grid-template-columns: 30px 200px 1fr 40px;align-items: center;gap: 5px;padding:5px;border-bottom: 1px solid #c9c9c9;background-color: #ffffff"
			data-id="<?=$p_id?>"
		>
			<div>
				<?php if($editable):
					echo UI::icon('arrows-v');
				endif; ?>
				
			</div>
			
			<div><?=$p_manager->renderActiveState($product)?></div>
			<div><?=$p_manager->showName($product)?></div>
			<div>
				<?php if($editable && !$auto_append): ?>
					<?=UI::button_delete(' ')
						->setUrl(Http_Request::currentURI(set_GET_params: ['remove_product'=>$p_id]))
					?>
				<?php endif; ?>
			</div>
		</div>
		<?php endforeach; ?>
	</div>
	<br><br><br><br><br>

<?php if($editable): ?>
	<script>
		const CategoryProducts = {
			init: () => {
				$('#products_sort_area')['sortable']({
					//revert: true,
					stop: function() {

						let items = [];

						$('#products_sort_area').find('.sort_item').each(function ( i, item ) {
							items.push( $(item).data('id') );
						});

						items = items.join(',');

						$.ajax({
							url: '<?=Http_Request::currentURI(['action'=>'sort_products'])?>&products='+items,
							success: function( response ) {
							}
						});
					}
				});

			}
		};

		CategoryProducts.init();
	</script>

<?php endif; ?>

<?php
echo $this->render('lj_end');

