<?php
namespace JetApplicationModule\Admin\Catalog\Categories;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Admin_Managers;
use JetApplication\Product;

/**
 * @var MVC_View   $this
 */
$category = Controller_Main::getCurrentCategory();
$form = $category->getEditForm();
$editable = !$form->getIsReadonly();

echo $this->render('lj_start');
?>
<div class="toolbar">
	<table>
		<tr>
			<td>
				<?=Tr::_('Kind of product:')?>
			</td>
			<td>
				<?php if(($kind_id=$category->getKindOfProductId())):
					?><?=Admin_Managers::KindOfProduct()->showName($kind_id)?><?php
				else:
					?><b><?=Tr::_('- kind of product is not set -')?></b><?php
				endif; ?>
			</td>
			<?php if($editable): ?>
			<td style="padding-left: 30px;">
				<?=Tr::_('Set kind of product:')?>
			</td>
			<td>
					<form action="<?=Http_Request::currentURI(['action'=>'change_kind_of_product'])?>" method="post">
						<input type="hidden" name="kind_of_product_id" id="kind_of_product_id" value="0"/>
						
						<table>
							<tr>
								<td style="width: 300px;"><?=Admin_Managers::KindOfProduct()->renderSelectWidget(
										"$('#kind_of_product_id').val(selected_item.id);",
										$category->getKindOfProductId()
									)?></td>
								<td><?=UI::button_save(Tr::_('Change')); ?></td>
							</tr>
						</table>
					</form>
			</td>
			<?php endif; ?>
		</tr>
	</table>
</div>

<fieldset>
	<legend><?=Tr::_('Products')?></legend>
	
	<?php if($editable): ?>
	<div class="toolbar">
		<table>
			<tr>
				<td>
					<?=UI::icon('plus')?>
					<?=Tr::_('Add product:')?>
				</td>
				<td><?=Admin_Managers::Product()->renderSelectWidget(
					on_select: "location='".Http_Request::currentURI()."&add_product='+selected_item.id",
					only_type_filter:[
							Product::PRODUCT_TYPE_REGULAR,
							Product::PRODUCT_TYPE_VARIANT_MASTER,
							Product::PRODUCT_TYPE_SET
					] )?></td>
			</tr>
		</table>
	</div>
	<?php endif; ?>
	
	<table class="table table-striped">
		<thead>
		<tr>
			<th style="width: 30px;"></th>
			<th></th>
		</tr>
		</thead>
		<?php
		$p_manager = Admin_Managers::Product();
		foreach($category->getProductIds() as $p_id): ?>
		<tr>
			<td>
				<?php if($editable): ?>
				<?=UI::button_delete(' ')->setUrl(Http_Request::currentURI(set_GET_params: ['remove_product'=>$p_id]))?>
				<?php endif; ?>
			</td>
			<td><?=$p_manager->showName($p_id)?></td>
		</tr>
		<?php endforeach; ?>
	</table>
	
</fieldset>

<?php
echo $this->render('lj_end');

