<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\Form;
use Jet\Http_Request;
use JetShop\Category;
use JetShop\Shops;

use Jet\UI_dataGrid;
use Jet\UI;
use Jet\UI_button;

use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Form         $filter_form
 * @var Listing      $listing
 */
$grid = $this->getRaw( 'grid' );
$router = $this->getController()->getControllerRouter();
$filter_form = $this->getRaw( 'filter_form' );
$listing = $this->getRaw('listing');

?>
<script>
	let productFilter = {
		addCategory: function( id )
		{
			let categories = document.getElementById('filter_form__categories');

			let new_value = '';
			if(categories.value.length) {
				new_value = categories.value.split(',');
				if(!new_value.includes(id)) {
					new_value.push(id);
				}

				new_value = new_value.join(',');

			} else {
				new_value = id;
			}

			categories.value = new_value;

			document.getElementById('filter_form').submit();
		},

		removeCategory: function( id )
		{
			let categories = document.getElementById('filter_form__categories');

			let new_value = '';
			if(categories.value.length) {
				new_value = categories.value.split(',');
				let _new_value = [];
				for(let i=0;i<new_value.length;i++) {
					if(new_value[i]!=id) {
						_new_value.push(new_value[i]);
					}
				}
				new_value = _new_value.join(',');
			}

			categories.value = new_value;

			document.getElementById('filter_form').submit();

		}
	};
</script>

<?=$filter_form->start()?>

<?=$filter_form->field('categories')?>
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-3" style="padding-bottom: 10px;">
				<?=UI::button_create('')->setUrl($router->getAction('add')->URI())->setClass('success')?>
			</div>
		</div>
		<div class="row">
			<?php if(Main::getCategoryMode()==Main::CATEGORY_MODE_TREE): ?>
				<div class="col-xs-12 col-sm-12 col-md-3">
					<?=UI::button(Tr::_('Switch to multiple mode'))->setIcon('list-check')->setUrl( Http_Request::currentURI(['set_category_mode'=>Main::CATEGORY_MODE_MULTIPLE]) )?>
				</div>
			<?php endif; ?>
			<?php if(Main::getCategoryMode()==Main::CATEGORY_MODE_MULTIPLE): ?>
				<div class="col-xs-12 col-sm-12 col-md-3">
					
					<table style="width: 100%">
						<tr>
							<td style="width: 250px;"><?=UI::button(Tr::_('Switch to tree mode'))->setIcon('folder-tree')->setUrl( Http_Request::currentURI(['set_category_mode'=>Main::CATEGORY_MODE_TREE]) )?></td>
							<td style="width: 50px;"><?=Tr::_('Category:')?></td>
							<td><?=Category::renderSelectCategoryWidget("productFilter.addCategory(selected_item.id)")?></td>
						</tr>
						<tr>
							<td></td>
							<td style="padding: 5px;" colspan="2">
								<?php foreach($listing->getFilter_categories()->getSelected() as $c_id=>$category): ?>
									<div style="float: left;margin: 2px;">
										<?=UI::button(' '.$category->getPathName())->setIcon('trash')->setClass('info')->setSize(UI_button::SIZE_EXTRA_SMALL)->setOnclick("productFilter.removeCategory({$c_id})")?>
									</div>
								
								<?php endforeach; ?>
							</td>
						</tr>
					</table>
				</div>
			<?php endif; ?>
			
			<div class="col-xs-12 col-sm-12 col-md-3">
				<?= $filter_form->field( 'search' )->input() ?>
			</div>
		</div>
		<div class="row" style="padding-top: 5px;padding-bottom: 5px;">
			<div class="col-xs-12 col-sm-12 col-md-3">
				<?php
				$filter_form->field('product_kind')->input()->addJsAction('onchange', 'this.form.submit()');
				$filter_form->field('product_kind')->label()->addCustomCssClass('text-right');
				?>
				<?=$filter_form->field('product_kind')?>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-3">
				<?php
				$filter_form->field('product_type')->input()->addJsAction('onchange', 'this.form.submit()');
				$filter_form->field('product_type')->label()->addCustomCssClass('text-right');
				?>
				<?=$filter_form->field('product_type')?>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12" style="padding-left: 100px;padding-top: 5px;padding-bottom: 5px;">
				<table class="badge badge-<?=match((string)$filter_form->field('is_active_general')->getValue()) {'0'=>'light', '-1'=>'danger', '1'=>'success' }?>">
					<tr>
						<td style="width: 150px;"><?=Tr::_('Is active - general')?></td>
						<td style="width: 100px;"><?=$filter_form->field('is_active_general')->input()->addJsAction('onchange', 'this.form.submit()')?></td>
					</tr>
				</table>
				<?php foreach(Shops::getList() as $code=>$shop): ?>
					<table class="badge badge-<?=match((string)$filter_form->field('is_active_'.$code)->getValue()) {'0'=>'light', '-1'=>'danger', '1'=>'success' }?>">
						<tr>
							<td style="width: 150px;"><?=Tr::_('Is active - '.$shop->getShopName())?></td>
							<td style="width: 100px;"><?=$filter_form->field('is_active_'.$code)->input()->addJsAction('onchange', 'this.form.submit()')?></td>
						</tr>
					</table>
				<?php endforeach; ?>
			</div>
		</div>
		
		<div class="row">
			<div class="col-xs-7 col-md-3">
			
			</div>
		</div>

<?=$filter_form->end()?>

