<?php
namespace JetApplicationModule\Shop\Customer\Login;

use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

$form = Main::getLoginForm(true);

$form->renderer()->addJsAction('onsubmit', 'CustomerLogin.login();return false;');
?>
<?=$form->start()?>
	<?=$form->getCommonMessage()?>
	<?=$form->field('email')?>
	<?=$form->field('password')?>

	<div class="buttons">
		<?=UI::button(Tr::_('I forget my password'))->setClass( UI_button::CLASS_LINK )->setOnclick('PasswordReset.start();')?>
		<?=UI::button(Tr::_('Sign in'))->setClass( UI_button::CLASS_PRIMARY )->setOnclick('CustomerLogin.login();')?>
	</div>
<?=$form->end()?>
