<?php
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var EShop $eshop
 */

$eshop = $this->getRaw('eshop');
$form = $this->getRaw('form');
$eshop_key = $eshop->getKey();
?>
<?=$form->field('/eshop_data/'.$eshop_key.'/title');?>
<?=$form->field('/eshop_data/'.$eshop_key.'/seo_title');?>
<?=$form->field('/eshop_data/'.$eshop_key.'/perex');?>
<?=$form->field('/eshop_data/'.$eshop_key.'/text');?>
