<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Complaints;

use Jet\Form;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Complaint;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Complaint $compaint
 */

$compaint = $this->getRaw('item');
$form = $this->getRaw('form');

echo UI::button( Tr::_('Generate service report') )
	->setClass( UI_button::CLASS_PRIMARY )
	->setIcon('file-invoice')
	->setUrl( Http_Request::currentURL(set_GET_params: ['service_report_action'=>'generate']) );