<?php
namespace JetApplicationModule\Admin\Payment\Methods;

use JetApplication\Payment_Method;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View   $this
 * @var Payment_Method       $payment_method
 */
$payment_method = $this->getRaw( 'payment_method' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( 'Do you really want to delete this payment method?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $payment_method->getCode() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$payment_method->getInternalName();?> (<?=$payment_method->getInternalName();?>)</a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>