<?php
namespace JetShopModule\Admin\Payment\Methods;

use JetShop\Payment_Method;

use Jet\UI;
use Jet\UI_dataGrid;
use Jet\UI_button;

use Jet\Tr;
use Jet\Mvc_View;
use Jet\Form;

/**
 * @var Mvc_View     $this
 * @var UI_dataGrid  $grid
 * @var Form         $filter_form
 */
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );
$router = $this->getController()->getControllerRouter();


$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( Payment_Method $item ) use ( $router ) {
		if( ( $edit_uri = $router->action('edit')->URI( $item->getCode() ) ) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;
		echo '&nbsp;';
		if( ( $delete_uri = $router->action('delete')->URI( $item->getCode() ) ) ):
			echo UI::button_delete()->setUrl( $delete_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;

	}
);
$c_edit->setCssStyle( 'width:200px;' );

$grid->getColumn( 'code' )->setCssStyle( 'width:120px;' );

$grid->getColumn( 'internal_name' )->setRenderer(
	function( Payment_Method $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getCode() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getInternalName();?></a>
		<?php
	}
);

$grid->getColumn( 'code' )->setRenderer(
	function( Payment_Method $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getCode() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getCode();?></a>
		<?php
	}
);

$grid->getColumn( 'kind' )->setRenderer(
	function( Payment_Method $item ) use ( $router ) {
		echo $item->getKindTitle();
	}
);
$grid->getColumn( 'kind' )->setCssStyle( 'width:200px;' );

$grid->getColumn( 'services' )->setRenderer(
	function( Payment_Method $item ) use ( $router ) {
		foreach($item->getServices() as $service) {
			echo $service->getInternalName().'<br>';
		}
	}
);
$grid->getColumn( 'services' )->setCssStyle( 'width:350px;' );


$grid->getColumn( 'delivery_methods' )->setRenderer(
	function( Payment_Method $item ) use ( $router ) {
		foreach($item->getDeliveryMethods() as $method) {
			echo $method->getInternalName().'<br>';
		}
	}
);
$grid->getColumn( 'delivery_methods' )->setCssStyle( 'width:350px;' );

?>

<?=$filter_form->start()?>
<div class="row toolbar">
	<?php if( ( $add_uri = $router->action('add')->URI() ) ): ?>
		<div class="col-md-2 col-sm-12">
			<?=UI::button_create( Tr::_( 'Create a new Payment Method' ) )->setUrl( $add_uri )?>
		</div>
	<?php endif; ?>

	<div class="col-md-3 col-sm-12">
		<?=UI::searchField( 'search', $filter_form->field('search')->getValue() )?>
	</div>
	<div class="col-md-4 col-sm-12">
	</div>

</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
