<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\AutoOffers;


use Jet\MVC_View;
use JetApplication\Marketing_AutoOffer;
use JetApplication\Product_EShopData;
use JetApplication\Application_Service_EShop;
use JetApplication\ShoppingCart;

/**
 * @var MVC_View   $this
 * @var Marketing_AutoOffer $offer
 * @var ShoppingCart $cart
 */

$offer = $this->getRaw('offer');
$product = Product_EShopData::get( $offer->getOfferProductId() );
$cart = $this->getRaw('cart')
?>
<div class="auto-offer">
	<div class="auto-offer-checkbox">
		<input type="checkbox" onclick="ShoppingCart.selectAutoOffer(<?=$offer->getId()?>, 1);">
	</div>
	<div class="auto-offer-title">
		<div class="auto-offer-title">
			<a href="<?= $product->getURL() ?>"><?= $offer->getLabel()?:$product->getName() ?></a>
		</div>
		<div class="auto-offer-description">
			<?= $offer->getDescription() ? : $product->getDescription() ?>
		</div>
	</div>
	<div class="auto-offer-price">
		<?= Application_Service_EShop::PriceFormatter()->formatWithCurrency( $product->getPrice( $cart->getPricelist() ) ) ?>
	</div>
</div>
