<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ProductFilterManager;


use Jet\MVC_View;
use Jet\UI;
use JetApplication\Application_Service_Admin;

/**
 * @var MVC_View   $this
 */

$brand_ids = $this->getRaw('brand_ids');
if(!$brand_ids) {
	return;
}

$brand_ids = explode(',', $brand_ids);
?>
<table class="table table-striped">
	<?php foreach($brand_ids as $id): ?>
	<tr>
		<td style="width: 20px;"><?=UI::button_delete(' ')->setOnClick("FilterEditBrands.remove({$id})")?></td>
		<td><?=Application_Service_Admin::Brand()->renderItemName( $id )?></td>
	</tr>
	<?php endforeach; ?>
</table>
