<?php
namespace JetApplicationModule\Shop\Articles;

use Jet\MVC_View;
use JetApplication\Content_Article_ShopData;

/**
 * @var MVC_View   $this
 * @var Content_Article_ShopData $article
 */
$article = $this->getRaw('article');

$author = $article->getAuthor();
?>
<h1><?=$article->getTitle()?></h1>

<p><?=$article->getPerex()?></p>

<?=$article->getText()?>

<?php if($author): ?>
<div style="display: grid;grid-template-columns: 110px 1fr;gap: 10px;">
	<div>
		<?php if($author->getImageAvatar1()): ?>
		<img src="<?=$author->getImageAvatar1ThumbnailUrl(100,100)?>">
		<?php endif; ?>
	</div>
	<div>
		<b><?=$author->getName()?></b><br>
		<?=$author->getAboutAuthor()?>
	</div>
</div>
<?php endif; ?>
