<?php
namespace JetApplicationModule\EShop\ReturnsOfGoods;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use Jet\UI_messages;
use JetApplication\ReturnOfGoods;

/**
 * @var MVC_View  $this
 * @var ReturnOfGoods $return
 */

$return = $this->getRaw('return');
?>

<div class="return-of-goods-description">
<?php if($return->canBeFinished()): ?>
	<?=UI::button( Tr::_('Finish entering return of goods request') )->setUrl( Http_Request::currentURI(['finish'=>1]) )->setClass(UI_button::CLASS_SUCCESS)?>
	<?php
else:
	if(strlen($return->getProblemDescription())<$return->getMinimalProblemDescriptionLength()):
		?>
		<div class="return-of-goods-description">
		<?=UI_messages::createInfo( Tr::_('Please provide a sufficiently detailed description of the problem.', ['m'=>$return->getMinimalProblemDescriptionLength()]) )?>
		</div>
		<?php
	endif;
endif;
?>
</div>
