<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\KindsOfProduct;

use Jet\Http_Request;
use Jet\MVC_View;
use JetApplication\Admin_Managers_EShopEntity_Edit;
use JetApplication\Exports;
use JetApplication\Exports_Module;
use JetApplication\EShops;
use JetApplication\EShop;
use JetApplication\KindOfProduct;

/**
 * @var MVC_View $this
 * @var Exports_Module $selected_exp
 * @var EShop $selected_exp_eshop
 * @var KindOfProduct $kind_of_product
 * @var Admin_Managers_EShopEntity_Edit $editor_manager
 */

$modules = Exports::getExportModulesList();

$selected_exp = $this->getRaw('selected_exp');
$selected_exp_eshop = $this->getRaw('selected_exp_eshop');
$selected_exp_code = $this->getString('selected_exp_code');
$selected_exp_eshop_key = $this->getString('selected_exp_eshop_key');

$kind_of_product = $this->getRaw('kind_of_product');

$editor_manager = $this->getRaw('editor_manager');


echo $editor_manager->renderToolbar();
?>
<div id="main-col">
	<?=$this->getRaw('tabs')?>
	<br>
	
	<div style="display: grid;grid-template-columns: 2fr 10fr;gap: 10px;">
		<div>
			<ul class="list-group">
				<?php foreach($modules as $module):
					foreach( EShops::getListSorted() as $eshop):
						if(!$module->isAllowedForShop($eshop)):
							continue;
						endif;
						
						$title = $module->getTitle().' - '.$eshop->getName();
						$link = Http_Request::currentURI(['exp'=>$module->getCode(),'exp_eshop'=>$eshop->getKey()]);
						
						if($module->getCode()==$selected_exp_code && $eshop->getKey()==$selected_exp_eshop_key):
							?><li class="list-group-item active"><?=$title?></li><?php
						else:
							?><li class="list-group-item"><a href="<?=$link?>"><?=$title?></a></li><?php
						endif;
					endforeach;
				endforeach; ?>
			</ul>
		</div>
		<div>
			<?php if($selected_exp): ?>
				<legend><?=$selected_exp->getTitle()?> - <?=$selected_exp_eshop->getName()?></legend>
				<?php $selected_exp->handleKindOfProductSettings( $kind_of_product, $selected_exp_eshop )?>
			<?php endif; ?>
		</div>
	</div>
</div>

