<?php
namespace JetApplicationModule\Admin\Catalog\KindsOfProduct;


use Jet\Http_Request;
use Jet\UI;
use JetApplication\Exports;
use JetApplication\Exports_Module;
use Jet\MVC_View;
use JetApplication\Shops;
use JetApplication\Shops_Shop;

/**
 * @var MVC_View $this
 * @var Exports_Module $selected_exp
 * @var Shops_Shop $selected_exp_shop
 * @var KindOfProduct $kind_of_product
 */

$modules = Exports::getActiveModules();

$selected_exp = $this->getRaw('selected_exp');
$selected_exp_shop = $this->getRaw('selected_exp_shop');
$selected_exp_code = $this->getString('selected_exp_code');
$selected_exp_shop_key = $this->getString('selected_exp_shop_key');

$kind_of_product = $this->getRaw('kind_of_product');




?>
<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>
	</div>
</div>
<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>
	</div>
</div>

<div class="row">
	<div class="col-md-2">
		<ul class="list-group">
			<?php foreach($modules as $module):
				foreach(Shops::getListSorted() as $shop):
					if(!$module->isAllowedForShop($shop)):
						continue;
					endif;
					
					$title = $module->getTitle().' - '.$shop->getShopName();
					$link = Http_Request::currentURI(['exp'=>$module->getCode(),'exp_shop'=>$shop->getKey()]);
					
					if($module->getCode()==$selected_exp_code && $shop->getKey()==$selected_exp_shop_key):
						?><li class="list-group-item active"><?=$title?></li><?php
					else:
						?><li class="list-group-item"><a href="<?=$link?>"><?=$title?></a></li><?php
					endif;
				endforeach;
			endforeach; ?>
		</ul>
	</div>
	<div class="col-md-10" id="main-col">
		<?php if($selected_exp): ?>
			<legend><?=$selected_exp->getTitle()?> - <?=$selected_exp_shop->getShopName()?></legend>
			<?=$selected_exp->handleKindOfProductSettings( $kind_of_product, $selected_exp_shop )?>
		<?php endif; ?>
	</div>
</div>