<?php
namespace JetShopModule\Admin\Catalog\KindsOfProduct;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetShop\KindOfProduct;
use JetShop\Property;
use JetShop\PropertyGroup;

/**
 * @var MVC_View   $this
 * @var KindOfProduct $kind_of_product
 */

$kind_of_product = $this->getRaw('kind_of_product');

$form = $kind_of_product->getEditForm();

$editable = !$form->getIsReadonly();
?>
<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>
		
	</div>
</div>

<div class="row">
	
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>
		
		<div class="toolbar">
			<?php if( $editable ): ?>
				<table style="width: 100%">
					<tr>
						<td style="padding-left: 30px;width: 100px;" nowrap=""><?=Tr::_('Add group: ')?></td>
						<td style="width: 400px;" nowrap="">
								<?=PropertyGroup::renderSelectPropertyGroupWidget( "location='".Http_Request::currentURI()."&add_group='+selected_item.id" )?>
						</td>
						<td style="text-align: right;">
							<?=UI::button(Tr::_('Apply detail settings'))->setUrl( Http_Request::currentURI(['apply_detail_settings'=>1]) )?>
						</td>
					</tr>
				</table>
			<?php endif; ?>
		</div>
		
		<div id="groups">
		<?php foreach( $kind_of_product->getFilterGroups() as $g):
			$group = $g->getGroup();
			?>
			<div class="card sortable-item group" style="margin-bottom: 15px;" data-id="<?=$g->getGroupId()?>">
				<div class="card-header">
					<?php if($editable): ?>
						<?=UI::icon('up-down')?>
					<?php endif ?>
					<a href="<?=$group->getEditURL()?>"><?=$group->getInternalName()?></a>
					<?php if($editable): ?>
					<div class="float-right">
						<?=UI::button_delete(' ')->setSize(UI_button::SIZE_EXTRA_SMALL )->setUrl(Http_Request::currentURI(['remove_group'=>$g->getGroupId()]))?>
					</div>
					<?php endif; ?>
				</div>
				<div class="toolbar">
					<?php if( $editable ): ?>
						<table>
							<tr>
								<td style="padding-left: 30px;"><?=Tr::_('Add property: ')?></td>
								<td style="width: 400px;">
									<?=Property::renderSelectPropertyWidget(
										on_select: "location='".Http_Request::currentURI()."&group=".$g->getGroupId()."&add_property='+selected_item.id",
										name: 'add_property_'.$g->getGroupId()
									)?>
								</td>
							</tr>
						</table>
					<?php endif; ?>
				</div>
					<ul class="list-group list-group-flush" id="properties_<?=$g->getGroupId()?>">
						<?php foreach( $g->getProperties() as $p):
							$property = $p->getProperty();
							?>
							<li class="list-group-item sortable-item property" data-id="<?=$p->getPropertyId()?>">
								<?php if($editable): ?>
									<?=UI::icon('up-down')?>
								<?php endif; ?>
								<a href="<?=$property->getEditURL()?>"><?=$property->getInternalName()?></a>
								<?php if($editable): ?>
									<div class="float-right">
										<?=UI::button_delete(' ')->setSize(UI_button::SIZE_EXTRA_SMALL )->setUrl(Http_Request::currentURI(['remove_property' =>$p->getPropertyId(), 'group' =>$g->getGroupId()]))?>
									</div>
								<?php endif; ?>
							</li>
						<?php endforeach; ?>
					</ul>
			</div>
		<?php endforeach; ?>
		</div>
	</div>
</div>

<?php if($editable): ?>
	<script type="text/javascript">

		const sortProperties = {
			init: function ( group_id ) {
				$('#properties_'+group_id).sortable({
					stop: function () {
						sortProperties.setSort(group_id);
					}
				});
			},

			setSort: function (group_id) {
				let values = [];

				$('#properties_'+group_id).find('.property').each(function (i, item) {
					values.push($(item).data('id'));
				});

				values = values.join('|');

				location = '<?=Http_Request::currentURI()?>&group='+group_id+'&sort_properties='+values;

			}
		};

		<?php foreach( $kind_of_product->getFilterGroups() as $g): ?>
		sortProperties.init(<?=$g->getGroupId()?>);
		<?php endforeach; ?>

		$('#groups').sortable({
			stop: function () {
				let values = [];

				$('#groups').find('.group').each(function (i, item) {
					values.push($(item).data('id'));
				});

				values = values.join('|');

				location = '<?=Http_Request::currentURI()?>&sort_groups='+values;
			
			}
		});
		
	</script>

<?php endif; ?>
