<?php
namespace JetApplicationModule\Admin\Catalog\KindsOfProduct;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View   $this
 * @var KindOfProduct $kind_of_product
 */

$kind_of_product = $this->getRaw('kind_of_product');

$form = $kind_of_product->getEditForm();

$editable = !$form->getIsReadonly();
?>
<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>
		
	</div>
</div>

<div class="row">
	
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>
		
		<div class="toolbar">
			<?php if( $editable ): ?>
				<table style="width: 100%">
					<tr>
						<td style="padding-left: 30px;width: 100px;" nowrap=""><?=Tr::_('Add property: ')?></td>
						<td style="width: 400px;" nowrap="">
								<?=Admin_Managers::Property()->renderSelectWidget( "location='".Http_Request::currentURI()."&add_property='+selected_item.id" )?>
						</td>
						<td style="text-align: right;">
						</td>
					</tr>
				</table>
			<?php endif; ?>
		</div>
		
		<div>
			<ul class="list-group list-group-flush" id="properties">
			<?php foreach( $kind_of_product->getHiddenProperties() as $p): ?>

					<li class="list-group-item sortable-item property" data-id="<?=$p->getPropertyId()?>">
						<?php if($editable): ?>
							<?=UI::icon('up-down')?>
						<?php endif; ?>
						<?=Admin_Managers::Property()->showName( $p->getPropertyId() ) ?>
						<?php if($editable): ?>
							<div class="float-right">
								<?=UI::button_delete(' ')->setSize(UI_button::SIZE_EXTRA_SMALL )->setUrl(Http_Request::currentURI(['remove_property' =>$p->getPropertyId()]))?>
							</div>
						<?php endif; ?>
					</li>
		
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
</div>

<?php if($editable): ?>
	<script type="text/javascript">
		
		$('#properties').sortable({
			stop: function () {
				let values = [];

				$('#properties').find('.property').each(function (i, item) {
					values.push($(item).data('id'));
				});

				values = values.join('|');

				location = '<?=Http_Request::currentURI()?>&sort_properties='+values;
			
			}
		});
		
	</script>

<?php endif; ?>
