<?php
namespace JetApplicationModule\Admin\Catalog\KindsOfProduct;

use JetApplication\Admin_Managers;

use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use JetApplication\Shops;
use JetApplication\Shops_Shop;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var KindOfProduct     $kind_of_product
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 1 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );

$kind_of_product = $this->getRaw( 'kind_of_product' );
$router = $this->getController()->getControllerRouter();
?>


<?=$form->start()?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>
		
		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()?>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>
		<br>
		
		<?=Admin_Managers::UI()->renderEntityActivation( $kind_of_product, !$form->getIsReadonly() )?>
		<?=$form->field('internal_name');?>
		<?=$form->field('internal_notes');?>
		
		<?php
		Admin_Managers::UI()->renderShopDataBlocks(
			form: $form,
			renderer: function( Shops_Shop $shop, string $shop_key ) use ($kind_of_product, $form) : void {
				?>
				<fieldset>
					<legend class="sub"><?=Tr::_('Main data')?></legend>
					
					<?=Admin_Managers::UI()->renderEntityShopDataActivation( $kind_of_product, $shop, !$form->getIsReadonly() )?>
					
					<?=$form->field('/shop_data/'.$shop_key.'/label');?>
					<?=$form->field('/shop_data/'.$shop_key.'/description');?>
				</fieldset>
			
			<?php }); ?>
	
	</div>
</div>

<?=$form->end()?>
