<?php
namespace JetApplicationModule\Admin\Catalog\KindsOfProduct;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use JetApplication\MarketplaceIntegration;
use JetApplication\MarketplaceIntegration_Module;
use JetApplication\EShops;
use JetApplication\EShop;
use JetApplication\KindOfProduct;

/**
 * @var MVC_View $this
 * @var MarketplaceIntegration_Module $selected_mp
 * @var EShop $selected_mp_eshop
 * @var KindOfProduct $kind_of_product
 */

$modules = MarketplaceIntegration::getActiveModules();

$selected_mp = $this->getRaw('selected_mp');
$selected_mp_eshop = $this->getRaw('selected_mp_eshop');
$selected_mp_code = $this->getString('selected_mp_code');
$selected_mp_eshop_key = $this->getString('selected_mp_eshop_key');

$kind_of_product = $this->getRaw('kind_of_product');

?>
<div class="toolbar" id="main-toolbar">
	<?=UI::button_goBack()?>
</div>
<div id="main-col">
	<?=$this->getRaw('tabs')?>

	<br>
	<div style="display: grid;grid-template-columns: 2fr 10fr;gap: 10px;">
		<div>
			<ul class="list-group">
				<?php foreach($modules as $module):
					foreach( EShops::getListSorted() as $eshop):
						if(
							!$module->isAllowedForShop($eshop) ||
							!$module->hasKindOfProductSettings()
						):
							continue;
						endif;
						
						$title = $module->getTitle().' - '.$eshop->getName();
						$link = Http_Request::currentURI(['mp'=>$module->getCode(),'mp_eshop'=>$eshop->getKey()]);
						
						if($module->getCode()==$selected_mp_code && $eshop->getKey()==$selected_mp_eshop_key):
							?><li class="list-group-item active"><?=$title?></li><?php
						else:
							?><li class="list-group-item"><a href="<?=$link?>"><?=$title?></a></li><?php
						endif;
					endforeach;
				endforeach; ?>
			</ul>
		</div>
		<div>
			<?php if($selected_mp): ?>
				<legend><?=$selected_mp->getTitle()?> - <?=$selected_mp_eshop->getName()?></legend>
				<?php $selected_mp->handleKindOfProductSettings( $kind_of_product, $selected_mp_eshop ) ?>
			<?php endif; ?>
		</div>
	</div>
</div>