<?php
namespace JetApplicationModule\Admin\TimerManager;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Entity_WithShopData;
use JetApplication\Shops_Shop;


/**
 * @var MVC_View   $this
 * @var Entity_WithShopData $entity
 * @var Shops_Shop $shop
 */

$entity = $this->getRaw('entity');
$shop = $this->getRaw('shop');

$class = $this->getRaw('class');

echo UI::button( Tr::_('Timer') )
	->setIcon('clock')
	->setClass( $this->getBool('has_not_processed') ? UI_button::CLASS_INFO : UI_button::CLASS_LIGHT )
	->setOnClick("TimerManager.open('{$entity::getEntityType()}', '{$class}',{$entity->getId()},'{$shop->getKey()}')");
