<?php
namespace JetApplicationModule\Admin\TimerManager;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Http_Request;
use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Timer;
use JetApplication\Timer_Action;

/**
 * @var MVC_View   $this
 * @var Form[] $forms
 * @var Timer_Action[] $actions
 * @var Timer[] $scheduled
 */
$forms = $this->getRaw('forms');
$actions = $this->getRaw('actions');
$scheduled = $this->getRaw('scheduled');
?>
<br>
<?php
if($scheduled):
	?>
	<div class="card">
		<div class="card-header bg-info"><?=Tr::_('Scheduled timers')?></div>
		<div class="card-body">
			<table class="table table-striped">
				<thead>
				<tr>
					<th nowrap=""><?=Tr::_('Scheduled date and time')?></th>
					<th nowrap=""><?=Tr::_('Action')?></th>
					<th nowrap=""><?=Tr::_('Context value')?></th>
					<th style="width: 100%"></th>
				</tr>
				</thead>
				<?php foreach($scheduled as $item): ?>
				<tr>
					<td nowrap=""><?=Locale::dateAndTime( $item->getDateTime() )?></td>
					<td nowrap=""><b><?=$actions[$item->getAction()]?->getTitle()?></b></td>
					<td nowrap=""><?=$actions[$item->getAction()]?->formatActionContextValue( $item->getActionContext() )?></td>
					<td style="text-align: right">
						<?php if(Main::getCurrentUserCanCancel()):
							echo UI::button_delete( Tr::_('Cancel'))->setUrl( Http_Request::currentURI(set_GET_params: ['cancel'=>$item->getId()]) );
						endif; ?>
					</td>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
	</div>
	<br><br>
	<?php
endif;

if(Main::getCurrentUserCanSet()):
?>
<div class="card">
	<div class="card-header"><?=Tr::_('Set new timer')?></div>
	<div class="card-body">
		
		<?php
		foreach($actions as $action):
			$form = $forms[$action->getAction()];
			
			$form->renderer()->setDefaultLabelWidth([
				Form_Renderer::LJ_SIZE_EXTRA_SMALL => 3,
				Form_Renderer::LJ_SIZE_SMALL => 3,
				Form_Renderer::LJ_SIZE_MEDIUM => 3
			]);
			$form->renderer()->setDefaultFieldWidth([
				Form_Renderer::LJ_SIZE_EXTRA_SMALL => 8,
				Form_Renderer::LJ_SIZE_SMALL => 8,
				Form_Renderer::LJ_SIZE_MEDIUM => 8
			]);
		
			?>
		<fieldset>
			<legend><?=$action->getTitle()?></legend>
			<?php
			echo $form->start();
			foreach($form->getFields() as $field):
				echo $field;
			endforeach;
			?>
			<div class="text-right" style="padding: 5px;">
					<?=UI::button(Tr::_('Set'))->setIcon('clock')->setType(UI_button::TYPE_SUBMIT)->setClass(UI_button::CLASS_PRIMARY)?>
			</div>
			<?=$form->end();?>
		</fieldset>
		<?php
		endforeach;
		?>
	</div>
</div>

<?php endif; ?>

<script>
	window.parent.postMessage('<?=$this->getRaw('reload_URL')?>', '*');
</script>
