<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use JetApplication\Product_ShopData;

/**
 * @var MVC_View $this
 * @var Product_ShopData $product
 */

$product = $this->getRaw('product');

$categories = $product->getCategories();

?>
<table class="table table-striped">
	<?php foreach($categories as $category): ?>
		<tr>
			<td>
				<a href="<?=$category->getURL()?>">
					<?=$category->getPathName()?>
				</a>
			</td>
		</tr>
	<?php endforeach; ?>
</table>
