<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_Layout;
use Jet\MVC_View;
use JetApplication\Product_ShopData;

/**
 * @var MVC_View $this
 * @var Product_ShopData $product
 */

$product = $this->getRaw('product');


$count = 0;
$previews = array();

for ($i = 1; $i <= 9; $i++) {
	if ($img = $product->getImg($i)) {
		$previews[] = array(
			'url' => $product->getImgUrl( $i ),
			'image' => $product->getImgThumbnailUrl($i, 110, 110 )
		);
	}
}

MVC_Layout::getCurrentLayout()->requireCssFile( 'https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.9.0/css/lightbox.css' );
MVC_Layout::getCurrentLayout()->requireJavascriptFile( 'https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.9.0/js/lightbox.js' );


?>
<div style="text-align: center">
	<?php if( $product->getImg( 0 ) ): ?>
		<a href="<?= $product->getImgUrl( 0 ) ?>"
		   title="<?= $product->getFullName() ?>"
		   data-lightbox="example-set"
		>
			<img src="<?= $product->getImgThumbnailUrl( 0, 650, 650 ) ?>"/>
		</a>
	<?php endif; ?>
	
	<div style="display: grid;grid-template-columns: repeat(5, 1fr);margin: 30px;">
		<?php foreach ($previews as $preview): ?>
			<div style="padding: 10px;">
				<a href="<?= $preview['url'] ?>" data-lightbox="example-set">
					<img src="<?= $preview['image'] ?>"/>
				</a>
			</div>
		<?php endforeach; ?>
	
	</div>
</div>

