<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\Locale;
use Jet\MVC_View;
use JetApplication\Pricelists;
use JetApplication\Product_ShopData;
use JetApplication\Shop_Managers;

/**
 * @var MVC_View $this
 * @var Product_ShopData $product
 */

$product = $this->getRaw('product');
$pricelist = Pricelists::getCurrent();

$units = $product->getMeasureUnit()?->getName();
if($units) {
	$units = ' / '.$units;
}
?>

	<div style="display: flex;align-items: center">
		<div style="font-size: 2rem;">
			<?php if($product->getDiscountPercentage($pricelist)):?>
				<div style="font-size: 1.5rem;text-decoration: line-through"><?= Shop_Managers::PriceFormatter()->formatWithCurrency( $product->getPriceBeforeDiscount( $pricelist ) ) ?></div>
			<?php endif; ?>
			<b><?= Shop_Managers::PriceFormatter()->formatWithCurrency( $product->getPrice( $pricelist ) ) ?> <?=$units?></b>
			
			<?php if($product->getDiscountPercentage($pricelist)):?>
				<div>-<?=Locale::int(floor($product->getDiscountPercentage($pricelist)))?>%</div>
			<?php endif; ?>
		</div>
	</div>

<?=Shop_Managers::ShoppingCart()->renderBuyButton_detail( $product )?>
<?=Shop_Managers::PromoAreas()?->renderArea('main', [$product->getId()])?>
