<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use JetApplication\Product_ShopData;

/**
 * @var MVC_View $this
 * @var Product_ShopData $product
 */

$product = $this->getRaw('product');

$kind = $product->getKind();

$variants = $product->getVariants();

?>
<div>
	<b><?=$kind?->getVariantSelectDescription()?></b><br>
	
	<?php foreach($variants as $variant):
		if($variant->getId()==$product->getId()):
			?>
		<div style="display: inline-block;border: 2px solid black;margin: 10px;padding: 10px;">
			<img src="<?= $variant->getImgThumbnailUrl( 0, 150, 150 ) ?>"/>
			<b><?=$variant->getVariantName()?></b>
		</div>
		<?php
		else:
		?>
			<div style="display: inline-block;margin: 10px;padding: 10px;">
			<a href="<?=$variant->getURL()?>" title="<?= $variant->getVariantName() ?>">
				<img src="<?= $variant->getImgThumbnailUrl( 0, 150, 150 ) ?>"/>
			</a>
			<a href="<?=$variant->getURL()?>"><?=$variant->getVariantName()?></a>
		</div>
		<?php
	    endif;
	endforeach; ?>
</div>
