<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use JetApplication\Product_ShopData;

/**
 * @var MVC_View $this
 * @var Product_ShopData $product
 */

$product = $this->getRaw('product');

$similar = $product->getSimilarProducts();
if(!$similar) {
	return;
}

$kind = $product->getKind();

?>
<div>
	<b><?=$kind?->getSimilarProductSelectDescription()?></b><br>
	
	<?php foreach($similar as $s):
		if($s->getId()==$product->getId()):
			?>
			<div style="display: inline-block;border: 2px solid black;margin: 10px;padding: 10px;">
				<img src="<?= $s->getImgThumbnailUrl( 0, 150, 150 ) ?>"/>
				<b><?=$s->getVariantName()?></b>
			</div>
		<?php
		else:
			?>
			<div style="display: inline-block;margin: 10px;padding: 10px;">
				<a href="<?=$s->getURL()?>" title="<?= $s->getVariantName() ?>">
					<img src="<?= $s->getImgThumbnailUrl( 0, 150, 150 ) ?>"/>
				</a>
				<a href="<?=$s->getURL()?>"><?=$s->getVariantName()?></a>
			</div>
		<?php
		endif;
	endforeach; ?>
</div>

