<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use JetApplication\Marketing_ProductSticker;
use JetApplication\Product_ShopData;

/**
 * @var MVC_View $this
 * @var Product_ShopData $product
 */

$product = $this->getRaw('product');

$stickers = Marketing_ProductSticker::getProductStickers( $product->getId() );

if(!$stickers) {
	return;
}
?>
<div style="margin: 5px;">
<?php foreach($stickers as $sticker): ?>
	<div class="product_listing_item_sticker" style="background-color: <?=$sticker->getColorBackground();?>;color: <?=$sticker->getColorText()?>">
		<?php if($sticker->getImageProductDetail()): ?>
		<div class="product_listing_item_sticker_image">
			<img src="<?=$sticker->getImageProductDetailThumbnailUrl(30, 30)?>">
		</div>
		<?php endif; ?>
		<div class="product_listing_item_sticker_text"><?=$sticker->getText()?></div>
	</div>
<?php endforeach; ?>
</div>
