<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\CashDesk;


use Jet\MVC_View;
use JetApplication\Delivery_Method;
use JetApplication\Application_Service_EShop;

/**
 * @var MVC_View $this
 * @var Delivery_Method $method
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');

$method = $this->getRaw('delivery_method');
$pricelist = $cash_desk->getPricelist();
?>
<div class="price">
	<?php if($method->getDefaultPrice($pricelist)!=$method->getPrice($pricelist)):?>
		<div class="price-standard"><?=Application_Service_EShop::PriceFormatter()->formatWithCurrency($method->getDefaultPrice($pricelist), $pricelist );?></div>
	<?php endif; ?>
	<div class="price-final"><?=Application_Service_EShop::PriceFormatter()->formatWithCurrency($method->getPrice($pricelist), $pricelist );?></div>
</div>