<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\CashDesk;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Application_Service_EShop;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');
$pricelist = $cash_desk->getPricelist();

$step = $cash_desk->getCurrentStep();
?>


<dialog id="select_personal_takeover_point_dialog" tabindex="-1">

	<div class="dialog-header">
		<h5><?=Tr::_('Personal takeover place')?></h5>
		<button type="button" aria-label="Close" onclick="dialog.close('select_personal_takeover_point_dialog')">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
	<div class="dialog-body" id="select_personal_takeover_point_dialog_body">
		
		<div id="personal_takeover_filter">
			<div>
				<b><?=Tr::_('Where do you want to send the package?')?></b>
				
				<div class="search-dialog">
					<div>
						<input type="text" id="select_personal_takeover_point_search_input" placeholder="" />
						<div style="position: relative">
							<div  id="select_personal_takeover_point_search_result" class="whisperer-items" style="display: none;">
							</div>
						</div>
						
					</div>
					<button onclick="CashDesk.delivery.personalTakeover.resetSearch();">
						<?=UI::icon('circle-xmark')?>
					</button>
				</div>
				
			</div>
			
			
			<div>
				<b><?=Tr::_('Available delivery methods')?></b>
				<?php foreach($cash_desk->getAvailableDeliveryMethods() as $method):
					if(!$method->isPersonalTakeover()) {
						continue;
					}
					?>
					<div
						class="method"
						onclick="CashDesk.delivery.personalTakeover.selectMethod(<?=$method->getId()?>)"
					>
						<div class="checkbox">
							<input
								type="checkbox"
								value="<?=$method->getId()?>" checked
								class="personal_takeover_method"
								onchange="this.checked=!this.checked;CashDesk.delivery.personalTakeover.actualizeMethodsSelection();"
							>
						</div>
						<div class="icon">
							<?php if(($img=$method->getIcon1ThumbnailUrl(50, 50))): ?>
								<img src="<?=$img?>">
							<?php endif; ?>
						</div>
						<div class="title"><?=$method->getTitle()?></div>
						<div class="price"><?=Application_Service_EShop::PriceFormatter()->formatWithCurrency( $method->getPrice($pricelist), $pricelist )?></div>
					</div>
				<?php endforeach; ?>
			</div>
		</div>

		<div id="personal_takeover_buttons">
			<button type="button"
			        onclick="document.getElementById('select_personal_takeover_point_dialog_body').classList.toggle('filter-visible');this.classList.toggle('opened')"
			> </button>
		</div>
		
		
		<div id="personal_takeover_map">
		</div>
	</div>

</dialog>

<dialog id="select_personal_takeover_selected_point_dialog" tabindex="-1">
	<div class="dialog-header">
		<h5></h5>
		<button type="button" aria-label="Close" onclick="dialog.close('select_personal_takeover_selected_point_dialog')">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
	<div class="dialog-body" id="personal_takeover_point">
	
	</div>

</dialog>

