<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Content\Email\Layouts;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\EMail_Layout;

/**
 * @var MVC_View $this
 * @var EMail_Layout $item
 */

$item = $this->getRaw('item');

if($item->isEditable()) {
	echo Admin_Managers::Image()->commonImageManager( 'email_layout', $item->getId() );
}
