<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use JetApplication\EShop_CookieSettings_Group;
use JetApplication\Application_Service_EShop;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 */

$g_id = $this->getRaw('id');
?>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<?=$g_id?>"></script>
<script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}

	gtag('consent', 'default', {
		'ad_storage': '<?=Application_Service_EShop::CookieSettings()->groupEnabled( EShop_CookieSettings_Group::MARKETING)?'granted':'denied'?>',
		'ad_user_data': '<?=Application_Service_EShop::CookieSettings()->groupEnabled( EShop_CookieSettings_Group::MARKETING)?'granted':'denied'?>',
		'ad_personalization': '<?=Application_Service_EShop::CookieSettings()->groupEnabled( EShop_CookieSettings_Group::MARKETING)?'granted':'denied'?>',
		'analytics_storage': '<?=Application_Service_EShop::CookieSettings()->groupEnabled( EShop_CookieSettings_Group::STATS )?'granted':'denied'?>'
	});


	gtag('js', new Date());

	gtag('config', '<?=$g_id?>', {
		//client_storage: 'none',
		//client_id: '',
	});
	
	if(!window['CookieSettingHandlers']) {
		window['CookieSettingHandlers'] = [];
	}

	window['CookieSettingHandlers'].push(( state )=>{
		gtag('consent', 'update', {
			'ad_storage': state.marketing?'granted':'denied',
			'ad_user_data': state.marketing?'granted':'denied',
			'ad_personalization': state.marketing?'granted':'denied',
			'analytics_storage': state.stats?'granted':'denied'
		});
	});


	const scrollMeasurement = {
		measurement_limits: [ 90, 75, 50, 25 ],

		last_reached_scroll: 0,

		init: () => {
			window.addEventListener('scroll', function () {
				scrollMeasurement.measure();
			});
		},

		measure: ()=> {

			let scroll_top = window.scrollY;
			let doc_height = document.body.offsetHeight;
			let win_height = window.innerHeight;
			let scroll_percent = (scroll_top / (doc_height - win_height))*100;

			scroll_percent = Math.round( scroll_percent );

			if(scroll_percent>scrollMeasurement.last_reached_scroll) {
				scrollMeasurement.last_reached_scroll = scroll_percent;

				for (let i = 0; i < scrollMeasurement.measurement_limits.length; i++) {
					let limit = scrollMeasurement.measurement_limits[i];

					if(scrollMeasurement.last_reached_scroll>=limit) {
						gtag('event', 'scroll_'+limit, {
							page_title: document.title,
							page_location: window.location.href
						});
						break;
					}
				}
			}
		}
	};

	scrollMeasurement.init();

</script>
