<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Properties;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Admin_Managers;


/**
 * @var MVC_View $this
 * @var Listing_Filter_Type $filter
 */

$listing = $this->getRaw( 'listing' );
$filter = $this->getRaw('filter');
$filter_form = $listing->getFilterForm();
$field = $filter_form->field( 'is_default_filter' );
$field->input()->addJsAction( 'onchange', 'this.form.submit()' );

echo Admin_Managers::EntityListing()->renderListingFilter(
	filter:      $filter,
	title:       Tr::_('Is default filter'),
	form_fields: [$field],
	is_active:   $field->getValue(),
	renderer:    function() use ($field) {
		?>
		<?= $field->input() ?>
		<?php
	}
);
