<?php
namespace JetApplicationModule\Admin\Complaints;

use Jet\Form;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

use Jet\MVC_View;


/**
 * @var MVC_View $this
 * @var Form $form
 */

$form = $this->getRaw('phone_and_email_form');

if(!$form) {
	return;
}
?>
<div style="text-align: center;padding: 10px;">
<?=UI::button(Tr::_('Edit'))->setIcon('pen-to-square')
	->setClass(UI_button::CLASS_PRIMARY)
	->setOnClick("$('#phone_end_email_dialog').modal('show');")?>
</div>