<?php
namespace JetApplication;

use JetShop\Core_Admin_EntityManager_WithEShopRelation_Interface;

interface Admin_EntityManager_WithEShopRelation_Interface extends Core_Admin_EntityManager_WithEShopRelation_Interface {

}