<?php
namespace JetApplicationModule\Admin\SupplierGoodsOrders;

use Jet\Locale;
use Jet\MVC_View;
use JetApplication\Supplier_GoodsOrder;

/**
 * @var MVC_View $this
 * @var Supplier_GoodsOrder $item
 */

$item = $this->getRaw('item');
?>
<div style="display: grid;grid-template-columns: 40px 1fr;gap: 10px; align-items: center;font-size: 0.7rem">
	<?php foreach($item->getItems() as $item):
		if(!$item->getUnitsOrdered()) {
			continue;
		}
		?>
	<div><?=Locale::float($item->getUnitsOrdered())?> <?=$item->getMeasureUnit()?->getName()?></div>
	<div><?=$item->getProductName()?></div>
	<?php endforeach; ?>
</div>
