<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\SupplierGoodsOrders;


use Jet\MVC_View;
use JetApplication\Supplier_GoodsOrder;

/**
 * @var MVC_View $this
 * @var Supplier_GoodsOrder $item
 */

$item = $this->getRaw('item');
?>
<a href="<?=$item->getEditUrl()?>"><?=$item->getNumber()?></a>
