<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Discounts\CodesDefinition;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Application_Service_Admin;
use Jet\Form;
use JetApplication\Discounts_Code;

/**
 * @var MVC_View   $this
 * @var Discounts_Code $item
 * @var Form $form
 */

$item = $this->getRaw('item');
$form = $this->getRaw('filter_form');
$editable = $item->isEditable();

$p_manager = Application_Service_Admin::Product();

echo $this->controller->getEditorManager()->renderToolbar();

?>
<div id="main-col">
	<?=$this->getRaw('tabs')?>
	
	<fieldset>
		<legend><?=Tr::_('Filter')?></legend>
		
		
		<?=$form->start();?>
		<div class="toolbar">
			<?=UI::button_save( Tr::_('Save filter settings') )?>
		</div>
		
		<div>
			<?=Application_Service_Admin::ProductFilter()->renderFilterForm(); ?>
		</div>
		<?=$form->end();?>
		
	</fieldset>

</div>