<?php
return [
	[
		'code' => 'CZK',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => ',-_Kč',
		'symbol_right_without_VAT' => '_Kč',
		'symbol_right_VAT' => '_Kč',
		'decimal_separator' => ',',
		'thousands_separator' => '_',
		'decimal_places_with_VAT' => 0,
		'decimal_places_without_VAT' => 2,
		'decimal_places_VAT' => 2,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 0,
		'exchange_rates' => [
			'EUR' => 0.039,
			'HUF' => 15.5,
			'ZLO' => 1.0,
			'PLN' => 0.17,
		],
	],
	[
		'code' => 'EUR',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_€',
		'symbol_right_without_VAT' => '_€',
		'symbol_right_VAT' => '_€',
		'decimal_separator' => ',',
		'thousands_separator' => '_',
		'decimal_places_with_VAT' => 2,
		'decimal_places_without_VAT' => 2,
		'decimal_places_VAT' => 2,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 2,
		'exchange_rates' => [
			'CZK' => 25.43,
			'HUF' => 399.74,
			'PLN' => 4.3,
			'ZLO' => 1.0,
		],
	],
	[
		'code' => 'PLN',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_zł',
		'symbol_right_without_VAT' => '_zł',
		'symbol_right_VAT' => '_zł',
		'decimal_separator' => ',',
		'thousands_separator' => '_',
		'decimal_places_with_VAT' => 2,
		'decimal_places_without_VAT' => 2,
		'decimal_places_VAT' => 2,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 2,
		'exchange_rates' => [
			'CZK' => 5.86,
			'EUR' => 0.23,
			'HUF' => 92.88,
		],
	],
	[
		'code' => 'HUF',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_Ft',
		'symbol_right_without_VAT' => '_Ft',
		'symbol_right_VAT' => '_Ft',
		'decimal_separator' => ',',
		'thousands_separator' => '_',
		'decimal_places_with_VAT' => 0,
		'decimal_places_without_VAT' => 0,
		'decimal_places_VAT' => 0,
		'round_precision_without_VAT' => 0,
		'round_precision_VAT' => 0,
		'round_precision_with_VAT' => 0,
		'exchange_rates' => [
			'CZK' => 0.063,
			'EUR' => 0.0025,
			'PLN' => 0.011,
		],
	],
	[
		'code' => 'USD',
		'symbol_left_with_VAT' => '$',
		'symbol_left_without_VAT' => '$',
		'symbol_left_VAT' => '$',
		'symbol_right_with_VAT' => '',
		'symbol_right_without_VAT' => '',
		'symbol_right_VAT' => '',
		'decimal_separator' => ',',
		'thousands_separator' => '_',
		'decimal_places_with_VAT' => 2,
		'decimal_places_without_VAT' => 2,
		'decimal_places_VAT' => 2,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 2,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'BGN',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_лв.',
		'symbol_right_without_VAT' => '_лв.',
		'symbol_right_VAT' => '_лв.',
		'decimal_separator' => ',',
		'thousands_separator' => '_',
		'decimal_places_with_VAT' => 2,
		'decimal_places_without_VAT' => 2,
		'decimal_places_VAT' => 2,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 2,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'DKK',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_kr',
		'symbol_right_without_VAT' => '_kr',
		'symbol_right_VAT' => '_kr',
		'decimal_separator' => ',',
		'thousands_separator' => '_',
		'decimal_places_with_VAT' => 2,
		'decimal_places_without_VAT' => 2,
		'decimal_places_VAT' => 2,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 2,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'ISK',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_kr.',
		'symbol_right_without_VAT' => '_kr.',
		'symbol_right_VAT' => '_kr.',
		'decimal_separator' => ',',
		'thousands_separator' => '.',
		'decimal_places_with_VAT' => 0,
		'decimal_places_without_VAT' => 2,
		'decimal_places_VAT' => 2,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 0,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'CHF',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_CHF',
		'symbol_right_without_VAT' => '_CHF',
		'symbol_right_VAT' => '_CHF',
		'decimal_separator' => ',',
		'thousands_separator' => '_',
		'decimal_places_with_VAT' => 2,
		'decimal_places_without_VAT' => 2,
		'decimal_places_VAT' => 2,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 2,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'NOK',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_NOK',
		'symbol_right_without_VAT' => '_NOK',
		'symbol_right_VAT' => '_NOK',
		'decimal_separator' => ',',
		'thousands_separator' => '_',
		'decimal_places_with_VAT' => 2,
		'decimal_places_without_VAT' => 2,
		'decimal_places_VAT' => 2,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 2,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'RON',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_Lei',
		'symbol_right_without_VAT' => '_Lei',
		'symbol_right_VAT' => '_Lei',
		'decimal_separator' => ',',
		'thousands_separator' => '_',
		'decimal_places_with_VAT' => 2,
		'decimal_places_without_VAT' => 2,
		'decimal_places_VAT' => 2,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 2,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'GBP',
		'symbol_left_with_VAT' => '£',
		'symbol_left_without_VAT' => '£',
		'symbol_left_VAT' => '£',
		'symbol_right_with_VAT' => '',
		'symbol_right_without_VAT' => '',
		'symbol_right_VAT' => '',
		'decimal_separator' => '.',
		'thousands_separator' => ',',
		'decimal_places_with_VAT' => 2,
		'decimal_places_without_VAT' => 2,
		'decimal_places_VAT' => 2,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 2,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'GIP',
		'symbol_left_with_VAT' => '£',
		'symbol_left_without_VAT' => '£',
		'symbol_left_VAT' => '£',
		'symbol_right_with_VAT' => '',
		'symbol_right_without_VAT' => '',
		'symbol_right_VAT' => '',
		'decimal_separator' => '.',
		'thousands_separator' => ',',
		'decimal_places_with_VAT' => 2,
		'decimal_places_without_VAT' => 2,
		'decimal_places_VAT' => 2,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 2,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'SEK',
		'symbol_left_with_VAT' => 'kr',
		'symbol_left_without_VAT' => 'kr',
		'symbol_left_VAT' => 'kr',
		'symbol_right_with_VAT' => '',
		'symbol_right_without_VAT' => '',
		'symbol_right_VAT' => '',
		'decimal_separator' => ',',
		'thousands_separator' => '_',
		'decimal_places_with_VAT' => 0,
		'decimal_places_without_VAT' => 0,
		'decimal_places_VAT' => 0,
		'round_precision_without_VAT' => 0,
		'round_precision_VAT' => 0,
		'round_precision_with_VAT' => 0,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'ALL',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_LEK',
		'symbol_right_without_VAT' => '_LEK',
		'symbol_right_VAT' => '_LEK',
		'decimal_separator' => ',',
		'thousands_separator' => '.',
		'decimal_places_with_VAT' => 0,
		'decimal_places_without_VAT' => 0,
		'decimal_places_VAT' => 0,
		'round_precision_without_VAT' => 0,
		'round_precision_VAT' => 0,
		'round_precision_with_VAT' => 0,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'TRY',
		'symbol_left_with_VAT' => '₺',
		'symbol_left_without_VAT' => '₺',
		'symbol_left_VAT' => '₺',
		'symbol_right_with_VAT' => '',
		'symbol_right_without_VAT' => '',
		'symbol_right_VAT' => '',
		'decimal_separator' => ',',
		'thousands_separator' => '.',
		'decimal_places_with_VAT' => 0,
		'decimal_places_without_VAT' => 0,
		'decimal_places_VAT' => 0,
		'round_precision_without_VAT' => 0,
		'round_precision_VAT' => 0,
		'round_precision_with_VAT' => 0,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'MKD',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_Den',
		'symbol_right_without_VAT' => '_Den',
		'symbol_right_VAT' => '_Den',
		'decimal_separator' => '.',
		'thousands_separator' => ',',
		'decimal_places_with_VAT' => 0,
		'decimal_places_without_VAT' => 0,
		'decimal_places_VAT' => 0,
		'round_precision_without_VAT' => 0,
		'round_precision_VAT' => 0,
		'round_precision_with_VAT' => 0,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'MDL',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_mdl',
		'symbol_right_without_VAT' => '_mdl',
		'symbol_right_VAT' => '_mdl',
		'decimal_separator' => ',',
		'thousands_separator' => '',
		'decimal_places_with_VAT' => 0,
		'decimal_places_without_VAT' => 0,
		'decimal_places_VAT' => 0,
		'round_precision_without_VAT' => 0,
		'round_precision_VAT' => 0,
		'round_precision_with_VAT' => 0,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'RSD',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_RSD',
		'symbol_right_without_VAT' => '_RSD',
		'symbol_right_VAT' => '_RSD',
		'decimal_separator' => ',',
		'thousands_separator' => '.',
		'decimal_places_with_VAT' => 0,
		'decimal_places_without_VAT' => 0,
		'decimal_places_VAT' => 0,
		'round_precision_without_VAT' => 0,
		'round_precision_VAT' => 0,
		'round_precision_with_VAT' => 0,
		'exchange_rates' => [
		],
	],
	[
		'code' => 'UAH',
		'symbol_left_with_VAT' => '',
		'symbol_left_without_VAT' => '',
		'symbol_left_VAT' => '',
		'symbol_right_with_VAT' => '_ грн',
		'symbol_right_without_VAT' => '_ грн',
		'symbol_right_VAT' => '_ грн',
		'decimal_separator' => ',',
		'thousands_separator' => '_',
		'decimal_places_with_VAT' => 0,
		'decimal_places_without_VAT' => 0,
		'decimal_places_VAT' => 0,
		'round_precision_without_VAT' => 0,
		'round_precision_VAT' => 0,
		'round_precision_with_VAT' => 0,
		'exchange_rates' => [
		],
	],
];
