<?php
use Jet\MVC_View;
use Jet\Form;
use Jet\Locale;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Locale $locale
 */
$form = $this->getRaw('form');
$locale = $this->getRaw('locale');
$locale = $locale->toString();

$form->field('/description/'.$locale.'/URL_path_part')->setIsReadonly(true);
?>

<?=$form->field('/description/'.$locale.'/name');?>
<?=$form->field('/description/'.$locale.'/description');?>
<?=$form->field('/description/'.$locale.'/URL_path_part');?>
