<?php
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var EShop $eshop
 */
$form = $this->getRaw('form');
$eshop = $this->getRaw('eshop');
$eshop_key = $eshop->getKey();

$form->field('/eshop_data/'.$eshop_key.'/URL_path_part')->setIsReadonly(true);
?>

<?=$form->field('/eshop_data/'.$eshop_key.'/name');?>
<?=$form->field('/eshop_data/'.$eshop_key.'/description');?>
<?=$form->field('/eshop_data/'.$eshop_key.'/URL_path_part');?>
