<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Analytics\Service\JetAnalytics;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;

/**
 * @var MVC_View $this
 * @var Main $module
 * @var Report $report
 * @var Session $session
 * @var Report_SessionListing $listing
 * @var Form $filter_form
 */

$module = $this->getRaw('module');
$report = $this->getRaw('report');
$listing = $this->getRaw('listing');

$filter_form = $this->getRaw('filter_form');

$session = $this->getRaw('session');
if(!$session):
	$filter_form->renderer()->setDefaultLabelWidth([
		Form_Renderer::LJ_SIZE_MEDIUM => 1
	]);
	$filter_form->renderer()->setDefaultFieldWidth([
			Form_Renderer::LJ_SIZE_MEDIUM => 11
	]);
	$filter_form->field('what')->input()->addJsAction('onchange', 'this.form.submit();');
	$filter_form->field('source')->input()->addJsAction('onchange', 'this.form.submit();');
	?>
	<h2><?=Tr::_('Sessions list')?></h2>

	<div class="card card-body">
		<?=$filter_form->start()?>
		<?=$filter_form->field('what')?>
		<?=$filter_form->field('source')?>
		<?=$filter_form->end()?>
	</div>
	<?php
	echo $listing->getGrid();
	return;
endif;

?>
<div class="toolbar">
	<?=UI::button_goBack()->setUrl(Http_Request::currentURI(unset_GET_params: ['session_id']))?>
</div>

<div>
	<?=$module->renderSessionDetails( $session );?>
</div>
