<?php
namespace JetApplicationModule\Admin\Payment\Methods;


use JetApplication\Admin_Managers;
use JetApplication\Payment_Method;

use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use JetApplication\Payment_Method_Option;
use JetApplication\Shops_Shop;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Payment_Method     $payment_method
 * @var Payment_Method_Option    $new_option
 */

$option = $this->getRaw('payment_method_option');

$form = $option->getEditForm();

$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 1 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );

?>
<?=$form->start()?>
	<div class="row toolbar" id="main-toolbar">
		<div class="col-md-12">
			<?=UI::button_goBack()?>

			<?=UI::button_save()?>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12" id="main-col">
			<?=$this->getRaw('tabs')?>

			<br/>

			<?=$this->getRaw('option_tabs')?>

			<br/>

			<?=$form->field('code')?>
			
			<?php
			Admin_Managers::UI()->renderShopDataBlocks(
				form: $form,
				renderer: function( Shops_Shop $shop, string $shop_key ) use ($form) : void {
					?>
					<?=$form->field('/shop_data/'.$shop_key.'/is_active_for_shop')?>
					<?=$form->field('/shop_data/'.$shop_key.'/title')?>
					<?=$form->field('/shop_data/'.$shop_key.'/description')?>
				<?php }); ?>
			

		</div>
	</div>
<?=$form->end()?>