<?php
namespace JetShopModule\Admin\Payment\Methods;


use Jet\Tr;
use JetShop\Payment_Method;

use Jet\UI;
use Jet\Mvc_View;
use Jet\Form;
use JetShop\Payment_Method_Option;
use JetShop\Shops;

/**
 * @var Mvc_View $this
 * @var Form     $form
 * @var Payment_Method     $payment_method
 * @var Payment_Method_Option    $new_option
 */

$option = $this->getRaw('payment_method_option');

$form = $option->getEditForm();

$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 1 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 4 ] );

?>
<?=$form->start()?>
	<div class="row toolbar" id="main-toolbar">
		<div class="col-md-12">
			<?=UI::button_goBack()?>

			<?=UI::button_save()?>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12" id="main-col">
			<?=$this->getRaw('tabs')?>

			<br/>

			<?=$this->getRaw('option_tabs')?>

			<br/>

			<?=$form->field('code')?>

			<?php foreach(Shops::getList() as $shop):
				$shop_code = $shop->getCode();
				$shop_data = $option->getShopData( $shop_code );
				?>
				<?=$shop_data->renderShopDataBlock_start()?>
				<?=$form->field('/shop_data/'.$shop_code.'/is_active')?>
				<?=$form->field('/shop_data/'.$shop_code.'/title')?>
				<?=$form->field('/shop_data/'.$shop_code.'/description')?>
				<?=$shop_data->renderShopDataBlock_end()?>
			<?php endforeach; ?>

		</div>
	</div>
<?=$form->end()?>