<?php
use Jet\Tr;
use Jet\UI;

require_once 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html>
<head>
	<title><?=$this->getString( 'page_title', 'Jet Shop admin' )?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>
</head>
<body>
<script type="text/javascript">
	$(document).ready(function () {
		UI.mainToolbarPin();
	});
</script>
<jet_module module="Admin.UI" action="main_menu"/>
<jet_module module="Admin.UI" action="breadcrumb_navigation"/>

<div class="container-fluid h-100">
	<div class="row">
		<div class="col-md-12" id="system-messages-area">
			<jet_module module="Admin.UI" action="messages"/>
		</div>
	</div>

	<jet_layout_main_position/>
</div>



<div id="__progress__">
	<div class="loading text-center">
		<div id="__progress_prc__"></div>
		<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>
		<span class="sr-only"><?= Tr::_( 'Loading ...' ); ?></span>
	</div>
</div>

<?php
$dialog = UI::dialog('image_delete_confirm', Tr::_('Do you really want to delete this image?', [], Tr::COMMON_DICTIONARY) );

echo $dialog->start();
?>
<div align="center">
	<div class="image-thumbnail"  id="image_delete_confirm_thb" style="width:200px;height:200px;">
	</div>
</div>
<?php
echo $dialog->footer();
echo UI::button( Tr::_('No', [], Tr::COMMON_DICTIONARY) )->setOnclick("Images.deleteImageReject();");
echo UI::button_delete()->setOnclick("Images.deleteImageConfirm();");
echo $dialog->end();
?>


</body>
</html>