<?php
use Jet\Tr;

require_once 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html>
<head>
	<title><?=$this->getString( 'page_title', 'Jet Shop admin' )?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>

	<link rel="icon" href="data:image/png;base64,iVBORw0KGgo=">
</head>
<body>
<script type="text/javascript">
	$(document).ready(function () {
		UI.mainToolbarPin();
	});
</script>
<jet_module module="Admin.UI" action="main_menu"/>
<jet_module module="Admin.UI" action="breadcrumb_navigation"/>

<div id="system-messages-area">
	<jet_module module="Admin.UI" action="messages"/>
</div>

<jet_layout_main_position/>


<div id="__progress__">
	<div class="loading text-center">
		<div id="__progress_prc__"></div>
		<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>
		<span class="sr-only"><?= Tr::_( 'Loading ...' ); ?></span>
	</div>
</div>


<style>
	#nav_buttons {
		position: fixed;
		bottom:10px;
		right:10px;
		display: grid;
		grid-template-columns: 40px 40px;
		grid-template-rows: 40px;
		gap: 10px;
	}

	#nav_buttons>div {
		background-color:#f9f9f9;
		border:1px #aaaaaa solid;
		color: #aaaaaa;
		border-radius:0;
		cursor:pointer;
		transition: all;
		transition-duration: 0.2s;
		opacity: 0.4;
		font-size: 20px;
		text-align: center;
		padding-top: 5px;
	}

	#nav_buttons>div:hover {
		background-color:#000000;
	}
	
</style>
<script>
	document.addEventListener('scroll', function (e) {
		if(window.scrollY>800) {
			$('#nav_buttons').fadeIn();
		} else {
			$('#nav_buttons').fadeOut();
		}
	});
</script>

<div id="nav_buttons" style="display: none;">
	<div id="nav_to_the_top" onclick="$('html, body').animate({scrollTop: 0}, 400);">&#11205;</div>
	<div id="nav_to_the_bottom" onclick="$('html, body').animate({scrollTop: $(document).height()}, 400);">&#11206;</div>
</div>

</body>
</html>