<?php

require_once 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html>
<head>
	<title><?=$this->getString( 'page_title', 'Jet Shop admin' )?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	
	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>

	<link rel="icon" href="data:image/png;base64,iVBORw0KGgo=">
</head>
<body>

	<jet_layout_main_position/>

</body>
</html>