<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\OrderDispatch\CustomDispatch;


use Jet\MVC_View;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Application_Service_Admin;

/**
 * @var MVC_View   $this
 */

$items = $this->getRaw('items');
if(!$items) {
	return;
}

$items = json_decode($items, true);

if(!is_array($items)) {
	return;
}

?>
<table class="table table-striped">
	<?php foreach($items as $id=>$qty):
		$id = (int)$id;
		$qty = (int)$qty;
		?>
	<tr>
		<td style="width: 80px">
			<?=UI::button_delete(' ')->setOnClick("CustomOD.removeItem({$id})")->setSize(UI_button::SIZE_EXTRA_SMALL)?>
		</td>
		<td style="width: 80px"><?=$qty?>x</td>
		<td><?=Application_Service_Admin::Product()->renderItemName( $id )?></td>
	</tr>
	<?php endforeach; ?>
</table>
