<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\CashDesk;


use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;
?>
	<?=UI_messages::createInfo(Tr::_('Place order as an unregistered client. Unfortunately, this <strong> loses your loyalty discount </strong>'))?>
	<?=UI::button(Tr::_('Change'))->setOnclick("CashDesk.customer.registration.back();")->setClass('link')?>
