<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;
use JetApplication\CashDesk;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');

$form = $cash_desk->getSetPasswordForm();

$form->renderer()->addJsAction('onsubmit', "CashDesk.customer.registration.setPassword();return false;");

require 'email_and_phone_has_been_set.phtml';

$password = $form->field('password');
$password->renderer()->setCustomRenderer(function() use ( $password, $cash_desk ) {
	?>
	<div class="form-field">
		<label><?=$password->getLabel()?></label>
		<div><?=$password->input().$password->error()?></div>
	</div>
	<?php
});

$password_confirm = $form->field('password_confirm');
$password_confirm->renderer()->setCustomRenderer(function() use ( $password_confirm, $cash_desk ) {
	?>
	<div class="form-field">
		<label><?=$password_confirm->getLabel()?></label>
		<div><?=$password_confirm->input().$password_confirm->error()?></div>
	</div>
	<?php
});

?>


	<div class="step-title"><?=Tr::_('Now choose a password')?></div>

	<div>
		<?=$form->start()?>
			<?=$form->field('password')?>
			<?=$form->field('password_confirm')?>
		
		
			<div class="continue-button-area">
				<?=UI::button(Tr::_('Continue without registration'))->setClass('link')->setOnclick("visibility.show('no_register_area'); return false;")?>
				<?=UI::button('Continue')->setClass('primary')->setType('submit')?>
			</div>
		<?=$form->end()?>

	</div>


	<div id="no_register_area" style="display: none;">
		<br>
		<?=UI_messages::createInfo(Tr::_('<b>Warning! </b> If you place an order as an unregistered client, you will lose a loyalty discount.'))?>
		
		<div class="continue-button-area">
		<?=UI::button(Tr::_('Continue without registration'))->setClass('link')->setOnclick("CashDesk.customer.registration.doNotRegister();")?>
		</div>
	</div>

