<?php
namespace JetApplication;

use JetShop\Core_Admin_Managers_WarehouseManagementOverview;

interface Admin_Managers_WarehouseManagementOverview extends Core_Admin_Managers_WarehouseManagementOverview
{

}