<?php
use JetApplication\Shops_Shop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Shops_Shop $shop
 */
$form = $this->getRaw('form');
$shop = $this->getRaw('shop');
$shop_key = $shop->getKey();

$form->field('/shop_data/'.$shop_key.'/url_param')->setIsReadonly(true);
?>
<fieldset>
	<legend class="sub"><?=Tr::_('Main data')?></legend>
	
	<?=$form->field('/shop_data/'.$shop_key.'/name');?>
	<?=$form->field('/shop_data/'.$shop_key.'/second_name');?>
	<?=$form->field('/shop_data/'.$shop_key.'/description');?>
	<?=$form->field('/shop_data/'.$shop_key.'/url_param');?>
</fieldset>
<fieldset>
	<legend class="sub"><?=Tr::_('SEO')?></legend>
	
	<?=$form->field('/shop_data/'.$shop_key.'/seo_title');?>
	<?=$form->field('/shop_data/'.$shop_key.'/seo_description');?>
	<?=$form->field('/shop_data/'.$shop_key.'/seo_keywords');?>
</fieldset>
