<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\UI;
use Jet\UI_button;

/**
 * @var MVC_View $this
 */

if($this->getBool('container')):
	echo '<div id="compare_btn_'.$this->getInt('id').'">';
endif;

echo UI::button(' ')
	->setIcon('scale')
	->setClass( UI_button::CLASS_SECONDARY )
	->addCustomCssClass('product_listing_item_compare_button_selected')
	->setOnClick("Compare.unselect({$this->getInt('id')})");

if($this->getBool('container')):
	echo '</div>';
endif;
