<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\OAuth\Backend\Facebook;


use Jet\Form;
use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;
use JetApplication\EShop_Managers;


/**
 * @var MVC_View $this
 * @var Form $form
 */

$form = $this->getRaw('form');

$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 10
]);
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 2
]);

$register_URL = EShop_Managers::OAuth()->getOAuthModules()[Main::OAUTH_SERVICE_ID]->getHandlerUrl();



foreach( UI_messages::get(context: 'CC') as $message ):
	echo $message;
endforeach;

echo $form->getCommonMessage();

$message = UI_messages::createInfo( Tr::_('Please register the following URL in Google OAuth: <b>%URL%</b>', ['URL'=>$register_URL]) );
$message->setCloseable( false );

echo '<br>'.$message.'<hr>';

echo $form->start();

echo $form->field('client_id');
echo $form->field('client_secret');
echo $form->field('oauth_endpoint_URL');
echo $form->field('token_endpoint_URL');
echo $form->field('user_detail_endpoint_URL');
?>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<?=UI::button_save()?>
		</div>
	</div>
	<?php
echo $form->end();