<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Discounts\CodesDefinition;


use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );


echo $form->field( 'eshop' );
echo $form->field( 'code' );
echo $form->field( 'internal_notes' );
echo $form->field( 'active_from' );
echo $form->field( 'active_till' );
echo $form->field( 'minimal_order_amount' );
echo $form->field( 'number_of_codes_available' );
echo $form->field( 'discount_type' );
echo $form->field( 'discount' );
echo $form->field( 'do_not_combine' );
echo $form->field( 'relevance_mode' );


