<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\OrderPersonalReceipt\DoPersonalReceipt;


use Jet\Http_Request;
use Jet\Mvc_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\OrderPersonalReceipt;

/**
 * @var Mvc_View $this
 * @var OrderPersonalReceipt $dispatch
 */

$dispatch = $this->getRaw('dispatch');


echo UI::button(Tr::_('Confirm cancellation'))
	->setUrl( Http_Request::currentURI(['action'=>'confirm_cancellation']) )
	->setClass( UI_button::CLASS_INFO );


