<?php
namespace JetApplicationModule\Admin\OrderPersonalReceipt\DoPersonalReceipt;

use Jet\Http_Request;
use Jet\Mvc_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\OrderPersonalReceipt;

/**
 * @var Mvc_View $this
 * @var OrderPersonalReceipt $dispatch
 */

$dispatch = $this->getRaw('dispatch');

echo UI::button(Tr::_('Handed over'))->setUrl( Http_Request::currentURI(['action'=>'handed_over']) )
		->setClass( UI_button::CLASS_SUCCESS );

