<?php
namespace JetApplicationModule\Discounts\Code;

use Jet\MVC_View;
use JetApplication\Discounts_Code;

/**
 * @var MVC_View   $this
 * @var Discounts_Code|null $used_code
 * @var Main $module
 */

$module = $this->getRaw('module');
$used_code = $this->getRaw('used_code');


require 'shopping_cart/js.phtml';
?>

<div id="discount_code_area">
	<?php
	require 'shopping_cart/used-codes.phtml';
	require 'shopping_cart/form.phtml';
	?>
</div>
