<?php
return [
	[
		'code' => 'CZK',
		'symbol_left' => '',
		'symbol_right' => 'Kč',
		'decimal_separator' => ',',
		'thousands_separator' => '',
		'decimal_places' => 0,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 0,
		'exchange_rates' => [
			'EUR' => 0.039,
			'HUF' => 15.5,
			'ZLO' => 1.0,
		],
	],
	[
		'code' => 'EUR',
		'symbol_left' => '',
		'symbol_right' => '€',
		'decimal_separator' => ',',
		'thousands_separator' => '',
		'decimal_places' => 2,
		'round_precision_without_VAT' => 2,
		'round_precision_VAT' => 2,
		'round_precision_with_VAT' => 1,
		'exchange_rates' => [
			'CZK' => 25.43,
			'HUF' => 394.07,
		],
	],
	[
		'code' => 'HUF',
		'symbol_left' => '',
		'symbol_right' => 'Huf',
		'decimal_separator' => '',
		'thousands_separator' => '',
		'decimal_places' => 0,
		'round_precision_without_VAT' => 0,
		'round_precision_VAT' => 0,
		'round_precision_with_VAT' => 0,
		'exchange_rates' => [
			'CZK' => 0.065,
			'EUR' => 0.0025,
		],
	],
	[
		'code' => 'ZLO',
		'symbol_left' => '',
		'symbol_right' => 'Zl',
		'decimal_separator' => '',
		'thousands_separator' => '',
		'decimal_places' => 0,
		'round_precision_without_VAT' => 0,
		'round_precision_VAT' => 0,
		'round_precision_with_VAT' => 0,
		'exchange_rates' => [
		],
	],
];
