<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Form;
use Jet\MVC_View;

use JetShop\Shops;

use JetShop\Parametrization_Group_ShopData;
use JetShop\Parametrization_Group;

/**
 * @var MVC_View   $this
 * @var Parametrization_Group $new_group
 * @var Form $form
 */
$group = Controller_Main::getCurrentParamGroup();


echo $this->render('lj_start');

	foreach(Shops::getList() as $shop):
		echo $group->getShopData( $shop )->renderImageWidgets( Parametrization_Group_ShopData::getImageClasses(), !$group->getEditForm()->getIsReadonly() );
	endforeach;

echo $this->render('lj_end');