<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Form;
use Jet\Tr;
use Jet\MVC_View;

use JetShop\Shops;

use JetShop\Parametrization_Group;

/**
 * @var MVC_View   $this
 * @var Parametrization_Group $new_group
 * @var Form $form
 */
$group = Controller_Main::getCurrentParamGroup();

$form = $group->getEditForm();
$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 1
]);

?>
<?=$this->render('lj_start')?>
	<br/>
<?php if($group->isInherited()): ?>
	<h4 class="inherited"><?=Tr::_('Inherited')?></h4>
<?php endif; ?>

		<?php
		echo $form->start();

		echo $form->field('is_active');
		echo $form->field('allow_display');
		echo $form->field('allow_filter');
		echo $form->field('allow_compare');

		foreach(Shops::getList() as $shop):
			$shop_key= $shop->getKey();
			$shop_data = $group->getShopData( $shop );

			echo $shop_data->renderShopDataBlock_start();
				echo $form->field('/shop_data/'.$shop_key.'/is_active');
				echo $form->field('/shop_data/'.$shop_key.'/label');
				echo $form->field('/shop_data/'.$shop_key.'/description');
			echo $shop_data->renderShopDataBlock_end();
		endforeach;

		echo $form->end();
		?>

<?=$this->render('lj_end')?>