<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\Form;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Form $form
 */
$form = $this->getRaw('form');

$form->field('delivery_methods')->input()->addCustomCssStyle('height: 400px');

$is_default = $form->field('is_default');
if($is_default->getValue()) {
	$is_default->setIsReadonly(true);
}
?>
<?=$form->field( 'is_default' )?>
<?=$form->field( 'delivery_methods' )?>
