<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Orders;


use Jet\Form;
use Jet\Http_Request;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

use Jet\MVC_View;
use Jet\UI_dialog;
use JetApplication\Order;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Order $order
 */

$order = $this->getRaw('order');
if(
	!main::getCurrentUserCanEdit() ||
	$order->getDelivered() ||
	$order->getDispatched()
) {
	return;
}

if( !$order->getReadyForDispatch() ):
	/*
	$dialog = new UI_dialog(
		id: 'set_is_ready_for_dispatch_dialog',
		title: Tr::_('Set order as ready for dispatch?'),
		size: UI_dialog::SIZE_DEFAULT
	);

	echo $dialog->start();
	echo Tr::_('Do you really want to set order as ready for dispatch?');
	echo $dialog->footer();
	echo UI::button( Tr::_('Yes, let\'s do it.') )
		->setUrl(Http_Request::currentURI(set_GET_params: ['dispatch_action'=>'set_ready']))
		->setClass(UI_button::CLASS_PRIMARY);
	echo $dialog->end();
	*/
	return;

endif;

if( !$order->getDispatchStarted() ):
	
	/*
	$dialog = new UI_dialog(
		id: 'set_not_ready_for_dispatch_dialog',
		title: Tr::_('Set order as not ready for dispatch?'),
		size: UI_dialog::SIZE_DEFAULT
	);
	
	echo $dialog->start();
	echo Tr::_('Do you really want to set order as not ready for dispatch?');
	echo $dialog->footer();
	echo UI::button( Tr::_('Yes, let\'s do it.') )
		->setUrl(Http_Request::currentURI(set_GET_params: ['dispatch_action'=>'set_not_ready']))
		->setClass(UI_button::CLASS_PRIMARY);
	echo $dialog->end();
	*/
	
	
	$dialog = new UI_dialog(
		id: 'start_dispatch_dialog',
		title: Tr::_('Start order dispatch?'),
		size: UI_dialog::SIZE_DEFAULT
	);
	
	echo $dialog->start();
	echo Tr::_('Do you really want to start order dispatch?');
	echo $dialog->footer();
	echo UI::button( Tr::_('Yes, let\'s do it.') )
		->setUrl(Http_Request::currentURI(set_GET_params: ['dispatch_action'=>'start_dispatch']))
		->setClass(UI_button::CLASS_PRIMARY);
	echo $dialog->end();
	
	
	return;
endif;

$dialog = new UI_dialog(
	id: 'cancel_dispatch_dialog',
	title: Tr::_('Cancel order dispatch?'),
	size: UI_dialog::SIZE_DEFAULT
);

echo $dialog->start();
echo Tr::_('Do you really want to cancel dispatch?');
echo $dialog->footer();
echo UI::button( Tr::_('Yes, let\'s do it.') )
	->setUrl(Http_Request::currentURI(set_GET_params: ['dispatch_action'=>'cancel_dispatch']))
	->setClass(UI_button::CLASS_PRIMARY);
echo $dialog->end();

