<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\OrderPersonalReceipt\Overview;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\OrderPersonalReceipt;

/**
 * @var MVC_View $this
 * @var OrderPersonalReceipt $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::Context()->showContext( $item->getContext() );
