<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\OrderPersonalReceipt\Overview;

use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\OrderPersonalReceipt;

/**
 * @var MVC_View $this
 * @var OrderPersonalReceipt $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::OrderPersonalReceipt()->showOrderPersonalReceiptStatus( $item );
