<?php
use Jet\Form;
use Jet\MVC_View;


/**
 * @var MVC_View $this
 * @var Form $form
 */
$form = $this->getRaw('form');

echo $form->field('backend_module_name');
echo $form->field('company_name');
echo $form->field('company_id');
echo $form->field('company_vat_id');
echo $form->field('address_street_and_no');
echo $form->field('address_town');
echo $form->field('address_town');
echo $form->field('address_zip');
echo $form->field('address_country');
echo $form->field('locale');
echo $form->field('phone_1');
echo $form->field('phone_2');
echo $form->field('email_1');
echo $form->field('email_2');
echo $form->field('currency_code');