<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Orders;


use Jet\Form;
use Jet\Mvc_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Order;

/**
 * @var Mvc_View $this
 * @var Order $order
 * @var Form $form
 */
$order = $this->getRaw( 'item' );

$form = $this->getRaw('change_payment_method_form');
if(!$form) {
	return;
}


echo $form->start();

foreach($form->getFields() as $field) {
	echo $field;
}

?>
</div>
<div class="modal-footer">
<?php
echo UI::button_save(Tr::_('Update'));


echo $form->end();


