<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Entity\Edit;


use JetApplication\EShopEntity_Admin_Interface;
use JetApplication\EShopEntity_WithEShopData;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;

/**
 * @var MVC_View   $this
 * @var EShopEntity_WithEShopData|EShopEntity_Admin_Interface     $item
 */
$item = $this->getRaw( 'item' );
?>
<div class="col d-flex justify-content-center">

	<div class="card" style="margin-top:50px;">
		<div class="card-body">
			<p>
				<?=$this->getRaw('message')?>
				<br/>
				<a href="<?=$item->getEditUrl();?>" style="font-weight: bolder;font-size: 20px;"><?=$item->getAdminTitle();?></a>
			</p>

			<div style="display: inline-block;width: 50%">
				<?= UI::button_goBack()->setUrl(Http_Request::currentURI(unset_GET_params: ['id', 'action'])) ?>
			</div>
			<div style="display: inline-block;width: 45%;text-align: right">
				<form action="<?= Http_Request::currentURI() ?>" method="post">
					<input type="hidden" name="delete" value="yes">
					<?= UI::button_delete()->setType( 'submit' ) ?>
				</form>
			</div>
		</div>
	</div>
</div>
