<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Edit;


use Jet\Tr;
use JetApplication\Admin_EntityManager_Module;
use JetApplication\Admin_Managers;
use JetApplication\EShopEntity_Admin_Interface;
use JetApplication\EShopEntity_CanNotBeDeletedReason;
use JetApplication\EShopEntity_WithEShopData;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var EShopEntity_WithEShopData|EShopEntity_Admin_Interface     $item
 * @var EShopEntity_CanNotBeDeletedReason[] $reasons
 */
$item = $this->getRaw( 'item' );
$reasons = $this->getRaw('reasons');
?>
<div class="col d-flex justify-content-center">
	
	<div class="card" style="margin-top:50px;">
		<div class="card-body">
			<div style="margin: 20px;">
				<?=$this->getRaw('message')?>
				<br/>
				<a href="<?=$item->getEditUrl();?>" style="font-weight: bolder;font-size: 20px;"><?=$item->getInternalName();?> (<?=$item->getId();?>)</a>
			</div>
			
			<div>
				<?php foreach($reasons as $reason):
					if(
						!($manager_ifc = $reason->getEntityDefinitio()->getAdminManagerInterface()) ||
						!($manager = Admin_Managers::get( $manager_ifc ))
					) {
						continue;
					}
					
					/**
					 * @var Admin_EntityManager_Module $manager
					 */
					?>
				<div style="margin-bottom: 20px;" class="card card-body">
					<div style="padding: 10px;font-weight: bolder;"><?=Tr::_($reason->getReason(), dictionary: $manager->getModuleManifest()->getName() )?></div>
					<div style="padding: 5px;padding-left: 15px;padding-right: 15px;">
						<?php
						$limit = 50;
						$c = 0;
						foreach($reason->getEntityIds() as $id):
							$c++;
							?>
							<div style="padding: 3px"><?=$manager->renderItemName( $id ) ?></div>
							<?php
							if(
								$c==$limit &&
								count($reason->getEntityIds())>$limit
							): ?>
								<div style="padding: 3px"><?=Tr::_('... and more (%TOTAL% in total)', ['TOTAL'=>count($reason->getEntityIds())],dictionary: Tr::COMMON_DICTIONARY)?></div>
								<?php
								break;
							endif;
						endforeach; ?>
					</div>
				</div>
				<?php endforeach; ?>
			</div>
			
			<div style="display: inline-block;width: 50%">
				<?= UI::button_goBack()->setUrl(Http_Request::currentURI(unset_GET_params: ['id', 'action'])) ?>
			</div>
		</div>
	</div>
</div>
