<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\WarehouseManagement\LossOrDestruction;


use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Application_Service_Admin;
use JetApplication\Supplier_GoodsOrder;
use JetApplication\WarehouseManagement_LossOrDestruction;
use JetApplication\WarehouseManagement_Warehouse;

/**
 * @var MVC_View   $this
 * @var WarehouseManagement_LossOrDestruction $rcp
 * @var Controller_Main $controller
 * @var Supplier_GoodsOrder $order
 */

$controller = $this->getController();

$order_number = $this->getString('order_number');
$order = $this->getRaw('order');


$rcp = $this->getRaw('item');



$form = $rcp->getEditForm();
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 1
]);
$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 8
]);

$form->field('notes')->input()->addCustomCssStyle("height: 500px");
?>
<div id="main-col">
	<?=$form->start()?>

	<div class="card card-body" style="margin: 10px;">
		<div class="row">
			<div class="col-md-1" style="padding: 15px"><?=Tr::_('Warehouse:')?></div>
			<div class="col-md-8" style="font-weight: bolder;padding: 15px;"><?=WarehouseManagement_Warehouse::getScope()[$rcp->getWarehouseId()]?></div>
		</div>
		<div class="row">
			<div class="col-md-1" style="padding: 15px"><?=Tr::_('Product:')?></div>
			<div class="col-md-8" style="font-weight: bolder;padding: 15px;">
				<?=Application_Service_Admin::Product()->renderItemName( $rcp->getProductId() )?>
			</div>
		</div>
		<div class="row">
			<div class="col-md-1" style="padding: 15px"><?=Tr::_('Price per unit:')?></div>
			<div class="col-md-8" style="font-weight: bolder;padding: 15px;">
				<?=Application_Service_Admin::PriceFormatter()->formatWithCurrency_WithoutVAT( $rcp->getCurrency(), $rcp->getPricePerUnit() )?> / <?=$rcp->getMeasureUnit()?->getName()?>
			</div>
		</div>
		<div class="row">
			<div class="col-md-1" style="padding: 15px"><?=Tr::_('Total:')?></div>
			<div class="col-md-8" style="font-weight: bolder;padding: 15px;">
				<?=Application_Service_Admin::PriceFormatter()->formatWithCurrency_WithoutVAT( $rcp->getCurrency(), ($rcp->getNumberOfUnits() * $rcp->getPricePerUnit()) )?>
			</div>
		</div>
		
		
		<?=$form->field('date')?>
		<?=$form->field('number_of_units')?>
		<?=$form->field('notes')?>
		
		<div class="row">
			<div class="col-md-1" style="padding: 15px"></div>
			<div class="col-md-8" style="padding: 15px;">
				<?=$rcp->getStatus()->showAdmin()?>
			</div>
		</div>
	</div>

	
	<br><br><br>
	<?=$form->start()?>
</div>
	
