<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Catalog;


use Jet\MVC_View;
use JetApplication\ProductListing;
use JetApplication\EShops;


/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$eshop = EShops::getCurrent();
$listing = $this->getRaw('listing');

$filter = $listing->getFilter()->getBasicFilter();
