<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\Catalog;


use Jet\MVC_View;
use JetApplication\ProductListing;
use JetApplication\Property_EShopData;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');

$properties = $listing->getProperties();

if(!$properties) {
	return;
}



foreach($properties as $property):
	
	/**
	 * @var Property_EShopData $property
	 */
	
	$this->setVar('property', $property);

	$filter = $this->render('filter/properties/'.$property->getType());
	if(!$filter) {
		continue;
	}
	?>
	<div class="product_listing_filter">
		<div
			id="f_property_<?=$property->getId()?>_title"
			class="product_listing_filter_title"
			data-target="f_property_<?=$property->getId()?>"
			onclick="listing.UI.toggleFilterItem(this)"
		><?=$property->getLabel()?></div>
	
		<div
			class="product_listing_filter_filter"
			id="f_property_<?=$property->getId()?>"
			style="display: none;"
			onscroll="listing.UI.filterContainerScroll( this )"
		>
			<?=$filter?>
		</div>
	</div>
<?php endforeach;
