<?php
namespace JetShopModule\Admin\Catalog\Properties;

use JetShop\KindOfProduct;
use JetShop\Property;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Property $property
 * @var KindOfProduct[] $kinds
 */
$property = $this->getRaw( 'property' );
$kinds = $this->getRaw('kinds');

?>
<div class="col d-flex justify-content-center">
	
	<div class="card" style="margin-top:50px;">
		<div class="card-body">
			<p>
				<?=Tr::_( 'It is mot possible tp delete this property.' );?>
				<br/>
				<a href="<?=$property->getEditURL();?>" style="font-weight: bolder;font-size: 20px;"><?=$property->getInternalName();?> (<?=$property->getId();?>)</a>
			</p>
			
			<p>
				<?=Tr::_( 'It is used by following kinds of product:' );?>
				<ul>
					<?php foreach($kinds as $kind): ?>
						<li><a href="<?=$kind->getEditURL()?>"><?=$kind->getInternalName()?></a></li>
					<?php endforeach; ?>
				</ul>
			</p>
			
			<div style="display: inline-block;width: 50%">
				<?= UI::button_goBack()->setUrl(Http_Request::currentURI(unset_GET_params: ['id', 'action'])) ?>
			</div>
		</div>
	</div>
</div>
