<?php
namespace JetShop;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var ProductListing_Filter_Params_Property_Number $filter_property
 */
$filter_property = $this->getRaw('filter_property');
$property = $filter_property->getProperty();

$property_id = $property->getId();

?>
<div class="filter-item-list">
	<div class="filter-item-option-box">
		<a href="javascript:ProductListing.filter.properties.bool.deactivate(<?=$property_id?>);">&times;</a>
		<span class="filter-item-text"><?= $property->getLabel() ?></span>
	</div>
</div>