<?php
namespace JetApplication;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var ProductListing_Filter_Params_Property_Bool $filter_property
 */
$filter_property = $this->getRaw('filter_property');
$property = $filter_property->getProperty();

$element_id = 'filter_property_'.$property->getId();

$count = $filter_property->getCount();
?>

<?php /* if( $property->getDescription() || $property->getImageMain() ): ?>
	<div class="group-sub-description-content">
		<?php if($property->getImageMain()): ?>
			<img src="<?= $property->getImageMainUrl();?>" />
		<?php endif; ?>
		<?= $property->getDescription();?>
	</div>
<?php endif; */ ?>

<div class="group-sub-content">

	<?php if(!$count && !$filter_property->isActive()): ?>
		<div class="item disabled">
			<span><input type="checkbox" id="<?= $element_id;?>" disabled="disabled" name="properties[<?= $property->getId();?>]" value="0" /></span>
			<label><?= $property->getLabel(); ?> [<?=$count;?>]</label>
		</div>
	<?php else: ?>
		<?php if($filter_property->isActive()): ?>
			<div class="item selected" onclick="ProductListing.filter.properties.bool.toggle(<?=$property->getId()?>);return false;">
				<span><input type="checkbox" id="<?= $element_id;?>" checked="checked"/></span>
				<label><a href="<?=$filter_property->generateURLWithout()?>"><?= $property->getLabel(); ?></a> (<?=$count;?>)</label>
			</div>
		<?php else: ?>
			<div class="item default" onclick="ProductListing.filter.properties.bool.toggle(<?=$property->getId()?>);return false;">
				<span><input type="checkbox" id="<?= $element_id;?>"/></span>
				<label><a href="<?=$filter_property->generateURLWith()?>"><?= $property->getLabel(); ?></a> (<?=$count;?>)</label>
			</div>
		<?php endif; ?>
	<?php endif;?>

	<div class="clear"></div>

</div>
