<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Catalog\ProductQuestions;


use Jet\MVC_View;
use JetApplication\ProductQuestion;

/**
 * @var MVC_View $this
 
 * @var ProductQuestion $item
 */

$item = $this->getRaw('item');
$listing = $this->getRaw('listing');

?>
<a href="<?=$listing->getEditUrl( $item );?>"><?=$item->getAuthorEmail();?></a>
<?php
