<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\ProductQuestions;


use Jet\MVC_View;
use Jet\UI_messages;
use JetApplication\ProductQuestion;

/**
 * @var MVC_View $this
 
 * @var ProductQuestion $item
 */

$item = $this->getRaw('item');
$listing = $this->getRaw('listing');

if($item->isSpam()) {
	echo UI_messages::createDanger('Spam')->setCloseable(false);
}