<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Marketing\Banners;


use Jet\MVC_View;
use Jet\Form;
use JetApplication\Marketing_Banner;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Marketing_Banner   $item
 */
$form = $this->getRaw( 'form' );
$item = $this->getRaw( 'item' );

$group = $item->getGroup();
?>

<?=$form->field('group_id')?>
<?php
	echo $form->field('text');
	echo $form->field('text_color');
?>
<?=$form->field('URL')?>


<?=$form->field('display_info');?>
<?=$form->field('nofollow')?>
<?=$form->field('open_in_new_window')?>

