<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Form_Renderer;
use Jet\Tr;
use Jet\MVC_View;
use JetShop\Category;
use JetShop\Shops;

/**
 * @var MVC_View   $this
 * @var Category   $new_category
 */

$new_category = $this->getRaw('new_category');
$form = $new_category->getAddForm();
$form->renderer()->setDefaultLabelWidth([Form_Renderer::LJ_SIZE_MEDIUM=>2]);
$form->renderer()->setDefaultFieldWidth([Form_Renderer::LJ_SIZE_MEDIUM=>8]);

?>


<?=$this->render('lj_start')?>
<br/>
<?=$form->start();?>
		<?php foreach(Shops::getList() as $shop):
			$shop_key = $shop->getKey();
			$shop_data = $new_category->getShopData( $shop );
			?>
			<?=$shop_data->renderShopDataBlock_start()?>

				<fieldset>
					<legend class="sub"><?=Tr::_('Main data')?></legend>

					<?=$form->field('/shop_data/'.$shop_key.'/is_active')?>

					<?=$form->field('/shop_data/'.$shop_key.'/name')?>
					<?=$form->field('/shop_data/'.$shop_key.'/second_name')?>
					<?=$form->field('/shop_data/'.$shop_key.'/description')?>
				</fieldset>

				<fieldset>
					<legend class="sub"><?=Tr::_('SEO')?></legend>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_h1')?>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_title')?>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_description')?>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_keywords')?>
					<?=$form->field('/shop_data/'.$shop_key.'/internal_fulltext_keywords')?>
				</fieldset>

			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach; ?>
<?=$form->end();?>

<?=$this->render('lj_end')?>

