<?php
namespace JetApplicationModule\Admin\Catalog\Categories;

use Jet\Form_Renderer;
use Jet\Tr;
use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Shops_Shop;

/**
 * @var MVC_View   $this
 * @var Category   $new_category
 */

$new_category = $this->getRaw('new_category');
$form = $new_category->getAddForm();
$form->renderer()->setDefaultLabelWidth([Form_Renderer::LJ_SIZE_MEDIUM=>2]);
$form->renderer()->setDefaultFieldWidth([Form_Renderer::LJ_SIZE_MEDIUM=>8]);

?>


<?=$this->render('lj_start')?>
<br/>
<?=$form->start();?>

	<?=Admin_Managers::UI()->renderEntityFormCommonFields( $form );?>

	<?php
	Admin_Managers::UI()->renderShopDataBlocks(
		form: $form,
		renderer: function( Shops_Shop $shop, string $shop_key ) use ($new_category, $form) : void {
			?>
			<fieldset>
				<legend class="sub"><?=Tr::_('Main data')?></legend>
				
				<?=$form->field('/shop_data/'.$shop_key.'/name')?>
				<?=$form->field('/shop_data/'.$shop_key.'/second_name')?>
				<?=$form->field('/shop_data/'.$shop_key.'/description')?>
			</fieldset>
			
			<fieldset>
				<legend class="sub"><?=Tr::_('SEO')?></legend>
				<?=$form->field('/shop_data/'.$shop_key.'/seo_title')?>
				<?=$form->field('/shop_data/'.$shop_key.'/seo_description')?>
				<?=$form->field('/shop_data/'.$shop_key.'/seo_keywords')?>
			</fieldset>
		<?php }); ?>

<?=$form->end();?>

<?=$this->render('lj_end')?>

