<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;


/**
 * @var MVC_View $this
 * @var Form     $form
 * @var EShop $eshop
 */

$eshop = $this->getRaw('eshop');
$form = $this->getRaw('form');
$eshop_key = $eshop->getKey();

$form->field('/eshop_data/'.$eshop_key.'/layout_txt')->input()->addCustomCssStyle('height:400px');
?>
<?=$form->field('/eshop_data/'.$eshop_key.'/layout_html')?>
<?=$form->field('/eshop_data/'.$eshop_key.'/layout_txt')?>
<br><br><br>
