<?php

use Jet\UI_tabsJS_tab;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var UI_tabsJS_tab $t
 */
$t = $this->getRaw( 'element' );


if($t->getIsSelected()) {
	$t->setBaseCssClass('tabs-tab active');
	
} else {
	$t->setBaseCssClass('tabs-tab');
}

$t->setId($GLOBALS['__current_js_tabs'].'_tab_'.$t->content()->getId());

?>
<li <?=$t->renderTagAttributes()?>><a onclick="tabs.select('<?=$GLOBALS['__current_js_tabs'];?>', '<?=$t->content()->getId()?>' );"><?= $t->getTitle() ?></a></li>
