<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\OrderPersonalReceipt\DoPersonalReceipt;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI_messages;
use JetApplication\Admin_Managers;
use JetApplication\OrderPersonalReceipt;


/**
 * @var MVC_View   $this
 * @var OrderPersonalReceipt $dispatch
 */

$dispatch = $this->getRaw('dispatch');

$is_editable = $dispatch->isEditable();

$packet_default_params = [];

$our_note_form = $dispatch->getOurNoteForm();
$our_note_form->field('our_note')->input()->addJsAction('onblur', "Notes.saveOurNoteForm();");


require 'detail/js.phtml';

?>
<div id="main-toolbar" class="toolbar">
		<?=$this->render('detail/toolbar')?>
</div>

<div id="main-col">
	
	<?php
	foreach( UI_messages::get() as $message ):
		echo $message;
	endforeach;
	?>
	
	<div style="display: grid;grid-template-columns: 200px 1fr;gap: 20px;margin: 20px;">
		<div><?=Tr::_('Order dispatch:')?></div>
		<div style="display: flex;align-items: center;gap: 10px;">
			<div><?=$dispatch->getNumber()?></div>
			<div>
				<?php
				require 'status.phtml';
				?>
			</div>
		</div>
		
		<div><?=Tr::_('Context:')?></div>
		<div>
			<?php
			require 'context.phtml';
			?>
		</div>
		
		
		

		<?php if($dispatch->getAmountToPay()):?>
		<div class="text-danger" style="font-size: 1.5rem"><?=Tr::_('Amount to pay:')?></div>
		<div class="text-danger" style="font-size: 1.5rem">
			<b><?=Admin_Managers::PriceFormatter()->formatWithCurrency_WithVAT( $dispatch->getCurrency(), $dispatch->getAmountToPay() )?></b>
		</div>
		<?php endif; ?>
		
		<div><?=Tr::_('Our internal notes:')?></div>
		<div>
			<?php
			$our_note_form->field('our_note')->input()->addCustomCssStyle("height: 300px");
			?>
			<?=$our_note_form->start()?>
			<?=$our_note_form->field('our_note')->input()?>
			<?=$our_note_form->end()?>
		</div>
		
		
		
		
		<div><?=Tr::_('Items:')?></div>
		<div>
			<table class="table table-striped">
				<thead>
					<tr>
						<th></th>
						<th><?=Tr::_('EAN')?></th>
						<th><?=Tr::_('Internal code')?></th>
						<th><?=Tr::_('Name / Title')?></th>
						<th><?=Tr::_('Sector')?></th>
						<th><?=Tr::_('Rack')?></th>
						<th><?=Tr::_('Position')?></th>
					</tr>
				</thead>
				<tbody>
				<?php foreach($dispatch->getItems() as $item): ?>
					<tr>
						<td><?=$item->getNumberOfUnits()?> <?=$item->getMeasureUnit()?->getName()?></td>
						<td><?=$item->getEAN()?></td>
						<td><?=$item->getInternalCode()?></td>
						<td><?=$item->getTitle()?></td>
						<td><?=$item->getWarehouseSector()?></td>
						<td><?=$item->getWarehouseRack()?></td>
						<td><?=$item->getWarehousePosition()?></td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
	

	<br><br><br><br>
</div>

