<?php
namespace JetApplicationModule\Admin\OrderPersonalReceipt\DoPersonalReceipt;

use Jet\MVC_View;
use Jet\UI;use JetApplication\OrderPersonalReceipt;


/**
 * @var MVC_View   $this
 * @var OrderPersonalReceipt $dispatch
 */

$dispatch = $this->getRaw('dispatch');

$URL = $dispatch->getEditURL(['warehouse'=>$dispatch->getWarehouseId()]);
?>
<?=$dispatch->getNumber()?> <a href="<?=$URL?>"><?=UI::icon('link')?></a>
