<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\OrderPersonalReceipt\DoPersonalReceipt;


use Jet\MVC_View;
use Jet\UI;use JetApplication\OrderPersonalReceipt;


/**
 * @var MVC_View   $this
 * @var OrderPersonalReceipt $dispatch
 */

$dispatch = $this->getRaw('dispatch');

$URL = $dispatch->getEditUrl(['warehouse'=>$dispatch->getWarehouseId()]);
?>
<?=$dispatch->getNumber()?> <a href="<?=$URL?>"><?=UI::icon('link')?></a>
