<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\OrderPersonalReceipt\DoPersonalReceipt;


use JetApplication\Admin_Managers;
use JetApplication\OrderPersonalReceipt;
use Jet\MVC_View;

/**
 * @var MVC_View   $this
 * @var OrderPersonalReceipt $dispatch
 */

$dispatch = $this->getRaw('dispatch');

if(!$dispatch->getOrderId()) {
	return;
}

echo Admin_Managers::Order()->showName( $dispatch->getOrderId() );