<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use JetApplication\Discounts_Code;

/**
 * @var MVC_View $this
 * @var Discounts_Code $discounts_code
 */

$value = 100;

$discounts_code = $this->getRaw('discounts_code');
$discounts_code->setDiscount( $value );
$discounts_code->save();

?>
Vážený zákazníku,

omlouváme se za problémy s objednávkou <?=$this->getRaw('order_number')?>.

Jako omluvu přijměte slevový kupon <?=$discounts_code->getCode()?> na časku <?=$value?>,- Kč.