<?php
namespace JetShopModule\Order\Discounts\Code;

use Jet\MVC_View;
use JetShop\Discounts_Code;

/**
 * @var MVC_View   $this
 * @var Discounts_Code|null $used_code
 */

$used_code = $this->getRaw('used_code');
?>
<div id="discount_code_area">
	<?php
	if($used_code):
		require 'shopping_cart/used.phtml';
	else:
		require 'shopping_cart/form.phtml';
	endif;
	?>
</div>

<script type="text/javascript">
	const DiscountCode = {
		submit: function() {
			JetAjaxForm.submit('discount_code_use_form', {});
		},

		cancel: function() {
			$('#discount_code_area').load('?action=cancel_use_code')
		}
	};
</script>