<?php
namespace JetApplication;

use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Product $product
 */

$product = $this->getRaw('product');
?>
<div class="row">
	<div class="col-md-12">
		<div class="content-white">
			<div class="product-info center-content">
				<div class="gallery">
					<?php require('parts/images.phtml'); ?>
					<?php require('parts/stickers.phtml'); ?>
				</div>
				<div class="info">
					<div>
						<?php include('parts/socials.phtml'); ?>
						<h1><?= $product->getName() ?></h1>
						<?php require 'parts/rank.phtml'; ?>
						<?php require 'parts/price.phtml'; ?>


						<div class="pre-actions">
							<?php require 'parts/availability.phtml'; ?>
						</div>

						<div class="actions">
							<div class="left">

								<input type="button" class="button-popup-cart"
								       onclick="ShoppingCart.buy(<?=$product->getId()?>,1);"
								       value="<?=Tr::_('Koupit')?>"/>

								<?php require 'parts/delivery_term_popup.phtml'; ?>
							</div>
							<?php require 'parts/compare.phtml'; ?>
							<div class="clear"></div>
						</div>
						<?php require 'parts/brand.phtml'; ?>
					</div>
				</div>
				<div class="clear"></div>
			</div>
		</div>


	</div>
</div>
