<?php
namespace JetApplicationModule\Admin\Content\InfoPages;

use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Content_InfoPage;

/**
 * @var MVC_View $this
 * @var Content_InfoPage $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::EntityEdit()->renderPreviewButton( $item );

if($item->isEditable()) {
	echo Admin_Managers::Image()->commonImageManager( 'info_page', $item->getId() );
}
