<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use JetApplication\ProductListing;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');
?>
<div class="toolbar">
	<?php foreach($listing->getSorters() as $sorter): ?>
		<div style="display: inline-block;padding-left: 15px;padding-right: 15px;padding-top: 10px;padding-bottom: 5px;">
		<?php if($sorter->getIsSelected()):?>
			<b id="product_listing_selected_sorter" data-key="<?=$sorter->getKey()?>"><?=$sorter->getLabel()?></b>
		<?php else: ?>
			<button type="button" class="btn btn-link" onclick="listing.sort('<?=$sorter->getKey()?>');"><?=$sorter->getLabel()?></button>
		<?php endif; ?>
		</div>
	<?php endforeach; ?>
</div>
