<?php
namespace JetApplication;

use Jet\MVC_Layout;
use Jet\MVC;

/**
 * @var MVC_Layout $this
 */

require 'init_libs.php';

$title = $this->getString('title');
if(!$title) {
	$title = MVC::getBase()->getLocalizedData( MVC::getLocale() )->getTitle().' : '.MVC::getPage()->getTitle();
}
?>
	<title><?=$title?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="<?=MVC::getLocale()->getLanguage()?>" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<link rel="icon" type="image/x-icon" href="/images/favicon.ico" />
	
	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>
	
	<?=EShop_Managers::Analytics()?->header()?>
