<?php
namespace JetApplication;

use JetShop\Core_EShopConfig_ModuleConfig_ModuleHasConfig_General_Interface;

interface EShopConfig_ModuleConfig_ModuleHasConfig_General_Interface extends Core_EShopConfig_ModuleConfig_ModuleHasConfig_General_Interface
{
}