<?php
namespace JetApplicationModule\Admin\WarehouseManagement\StockVerification;

use Jet\Locale;
use Jet\MVC_View;
use JetApplication\Admin_Managers_EShopEntity_Listing;
use JetApplication\WarehouseManagement_StockVerification;

/**
 * @var MVC_View $this
 * @var WarehouseManagement_StockVerification $item
 * @var Admin_Managers_EShopEntity_Listing $listing
 */

$item = $this->getRaw('item');
$listing = $this->getRaw('listing');

$edit_uri = $listing->getEditUrl($item);
?>
<a href="<?=$edit_uri?>"><?=Locale::date($item->getDate())?></a>


