<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\WarehouseManagement\StockVerification;


use Jet\Locale;
use Jet\MVC_View;
use JetApplication\WarehouseManagement_StockVerification;

/**
 * @var MVC_View $this
 * @var WarehouseManagement_StockVerification $item
 */

$item = $this->getRaw('item');


?>
<div style="display: grid;grid-template-columns: 40px 20px 40px 1fr;gap: 10px; align-items: center;font-size: 0.7rem">
	<?php foreach($item->getItems() as $item):
		if($item->getNumberOfUnitsExpected()==$item->getNumberOfUnitsReality()) {
			continue;
		}
		?>
		<div><?=Locale::float( $item->getNumberOfUnitsExpected() )?> <?=$item->getMeasureUnit()?->getName()?></div>
		<div> &lt; &gt; </div>
		<div><?=Locale::float( $item->getNumberOfUnitsReality() )?> <?=$item->getMeasureUnit()?->getName()?></div>
		<div><?=$item->getProductName()?></div>
	<?php endforeach; ?>
</div>
