<?php
namespace JetApplicationModule\Admin\WarehouseManagement\StockVerification;

use Jet\MVC_View;
use JetApplication\Admin_Managers_Entity_Listing;
use JetApplication\WarehouseManagement_StockVerification;

/**
 * @var MVC_View $this
 * @var WarehouseManagement_StockVerification $item
 * @var Admin_Managers_Entity_Listing $listing
 */

$item = $this->getRaw('item');

echo nl2br( $item->getNotes() );
