<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\WarehouseManagement\StockVerification;


use Jet\MVC_View;
use JetApplication\Admin_Managers_EShopEntity_Listing;
use JetApplication\WarehouseManagement_StockVerification;
use JetApplication\WarehouseManagement_Warehouse;

/**
 * @var MVC_View $this
 * @var WarehouseManagement_StockVerification $item
 * @var Admin_Managers_EShopEntity_Listing $listing
 */

$item = $this->getRaw('item');
$listing = $this->getRaw('listing');

$edit_uri = $listing->getEditUrl($item);
?>
<a href="<?=$edit_uri?>"><?=WarehouseManagement_Warehouse::getScope()[$item->getWarehouseId()]??'';?></a>


