<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Orders;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;


/**
 * @var MVC_View $this
 */

if(!Main::getCurrentUserCanEdit()) {
	return;
}

echo UI::button( Tr::_('Dispatch all orders that are ready') )
	->setClass(UI_button::CLASS_SUCCESS)
	->setOnClick("$('#dispatch_all_ready').modal('show');");