<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Orders;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use Jet\UI_dialog;


/**
 * @var MVC_View $this
 */

if(!Main::getCurrentUserCanEdit()) {
	return;
}

$dialog = new UI_dialog( 'dispatch_all_ready', Tr::_('Dispatch all orders that are ready'), UI_dialog::SIZE_DEFAULT );

echo $dialog->start();
	echo Tr::_('Do you really want to dispatch all orders that are ready?');
echo $dialog->footer();

echo UI::button(Tr::_('OK, here we go.'))
	->setUrl(Http_Request::currentURI(set_GET_params: [
		'action' => 'dispatch_all_ready',
	]))
	->setClass( UI_button::CLASS_SUCCESS );

echo $dialog->end();