<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\Form;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Exports_Module_Controller_ProductSettings;


/**
 * @var Exports_Module_Controller_ProductSettings $controller
 * @var MVC_View   $this
 * @var Form $params_form
 */

$controller = $this->getController();

$product = $controller->getProduct();
$export = $controller->getExport();
$eshop = $controller->getEshop();
$editable = $controller->getEditable();
$category = $controller->getCategory();
$params_form = $controller->getParametersForm();
$product_join = $controller->getProductJoin();

?>
<?=$controller->getTabs()?>
<br>

<div class="card card-body">
<?php if($editable):
	$form = $product_join->getEditForm();
	
	$form->renderer()->setDefaultFieldWidth([
		Form_Renderer::LJ_SIZE_MEDIUM => 5
	]);
	$form->renderer()->setDefaultLabelWidth([
		Form_Renderer::LJ_SIZE_MEDIUM => 2
	]);
	
	echo $form->start();
	foreach($form->getFields() as $field):
		echo $field;
	endforeach;
	?>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-5">
			<?=UI::button_save()?>
		</div>
	</div>
	
	<?php
	echo $form->end();
	?>
<?php endif; ?>
</div>
<br><br>


<?php if($category): ?>
	<div>
		<b><?=$category->getCategoryId()?></b> <?=implode(' / ', $category->getFullName())?>
	</div>
	
	<div class="toolbar">
		<?php if($editable): ?>
			<?=UI::button( Tr::_('Actualize list of parameters'))->setClass(UI_button::CLASS_PRIMARY)->setUrl(Http_Request::currentURI(['actualize_list_of_parameters'=>'1']))?>
		<?php endif; ?>
	</div>
	
	
<?php if($params_form): ?>
	<?=$params_form->start();?>
	
	<div style="display: grid;grid-template-columns: 2fr 8fr;gap: 20px;">
		<?php foreach($params_form->getFields() as $field): ?>
			<div><?=$field->getLabel()?></div>
			<div><?=$field->input()?><?=$field->error()?></div>
		<?php endforeach; ?>
		
		<?php if($editable): ?>
			<div style="position: fixed;right: 10px;bottom: 10px;">
				<?=UI::button_save()?>
			</div>
		<?php endif; ?>
	</div>
	
	<?php
	echo $params_form->end();
endif;
endif; ?>
