<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Listing;


use Jet\Form_Field;
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Application_Service_Admin;
use JetApplication\EShops;


/**
 * @var MVC_View $this
 * @var Listing_Filter_IsActive $filter
 * @var Listing $listing
 */

$filter = $this->getRaw('filter');
$listing = $filter->getListing();
$filter_form = $listing->getFilterForm();

$show_filter = function( Form_Field $field, string $what ) {
	?>
		<div
			class="badge badge-<?=match((string)$field->getValue()) {''=>'light', '-1'=>'danger', '1'=>'success' }?>"
			style="display: grid;justify-content:left;grid-template-columns: auto 100px;align-items: center;gap: 10px;"
		>
			<div><?=$what?></div>
			<div><?=$field->input()->addJsAction('onchange', 'this.form.submit()')?></div>
		</div>
	
	<?php
};

$fields = [$filter_form->field('is_active_general')];

$is_active = false;
if($filter_form->field('is_active_general')->getValue()) {
	$is_active = true;
}

if($filter->isMultiEShopMode()) {
	foreach( EShops::getListSorted() as $code=> $eshop) {
		$fields[] = $filter_form->field('is_active_'.$code);
		if($filter_form->field('is_active_'.$code)->getValue()) {
			$is_active = true;
		}
	}
}


echo Application_Service_Admin::EntityListing()->renderListingFilter(
	filter:      $filter,
	title:       Tr::_('Is active', dictionary: Tr::COMMON_DICTIONARY),
	form_fields: $fields,
	is_active:   $is_active,
	renderer:    function() use ($show_filter, $filter_form, $filter) {
		?>
		<div style="display: flex;flex-wrap: wrap;gap: 10px;">
		<?php
		$show_filter(
			$filter_form->field('is_active_general'),
			Tr::_('General', dictionary: Tr::COMMON_DICTIONARY)
		);
		
		if( $filter->isMultiEShopMode() ):
			foreach( EShops::getListSorted() as $key=> $eshop):
				$show_filter(
					$filter_form->field('is_active_'.$key),
					$eshop->getName()
				);
			
			endforeach;
		endif;
		?>
		</div>
		<?php
	}
);
