<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Listing;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Application_Service_Admin;

/**
 * @var MVC_View $this
 * @var Listing $listing
 */

$listing = $this->getRaw( 'listing' );
$filter = $this->getRaw('filter');
$filter_form = $listing->getFilterForm();

$field = $filter_form->field( 'search' );

$field->input()->addCustomCssStyle('width:500px');

echo Application_Service_Admin::EntityListing()->renderListingFilter(
	filter:      $filter,
	title:       Tr::_('Search', dictionary: Tr::COMMON_DICTIONARY),
	form_fields: [$field],
	is_active:   $field->getValue(),
	renderer:    function() use ($field) {
		?>
		<?= $field->input() ?>
		<div><?=UI::button(' ')->setType(UI_button::TYPE_SUBMIT)->setIcon('search')?></div>
		<?php
	}
);


