<?php
namespace JetApplicationModule\Admin\Entity\Listing;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View $this
 * @var Listing $listing
 */

$listing = $this->getRaw( 'listing' );
$filter = $this->getRaw('filter');
$filter_form = $listing->getFilterForm();

$field = $filter_form->field( 'search' );

$field->input()->addCustomCssStyle('width:500px');

echo Admin_Managers::EntityListing()->renderListingFilter(
	filter:      $filter,
	title:       Tr::_('Search', dictionary: Tr::COMMON_DICTIONARY),
	form_fields: [$field],
	is_active:   $field->getValue(),
	renderer:    function() use ($field) {
		?>
		<?= $field->input() ?>
		<div><?=UI::button(' ')->setType(UI_button::TYPE_SUBMIT)->setIcon('search')?></div>
		<?php
	}
);


