<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Marketing\Banners;



use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Marketing_Banner;

/**
 * @var MVC_View $this
 * @var Marketing_Banner   $item
 */
$item = $this->getRaw( 'item' );

$group = $item->getGroup();
$upload_form = $item->getUploadForm_MainVideo();

$video_field = $upload_form->field('video');

$video_field->input()
	->addJsAction('onchange', "JetAjaxForm.submit(this.form.id)");


?>
<div class="card card-body">
	<h5><?=Tr::_('Main video (%W%px x %H%px)', ['W'=>$group->getMainVideoW(), 'H'=>$group->getMainVideoH()])?></h5>
	
	<?php if($item->isEditable()): ?>
		<?=$upload_form->start()?>
		<div class="btn btn-light btn-upload">
			<?=UI::icon('upload')?>&nbsp;<span><?=Tr::_('Select and upload video')?></span>
			<?=$video_field->input()?>
		</div>
		<?=$upload_form->end()?>
	<?php endif; ?>
	
	<?php if($item->getVideoMain()): ?>
		<video style="width: <?=$group->getMainVideoW()?>px;height: <?=$group->getMainVideoH()?>px;" controls>
			<source src="<?=$item->getVideoMainURI()?>">
		</video>
		<?php if($item->isEditable()):
			$delete_url = Http_Request::currentURI(['delete_media'=>'video_main']);
			?>
			<div style="margin:10px;">
				<?=UI::button_delete(' ')->setOnClick("$('#video-main').load('{$delete_url}');")?>
			</div>
		<?php endif; ?>
	
	<?php endif; ?>
</div>
