<?php
namespace JetApplicationModule\Order\Discounts\Code;

use Jet\MVC_View;
use Jet\UI;
use JetApplication\CashDesk;
use JetApplication\Discounts_Code;
use JetApplication\Order_Item;
use JetApplication\Price;
use JetApplication\ShoppingCart;

/**
 * @var MVC_View   $this
 * @var Discounts_Code|null $used_code
 * @var Main $module
 */

$module = $this->getRaw('module');

$discounts = $module->getDiscounts( CashDesk::get() );
?>

<?php foreach($discounts as $discount): ?>
<div style="padding: 10px;">

	<?php if(
		$discount->getSubType()==Order_Item::DISCOUNT_TYPE_PRODUCTS_PERCENT ||
		$discount->getSubType()==Order_Item::DISCOUNT_TYPE_PRODUCTS_AMOUNT
	):
		$d_a = $discount->getItemAmount();
		if($discount->getSubType()==Order_Item::DISCOUNT_TYPE_PRODUCTS_PERCENT) {
			$d_a = Price::round(ShoppingCart::get()->getAmount() * ((100-$d_a)/100));
		}
		?>
		<?=$discount->getTitle()?>:

		<strong style="font-size: 20px;">-<?=Price::formatWithCurrency($d_a)?></strong>
	<?php else: ?>
		<?=$discount->getTitle()?>
	<?php endif; ?>

	<?=UI::button(' ')->setIcon('trash')->setOnclick('DiscountCode.cancel()')?>
</div>
<?php endforeach; ?>

