<?php
namespace JetApplicationModule\Shop\Login;

use Jet\Tr;
use Jet\UI;
use JetApplication\Customer;

$customer = Customer::getCurrentCustomer();

$form = Main::getLogoutForm();
?>
<div class="dropdown" style="display: inline-block">
	<button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		<?=UI::icon('user')?>
	</button>
	<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
		<div class="dropdown-item" style="padding-bottom: 10px;">
			<?=$customer->getEmail()?><br/><br/>

			<?=$form->start()?>
			<?=$form->end()?>

			<?=UI::button(Tr::_('Sign out'))->setOnclick('CustomerLogin.logout();')->setClass('ling')?>
		</div>
	</div>
</div>

<?=$this->render('js')?>
