<?php
namespace JetApplicationModule\Shop\Login;
use Jet\Tr;
use Jet\UI;

?>
<div class="dropdown" style="display: inline-block">
	<button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		<?=UI::icon('key')?> <?=Tr::_('Sign in')?>
	</button>
	<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
		<div class="dropdown-item" style="padding-bottom: 10px;">

			<div id="customer_login_form_area" style="width: 400px;">
				<?php require 'login/form.phtml' ?>
			</div>
		</div>
	</div>
</div>

<?=$this->render('reset_password/dialog')?>
<?=$this->render('js')?>
