<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Orders;


use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;
use Jet\MVC_View;
use JetApplication\Order;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Order $order
 */

$order = $this->getRaw('order');
if(!$order->isEditable()) {
	return;
}

$form = $this->getRaw('form');
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 3
]);
$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 9
]);


$form->renderer()->addJsAction("onsubmit", "JetAjaxForm.submit(this.id, {onSuccess: ()=>{location.reload();}});return false;");

echo $form->start();

echo $form->field('description');
echo $form->field('discount_type');
echo $form->field('discount_module');
echo $form->field('discount_context');
echo $form->field('discount');


?>
	<div class="row form-group">
		<div class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-3"></div>
		<div class="col-md-8" style="padding-bottom: 10px">
			<?=UI::button_save(Tr::_('Add'))?>
		</div>
	</div>
	<?php
echo $form->end();