<?php
namespace JetApplicationModule\Admin\Orders;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;
use Jet\MVC_View;
use JetApplication\Admin_Managers;


/**
 * @var MVC_View $this
 * @var Form $form
 * @var Order $order
 */

$order = $this->getRaw('order');
if(!$order->isEditable()) {
	return;
}

$form = $this->getRaw('form');
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 3
]);
$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 9
]);

$form->renderer()->addJsAction("onsubmit", "JetAjaxForm.submit(this.id, {onSuccess: ()=>{location.reload();}});return false;");

echo $form->start();
echo $form->field('product_id');
?>
	<div class="row form-group">
		<label class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-3"><?= Tr::_('Product:')?></label>
		<div class="col-md-9" style="padding-bottom: 10px">
			<?=Admin_Managers::Product()->renderSelectWidget(
				"$('#{$form->field('product_id')->getId()}').val(selected_item.id)",
				selected_product_id: 0,
				name: 'add_item_select_product'
			);?>
		</div>
	</div>
<?php
echo $form->field('qty');
?>
	<div class="row form-group">
		<div class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-3"></div>
		<div class="col-md-8" style="padding-bottom: 10px">
			<?=UI::button_save(Tr::_('Add'))?>
		</div>
	</div>
<?php
echo $form->end();