<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\Tr;
use JetApplication\EMail_Template;
use JetApplication\EMail_TemplateText;
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;


/**
 * @var MVC_View $this
 * @var Form     $form
 * @var EShop $eshop
 * @var EMail_Template[] $templates
 * @var EMail_TemplateText $item
 */

$eshop = $this->getRaw('eshop');
$form = $this->getRaw('form');
$eshop_key = $eshop->getKey();
$item = $this->getRaw('item');

$templates = $this->getRaw('templates');

$template = $templates[$item->getInternalCode()]??null;
?>

<div style="display: grid;grid-template-columns: 2fr 1fr;gap: 10px;margin: 10px;">
	<div>
		<div><?= Tr::_('Layout:');?></div>
		<?=$form->field('/eshop_data/'.$eshop_key.'/layout_id')->input()?>
		<br>
		<div><?= Tr::_('Sender - e-mail:');?></div>
		<?=$form->field('/eshop_data/'.$eshop_key.'/sender_email')->input()?>
		<br>
		<div><?= Tr::_('Sender - name:');?></div>
		<?=$form->field('/eshop_data/'.$eshop_key.'/sender_name')->input()?>
		<br>
		<div><?= Tr::_('Subject:');?></div>
		<?=$form->field('/eshop_data/'.$eshop_key.'/subject')->input()?>
		<br>
		<div><?= Tr::_('HTML');?></div>
		<?=$form->field('/eshop_data/'.$eshop_key.'/body_html')->input()?>
		<br>
		<div><?= Tr::_('TXT');?></div>
		<?=$form->field('/eshop_data/'.$eshop_key.'/body_txt')->input()->addCustomCssStyle('height: 400px;')?>
	</div>
	<div>
		<?php if($template): ?>
			<?php if($template->getConditions()): ?>
				<div class="card">
					<div class="card-header"><?=Tr::_('Conditions')?></div>
					<div class="card-body">
						<?php foreach($template->getConditions() as $p): ?>
							<div>
								<b><?=$p->getInstructionTemplate()?></b>
							</div>
							<div>
								<?=$p->getDescription()?>
							</div>
							<hr>
						<?php endforeach; ?>

					</div>
				</div>
				<br>
			<?php endif; ?>
		
			<?php if($template->getProperties()): ?>
			<div class="card">
				<div class="card-header"><?=Tr::_('Properties')?></div>
				<div class="card-body">
					<?php foreach($template->getProperties() as $p): ?>
					<div>
						<b><?=$p->getInstructionTemplate()?></b>
					</div>
					<div>
						<?=$p->getDescription()?>
					</div>
					<hr>
					<?php endforeach; ?>
					
				</div>
			</div>
			<br>
			<?php endif; ?>
		
			<?php if($template->getBlocks()): ?>
			<div class="card">
				<div class="card-header"><?=Tr::_('Blocks')?></div>
				<div class="card-body">
					<?php foreach($template->getBlocks() as $b): ?>
						<div>
							<b><?=$b->getInstructionTemplate()?></b>
						</div>
						<div>
							<?=$b->getDescription()?>
						</div>
						<div style="padding: 20px;padding-left: 30px;padding-right: 30px;">
							<i><?=Tr::_('Block properties:')?></i><br><br>
							
							<?php foreach($b->getProperties() as $p): ?>
								<div>
									<b><?=$p->getInstructionTemplate()?></b>
								</div>
								<div>
									<?=$p->getDescription()?>
								</div>
							<?php endforeach; ?>
							
						</div>
					
						<?php if($b->getConditions()): ?>
							<div style="padding: 20px;padding-left: 30px;padding-right: 30px;">
								<i><?=Tr::_('Block conditions:')?></i><br><br>
								
								<?php foreach($b->getConditions() as $p): ?>
									<div>
										<b><?=$p->getInstructionTemplate()?></b>
									</div>
									<div>
										<?=$p->getDescription()?>
									</div>
								<?php endforeach; ?>
							</div>
						<?php endif; ?>
					
					
						<hr>
					<?php endforeach; ?>

				</div>
			</div>
			<?php endif; ?>
		
		<?php endif; ?>
	</div>
</div>
<br><br><br><br>

