<?php
namespace JetShopModule\Admin\Content\InfoPages;

use Jet\MVC;
use JetShop\Content_InfoPage as ContentInfoPage;

use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use JetShop\Shops;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var ContentInfoPage     $info_page
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 1 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 5 ] );

$URLs = [];
$base_URL = '';
foreach( Shops::getList() as $shop ) {
	$URL = MVC::getBase($shop->getBaseId())->getHomepage($shop->getLocale())->getURL();
	$URLs[$shop->getKey()] = $URL;

	if($shop->getKey()==$form->field('shop')->getValue()) {
		$base_URL = $URL;
	}
}

$form->field( 'shop' )->input()->addJsAction('onchange', 'actualizeUrl()');

$form->field( 'text' )->input()->addCustomCssStyle('height:1000px');

$info_page = $this->getRaw('content_info_page');

$page = $info_page->getPage();
?>
<?=$form->start()?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()?>
		<?php endif; ?>

		<?php if($page): ?>
			&nbsp;&nbsp;&nbsp;<a href="<?=$page->getURL()?>" target="_blank"><?=UI::icon('eye')?></a>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=$form->field( 'shop' )?>
		<?=$form->field( 'page_id' )?>
		<?=$form->field( 'is_active' )?>
		<?=$form->field( 'internal_description' )?>
		<?=$form->field( 'title' )?>
		<?=$form->field( 'menu_title' )?>
		<?=$form->field( 'breadcrumb_title' )?>
		<?=$form->field( 'meta_keywords' )?>
		<?=$form->field( 'meta_description' )?>

		<?php
		$relative_path_fragment = $form->field('relative_path_fragment');
		?>
		<?=$relative_path_fragment->row()->start()?>
			<?=$relative_path_fragment->label()?>

			<?=$relative_path_fragment->container()->start()?>
			<div class="input-group">
				<span class="input-group-prepend" style="font-weight: bolder"><span class="input-group-text" id="base_URL"><?=$base_URL?></span></span>
				<?=$relative_path_fragment->input()?>
				<?=$relative_path_fragment->error()?>
			</div>
			<?=$relative_path_fragment->container()->end()?>

		<?=$relative_path_fragment->row()->end()?>



		<?=$form->field( 'custom_layout_script' )?>
		<?=$form->field( 'text' )?>



	</div>
</div>

<?=$form->end()?>


<script type="text/javascript">
	function actualizeUrl()
	{
		const URLs = <?=json_encode($URLs)?>

		const select = document.getElementById('add_form__shop');
		if(!select) {
			return;
		}

		const shop_key = select.options[select.selectedIndex].value;


		document.getElementById('base_URL').innerText = URLs[shop_key];
	}

	actualizeUrl();
</script>
