<?php
namespace JetApplicationModule\Admin\Content\InfoPages;

use JetApplication\Content_InfoPage as ContentInfoPage;

use Jet\UI;
use Jet\UI_dataGrid;
use Jet\UI_button;

use Jet\Tr;
use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Form         $filter_form
 */
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );
$router = $this->getController()->getControllerRouter();


$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( ContentInfoPage $item ) use ( $router ) {
		if( ( $edit_uri = $router->action('edit')->URI( $item->getId() ) ) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;
	}
);
$c_edit->addCustomCssStyle( 'width:80px;' );


$grid->getColumn( 'page_id' )->setRenderer(
	function( ContentInfoPage $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getId() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getPageId();?></a>
		<?php
	}
);
$grid->getColumn('page_id')->addCustomCssStyle('width:220px');

$grid->getColumn( 'shop_code' )->setRenderer(
	function( ContentInfoPage $item ) use ( $router ) {
		echo $item->getShop()->getShopName();
	}
);
$grid->getColumn('shop_code')->addCustomCssStyle('width:150px');

$grid->getColumn( 'title' )->setRenderer(
	function( ContentInfoPage $item ) use ( $router ) {
		echo $item->getTitle();
	}
);
$grid->getColumn('title')->addCustomCssStyle('width:350px');


$grid->getColumn( 'internal_description' )->setRenderer(
	function( ContentInfoPage $item ) use ( $router ) {
		echo $item->getInternalDescription();
	}
);

$grid->getColumn( 'is_active' )->setRenderer(
	function( ContentInfoPage $item ) use ( $router ) {
		if($item->getIsActive()) {
			echo '<div class="badge badge-success">';
			echo Tr::_('Active');
			echo '</div>';
		} else {
			echo '<div class="badge badge-danger">';
			echo Tr::_('Not Active');
			echo '</div>';
		}
	}
);
$grid->getColumn('is_active')->addCustomCssStyle('width:100px');


?>

<?=$filter_form->start()?>
<div class="row toolbar">
	<?php if( ( $add_uri = $router->action('add')->URI() ) ): ?>
		<div class="col-md-2 col-sm-12">
			<?=UI::button_create( Tr::_( 'Create a new Content Info Page' ) )->setUrl( $add_uri )?>
		</div>
	<?php endif; ?>

	<div class="col-md-3 col-sm-12">
		<?= $filter_form->field( 'search' )->input() ?>
	</div>
	<div class="col-md-4 col-sm-12">
		<table>
			<tr>
				<td><?=$filter_form->field('shop')->label()?></td>
				<td><?=$filter_form->field('shop')->input()->addJsAction('onchange', 'this.form.submit()')?></td>
			</tr>
		</table>
	</div>

</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
