<?php
use Jet\MVC_View;

/**
 * @var MVC_View $this
 */

$id = $this->getRaw('id');
$campaign_id = $this->getRaw('campaign_id');
?>
<div id='papPlaceholder'></div>

<script type="text/javascript">
	(function(d,t) {
		var script = d.createElement(t); script.id= 'pap_x2s6df8d'; script.async = true;
		script.src = '//login.dognet.sk/scripts/fj27g82d';
		script.onload = script.onreadystatechange = function() {
			var rs = this.readyState; if (rs && (rs != 'complete') && (rs != 'loaded')) return;
			PostAffTracker.setAccountId('<?=$id?>');
			try { var CampaignID='<?=$campaign_id?>';
				PostAffTracker.track(); } catch (e) {}
		}
		var placeholder = document.getElementById('papPlaceholder');
		placeholder.parentNode.insertBefore(script, placeholder);
		placeholder.parentNode.removeChild(placeholder);
	})(document, 'script');
</script>
