<?php
use Jet\MVC_View;
use JetApplication\Order;

/**
 * @var MVC_View $this
 * @var Order $order
 */

$id = $this->getRaw('id');
$campaign_id = $this->getRaw('campaign_id');
$order = $this->getRaw('order');

$product_ids = [];
foreach($order->getItems() as $item) {
	if($item->isStdProduct()) {
		$product_ids[] = $item->getItemId();
	}
}

$product_ids = implode(', ', $product_ids);
?>

<div id='papSaleTrackingPlaceholder'></div>

<script type="text/javascript">
	(function(d,t) {
		var script = d.createElement(t); script.id= 'pap_x2s6df8d'; script.async = true;
		script.src = '//login.dognet.sk/scripts/fj27g82d';
		script.onload = script.onreadystatechange = function() {
			var rs = this.readyState; if (rs && (rs != 'complete') && (rs != 'loaded')) return;

			PostAffTracker.setAccountId('<?=$id?>');
			var sale = PostAffTracker.createSale();
			sale.setCampaignID('<?=$campaign_id?>');
			
			sale.setTotalCost('<?=$order->getProductAmount_WithoutVAT()?>'); //dosadit vysku objednavky BEZ DPH a BEZ DOPRAVY
			sale.setOrderID('<?=$order->getNumber()?>');
			sale.setProductID('<?=$product_ids?>');
			
			sale.setCurrency('<?=$order->getPricelist()->getCurrency()->getCode()?>');
			try { PostAffTracker.track(); } catch (e) {}

		}
		var placeholder = document.getElementById('papSaleTrackingPlaceholder');
		placeholder.parentNode.insertBefore(script, placeholder);
		placeholder.parentNode.removeChild(placeholder);
	})(document, 'script');
</script>
