<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Properties;


use Jet\Form;
use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Property;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Property $property
 */

$property = $this->getRaw('property');
$form = $this->getRaw('form');
$prefix = $this->getString('prefix');

if(!$form->fieldExists($prefix.'value')) {
	return;
}


$value = $form->field($prefix.'value');

$value->input()->addCustomCssStyle('height:300px');

$value->setLabel(
	'<a href="'.$property->getEditUrl().'" tabindex="99999">'.$property->getInternalName().'</a><br>'
	.Admin_Managers::Property()->renderActiveState( $property )
);

echo $value;
?>
<div style="opacity: 0.3;position: relative;top: -13px;">
	<?=$form->field($prefix.'information_in_not_available')?>
</div>
