<?php
namespace JetApplicationModule\Admin\Catalog\Properties;

use Jet\Form;
use Jet\MVC_View;
use Jet\UI;
use JetApplication\Admin_Managers;
use JetApplication\EShops;
use JetApplication\Property;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Property $property
 */

$property = $this->getRaw('property');
$form = $this->getRaw('form');
$prefix = $this->getString('prefix');


if(!$form->fieldExists($prefix.EShops::getDefault()->getKey())) {
	return;
}

$default = $form->field($prefix.EShops::getDefault()->getKey());

$default->setLabel(
	'<a href="'.$property->getEditUrl().'" tabindex="99999">'.$property->getInternalName().'</a><br>'
	.Admin_Managers::Property()->renderActiveState( $property )
);

if( EShops::isMultiEShopMode() ) {
	$default->input()->setCustomRenderer( function() use ($form, $prefix) {
		foreach( EShops::getListSorted() as $eshop) {
			if(!$form->fieldExists($prefix.$eshop->getKey())) {
				continue;
			}
			
			$field = $form->field($prefix.$eshop->getKey());
			?>
			<div style="padding-bottom: 5px;">
				<div><?=UI::flag($eshop->getLocale())?> <?=$eshop->getName();?></div>
				<div><?=$field->input()->renderByView();?></div>
			</div>
			<?php
		}
	} );
}

echo $default;
?>
<div style="opacity: 0.3;position: relative;top: -13px;">
	<?=$form->field($prefix.'information_in_not_available')?>
</div>
