<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\EventViewer\Services;


use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Listing  $listing
 */
$listing = $this->getRaw( 'listing' );
$filter_form = $listing->getFilterForm();
?>
<td nowrap=""><?= $filter_form->field( 'context_object_id' )->label() ?></td>
<td><?= $filter_form->field( 'context_object_id' )->input()?></td>
