<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\EventViewer\Services;


use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Listing  $listing
 */
$listing = $this->getRaw( 'listing' );
$filter_form = $listing->getFilterForm();
?>
<?= $filter_form->field( 'search' )->input() ?>
