<?php
namespace JetApplicationModule\Shop\ReturnsOfGoods;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use JetApplication\Product_ShopData;
use JetApplication\ReturnOfGoods;

/**
 * @var MVC_View   $this
 * @var Form $edit_form
 * @var Product_ShopData $product
 * @var ReturnOfGoods $return
 */

$return = $this->getRaw('return');
$edit_form = $this->getRaw('form');
$product = $return->getProduct();

?>
<div class="card" style="margin: 10px;">
	<div class="card-body">
		<h5 class="card-title"><?=Tr::_('Return of goods %n%', ['n'=>$return->getNumber()])?></h5>
		
		<div style="display: grid;grid-template-columns: 60px 1fr;gap: 5px;margin: 10px;align-items: center;margin-bottom: 20px;">
			<div>
				<?php if($product->getImg(0)): ?>
					<a href="<?=$product->getURL()?>"><img src="<?=$product->getImgThumbnailUrl(0, 50, 50)?>"></a>
				<?php endif; ?>
			</div>
			<div><a href="<?=$product->getURL()?>"><?=$product->getName()?></a></div>
		</div>
		
		<?=$this->render('return-of-goods-status')?>
		
		
		<div class="card card-body" style="width: 800px;margin: 10px;">
			<?=nl2br( $return->getProblemDescription() )?>
		</div>
		
	</div>
</div>


