<?php
namespace JetApplicationModule\Shop\ReturnsOfGoods;

use Jet\MVC_View;
use Jet\Tr;
use JetApplication\ReturnOfGoods;

/**
 * @var MVC_View  $this
 * @var ReturnOfGoods $return
 */

$return = $this->getRaw('return');

?>
<h1><?=Tr::_('Return of goods request entry completed')?></h1>

<p><?=Tr::_('Your return of goods request has the number <b>%no%</b>', ['no'=>$return->getNumber()])?></p>

<p><?=Tr::_('Our team will deal with your return of goods request as soon as possible.')?></p>