<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use JetApplication\Shops_Shop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Shops_Shop $shop
 * @var Product $item
 */
$form = $this->getRaw('form');
$item = $this->getRaw('item');
$shop = $this->getRaw('shop');
$shop_key = $shop->getKey();

$form->field('/shop_data/'.$shop_key.'/description')->input()->addCustomCssStyle('height:600px');
?>
<fieldset>
	<legend class="sub"><?=Tr::_('Main data')?></legend>
	
	<?=$form->field('/shop_data/'.$shop_key.'/allow_to_order_when_sold_out')?>
	
	<?=$form->field('/shop_data/'.$shop_key.'/name')?>
	<?php if($form->fieldExists('/shop_data/'.$shop_key.'/variant_name')): ?>
	<?=$form->field('/shop_data/'.$shop_key.'/variant_name')?>
	<?php endif; ?>
	<?=$form->field('/shop_data/'.$shop_key.'/description')?>
	<?=$form->field('/shop_data/'.$shop_key.'/short_description')?>
</fieldset>

<fieldset>
	<legend class="sub"><?=Tr::_('SEO')?></legend>
	<?=$form->field('/shop_data/'.$shop_key.'/seo_title')?>
	<?=$form->field('/shop_data/'.$shop_key.'/seo_description')?>
	<?=$form->field('/shop_data/'.$shop_key.'/seo_keywords')?>
</fieldset>
