<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Products;


use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use JetApplication\Product;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var EShop $eshop
 * @var Product $item
 */
$form = $this->getRaw('form');
$item = $this->getRaw('item');
$eshop = $this->getRaw('eshop');
$eshop_key = $eshop->getKey();

$form->field('/eshop_data/'.$eshop_key.'/description')->input()->addCustomCssStyle('height:600px');
?>
<fieldset>
	<legend class="sub"><?=Tr::_('Main data')?></legend>
	
	<?=$form->field('/eshop_data/'.$eshop_key.'/name')?>
	<?php if($form->fieldExists('/eshop_data/'.$eshop_key.'/variant_name')): ?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/variant_name')?>
	<?php endif; ?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/description')?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/short_description')?>
</fieldset>

<fieldset>
	<legend class="sub"><?=Tr::_('SEO')?></legend>
	<?=$form->field('/eshop_data/'.$eshop_key.'/seo_title')?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/seo_description')?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/seo_keywords')?>
</fieldset>
