<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\CashDesk;



use Jet\MVC_View;
use JetApplication\Payment_Method_Option;

/**
 * @var MVC_View $this
 * @var Payment_Method_Option $payment_method_option
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');

$payment_method_option = $this->getRaw('payment_method_option');

?>

<div class="option" onclick="CashDesk.payment.selectOption('<?= $payment_method_option->getInternalCode() ?>')">

	<div class="option-radio-btn">
		<input type="radio" name="payment_method_option" onclick="setTimeout(function(){CashDesk.payment.selectOption('<?= $payment_method_option->getInternalCode() ?>')}, 10);return false;" />
	</div>
	<div class="option-icon">
		<?php if($payment_method_option->getImageIcon1()):?>
		<img src="<?=$payment_method_option->getIcon1ThumbnailUrl(30, 30)?>">
		<?php endif; ?>
	</div>
	<div class="option-title">
		<b><?= $payment_method_option->getTitle() ?></b>
		
		<?php if($payment_method_option->getDescription()): ?>
			<div>
				<?= $payment_method_option->getDescription() ?>
			</div>
		<?php endif; ?>
	</div>
</div>
