<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Http_Request;
use Jet\Mvc_View;
use Jet\Tr;
use Jet\UI;
use JetShop\Parametrization_Property;

/**
 * @var Mvc_View   $this
 */

$form_id = Controller_Main::getCurrentParamGroup()->getEditForm()->getId();
?>
<?=UI::button_save()->setOnclick("$('#$form_id').submit();")?>

<?php if(!Controller_Main::getCurrentParamGroup()->isInherited()): ?>

	<div class="dropdown">
		<button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<?=Tr::_('Create a new property')?>
		</button>

		<div class="dropdown-menu" style="padding: 10px;">
			<?php foreach(Parametrization_Property::getTypes() as $type=>$label): ?>
				<a class="dropdown-item" href="<?=Http_Request::currentURI(['action' => 'create_property', 'type'=>$type])?>" ><?=$label?></a>
			<?php endforeach; ?>
		</div>
	</div>&nbsp;
<?php endif; ?>


<?php if($this->getBool('can_sort_properties')): ?>
	<?=UI::button('Sort properties')->setOnclick('paramSort.openDialog()')?>
<?php endif; ?>
