<?php
namespace JetApplicationModule\Admin\Catalog\ProductReviews;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

/**
 * @var MVC_View $this
 * @var ProductReview $item
 */

$item = $this->getRaw('item');

if(
	!$item->isEditable()
) {
	return;
}
?>
&nbsp;&nbsp;&nbsp;&nbsp;
<?=UI::button( Tr::_('Approve') )
	->setUrl( Http_Request::currentURI(set_GET_params: ['action'=>'approve']) )
	->setClass(UI_button::CLASS_SUCCESS);?>
&nbsp;&nbsp;&nbsp;&nbsp;
<?=UI::button( Tr::_('Reject') )
	->setUrl( Http_Request::currentURI(set_GET_params: ['action'=>'reject']) )
	->setClass(UI_button::CLASS_DANGER)?>
