<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\ProductReviews;

use Jet\MVC_View;
use JetApplication\ProductReview;

/**
 * @var MVC_View $this
 * @var ProductReview $item
 */

$item = $this->getRaw('item');

if( $item->getIsNew() ) {
	return;
}


echo Plugin::get( Plugin_SetStatus_Main::KEY )?->renderButton();
echo Plugin::get( Plugin_ForceStatus_Main::KEY )?->renderButton();