<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Catalog\ProductReviews;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\ProductReview;

/**
 * @var MVC_View $this
 * @var ProductReview $item
 */

$item = $this->getRaw('item');

if(
	!$item->isEditable()
) {
	return;
}
?>
&nbsp;&nbsp;&nbsp;&nbsp;
<?=UI::button( Tr::_('Approve') )
	->setUrl( Http_Request::currentURI(set_GET_params: ['action'=>'approve']) )
	->setClass(UI_button::CLASS_SUCCESS);?>
&nbsp;&nbsp;&nbsp;&nbsp;
<?=UI::button( Tr::_('Reject') )
	->setUrl( Http_Request::currentURI(set_GET_params: ['action'=>'reject']) )
	->setClass(UI_button::CLASS_DANGER)?>
