<?php
namespace JetApplicationModule\Shop\ProductReviews;

use Jet\MVC_View;
use JetApplication\Product_ShopData;
use JetApplication\ProductReview;

/**
 * @var MVC_View   $this
 * @var Product_ShopData $product
 */
$product = $this->getRaw('product');

$reviews = ProductReview::getReviews($product);


foreach($reviews as $review):
	$this->setVar('review', $review);
	echo $this->render('product-reviews/item');
endforeach;
