<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Analytics\Service\JetAnalytics;

use Jet\Data_DateTime;
use Jet\Locale;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Main $module
 */

$data = $this->getRaw('data');

$data_set = [];
$labels = [];


foreach( array_keys( array_values($data)[0] ) as $date ) {
	$labels[$date] = Locale::date( new Data_DateTime( $date ), Locale::DATE_TIME_FORMAT_SHORT );
}

foreach($data as $key=>$_items) {

	
	$items = [];
	foreach( $_items as $date=>$v) {
		$items[$labels[$date]] = $v;
	}
	
	$label = strip_tags( Main::keyToTitle( $key ) );
	
	$data_set[] = [
		'label' => $label,
		'data' => $items,
		'borderWidth' => $key=='total' ? 3 : 1
	];
}

$labels = array_values( $labels );

$this->setVar('labels', $labels);
$this->setVar('data_set', $data_set);

echo $this->render('chart/line/common');

