<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Analytics\Service\JetAnalytics;

use Jet\Data_DateTime;
use Jet\Locale;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Main $module
 */

$data = $this->getRaw('data');

$data_set = [];
$labels = [];


foreach( array_keys( array_values($data)[0] ) as $date ) {
	$labels[$date] = Locale::date( new Data_DateTime( $date ), Locale::DATE_TIME_FORMAT_SHORT );
}

/*
foreach($data as $key=>$_items) {
	if($key=='total') {
		foreach( $_items as $date=>$v) {
			$data[$key][$date] = 0;
		}
		
		continue;
	}
	
	foreach( $_items as $date=>$v) {
		$data[$key][$date] = rand(0, 1000);
	}
}

if(isset($data['total'])) {
	foreach($data as $key=>$_items) {
		if($key=='total') {
			continue;
		}
		
		foreach( $_items as $date=>$v) {
			$data['total'][$date] += $data[$key][$date];
		}
	}
}
*/


foreach($data as $key=>$_items) {

	
	$items = [];
	foreach( $_items as $date=>$v) {
		$items[$labels[$date]] = $v;
	}
	
	$label = strip_tags( Main::keyToTitle( $key ) );
	
	$data_set[] = [
		'label' => $label,
		'data' => $items,
		'borderWidth' => $key=='total' ? 3 : 1
	];
}

$labels = array_values( $labels );
?>

<div>
	<canvas id="chart-canvas"></canvas>
</div>


<script>
	const ctx = document.getElementById('chart-canvas');

	new Chart(ctx, {
		type: 'line',
		data: {
			labels: <?=json_encode( $labels )?>,
			datasets: <?=json_encode($data_set)?>
		},
		options: {
			scales: {
				y: {
					beginAtZero: false
				}
			}
		}
	});
</script>
