<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\Catalog;


use Jet\Locale;
use Jet\MVC_View;
use JetApplication\Property_EShopData;

/**
 * @var MVC_View $this
 * @var Property_EShopData $property
 */

$property = $this->getRaw('property');

$value = $property->getProductDetailDisplayValue();

if(!$value) {
	return;
}

if(is_int( $value )):
	echo Locale::int( $value ).' '.$property->getUnits();
endif;
if(is_float( $value )):
	echo Locale::float( $value, 0, $property->getDecimalPlaces() ).' '.$property->getUnits();
endif;
