<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Properties;


use Jet\Form;
use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\Locale;
use JetApplication\Admin_Managers;
use JetApplication\Property_Options_Option;
use JetApplication\EShop;
use JetApplication\Property;

/**
 * @var MVC_View   $this
 * @var Form $form
 * @var Property $property
 * @var Property_Options_Option $option
 */
$property = $this->getRaw('property');
$option = $this->getRaw('option');

$form = $option->getEditForm();
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 2
]);

echo $form->start();

echo Admin_Managers::UI()->renderEntityToolbar($form);
?>
	<div id="main-col">
			<?=$this->getRaw('tabs')?>
			<br>
			
			<?=Admin_Managers::EntityEdit()->renderEntityActivation( $option, !$form->getIsReadonly() )?>
			
			<?=Admin_Managers::EntityEdit()->renderEntityFormCommonFields($form)?>
			<?php
			
			if($option->getDescriptionMode()) {
				echo Admin_Managers::EntityEdit()->renderDescriptionBlocks(
					form: $form,
					renderer: function( Locale $locale, string $locale_str ) use ($option, $form) : void {
						?>
							<fieldset>
								<?=$form->field('/description/'.$locale_str.'/filter_label')?>
								<?=$form->field('/description/'.$locale_str.'/product_detail_label')?>
								<?=$form->field('/description/'.$locale_str.'/description')?>
							</fieldset>
					<?php });
			} else {
				echo Admin_Managers::EntityEdit()->renderShopDataBlocks(
					form: $form,
					renderer: function( EShop $eshop, string $eshop_key ) use ($option, $form) : void {
						?>
							<fieldset>
								<?=$form->field('/eshop_data/'.$eshop_key.'/filter_label')?>
								<?=$form->field('/eshop_data/'.$eshop_key.'/product_detail_label')?>
								<?=$form->field('/eshop_data/'.$eshop_key.'/description')?>
							</fieldset>
					<?php });
			}
			
			?>
		
	</div>
	
	<?php
echo $form->end();

