<?php
namespace JetApplicationModule\Admin\Catalog\Properties;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Property_Options_Option;
use JetApplication\Shops_Shop;

/**
 * @var MVC_View   $this
 * @var Form $form
 * @var Property $property
 * @var Property_Options_Option $option
 */
$property = $this->getRaw('property');
$option = $this->getRaw('option');

$form = $option->getEditForm();
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 2
]);

echo $form->start();

echo Admin_Managers::UI()->renderEntityToolbar($form);
?>
	<div id="main-col">
			<?=$this->getRaw('tabs')?>
			<br>
			
			<?=Admin_Managers::EntityEdit_WithShopData()->renderEntityActivation( $option, !$form->getIsReadonly() )?>
			
			<?=Admin_Managers::EntityEdit_WithShopData()->renderEntityFormCommonFields($form)?>
			<?php
			
			Admin_Managers::EntityEdit_WithShopData()->renderShopDataBlocks(
				form: $form,
				renderer: function( Shops_Shop $shop, string $shop_key ) use ($option, $form) : void {
					$form->field('/shop_data/'.$shop_key.'/url_param')->setIsReadonly(true);
					?>
					<fieldset>
						<legend class="sub"><?=Tr::_('Main data')?></legend>
						
						<?=Admin_Managers::EntityEdit_WithShopData()->renderEntityShopDataActivation( $option, $shop, !$form->getIsReadonly() )?>
						
						<?=$form->field('/shop_data/'.$shop_key.'/filter_label')?>
						<?=$form->field('/shop_data/'.$shop_key.'/product_detail_label')?>
						<?=$form->field('/shop_data/'.$shop_key.'/description')?>
						<?=$form->field('/shop_data/'.$shop_key.'/url_param')?>
					</fieldset>
				<?php }); ?>
		
	</div>
	
	<?php
echo $form->end();

