<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Form;
use Jet\Tr;
use Jet\MVC_View;
use JetShop\Brand;
use JetShop\Parametrization_Property;
use JetShop\Sticker;

/**
 * @var MVC_View   $this
 */

$category = Controller_Main::getCurrentCategory();
$target_category = $category->getTargetCategory();

$target_filter_form = $category->getTargetFilterEditForm();
$target_filter_form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM=>1
])
?>

<?=$this->render('lj_start')?>
<?=$target_filter_form->start()?>


<?php if($target_category): ?>
<fieldset>
	<legend><?=Tr::_('Property filter')?></legend>

	<?php
	foreach($target_category->getParametrizationProperties() as $property):
	if(!$property->getIsFilterable()) {
		continue;
	}

	$field_prefix = '/properties/'.$property->getId();
	?>
	<fieldset>
		<legend class="sub"><?=$property->getGroup()->getShopData()->getLabel()?> - <?=$property->getShopData()->getLabel()?></legend>
		<div style="opacity: 0.5;color: red;">
			<?=$target_filter_form->field($field_prefix.'/disable_filter');?>
		</div>

		<?php
		switch($property->getType()) {
			case Parametrization_Property::PROPERTY_TYPE_BOOL:
				echo $target_filter_form->field($field_prefix.'/selected');
				break;
			case Parametrization_Property::PROPERTY_TYPE_NUMBER:
				echo $target_filter_form->field($field_prefix.'/min');
				echo $target_filter_form->field($field_prefix.'/max');
				break;
			case Parametrization_Property::PROPERTY_TYPE_OPTIONS:
			case Parametrization_Property::PROPERTY_TYPE_STENCIL_OPTIONS:
				?>

				<div class="row form-group">
					<div class="col-md-1"></div>
					<div class="col-md-8">
						<div style="padding: 10px;">
							<?php
							foreach( $property->getOptions() as $option ):
								?>
								<div style="width: 250px;height: 30px;float: left;">
									<?=$target_filter_form->field($field_prefix.'/option_'.$option->getId())->input()?>
								</div>
							<?php
							endforeach;
							?>
						</div>
						<div style="clear: both;margin-bottom: 20px;"></div>

					</div>

				</div>
				<?php
				break;
		}

		endforeach; ?>
	</fieldset>

	<fieldset>
		<legend><?=Tr::_('Sticker filter')?></legend>

		<div class="row form-group">
			<div class="col-md-1"></div>
			<div class="col-md-8">
				<div style="padding: 10px;">
					<?php
					foreach( Sticker::getList() as $sticker ):
						?>
						<div style="width: 250px;height: 30px;float: left;">
							<?=$target_filter_form->field( '/stickers/'.$sticker->getCode() )->input()?>
						</div>
					<?php
					endforeach;
					?>
				</div>
				<div style="clear: both;margin-bottom: 20px;"></div>

			</div>

		</div>

	</fieldset>

	<fieldset>
		<legend><?=Tr::_('Brand filter')?></legend>

		<div class="row form-group">
			<div class="col-md-1"></div>
			<div class="col-md-8">
				<div style="padding: 10px;">
					<?php
					foreach( Brand::getList() as $brand ):
						?>
						<div style="width: 250px;height: 30px;float: left;">
							<?=$target_filter_form->field( '/brands/'.$brand->getId() )->input()?>
						</div>
					<?php
					endforeach;
					?>
				</div>
				<div style="clear: both;margin-bottom: 20px;"></div>

			</div>

		</div>

	</fieldset>

	<fieldset>
		<legend><?=Tr::_('Sort order')?></legend>
		<?=$target_filter_form->field( 'sort_order' )?>
	</fieldset>

<?php endif; ?>

<?=$target_filter_form->end()?>

<?=$this->render('lj_end')?>
