<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Http_Request;
use Jet\UI;
use Jet\Form;
use Jet\Tr;
use Jet\Mvc;
use Jet\Mvc_View;
use JetShop\Category;
use JetShop\Shops;
use JetShopAdmin\Shop_Admin;

/**
 * @var Mvc_View   $this
 */

$category = Controller_Main::getCurrentCategory();
$form = $category->getEditForm();
$form->setDefaultLabelWidth([Form::LJ_SIZE_MEDIUM=>2]);
$form->setDefaultFieldWidth([Form::LJ_SIZE_MEDIUM=>8]);
?>
<?=$this->render('lj_start')?>


<?=$form->start();?>

		<?=$form->field('target_category_id')?>

		<div class="form-group row" style="padding-bottom: 30px;margin-top: 30px;">
			<label class="col-md-2 col-form-label"><?=Tr::_('Target category:')?></label>
			<div class="col-md-8">
				<?=Category::renderSelectCategoryWidget("$('#edit_form__target_category_id').val(selected_item.id);", $category->getTargetCategoryId() )?>
			</div>
		</div>

		<?php foreach(Shops::getList() as $shop):
			$shop_id= $shop->getId();
			$shop_data = $category->getShopData( $shop_id );
			?>
			<?=$shop_data->renderShopDataBlock_start()?>

				<fieldset>
					<legend class="sub"><?=Tr::_('Main data')?></legend>

					<?=$form->field('/shop_data/'.$shop_id.'/is_active')?>

					<?=$form->field('/shop_data/'.$shop_id.'/name')?>
					<?=$form->field('/shop_data/'.$shop_id.'/second_name')?>
				</fieldset>
			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach; ?>

<?=$form->end();?>

<?=$this->render('lj_end')?>