<?php
namespace JetApplicationModule\EShop\ShoppingCart;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Product_EShopData;
use JetApplication\ShoppingCart;

/**
 * @var MVC_View $this
 * @var Product_EShopData $product
 * @var ShoppingCart $cart
 */

$product = $this->getRaw('product');
$cart = $this->getRaw('cart');

$gifts = $cart->getAvailableProductGifts( $product );
$mu = $product->getMeasureUnit();

$p_id = $product->getEntityId();

$delivery_info = $product->getDeliveryInfo();
?>
	<?php if($delivery_info->allowToOrder()): ?>
		<div class="shopping-cart-buy-button">
			<div><input type="number" value="1" step="<?=$mu?->getNumberStep()??1?>" <?php if(!$mu?->isIsDecimalNumber()):?> oninput="this.value=(parseInt(this.value)||0)"<?php endif; ?> id="qty_<?=$product->getId()?>"></div>
			<div><?=$mu?->getName()?></div>
			<?=UI::button(Tr::_('Buy'))->setOnclick("ShoppingCart.buy({$p_id},document.getElementById('qty_{$p_id}').value);")->setClass(UI_button::CLASS_SECONDARY)->setSize(UI_button::SIZE_SMALL)?>
		</div>
		<?php


		if($gifts):
			?>
		<div class="shopping-cart-product-gifts">
			<div class="title"><?=Tr::_('Gift:')?></div>
			<?php foreach($gifts as $gift): ?>
				<div class="gift-item"><?=$gift->getGiftProduct()->getName();?></div>
			<?php endforeach; ?>
		</div>
		<?php
		endif;
	endif;