<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\ShoppingCart;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Product_EShopData;

/**
 * @var MVC_View $this
 * @var Product_EShopData $product
 */

$product = $this->getRaw('product');

if(
	$product->getMeasureUnit()?->isIsDecimalNumber() ||
	!$product->getDeliveryInfo()->getAllowToOrderMore()
) {
	return;
}


echo UI::button(Tr::_('Buy'))->setOnclick('ShoppingCart.buy('.$product->getEntityId().',1);')->setClass(UI_button::CLASS_SECONDARY)->setSize(UI_button::SIZE_NORMAL);