<?php
namespace JetApplicationModule\Admin\ReturnsOfGoods;

use Jet\Form;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

use Jet\MVC_View;


/**
 * @var MVC_View $this
 * @var ReturnOfGoods     $return_of_goods
 * @var Form $form
 */

$return_of_goods = $this->getRaw( 'return_of_goods' );
$form = $this->getRaw('delivery_address_form');


if(!$return_of_goods->isEditable()) {
	return;
}

?>
<div style="text-align: center;padding: 10px;">
<?=UI::button(Tr::_('Edit'))->setIcon('pen-to-square')
	->setClass(UI_button::CLASS_PRIMARY)
	->setOnClick("$('#delivery_address_dialog').modal('show');")?>
</div>

