<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Invoices;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Admin_Managers;
use JetApplication\CustomerBlacklist;
use JetApplication\Invoice;

/**
 * @var MVC_View $this
 * @var Invoice $item
 */

$item = $this->getRaw('item');
?>
<?php if($item->getCustomerCompanyName()): ?>
<?=$item->getCustomerCompanyName()?><br>
<?php endif; ?>
<?=$item->getCustomerFirstName()?> <?=$item->getCustomerSurname()?> (<?=Admin_Managers::Customer()->showName( $item->getCustomerId() )?>)<br>
<a href="mailto:<?=$item->getCustomerEmail()?>"><?=$item->getCustomerEmail()?></a><br>
<?=$item->getCustomerPhone()?><br>


<?php if( CustomerBlacklist::customerIsBlacklisted( $item->getCustomerEmail() ) ): ?>
	<div class="alert alert-danger" role="alert">
		<?=UI::icon('skull-crossbones')?> <?=Tr::_('Customer is blacklisted')?>
	</div>
<?php endif; ?>
