<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Invoices;


use Jet\MVC_View;
use JetApplication\Invoice;

/**
 * @var MVC_View $this
 * @var Invoice $item
 */

$item = $this->getRaw('item');
?>
<ul>
<?php foreach($item->getItems() as $item): ?>
	<li><?=$item->getTitle();?></li>
<?php endforeach;  ?>
</ul>