<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\Invoices;

use Jet\MVC_View;
use Jet\Tr;
use JetApplicationModule\Admin\Entity\Listing\Listing;

/**
 * @var MVC_View $this
 * @var Listing $listing
 * @var Invoice $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
<?php if($item->hasCorrections()): ?>
	<a href="<?=$listing->getEditUrl( $item );?>" style="text-decoration: line-through"><?=$item->getNumber();?></a>
<?php else: ?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=$item->getNumber();?></a>
<?php endif; ?>


<?php if($item->getIsCorrectionInvoice()): ?>
<div class="text-danger">
<?=Tr::_('Correction of:<br><a href="%URL%">%NUMBER%</a>', [
		'URL' => Main::getEditUrl( $item->getCorrectionOfInvoiceId() ),
		'NUMBER' => $item->getCorrectionOfInvoiceNumber()
	])?>
</div>
<?php endif; ?>
