<?php
use Jet\UI;
use Jet\MVC_View;
use JetApplication\Entity_WithEShopData;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 * @var Entity_WithEShopData $item
 */

$item = $this->getRaw('item');

if(EShops::isMultiEShopMode()):
	?>
	
	<div class="dropdown">
		<button class="btn btn-info dropdown-toggle" type="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<?=UI::icon('eye');?>
		</button>
		<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			<?php foreach( EShops::getListSorted() as $eshop ):
				$URL = $item->getEshopData($eshop)->getURL();
				if(!$URL) {
					continue;
				}
				?>
					<a class="dropdown-item" href="<?=$URL?>?cache_prevent_<?=uniqid()?>" target="_blank">
						<?=UI::icon('arrow-up-right-from-square')->addCustomCssStyle('opacity:0.5');?>
						<?=$eshop->getName()?>
					</a>
			<?php endforeach; ?>
		</div>
	</div>
<?php
else:
	foreach( EShops::getListSorted() as $eshop ):
		$URL = $item->getEshopData($eshop)->getURL();
		if($URL):
			?>
			<a href="<?=$URL?>?cache_prevent_<?=uniqid()?>" target="_blank" class="btn btn-info"><?=UI::icon('eye');?></a>
			<?php
			continue;
		endif;
	endforeach;
endif;
?>
