<?php
namespace JetApplicationModule\Admin\WarehouseManagement\StockStatusOverview;

use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_badge;
use JetApplication\Admin_Managers;
use JetApplication\WarehouseManagement_StockMovement;

/**
 * @var MVC_View $this
 * @var WarehouseManagement_StockMovement $mv
 */

$mv = $this->getRaw('movement');
?>
<tr <?php if($mv->getCancelled()): ?>style="text-decoration: line-through"<?php endif;?> class="table-success">
	<td>
		<?=Locale::dateAndTime($mv->getDateTime())?>
	</td>
	<td>
		<?=Admin_Managers::Context()->showContext($mv->getContext())?>
	</td>
	<td>
		<?php
		echo Tr::_('Receipt of goods');
		
		if($mv->getCancelled()):
			echo '<br>';
			echo UI::badge(
				UI_badge::INFO,
				Tr::_('Cancelled %date%', ['date'=>Locale::dateAndTime($mv->getCancelledDateTime())])
			);
		endif;
		
		?>
	</td>
	<td>
		<?=Locale::float($mv->getNumberOfUnits())?> <?=$mv->getMeasureUnit()?->getName()?>
	</td>
	<td>
		<?php if($mv->getCurrency()): ?>
			<?=Admin_Managers::PriceFormatter()->formatWithCurrency( $mv->getCurrency(), $mv->getPricePerUnit() )?>
			<?php if($mv->getEntryCurrencyIsDifferent()): ?>
				<br>
				<?=Admin_Managers::PriceFormatter()->formatWithCurrency( $mv->getEntryCurrency(), $mv->getEntryPricePerUnit() )?>
			<?php endif; ?>
		<?php endif; ?>
	</td>
	<td>
		<?php if($mv->getCurrency()): ?>
			<?=Admin_Managers::PriceFormatter()->formatWithCurrency( $mv->getCurrency(), $mv->getPricePerUnit()*$mv->getNumberOfUnits() )?>
			<?php if($mv->getEntryCurrencyIsDifferent()): ?>
				<br>
				<?=Admin_Managers::PriceFormatter()->formatWithCurrency( $mv->getEntryCurrency(), $mv->getEntryPricePerUnit()*$mv->getNumberOfUnits() )?>
			<?php endif; ?>
		<?php endif; ?>
	</td>
	<td>
		<?php if($mv->getCurrency()): ?>
			<?php if($mv->getEntryCurrencyIsDifferent()): ?>
				<?=$mv->getEntryCurrencyExchangeRate()?>
			<?php endif; ?>
		<?php endif; ?>
	</td>
	<td>
		<?php if($mv->getSector() || $mv->getRack() || $mv->getPosition()):
			echo $mv->getSector().'-'.$mv->getRack().'-'.$mv->getPosition();
		endif; ?>
	</td>
</tr>

