<?php
use JetApplication\Entity_Basic;
use JetApplication\Entity_Admin_Interface;

use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Entity_Basic|Entity_Admin_Interface     $item
 */

$form = $this->getRaw('form');
$item = $this->getRaw('item');

$form->field('delivery_methods')->input()->addCustomCssStyle('height: 400px');

?>
<?=$form->field( 'is_default' )?>
<?=$form->field( 'delivery_methods' )?>
