<?php
namespace JetApplicationModule\EShop\ReturnsOfGoods;

use Jet\MVC_View;
use JetApplication\ReturnOfGoods;

/**
 * @var MVC_View   $this
 * @var ReturnOfGoods $return
 */
$return = $this->getRaw('return');
$status = $return->getStatus();
?>
<div class="return-of-goods-status-status return-of-goods-status-status-<?=$status?->getCode()?>">
	<div class="return-of-goods-status-status-title"><?=$status?->getTitle()?></div>
</div>