<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ReturnsOfGoods;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Application_Service_Admin;
use JetApplication\Product;
use JetApplication\ReturnOfGoods;

/**
 * @var MVC_View $this
 * @var ReturnOfGoods     $return
 */

$return = $this->getRaw( 'return' );

$money_refunds = Application_Service_Admin::MoneyRefund()?->showMoneyRefunds( $return->getProvidesContext() );

?>
<?php require 'edit/toolbar.phtml';?>

<div id="main-col">
	<div id="o_main" class="o_anchor"></div>
	<fieldset class="o_section">
		<?php require 'edit/main.phtml'; ?>
	</fieldset>

	<div id="o_product" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('Product')?></h5>

			<div style="display: flex;gap: 10px;align-items: center">
				<?php if(($p=Product::get($return->getProductId()))): ?>
					<?=Application_Service_Admin::EntityEdit()->renderPreviewButton( $p )?>
				<?php endif; ?>
				<div>
					<?=Application_Service_Admin::Product()->renderItemName( $return->getProductId() )?>
				</div>
			</div>

		</div>
	</fieldset>

	<div id="o_description" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('Description of the problem')?></h5>

			<p><?=nl2br($return->getProblemDescription())?></p>
		</div>
	</fieldset>



	<div id="o_url" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('URL')?></h5>
			<p><a href="<?=$return->getURL()?>" target="_blank"><?=$return->getURL()?></a></p>
		</div>
	</fieldset>
	
	<?php if( $money_refunds ): ?>
		<div id="o_money_refund" class="o_anchor"></div>
		<?=$money_refunds?>
	<?php endif; ?>
	

	<div id="o_history" class="o_anchor"></div>
	<?=Application_Service_Admin::EntityEdit()->renderEventHistory( $return, true )?>


	<div id="o_sent_emails" class="o_anchor"></div>
	<?=Application_Service_Admin::EntityEdit()->renderSentEmails( $return, true )?>

	<br><br><br><br>
</div>

<?php
foreach( Plugin::getPlugins() as $handler):
	echo $handler->renderDialog();
endforeach;

