<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ReturnsOfGoods;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Admin_Managers;
use JetApplication\ReturnOfGoods;

/**
 * @var MVC_View $this
 * @var ReturnOfGoods     $return
 */

$return = $this->getRaw( 'return' );

?>
<?php require 'edit/toolbar.phtml';?>

<div id="main-col">
	<div id="o_main" class="o_anchor"></div>
	<fieldset class="o_section">
		<?php require 'edit/main.phtml'; ?>
	</fieldset>

	<div id="o_product" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('Product')?></h5>

			<p><?=Admin_Managers::Product()->renderItemName( $return->getProductId() )?></p>
		</div>
	</fieldset>

	<div id="o_description" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('Description of the problem')?></h5>

			<p><?=nl2br($return->getProblemDescription())?></p>
		</div>
	</fieldset>



	<div id="o_url" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('URL')?></h5>
			<p><a href="<?=$return->getURL()?>" target="_blank"><?=$return->getURL()?></a></p>
		</div>
	</fieldset>


	<div id="o_history" class="o_anchor"></div>
	<fieldset class="o_section">
		<legend><?=UI::icon('clock-rotate-left')?> <?=Tr::_('History')?></legend>
		<div id="event-history">
			<?=Admin_Managers::EntityEdit()->renderEventHistory( $return )?>
		</div>
	</fieldset>


	<div id="o_sent_emails" class="o_anchor"></div>
	<fieldset class="o_section">
		<legend><?=UI::icon('envelope-circle-check')?> <?=Tr::_('Sent e-mails')?></legend>

		<div id="sent-emails">
			<?=Admin_Managers::EntityEdit()->renderSentEmails( $return )?>
		</div>
	</fieldset>

	<br><br><br><br>
</div>

<?php
foreach( Plugin::getPlugins() as $handler):
	echo $handler->renderDialog();
endforeach;

