<?php
namespace JetShopModule\Admin\Payment\Methods;

use JetShop\Payment_Method;

use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use JetShop\Payment_Method_Option;
use JetShop\Shops;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Payment_Method     $payment_method
 * @var Payment_Method_Option    $new_option
 */

$new_option = $this->getRaw('new_option');

$form = $new_option->getAddForm();

$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 1 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );

?>
<?=$form->start()?>
<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?=UI::button_save()?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>

		<br/>
		<?=$form->field('code')?>

		<?php foreach(Shops::getListSorted() as $shop):
			$shop_key = $shop->getKey();
			$shop_data = $new_option->getShopData( $shop );
			?>
			<?=$shop_data->renderShopDataBlock_start()?>
				<?=$form->field('/shop_data/'.$shop_key.'/is_active')?>
				<?=$form->field('/shop_data/'.$shop_key.'/title')?>
				<?=$form->field('/shop_data/'.$shop_key.'/description')?>
			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach; ?>

	</div>
</div>
<?=$form->end()?>