<?php
namespace JetApplication;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

/**
 * @var MVC_View $this
 * @var Product $product
 */

$product = $this->getRaw('product');
?>

<div class="card bg-light" style="float: left; height: 200px;margin: 10px;padding: 10px; width: 300px;position: relative">
	<?php /*
	<div class="images">
		<a href="<?= $product->getURL() ?>" class="image">
			<?php

			if($product->getImage()):
				?>
				<img src="<?=$product->getImageThumbnailUrl( 350, 350 )?>"/>
			<?php
			endif;
			?>
		</a>

		<?php if ($product->getImage(1)): ?>
			<div class="thumbnails-icon"></div>
			<div class="thumbnails">
				<div class="list">
					<?php
					for ($i = 0; $i <= 3; $i++) {
						$img = $product->getImage($i);
						if (!$img) {
							break;
						}
						$selected = ($i == 0) ? ' class="selected"' : '';
						?>
						<div data-product-preview-thumb data-src="<?= $img ?>"<?= $selected ?>>
							<img src="<?=$product->getImageThumbnailUrl( 350, 350, $i )?>"/>
						</div>
						<?php
					}
					?>
				</div>
			</div>
		<?php endif; ?>
	</div>
    */ ?>

	<a href="<?= $product->getUrl() ?>" class="title"><?= $product->getName() ?></a>

	<div class="availability">
		<?php /*= $product->getDeliveryText(($product->getProductsQuantity() >= 10) ? '<span>' . SKLADEM_10AVIC . sklonovaniKusu(10) . '</span>' : '<span>' . SKLADEM_.' ' . $product->getProductsQuantity() . ' ' . sklonovaniKusu($product->getProductsQuantity()) . '</span>' )*/ ?>
	</div>

	<div class="prices" style="position: absolute;right: 10px;bottom: 60px;">
		<?php if ($product->getActionPrice()): ?>
			<div class="price-rtp"><?= Price::formatWithCurrency( $product->getStandardPrice() ) ?></div>
		<?php endif; ?>
		<div class="price-final"><b><?= Price::formatWithCurrency( $product->getFinalPrice() ) ?></b></div>
	</div>

	<div class="buttons" style="position: absolute;bottom:5px;right: 5px;">
		<?=UI::button(Tr::_('More info'))->setUrl($product->getUrl())->setClass('default')->setSize(UI_button::SIZE_SMALL)?>

		<?php if ($product->getType()==Product::PRODUCT_TYPE_VARIANT_MASTER): ?>
			<?=UI::button(Tr::_('Select variant'))->setUrl($product->getURL())->setClass('success')->setSize(UI_button::SIZE_SMALL)?>
		<?php else: ?>
			<?=UI::button(Tr::_('Add to cart'))->setOnclick('ShoppingCart.buy('.$product->getId().',1);')->setClass('success')->setSize(UI_button::SIZE_SMALL)?>
		<?php endif; ?>
	</div>

</div>

