<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Product_ShopData;
use JetApplication\Shop_Managers;

/**
 * @var MVC_View $this
 * @var Product_ShopData $product
 */

$product = $this->getRaw('product');
?>

<div class="card bg-light" style="height: 200px;margin: 10px;padding: 10px;">
	<div class="images">
		<a href="<?= $product->getURL() ?>" class="image">
			<?php

			if($product->getImgUrl(0)):
				?>
				<img src="<?=$product->getImgThumbnailUrl( 0, 150, 150 )?>"/>
			<?php
			endif;
			?>
		</a>

		<?php /*if ($product->getImageUrl(1)): ?>
			<div class="thumbnails-icon"></div>
			<div class="thumbnails">
				<div class="list">
					<?php
					for ($i = 0; $i <= 3; $i++) {
						$img = $product->getImageUrl($i);
						if (!$img) {
							break;
						}
						$selected = ($i == 0) ? ' class="selected"' : '';
						?>
						<div data-product-preview-thumb data-src="<?= $img ?>"<?= $selected ?>>
							<img src="<?=$product->getImageThumbnailUrl( $i, 150, 150 )?>"/>
						</div>
						<?php
					}
					?>
				</div>
			</div>
		<?php endif;*/ ?>
	</div>

	<a href="<?= $product->getUrl() ?>" class="title"><?= $product->getFullName() ?></a>

	<div class="availability">
	</div>

	<div class="prices" style="position: absolute;right: 10px;bottom: 60px;">
		<?php if ($product->getStandardPrice()): ?>
			<div class="price-rtp" style="text-decoration: line-through"><?= Shop_Managers::PriceFormatter()->formatWithCurrency( $product->getStandardPrice() ) ?></div>
		<?php endif; ?>
		<div class="price-final"><b><?= Shop_Managers::PriceFormatter()->formatWithCurrency( $product->getPrice() ) ?></b></div>
	</div>

	<div class="buttons" style="position: absolute;bottom:5px;right: 5px;">
		<?=UI::button(Tr::_('More info'))->setUrl($product->getUrl())->setClass('default')->setSize(UI_button::SIZE_SMALL)?>

		<?php if ($product->isVariantMaster()): ?>
			<?=UI::button(Tr::_('Select variant'))->setUrl($product->getURL())->setClass('success')->setSize(UI_button::SIZE_SMALL)?>
		<?php else: ?>
			<?=UI::button(Tr::_('Add to cart'))->setOnclick('ShoppingCart.buy('.$product->getEntityId().',1);')->setClass('success')->setSize(UI_button::SIZE_SMALL)?>
		<?php endif; ?>
	</div>

</div>

