<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\Discounts\CodesDefinition;

use Jet\MVC_View;
use JetApplication\Admin_Managers_EShopEntity_Listing;
use JetApplication\Discounts_Code;

/**
 * @var MVC_View $this
 * @var Admin_Managers_EShopEntity_Listing $listing
 * @var Discounts_Code $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
<?=nl2br( $item->getInternalNotes() )?>
