<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\Discounts\CodesDefinition;

use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Discounts_Code;

/**
 * @var MVC_View $this
 * @var Discounts_Code $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::PriceFormatter()->formatWithCurrency( $item->getEshop()->getDefaultPricelist(), $item->getMinimalOrderAmount() );