<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Discounts\CodesDefinition;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Discounts_Code;

/**
 * @var MVC_View $this
 * @var Discounts_Code $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::PriceFormatter()->formatWithCurrency( $item->getEshop()->getDefaultPricelist(), $item->getMinimalOrderAmount() );