<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\Discounts\CodesDefinition;


use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var DiscountsCode $item
 */

$item = $this->getRaw('item');

if($item->isActive()) {
	$class = 'active';
} else {
	if($item->isWaiting()) {
		$class = 'waiting';
	} else {
		$class = 'expired';
	}
}


if(!$item->getValidTill()):
	?>
	<div class="time-interval time-interval-<?=$class?>"><?=Tr::_('Unlimited')?></div>
	<?php
	return;
endif;
?>
	<div class="time-interval time-interval-<?=$class?>"><?=Locale::dateAndTime( $item->getValidTill() )?></div>
<?php
