<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\Customer\Login;


use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Customer;
use JetApplication\EShop_Managers;
use JetApplication\EShop_Pages;

$customer = Customer::getCurrentCustomer();

$form = Main::getLogoutForm();

$dialog = UI::dialog('customer_detail_dialog', '');

$manager_name = EShop_Managers::CustomerLogin()->getModuleManifest()->getName();

echo UI::button( '' )
	->setIcon('user')
	->setClass( UI_button::CLASS_LIGHT )
	->setOnClick( "dialog.open('customer_detail_dialog')" );

?>

<?=$dialog->start()?>

<div class="user-name">
	<?=UI::icon('user')?>
	<a href="<?=EShop_Pages::CustomerSection()->getURL()?>"><?=$customer->getName()?></a><br>
	
</div>

<div class="buttons">
	<?=UI::button(Tr::_('Show my account detail', dictionary: $manager_name ))->setUrl( EShop_Pages::CustomerSection()->getURL() )->setClass(UI_button::CLASS_SUCCESS)?><br>
	<?=UI::button(Tr::_('Sign out', dictionary: $manager_name))->setOnclick('CustomerLogin.logout();')->setClass(UI_button::CLASS_INFO)?>
</div>

<?=$dialog->end()?>


<?=$this->render('js')?>

<?=$form->start()?>
<?=$form->end()?>
