<?php
namespace JetApplication;

use Jet\MVC_Layout;
use Jet\MVC;

/**
 * @var MVC_Layout $this
 */

$this->setVar('customer_icon', true);
$this->setVar('shopping_cart_icon', true);
$this->setVar('compare_icon', true);
$this->setVar('wishlist_icon', true);
?>
<!DOCTYPE html>
<html lang="<?=MVC::getLocale()->getLanguage()?>">
<head>
	<?php require 'parts/head.phtml'; ?>
</head>
<body>
	<?=Application_Service_EShop::AnalyticsManager()?->documentStart()?>
	<div id="main-container">
		<?php  require 'parts/header.phtml';  ?>
		<?=Application_Service_EShop::UI()->renderBreadcrumbNavigation()?>
		<div id="content">
			<jet_layout_main_position/>
		</div>
		<?php require 'parts/footer.phtml'; ?>
	</div>

	<?=Application_Service_EShop::ShoppingCart()->renderIntegration();?>
	<?=Application_Service_EShop::CustomerPasswordReset()->renderIntegration();?>
	<?=Application_Service_EShop::Compare()?->renderIntegration();?>
	<?=Application_Service_EShop::Wishlist()?->renderIntegration();?>
	<?=Application_Service_EShop::CookieSettings()?->renderDialog()?>
	
	<?=Application_Service_EShop::AnalyticsManager()?->documentEnd()?>
</body>
</html>