<?php
use Jet\MVC_Layout;
use Jet\MVC;
use JetApplication\Application_Service_EShop;

/**
 * @var MVC_Layout $this
 */
?>
<!DOCTYPE html>
<html lang="<?=MVC::getLocale()->getLanguage()?>">
<head>
	<?php require 'parts/head.phtml'; ?>
</head>
<body>
	<?=Application_Service_EShop::AnalyticsManager()?->documentStart()?>
	<jet_layout_main_position/>
	<?=Application_Service_EShop::AnalyticsManager()?->documentEnd()?>
</body>
</html>