<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Marketing\CategoryBanners;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use JetApplication\Application_Service_Admin;

/**
 * @var MVC_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
//$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
//$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );


$cf = $form->field('_category_ids');
$cf_id = $cf->getId();

$this->setVar('category_ids', $cf->getValue() ? explode(',', $cf->getValue()): [] );


echo $form->field('_category_ids');
echo $form->field( 'URL' );
echo $form->field( 'for_product_listing' );

?>
<div class="form-group row">
	<div class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?= Tr::_('Categories:')?></div>
	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
		<?php if( Main::getCurrentUserCanEdit() ): ?>
			<?= Application_Service_Admin::Category()->renderSelectWidget("Catgories.add(selected_item.id);", name: 'add_category')?>
		<?php endif ?>
		
		<div id="categoeies">
			<?=$this->render('edit/main/categories')?>
		</div>
		<br><br><br><br><br><br>
		<br><br><br><br><br><br>
	</div>
</div>

<?php if( Main::getCurrentUserCanEdit() ): ?>
	<script>
		const Catgories = {
			getCurrent: () => {
				let ids = document.getElementById('<?=$cf_id?>').value;
				if(!ids) {
					return [];
				}

				return ids.split(',');
			},
			actualize: ( ids ) => {
				ids = ids.join(',');
				document.getElementById('<?=$cf_id?>').value = ids;
				$('#categoeies').load( '<?=Http_Request::currentURI()?>&show_categories='+ids );
			},
			add: (id) => {
				id = id+'';

				let current = Catgories.getCurrent();
				if(current.includes(id)) {
					return;
				}
				current.push(id);
				Catgories.actualize( current );
			},
			remove: (id) => {
				id = id+'';

				let current = Catgories.getCurrent();

				console.debug(current, current.includes(id));

				if(!current.includes(id)) {
					return;
				}


				current.splice(current.indexOf(id), 1);

				Catgories.actualize( current );
			}
		};
	</script>
<?php endif ?>
