<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Marketing\CategoryBanners;


use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use JetApplication\Application_Service_Admin;

/**
 * @var MVC_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
//$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
//$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );


echo $form->field( 'URL' );
echo $form->field( 'for_product_listing' );

?>
<div class="form-group row">
	<div class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?= Tr::_('Categories:')?></div>
	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
		<?= /** @noinspection PhpParamsInspection */
		Application_Service_Admin::Category()->renderSelectCategoriesWidget( $form->field('_category_ids') )?>
		<br><br><br><br><br><br>
		<br><br><br><br><br><br>
	</div>
</div>

