<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\Tr;
use Jet\UI;
use JetApplication\Customer;

$cash_desk = CashDesk::get();

if($cash_desk->getBillingAddressHasBeenSet()) {
	require 'billing_address/has_been_set.phtml';

	return;
}


$form = $cash_desk->getBillingAddressForm();


$cash_desk->setBillingAddressEditable( true );

foreach($form->getFields() as $field) {
	if($field->getValue() && !$field->getLastErrorCode()) {
		$field->input()->addCustomCssClass('is-valid');
	}
}

?>
<span class="step-title"><?=Tr::_('Billing address')?></span>

<?php
if( Customer::getCurrentCustomer() ) {
	require 'billing_address/select_address.phtml';
}

require 'billing_address/company_person_switch.phtml';
?>


<?=$form->start()?>

<?php if ($cash_desk->isCompanyOrder()): ?>
	<div id="field_<?=$form->field('company_name')->getId()?>">
		<?=$form->field('company_name')?>
	</div>
	<div id="field_<?=$form->field('company_id')->getId()?>">
		<?=$form->field('company_id')?>
	</div>
	<div id="field_<?=$form->field('company_vat_id')->getId()?>">
		<?=$form->field('company_vat_id')?>
	</div>
<?php endif; ?>

	<div id="field_<?=$form->field('first_name')->getId()?>">
		<?=$form->field('first_name')?>
	</div>
	<div id="field_<?=$form->field('surname')->getId()?>">
		<?=$form->field('surname')?>
	</div>


	<div id="field_<?=$form->field('address_street_no')->getId()?>">
		<?=$form->field('address_street_no')?>
	</div>
	<div id="field_<?=$form->field('address_town')->getId()?>">
		<?=$form->field('address_town')?>
	</div>
	<div id="field_<?=$form->field('address_zip')->getId()?>">
		<?=$form->field('address_zip')?>
	</div>

<div class="continue-button-area">
	<?=UI::button(Tr::_('Continue'))->setType('submit')->setClass('primary')?>
</div>

<?=$form->end()?>
