<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;

$cash_desk = CashDesk::get();

$form = $cash_desk->getSetEMailForm();

$form->renderer()->addJsAction('onsubmit', 'CashDesk.customer.email.set();return false;');

$form->renderer()->setDefaultLabelWidth([
		Form_Renderer::LJ_SIZE_MEDIUM => '3'
]);

$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => '9'
]);

?>


<span class="step-title"><?=Tr::_("Please tell us your e-mail or log-in using your Google or Facebook account.")?></span>
<?=$form->start()?>
<?=$form->field('email')?>

<div class="continue-button-area">
	<?=UI::button('Continue')->setClass('primary')->setType('submit')?>
</div>
<?=$form->end()?>

