<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;

$cash_desk = CashDesk::get();

$form = $cash_desk->getLoginForm();
$form->renderer()->setDefaultLabelWidth([
		Form_Renderer::LJ_SIZE_MEDIUM => 2
]);
$form->renderer()->setDefaultFieldWidth([
		Form_Renderer::LJ_SIZE_MEDIUM => 10
]);

$form->renderer()->addJsAction('onsubmit', 'CashDesk.customer.registration.login();return false;');
?>

<div class="step-title"><?=Tr::_('Welcome back!')?></div>

<?=Tr::_('Please log in. Maybe we have a loyalty discount for you :-)')?><br />
<br />
<?=Tr::_('Please enter a valid password for your <strong>%EMAIL% </strong> user account', ['EMAIL'=>$cash_desk->getEmailAddress()])?>
(<a href="#" onclick="CashDesk.customer.email.back();return false;"><?=Tr::_('change e-mail')?></a>)<br />
<br />
<br />


<?=$form->start()?>
<?=$form->message()?>
<?=$form->field('password')?>

<div class="continue-button-area">
	<?=UI::button(Tr::_('Today I prefer to continue without logging in'))->setClass('link')->setOnclick('CashDesk.customer.registration.continueWithoutRegistration();')?>
	<?=UI::button(Tr::_('I forget password ...'))->setClass('info')->setOnclick('CustomerLogin.passwordReset.start();')?>
	<?=UI::button(Tr::_('Continue'))->setClass('primary')->setOnclick('CashDesk.customer.registration.login();')?>
</div>
<?=$form->end()?>


