<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\Form_Field_Hidden;
use Jet\Http_Request;
use Jet\MVC_View;
use JetApplication\Application_Service_Admin;

/**
 * @var MVC_View $this
 * @var Form_Field_Hidden $input
 */

$input = $this->getRaw('input');

$name = $input->getId();

echo $input;

?>

<div class="card card-body">
<?php if( !$input->getIsReadonly() ): ?>
	<?= Application_Service_Admin::Product()->renderSelectWidget("Products_{$name}.add(selected_item.id);", name: 'add_product_'.$name)?>
<?php endif ?>

<div id="products_<?=$name?>" style="height: 400px;overflow: auto;">
	<?=$this->render('select-products/products')?>
</div>
</div>

<?php if( !$input->getIsReadonly() ): ?>
	<script>
		const Products_<?=$name?> = {
			getCurrent: () => {
				let ids = document.getElementById('<?=$input->getId()?>').value;
				if(!ids) {
					return [];
				}

				return ids.split(',');
			},
			actualize: ( ids ) => {
				ids = ids.join(',');
				document.getElementById('<?=$input->getId()?>').value = ids;
				$('#products_<?=$name?>').load( '<?=Http_Request::currentURI()?>&show_products='+ids+'&input_id=<?=$input->getId()?>' );
			},
			add: (id) => {
				id = id+'';

				let current = Products_<?=$name?>.getCurrent();
				if(current.includes(id)) {
					return;
				}
				current.push(id);
				Products_<?=$name?>.actualize( current );
			},
			remove: (id) => {
				id = id+'';

				let current = Products_<?=$name?>.getCurrent();

				if(!current.includes(id)) {
					return;
				}


				current.splice(current.indexOf(id), 1);

				Products_<?=$name?>.actualize( current );
			}
		};
	</script>
<?php endif ?>
