<?php
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Entity_WithEShopData;

/**
 * @var MVC_View $this
 * @var Entity_WithEShopData $entity
 */

$entity = $this->getRaw('entity');
?>
<div style="padding: 10px;">
	<?php if($entity->isActive()): ?>
		<span class="btn btn-success"><?= UI::icon('check');?> <?=Tr::_('Active')?></span>
	<?php else: ?>
		<span class="btn btn-danger"><?= UI::icon('circle-xmark');?> <?=Tr::_('Not active')?></span>
	<?php endif; ?>
</div>