<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\WarehouseManagement\TransferBetweenWarehouses;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_badge;
use JetApplication\WarehouseManagement_TransferBetweenWarehouses;

/**
 * @var MVC_View $this
 * @var WarehouseManagement_TransferBetweenWarehouses $item
 */

$item = $this->getRaw('item');

echo match ($item->getStatus()) {
	WarehouseManagement_TransferBetweenWarehouses::STATUS_PENDING
		=> UI::badge( UI_badge::INFO, Tr::_( 'Pending' ) )->addCustomCssStyle( 'padding:10px' ),
	WarehouseManagement_TransferBetweenWarehouses::STATUS_SENT
		=> UI::badge( UI_badge::PRIMARY, Tr::_( 'Sent' ) )->addCustomCssStyle( 'padding:10px' ),
	WarehouseManagement_TransferBetweenWarehouses::STATUS_RECEIVED
	=> UI::badge( UI_badge::SUCCESS, Tr::_( 'Received' ) )->addCustomCssStyle( 'padding:10px' ),
	WarehouseManagement_TransferBetweenWarehouses::STATUS_CANCELLED
		=> UI::badge( UI_badge::DANGER, Tr::_( 'Cancelled' ) )->addCustomCssStyle( 'padding:10px' ),
	default
	=> $item->getStatus(),
};
