<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ControlCentreModule\CompanyInfo;


use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\UI;
use JetApplication\Application_Service_Admin_Image;
use JetApplication\CompanyInfo;

/**
 * @var MVC_View   $this
 * @var CompanyInfo $info
 * @var Application_Service_Admin_Image $image_manager
 */

$info = $this->getRaw('info');
$image_manager = $this->getRaw('image_manager');

$form = $info->getEditForm();

$form->renderer()->setDefaultLabelWidth([Form_Renderer::LJ_SIZE_MEDIUM=>3]);
$form->renderer()->setDefaultFieldWidth([Form_Renderer::LJ_SIZE_MEDIUM=>8]);


echo $image_manager->renderMain();
?>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-8">
		<?=$image_manager->renderImageWidgets()?>
	</div>
</div>

<?=$form->start()?>

<?php foreach($form->getFields() as $field):
	echo $field;
endforeach;  ?>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-8">
		<?=UI::button_save()?>
	</div>
</div>

<?=$form->end();?>
