<?php
use JetApplication\Entity_Basic;
use JetApplication\Entity_Admin_Interface;

use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Entity_Basic|Entity_Admin_Interface     $item
 */

$form = $this->getRaw('form');
$item = $this->getRaw('item');

echo $form->field('backend_module_name');
echo $form->field('company_name');
echo $form->field('company_id');
echo $form->field('company_vat_id');
echo $form->field('address_street_and_no');
echo $form->field('address_town');
echo $form->field('address_town');
echo $form->field('address_zip');
echo $form->field('address_country');
echo $form->field('locale');
echo $form->field('phone_1');
echo $form->field('phone_2');
echo $form->field('email_1');
echo $form->field('email_2');
echo $form->field('currency_code');