<?php
use Jet\MVC_View;
use JetApplication\Discounts_Code;

/**
 * @var MVC_View $this
 * @var Discounts_Code $discounts_code
 */

$value = 100;

$discounts_code = $this->getRaw('discounts_code');
$discounts_code->setDiscount( $value );
$discounts_code->save();

?>
Vážený zákazníku,

omlouváme se za problémy s reklamací <?=$this->getRaw('complaint_number')?>.

Jako omluvu přijměte slevový kupon <?=$discounts_code->getCode()?> na časku <?=$value?>,- Kč.