<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Marketing\PromoAreas;


use Jet\MVC_View;
use JetApplication\Marketing_PromoArea;
use JetApplication\Marketing_PromoAreaDefinition;


/**
 * @var MVC_View $this
 * @var Marketing_PromoArea $item
 */

$item = $this->getRaw('item');
echo Marketing_PromoAreaDefinition::getScope()[$item->getPromoAreaId()];
