<?php
namespace JetApplicationModule\Admin\Catalog\Categories;

use Jet\MVC_View;
use Jet\UI;

/**
 * @var MVC_View   $this
 * @var Controller_Main $controller
 */
$controller = $this->controller;
$category = $this->controller->getCurrentItem();

$form = $category->getEditForm();

if($form->getIsReadonly()) {
	return;
}

$form_id = $form->getId();

?>
<?=UI::button_save()->setOnclick("$('#$form_id').submit();")?>
