<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Catalog\Categories;


use Jet\MVC_View;
use Jet\UI;
use Jet\Form;

/**
 * @var MVC_View   $this
 * @var Controller_Main $controller
 * @var Form $form
 */
$controller = $this->controller;
$category = $this->controller->getCurrentItem();

$form = $this->getRaw('form');

if($form->getIsReadonly()) {
	return;
}

$form_id = $form->getId();

?>
<?=UI::button_save()->setOnclick("$('#$form_id').submit();")?>
