<?php
use Jet\Mvc_View;
use Jet\Form_Field;
use JetShop\Shops;

/**
 * @var Mvc_View      $this
 * @var Form_Field $f
 */
$f = $this->getRaw( 'field' );

$shop = Shops::getCurrent();


echo $f->row()->start();
echo $f->label();
echo $f->container()->start();
?>
	<div class="input-group">
						<span class="input-group-prepend">
							<span class="input-group-text"><?=$shop->getPhonePrefix()?></span>
						</span>
		<?=$f->input()?>
		<?=$f->error();?>
	</div>
<?php
echo $f->container()->end();
echo $f->row()->end();

