<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');
?>
	<?php if($cash_desk->getPhoneHasBeenSet()): ?>
	<div class="selected-contact">
		<div><b><?=Tr::_('Phone:')?></b></div>
		<div>
			<?=$cash_desk->getPhone()?>
		</div>
		<div>
			<?=UI::button(Tr::_('Change phone'))->setOnclick("CashDesk.customer.phone.back();")->setClass('link')->setSize(UI_button::SIZE_SMALL)?>
		</div>
	</div>
<?php endif; ?>