<?php
namespace JetApplicationModule\Admin\Marketing\DeliveryFeeDiscount;

use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Marketing_DeliveryFeeDiscount;

/**
 * @var MVC_View $this
 * @var Marketing_DeliveryFeeDiscount $item
 */

$item = $this->getRaw('item');

if($item->isEditable()) {
	echo Admin_Managers::Image()->commonImageManager( $item::getEntityType(), $item->getId() );
}
