<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Marketing\DeliveryFeeDiscount;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Marketing_DeliveryFeeDiscount;

/**
 * @var MVC_View $this
 * @var Marketing_DeliveryFeeDiscount $item
 */

$item = $this->getRaw('item');

if($item->isEditable()) {
	echo Admin_Managers::Image()->commonImageManager( $item::getEntityType(), $item->getId() );
}
