<?php
namespace JetApplicationModule\Admin\WarehouseManagement\TransferBetweenWarehouses;

use Jet\Http_Request;
use Jet\Tr;

use Jet\MVC_View;
use Jet\Form;
use Jet\UI;
use Jet\UI_button;
use JetApplication\WarehouseManagement_ReceiptOfGoods;
use JetApplication\WarehouseManagement_TransferBetweenWarehouses;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var WarehouseManagement_ReceiptOfGoods  $item
 */

$item = $this->getRaw('item');

if($item->getStatus()==WarehouseManagement_TransferBetweenWarehouses::STATUS_PENDING) {
	
	echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
	echo UI::button(Tr::_('Done - sent'))->setUrl(Http_Request::currentURL(['action'=>'sent']))->setClass(UI_button::CLASS_SUCCESS);
	
	echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
	echo UI::button(Tr::_('Cancel'))->setUrl(Http_Request::currentURL(['action'=>'cancel']))->setClass(UI_button::CLASS_DANGER);

}

if($item->getStatus()==WarehouseManagement_TransferBetweenWarehouses::STATUS_SENT) {
	
	echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
	echo UI::button(Tr::_('Finished - received'))->setUrl(Http_Request::currentURL(['action'=>'received']))->setClass(UI_button::CLASS_SUCCESS);
	
	echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
	echo UI::button(Tr::_('Cancel'))->setUrl(Http_Request::currentURL(['action'=>'cancel']))->setClass(UI_button::CLASS_DANGER);
	
}