<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\WarehouseManagement\TransferBetweenWarehouses;


use Jet\MVC_View;
use Jet\Form;
use JetApplication\WarehouseManagement_TransferBetweenWarehouses;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var WarehouseManagement_TransferBetweenWarehouses  $item
 */

$item = $this->getRaw('item');

if($item->getIsNew()) {
	return;
}


echo Plugin::get( Plugin_SetStatus_Main::KEY )?->renderButton();
echo '&nbsp;&nbsp;&nbsp';
echo Plugin::get( Plugin_ForceStatus_Main::KEY )?->renderButton();
