<?php
namespace JetApplicationModule\Admin\ProductFilterManager;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Http_Request;
use Jet\MVC_View;
use JetApplication\Property;

/**
 * @var MVC_View   $this
 * @var Form $form
 * @var Property[] $properties
 */

$form = $this->getRaw('form');

$form->getField('/basic/kins_of_product')->input()->addJsAction('onchange', "$('#filter_form_properties').load('".Http_Request::currentURI()."&filter_kind_of_product_selected='+this.value);");

foreach($form->getFields() as $field):
	if(!str_starts_with($field->getName(), '/basic/')) {
		continue;
	}
	
	$field->label()->setWidth([
		Form_Renderer::LJ_SIZE_MEDIUM => 1
	]);
	
	echo $field;
endforeach;


