<?php
namespace JetApplicationModule\Admin\ProductFilterManager;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View   $this
 * @var Form $form
 */

$form = $this->getRaw('form');


$form->field('/categories/branch_mode')->label()->setWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 0,
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 0,
]);

$this->setVar('category_ids', $form->field('/categories/selected_categories')->getValue() );

?>
<script>
	const FilterEditCategories = {
		add: ( selected_item )=> {
			let input = $('#<?=$form->field('/categories/selected_categories')->getId()?>');
			let current = input.val();

			if(!current) {
				current = [];
			} else {
				current = current.split(',');
			}

			if(!current.includes( selected_item.object_id )) {
				current.push( selected_item.object_id );
			}
			
			current = current.join(',');

			input.val(current);

			$('#filter_selected_categories').load('<?=Http_Request::currentURI()?>&filter_categories_render_selected='+current);
			
		},
		
		remove: ( id ) => {
			let input = $('#<?=$form->field('/categories/selected_categories')->getId()?>');
			let current = input.val();

			if(!current) {
				current = [];
			} else {
				current = current.split(',');
			}


			let _new = [];

			for( let i=0;i<current.length;i++ ) {
				if(current[i]!=id) {
					_new.push(current[i]);
				}
			}

			_new = _new.join(',');

			input.val(_new);

			$('#filter_selected_categories').load('<?=Http_Request::currentURI()?>&filter_categories_render_selected='+_new);
		
		}
	};
</script>
	
	<div>
		<div style="padding: 5px;">
			<?=$form->field('/categories/selected_categories');?>
			<?=$form->field('/categories/branch_mode');?>
		</div>
		
		<?php if($this->getBool('editable')): ?>
		<div style="display: flex;align-items: center;">
			<div style="padding: 5px;"><?=Tr::_('Add category:')?></div>
			<div style="width: 400px"><?=Admin_Managers::Category()->renderSelectWidget(on_select: "FilterEditCategories.add(selected_item);")?></div>
		</div>
		<?php endif; ?>
		
	</div>
	
	<div style="height: 300px;overflow: auto;border: 1px solid #c9c9c9;padding: 10px; margin: 10px;" id="filter_selected_categories">
		<?php require 'categories/selected.phtml'; ?>
	</div>
