<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\ProductFilterManager;


use Jet\Form;
use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Property;

/**
 * @var MVC_View   $this
 * @var Form $form
 * @var Property[] $properties
 */

$form = $this->getRaw('form');
$properties = $this->getRaw('properties');

$property_manager = Admin_Managers::Property();

?>

<?php foreach($properties as $property): ?>
	<div>
		<h5><?=$property_manager->showName( $property->getId() )?></h5>
		<hr>
		<?php
		if($property->getType()==Property::PROPERTY_TYPE_OPTIONS):
			?>
			<div style="margin:10px;display: grid; grid-template-columns: 1fr 1fr 1fr 1fr;align-items: center">
				<?php
				foreach($form->getFields() as $field):
					if(!str_starts_with($field->getName(), '/property/'.$property->getId().'/')) {
						continue;
					}
					?><div class="<?=$field->getValue()?'bg-info':''?>" style="margin: 2px;padding: 2px;"><?=$field->input()?></div><?php
				endforeach;
				?>
			</div>
			<?php
		else:
			foreach($form->getFields() as $field):
				if(!str_starts_with($field->getName(), '/property/'.$property->getId().'/')) {
					continue;
				}
				
				echo $field;
			endforeach;
		endif;
		?>
	</div>
	<br>
<?php endforeach; ?>
