<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;

$cash_desk = CashDesk::get();

$form = $cash_desk->getSetPasswordForm();

$form->renderer()->addJsAction('onsubmit', "CashDesk.customer.registration.setPassword();return false;");

require 'email_and_phone_has_been_set.phtml';
?>


	<div class="step-title"><?=Tr::_('Now choose a password')?></div>

	<div>
		<?=$form->start()?>
			<?=$form->field('password')?>
			<?=$form->field('password_confirm')?>
			
			<div class="continue-button-area">
				<?=UI::button(Tr::_('Continue without registration'))->setClass('link')->setOnclick("$('#no_register_area').show(); $(this).hide(); return false;")?>
				<?=UI::button('Continue')->setClass('primary')->setType('submit')?>
			</div>
		<?=$form->end()?>

	</div>


	<div id="no_register_area" style="display: none;">
		<?=UI_messages::createInfo(Tr::_('<b>Warning! </b> If you place an order as an unregistered client, you will lose a loyalty discount.'))?>
		
		<div class="continue-button-area">
		<?=UI::button(Tr::_('Continue without registration'))->setClass('link')->setOnclick("CashDesk.customer.registration.doNotRegister();")?>
		</div>
	</div>

