<?php
namespace JetApplication;

use Jet\Tr;use Jet\UI;
use Jet\UI_button;
use Jet\UI_messages;

$cash_desk = CashDesk::get();

$form = $cash_desk->getSetPasswordForm();

$form->renderer()->addJsAction('onsubmit', "CashDesk.customer.registration.setPassword();return false;");
?>
<br/>
<div class="card">

	<div class="card-body bg-light">
		<div>
			<?=Tr::_('Your e-mail: <strong>%MAIL%</strong>', ['MAIL'=>$cash_desk->getEmailAddress()])?>
			<br>
			<?=UI::button(Tr::_('Change'))->setOnclick("CashDesk.customer.email.back();")->setClass('link')->setSize(UI_button::SIZE_SMALL)?>
		</div>
		<br>

		<h2 class="card-title"><?=Tr::_('Now choose a password')?></div>


		<div class="container-fluid bg-light">
			<div class="row">
				<div class="col-md-2 col-sm-0"></div>
				<div class="col-md-8 col-sm-12">

					<?=$form->start()?>
					<?=$form->field('password')?>

					<div class="text-right">
						<?=UI::button('Continue')->setClass('primary')->setType('submit')?>
					</div>
					<?=$form->end()?>

				</div>
				<div class="col-md-2 col-sm-0"></div>
			</div>
		</div>

		<div class="container-fluid bg-light">
			<br/>
			<div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-8 text-center">
					<?=UI::button(Tr::_('Continue without registration'))->setClass('link')->setOnclick("$('#no_register_area').show(); $(this).hide(); return false;")?>

					<div id="no_register_area" style="display: none;">
						<?=UI_messages::createInfo(Tr::_('<b>Warning! </b> If you place an order as an unregistered client, you will lose a loyalty discount.'))?>

						<?=UI::button(Tr::_('Continue without registration'))->setClass('link')->setOnclick("CashDesk.customer.registration.doNotRegister();")?>
					</div>

				</div>
				<div class="col-md-2"></div>
			</div>
			<br/>
		</div>

	</div>

</div>

