<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Mvc_View;
use JetShop\Category_ShopData;
use JetShop\Shops;

/**
 * @var Mvc_View   $this
 */

$category = Controller_Main::getCurrentCategory();

$image_classes = Category_ShopData::getImageClasses();

echo $this->render('lj_start');;

foreach(Shops::getList() as $shop):
	$shop_code = $shop->getCode();

	echo $category->getShopData( $shop_code )->renderImageWidgets( $image_classes );
endforeach;
echo $this->render('lj_end');