<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\MVC_View;
use JetShop\Category_ShopData;
use JetShop\Shops;

/**
 * @var MVC_View   $this
 */

$category = Controller_Main::getCurrentCategory();

$image_classes = Category_ShopData::getImageClasses();

echo $this->render('lj_start');

foreach(Shops::getList() as $shop):
	echo $category->getShopData( $shop )->renderImageWidgets( $image_classes, !$category->getEditForm()->getIsReadonly() );
endforeach;
echo $this->render('lj_end');