<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\Http_Request;
?>
<script>
	let NoteHandler = {
		showDialog: function() {
			$('#new-note-dialog').modal('show');
		},

		upload: function() {
			JetAjaxForm.submit('upload_note_files_form');
		},

		deleteImage: function( node )
		{
			$('#note-uploaded-files').load( node.href );
		},

		addInternalNote: function()
		{
			JetAjaxForm.submit('internal_note_form');
			$('#new-note-dialog').modal('hide');
		},

		addCustomerMessage: function()
		{
			JetAjaxForm.submit('customer_message_form');
			$('#new-note-dialog').modal('hide');
		},

		generateMessage: function( generator_key )
		{
			$.get(
				'<?=Http_Request::currentURI()?>&generate_message='+generator_key,
				function( data, status ) {
					$('#customer_message_form__email_subject').val( data['subject'] );
					$('#customer_message_form__new_note_text').val( data['text'] );

				},
				'json'
			);

		}
		
	}
</script>
