<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\NoteManager;


use Jet\Http_Request;
use Jet\Locale;
use Jet\Mvc_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Order_Note;

/**
 * @var Mvc_View $this
 * @var Order_Note $new_note
 */

$new_note = $this->getRaw('new_note');
?>
<div class="card">
	<div class="card-body">
		<h5 class="card-title"><?=Tr::_('Attach files')?></h5>
		<form action="<?=Http_Request::currentURI(['note-action'=>'upload_note_files'])?>" method="post" enctype="multipart/form-data" id="upload_note_files_form">
			<input type="file" name="files[]" multiple value="<?=Tr::_('Select and upload files')?>" onchange="NoteHandler.upload()">
		</form>
		<br>
		<?php if(($files=$new_note->getUploadedFiles())): ?>
			<table class="table table-striped">
				<thead>
				<tr>
					<th style="width: 20px;"></th>
					<th style="width: 120px;"></th>
					<th></th>
				</tr>
				</thead>
				<?php foreach($files as $f):
					$download_URL = Http_Request::currentURI(['note-action'=>'show_note_tmp_file', 'file'=>$f->getName()]);
					$delete_URL = Http_Request::currentURI(['note-action'=>'delete_note_uploaded_file', 'file'=>$f->getName()]);
					?>
					<tr>
						<td>
							<a href="<?=$delete_URL?>" class="btn btn-danger" onclick="NoteHandler.deleteImage(this);return false;"><?=UI::icon('trash')?></a>
						</td>
						<td>
							<?php if( $f->isImage() ): ?>
								<img src="<?=$download_URL?>" style="max-width: 100px;height: auto">
							<?php endif; ?>
						</td>
						<td>
							<a href="<?=$download_URL?>" target="_blank"><?=$f->getName()?></a><br>
							<?=$f->getMime()?><br>
							<?=Locale::size( $f->getSize() )?>
						</td>
					</tr>
				<?php endforeach; ?>
			</table>
		<?php endif; ?>
		
	</div>
</div>

