<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\Form;
use Jet\Http_Request;
use Jet\Tr;
use JetApplication\Delivery_Method;
use JetApplication\Delivery_Method_Price;
use JetApplication\Admin_Managers;


/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Delivery_Method $item
 */

$item = $this->getRaw('item');
$form = $this->getRaw('form');


$form->field( 'carrier_code' )->input()->addJsAction('onchange', 'reloadCarrierServices(this.options[this.selectedIndex].value);');
$form->field( 'delivery_classes' )->input()->addCustomCssStyle('height: 300px');
$form->field( 'payment_methods' )->input()->addCustomCssStyle('height: 300px');

?>
<!--suppress JSCheckFunctionSignatures, JSUnresolvedReference -->
<script>
	async function reloadCarrierServices( carrier ) {
		const set = ( field_id, options ) => {
			const select = document.getElementById( field_id );

			while (select.options.length > 0) {
				select.remove(0);
			}
			for( let opt in options ) {
				const option = new Option(options[opt], opt);
				select.add( option );
			}
		};
		
		const _services = await fetch('<?=Http_Request::currentURI(['action' =>'get_carrier_services'])?>&carrier='+encodeURIComponent(carrier));
		const services = await _services.json();
		const _dp_types = await fetch('<?=Http_Request::currentURI(['action' =>'get_carrier_dp_types'])?>&carrier='+encodeURIComponent(carrier));
		const dp_types = await _dp_types.json();

		set( '<?=$form->field('carrier_service_code')->getId()?>', services );
		set( '<?=$form->field('allowed_delivery_point_types')->getId()?>', dp_types );
	}
	
</script>

<?=$form->field( 'kind' )?>
<?=$form->field( 'delivery_classes' )?>
<?=$form->field( 'carrier_code' )?>
<?=$form->field( 'carrier_service_code')?>
<?=$form->field( 'allowed_delivery_point_types')?>
<?=$form->field( 'payment_methods' )?>
<?=$form->field( 'discount_is_not_allowed')?>
<?=$form->field( 'free_delivery_limit')?>
<?=$form->field( 'priority')?>

<div class="form-group row">
	<label class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?=Tr::_('Price:')?></label>
	<div class="col-md-8">
		<div style="display: grid; grid-template-columns: repeat(auto-fit, 300px); gap: 20px;">
			<?php foreach( $item->getEshop()->getPricelists() as $pricelist):
				$price = Delivery_Method_Price::get( $pricelist, $item->getId() );
				
				echo Admin_Managers::PriceFormatter()->showPriceInfo( $price );
			endforeach; ?>
		</div>
	</div>
</div>
<br><br>



<?=$form->field( 'length_of_delivery_in_working_days')?>
<?=$form->field( 'title')?>
<?=$form->field( 'description')?>
<?=$form->field( 'description_short')?>
<?=$form->field( 'confirmation_email_info_text')?>
<?=$form->field( 'order_final_page_info_text')?>



