<?php
use Jet\MVC_View;
use Jet\Form;
use Jet\Http_Request;
use Jet\Tr;
use JetApplication\Delivery_Method;
use JetApplication\Delivery_Method_Price;
use JetApplication\EShops;
use JetApplication\Pricelists;
use JetApplication\Admin_Managers;


/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Delivery_Method $item
 */

$item = $this->getRaw('item');
$form = $this->getRaw('form');
$form->field( 'carrier_code' )->input()->addJsAction('onchange', 'reloadCarrierServices(this.options[this.selectedIndex].value);');
?>
<!--suppress JSCheckFunctionSignatures -->
<script>
	async function reloadCarrierServices( carrier ) {
		const set = ( field_id, options ) => {
			const select = document.getElementById( field_id );

			while (select.options.length > 0) {
				select.remove(0);
			}
			for( let opt in options ) {
				const option = new Option(options[opt], opt);
				select.add( option );
			}
		};
		
		const _services = await fetch('<?=Http_Request::currentURI(['action' =>'get_carrier_services'])?>&carrier='+encodeURIComponent(carrier));
		const services = await _services.json();
		const _dp_types = await fetch('<?=Http_Request::currentURI(['action' =>'get_carrier_dp_types'])?>&carrier='+encodeURIComponent(carrier));
		const dp_types = await _dp_types.json();
		
		
		<?php foreach(EShops::getList() as $eshop): ?>
		set( '<?=$form->field('/eshop_data/'.$eshop->getKey().'/carrier_service_code')->getId()?>', services );
		set( '<?=$form->field('/eshop_data/'.$eshop->getKey().'/allowed_delivery_point_types')->getId()?>', dp_types );
		<?php endforeach; ?>

	}
</script>

<?=$form->field( 'kind' )?>
<?=$form->field( 'delivery_classes' )?>
<?=$form->field( 'carrier_code' )?>
<?=$form->field( 'payment_methods' )?>

<div class="form-group row">
	<label class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?=Tr::_('Price:')?></label>
	<div class="col-md-8">
		<div style="display: grid; grid-template-columns: repeat(auto-fit, 300px); gap: 20px;">
		<?php foreach( Pricelists::getList() as $pricelist):
			$price = Delivery_Method_Price::get( $pricelist, $item->getId() );
			
			echo Admin_Managers::PriceFormatter()->showPriceInfo( $price );
		endforeach; ?>
		</div>
	</div>
</div>
<br><br>

