<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ControlCentreModule\Pages;


use Jet\Form;
use Jet\Form_Renderer;
use Jet\Http_Request;
use Jet\Locale;
use Jet\MVC_Base_Interface;
use Jet\MVC_Page_Interface;use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;

/**
 * @var MVC_View   $this
 * @var MVC_Base_Interface[] $bases
 * @var MVC_Base_Interface $selected_base
 * @var MVC_Page_Interface $selected_page
 * @var Locale $selected_locale
 * @var Form $edit_form
 */

$bases = $this->getRaw('bases');
$selected_base = $this->getRaw('selected_base');
$selected_locale = $this->getRaw('selected_locale');
$selected_page = $this->getRaw('selected_page');

$edit_form = $this->getRaw('edit_form');

$edit_form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 3
]);
$edit_form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 9
]);

?>
<div style="display: grid;grid-template-columns: 1fr 3fr;gap: 10px">
	<div>
		<?php
		require 'pages_tree.phtml';
		?>
	</div>
	<div>
		<?php
		foreach( UI_messages::get(context: 'CC') as $message ):
			echo $message;
		endforeach;
		
		echo UI::button('Show the page')->setUrl($selected_page->getURL())->setCustomTagAttribute('target', '_blank')->setIcon('eye');
		
		?>
		<?=$edit_form->start()?>
		<?=$edit_form->field('is_active')?>
		<?=$edit_form->field('title')?>
		<?=$edit_form->field('menu_title')?>
		<?=$edit_form->field('breadcrumb_title')?>
		<?=$edit_form->field('icon')?>
		<?=$edit_form->field('order')?>
		<?=$edit_form->field('layout_script_name')?>
		<?php if($edit_form->fieldExists('relative_path_fragment')):
				$field = $edit_form->field( 'relative_path_fragment' );
				
				$parent = $selected_page->getParent();
				if( $parent ) {
					$parent_URL = $parent->getURL();
				} else {
					$parent_URL = $selected_page->getBase()->getHomepage( $selected_page->getLocale() )->getURL();
				}
				?>
				<?= $field->row()->start() ?>
				<?= $field->label() ?>
				
				<?= $field->container()->start() ?>
				<div class="input-group">
					<span class="input-group-prepend" style="font-weight: bolder"><span
								class="input-group-text"><?= rtrim( $parent_URL, '/' ) ?>/</span></span>
					<?= $field->input() ?>
					<?= $field->error() ?>
				</div>
				<?= $field->container()->end() ?>
				
				<?= $field->row()->end();
				
		endif; ?>
		
		
		<?php
		
		$indexes = array_keys( $selected_page->getContent() );
		$indexes[] = 'new';
		
		foreach($indexes as $i):
			$prefix = '/content/'.$i.'/';
			?>
		<div class="card" style="margin: 10px">
			<div class="card-body">
			<?php
			if($i=='new'):
				?><h4><?=Tr::_('Add content')?></h4><?php
			else:
				echo UI::button_delete(Tr::_('Delete content'))->setUrl( Http_Request::currentURI(['delete_content'=>$i]) );
			endif;
			
			echo $edit_form->field($prefix.'module_name');
			echo $edit_form->field($prefix.'controller_name');
			echo $edit_form->field($prefix.'controller_action');
			echo $edit_form->field($prefix.'output_position');
			echo $edit_form->field($prefix.'output_position_order');
			?>
			</div>
		</div>
		<?php endforeach; ?>
		
		<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-9">
				<?=UI::button_save()?>
			</div>
		</div>
		<?=$edit_form->end()?>
	</div>
</div>