<?php
namespace JetApplicationModule\Admin\Orders;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Admin_Managers;


/**
 * @var MVC_View $this
 * @var Listing_Filter_DatePurchased $filter
 */

$filter = $this->getRaw('filter');
$listing = $filter->getListing();
$filter_form = $listing->getFilterForm();

$purchased_from = $filter_form->field( 'purchased_from' );
$purchased_till = $filter_form->field( 'purchased_till' );

echo Admin_Managers::EntityListing()->renderListingFilter(
	filter:      $filter,
	title:       Tr::_('Purchased'),
	form_fields: [$purchased_from, $purchased_till],
	is_active:   $filter->getFrom() || $filter->getTill(),
	renderer:    function() use ($purchased_from, $purchased_till) {
		?>
		<div><?=Tr::_('From:')?></div>
		<div><?= $purchased_from->input() ?></div>
		<div><?=Tr::_('Till:')?></div>
		<div><?= $purchased_till->input() ?></div>
		
		<div><?=UI::button(Tr::_('Set'))->setType(UI_button::TYPE_SUBMIT)?></div>
		<?php
	}
);