<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Analytics\Service\JetAnalytics;

use Jet\MVC_View;
use Jet\UI_dataGrid;

/**
 * @var MVC_View $this
 * @var Main $module
 * @var Report $report
 * @var UI_dataGrid $grid
 */

$module = $this->getRaw('module');
$report = $this->getRaw('report');
$eshop = $this->getRaw('eshop');
$grid = $this->getRaw( 'grid' );


echo $module->renderSelectOneEShop();
echo $grid;