<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\Tr;
use Jet\MVC_View;
use JetApplication\EShops;
use JetApplication\Product;

/**
 * @var MVC_View   $this
 * @var Product    $product
 */

$product = $this->getRaw('product');


if($product->isActive()):
	?><span class="badge badge-success"> <?=Tr::_('Active')?> </span> <?php
else:
	?><span class="badge badge-danger"><?=Tr::_('Inactive')?></span> <?php
endif;

foreach( EShops::getListSorted() as $eshop):
	if($product->getEshopData($eshop)->isActive()):
		?><span class="badge badge-success"><?=$eshop->getName()?></span> <?php
	else:
		?><span class="badge badge-danger"><?=$eshop->getName()?></span> <?php
	endif;
endforeach;
