<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;
use Jet\Http_Request;
use JetApplication\Admin_Managers;
use JetApplication\Shops_Shop;

/**
 * @var MVC_View   $this
 * @var Form       $form
 * @var Product    $product
 */
$product = $this->getRaw( 'product' );

$form = $product->getAddForm();

$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 8 ] );



?>


<?=$form->start()?>

<div class="toolbar" id="main-toolbar">
	<?=UI::button_goBack()->setUrl(Http_Request::currentURI([], ['action']))?>

	<?=UI::button_save()?>
</div>

<div id="main-col">


		<?=$form->field('ean')?>
		<?=$form->field('internal_code')?>
		<?=$form->field('brand_id')?>
		<?=$form->field('supplier_id')?>
		
		<?php
		Admin_Managers::EntityEdit_WithShopData()->renderShopDataBlocks(
			form: $form,
			renderer: function( Shops_Shop $shop, string $shop_key ) use ($product, $form) : void {
				?>
				<fieldset>
					<legend class="sub"><?=Tr::_('Main data')?></legend>
					
					<?=$form->field('/shop_data/'.$shop_key.'/name')?>
					<?=$form->field('/shop_data/'.$shop_key.'/description')?>
					<?=$form->field('/shop_data/'.$shop_key.'/short_description')?>
				</fieldset>
				
				<fieldset>
					<legend class="sub"><?=Tr::_('SEO')?></legend>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_title')?>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_description')?>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_keywords')?>
				</fieldset>
				
			<?php }); ?>
</div>

<?=$form->end()?>
