<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\Mvc;
use Jet\Mvc_View;
use Jet\Form;
use Jet\Tr;
use Jet\UI;
use Jet\Http_Request;
use JetShop\Product;
use JetShop\Product_ShopData;
use JetShop\Shops;
use JetShopAdmin\Shop_Admin;

/**
 * @var Mvc_View   $this
 * @var Form       $form
 * @var Product    $product
 */
$product = $this->getRaw( 'product' );

$form = $product->getAddForm();

$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 8 ] );



?>



<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()->setUrl( Mvc::getCurrentPage()->getURI([], Http_Request::GET()->getRawData()) )?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()->setOnclick("$('#".$form->getId()."').submit();")?>
		<?php endif; ?>

		<?=$this->render('edit/preview_button');?>
	</div>
</div>

<div class="row">

	<div class="col-md-12" id="main-col">

		<?=$form->start()?>

		<?=$form->field('is_active')?>
		<?=$form->field('ean')?>
		<?=$form->field('internal_code')?>
		<?=$form->field('brand_id')?>
		<?=$form->field('supplier_id')?>
		<?=$form->field('stock_status')?>

		<?php foreach(Shops::getList() as $shop):
			$shop_id = $shop->getId();

			$shop_data = $product->getShopData( $shop_id );
			?>
			<?=$shop_data->renderShopDataBlock_start()?>

			<fieldset>
				<legend class="sub"><?=Tr::_('Main data')?></legend>

				<?=$form->field('/shop_data/'.$shop_id.'/is_active')?>

				<?=$form->field('/shop_data/'.$shop_id.'/name')?>
				<?=$form->field('/shop_data/'.$shop_id.'/variant_name')?>
				<?=$form->field('/shop_data/'.$shop_id.'/description')?>
				<?=$form->field('/shop_data/'.$shop_id.'/short_description')?>
			</fieldset>

			<fieldset>
				<legend class="sub"><?=Tr::_('SEO')?></legend>
				<?=$form->field('/shop_data/'.$shop_id.'/seo_h1')?>
				<?=$form->field('/shop_data/'.$shop_id.'/seo_title')?>
				<?=$form->field('/shop_data/'.$shop_id.'/seo_description')?>
				<?=$form->field('/shop_data/'.$shop_id.'/seo_keywords')?>
				<?=$form->field('/shop_data/'.$shop_id.'/internal_fulltext_keywords')?>
			</fieldset>

			<fieldset>
				<legend class="sub"><?=Tr::_('Price')?></legend>

				<?=$form->field('/shop_data/'.$shop_id.'/vat_rate')?>
				<?=$form->field('/shop_data/'.$shop_id.'/standard_price')?>
				<?=$form->field('/shop_data/'.$shop_id.'/action_price')?>
				<?=$form->field('/shop_data/'.$shop_id.'/action_price_valid_from')?>
				<?=$form->field('/shop_data/'.$shop_id.'/action_price_valid_till')?>
				<?=$form->field('/shop_data/'.$shop_id.'/sale_price')?>
				<?=$form->field('/shop_data/'.$shop_id.'/reset_sale_after_sold_out')?>
				<?=$form->field('/shop_data/'.$shop_id.'/deactivate_product_after_sold_out')?>
			</fieldset>
			<fieldset>
				<legend class="sub"><?=Tr::_('Availability')?></legend>

				<?=$form->field('/shop_data/'.$shop_id.'/delivery_term_id')?>
				<?=$form->field('/shop_data/'.$shop_id.'/date_available')?>
				<?=$form->field('/shop_data/'.$shop_id.'/stock_status')?>
			</fieldset>



			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach; ?>
		<?=$form->end()?>


	</div>
</div>

