<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\Http_Request;
use Jet\Tr;
use Jet\UI;

$types = [
	Product::PRODUCT_TYPE_REGULAR         => Tr::_('Regular'),
	Product::PRODUCT_TYPE_VARIANT_MASTER  => Tr::_('With variants'),
	Product::PRODUCT_TYPE_SET             => Tr::_('Set'),
];
?>
<div class="dropdown">
	<button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		<?= UI::icon( 'plus' ) ?> <?= Tr::_( 'Create' ) ?>
	</button>
	<div class="dropdown-menu" style="padding: 10px;">
		<?php foreach($types as $type=>$label): ?>
			<a class="dropdown-item" href="<?=Http_Request::currentURI(['action'=>'add', 'type'=>$type], ['id', 'option_id', 'page'])?>" ><?=$label?></a>
		<?php endforeach; ?>
	</div>
</div>