<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\Http_Request;
use Jet\Tr;
use Jet\UI;
use JetApplication\Product;

$types = [
	Product::PRODUCT_TYPE_REGULAR        => Product::getProductTypes()[Product::PRODUCT_TYPE_REGULAR ],
	Product::PRODUCT_TYPE_VARIANT_MASTER => Product::getProductTypes()[Product::PRODUCT_TYPE_VARIANT_MASTER ],
	Product::PRODUCT_TYPE_SET            => Product::getProductTypes()[Product::PRODUCT_TYPE_SET ],
];
?>
<div class="dropdown">
	<button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		<?= UI::icon( 'plus' ) ?> <?= Tr::_( 'Create' ) ?>
	</button>
	<div class="dropdown-menu" style="padding: 10px;">
		<?php foreach($types as $type=>$label): ?>
			<a class="dropdown-item" href="<?=Http_Request::currentURI(['action'=>'add', 'type'=>$type], ['id', 'option_id', 'page'])?>" ><?=$label?></a>
		<?php endforeach; ?>
	</div>
</div>