<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\Http_Request;
use JetShop\Product;

use Jet\UI;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View   $this
 * @var Product    $product
 */
$product = $this->getRaw( 'product' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( 'Do you really want to delete this product?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $product->getId() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$product->getInternalName();?></a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>