<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\Mvc;
use Jet\Mvc_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;
use Jet\UI_tabs;
use JetShop\Product;

/**
 * @var Mvc_View   $this
 * @var UI_tabs    $tabs
 */

$tabs = $this->getRaw('tabs');

$product = Controller_Main::getCurrentProduct();

if($product->getType()==Product::PRODUCT_TYPE_VARIANT):
	$master = Product::get($product->getVariantMasterProductId());

	if($master) {
		echo UI_messages::createWarning( Tr::_('Is variant of %MASTER%', [
			'MASTER' => '<a href="'.$master->getEditURL().'"><b>'.$master->getInternalName().'</b></a>'
		]) );
	} else {
		echo UI_messages::createDanger( Tr::_('Is variant of unknown product!', [
			'MASTER' => '<a href=""></a>'
		]) );

	}
endif;

echo $tabs;

echo $this->render('edit/'.$tabs->getSelectedTabId());

