<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\MVC_View;

/**
 * @var MVC_View     $this
 * @var Listing      $listing
 */
$listing = $this->getRaw('listing');
?>

<div class="row toolbar" id="main-toolbar">
	<div class="container-fluid">
		<?php require 'list/header.phtml'; ?>
	</div>
</div>


<div class="row" id="main-col">
	<div class="col-md-12">
		<?php require 'list/grid.phtml'; ?>
	</div>
</div>
