<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\MVC_View;

/**
 * @var MVC_View     $this
 */
?>

<?php if(Main::getCategoryMode()==Main::CATEGORY_MODE_TREE): ?>
<div class="row">
	<div class="col-md-2 tree">
		<?php require 'listing/cat_tree.phtml'; ?>
	</div>
	<div class="col-md-10">
		<div class="row toolbar" id="main-toolbar">
			<div class="container-fluid">
				<?php require 'listing/filter.phtml'; ?>
			</div>
		</div>


		<div class="row" id="main-col">
			<div class="col-md-12">
				<?php require 'listing/grid.phtml'; ?>
			</div>
		</div>
	</div>
</div>


<?php endif; ?>

<?php if(Main::getCategoryMode()==Main::CATEGORY_MODE_MULTIPLE): ?>
	<div class="row toolbar" id="main-toolbar">
		<div class="container-fluid">
			<?php require 'listing/filter.phtml'; ?>
		</div>
	</div>


	<div class="row" id="main-col">
		<div class="col-md-12">
			<?php require 'listing/grid.phtml'; ?>
		</div>
	</div>
<?php endif; ?>


