<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\Form;
use Jet\UI_messages;
use JetShop\Category;
use JetShop\Product;
use JetShop\Shops;

use Jet\UI_dataGrid;
use Jet\UI;
use Jet\UI_button;

use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Form         $filter_form
 * @var Listing      $listing
 */
$grid = $this->getRaw( 'grid' );
$router = $this->getController()->getControllerRouter();
$filter_form = $this->getRaw( 'filter_form' );
$listing = $this->getRaw('listing');

$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( Product $item ) use ( $router ) {

		$edit_uri = $item->getEditURL();
		//TODO: checkboxy a multiakce
		$delete_uri = '';

		if( $edit_uri ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;

	}
);
$c_edit->setCssStyle( 'width:180px;' );


$grid->getColumn( 'products_shop_data.name' )->setRenderer(
	function( Product $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getId() );
		?>
		<?=$item->renderActiveState()?>
		<a href="<?=$edit_uri;?>"><?=$item->getAdminTitle();?></a>

		<?php
		if($item->getType()==Product::PRODUCT_TYPE_VARIANT_MASTER) {
			?>
			<br>
			<table>
				<thead>
				<tr>
					<th colspan="2"><?=Tr::_('Variants')?></th>
				</tr>
				</thead>
				<?php foreach($item->getVariants() as $variant): ?>
					<tr>
						<td><?=$variant->renderActiveState() ?></td>
						<td><a href="<?=$variant->getEditURL()?>"><?=$variant->getAdminTitle()?></a></td>
					</tr>
				<?php endforeach; ?>
			</table>
			<?php
		}

		if( $item->getType()==Product::PRODUCT_TYPE_SET ) {
			?>
			<br>
			<table>
				<thead>
				<tr>
					<th colspan="2"><?=Tr::_('Set items')?></th>
				</tr>
				</thead>
				<?php foreach($item->getSetItems() as $set_item):
					$set_item_product = Product::get($set_item->getItemProductId());

					if(!$set_item_product) {
						?>
						<tr>
							<td></td>
							<td><?=UI_messages::createDanger(Tr::_('Unknown product %ID%', ['ID'=>$set_item->getItemProductId()]))->setCloseable(false)?></td>
						</tr>
						<?php
						continue;
					}

					?>
					<tr>
						<td><?=$set_item_product->renderActiveState()?></td>
						<td><a href="<?=$set_item_product->getEditURL()?>"><?=$set_item_product->getAdminTitle()?></a></td>
					</tr>
				<?php endforeach; ?>
			</table>
			<?php
		}

	}
);

$grid->getColumn( 'id' )->setCssStyle( 'width:120px;' );
$grid->getColumn( 'id' )->setRenderer(
	function( Product $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getId() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getId();?></a>
		<?php
	}
);



?>
<script>
	let productFilter = {
		addCategory: function( id )
		{
			let categories = document.getElementById('filter_form__categories');

			let new_value = '';
			if(categories.value.length) {
				new_value = categories.value.split(',');
				if(!new_value.includes(id)) {
					new_value.push(id);
				}

				new_value = new_value.join(',');

			} else {
				new_value = id;
			}

			categories.value = new_value;

			document.getElementById('filter_form').submit();
		},

		removeCategory: function( id )
		{
			let categories = document.getElementById('filter_form__categories');

			let new_value = '';
			if(categories.value.length) {
				new_value = categories.value.split(',');
				let _new_value = [];
				for(let i=0;i<new_value.length;i++) {
					if(new_value[i]!=id) {
						_new_value.push(new_value[i]);
					}
				}
				new_value = _new_value.join(',');
			}

			categories.value = new_value;

			document.getElementById('filter_form').submit();

		}
	};
</script>

<?=$filter_form->start()?>

<?=$filter_form->field('categories')?>
<div class="row toolbar" id="main-toolbar">
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-3" style="padding-bottom: 10px;">
				<?=UI::button_create('')->setUrl($router->getAction('add')->URI())->setClass('success')?>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-3">
				<table style="width: 100%">
					<tr>
						<td style="width: 50px;"><?=Tr::_('Category:')?></td>
						<td><?=Category::renderSelectCategoryWidget("productFilter.addCategory(selected_item.id)")?></td>
					</tr>
					<tr>
						<td></td>
						<td style="padding: 5px;">
							<?php foreach($listing->filter_categories_getSelected() as $c_id=>$category): ?>
								<?=UI::button(' '.$category->_getPathName())->setIcon('trash')->setClass('info')->setSize(UI_button::SIZE_EXTRA_SMALL)->setOnclick("productFilter.removeCategory({$c_id})")?>
							<?php endforeach; ?>
						</td>
					</tr>
				</table>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-3">
				<?=UI::searchField( 'search', $filter_form->field('search')->getValue() )?>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-3">
				<?php
				$filter_form->field('product_type')->input()->addJsAction('onchange', 'this.form.submit()');
				$filter_form->field('product_type')->label()->addCustomCssClass('text-right');
				?>
				<?=$filter_form->field('product_type')?>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12" style="padding-left: 100px;padding-top: 5px;padding-bottom: 5px;">
				<table class="badge badge-<?=match((string)$filter_form->field('is_active_general')->getValue()) {'0'=>'light', '-1'=>'danger', '1'=>'success' }?>">
					<tr>
						<td style="width: 150px;"><?=Tr::_('Is active - general')?></td>
						<td style="width: 100px;"><?=$filter_form->field('is_active_general')->input()->addJsAction('onchange', 'this.form.submit()')?></td>
					</tr>
				</table>
				<?php foreach(Shops::getList() as $code=>$shop): ?>
				<table class="badge badge-<?=match((string)$filter_form->field('is_active_'.$code)->getValue()) {'0'=>'light', '-1'=>'danger', '1'=>'success' }?>">
					<tr>
						<td style="width: 150px;"><?=Tr::_('Is active - '.$shop->getShopName())?></td>
						<td style="width: 100px;"><?=$filter_form->field('is_active_'.$code)->input()->addJsAction('onchange', 'this.form.submit()')?></td>
					</tr>
				</table>
				<?php endforeach; ?>
			</div>
		</div>

		<div class="row">
			<div class="col-xs-7 col-md-3">

			</div>
		</div>

	</div>
</div>
<?=$filter_form->end()?>


<div class="row" id="main-col">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
