<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Stats\Views;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\EShops;

/**
 * @var MVC_View   $this
 * @var Statistics $stat
 * @var Statistics[] $stats
 */

$stats = $this->getRaw('stats');
$stat = $this->getRaw('stat');
?>



<div class="card card-body shadow" style="margin: 20px;">
	<div style="display: grid;grid-template-columns: 150px 1fr;gap: 20px;margin: 10px;align-items: center">
		<div><?=Tr::_('E-Shop:')?></div>
		<div style="display: flex;gap: 10px;align-items: center;flex-wrap: wrap;">
			<?php foreach(EShops::getListSorted() as $eshop):
				
				if($stat->getEshop()->getKey()==$eshop->getKey()):
					?><div class="btn btn-success"><?=$eshop->getName()?></div><?php
				else:
					?><a href="<?=Http_Request::currentURI(['eshop'=>$eshop->getKey()])?>" class="btn btn-secondary"><?=$eshop->getName()?></a><?php
				endif;
			endforeach; ?>
		</div>

		<div><?=Tr::_('Statistic:')?></div>
		<div style="display: flex;gap: 10px;align-items: center;flex-wrap: wrap;">
			<?php foreach($stats as $key=>$s): ?>
				<?php if($s->getIsSelected()): ?>
					<strong style="margin-right: 20px;" class="btn btn-success"><?=$s->getTitle()?></strong>
				<?php else: ?>
					<a href="<?=Http_Request::currentURI([ 'stat' => $key ])?>" style="margin-right: 20px;" class="btn btn-secondary"><?=$s->getTitle()?></a>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>
	</div>

	<form method="get">
		<input type="hidden" name="eshop" value="<?=$stat->getEshop()->getKey()?>">
		<input type="hidden" name="stat" value="<?=$stat->getKey()?>">

		<div style="display: grid;grid-template-columns: 150px 1fr;gap: 20px;margin: 10px;align-items: center">

			<?php /*
			<div><?=Tr::_( 'Time period:' )?></div>
			<div style="display: flex;align-items: center;gap: 10px;">
				<div><?=Tr::_('From year:')?></div>
				<div>
					<input type="number" name="start_year" value="<?=$stat->getStartYear()?>" class="form-control" style="width: 100px"/>
				</div>
				<div><?=Tr::_('To year:')?></div>
				<div>
					<input type="number" name="end_year" value="<?=$stat->getEndYear()?>" class="form-control" style="width: 100px"/>
				</div>

			</div>

			<div><?=Tr::_( 'Show days:' )?></div>
			<div>
				<select name="display_days" class="form-control" style="width: 100px">
					<option value="0" <?=(!$stat->getDisplayDays()?' selected':'')?>><?=Tr::_('No')?></option>
					<option value="1" <?=($stat->getDisplayDays()?' selected':'')?>><?=Tr::_('Yes')?></option>
				</select>
			</div>

			<div></div>
			<div>
				<?=$stat->renderDetailFilterForm();?>
			</div>
			*/ ?>
			
			<?=$stat->setupForm()?>

			<div></div>
			<div>
				<?=UI::button(Tr::_('Setup statistic'))->setClass(UI_button::CLASS_PRIMARY)->setType(UI_button::TYPE_SUBMIT)?>
			</div>
		</div>


	</form>

</div>


<div style="padding-top: 50px">
	<?=$stat->output()?>
</div>

