<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\ReturnsOfGoods;


use Jet\Form;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

use Jet\MVC_View;
use JetApplication\ReturnOfGoods;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var ReturnOfGoods $return_of_goods
 */

$return_of_goods = $this->getRaw('return_of_goods');
if(!$return_of_goods->isEditable()) {
	return;
}
echo '&nbsp;';

echo UI::button(Tr::_('Done - rejected'))
	->setClass(UI_button::CLASS_DANGER)
	->setIcon('xmark')
	->setOnClick("$('#done_rejected_form_dialog').modal('show');");