<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\UI;
use JetApplication\EShop;

/**
 * @var MVC_View $this
 * @var EShop $eshop
 */

$eshop = $this->getRaw('eshop');
?>
<div>
<fieldset>
	<legend><?=UI::flag( $eshop->getLocale() )?> <?=$eshop->getName()?></legend>
