<?php
namespace JetApplicationModule\EShop\CashDesk;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');

?>

<script>
	CashDesk.delivery = {

		select: function( method ) {
			if(CashDesk.selected_delivery==method) {
				return;
			}
			CashDesk.selected_delivery=method;
			CashDesk._request.doGet('?action=select_delivery&method=' + method);
		},

		back: function() {
			CashDesk.slideUp('cash_desk_confirm', () => {
				CashDesk.slideUp('cash_desk_customer', () => {
					CashDesk.slideUp('cash_desk_payment', () => {
						CashDesk.slideUp('cash_desk_delivery', () => {
							CashDesk._request.doGet('?action=back_to_delivery', () => {
								CashDesk.slideDown('cash_desk_delivery', () => {
									CashDesk.scrollTo('cash_desk_delivery');
								});
							});
						});
					});
				});
			});
		},

		continue: function() {
			CashDesk.slideUp('cash_desk_delivery', () => {
				CashDesk._request.doGet('?action=continue_to_payment', () => {
					CashDesk.slideDown('cash_desk_delivery', () => {
						CashDesk.slideDown('cash_desk_payment', () => {
							CashDesk.scrollTo('cash_desk_payment');
						});
					});
				});

			});
		}
	};
</script>
