<?php
use Jet\MVC_View;
use JetApplication\Order;


/**
 * @var MVC_View $this
 * @var Order $order
 */

$id = $this->getString('id');
$order = $this->getRaw('order');


$items = [];

foreach ($order->getItems() as $item):
	if($item->isStdProduct()):
		$items[] = [
			'id' => $item->getId(),
			'price' => $item->getPricePerUnit(),
			'quantity' => $item->getNumberOfUnits(),
		];
	endif;
endforeach;
?>
<!-- Criteo -->
<script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="async"></script>
<script type="text/javascript">
	window.criteo_q = window.criteo_q || [];
	window.criteo_q.push(
		{ event: "setAccount", account: <?= $id ?> },
		{ event: "setEmail", email: "<?= $this->getString('email') ?>" },
		{ event: "setSiteType", type: (/iPad/.test(navigator.userAgent) ? "t" : (/Mobile|iP(hone|od)|Android|BlackBerry|IEMobile/.test(navigator.userAgent) ? "m" : "d")) },
		{ event: "trackTransaction", id: "<?= $order->getNumber() ?>", item: <?=json_encode($items)?> },
	);
</script>