<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\ProductReviews;


use Jet\Locale;use Jet\MVC_View;
use Jet\UI;
use JetApplication\ProductReview;

/**
 * @var MVC_View   $this
 * @var ProductReview $review
 */


$review = $this->getRaw('review');

$showStarts = function( int $rank ) {
	$stars = $rank / 20;
	
	$b_stars = 0;
	$w_stars = 5;
	$half_star = false;
	
	while($stars>=1) {
		$b_stars++;
		$w_stars--;
		$stars--;
	}
	
	if($stars>0.7) {
		$b_stars++;
		$w_stars--;
	}
	
	if($stars>0.3 && $stars<0.7) {
		$w_stars--;
		$half_star = true;
	}
	
	for($c=1;$c<=$b_stars;$c++):
		echo UI::icon('star-filled');
	endfor;
	
	if($half_star):
		echo UI::icon('star-half');
	endif;
	
	for($c=1;$c<=$w_stars;$c++):
		echo UI::icon('star-empty');
	endfor;
	
};

?>
	
	<div class="product-review">
		<div class="header">
			<div><?php $showStarts($review->getRank()); ?></div>
			<div><?=Locale::date($review->getCreated())?></div>
		</div>
		
		<div class="summary">
			<?=nl2br( $review->getSummary() )?>
		</div>
		
		<div class="pros-cons">
			<div>
				<?php
				if(trim($review->getPositiveCharacteristics()))
					foreach( explode("\n", $review->getPositiveCharacteristics()) as $item ):
						$item = trim($item);
						if(strlen($item)<3) {
							continue;
						}
						?>
						<div>
							<?=UI::icon('plus')?> <?=$item?>
						</div>
					<?php endforeach; ?>
			</div>
			<div>
				<?php
				if(trim($review->getNegativeCharacteristics()))
					foreach( explode("\n", $review->getNegativeCharacteristics()) as $item ):
						$item = trim($item);
						if(strlen($item)<3) {
							continue;
						}
						?>
						<div>
							<?=UI::icon('minus')?> <?=$item?>
						</div>
					<?php endforeach; ?>
			</div>
		</div>
	
	</div>

