<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Customer\CustomerSection;


use Jet\Form;
use Jet\Form_Renderer;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Customer_Address;
use JetApplication\Customer;

/**
 * @var MVC_View   $this
 * @var Customer_Address $current_address
 * @var Form $form
 */

$current_address = $this->getRaw('current_address');
$form = $this->getRaw('address_edit_form');
?>

<?=$this->getRaw('tabs')?>
<div class="customer-section-container">
<div class="customer_section_addresses">
<?php foreach(Customer::getCurrentCustomer()->getAddresses() as $address): ?>
<div class="card card-body<?=$address->getId()==$current_address?->getId()?' selected-address':''?>">
	<div class="customer_section_addresses_address">
		<div>
			<?php if( $address->getCompanyName() ): ?>
				<?=$address->getCompanyName()?><br>
				<?=$address->getCompanyId()?><br>
				<?=$address->getCompanyVatId()?><br>
			<?php endif?>
			
			<?=$address->getFirstName()?> <?=$address->getSurname()?><br>
			<?=$address->getAddressStreetNo()?><br/>
			<?=$address->getAddressZip()?> <?=$address->getAddressTown()?>
			
		</div>
		
		<div class="customer_section_addresses_address_buttons">
			<?php if($address->isDefault()): ?>
				<b><?=Tr::_('Default address')?></b>
				<a href="<?=Http_Request::currentURL(['edit'=>$address->getId()])?>"><div class="btn-content"><?=UI::icon('edit')?> <?=Tr::_('Edit')?></div></a>
			<?php else: ?>
				<a href="<?=Http_Request::currentURL(['set_default'=>$address->getId()])?>"><div class="btn-content"><?=UI::icon('check')?> <?=Tr::_('Set as default')?></div></a>
				<a href="<?=Http_Request::currentURL(['edit'=>$address->getId()])?>"><div class="btn-content"><?=UI::icon('edit')?><?=Tr::_('Edit')?></div></a>
				<a href="<?=Http_Request::currentURL(['delete'=>$address->getId()])?>" onclick="return confirm('<?=Tr::_('Do you really want do delete address?')?>');"><div class="btn-content"><?=UI::icon('trash')?> <?=Tr::_('Delete')?></div></a>
			<?php endif; ?>
			
		</div>
		
	</div>
	
</div>
<?php endforeach; ?>
</div>

<?php if($current_address):
	$form->renderer()->setDefaultLabelWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 3] );
	$form->renderer()->setDefaultFieldWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 9] );
	
	?>
<br>
<div class="card card-body customer_section_addresses_edit_form_dialog">
	<?=$form->start()?>
		<div class="customer_section_addresses_edit_form">
			<?=$form->field('company_name')?>
			<?=$form->field('company_id')?>
			<?=$form->field('company_vat_id')?>
			<?=$form->field('first_name')?>
			<?=$form->field('surname')?>
			<?=$form->field('address_street_no')?>
			<?=$form->field('address_town')?>
			<?=$form->field('address_zip')?>
			<div></div>
			<div><?=UI::button_save()?></div>
		</div>
	
	<?=$form->end()?>
</div>
<?php endif; ?>
</div>