<?php
namespace JetApplicationModule\EShop\Customer\CustomerSection;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\Form;
use JetApplication\Customer;

/**
 * @var MVC_View   $this
 * @var Form $form
 */

$customer = Customer::getCurrentCustomer();

$form = $this->getRaw('form');

echo $this->getRaw('tabs');
?>
<div class="customer-section-container">
<?php if($form):
	?>
	<div class="card card-body">
		<?=$form->start()?>
			<div class="customer_section_addresses_edit_form">
				<?=$form->field('first_name')?>
				<?=$form->field('surname')?>
				<?=$form->field('email')?>
				<?=$form->field('phone')?>
				
				<div></div>
				<div><?=UI::button_save()?></div>
			</div>
		<?=$form->end()?>
	</div>
	<?php
else:
	?>
	<div class="card card-body customer_section_basic_info">
		<div></div>
		<?=$customer->getName()?><br>
		<div><?=Tr::_('e-mail:')?></div>
		<?=$customer->getEmail()?><br>
		<div><?=Tr::_('Phone:')?></div>
		<?=$customer->getPhoneNumber()?>
		<div></div>
		<div>
			<a href="<?=Http_Request::currentURL(['edit'=>'basic-info'])?>"><?=UI::icon('edit')?> <?=Tr::_('Edit')?></a>
		</div>
	</div>
	<?php
endif;
?>
</div>