<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\Customer\CustomerSection;


use Jet\MVC_View;
use JetApplication\EShop_Managers;

/**
 * @var MVC_View   $this
 */
?>
<?=$this->getRaw('tabs');?>
<div class="customer-section-container">
<?=EShop_Managers::ProductReviews()->renderCustomerSectionReviews()?>
</div>
