<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\Http_Request;
use Jet\UI_messages;
use JetShop\Product;

use Jet\UI_dataGrid;

use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Listing      $listing
 */
$grid = $this->getRaw( 'grid' );
$listing = $this->getRaw('listing');

$editUrl = function( Product $item ) {
	return Http_Request::currentURI(['id'=>$item->getId()]);
};


$cols = [
	
	'_edit_' => [
		'renderer' => function( Product $item ) {
			?>
			<input type="checkbox" class="checkbox select_product" value="<?=$item->getId()?>" name="products[]"/>
			<?php
		},
		'style' => 'width:20px;'
	],
	
	'id' => [
		'renderer' => function( Product $item ) use ($editUrl) {
			?><a href="<?=$editUrl($item);?>"><?=$item->getId();?></a><?php
		},
		'style' => 'width:120px;'
	],
	
	
	
	'products_shop_data.name' => [
		'renderer' => function( Product $item ) use ($editUrl) {
			$edit_uri = $editUrl($item);
			?>
			<?=$item->renderActiveState()?>
			<a href="<?=$edit_uri;?>"><?=$item->getAdminTitle();?></a>
			
			<?php
			if($item->getType()==Product::PRODUCT_TYPE_VARIANT_MASTER) {
				?>
				<br>
				<table>
					<thead>
					<tr>
						<th colspan="2"><?=Tr::_('Variants')?></th>
					</tr>
					</thead>
					<?php foreach($item->getVariants() as $variant): ?>
						<tr>
							<td><?=$variant->renderActiveState() ?></td>
							<td><a href="<?=$variant->getEditURL()?>"><?=$variant->getAdminTitle()?></a></td>
						</tr>
					<?php endforeach; ?>
				</table>
				<?php
			}
			
			if( $item->getType()==Product::PRODUCT_TYPE_SET ) {
				?>
				<br>
				<table>
					<thead>
					<tr>
						<th colspan="2"><?=Tr::_('Set items')?></th>
					</tr>
					</thead>
					<?php foreach($item->getSetItems() as $set_item):
						$set_item_product = Product::get($set_item->getItemProductId());
						
						if(!$set_item_product) {
							?>
							<tr>
								<td></td>
								<td><?=UI_messages::createDanger(Tr::_('Unknown product %ID%', ['ID'=>$set_item->getItemProductId()]))->setCloseable(false)?></td>
							</tr>
							<?php
							continue;
						}
						
						?>
						<tr>
							<td><?=$set_item_product->renderActiveState()?></td>
							<td><a href="<?=$set_item_product->getEditURL()?>"><?=$set_item_product->getAdminTitle()?></a></td>
						</tr>
					<?php endforeach; ?>
				</table>
				<?php
			}
			
		}
	]
];




foreach($cols as $col_name=>$col_prop) {
	if(!$grid->hasColumn($col_name)) {
		continue;
	}
	
	$col = $grid->getColumn($col_name);
	$col->setRenderer($col_prop['renderer']);
	
	if(isset($col_prop['style'])) {
		$col->addCustomCssStyle($col_prop['style']);
	}
}

