<?php
namespace JetApplicationModule\Admin\Delivery\Deadlines;

use JetApplication\Delivery_Deadline;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use Jet\UI;

/**
 * @var MVC_View   $this
 * @var Form       $form
 * @var Delivery_Deadline    $delivery_deadline
 */
$form = $this->getRaw( 'form' );

$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 1 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );

?>



<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()->setOnclick("$('#".$form->getId()."').submit();")?>
		<?php endif; ?>
	</div>
</div>

<div class="row">

	<div class="col-md-12" id="main-col">

		<?=$form->start()?>
		<?=$form->field( 'internal_name' )?>
		<?=$form->field( 'code' )?>
		<?=$form->field( 'internal_description' )?>

		<?=$form->end()?>


	</div>
</div>

