<?php
namespace JetShopModule\Admin\Delivery\Deadlines;

use Jet\Http_Request;
use JetShop\Delivery_Deadline;

use Jet\UI;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View   $this
 * @var Delivery_Deadline    $delivery_deadline
 */
$delivery_deadline = $this->getRaw( 'delivery_deadline' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( 'Do you really want to delete this delivery deadline?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $delivery_deadline->getCode() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$delivery_deadline->getInternalName();?></a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>