<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;


/**
 * @var MVC_View $this
 * @var Listing_Filter_Categories $filter
 */

$filter = $this->getRaw('filter');
$listing = $filter->getListing();

if( $filter->getMode()==Listing_Filter_Categories::MODE_TREE ): ?>
	<?=UI::button(Tr::_('Switch to multiple mode'))->setIcon('list-check')->setUrl( $filter->getModeUrl( Listing_Filter_Categories::MODE_MULTIPLE ) )->setClass(UI_button::CLASS_LINK)?>
	<?php require 'categories/tree.phtml'; ?>
<?php
endif;
if( $filter->getMode()==Listing_Filter_Categories::MODE_MULTIPLE ): ?>
	<?=UI::button(Tr::_('Switch to tree mode'))->setIcon('folder-tree')->setUrl( $filter->getModeUrl( Listing_Filter_Categories::MODE_TREE ) )->setClass(UI_button::CLASS_LINK)?>
	<?php require 'categories/multiple.phtml'; ?>
<?php endif;