<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\Form_Renderer;
use Jet\MVC_View;


/**
 * @var MVC_View $this
 * @var Listing_Filter_ProductKind $filter
 */

$filter = $this->getRaw('filter');
$listing = $filter->getListing();
$filter_form = $listing->getFilterForm();

$field = $filter_form->field( 'product_kind' );

$field->input()->addJsAction( 'onchange', 'this.form.submit()' );
$field->label()->addCustomCssClass( 'text-right' );



$field->label()->setWidth([
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 3,
	Form_Renderer::LJ_SIZE_MEDIUM => 4,
	Form_Renderer::LJ_SIZE_LARGE => 4,
]);

$field->input()->setWidth([
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 8,
	Form_Renderer::LJ_SIZE_MEDIUM => 7,
	Form_Renderer::LJ_SIZE_LARGE => 8,

]);

?>
<?= $field ?>

