<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetShop\Category;


/**
 * @var MVC_View $this
 * @var Listing_Filter_Categories $filter
 */

$filter = $this->getRaw('filter');
$listing = $filter->getListing();
$filter_form = $listing->getFilterForm();

?>


<script>
	let productFilter = {
		addCategory: function( id )
		{
			let categories = document.getElementById('categories_filter_form__categories');

			let new_value = '';
			if(categories.value.length) {
				new_value = categories.value.split(',');
				if(!new_value.includes(id)) {
					new_value.push(id);
				}

				new_value = new_value.join(',');

			} else {
				new_value = id;
			}

			categories.value = new_value;

			document.getElementById('categories_filter_form').submit();
		},

		removeCategory: function( id )
		{
			let categories = document.getElementById('categories_filter_form__categories');

			let new_value = '';
			if(categories.value.length) {
				new_value = categories.value.split(',');
				let _new_value = [];
				for(let i=0;i<new_value.length;i++) {
					if(new_value[i]!=id) {
						_new_value.push(new_value[i]);
					}
				}
				new_value = _new_value.join(',');
			}

			categories.value = new_value;

			document.getElementById('categories_filter_form').submit();

		}
	};
</script>

<form method="get" id="categories_filter_form">
	<?php foreach(Http_Request::GET()->getRawData() as $key=>$val):
		if($key=='categories' || $key=='p') {
			continue;
		}
		?>
		<input type="hidden" name="<?=$key?>" value="<?=Http_Request::GET()->getString($key)?>"/>
	<?php endforeach; ?>
	<input type="hidden" name="categories" id="categories_filter_form__categories" value="<?=$filter->getSelectedCategoryIds( true )?>">
</form>

<div class="row">
	<div class="col-10" style="padding: 10px;">
		<?=Category::renderSelectCategoryWidget("productFilter.addCategory(selected_item.id)")?>
	</div>
</div>

<div class="row">
	<div class="col">

		<?php foreach( $filter->getSelectedCategories() as $c_id=> $category): ?>
			<div style="margin: 2px;">
				<?=UI::button(' '.$category->getPathName())->setIcon('trash')->setClass('info')->setSize(UI_button::SIZE_EXTRA_SMALL)->setOnclick("productFilter.removeCategory({$c_id})")?>
			</div>
		<?php endforeach; ?>
	</div>
</div>
