<?php
namespace JetShopModule\Admin\Catalog\Stencils;

use Jet\Form;
use JetShop\Stencil;

use Jet\UI_dataGrid;
use Jet\UI;
use Jet\UI_button;

use Jet\Tr;
use Jet\Mvc_View;

/**
 * @var Mvc_View        $this
 * @var UI_dataGrid     $grid
 * @var Form            $filter_form
 */
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );
$router = $this->getController()->getControllerRouter();


$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( Stencil $item ) use ( $router ) {
		if( ( $edit_uri = $router->action('edit')->URI( $item->getId() ) ) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;
		echo '&nbsp;';
		if( ( $delete_uri = $router->action('delete')->URI( $item->getId() ) ) ):
			echo UI::button_delete()->setUrl( $delete_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;

	}
);
$c_edit->setCssStyle( 'width:180px;' );


$grid->getColumn( 'name' )->setRenderer(
	function( Stencil $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getId() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getName();?></a>
		<?php
	}
);

$grid->getColumn( 'id' )->setCssStyle( 'width:120px;' );
$grid->getColumn( 'id' )->setRenderer(
	function( Stencil $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getId() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getId();?></a>
		<?php
	}
);



?>
<?=$filter_form->start()?>
<div class="row toolbar">
	<div class="col-xs-5 col-md-2">
		<?php if( ( $add_uri = $router->action('add')->URI() ) ): ?>
			<?=UI::button_create( Tr::_( 'Create a new Stencil' ) )->setUrl( $add_uri )?>
		<?php endif; ?>
	</div>
	<div class="col-xs-7 col-md-3">
		<?=UI::searchField( 'search', $filter_form->field('search')->getValue() )?>
	</div>
</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
