<?php
use Jet\MVC_Layout;
use Jet\MVC;

/**
 * @var MVC_Layout $this
 */

require 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html lang="<?=MVC::getLocale()->getLanguage()?>">
<head>
	<title><?=MVC::getBase()->getLocalizedData( MVC::getLocale() )->getTitle()?> : <?=MVC::getPage()->getTitle()?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="<?=MVC::getLocale()->getLanguage()?>" />

	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>

</head>
<body>
<div class="container-fluid">
	<div class="page-header card text-white bg-dark">
		<div class="card-body">
			<h1>JetShop!</h1>
			<small>JetShop Example</small>

			<div class="float-right">
				<div style="display: inline-block;"  id="customer_icon">
					<jet_module module="Shop.Login" action="customer_icon" is_cacheable="false" />
				</div>
			</div>

		</div>
	</div>

	<jet_module module="Shop.UI" action="breadcrumbNavigation" view="default" is_cacheable="true" />

	<jet_layout_main_position/>
</div>
</body>
</html>