<?php
namespace JetApplication;

use Jet\DataModel_Definition;
use JetShop\Core_MarketplaceIntegration_MarketplaceCategory_Parameter;

#[DataModel_Definition]
class MarketplaceIntegration_MarketplaceCategory_Parameter extends Core_MarketplaceIntegration_MarketplaceCategory_Parameter
{
}
