<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use JetApplication\Category_ShopData;

/**
 * @var MVC_View   $this
 * @var Category_ShopData $category
 */

$category = $this->getRaw('category');

$subcategories = $category->getChildren();
?>

<h1><?=$category->getName()?></h1>
<p><?=$category->getDescription()?></p>

<?php foreach($subcategories as $item): ?>
	<a href="<?=$item->getUrl()?>" style="font-size: 14px;font-weight: bolder"><?=$item->getName()?></a>
<?php endforeach; ?>

<?=$this->render('product_listing')?>