<?php
namespace JetApplication;

use Jet\MVC_View;

/**
 * @var MVC_View   $this
 * @var Category $category
 */

$category = $this->getRaw('category');

$subcategories = Category_Menu::getItems( $category->getId() );
?>
<h1><?=$category->getName()?></h1>
<p><?=$category->getDescription()?></p>

<?php foreach($subcategories as $item): ?>
	<a href="<?=$item->getUrl()?>" style="font-size: 14px;font-weight: bolder"><?=$item->getLabel()?></a>
	<br/>
	<?php foreach($item->getChildren() as $s_item): ?>
		<a href="<?=$s_item->getUrl()?>" style="font-size: 10px;"><?=$s_item->getLabel()?></a>
	<?php endforeach; ?>
	<br/>
<?php endforeach; ?>
