<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use JetApplication\Category_ShopData;

/**
 * @var MVC_View   $this
 * @var Category_ShopData $category
 */

$category = $this->getRaw('category');

?>
<h1><?=$category->getName()?></h1>
<p><?=$category->getDescription()?></p>

<?php foreach( $category->getChildren() as $item): ?>
	<a href="<?=$item->getUrl()?>" style="font-size: 14px;font-weight: bolder"><?=$item->getName()?></a>
	<br/>
	<?php foreach( $item->getChildren() as $s_item): ?>
		<a href="<?=$s_item->getUrl()?>" style="font-size: 10px;"><?=$s_item->getName()?></a>
	<?php endforeach; ?>
	<br/>
<?php endforeach; ?>
