<?php
namespace JetApplicationModule\Admin\Entity\Edit\WithEShopData;

use Jet\Locale;
use JetApplication\Admin_Entity_WithEShopData_Interface;
use JetApplication\Admin_Managers;
use JetApplication\Entity_WithEShopData;
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Entity_WithEShopData|Admin_Entity_WithEShopData_Interface     $item
 * @var Main $module
 */
$form = $this->getRaw( 'form' );
$item = $this->getRaw( 'item' );

$module = $this->getRaw('module');

$common_data_fields_renderer = $this->getRaw('common_data_fields_renderer');
$eshop_data_fields_renderer = $this->getRaw('eshop_data_fields_renderer');
$description_fields_renderer = $this->getRaw('description_fields_renderer');

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 3,
	Form_Renderer::LJ_SIZE_LARGE => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 8,
	Form_Renderer::LJ_SIZE_LARGE => 8
] );

?>

<?php require 'toolbar.phtml'; ?>


<div id="main-col">
		<?php
		echo $this->getRaw('tabs');
		
		echo '<br>';
		
		echo $module->renderEntityActivation(
					entity: $item,
					editable: !$form->getIsReadonly(),
				);
		
		if( !$module->getTimerDisabled()) {
			echo Admin_Managers::Timer()?->renderEntityEdit( $item, !$form->getIsReadonly() );
		}
		
		echo $form->start();
		
		echo $module->renderEntityFormCommonFields( $form );
		
		if($common_data_fields_renderer) {
			$common_data_fields_renderer( $item, $form );
		}
		
		if($eshop_data_fields_renderer) {
			echo $module->renderShopDataBlocks(
				form: $form,
				renderer: function( EShop $eshop, string $eshop_key ) use ($item, $form, $eshop_data_fields_renderer ) : void {
					$eshop_data = $item->getEshopData( $eshop );
					
					$eshop_data_fields_renderer( $eshop, $eshop_key, $item, $form );
				});
		}
		
		if($description_fields_renderer) {
			echo $module->renderDescriptionBlocks(
				form: $form,
				renderer: function( Locale $locale, string $locale_str ) use ($item, $form, $description_fields_renderer ) : void {
					$description_fields_renderer( $locale, $locale_str, $item, $form );
				});
			
		}
		
		echo $form->end();
		?>
</div>

<?=Admin_Managers::Timer()?->renderIntegration()?>