<?php
namespace JetApplication;

use Jet\MVC_Layout;
use Jet\MVC;

/**
 * @var MVC_Layout $this
 */

require 'init_libs.php';

$title = $this->getString('title');
if($title) {
	$title = MVC::getBase()->getLocalizedData( MVC::getLocale() )->getTitle().' : '.MVC::getPage()->getTitle();
}
?>
	<title><?=$title?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="<?=MVC::getLocale()->getLanguage()?>" />
	
	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>
	
	<?=Shop_Managers::Analytics()?->header()?>
