<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Complaints;


use Jet\MVC_View;
use JetApplication\Complaint;

/**
 * @var MVC_View $this
 * @var Complaint $complaint
 */
$complaint = $this->getRaw('complaint');

$status = $complaint->getStatus();
?>
<div class="complaint-status complaint-status-<?=$status?->getCode()?>">
	<div class="complaint-status-title"><?=$status?->getTitle()?></div>
</div>