<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Complaints;


use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Application_Service_Admin;
use JetApplication\Complaint;

/**
 * @var MVC_View $this
 * @var Complaint[]     $complaints
 */

$complaints = $this->getRaw( 'complaints' );
?>
<table class="table table-striped">
	<thead>
	<tr>
		<th><?=Tr::_('Number')?></th>
		<th><?=Tr::_('Product')?></th>
		<th><?=Tr::_('Date started')?></th>
		<th><?=Tr::_('Status')?></th>
	</tr>
	</thead>
	<?php foreach( $complaints as $complaint): ?>
	<tr>
		<td><a href="<?=$complaint->getEditUrl()?>"><?=$complaint->getNumber()?></a></td>
		<td>
			<?=Application_Service_Admin::Product()->renderItemName( $complaint->getProductId() )?>
		</td>
		<td>
			<?=Locale::dateAndTime( $complaint->getDateStarted() );?>
		</td>
		<td>
			<?=$complaint->getStatus()->showAdmin()?>
		</td>
	</tr>
	<?php endforeach; ?>
</table>

