<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Complaints;


use Jet\Http_Request;
use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Application_Service_Admin;
use JetApplication\Complaint;
use JetApplication\Product;

/**
 * @var MVC_View $this
 * @var Complaint     $complaint
 */

$complaint = $this->getRaw( 'complaint' );


$money_refunds = Application_Service_Admin::MoneyRefund()?->showMoneyRefunds( $complaint->getProvidesContext() );
$dispatch = Application_Service_Admin::OrderDispatch()?->showDispatches( $complaint->getProvidesContext() );
?>
<?php require 'edit/toolbar.phtml';?>


<div id="main-col">
	<div id="o_main" class="o_anchor"></div>
	<fieldset class="o_section">
		<?php require 'edit/main.phtml'; ?>
	</fieldset>


	<div id="o_product" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('Product')?></h5>

			<div style="display: flex;gap: 10px;align-items: center">
				<div>
					<?=Plugin::get( Plugin_ChangeProduct_Main::KEY )?->renderButton()?>
				</div>
				<?php if(($p=Product::get($complaint->getProductId()))): ?>
				<?=Application_Service_Admin::EntityEdit()->renderPreviewButton( $p )?>
				<?php endif; ?>
				<div>
					<?=Application_Service_Admin::Product()->renderItemName( $complaint->getProductId() )?>
				</div>
			</div>
		</div>
	</fieldset>

	<div id="o_description" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('Description of the problem')?></h5>

			<p><?=nl2br($complaint->getProblemDescription())?></p>
		</div>
	</fieldset>

	<div id="o_images" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('Images')?></h5>
			<div style="display: grid;grid-template-columns: 30px 100px 300px 200px 1fr;align-items: center;gap: 20px;margin: 20px;">
				<?php foreach( $complaint->getImages() as $img ):
					$thb = $img->getThbURL();
					?>
					<div>
						<?php if(Main::getCurrentUserCanEdit()):
							echo UI::button_delete(' ')->setUrl( Http_Request::currentURI(['delete_image'=>$img->getId()]) )->setOnClick("return confirm('".Tr::_('Are you sure you want to delete this image?')."')");
						endif; ?>
					</div>

					<div>
						<?php if($thb): ?>
						<a href="<?=$img->getURL()?>" target="_blank"><img src="<?=$img->getThbURL()?>" style="max-width: 100px; height: auto"></a>
						<?php endif; ?>
					</div>
					<div>
						<a href="<?=$img->getURL()?>" target="_blank"><?=$img->getName()?></a>
					</div>
					<div><?=Locale::size( $img->getSize() )?></div>
					<div></div>
				
				<?php endforeach; ?>
			</div>
		</div>
	</fieldset>



	<div id="o_url" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('URL')?></h5>
			<p><a href="<?=$complaint->getURL()?>" target="_blank"><?=$complaint->getURL()?></a></p>
		</div>
	</fieldset>

	<?php if($dispatch): ?>
	<div id="o_dispatch" class="o_anchor"></div>
	<fieldset class="o_section">
		<legend><?=UI::icon('boxes-packing')?> <?=Tr::_('Complaint dispatch')?></legend>
		<?=$dispatch?>
	</fieldset>
	<?php endif; ?>
	
	
	<?php if( $money_refunds ): ?>
	<div id="o_money_refund" class="o_anchor"></div>
	<?=$money_refunds?>
	<?php endif; ?>
	
	
	<div id="o_history" class="o_anchor"></div>
	<?=Application_Service_Admin::EntityEdit()->renderEventHistory( $complaint, true )?>
	
	<div id="o_sent_emails" class="o_anchor"></div>
	<?=Application_Service_Admin::EntityEdit()->renderSentEmails( $complaint, true )?>

	<br><br><br><br>
</div>

<?php
foreach( Plugin::getPlugins() as $handler):
	if($handler->hasDialog()) {
		echo $handler->renderDialog();
	}
endforeach;
?>
