<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Complaints;


use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Admin_Managers;
use JetApplication\Complaint;

/**
 * @var MVC_View $this
 * @var Complaint     $complaint
 */

$complaint = $this->getRaw( 'complaint' );


$money_refunds = Admin_Managers::MoneyRefund()?->showMoneyRefunds( $complaint->getProvidesContext() );
$dispatch = Admin_Managers::OrderDispatch()->showDispatches( $complaint->getProvidesContext() );
?>
<?php require 'edit/toolbar.phtml';?>


<div id="main-col">
	<div id="o_main" class="o_anchor"></div>
	<fieldset class="o_section">
		<?php require 'edit/main.phtml'; ?>
	</fieldset>


	<div id="o_product" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('Product')?></h5>
		
			<p><?=Admin_Managers::Product()->renderItemName( $complaint->getProductId() )?></p>
		</div>
	</fieldset>

	<div id="o_description" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('Description of the problem')?></h5>

			<p><?=nl2br($complaint->getProblemDescription())?></p>
		</div>
	</fieldset>

	<div id="o_images" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('Images')?></h5>
			<div style="display: grid;grid-template-columns: 100px 300px 200px 1fr;align-items: center;gap: 20px;margin: 20px;">
				<?php foreach( $complaint->getImages() as $img ):?>

					<div>
						<a href="<?=$img->getURL()?>" target="_blank"><img src="<?=$img->getThbURL()?>" style="max-width: 100px; height: auto"></a>
					</div>
					<div><?=$img->getName()?></div>
					<div><?=Locale::size( $img->getSize() )?></div>
					<div></div>
				
				<?php endforeach; ?>
			</div>
		</div>
	</fieldset>



	<div id="o_url" class="o_anchor"></div>
	<fieldset class="o_section">
		<div class="card card-body" style="margin: 10px;">
			<h5><?=Tr::_('URL')?></h5>
			<p><a href="<?=$complaint->getURL()?>" target="_blank"><?=$complaint->getURL()?></a></p>
		</div>
	</fieldset>

	<?php if($dispatch): ?>
	<div id="o_dispatch" class="o_anchor"></div>
	<fieldset class="o_section">
		<legend><?=UI::icon('boxes-packing')?> <?=Tr::_('Complaint dispatch')?></legend>
		<?=$dispatch?>
	</fieldset>
	<?php endif; ?>
	
	
	<?php if( $money_refunds ): ?>
	<div id="o_money_refund" class="o_anchor"></div>
	<?=$money_refunds?>
	<?php endif; ?>
	
	
	<div id="o_history" class="o_anchor"></div>
	<?=Admin_Managers::EntityEdit()->renderEventHistory( $complaint, true )?>
	
	<div id="o_sent_emails" class="o_anchor"></div>
	<?=Admin_Managers::EntityEdit()->renderSentEmails( $complaint, true )?>

	<br><br><br><br>
</div>

<?php
foreach( Plugin::getPlugins() as $handler):
	echo $handler->renderDialog();
endforeach;
?>
