<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Complaints;


use Jet\Tr;
use JetApplication\Admin_Managers;
use Jet\MVC_View;
use JetApplication\Complaint;

/**
 * @var MVC_View $this
 * @var Complaint[] $complaints
 */
$complaints = $this->getRaw('complaints');
?>

<h5><?=Tr::_('Complaint')?></h5>
<table>
	<?php foreach($complaints  as $complaint ): ?>
		<tr>
			<td><?=Admin_Managers::Complaint()->renderItemName( $complaint->getId() )?></td>
			<td><?=Admin_Managers::Complaint()->showComplaintStatus( $complaint )?></td>
		</tr>
	<?php endforeach; ?>
</table>
