<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\MoneyRefunds;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Admin_Managers;
use JetApplication\MoneyRefund;

/**
 * @var MVC_View $this
 * @var MoneyRefund     $money_refund
 */

$money_refund = $this->getRaw( 'money_refund' );


?>
<?php require 'edit/toolbar.phtml';?>


<div id="main-col">
	<div id="o_main" class="o_anchor"></div>
	<fieldset class="o_section">
		<?php require 'edit/main.phtml'; ?>
	</fieldset>

	<div class="card card-body" style="margin: 10px;">
		<div style="display: grid;grid-template-columns: auto 1fr;gap: 20px;font-size: 1.2rem">
			<div style="font-weight: bolder"><?=Tr::_('Amount to be refunded:')?></div>
			<div><b><?=Admin_Managers::PriceFormatter()->formatWithCurrency_WithVAT( $money_refund->getCurrency(), $money_refund->getAmountToBeRefunded() )?></b></div>
			<div style="font-weight: bolder"><?=Tr::_('Internal summary:')?></div>
			<div><?=nl2br($money_refund->getInternalSummary())?></div>
		</div>
	</div>
	<br><br><br><br>

	<div id="o_history" class="o_anchor"></div>
	<fieldset class="o_section">
		<legend><?=UI::icon('clock-rotate-left')?> <?=Tr::_('Money refund history')?></legend>
		<div id="money-refund-history">
			<?php require 'edit/history.phtml';?>
		</div>
	</fieldset>



	<div id="o_sent_emails" class="o_anchor"></div>
	<fieldset class="o_section">
		<legend><?=UI::icon('envelope-circle-check')?> <?=Tr::_('Sent e-mails')?></legend>

		<div id="sent-emails">
			<?php require 'edit/sent-emails.phtml'; ?>
		</div>
	</fieldset>

	<br><br><br><br>
</div>

<style>
	.o_section {
		padding: 10px;
		margin-bottom: 50px;
	}

	.o_anchor {
		position: relative;
		top: -80px;
	}
</style>

<?php
foreach(Handler::getHandlers() as $handler):
	echo $handler->renderDialog();
endforeach;
?>
