<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\MoneyRefunds;


use Jet\MVC_View;
use JetApplication\MoneyRefund;

/**
 * @var MVC_View $this
 * @var MoneyRefund $money_refund
 */
$money_refund = $this->getRaw('money_refund');

$status = $money_refund->getStatus();
?>
<div class="money-refund-status money-refund-status-<?=$status?->getCode()?>">
	<div class="money-refund-status-title"><?=$status?->getTitle()?></div>
</div>