<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\MoneyRefunds;


use Jet\Tr;
use Jet\UI;
use JetApplication\Application_Service_Admin;
use Jet\MVC_View;
use JetApplication\MoneyRefund;

/**
 * @var MVC_View $this
 * @var MoneyRefund[] $money_refunds
 */
$money_refunds = $this->getRaw('money_refunds');
?>
<fieldset class="o_section">
	<legend><?=UI::icon('money-bill-transfer')?> <?=Tr::_('Money refundation requests')?></legend>

	<table class="table table-striped">
		<thead>
		<tr>
			<th nowrap=""><?=Tr::_('Request number')?></th>
			<th nowrap=""><?=Tr::_('Request status')?></th>
			<th nowrap=""><?=Tr::_('Amount to be refunded')?></th>
			<th style="width: 100%"></th>
		</tr>
		</thead>
		<?php foreach( $money_refunds as $money_refund ): ?>
			<tr>
				<td nowrap=""><?=Application_Service_Admin::MoneyRefund()->renderItemName( $money_refund->getId() )?></td>
				<td nowrap=""><?=$money_refund->getStatus()->showAdmin()?></td>
				<td nowrap=""><?=Application_Service_Admin::PriceFormatter()->formatWithCurrency_WithVAT( $money_refund->getCurrency(), $money_refund->getAmountToBeRefunded() )?></td>
				<td></td>
			</tr>
		<?php endforeach; ?>
	</table>
</fieldset>
