<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Catalog;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Property_EShopData;

/**
 * @var MVC_View $this
 * @var Property_EShopData $property
 */

$property = $this->getRaw('property');

$value = $property->getProductDetailDisplayValue();

if($value):
	echo $property->getBoolYesDescription() ? : Tr::_('yes');
else:
	echo Tr::_('no');
endif;
