<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Content\InfoPages;


use Jet\MVC_View;
use JetApplication\Application_Service_Admin;
use JetApplication\Content_InfoPage;

/**
 * @var MVC_View $this

 * @var Content_InfoPage $item
 */

$item = $this->getRaw('item');
?>
<div style="display: flex;align-items: center">
	<div><?=Application_Service_Admin::EntityEdit()->renderPreviewButton( $item )?></div>
	<div style="padding-left: 10px;"><?=$item->getPageId();?></div>
</div>


<?php
