<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\Content\InfoPages;

use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Content_InfoPage;

/**
 * @var MVC_View $this

 * @var Content_InfoPage $item
 */

$item = $this->getRaw('item');
?>
<div style="display: flex;align-items: center">
	<div><?=Admin_Managers::EntityEdit()->renderPreviewButton( $item )?></div>
	<div style="padding-left: 10px;"><?=$item->getPageId();?></div>
</div>


<?php
