<?php
namespace JetApplication;

use JetShop\Core_EShopEntity_Admin_WithEShopData_Interface;

interface EShopEntity_Admin_WithEShopData_Interface extends Core_EShopEntity_Admin_WithEShopData_Interface {
}