<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Brand_ShopData;
use JetApplication\ProductListing;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');

$initial_map = $listing->getInitialMap();
$brand_ids = $initial_map->getBrandIds();
if(!$brand_ids) {
	return;
}

$filtered_map = $listing->getFilteredMap();

$brands = Brand_ShopData::getActiveList( $brand_ids );


?>
<div style="display: grid;grid-template-columns: 200px 1fr;padding-bottom:10px;margin-bottom: 30px;border-bottom: 1px solid #c9c9c9;">
	<div><b><?=Tr::_('Brand')?></b></div>
	<div style="display: grid;grid-template-columns: repeat(5, 1fr)">
<?php
foreach( $brands as $brand_id=>$brand ):
	
	$selected = $listing->getFilter()->getBrandsFilter()->getBrandSelected( $brand_id );
	
	if(!$selected) {
		$count = $listing->getBrandCount( $brand_id );
		$disabled = $count==0;
	}
	
	$label = $brand->getName();
	
	if($selected):
	?>
	<div>
		<label>
			<input
				type="checkbox"
				class="lf-brand"
				value="<?=$brand_id?>"
				checked
				onchange="listing.submitFilter()"
			>
			<?=$label;?>
		</label>
	</div>
	<?php
	else:
		if($disabled):
			?>
			<div>
				<label>
					<input
						type="checkbox"
						class="lf-brand"
						value="<?=$brand_id?>"
						disabled
						onchange="listing.submitFilter()"
					>
					<?=$label;?>
				</label>
			</div>
		<?php
		else:
		?>
		<div>
			<label>
				<input
					type="checkbox"
					class="lf-brand"
					value="<?=$brand_id?>"
					onchange="listing.submitFilter()"
				>
				<?=$label;?> (<?=$count;?>)
			</label>
		</div>
		<?php
		endif;
    endif;
endforeach; ?>
	</div>
</div>
