<?php
namespace JetShop;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');

if(count( $listing->flags()->getFilterFlags() )<1) {
	return;
}
?>
<div class="options">
	<?php foreach ($listing->flags()->getFilterFlags() as $flag):
		if($flag->isDisabled()) {
			continue;
		}

		if($flag->isActive()) {
			$checked_arg = ' checked="checked"';
			$URL = $flag->generateURLWithout();

		} else {
			$checked_arg = '';
			$URL = $flag->generateURLWith();

		}

		if(!$flag->getCount()):
			?>
			<span onclick="return false;">
			<input type="checkbox" <?=$checked_arg?> disabled/>
					<span class="option"><?=$flag->getLabel();?></span>
			</span>
		<?php
		else:
			?>
			<span onclick="ProductListing.filter.flags.toggle('<?=$flag->getId();?>');return false">
			<input type="checkbox" id="filter_flag_<?=$flag->getId()?>"<?=$checked_arg?>/>
				<a href="<?=$URL;?>"><?=$flag->getLabel();?></a>
			</span>
		<?php
		endif;
	endforeach; ?>
</div>
