<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use Jet\Tr;
use JetApplication\ProductListing;
use JetApplication\Shops;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$shop = Shops::getCurrent();
$listing = $this->getRaw('listing');

$map = $listing->getInitialMap();

$min_price = $map->getMinPrice();
$max_price = $map->getMaxPrice();


if($min_price==$max_price) {
	return;
}

$filter_min_price = $min_price;
$filter_max_price = $max_price;

$price_filter = $listing->getFilter()->getPriceFilter();
if($price_filter->getIsActive()) {
	if($price_filter->getMinPrice()!==null) {
		$filter_min_price = $price_filter->getMinPrice();
	}
	if($price_filter->getMaxPrice()!==null) {
		$filter_max_price = $price_filter->getMaxPrice();
	}
	
}

$decimals = $shop->getCurrencyDecimalPlaces();
?>
<div style="display: grid;grid-template-columns: 200px 1fr;padding-bottom:10px;margin-bottom: 30px;border-bottom: 1px solid #c9c9c9;">
	<div><b><?=Tr::_('Price');?></b></div>
	
	<div>
		<input id="lf-price-min" type="number" value="<?=$filter_min_price?>" onchange="listing.submitFilter()" data-min="<?=$min_price?>"><span><?=$shop->getCurrencySymbolRight()?></span>
		<input id="lf-price-max" type="number" value="<?=$filter_max_price?>" onchange="listing.submitFilter()" data-max="<?=$max_price?>"><span><?=$shop->getCurrencySymbolRight()?></span>
	</div>
	
</div>
<hr>