<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use JetApplication\ProductListing;
use JetApplication\Property_Options_Option_ShopData;
use JetApplication\Property_ShopData;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');

$initial_map = $listing->getInitialMap();
$property_ids = $initial_map->getPropertyIds();
$option_ids = $initial_map->getPropertyOptionIds();
if(!$property_ids) {
	return;
}


$filtered_map = $listing->getFilteredMap();
$properties = Property_ShopData::getActiveList( $property_ids );
$property_options = Property_Options_Option_ShopData::getActiveList( $option_ids, order_by: ['priority'] );


foreach($properties as $property):
	/**
	 * @var Property_ShopData $property
	 */
	
	$this->setVar('property', $property);
	$this->setVar('property_options', $property_options);

	$filter = $this->render('product_listing/filter/properties/'.$property->getType());
	if(!$filter) {
		continue;
	}
	?>
	<div style="display: grid;grid-template-columns: 200px 1fr;padding-bottom:10px;margin-bottom: 30px;border-bottom: 1px solid #c9c9c9;">
		<div><b><?=$property->getLabel()?></b></div>
		<?=$filter?>
	</div>
<?php endforeach;
