<?php
namespace JetShop;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');

$filter_properties = $listing->properties();
$filter_brands = $listing->brands();

$filter_groups = [];

foreach( $filter_properties->getGroups() as $group_id=>$property_group ) {
	if( $property_group->isDisabled() ) {
		continue;
	}
	$group = $property_group->getGroup();

	foreach( $property_group->getProperties() as $listing_property ) {
		if( $listing_property->isDisabled() ) {
			continue;
		}

		$filter_groups[$group_id] = $group->getLabel();

		break;
	}
}


foreach( $filter_properties->getGroups() as $group_id=>$property_group ):
	if( $property_group->isDisabled() ) {
		continue;
	}
	$group = $property_group->getGroup();
	?>
	<div>
		<?php if ($group->getImagePictogram() || $group->getDescription()): ?>
			<div class="group-description-content">
				<?php if ($group->getImagePictogram()): ?>
					<img src="<?=$group->getImagePictogramUrl()?>" />
				<?php endif; ?>
				<?php if ($group->getDescription()): ?>
					<div class="desc-title"><?= $group->getLabel() ?></div>
					<?= $group->getDescription() ?>
				<?php endif; ?>
			</div>
		<?php endif; ?>
		<div>
			<?php foreach ($property_group->getProperties() as $listing_property):
				if( $listing_property->isDisabled() ) {
					continue;
				}

				echo $listing_property->renderFilterItem();
			endforeach; ?>
		</div>
	</div>
	<?php
endforeach;
