<?php
namespace JetApplication;

use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');

$filter_price = $listing->price();


if( !$listing->filterIsActive() ) {
	return;
}
?>


<h4><?=Tr::_('Máte vybráno:');?></h4>

<div class="items">

	<?php if(($active_flags=$listing->flags()->getActiveFilterFlags())): ?>
		<div class="filter-item-list">
			<?php foreach($active_flags as $flag): ?>
				<div class="filter-item-option-box" onclick="ProductListing.filter.flags.disable('<?= $flag->getId() ?>');return false;">
					<a href="<?=$flag->generateURLWithout();?>" onclick="ProductListing.filter.flags.disable('<?= $flag->getId() ?>');return false;">&times;</a>
					<?= $flag->getLabel() ?>
				</div>
			<?php endforeach; ?>
		</div>
	<?php endif;


	if( $listing->price()->isActive() ):
		?>
		<div class="filter-item-list">
			<div class="filter-item-option-box">
				<a href="javascript:ProductListing.filter.price.deactivate();">&times;</a>
				<?=Price::formatWithCurrency($filter_price->getFrom())?> - <?=Price::formatWithCurrency($filter_price->getTo())?>
			</div>
		</div>
	<?php
	endif;

	if(($active_properties=$listing->properties()->getActiveProperties())):
		foreach ( $listing->properties()->getActiveProperties() as $active_property):
			echo $active_property->renderSelectedFilterItem();
		endforeach;
	endif;

	if($listing->brands()->filterIsActive()):
		?>
		<div class="filter-item-list">

			<?php foreach($listing->brands()->getActiveBrands() as $filter_brand):
				$brand = $filter_brand->getBrand();
				$id = $brand->getId();
				?>
				<div class="filter-item-option-box">
					<a href="javascript:ProductListing.filter.brands.disable(<?= $id ?>);">&times;</a>
					<?=$brand->getInternalName() ?>
				</div>
			<?php
			endforeach; ?>
		</div>
	<?php endif; ?>

	<div class="cancel">
		<a href="javascript:ProductListing.filter.deactivate();" class="filter-cancel-btn">&times; <?=Tr::_('Zrušit filtr')?></a>
	</div>
</div>
