<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Payment\Twisto;

use Jet\Http_Request;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Config_PerShop $config
 */
$config = $this->getRaw('config');
?>

<script>
	var _twisto_config = {
		public_key: '<?=$config->getPublickey()?>',
		script: 'https://static.twisto.cz/api/v2/twisto.js'
	};
	(function(e,g,a){function h(a){return function(){b._.push([a,arguments])}}var f=["check"],b=e||{},c=document.createElement(a);a=document.getElementsByTagName(a)[0];b._=[];for(var d=0;d<f.length;d++)b[f[d]]=h(f[d]);this[g]=b;c.type="text/javascript";c.async=!0;c.src=e.script;a.parentNode.insertBefore(c,a);delete e.script}).call(window,_twisto_config,"Twisto","script");
	
	let TwistoCheckHandler = {
		original_btn_handler: null,
		
		init: () => {
			let btn = document.getElementById('place_order_button');

			TwistoCheckHandler.original_btn_handler = btn.onclick;

			btn.onclick = function () {
				
				if(
					!document.getElementById('agree_flag_terms').checked ||
					!document.getElementById('agree_flag_twisto_disagree').checked
				) {
					TwistoCheckHandler.original_btn_handler();
					
					return;
				}

				Twisto.check(
					'<?=$this->getRaw('payload')?>',
					function(response) {
						if (response.status == 'accepted') {

							fetch('<?=Http_Request::currentURI(['action' =>'set_twisto_transaction_id'])?>&id='+encodeURIComponent(response.transaction_id));
							
							setTimeout(function () {
								TwistoCheckHandler.original_btn_handler();
							}, 250);
						}
					},
					function() {
						// někde se stala chyba – chybný požadavek nebo výpadek spojení.
					}
				);
			}
		}
	};

	(function() {
		TwistoCheckHandler.init();
	})();
	
</script>
