<?php
use Jet\MVC_View;
use JetApplication\Delivery_Method_ShopData;
use JetApplication\Carrier_DeliveryPoint;
use JetApplication\Shop_Managers;
use JetApplicationModule\Shop\CashDesk\CashDesk;

/**
 * @var MVC_View $this
 * @var Carrier_DeliveryPoint $point
 * @var Delivery_Method_ShopData $method
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');
$pricelist = $cash_desk->getPricelist();

$c = $this->getInt('c');
$point = $this->getRaw('point');
$method = $this->getRaw('method');

$icon = '';
if($method->getIcon1()) {
	$icon = $method->getIcon1ThumbnailUrl(50, 50);
}
?>
<div
	data-id="<?=$method->getId()?>:<?=$point->getPointCode()?>"
	data-type="place"
	class="whisperer-item<?=($c==1?' whisperer-item-selected':'')?>"
>
	<div class="place_search_result_item">
		<div class="place_search_result_item_image">
			<?php if($icon): ?>
			<img src="<?=$icon?>" title="<?=$method->getTitle()?>" alt="<?=$method->getTitle()?>" />
			<?php endif; ?>
		</div>
		<div class="place_search_result_item_address">
			<?=$point->getName()?><br />
			<?=$point->getStreet()?><br />
			<?=$point->getZip()?>  <?=$point->getTown()?>
		</div>
		<div class="place_search_result_item_price">
			<?= Shop_Managers::PriceFormatter()->formatWithCurrency( $method->getPrice($pricelist), $pricelist->getCurrency() )?>
		</div>
	</div>
</div>
