<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\InvoicesInAdvance;


use Jet\Locale;
use Jet\Tr;
use JetApplication\Admin_Managers;
use JetApplication\Admin_Managers_EShopEntity_Listing;

use Jet\UI;
use Jet\MVC_View;
use JetApplication\InvoiceInAdvance_Item;
use JetApplication\InvoiceInAdvance;

/**
 * @var MVC_View $this
 * @var InvoiceInAdvance $invoice
 * @var Admin_Managers_EShopEntity_Listing $listing
 */

$invoice = $this->getRaw( 'invoice' );
$listing = $this->getRaw('listing');


$price_formatter = Admin_Managers::PriceFormatter();
$product_manager = Admin_Managers::Product();
$icons = InvoiceInAdvance_Item::getItemIcons();

$has_VAT = $invoice->hasVAT();

?>

<fieldset style="padding: 10px;">
	
	<legend><?=Tr::_('Invoice items')?></legend>
	
	<table class="table table-striped">
		<thead>
		<tr>
			<th style="width: 20px;"></th>
			<th style="width: 60px;"></th>
			<th><?=Tr::_('Item')?></th>
			
			
			<th style="width: 200px;"><?=Tr::_('Price per item without VAT')?></th>
			
			<?php if($has_VAT): ?>
			<th style="width: 200px;"><?=Tr::_('VAT per item')?></th>
			<?php endif; ?>
			
			<th style="width: 100px;"><?=Tr::_('VAT rate')?></th>
			
			<?php if($has_VAT): ?>
			<th style="width: 200px;"><?=Tr::_('Price per item with VAT')?></th>
			<?php endif; ?>
			
			<th style="width: 200px;"><?=Tr::_('Total amount without VAT')?></th>
			
			<?php if($has_VAT): ?>
			<th style="width: 200px;"><?=Tr::_('Total amount with VAT')?></th>
			<?php endif; ?>
		</tr>
		</thead>
		<tbody>
		<?php
		$showItem = function( InvoiceInAdvance_Item $item ) use ($product_manager, $icons, $price_formatter, $invoice, $has_VAT) {
			?>
			<tr id="item_<?=$item->getId()?>">
				<td style="text-align: center"><?=$icons[$item->getType()]?></td>
				<td style="text-align: right"><b><?=Locale::float($item->getNumberOfUnits()) ?>&nbsp;<?=$item->getMeasureUnit()?->getName()?></b></td>
				<td>
					<?php if( $item->isPhysicalProduct() || $item->isVirtualProduct() ): ?>
						<a href="<?=$product_manager::getEditUrl( (int)$item->getItemId() )?>"><?=$item->getTitle() ?></a>
					<?php else: ?>
						<?=$item->getTitle() ?>
					<?php endif; ?>
				</td>
				
				<td><?=$price_formatter->formatWithCurrency_WithoutVAT( $invoice->getCurrency(), $item->getPricePerUnit_WithoutVat() )?></td>
			<?php if($has_VAT): ?>
				<td><?=$price_formatter->formatWithCurrency_VAT( $invoice->getCurrency(), $item->getPricePerUnit_Vat() )?></td>
			<?php endif; ?>
				<td><?=$item->getVatRate()?>%</td>
			
			<?php if($has_VAT): ?>
				<td><?=$price_formatter->formatWithCurrency_WithVAT( $invoice->getCurrency(), $item->getPricePerUnit_WithVat() )?></td>
			<?php endif; ?>
				<td><?=$price_formatter->formatWithCurrency_WithoutVAT( $invoice->getCurrency(), $item->getTotalAmount_WithoutVat() )?></td>
			<?php if($has_VAT): ?>
				<td><?=$price_formatter->formatWithCurrency_WithVAT( $invoice->getCurrency(), $item->getTotalAmount_WithVat() )?></td>
			<?php endif; ?>
			
			</tr>
			<?php
			
			if($item->getSetItems()):
				foreach($item->getSetItems() as $set_item):
					?>
					<tr style="opacity: 0.3">
						<td style="text-align: center">
						</td>
						<td style="text-align: right"><b><?=Locale::float($set_item->getNumberOfUnits()) ?>&nbsp;<?=$set_item->getMeasureUnit()?->getName()?></b></td>
						<td>
							<a href="<?=$product_manager::getEditUrl( $set_item->getItemId() )?>"><?=$set_item->getTitle() ?></a>
						</td>




						<td><?=$price_formatter->formatWithCurrency_WithoutVAT( $invoice->getCurrency(), $set_item->getPricePerUnit_WithoutVat() )?></td>
						<?php if($has_VAT): ?>
							<td><?=$price_formatter->formatWithCurrency_VAT( $invoice->getCurrency(), $set_item->getPricePerUnit_Vat() )?></td>
						<?php endif; ?>
						<td><?=$item->getVatRate()?>%</td>
						
						<?php if($has_VAT): ?>
							<td><?=$price_formatter->formatWithCurrency_WithVAT( $invoice->getCurrency(), $set_item->getPricePerUnit_WithVat()*$item->getNumberOfUnits() )?></td>
						<?php endif; ?>
						<td><?=$price_formatter->formatWithCurrency_WithoutVAT( $invoice->getCurrency(), $set_item->getTotalAmount_WithoutVat()*$item->getNumberOfUnits() )?></td>
						<?php if($has_VAT): ?>
							<td><?=$price_formatter->formatWithCurrency_WithVAT( $invoice->getCurrency(), $set_item->getTotalAmount_WithVat()*$item->getNumberOfUnits() )?></td>
						<?php endif; ?>
						
						
						
					</tr>
				<?php
				endforeach; ?>
				<tr style="opacity: 0.5">
					<td></td>
					<td></td>
					<td colspan="99">
						<i><?=Tr::_('Set discount:')?></i>
						<?php if($has_VAT): ?>
							<i><?=$price_formatter->formatWithCurrency_WithVAT($invoice->getCurrency(), $item->getSetDiscountPerUnit())?></i>
							<?php if($item->getNumberOfUnits()>1): ?> / <i><?=$price_formatter->formatWithCurrency_WithVAT($invoice->getCurrency(), $item->getSetDiscountPerUnit()*$item->getNumberOfUnits())?></i><?php endif; ?>
						<?php else: ?>
							<i><?=$price_formatter->formatWithCurrency_WithoutVAT($invoice->getCurrency(), $item->getSetDiscountPerUnit())?></i>
							<?php if($item->getNumberOfUnits()>1): ?> / <i><?=$price_formatter->formatWithCurrency_WithoutVAT($invoice->getCurrency(), $item->getSetDiscountPerUnit()*$item->getNumberOfUnits())?></i><?php endif; ?>
						<?php endif; ?>
					</td>
				</tr>
				<?php
			endif;
		};
		?>
		
		<?php
		foreach( $invoice->getItems() as $item ):
			if(
				$item->getType()==InvoiceInAdvance_Item::ITEM_TYPE_PRODUCT ||
				$item->getType()==InvoiceInAdvance_Item::ITEM_TYPE_VIRTUAL_PRODUCT
			) {
				$showItem( $item );
			}
		endforeach;
		
		foreach( $invoice->getItems() as $item ):
			if(
				$item->getType()==InvoiceInAdvance_Item::ITEM_TYPE_GIFT ||
				$item->getType()==InvoiceInAdvance_Item::ITEM_TYPE_VIRTUAL_GIFT
			) {
				$showItem( $item );
			}
		endforeach;
		
		foreach( $invoice->getItems() as $item ):
			if(
				$item->getType()==InvoiceInAdvance_Item::ITEM_TYPE_SERVICE
			) {
				$showItem( $item );
			}
		endforeach;
		
		foreach( $invoice->getItems() as $item ):
			if(
				$item->getType()==InvoiceInAdvance_Item::ITEM_TYPE_PAYMENT ||
				$item->getType()==InvoiceInAdvance_Item::ITEM_TYPE_DELIVERY
			) {
				$showItem( $item );
			}
		endforeach;
		
		foreach( $invoice->getItems() as $item ):
			if(
				$item->getType()==InvoiceInAdvance_Item::ITEM_TYPE_DISCOUNT
			) {
				$showItem( $item );
			}
		endforeach;
		
		
		?>
		</tbody>
	</table>
	
	<div style="display: grid;grid-template-columns: 1fr 500px;">
		<div>
		</div>
		<div>
			<table class="table table">
				<tr>
					<td style="width: 20px;"></td>
					<td><?=Tr::_('Without VAT:')?></td>
					<td><?=$price_formatter->formatWithCurrency_WithoutVAT($invoice->getCurrency(), $invoice->getTotalWithoutVat())?></td>
				</tr>
				<tr>
					<td></td>
					<td><?=Tr::_('VAT:')?></td>
					<td><?=$price_formatter->formatWithCurrency_VAT($invoice->getCurrency(), $invoice->getTotalVat())?></td>
				</tr>
				<?php if($invoice->getTotalRound()<>0): ?>
				<tr>
					<td></td>
					<td><?=Tr::_('Round:')?></td>
					<td><?=$price_formatter->formatWithCurrency_VAT($invoice->getCurrency(), $invoice->getTotalRound())?></td>
				</tr>
				<?php endif; ?>
					<tr>
						<td><?=UI::icon('calculator')?></td>
						<td style="font-weight: bolder;font-size: 1.4rem"><?=Tr::_('Total:')?></td>
						<td style="font-weight: bolder;font-size: 1.4rem">
							<?=$price_formatter->formatWithCurrencyByHasVAT($has_VAT, $invoice->getCurrency(), $invoice->getTotal())?>
						</td>
					</tr>
			</table>
		</div>
	</div>
</fieldset>

<?php if($has_VAT): ?>
<fieldset>
<legend><?=Tr::_('VAT overview')?></legend>

	<table class="table table-bordered" style="width: 600px;">
		<thead>
		<tr>
			<th nowrap=""><?=Tr::_('VAT rate')?></th>
			<th nowrap=""><?=Tr::_('Tax base')?></th>
			<th nowrap=""><?=Tr::_('Tax')?></th>
		</tr>
		</thead>
		<tbody>
		<?php foreach($invoice->getVATOverview() as $vat_ov_item): ?>
			<tr>
				<td nowrap=""><?=Locale::float($vat_ov_item->getVatRate())?>%</td>
				<td nowrap=""><?=$price_formatter->formatWithCurrency_WithoutVAT($invoice->getCurrency(), $vat_ov_item->getTaxBase())?></td>
				<td nowrap=""><?=$price_formatter->formatWithCurrency_VAT($invoice->getCurrency(), $vat_ov_item->getTax())?></td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
	
</fieldset>
<?php endif; ?>