<?php
namespace JetApplicationModule\Admin\InvoicesInAdvance;


use Jet\Http_Request;
use Jet\Tr;
use Jet\UI_button;
use JetApplication\Admin_Managers_Entity_Listing;

use Jet\UI;
use Jet\MVC_View;
use JetApplication\InvoiceInAdvance;

/**
 * @var MVC_View $this
 * @var InvoiceInAdvance $invoice
 * @var Admin_Managers_Entity_Listing $listing
 */

$invoice = $this->getRaw( 'invoice' );
$listing = $this->getRaw('listing');

$is_editable = $invoice->isEditable();

$prev_url = $listing->getPrevEditUrl( $invoice->getId() );
$next_url = $listing->getNextEditUrl( $invoice->getId() );

?>
<div class="toolbar" id="main-toolbar">
	<div>
		<?=UI::button_goBack()?>
	</div>
	
	<div style="padding-left:20px;width: 80px;text-align: center">
		<?php if($prev_url): ?>
			<?=UI::button(' ')->setIcon('chevron-left')->setUrl($prev_url)?>
		<?php endif; ?>
	</div>
	
	
	<div style="padding-left: 10px;padding-right: 10px;text-align: center;font-size: 1.5rem;">
		<?php if($invoice->isCancelled()): ?>
			<b style="text-decoration: line-through;color: red;"><?=$invoice->getNumber()?></b>
			<span style="color: red;font-size: 1rem;"><?=Tr::_('Cancelled')?></span>
		<?php else: ?>
			<b><?=$invoice->getNumber()?></b>
		<?php endif; ?>
	</div>
	
	<div style="width: 50px;text-align: center">
		<?php if($next_url): ?>
			<?=UI::button(' ')->setIcon('chevron-right')->setUrl($next_url)?>
		<?php endif; ?>
	</div>
	
	<div style="display: flex;gap: 100px;">
		<?php if(!$invoice->isCancelled()): ?>
			<?=UI::button(Tr::_('PDF'))
				->setIcon('print')
				->setUrl(Http_Request::currentURI(['handle'=>'show_pdf']))
				->setCustomTagAttribute('target', '_blank')
			?>
			<?=UI::button(Tr::_('Send by e-mail to the customer'))
				->setIcon('at')
				->setClass( UI_button::CLASS_INFO )
				->setUrl(Http_Request::currentURI(['handle'=>'send']))
			?>

			<?=UI::button(Tr::_('Cancel'))
				->setClass( UI_button::CLASS_DANGER )
				->setIcon('print')
				->setUrl(Http_Request::currentURI(['handle'=>'cancel']))
			?>

		<?php endif; ?>
	</div>
	

</div>

