<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\Form;
use Jet\Http_Request;

use Jet\UI_dataGrid;
use Jet\UI;

use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Form         $filter_form
 * @var Listing      $listing
 */
$grid = $this->getRaw( 'grid' );
$router = $this->getController()->getControllerRouter();
$filter_form = $this->getRaw( 'filter_form' );
$listing = $this->getRaw('listing');
?>


<?=$filter_form->start()?>
	<div class="row" style="padding-bottom: 10px;">
		<div class="col-12 col-sm-6 col-lg-3">
			<?=$listing->getFilter( Listing_Filter::CATEGORIES )->renderForm()?>
		</div>
		<div class="col-12 col-sm-6 col-lg-3">
			<?=$listing->getFilter( Listing_Filter::SEARCH )->renderForm()?>
		</div>
	</div>
	<div class="row">
		<div class="col-12 col-lg-6 col-xl-5">
			<?=$listing->getFilter( Listing_Filter::PRODUCT_KIND )->renderForm()?>
		</div>
		<div class="col-12 col-lg-6 col-xl-5">
			<?=$listing->getFilter( Listing_Filter::PRODUCT_TYPE )->renderForm()?>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<?=$listing->getFilter( Listing_Filter::IS_ACTIVE )->renderForm()?>
		</div>
	</div>
<?=$filter_form->end()?>
