<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\Form;

use Jet\MVC_View;

/**
 * @var MVC_View     $this
 * @var Form         $filter_form
 * @var Listing      $listing
 */
$filter_form = $this->getRaw( 'filter_form' );
$listing = $this->getRaw('listing');
?>


<?=$filter_form->start()?>
	<div class="row">
		<div class="col-12 col-sm-12 col-md-12 col-lg-8 col-xl-5">
			<?=$listing->getFilter( Listing_Filter::SEARCH )->renderForm()?>
		</div>
	</div>
	<div class="row">
		<div class="col-12 col-lg-6 col-xl-5">
			<?=$listing->getFilter( Listing_Filter::PRODUCT_KIND )->renderForm()?>
		</div>
		<div class="col-12 col-lg-6 col-xl-5">
			<?=$listing->getFilter( Listing_Filter::PRODUCT_TYPE )->renderForm()?>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<?=$listing->getFilter( Listing_Filter::IS_ACTIVE )->renderForm()?>
		</div>
	</div>
<?=$filter_form->end()?>
