<?php
namespace JetApplicationModule\Admin\ControlCentreModule\Shops;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;
use JetApplication\EShops;
use JetApplication\EShop;

/**
 * @var MVC_View   $this
 * @var EShop|null $selected_eshop
 * @var EShop|null $new_eshop
 */

$selected_eshop = $this->getRaw('selected_eshop');
$new_eshop = $this->getRaw('new_eshop');

?>
<div style="display: grid;grid-template-columns: 2fr 3fr;gap: 10px">
	<div>
		<table class="table table-striped">
		<thead>
		<tr>
			<th><?=Tr::_('Name')?></th>
			<th><?=Tr::_('Internal code')?></th>
			<th><?=Tr::_('Locale')?></th>
		</tr>
		</thead>
		<?php foreach( EShops::getList() as $eshop):
			$edit_URL = Http_Request::currentURI(set_GET_params: ['eshop'=>$eshop->getKey()], unset_GET_params: ['add']);
		
			if( $selected_eshop?->getKey()==$eshop->getKey() ):
				?>
				<tr>
					<td><b><?=$eshop->getName()?></b></td>
					<td><b><?=$eshop->getCode()?></b></td>
					<td><?=UI::flag($eshop->getLocale())?></td>
				</tr>
			<?php else: ?>
				<tr>
					<td><a href="<?=$edit_URL?>"><?=$eshop->getName()?></a></td>
					<td><a href="<?=$edit_URL?>"><?=$eshop->getCode()?></a></td>
					<td><a href="<?=$edit_URL?>"><?=UI::flag($eshop->getLocale())?></a></td>
				</tr>
			<?php
			endif;
		endforeach; ?>
		</table>
	</div>
	<div>
		<?php if($selected_eshop || $new_eshop):
			foreach( UI_messages::get(context: 'CC') as $message ):
				echo $message;
			endforeach;
			
			
			$form = $selected_eshop->getEditForm();
			$form->field('URLs')->input()->addCustomCssStyle("height: 300px");
			?>
			<?=$form->start()?>
				<?=$form->field('code')?>
				<?=$form->field('name')?>
				<?=$form->field('_is_active')?>
				<?=$form->field('is_default')?>
				<?=$form->field('URLs')?>
				<?=$form->field('pricelist_codes')?>
				<?=$form->field('default_pricelist_code')?>
				<?=$form->field('availability_codes')?>
				<?=$form->field('default_availability_code')?>
				<?=$form->field('default_warehouse_id')?>
				<?=$form->field('use_template')?>
				<?=$form->field('template_relative_dir')?>
		
				<div style="display: grid;grid-template-columns: 1fr 1fr;">
					<div>
						<?=UI::button_save()?>
					</div>
					<div style="text-align: right">
					</div>
				</div>
				
			<?=$form->end()?>
		<?php endif; ?>
		
	</div>
	
</div>