<?php
namespace JetApplication;

use Jet\DataModel_Definition;
use JetShop\Core_WarehouseManagement_TransferBetweenWarehouses_Item;

#[DataModel_Definition]
class WarehouseManagement_TransferBetweenWarehouses_Item extends Core_WarehouseManagement_TransferBetweenWarehouses_Item
{

}