<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Marketing\GiftShoppingCart;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Admin_Managers;


/**
 * @var MVC_View $this
 * @var Listing_Filter_Gift $filter
 */

$filter = $this->getRaw('filter');

$field = $filter->getListing()->getFilterForm()->field( 'gift' );

$field->input()->addJsAction( 'onchange', 'this.form.submit()' );

echo Admin_Managers::EntityListing()->renderListingFilter(
	filter:      $filter,
	title:       Tr::_('Gift'),
	form_fields: [$field],
	is_active:   $filter->getGift()>0,
	renderer:    function() use ($field) {
		?>
		<script>
			function filterGift( id ) {
				const input = document.getElementById('<?=$field->getId()?>');
				input.value = id;
				input.form.submit();
			}
		</script>
		<div style="width: 400px;">
			<?=Admin_Managers::Product()->renderSelectWidget(
				"filterGift(selected_item.id)",
				$field->getValue()
			)?>
			<?= $field->input() ?>
		</div>
		<?php
	}
);
