<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Discounts\Code;


use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Discounts_Code;

/**
 * @var MVC_View   $this
 * @var Discounts_Code|null $used_code
 * @var Main $module
 */

$module = $this->getRaw('module');

if(!$module->isPossibleToAddCode()) {
	return;
}

$form = $module->getUseCodeForm();

$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 0
]);
$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 10
]);

$code_f = $form->field('code');

$form->renderer()->addJsAction('onsubmit', 'DiscountCode.submit();return false;');
?>

<?=$form->start()?>
	<?=$form->getCommonMessage()?>
	<div id="discount_code_enter_form">
		<div></div>
		<div>
			<?=$code_f->input();?>
		</div>
		<?=UI::button(Tr::_('Use'))->setType('submit')?>
		<div><?=$code_f->error();?></div>
		<div></div>
	</div>
<?=$form->end()?>
