<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Discounts\Code;


use Jet\MVC_View;
use Jet\UI;
use JetApplication\CashDesk;
use JetApplication\Discounts_Code;
use JetApplication\Application_Service_EShop;

/**
 * @var MVC_View   $this
 * @var Discounts_Code|null $used_code
 * @var Main $module
 * @var CashDesk $cash_desk
 */

$module = $this->getRaw('module');
$cash_desk = $this->getRaw('cash_desk');


foreach($cash_desk->getDiscounts() as $discount):
	if($discount->getDiscountModule()!=Main::DISCOUNT_MODULE) {
		continue;
	}
	?>
<div id="discount_code_used_codes">
	<?php if( $discount->getAmount() ):
		?>
		<?=$discount->getDescription()?>:

		<strong><?=Application_Service_EShop::PriceFormatter()->formatWithCurrency($discount->getAmount())?></strong>
	<?php else: ?>
		<?=$discount->getDescription()?>
	<?php endif; ?>

	<?=UI::button(' ')->setIcon('trash')->setOnclick("DiscountCode.cancel('{$discount->getDiscountContext()}')")?>
</div>
<?php endforeach;

