<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Complaints;


use Jet\Form;
use Jet\Locale;
use Jet\Tr;
use JetApplication\Application_Service_Admin;
use JetApplication\Application_Service_Admin_EShopEntity_Listing;

use Jet\MVC_View;
use JetApplication\EShops;
use JetApplication\Complaint;

/**
 * @var MVC_View $this
 * @var Complaint     $complaint
 * @var Application_Service_Admin_EShopEntity_Listing $listing
 * @var Form $add_bl_form
 */

$complaint = $this->getRaw( 'complaint' );
?>


	<div style="display: flex">
		<div style="margin: 10px" class="card">
			
			<div class="card-header"><b><?=Tr::_('Common information')?></b></div>
			<div class="card-body">
				
				<?=$complaint->getStatus()->showAdmin()?>
				
				<table style="margin: 10px">
					<?php if(EShops::isMultiEShopMode()): ?>
						<tr>
							<td><b><?=Tr::_('e-shop')?></b></td>
							<td><?=$complaint->getEshop()->getName()?></td>
						</tr>
					<?php endif; ?>
					<tr>
						<td nowrap=""><b><?=Tr::_('Date and time:')?></b></td>
						<td nowrap="" style="padding: 3px"><?= Locale::dateAndTime($complaint->getDateStarted()) ?></td>
					</tr>

					<?php if($complaint->getDateOfReceiptOfClainedGoods()): ?>
					<tr>
						<td nowrap=""><b><?=Tr::_('Date of receipt of clained goods:')?></b></td>
						<td nowrap="" style="padding: 3px"><?= Locale::dateAndTime($complaint->getDateOfReceiptOfClainedGoods()) ?></td>
					</tr>
					<?php endif; ?>
					
					<?php if($complaint->getDateFinished()): ?>
						<tr>
							<td nowrap=""><b><?=Tr::_('Finish date:')?></b></td>
							<td nowrap="" style="padding: 3px"><?= Locale::dateAndTime($complaint->getDateFinished()) ?></td>
						</tr>
					<?php endif; ?>
					
					<?php /*
					<tr>
						<td nowrap=""><b><?=Tr::_('IP address:')?></b></td>
						<td nowrap="" style="padding: 3px"><?= $complaint->getIpAddress() ?></td>
					</tr>
					*/ ?>
					<tr>
						<td nowrap=""><b><?=Tr::_('Order:')?></b></td>
						<td nowrap="" style="padding: 3px"><?=Application_Service_Admin::Order()->renderItemName($complaint->getOrderId())?></td>
					</tr>
					<tr>
						<td nowrap=""><b><?=Tr::_('Bill number:')?></b></td>
						<td nowrap="" style="padding: 3px"><?=$complaint->getBillNumber()?></td>
					</tr>
					<tr>
						<td><b><?=Tr::_('Type:')?></b></td>
						<td><?=$complaint->getComplaintType()?->showAdmin()?></td>
					</tr>
					<tr>
						<td><b><?=Tr::_('Delivery of the complained goods:')?></b></td>
						<td><?=$complaint->getDeliveryOfClaimedGoods()?->showAdmin()?></td>
					</tr>
					<tr>
						<td><b><?=Tr::_('Preffered solution:')?></b></td>
						<td><?=$complaint->getPreferredSolution()?->showAdmin()?></td>
					</tr>
					<tr>
						<td></td>
						<td><?=Plugin::get(Plugin_EditMain_Main::getKey())->renderButton()?></td>
					</tr>
				</table>
			</div>
		</div>
		
		<div style="margin: 10px;margin-left: 80px;" class="card">
			<div class="card-header"><b><?=Tr::_('Customer')?></b></div>
			<div class="card-body">
				
				<table>
					<tr>
						<td></td>
						<td>
							<?=Application_Service_Admin::Customer()->renderItemName( $complaint->getCustomerId() )?>
							<br>
						</td>
					</tr>
					<tr>
						<td style="font-size: 1.2rem;font-weight: bolder"></td>
						<td style="font-size: 1.2rem;font-weight: bolder">
							<?php if($complaint->getDeliveryCompanyName()):?>
								<?=$complaint->getDeliveryCompanyName()?><br>
							<?php endif; ?>
							<?=$complaint->getDeliveryFirstName()?> <?=$complaint->getDeliverySurname()?>
						</td>
					</tr>
					<tr>
						<td style="font-size: 1.2rem;font-weight: bolder"><?=Tr::_('Phone:')?></td>
						<td style="font-size: 1.2rem;font-weight: bolder"><?=$complaint->getPhone()?></td>
					</tr>
					<tr>
						<td><?=Tr::_('e-mail:')?></td>
						<td><a href="mailto:<?=$complaint->getEmail()?>"><u><?=$complaint->getEmail()?></u></a></td>
					</tr>
				</table>
				
				<?=Plugin::get( Plugin_ChangeEMailAndPhone_Main::KEY )?->renderButton()?>
			</div>
		</div>

		<div style="margin: 10px;" class="card">
			<div class="card-header"><b><?=Tr::_('Delivery address')?></b></div>
			<div class="card-body">
				<?=Application_Service_Admin::Customer()->formatAddress( $complaint->getEshop(), $complaint->getDeliveryAddress() )?>
				<?=Plugin::get( Plugin_ChangeDeliveryAddress_Main::KEY )?->renderButton()?>
			</div>
		</div>

		<div style="margin: 10px;" class="card">
			<div class="card-header"><b><?=Tr::_('Service report')?></b></div>
			<div class="card-body">
				<?=Plugin::get( Plugin_ServiceReport_Main::KEY )?->renderDialog()?>
			</div>
		</div>
		
		
		<div style="margin: 10px;">
		</div>
	</div>

