<?php
namespace JetApplicationModule\Admin\Complaints;

use Jet\Http_Request;
use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\EMail_Sent;

/**
 * @var MVC_View $this
 * @var Complaint     $complaint
 */

$complaint = $this->getRaw( 'complaint' );
?>
	
	<table class="table table-striped">
		<thead>
		<tr>
			<th style="width: 20px;"></th>
			<th style="width: 200px;"><?=Tr::_('Date and time')?></th>
			<th style="width: 450px;"><?=Tr::_('Subject of e-mail')?></th>
			<th style="width: 450px;"><?=Tr::_('Sent to')?></th>
			<th><?=Tr::_('Attachments')?></th>
		</tr>
		</thead>
		<?php foreach( EMail_Sent::getByContext( 'complaint', $complaint->getId() ) as $sent_email): ?>
			<tr>
				<td><a href="<?=Http_Request::currentURI(set_GET_params: ['show_sent_email'=>$sent_email->getId()])?>" target="_blank"><?=UI::icon('eye')?></a></td>
				<td><?=Locale::dateAndTime($sent_email->getCreated())?></td>
				<td><?=$sent_email->getSubject()?></td>
				<td><?=nl2br($sent_email->getTo())?></td>
				<td><?php foreach(explode("\n", $sent_email->getAttachments()) as $file):
						echo basename( $file ).'<br>';
					endforeach;?></td>
			</tr>
		<?php endforeach; ?>
	</table>
