<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Complaints;


use Jet\Http_Request;
use Jet\Tr;
use Jet\UI_button;
use JetApplication\Application_Service_Admin_EShopEntity_Listing;

use Jet\UI;
use Jet\MVC_View;
use JetApplication\Complaint;


/**
 * @var MVC_View $this
 * @var Complaint     $complaint
 * @var Application_Service_Admin_EShopEntity_Listing $listing
 */

$complaint = $this->getRaw( 'complaint' );
$listing = $this->getRaw('listing');

$is_editable = $complaint->isEditable();

$prev_url = $listing->getPrevEditUrl( $complaint->getId() );
$next_url = $listing->getNextEditUrl( $complaint->getId() );

?>
<div class="toolbar" id="main-toolbar" style="display: grid;grid-template-columns: 1fr;gap:10px;">
	<div style="display: flex;align-items: center;gap: 10px;">
		<div>
			<?=UI::button_goBack()?>
		</div>
		
		<div style="padding-left:20px;width: 80px;text-align: center">
			<?php if($prev_url): ?>
				<?=UI::button(' ')->setIcon('chevron-left')->setUrl($prev_url)?>
			<?php endif; ?>
		</div>
		
		
		<div style="padding-left: 10px;padding-right: 10px;text-align: center;font-size: 1.5rem;display:flex;">
			<b><?=$complaint->getNumber()?></b>
			<?=UI::button(' ')->setIcon('clipboard')->setOnClick("cpNumber();")->setClass(UI_button::CLASS_LINK)?>
			
			<script>
				function cpNumber() {
					var number = "<?=$complaint::getEntityDefinition()->getEntityNameReadable(true)?> <?=$complaint->getNumber()?>";
					navigator.clipboard.writeText(number).then(function() {}, function(err) {});
				}
			</script>
		</div>
		
		<div style="width: 50px;text-align: center">
			<?php if($next_url): ?>
				<?=UI::button(' ')->setIcon('chevron-right')->setUrl($next_url)?>
			<?php endif; ?>
		</div>
		
		<?=Plugin::get(Plugin_Note_Main::KEY)?->renderButton()?>
		
		<?php /*Plugin::get( Plugin_SendMailConfirmation_Main::KEY )?->renderButton()* /?>
		<?php /*<?=Plugin::get( Plugin_DispatchNewGoods_Main::KEY )->renderButton()?> */ ?>

		<a href="<?=Http_Request::currentURI(['print'=>1])?>" target="_blank" class="btn btn-primary"><?=UI::icon('print')?> <?=Tr::_('Print')?></a>
		
		
		<?=Plugin::get( Plugin_SetStatus_Main::KEY )?->renderButton()?>
		
		<?=Plugin::get( Plugin_MoneyRefund_Main::KEY )?->renderButton()?>
		
		<?=Plugin::get( Plugin_GoodsReceiptProtocol_Main::KEY )?->renderButton()?>
		<?=Plugin::get( Plugin_ServiceReport_Main::KEY )?->renderButton()?>

		<?=Plugin::get( Plugin_ForceStatus_Main::KEY )?->renderButton()?>
		
	
	</div>
</div>
