<?php
namespace JetApplication;

use JetShop\Core_Admin_EntityManager_WithShopRelation_Controller;

abstract class Admin_EntityManager_WithShopRelation_Controller extends Core_Admin_EntityManager_WithShopRelation_Controller
{

}