<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Complaints;


use Jet\Form;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

use Jet\MVC_View;
use JetApplication\Complaint;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Complaint $complaint
 */

$complaint = $this->getRaw('complaint');
if(!$complaint->isEditable()) {
	return;
}
echo '&nbsp;';

echo UI::button(Tr::_('Reject'))
	->setClass(UI_button::CLASS_DANGER)
	->setIcon('xmark')
	->setOnClick("$('#reject_form_dialog').modal('show');");