<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Customers;


use Jet\MVC_View;
use JetApplication\Application_Service_Admin_EShopEntity_Listing;
use JetApplication\Customer;

/**
 * @var MVC_View $this
 * @var Application_Service_Admin_EShopEntity_Listing $listing
 * @var Customer $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=$item->getName();?></a>
<?php
