<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\Customers;

use Jet\MVC_View;
use JetApplication\Admin_Managers_EShopEntity_Listing;
use JetApplication\Customer;

/**
 * @var MVC_View $this
 * @var Admin_Managers_EShopEntity_Listing $listing
 * @var Customer $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=$item->getName();?></a>
<?php
