<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\ShoppingCart;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Pricelists;
use JetApplication\Application_Service_EShop;
use JetApplication\EShop_Pages;
use JetApplication\ShoppingCart_Item;

/**
 * @var MVC_View $this
 * @var ShoppingCart_Item $item
 */

$item = $this->getRaw('new_item');

$product = $item->getProduct();
?>

<div class="shopping-cart-popup-content">
	<div class="image">
		<?php if(($img=$product->getImageThumbnailUrl( 0, 100, 100))): ?>
			<img src="<?=$img?>"/>
		<?php endif; ?>
	</div>
	<div class="name">
		<a href="<?=$product->getURL()?>"><?=$product->getFullName()?></a><br>
	</div>
	<div class="price-per-unit">
		<?=$item->getNumberOfUnits()?> <?=$product->getMeasureUnit()?->getName()?> x <?=Application_Service_EShop::PriceFormatter()->formatWithCurrency($item->getProduct()->getPrice( Pricelists::getCurrent() ))?>
	</div>
	<div class="total">
		<?=Application_Service_EShop::PriceFormatter()->formatWithCurrency($item->getAmount())?>
	</div>
</div>


<div class="shopping-cart-popup-buttons">
	<?=UI::button(Tr::_('Proceed to checkout'))->setUrl( EShop_Pages::ShoppingCart()->getURL() )->setClass( UI_button::CLASS_SUCCESS )?>
</div>

<?=Application_Service_EShop::AnalyticsManager()?->addToCart( $item )?>