<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\UI;
use Jet\UI_dialog;

require 'add-note/js.phtml';

$dialog = UI::dialog('new-note-dialog', '', size: UI_dialog::SIZE_EXTRA_LARGE);

?>
<?=$dialog->start()?>
<div id="new-note-form">
	<?php
	require 'add-note/form.phtml';
	?>
</div>
<?=$dialog->end()?>