<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\Tr;
use Jet\UI;

$cash_desk = CashDesk::get();
?>
<br>
<span class="step-title"><?=Tr::_('Where should we send the goods?')?></span>

<div class="options" style="padding-top: 10px;padding-bottom: 10px;">
	<?php if($cash_desk->hasDifferentDeliveryAddress()): ?>
		<?=UI::button(Tr::_('To the same address'))->setOnclick('CashDesk.customer.deliveryAddress.setTheSame();')->setClass('light')?>
		<?=UI::button(Tr::_('To another address'))->setOnclick('CashDesk.customer.deliveryAddress.setDifferent();')->setClass('info')?>
	<?php else: ?>
		<?=UI::button(Tr::_('To the same address'))->setOnclick('CashDesk.customer.deliveryAddress.setTheSame();')->setClass('info')?>
		<?=UI::button(Tr::_('To another address'))->setOnclick('CashDesk.customer.deliveryAddress.setDifferent();')->setClass('light')?>
	<?php endif; ?>
</div>
