<?php
namespace JetShop;

$cash_desk = CashDesk::get();
?>


<form action="?action=delivery_address_confirm" method="post" id="cash_desk_delivery_address_form" name="cash_desk_delivery_address_form" onsubmit="CashDesk.customer.deliveryAddress.confirm();return false;">
	
	<div class="customer-delivery-register">
		<div class="heading">Kam máme zboží poslat?</div>
		
		<div class="inputs">
		</div>
	</div>
	
	<input type="submit" value="Pokračovat" class="btn right border_red color_white bg_red big" />
</form>
