<?php
namespace JetShop;

$cash_desk = CashDesk::get();

$delivery_address = $order->getDeliveryAddress();

$new_is_selected = 0==$delivery_address->getId();
$new_prefix = 'new_delivery';
?>


<form action="?action=delivery_address_confirm" method="post" id="cash_desk_delivery_address_form" name="cash_desk_delivery_address_form" onsubmit="CashDesk.customer.deliveryAddress.confirm();return false;">
	<div class="customer-delivery-registered">
		<div class="heading">Kam máme zboží poslat?</div>
		
		<?php foreach (Customer::getCurrentCustomer()->getAddressList() as $address): ?>
				
			<?php if ($address->getId() == $delivery_address->getId()): ?>
			
				<div class="address selected">
					<div class="row">
						<div class="select">
							<input type="radio" checked />
						</div>
						<div class="data">
							<?= $address->format() ?>

							<a href="#" onclick="CashDesk.customer.deliveryAddress.edit(<?= $address->getId() ?>);return false;">Upravit</a>
						</div>
					</div>
				</div>
				
			<?php else: ?>
			
				<div class="address" onclick="CashDesk.customer.deliveryAddress.select(<?= $address->getId() ?>)">
					<div class="row">
						<div class="select">
							<input type="radio" />
						</div>
						<div class="data">
							<?= $address->format() ?>

							<a href="#" onclick="CashDesk.customer.deliveryAddress.edit(<?= $address->getId() ?>);return false;">Upravit</a>
						</div>
					</div>
				</div>
				
			<?php endif; ?>
			
		<?php endforeach; ?>
		
		
		<?php if (!$delivery_address->getId()): ?>
			<?php
			CashDesk::setDeliveryAddressEditable( true );
			?>
			
			<div class="address selected">
				<div class="row">
					<div class="select">
						<input type="radio" checked />
					</div>
					<div class="new">
						<?= NEW_ADDRESS ?>
					</div>
				</div>

				<div class="inputs">
					<?= form::input($new_prefix.'_company', ENTRY_COMPANY, $delivery_address->getCompany())->setIsRequired(false) ?>
					<?= form::input($new_prefix.'_firstname', ENTRY_FIRST_NAME, $delivery_address->getFirstName()) ?>
					<?= form::input($new_prefix.'_lastname', ENTRY_LAST_NAME, $delivery_address->getLastName()) ?>
					<?= form::input($new_prefix.'_city', ENTRY_CITY, $delivery_address->getCity())->turnOffAutocomplete() ?>
					<?= form::input($new_prefix.'_postcode', ENTRY_POST_CODE, $delivery_address->getPostcode()) ?>
					<?= form::input($new_prefix.'_street_address', ENTRY_STREET_ADDRESS, $delivery_address->getStreetAddress())->turnOffAutocomplete() ?>
				</div>
			</div>
			
		<?php else: ?>
			<div class="address" onclick="CashDesk.customer.deliveryAddress.selectNew();">
				<div class="row">
					<div class="select">
						<input type="radio" name="select_delivery_address_id" value="0" />
					</div>
					<div class="new" onclick="CashDesk.customer.deliveryAddress.selectNew();">
						<?= NEW_ADDRESS ?>
					</div>
				</div>
			</div>
			
		<?php endif; ?>
		
	</div>
	
	<input type="submit" value="Pokračovat" class="btn right border_red color_white bg_red big" />
</form>
