<?php
namespace JetApplicationModule\Shop\CashDesk;


use Jet\Tr;
use Jet\UI;
use JetApplication\Customer;

$cash_desk = CashDesk::get();

$customer = Customer::getCurrentCustomer();
$delivery_address_hash = $cash_desk->getDeliveryAddress()->getHash();
?>
<div class="addresses">
<?php foreach( $customer->getAddresses() as $address): ?>
	<div class="<?=$delivery_address_hash==$address->getHash()?'address-selected':'address'?>" onclick="CashDesk.customer.deliveryAddress.select(<?=$address->getId()?>)">
		
		<?php if(
			$cash_desk->isCompanyOrder() &&
			$address->getCompanyName()
		): ?>
			<?=$address->getCompanyName()?><br>
		<?php endif?>

		<?=$address->getFirstName()?> <?=$address->getSurname()?><br>
		<?=$address->getAddressStreetNo()?><br/>
		<?=$address->getAddressZip()?> <?=$address->getAddressTown()?>

		<div class="continue-button-area">
			<?=UI::button(Tr::_('Select this address'))->setOnclick("CashDesk.customer.deliveryAddress.select({$address->getId()}")->setClass('link')?>
		</div>
	</div>
<?php endforeach; ?>
</div>
