<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Catalog;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Product_EShopData;

/**
 * @var MVC_View $this
 * @var Product_EShopData $product
 */

$product = $this->getRaw('product');

$categories = $product->getCategories();

if(!$categories) {
	return;
}

?>
<h3><?=Tr::_('Categories')?></h3>

<table class="table table-striped">
	<?php foreach($categories as $category): ?>
		<tr>
			<td>
				<a href="<?=$category->getURL()?>">
					<?=$category->getPathName()?>
				</a>
			</td>
		</tr>
	<?php endforeach; ?>
</table>
