<?php
namespace JetApplicationModule\Admin\Entity\Edit;

use Closure;
use Jet\Locale;
use Jet\UI_tabs;
use JetApplication\Admin_Managers;
use JetApplication\EShopEntity_Admin_WithEShopData_Interface;
use JetApplication\EShopEntity_WithEShopData;
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var EShopEntity_WithEShopData|EShopEntity_Admin_WithEShopData_Interface $item
 * @var Main $module
 * @var UI_tabs $tabs
 * @var Closure|null $eshop_data_fields_renderer
 * @var Closure|null $description_fields_renderer
 */
$form = $this->getRaw( 'form' );
$item = $this->getRaw( 'item' );
$tabs = $this->getRaw('tabs');

$module = $this->getRaw('module');

$eshop_data_fields_renderer = $this->getRaw('eshop_data_fields_renderer');
$description_fields_renderer = $this->getRaw('description_fields_renderer');

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 3,
	Form_Renderer::LJ_SIZE_LARGE => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 8,
	Form_Renderer::LJ_SIZE_LARGE => 8
] );

if($item->getId() && $item->isEditable()) {
	echo Admin_Managers::Image()->commonImageManager( $item::getEntityType(), $item->getId() );
}

?>
	
	<?php require 'toolbar.phtml'; ?>

	<div id="main-col">
		<?php
		if(count($tabs->getTabs())>1) {
			echo $tabs;
		}
		
		echo '<br>';
		
		echo $form->start();
		
		
		if( !$item->getDescriptionMode() ) {
			if($eshop_data_fields_renderer) {
				echo $module->renderShopDataBlocks(
					form: $form,
					renderer: function( EShop $eshop, string $eshop_key ) use ($item, $form, $eshop_data_fields_renderer ) : void {
						$eshop_data = $item->getEshopData( $eshop );
						
						$eshop_data_fields_renderer( $eshop, $eshop_key, $item, $form );
					});
			}
		} else {
			if($description_fields_renderer) {
				echo $module->renderDescriptionBlocks(
					form: $form,
					renderer: function( Locale $locale, string $locale_str ) use ($item, $form, $description_fields_renderer ) : void {
						$description_fields_renderer( $locale, $locale_str, $item, $form );
					});
				
			}
			
		}
		
		echo $form->end();
		?>
	</div>