<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Edit;


use Jet\MVC_View;
use JetApplication\EShopEntity_Admin_Interface;
use JetApplication\Application_Service_Admin;
use Jet\Form;
use JetApplication\Application_Service_Admin_EShopEntity_Edit;
use JetApplication\Product;

/**
 * @var MVC_View   $this
 * @var EShopEntity_Admin_Interface $item
 * @var Application_Service_Admin_EShopEntity_Edit $edit_manager
 * @var Form $form
 */

$item = $this->getRaw('item');
$edit_manager = $this->getRaw('edit_manager');
$form = $this->getRaw('filter_form');
$editable = $item->isEditable();

$p_manager = Application_Service_Admin::Product();

echo $edit_manager->renderToolbar( $form );

?>
<div id="main-col">
	<?=$this->getRaw('tabs')?>

	
	<br>
	<?=$form->start();?>
	<div class="card card-body">
		<?=Application_Service_Admin::ProductFilter()->renderFilterForm(); ?>
	</div>
	<?=$form->end();?>
	
	<br>

	<div class="card card-body">
	<table class="table table-striped">
		<?php foreach( $item->getProductIds() as $p_id):
			$product = Product::load( $p_id );
			if(!$product) {
				continue;
			}
			?>
			<tr>
				<td style="width: 200px;"><?=$p_manager->renderActiveState($product)?></td>
				<td><?=$p_manager->renderItemName($product)?></td>
			</tr>
		<?php endforeach; ?>
	</table>
	</div>


</div>