<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Edit;


use Jet\MVC_View;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View   $this
 */
?>

<?php require 'toolbar.phtml'; ?>

<div id="main-col">
	<?=$this->getRaw('tabs')?>
	
	<?=Admin_Managers::Image()->renderImageGalleryManagement();?>
</div>
