<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Edit;


use Jet\MVC_View;
use JetApplication\Application_Service_Admin;

/**
 * @var MVC_View   $this
 */
?>

<?php require 'toolbar.phtml'; ?>

<div id="main-col">
	<?php
	echo $this->getRaw('tabs');
	echo Application_Service_Admin::Image()->renderStandardManagement();
	?>
</div>

