<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Edit;


use Jet\Form_Field_WYSIWYG;
use Jet\Locale;
use Jet\UI_tabs;
use JetApplication\Admin_EntityManager_EditorPlugin;
use JetApplication\Admin_Managers;
use JetApplication\EShopEntity_Admin_WithEShopData_Interface;
use JetApplication\EShopEntity_Basic;
use JetApplication\EShopEntity_HasActivation_Interface;
use JetApplication\EShopEntity_HasTimer_Interface;
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var EShopEntity_Basic $item
 * @var Main $module
 * @var UI_tabs $tabs
 * @var Admin_EntityManager_EditorPlugin[]|null $plugins
 */
$form = $this->getRaw( 'form' );
$item = $this->getRaw( 'item' );
$tabs = $this->getRaw('tabs');

$module = $this->getRaw('module');

$common_data_fields_renderer = $this->getRaw('edit_common_data_fields_renderer');
$eshop_data_fields_renderer = $this->getRaw('edit_eshop_data_fields_renderer');
$description_fields_renderer = $this->getRaw('edit_description_fields_renderer');

$form->setAutocomplete( false );

$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 3,
	Form_Renderer::LJ_SIZE_LARGE => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 8,
	Form_Renderer::LJ_SIZE_LARGE => 8
] );

$has_wysiwyg_editor = false;
foreach($form->getFields() as $field) {
	if( $field instanceof Form_Field_WYSIWYG ) {
		$has_wysiwyg_editor = true;
	}
}

$plugins = $this->getRaw('plugins');
?>

<?php require 'toolbar.phtml'; ?>

<?php if( $has_wysiwyg_editor ) {
	echo Admin_Managers::EntityEdit()->renderEditorTools( $item );
} ?>

<div id="main-col">
		<?php
		if(count($tabs->getTabs())>1) {
			echo $tabs;
		}
		
		echo '<br>';
		
		if(
			$item instanceof EShopEntity_HasActivation_Interface
		) {
			echo $module->renderEntityActivation(
				entity: $item,
				editable: !$form->getIsReadonly(),
			);
		}
		
		if( $item instanceof EShopEntity_HasTimer_Interface ) {
			echo Admin_Managers::Timer()?->renderEntityEdit( $item, !$form->getIsReadonly() );
		}
		
		echo $form->start();
		
		echo $this->render('entity-form-common-fields');
		
		if($common_data_fields_renderer) {
			$common_data_fields_renderer( $item, $form );
		}
		
		if(
			$item instanceof EShopEntity_Admin_WithEShopData_Interface &&
			!$item->getSeparateTabFormShopData()
		) {
			if(!$item->getDescriptionMode()) {
				if($eshop_data_fields_renderer) {
					echo $module->renderShopDataBlocks(
						form: $form,
						renderer: function( EShop $eshop, string $eshop_key ) use ($item, $form, $eshop_data_fields_renderer ) : void {
							$eshop_data = $item->getEshopData( $eshop );
							
							$eshop_data_fields_renderer( $eshop, $eshop_key, $item, $form );
						});
				}
			} else {
				if($description_fields_renderer) {
					echo $module->renderDescriptionBlocks(
						form: $form,
						renderer: function( Locale $locale, string $locale_str ) use ($item, $form, $description_fields_renderer ) : void {
							$description_fields_renderer( $locale, $locale_str, $item, $form );
						});
					
				}
				
			}
			
			
		}
		
		echo $form->end();
		?>
</div>
<?php
echo Admin_Managers::Timer()?->renderIntegration();

if($plugins):
	foreach( $plugins as $handler):
		echo $handler->renderDialog();
	endforeach;
endif;