<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Edit;


use JetApplication\Admin_Managers_EShopEntity_Listing;
use JetApplication\EShopEntity_Basic;
use JetApplication\EShopEntity_HasURL_Interface;
use JetApplication\EShopEntity_WithEShopData;

use Jet\MVC_View;
use Jet\Form;
use Jet\UI;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var EShopEntity_Basic $item
 * @var Admin_Managers_EShopEntity_Listing $listing
 */
$form = $this->getRaw( 'form' );
$item = $this->getRaw( 'item' );

$toolbar_renderer = $this->getRaw('toolbar_renderer');
$listing = $this->getRaw('listing');

$prev_url = $listing?->getPrevEditUrl( $item->getId() );
$next_url = $listing?->getNextEditUrl( $item->getId() );

?>
<div class="toolbar" id="main-toolbar">

		<?=UI::button_goBack()?>
		
		<div style="display: inline-block;padding-left: 10px;padding-right: 10px;">
			<div style="width: 40px;display: inline-block;text-align: center">
			<?php if($prev_url): ?>
			<?=UI::button(' ')->setIcon('chevron-left')->setUrl($prev_url)?>
			<?php endif; ?>
			</div>
			
			<div style="width: 40px;display: inline-block;text-align: center">
			<?php if($next_url): ?>
			<?=UI::button(' ')->setIcon('chevron-right')->setUrl($next_url)?>
			<?php endif; ?>
			</div>
		</div>
		
		
		<?php if( $form && !$form->getIsReadonly() ): ?>
			<?=UI::button_save()->setOnclick("$('#".$form->getId()."').submit();")?>
			<?php
		endif;
		
		if( $item instanceof EShopEntity_HasURL_Interface || $item instanceof EShopEntity_WithEShopData ) {
			echo $this->render('preview-btn');
		}
		
		if($toolbar_renderer):
			$toolbar_renderer( $item, $form );
		endif;
		?>
</div>
