<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Stats\Orders;


use Jet\Data_DateTime;
use Jet\Http_Request;
use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\EShops;
use JetApplication\Statistics_Order;
use DateInterval;
use JetApplication\Order_Status;

/**
 * @var MVC_View   $this
 * @var Statistics_Order $stat
 * @var Statistics_Order[] $stats
 */

$stats = $this->getRaw('stats');
$stat = $this->getRaw('stat');

$results = $stat->getResults();

$default_result = $results[0];

unset($results[0]);


$day_map = $default_result->getDayMap();

$default_colspan = ((count($results)+1)*2);

$showHeader = function( $row_class='' ) use ($default_result, $results) {
		?>
		<th colspan="2" nowrap=""><?=$default_result->getTitle()?></th>
		<?php foreach($results as $result): ?>
			<th colspan="2" nowrap=""><?=$result->getTitle()?></th>
		<?php endforeach; ?>
		</tr>
		
		<tr class="<?=$row_class?>">
			<th><?=Tr::_('Count')?></th>
			<th><?=Tr::_('Value')?></th>
			
			<?php foreach($results as $stat): ?>
			<th><?=Tr::_('Count')?></th>
			<th><?=Tr::_('Value')?></th>
			<?php endforeach;

};

$showDayData = function( $y, $m, $d ) use ($stat, &$default_result, &$default_colspan, &$results) {
	$default_day = $default_result->getDayData($y, $m, $d);
	
	
	if(!$default_day):
		if($results):
			?><td colspan="<?=(1+$default_colspan);?>">&nbsp;&nbsp;</td><?php
		else:
			?><td colspan="<?=(1+$default_colspan);?>">&nbsp;&nbsp;</td><?php
		endif;
		return;
	endif;
	
	?>

	<td nowrap>
		<div style="display: grid;grid-template-columns: 40px 1fr; gap: 5px;align-items: center">
			<div style="font-size: 0.8rem"><?=$stat->getWeekDayName( $y, $m, $d )?></div>
			<div><?=$y?>-<?=$m?>-<?=$d?></div>
		</div>
	</td>
	<td nowrap><?=$default_day->getOrdersCount()?></td>
	<td nowrap><?=$default_day->getAmount();?></td>
	
	<?php foreach($results as $r ):
		$day = $r->getDayData( $y, $m, $d );
		$day->setRatioItem( $default_day );
		?>
		<td nowrap><?=$day->getOrdersCount()?></td>
		<td nowrap><?=$day->getAmount();?></td>
	
	<?php endforeach;
	
}
?>
	
<style>
	.disabled-day-row td {color:#aaa}
</style>


<div class="card card-body shadow" style="margin: 20px;">
	<div style="display: grid;grid-template-columns: 150px 1fr;gap: 20px;margin: 10px;align-items: center">
		<div><?=Tr::_('E-Shop:')?></div>
		<div style="display: flex;gap: 10px;align-items: center;flex-wrap: wrap;">
			<?php foreach(EShops::getListSorted() as $eshop):
				
				if($stat->getEshop()->getKey()==$eshop->getKey()):
					?><div class="btn btn-success"><?=$eshop->getName()?></div><?php
				else:
					?><a href="<?=Http_Request::currentURI(['eshop'=>$eshop->getKey()])?>" class="btn btn-secondary"><?=$eshop->getName()?></a><?php
				endif;
			endforeach; ?>
		</div>

		<div><?=Tr::_('Statistic:')?></div>
		<div style="display: flex;gap: 10px;align-items: center;flex-wrap: wrap;">
			<?php foreach($stats as $key=>$s): ?>
				<?php if($s->getIsSelected()): ?>
					<strong style="margin-right: 20px;" class="btn btn-success"><?=$s->getTitle()?></strong>
				<?php else: ?>
					<a href="<?=Http_Request::currentURI([ 'stat' => $key ])?>" style="margin-right: 20px;" class="btn btn-secondary"><?=$s->getTitle()?></a>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>
	</div>

	<form method="get">
		<input type="hidden" name="eshop" value="<?=$stat->getEshop()->getKey()?>">
		<input type="hidden" name="stat" value="<?=$stat->getKey()?>">

		<div style="display: grid;grid-template-columns: 150px 1fr;gap: 20px;margin: 10px;align-items: center">

			<div><?=Tr::_( 'Time period:' )?></div>
			<div style="display: flex;align-items: center;gap: 10px;">
				<div><?=Tr::_('From year:')?></div>
				<div>
					<input type="number" name="start_year" value="<?=$stat->getStartYear()?>" class="form-control" style="width: 100px"/>
				</div>
				<div><?=Tr::_('To year:')?></div>
				<div>
					<input type="number" name="end_year" value="<?=$stat->getEndYear()?>" class="form-control" style="width: 100px"/>
				</div>

			</div>

			<div><?=Tr::_( 'Show days:' )?></div>
			<div>
				<select name="display_days" class="form-control" style="width: 100px">
					<option value="0" <?=(!$stat->getDisplayDays()?' selected':'')?>><?=Tr::_('No')?></option>
					<option value="1" <?=($stat->getDisplayDays()?' selected':'')?>><?=Tr::_('Yes')?></option>
				</select>
			</div>

			<div></div>
			<div>
				<?=$stat->renderDetailFilterForm();?>
			</div>

			<div><?=Tr::_('Order status:')?></div>
			<div style="display: grid;grid-template-columns: repeat(auto-fill, 300px)">
				<?php
				$default_day =0;
				foreach(Order_Status::getList() as $key=>$status):
					if($default_day==5) {
						echo '</tr><tr>';
						$default_day=0;
					}
					$default_day++;
					?>
					<div style="display: grid;grid-template-columns: 20px 1fr;gap: 5px;align-items: center;margin: 5px;">
						<div>
							<input type="checkbox" name="status[]" value="<?=$key?>" id="status_<?=$key?>" <?=(in_array($key, array_keys($stat->getOrderStatuses()) )?' checked="checked"':'')?> class="checkbox"/>
						</div>
						<div>
							<label for="status_<?=$key?>" style="font-weight: normal;padding: 0px;margin: 0px;"><?=$status->getTitle()?></label>
						</div>

					</div>
				
				<?php endforeach; ?>
			</div>

			<div></div>
			<div>
				<?=UI::button(Tr::_('Setup statistic'))->setClass(UI_button::CLASS_PRIMARY)->setType(UI_button::TYPE_SUBMIT)?>
			</div>
		</div>


	</form>
	
</div>


<div style="padding-top: 50px">
	<table>
		<tr>
			<?php foreach($day_map as $y=> $months ):
				$default_year = $default_result->getYearData($y);
				$default_period = $default_result->getCompletedPartOfYear($y);
				
				?>
				<td valign="top">
					<div style="margin-left: 5px;margin-right: 5px;">
						<table border="1" cellspacing="0" cellpadding="3" class="table table-striped">
							<thead>
							<tr>
								<th colspan="<?=(1+$default_colspan);?>"><?=$y?></th>
							</tr>
							<tr>
								<th rowspan="2"><?=Tr::_('Date')?></th>
								
								<?php $showHeader() ?>
							</tr>
							</thead>
							<tbody>
							<?php foreach( $months as $m=>$days ):
								$default_month = $default_result->getMonthData($y, $m);
								
								if($stat->getDisplayDays()):
									$weeks_count = 0;
									$start_week_day = $stat->getWeekDayNo($y, $m, 1);
									
									$days_back_count = $start_week_day;
									
									$correction_start_date = new Data_DateTime($y.'-'.$m.'-1');
									$correction_start_date->sub( new DateInterval('P'.$days_back_count.'D') );
									
									$skip_days = 0;
									
									if($start_week_day<5) {
										for( $correction=0;$correction<$start_week_day;$correction++ ) {
											if($correction==0) {
												$weeks_count++;
											}
											?>
											<tr class="day-row disabled-day-row">
												<?php $showDayData( (int)$correction_start_date->format('Y'), (int)$correction_start_date->format('m'), (int)$correction_start_date->format('d') ); ?>
											</tr>
											<?php
											
											$correction_start_date->add( new DateInterval('P1D') );
										}
									} else {
										$skip_days = 7-$start_week_day;
									}
									
									
									$d = '1';
									foreach($days as $d ):
										if($skip_days) {
											$skip_days--;
											continue;
										}
										
										$week_day = $stat->getWeekDayNo($y, $m, $d);
										if($week_day==0) {
											$weeks_count++;
										}
										
										?>
										<tr class="day-row" id="<?=($d==1)?$y.'-'.$m:''?>">
											<?php $showDayData( $y, $m, $d ); ?>
										</tr>
									<?php
									endforeach;
									
									$last_date = new Data_DateTime( $y.'-'.$m.'-'.$d );
									$end_week_day = $stat->getWeekDayNo( $y, $m, $d )+1;
									if($end_week_day==7) {
										$end_week_day = 0;
									}
									
									for( $correction=$end_week_day;$correction<=6;$correction++ ) {
										if($correction==0) {
											$weeks_count++;
										}
										
										$last_date->add( new DateInterval('P1D') );
										
										?>
										<tr class="day-row disabled-day-row">
											<?php $showDayData( (int)$last_date->format('Y'), (int)$last_date->format('m'), (int)$last_date->format('d') ); ?>
										</tr>
										<?php
									}
									
									$weeks_correction = 6-$weeks_count;
									
									
									for( $correction=0;$correction<$weeks_correction;$correction++ ) {
										for($d=0;$d<=6;$d++) {
											$last_date->add( new DateInterval('P1D') );
											?>
											<tr class="day-row disabled-day-row">
												<?php $showDayData( (int)$last_date->format('Y'), (int)$last_date->format('m'), (int)$last_date->format('d') ); ?>
											</tr>
											<?php
										}
										
									}
								
								endif;
								?>

								<tr class="table-info">
									<td nowrap style="font-weight: bolder;" rowspan="8"><?=$y?>-<?=$m?></td>
									<?php $showHeader( 'table-info' ) ?>
								</tr>
								<tr class="table-info">
									<td nowrap style="font-weight: bolder;" colspan="<?=$default_colspan;?>"><?=Tr::_('Total for the month:')?></td>
								</tr>
								<tr class="table-info">
									<td nowrap><?=$default_month->getOrdersCount()?></td>
									<td nowrap><?=$default_month->getAmount()?></td>
									
									<?php foreach($results as $r ):
										$month = $r->getMonthData( $y, $m );
										$month->setRatioItem( $default_month );
										?>
										<td nowrap><?=$month->getOrdersCount()?><br/>(<?=$month->getOrdersCountRatio()?>%)</td>
										<td nowrap><?=$month->getAmount();?><br/>(<?=$month->getAmountRatio();?>%)</td>
									<?php endforeach; ?>
								</tr>
								<tr class="table-info">
									<td nowrap style="font-weight: bolder;" colspan="<?=(1+$default_colspan);?>"><?=Tr::_('Daily average in a month:')?></td>
								</tr>
								<tr class="table-info">
									<td nowrap><?=$default_month->getAverageOrdersCount()?></td>
									<td nowrap><?=$default_month->getAverageAmount()?></td>
									
									<?php foreach($results as $r ):
										$month = $r->getMonthData( $y, $m );
										?>
										<td nowrap><?=$month->getAverageOrdersCount()?></td>
										<td nowrap><?=$month->getAverageAmount();?></td>
									<?php endforeach; ?>
								</tr>
								<tr class="table-info">
									<td colspan="<?=($default_colspan)?>" style="font-weight: bolder;"><?=Tr::_('Average order value:')?></td>
								</tr>
								<tr class="table-info">
									<td colspan="2">
										<?php if($default_month->getOrdersCount()>0): ?>
											<?=Locale::float($default_month->getAmount(false)/$default_month->getOrdersCount(false))?>
										<?php else: ?>
											&nbsp;&nbsp;
										<?php endif; ?>
									</td>
									
									<?php foreach($results as $r ):
										$month = $r->getMonthData( $y, $m );
										?>
										<td colspan="2">
											<?php if($month->getOrdersCount()>0): ?>
												<?=Locale::float($month->getAmount(false)/$month->getOrdersCount(false))?>
											<?php else: ?>
												&nbsp;&nbsp;
											<?php endif; ?>
										</td>
									<?php endforeach; ?>

								</tr>
								<tr>
									<td colspan="<?=($default_colspan+1)?>"></td>
								</tr>
							<?php endforeach; ?>
							
							<tr class="table-success">
								<td nowrap style="font-weight: bolder;" rowspan="6"><?=$y?></td>
								<?php $showHeader( 'table-success' ) ?>
							</tr>
							<tr class="table-success">
								<td colspan="<?=($default_colspan);?>" nowrap="" style="font-weight: bolder;">Celkem za rok:</td>
							</tr>
							<tr class="table-success">
								<td nowrap><?=$default_year->getOrdersCount()?></td>
								<td nowrap><?=$default_year->getAmount()?></td>
								
								
								<?php foreach($results as $r ):
									$year = $r->getYearData( $y );
									$year->setRatioItem( $default_year );
									?>
									<td nowrap><?=$year->getOrdersCount()?><br/>(<?=$year->getOrdersCountRatio()?>%)</td>
									<td nowrap><?=$year->getAmount();?><br/>(<?=$year->getAmountRatio();?>%)</td>
								<?php endforeach; ?>

							</tr>
							<tr class="table-success">
								<td colspan="<?=($default_colspan);?>" nowrap="" style="font-weight: bolder;">Denní průměr v roce:</td>
							</tr>
							<tr class="table-success">
								<td nowrap><?=$default_year->getAverageOrdersCount()?></td>
								<td nowrap><?=$default_year->getAverageAmount()?></td>
								
								
								<?php foreach($results as $r ):
									$year = $r->getYearData( $y );
									?>
									<td nowrap><?=$year->getAverageOrdersCount()?></td>
									<td nowrap><?=$year->getAverageAmount();?></td>
								<?php endforeach; ?>
							</tr>
							
							
							<?php if(
								$default_result->getCurrentMonth()>1 &&
								$default_result->getStartYear()!=$default_result->getEndYear()
							): ?>
								<tr>
									<td colspan="<?=($default_colspan+1)?>"></td>
								</tr>
								<tr class="table-danger">
									<td nowrap style="font-weight: bolder;" rowspan="6"><?=$y?> 1-<?=($default_result->getCurrentMonth()-1)?></td>
									<?php $showHeader( 'table-danger' ) ?>
								</tr>
								<tr class="table-danger">
									<td colspan="<?=($default_colspan);?>" nowrap="" style="font-weight: bolder;">Celkem za období:</td>
								</tr>
								<tr class="table-danger">
									<td nowrap><?=$default_period->getOrdersCount()?></td>
									<td nowrap><?=$default_period->getAmount()?></td>
									
									
									<?php foreach($results as $r ):
										$period = $r->getCompletedPartOfYear( $y );
										$period->setRatioItem( $default_year );
										?>
										<td nowrap><?=$period->getOrdersCount()?><br/>(<?=$period->getOrdersCountRatio()?>%)</td>
										<td nowrap><?=$period->getAmount();?><br/>(<?=$period->getAmountRatio();?>%)</td>
									<?php endforeach; ?>

								</tr>
								<tr class="table-danger">
									<td colspan="<?=($default_colspan);?>" nowrap="" style="font-weight: bolder;">Denní průměr za období:</td>
								</tr>
								<tr class="table-danger">
									<td nowrap><?=$default_period->getAverageOrdersCount()?></td>
									<td nowrap><?=$default_period->getAverageAmount()?></td>
									
									
									<?php foreach($results as $r ):
										$period = $r->getCompletedPartOfYear( $y );
										?>
										<td nowrap><?=$period->getAverageOrdersCount()?></td>
										<td nowrap><?=$period->getAverageAmount();?></td>
									<?php endforeach; ?>
								</tr>
							
							<?php endif; ?>
							
							</tbody>
						</table>
					</div>
				</td>
			<?php endforeach; ?>
		</tr>
	</table>

</div>

<script type="text/javascript">
	const d = new Date();
	const id = d.getFullYear() + '-' + (d.getMonth() + 1);

	document.getElementById(id).scrollIntoView({behavior:'smooth'});
</script>
