<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\ProductReviews;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;use JetApplication\Product_EShopData;


/**
 * @var MVC_View   $this
 * @var CustomerReviewManager $manager
 */

$manager = $this->getRaw('manager');

$pwp = $manager->getPossibleProducts();
$reviews = $manager->getCustomersReviews();
?>

<?php if($pwp): ?>
	<h4><?=Tr::_('Write review')?></h4>
	
	<?php foreach($manager->getPossibleProducts() as $p): ?>
		<div class="card product-write-review">
			<div>
				<?php if($p->getImage(0)): ?>
					<a href="<?=$p->getURL()?>"><img src="<?=$p->getImageThumbnailUrl(0, 200, 200)?>"></a>
				<?php endif; ?>
			</div>
			<div>
				<a href="<?=$p->getURL()?>"><b><?=$p->getName()?></b></a>
				<br>
				<?=UI::button( Tr::_('Write review') )
					->setUrl(Http_Request::currentURI(set_GET_params: ['write_review'=>$p->getId()]))
					->setClass(UI_button::CLASS_SUCCESS)
				?>
			</div>
		</div>
	<?php endforeach; ?>

<?php endif; ?>

<?php if(count($reviews)): ?>

<h4><?=Tr::_('Reviews')?></h4>
	<?php foreach($reviews as $review):
	
		$p = Product_EShopData::get( $review->getProductId() );
		if(!$p) {
			continue;
		}
		
		$this->setVar('review', $review);
		?>
		<div class="product-review-product">
			<div>
				<?php if($p->getImage(0)): ?>
					<a href="<?=$p->getURL()?>"><img src="<?=$p->getImageThumbnailUrl(0, 100, 100)?>"></a>
				<?php endif; ?>
			</div>
			<div>
				<a href="<?=$p->getURL()?>"><b><?=$p->getName()?></b></a>
			</div>
		</div>
	
		<?=$this->render('product-reviews/item');?>
		
	<?php endforeach; ?>

<?php endif; ?>
