<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\ProductReviews;


use Jet\MVC_View;
use JetApplication\Product_EShopData;
use JetApplication\ProductReview;

/**
 * @var MVC_View   $this
 * @var Product_EShopData $product
 */
$product = $this->getRaw('product');

$reviews = ProductReview::getReviews($product);
?>
<div id="product_reviews">
<?php foreach($reviews as $review):
	$this->setVar('review', $review);
	echo $this->render('product-reviews/item');
endforeach;
?>
</div>
