<?php
namespace JetApplicationModule\Admin\Entity\Listing;

use Jet\UI;
use Jet\UI_button;

use Jet\MVC_View;
use JetApplication\Admin_Entity_WithShopData_Interface;
use JetApplication\Admin_Managers;
use JetApplication\Entity_WithShopData;

/**
 * @var MVC_View $this
 * @var Entity_WithShopData|Admin_Entity_WithShopData_Interface $item
 * @var Listing $listing
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');

if( $listing->getEntityManager()::getCurrentUserCanDelete() ):
	
	$delete_uri_creator = Admin_Managers::EntityListing()->getDeleteUriCreator();

	$delete_uri = $delete_uri_creator( $item->getId() );
	echo UI::button_delete(' ')
		->setUrl( $delete_uri )
		->setSize( UI_button::SIZE_EXTRA_SMALL)
		->addCustomCssStyle("margin-right:5px;");
endif;

