<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Entity\Listing;


use Jet\UI;
use Jet\UI_button;

use Jet\MVC_View;
use JetApplication\EShopEntity_Admin_Interface;
use JetApplication\Admin_Managers;
use JetApplication\EShopEntity_WithEShopData;

/**
 * @var MVC_View $this
 * @var EShopEntity_WithEShopData|EShopEntity_Admin_Interface $item
 * @var Listing $listing
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');

if( $listing->getEntityManager()::getCurrentUserCanDelete() ):
	
	$delete_uri_creator = Admin_Managers::EntityListing()->getDeleteUriCreator();

	$delete_uri = $delete_uri_creator( $item->getId() );
	echo UI::button_delete(' ')
		->setUrl( $delete_uri )
		->setSize( UI_button::SIZE_EXTRA_SMALL)
		->addCustomCssStyle("margin-right:5px;");
endif;

