<?php
namespace JetApplicationModule\Admin\Entity\Listing;

use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Entity_Admin_Interface;
use JetApplication\Admin_Managers;
use JetApplication\Entity_WithEShopData;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 * @var Entity_WithEShopData|Entity_Admin_Interface $item
 * @var Listing_Column_ActiveState $col
 */

$col = $this->getRaw('column');
$item = $this->getRaw('item');

if($item->isActive()):
	?><span class="badge badge-success"> <?=Tr::_('Active', dictionary: Admin_Managers::EntityListing()->getModuleManifest()->getName())?> </span> <?php
else:
	?><span class="badge badge-danger"><?=Tr::_('Inactive', dictionary: Admin_Managers::EntityListing()->getModuleManifest()->getName())?></span> <?php
endif;

if($col->isMultiEShopMode()):
	foreach( EShops::getListSorted() as $eshop):
		if($item->getEshopData($eshop)->isActiveForShop()):
			?><span class="badge badge-success"><?=$eshop->getName()?></span> <?php
		else:
			?><span class="badge badge-danger"><?=$eshop->getName()?></span> <?php
		endif;
	endforeach;
endif;