<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Listing;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\EShopEntity_Admin_Interface;
use JetApplication\EShopEntity_WithEShopData;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 * @var EShopEntity_WithEShopData|EShopEntity_Admin_Interface $item
 * @var Listing_Column_ActiveState $col
 */

$col = $this->getRaw('column');
$item = $this->getRaw('item');

if($item->isActive()):
	?><span class="badge badge-success" style="padding: 5px;"> <?=Tr::_('Active', dictionary: Tr::COMMON_DICTIONARY)?> </span> <?php
else:
	?><span class="badge badge-danger" style="padding: 5px;"><?=Tr::_('Inactive', dictionary: Tr::COMMON_DICTIONARY)?></span> <?php
endif;

?><br><?php

if($col->isMultiEShopMode()):
	foreach( EShops::getListSorted() as $eshop):
		if($item->getEshopData($eshop)->isActiveForShop()):
			?><span class="badge badge-success" style="font-size: 0.6rem;padding: 4px;"><?=$eshop->getName()?></span> <?php
		else:
			?><span class="badge badge-danger" style="font-size: 0.6rem;padding: 4px;"><?=$eshop->getName()?></span> <?php
		endif;
	endforeach;
endif;