<?php
namespace JetApplicationModule\Admin\Entity\Listing;

use Jet\MVC_View;
use JetApplication\Admin_Entity_Common_Interface;
use JetApplication\Entity_WithEShopRelation;

/**
 * @var MVC_View $this
 * @var Listing $listing;
 * @var Entity_WithEShopRelation|Admin_Entity_Common_Interface $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=$item->getEshop()->getName();?></a>
<?php
