<?php
namespace JetApplicationModule\Admin\Entity\Listing;

use Jet\MVC_View;
use JetApplication\EShopEntity_Admin_Interface;
use JetApplication\EShopEntity_WithEShopData;

/**
 * @var MVC_View $this
 * @var Listing $listing
 * @var EShopEntity_WithEShopData|EShopEntity_Admin_Interface $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=$item->getId();?></a>
<?php
