<?php
namespace JetApplicationModule\Admin\Entity\Listing;

use Jet\MVC_View;
use JetApplication\Admin_Entity_WithShopData_Interface;
use JetApplication\Entity_WithShopData;

/**
 * @var MVC_View $this
 * @var Listing $listing;
 * @var Entity_WithShopData|Admin_Entity_WithShopData_Interface $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=$item->getInternalName();?></a>
<?php
