<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Properties;


use Jet\MVC_View;
use JetApplication\EShopEntity_Admin_Interface;
use JetApplication\EShopEntity_WithEShopData;

/**
 * @var MVC_View $this
 * @var EShopEntity_WithEShopData|EShopEntity_Admin_Interface $item
 */
$item = $this->getRaw('item');
?>
<?= nl2br($item->getInternalNotes()); ?>
