<?php
namespace JetApplicationModule\Admin\Entity\Listing;

use Jet\MVC_View;
use JetApplication\Entity_Admin_Interface;
use JetApplication\Entity_WithEShopData;

/**
 * @var MVC_View $this
 * @var Listing $listing;
 * @var Entity_WithEShopData|Entity_Admin_Interface $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=$item->getInternalCode();?></a>
<?php
