<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Listing;

use Jet\MVC_View;
use JetApplication\EShopEntity_HasNumberSeries_Interface;

/**
 * @var MVC_View $this
 * @var Listing $listing
 * @var EShopEntity_HasNumberSeries_Interface $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=$item->getNumber();?></a>
<?php
