<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Listing;

use Jet\MVC_View;
use JetApplication\EShopEntity_HasStatus_Interface;

/**
 * @var MVC_View $this
 * @var EShopEntity_HasStatus_Interface $item
 */

$item = $this->getRaw('item');

echo $item->getStatus()->showAdmin();
