<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Listing;


use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\EShopEntity_HasActivationByTimePlan_Interface;

/**
 * @var MVC_View $this
 * @var EShopEntity_HasActivationByTimePlan_Interface $item
 */

$item = $this->getRaw('item');


if($item->isActiveByTimePlan()) {
	$class = 'active';
} else {
	if($item->isWaitingByTimePlan()) {
		$class = 'waiting';
	} else {
		$class = 'expired';
	}
}


if(!$item->getActiveFrom()):
	?>
	<div class="time-interval time-interval-<?=$class?>"><?=Tr::_('Unlimited', dictionary: Tr::COMMON_DICTIONARY)?></div>
	<?php
	return;
endif;
?>
<div class="time-interval time-interval-<?=$class?>"><?=Locale::dateAndTime( $item->getActiveFrom() )?></div>
<?php
