<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Application_Service_Admin;
use JetApplication\Accessories_Group;

/**
 * @var MVC_View $this
 * @var Accessories_Group $group
 */
$group = $this->getRaw('item');

$p_manager = Application_Service_Admin::Product();


foreach($group->getProducts() as $p): ?>
	<div
		class="product"
		style="border: 1px solid #c9c9c9;border-radius: 5px;background-color:#ffffff;display: grid;grid-template-columns: 20px 1fr 30px;gap: 20px;align-items: center;margin: 10px;padding: 10px;"
		data-id="<?=$p->getProductId()?>"
	>
		<div><?=UI::icon('up-down')?></div>
		<div><?=$p_manager->renderItemName( $p->getProductId() )?></div>
		<div><?= UI::button_delete(' ')->setOnClick("Products.remove({$p->getProductId()})")->setSize( UI_button::SIZE_EXTRA_SMALL)?></div>
	</div>
<?php endforeach;

