<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\Catalog;


use Jet\MVC_View;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Brand_EShopData;
use JetApplication\ProductListing;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');


$filter = $listing->getFilter()->getBrandsFilter();
if(!$filter->getIsActive()) {
	return;
}

$brand_ids = $filter->getSelectedBrandIds();


$brands = Brand_EShopData::getActiveList( $brand_ids );

foreach($brands as $brand):

	echo UI::button( $brand->getName() )
		->setClass(UI_button::CLASS_INFO)
		->setIcon('circle-xmark')
		->setOnClick("listing.filter.brands.cancel({$brand->getId()})");

endforeach;
