<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Catalog;


use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\ProductListing;
use JetApplication\Property_Options_Option_EShopData;
use JetApplication\Property_EShopData;


/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');


$option_filter = $listing->getFilter()->getPropertyOptionsFilter();
$number_filter = $listing->getFilter()->getPropertyNumberFilter();
$bool_filter = $listing->getFilter()->getPropertyBoolFilter();

$property_ids = array_merge(
	array_keys( $option_filter->getSelectedOptionIds( true ) ),
	array_keys( $number_filter->getPropertyRules() ),
	array_keys( $bool_filter->getPropertyRules() )
);


$properties = Property_EShopData::getActiveList($property_ids );

if($option_filter->getIsActive()):
	$all_selected = $option_filter->getSelectedOptionIds( false );
	$selected = $option_filter->getSelectedOptionIds( true );
	
	$options = Property_Options_Option_EShopData::getActiveList( $all_selected, order_by: ['priority'] );

	foreach($selected as $property_id=>$o):
		foreach($o as $option_id):
			/**
			 * @var Property_EShopData $property
			 * @var Property_Options_Option_EShopData $option
			 */
			$property = $properties[$property_id]??null;
			$option = $options[$option_id]??null;
			
			if(!$property||!$option) {
				continue;
			}
			
			echo UI::button( $property->getLabel().': '.$option->getFilterLabel().' '.$property->getUnits() )
				->setClass(UI_button::CLASS_INFO)
				->setIcon('circle-xmark')
				->setOnClick("listing.filter.options.cancel({$option_id})");
			
		endforeach;
	endforeach;
endif;

if($number_filter->getIsActive()):
	foreach($number_filter->getPropertyRules() as $property_id=>$rule):
		$property = $properties[$property_id]??null;
		if(!$property) {
			continue;
		}
	
		$min = $number_filter->getPropertyRuleMin( $property_id );
		$max = $number_filter->getPropertyRuleMax( $property_id );
	
		$min = $min?:$listing->getNumberMin($property_id);
		$max = $max?:$listing->getNumberMax($property_id);
		
		if(is_float($min)) {
			$min = Locale::float($min);
		} else {
			$min = Locale::int($min);
		}
		
		if(is_float($max)) {
			$max = Locale::float($max);
		} else {
			$max = Locale::int($max);
		}
		
		echo UI::button( $property->getLabel().': '.$min.' - '.$max.' '.$property->getUnits() )
			->setClass(UI_button::CLASS_INFO)
			->setIcon('circle-xmark')
			->setOnClick("listing.filter.numbers.cancel({$property_id})");
		
	endforeach;
endif;

if($bool_filter->getIsActive()):
	$rules = $bool_filter->getPropertyRules();

	foreach($rules as $property_id=>$rule):
		$property = $properties[$property_id]??null;
		if(!$property) {
			continue;
		}
		
		if(!$rule) {
			continue;
		}
		
		$label = $property->getBoolYesDescription() ? : Tr::_('yes');
		
		echo UI::button( $property->getLabel().': '.$label )
			->setClass(UI_button::CLASS_INFO)
			->setIcon('circle-xmark')
			->setOnClick("listing.filter.bool.cancel({$property_id})");
		
	
	endforeach;
endif;