<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Marketing\CategoryBanners;


use JetApplication\Application_Service_Admin;

use Jet\MVC_View;
use JetApplication\Marketing_CategoryBanner;

/**
 * @var MVC_View $this
 * @var Marketing_CategoryBanner   $item
 */
$item = $this->getRaw( 'item' );

foreach($item->getCategoryIds() as $category) {
	echo Application_Service_Admin::Category()->renderItemName( $category ).'<br>';
}