<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\Form;
use JetApplication\Application_Service_Admin;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Form     $form
 */

$form = $this->getRaw('form');

?>
	<div class="row form-group">
		<label class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?= Tr::_('Gift:')?></label>
		<div class="col-md-8" style="padding-bottom: 10px">
			<?=Application_Service_Admin::Product()->renderSelectWidget(
				"$('#{$form->field('gift_product_id')->getId()}').val(selected_item.id)",
				selected_product_id: 0
			);?>
		</div>
	</div>
<?php
echo $form->field( 'gift_product_id' );
echo $form->field( 'priority' );
echo $form->field( 'relevance_mode' );
echo $form->field( 'product_price_limit_min' );
echo $form->field( 'product_price_limit_max' );
echo $form->field( 'in_stock_limit' );
echo $form->field( 'only_one' );

