<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\ControlCentre;


use Jet\Application_Module;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_icon;
use JetApplication\Admin_ControlCentre;
use JetApplication\Admin_ControlCentre_Module_Interface;
use JetApplication\EShops;
use JetApplication\EShop;

/**
 * @var MVC_View   $this
 * @var Admin_ControlCentre_Module_Interface|Application_Module|null $selected_module
 * @var EShop $selected_eshop
 */

$selected_module = $this->getRaw( 'selected_module' );
$selected_eshop = $this->getRaw( 'selected_eshop' );

$selected_module_name = $selected_module?->getModuleManifest()->getName();

$groups = [
	Admin_ControlCentre::GROUP_MAIN                     => Tr::_('Main'),
	Admin_ControlCentre::GROUP_EXPORTS                  => Tr::_('Exports'),
	Admin_ControlCentre::GROUP_ANALYTICS                => Tr::_('Analytics'),
	Admin_ControlCentre::GROUP_PAYMENT                  => Tr::_('Payment'),
	Admin_ControlCentre::GROUP_DELIVERY                 => Tr::_('Delivery'),
	Admin_ControlCentre::GROUP_MARKET_PLACE_INTEGRATION => Tr::_('Market place integration'),
	Admin_ControlCentre::GROUP_SYSTEM                   => Tr::_('System'),
];


$modules = [];
foreach($groups as $group=>$group_title):
		$modules[$group] = [];
		
		foreach(Admin_ControlCentre::getModuleList() as $module_name=>$module):
			if($module->getControlCentreGroup()==$group) {
				$modules[$group][$module_name] = $module;
			}
		endforeach;
endforeach;
?>
<style>
	.module-list {
		background-color: #eeeeee;
	}
	
	.search {
		background-color: #eeeeee;
	}

	.module-list-item {
		margin: 10px;
		border: 1px solid #c2c2c2;
		border-radius: 5px;
		padding: 10px;
	}
	
	
	.module-list-item-selected {
		margin: 10px;
		border-left: 1px solid #999999;
		border-top: 1px solid #999999;
		border-bottom: 1px solid #999999;
		border-top-left-radius: 5px;
		border-bottom-left-radius: 5px;
		padding: 10px;
		font-weight: bolder;
		position: relative;
		left: 11px;
		background-image: linear-gradient(90deg, #f9f9f9 10%, #ffffff 90%);
	}
	
	.signpost {
		display:grid;
		grid-template-columns: repeat(8, 1fr);
		gap: 20px;
		align-items: center;
		margin-left: 20px;
		margin-right: 20px;
	}
	
	.signpost-title {
		margin-left: 20px;
		margin-right: 20px;
	}

	.signpost-item {
		margin: 10px;
		border: 1px solid #c2c2c2;
		border-radius: 5px;
		padding: 10px;
		text-align: center;
		color: #2b2b2b;
	}
	
	.signpost-item a {
		color: #2b2b2b;
	}
	
	.shop-select {
		display: flex;
		gap: 0px;
		background-color: #eeeeee;
	}
	
	.shop-select-item-selected {
		background-color: #ffffff;
		padding: 10px;
		margin-left: 5px;
		margin-right: 5px;
		border-left: 1px solid #666666;
		border-top: 1px solid #666666;
		border-right: 1px solid #666666;
		position: relative;
		top: 1px;
	}
	
	.shop-select-item {
		background-color: #f8f8f8;
		padding: 10px;
		margin-left: 5px;
		margin-right: 5px;
	}
	
</style>

<?php if($selected_module): ?>
<div style="display: grid;grid-template-columns: 1fr 3fr;grid-template-rows: 40px 1fr;height: 100%">
	
	<div class="search"></div>

	<div class="shop-select">
		<?php if($selected_module->getControlCentrePerShopMode() && EShops::isMultiEShopMode() ):
			foreach( EShops::getList() as $eshop):
				if($eshop->getKey()==$selected_eshop->getKey()): ?>
					<div class="shop-select-item-selected">
						<?=UI::flag( $eshop->getLocale() )?>
						<?=$eshop->getName()?>
					</div>
				<?php else: ?>
					<div class="shop-select-item">
						<a href="<?=Http_Request::currentURI(['eshop'=>$eshop->getKey()])?>">
							<?=UI::flag( $eshop->getLocale() )?>
							<?=$eshop->getName()?>
						</a>
					</div>
				<?php endif;
			endforeach;
		endif; ?>
	</div>
	
	
	<div class="module-list">
		<div class="signpost-title">
			<h4><?=$groups[$selected_module->getControlCentreGroup()]?></h4>
			<hr>
		</div>
		<?php foreach($modules[$selected_module->getControlCentreGroup()] as $module_name=>$module): ?>
		<?php if($selected_module_name==$module_name): ?>
				<div class="module-list-item-selected">
					<?=UI::icon( $module->getControlCentreIcon()) ?>
					<b><?=$module->getControlCentreTitleTranslated()?></b>
				</div>
		<?php else: ?>
				<div class="module-list-item">
					<a href="<?=Http_Request::currentURI(['id'=>$module_name])?>"><?=UI::icon( $module->getControlCentreIcon()) ?></a>
					<a href="<?=Http_Request::currentURI(['id'=>$module_name])?>"><?=$module->getControlCentreTitleTranslated()?></a>
				</div>
		<?php endif; ?>
		<?php endforeach; ?>
	</div>

	
	<div style="padding: 20px;border: 1px solid #999999">
		<h2><?=UI::icon( $selected_module->getControlCentreIcon())->setSize(UI_icon::SIZE_EXTRA_LARGE) ?> <?=$selected_module->getControlCentreTitleTranslated()?></h2>
		<hr>
		<?=$selected_module->handleControlCentre( $selected_eshop )?>
	</div>
</div>
<?php else: ?>
<br>
<?php foreach($groups as $group=>$group_title):
		if(!$modules[$group]) {
			continue;
		}
		?>
		<div class="signpost-title">
		<h4><?=$group_title?></h4>
		<hr>
		</div>
		<div class="signpost">
			<?php foreach($modules[$group] as $module_name=>$module): ?>
				<div class="signpost-item">
					<a href="<?=Http_Request::currentURI(['id'=>$module_name])?>"><?=UI::icon( $module->getControlCentreIcon())->setSize(UI_icon::SIZE_LARGE) ?></a>
					<br>
					<a href="<?=Http_Request::currentURI(['id'=>$module_name])?>"><?=$module->getControlCentreTitleTranslated()?></a>
				</div>
			<?php endforeach; ?>
		</div>
		<br><br>
<?php endforeach; ?>

<?php endif; ?>
