<?php
namespace JetApplicationModule\EShop\Wishlist;

use Jet\MVC_View;
use JetApplication\Product_EShopData;
use JetApplication\EShop_Managers;

/**
 * @var MVC_View   $this
 * @var Product_EShopData[] $products
 */

$products = $this->getRaw('products');

?>

<?php if($products): ?>
	<div class="product_listing_list_products">
		<?php foreach($products as $product): ?>
			<?=EShop_Managers::ProductListing()->renderItem( $product )?>
		<?php endforeach; ?>
	</div>
<?php endif; ?>
