<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Categories;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\Form;
use Jet\UI_button;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View   $this
 * @var Controller_Main $controller
 * @var Form $form
 */
$controller = $this->controller;
$category = $this->controller->getCurrentItem();

$form = $this->getRaw('form');

if($form->getIsReadonly()) {
	return;
}

$form_id = $form->getId();

?>
<?=UI::button_save()->setOnclick("$('#$form_id').submit();")?>

<script>
	const MoveCategory = {
		target: 0,
		
		moveThis: () => {
			if(MoveCategory.target) {
				location = '<?=Http_Request::currentURI()?>&move_category='+MoveCategory.target;
			}
		},
		moveSubcategories: () => {
			if(MoveCategory.target) {
				location = '<?=Http_Request::currentURI()?>&move_subcategories='+MoveCategory.target;
			}
		}
	};
	
</script>

<div style="padding-left: 20px;">
	<?=Tr::_('Move this category to:')?>
</div>
<div style="width: 300px;">
	<?=Admin_Managers::Category()->renderSelectWidget("MoveCategory.target=selected_item.id;")?>
</div>
<?=UI::button( Tr::_('Move this category') )->setOnClick("MoveCategory.moveThis();")->setClass(UI_button::CLASS_SECONDARY)?>
<?=UI::button( Tr::_('Move subcategories of this category') )->setOnClick("MoveCategory.moveSubcategories();")->setClass(UI_button::CLASS_SECONDARY)?>

<?php if( Main::getCurrentUserCanDelete() ): ?>
<div style="padding-right: 30px;"></div>
	<?=UI::button_delete( ' ' )->setUrl( $controller->getControllerRouter()->getAction('delete')->URI($category->getId()) )?>
<?php endif; ?>

<div style="padding-right: 30px;"></div>