<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\Catalog\ProductReviews;

use Jet\Locale;
use Jet\MVC_View;
use JetApplication\ProductReview;

/**
 * @var MVC_View $this
 
 * @var ProductReview $item
 */

$item = $this->getRaw('item');

$listing = $this->getRaw('listing');

?>
<a href="<?=$listing->getEditUrl( $item );?>"><?=Locale::dateAndTime( $item->getCreated() );?></a>
<?php

