<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\Catalog\ProductReviews;

use Jet\MVC_View;
use Jet\Tr;
use JetApplication\ProductReview;

/**
 * @var MVC_View $this
 
 * @var ProductReview $item
 */

$item = $this->getRaw('item');

if(!$item->getSource()) {
	echo Tr::_('e-shop');
	return;
}

echo $item->getSource();
echo '<br>';
echo $item->getSourceId();