<?php
namespace JetApplicationModule\Admin\Discounts\CodesDefinition;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View   $this
 * @var DiscountsCode       $discounts_code
 */
$discounts_code = $this->getRaw( 'discounts_code' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( 'Do you really want to delete this discounts code?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $discounts_code->getId() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$discounts_code->getCode();?> (<?=$discounts_code->getCode();?>)</a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>