<?php
namespace JetApplicationModule\Admin\Discounts\CodesDefinition;

use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var DiscountsCode     $discounts_code
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );
?>


<?=$form->start()?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()?>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		
		<?=$form->field( 'shop' )?>
		<?=$form->field( 'code' )?>
		<?=$form->field( 'internal_description' )?>
		<?=$form->field( 'valid_from' )?>
		<?=$form->field( 'valid_till' )?>
		<?=$form->field( 'minimal_order_amount' )?>
		<?=$form->field( 'number_of_codes_available' )?>
		<?=$form->field( 'discount_type' )?>
		<?=$form->field( 'discount' )?>

	</div>
</div>

<?=$form->end()?>
