<?php
namespace JetApplicationModule\Admin\Discounts\CodesDefinition;

use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var DiscountsCode     $discounts_code
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );

$discounts_code = $this->getRaw('discounts_code');


$form->field( 'use_filter' )->input()->addJsAction('onchange', "$('#filter_area').toggle()")
?>
<?=$form->start()?>
<div class="toolbar" id="main-toolbar">
	<?=UI::button_goBack()?>

	<?php if( !$form->getIsReadonly() ): ?>
		<?=UI::button_save()?>
	<?php endif; ?>
</div>

<div id="main-col">
	
	<?=$form->field( 'shop' )?>
	<?=$form->field( 'code' )?>
	<?=$form->field( 'internal_notes' )?>
	<?=$form->field( 'valid_from' )?>
	<?=$form->field( 'valid_till' )?>
	<?=$form->field( 'minimal_order_amount' )?>
	<?=$form->field( 'number_of_codes_available' )?>
	<?=$form->field( 'discount_type' )?>
	<?=$form->field( 'discount' )?>
	<?=$form->field( 'do_not_combine' )?>
	
	<?php if(!$discounts_code->getIsNew()): ?>
	<?=$form->field( 'use_filter' )?>
	
	
	<div id="filter_area" style="display: <?=$discounts_code->getUseFilter()?'block':'none'?>">
		<?=Admin_Managers::ProductFilter()->renderFilterForm();?>
	</div>
	<?php endif; ?>
</div>

<?=$form->end()?>
