<?php
namespace JetShopModule\Admin\Discounts\CodesDefinition;

use Jet\Locale;
use JetShop\Discounts_Code as DiscountsCode;

use Jet\UI;
use Jet\UI_dataGrid;
use Jet\UI_button;

use Jet\Tr;
use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Form         $filter_form
 */
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );
$router = $this->getController()->getControllerRouter();


$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( DiscountsCode $item ) use ( $router ) {
		if( ( $edit_uri = $router->action('edit')->URI( $item->getId() ) ) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;
		if($item->getNumberOfCodesUsed()==0) {
			echo '&nbsp;';
			if( ( $delete_uri = $router->action('delete')->URI( $item->getId() ) ) ):
				echo UI::button_delete()->setUrl( $delete_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
			endif;
		}

	}
);
$c_edit->addCustomCssStyle( 'width:150px;' );

$grid->getColumn( 'shop_code' )->setRenderer(
	function( DiscountsCode $item ) use ( $router ) {
		echo $item->getShop()->getShopName();
	}
);
$grid->getColumn('shop_code')->addCustomCssStyle('width:150px');


$grid->getColumn( 'code' )->setRenderer(
	function( DiscountsCode $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getId() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getCode();?></a>
		<?php
	}
);
$grid->getColumn('code')->addCustomCssStyle('width:300px');

$grid->getColumn( 'id' )->setRenderer(
	function( DiscountsCode $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getId() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getId();?></a>
		<?php
	}
);
$grid->getColumn('id')->addCustomCssStyle('width:120px');

$grid->getColumn('status')->setRenderer(
	function( DiscountsCode $item ) {
		$error_code = '';

		if($item->isValid( $error_code )) {
			echo '<div class="badge badge-success">';
			echo Tr::_('Available');
			echo '</div>';
		} else {
			echo '<div class="badge badge-danger">';
			echo Tr::_('Not Available');
			echo '</div>';
		}

		echo '<br>';

		if($item->getValidFrom()) {
			echo Tr::_('Valid from: %FROM%', ['FROM'=>Locale::getCurrentLocale()->formatDateAndTime($item->getValidFrom())]);
			echo '<br>';
		}

		if($item->getValidTill()) {
			echo Tr::_('Valid till: %FROM%', ['FROM'=>Locale::getCurrentLocale()->formatDateAndTime($item->getValidTill())]);
			echo '<br>';
		}

		echo Tr::_('Codes available: %N%', ['N'=>$item->getNumberOfCodesAvailable()]);
		echo '<br>';
		echo Tr::_('Codes used: %N%', ['N'=>$item->getNumberOfCodesUsed()]);
	}
);
$grid->getColumn('status')->addCustomCssStyle('width:300px');

$grid->getColumn('internal_description')->setRenderer(
	function( DiscountsCode $item ) {
		echo nl2br($item->getInternalDescription());
	}
);



?>

<?=$filter_form->start()?>
<div class="row toolbar">
	<?php if( ( $add_uri = $router->action('add')->URI() ) ): ?>
		<div class="col-md-2 col-sm-12">
			<?=UI::button_create( Tr::_( 'Create a new Discounts Code' ) )->setUrl( $add_uri )?>
		</div>
	<?php endif; ?>

	<div class="col-md-3 col-sm-12">
		<?= $filter_form->field( 'search' )->input() ?>
	</div>
	<div class="col-md-4 col-sm-12">
		<table>
			<tr>
				<td><?=$filter_form->field('shop')->label()?></td>
				<td><?=$filter_form->field('shop')->input()->addJsAction('onchange', 'this.form.submit()')?></td>
			</tr>
		</table>
	</div>

</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
