<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ControlCentreModule\CarrierServices;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;
use JetApplication\Carrier;
use JetApplication\Carrier_Service;

/**
 * @var MVC_View   $this
 * @var Carrier|null $selected_carrier
 * @var Carrier_Service|null $selected_carrier_service
 * @var Carrier_Service|null $new_carrier_service
 */

$selected_carrier = $this->getRaw('carrier');
$selected_carrier_service = $this->getRaw('carrier_service');

$new_carrier_service = $this->getRaw('new_carrier_service');

?>
<div style="display: grid;grid-template-columns: 1fr 1fr;gap: 10px">
	<div>
		<table class="table table-striped">
			<thead>
			<tr>
				<th style="width: 505px"><?=Tr::_('Carrier')?></th>
				<th style="width: 505px"><?=Tr::_('Service')?></th>
			</tr>
			</thead>
			<tbody>
			<?php foreach( Carrier::getList() as $carrier ): ?>
			<tr>
				<td>
					<?php if( $selected_carrier?->getCode()==$carrier->getCode() ): ?>
						<b><?=$carrier->getName()?></b>
						<br>
						<?=UI::button_create('Create a new service')->setUrl( Http_Request::currentURI(set_GET_params: ['add'=>'add'], unset_GET_params: ['service']) )?>
					<?php else: ?>
						<a href="<?=Http_Request::currentURI(['carrier'=>$carrier->getCode()],['service', 'add'])?>"><?=$carrier->getName()?></a>
					<?php endif; ?>
				</td>
				<td></td>
			</tr>
			<?php foreach($carrier->getServices() as $service): ?>
					<?php if(
						$selected_carrier?->getCode()==$carrier->getCode() &&
						$selected_carrier_service?->getCode()==$service->getCode()
					): ?>
					<tr>
						<td></td>
						<td><b><?=$service->getName()?> (<?=$service->getCode()?>)</b></td>
					</tr>
					<?php else: ?>
					<tr>
						<td></td>
						<td><a href="<?=Http_Request::currentURI(['carrier'=>$carrier->getCode(), 'service'=>$service->getCode()], unset_GET_params: ['add'])?>"><?=$service->getName()?> (<?=$service->getCode()?>)</a></td>
					</tr>
					
					<?php endif; ?>
			<?php endforeach; ?>
			<?php endforeach; ?>
			</tbody>
		</table>
		
	</div>
	<div>
		<?php if($selected_carrier_service || $new_carrier_service):
			foreach( UI_messages::get(context: 'CC') as $message ):
				echo $message;
			endforeach;
			
			
			$form = $selected_carrier_service?->getEditForm();
			if(!$form) {
				$form = $new_carrier_service->getAddForm();
			}
			
			
			?>
			<?=$form->start()?>
				<?=$form->field('code')?>
				<?=$form->field('name')?>
				<?=$form->field('compatible_kind_of_delivery')?>
				<?=$form->field('carrier_service_identification_code')?>
				<?=$form->field('packaging_has_dimensions')?>
				<?=$form->field('packaging_has_weight')?>
			
				<br><br>
		
				<div style="display: grid;grid-template-columns: 1fr 1fr;">
					<div>
						<?=UI::button_save()?>
					</div>
					<div style="text-align: right">
						<?php if($selected_carrier_service): ?>
							<?=UI::button_delete( Tr::_('Delete service'))->setUrl( Http_Request::currentURI(['delete'=>'delete']) )?>
						<?php endif ?>
					</div>
				</div>
				
			<?=$form->end()?>
		<?php endif; ?>
		
	</div>
	
</div>