<?php
namespace JetApplicationModule\Shop\CashDesk;


use Jet\MVC_View;
use JetApplication\Payment_Method_ShopData;

/**
 * @var MVC_View $this
 * @var Payment_Method_ShopData $method
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');
$method = $this->getRaw('payment_method');

$this->setVar('payment_method', $method);
?>

<div class="method" onclick="CashDesk.payment.select('<?= $method->getId() ?>')">
	<div>
		<input type="radio" name="payment_method" onclick="setTimeout(function(){CashDesk.payment.select('<?= $method->getId() ?>')}, 10);return false;" />
	</div>
	<div class="method-icon">
		<?php if(($img=$method->getIcon1ThumbnailUrl(50, 50))): ?>
			<img src="<?=$img?>" style="padding: 5px;">
		<?php endif; ?>
	</div>
	<div class="method-title">
		<b><?= $method->getTitle() ?></b><br>
		<div>
			<?= $method->getDescription() ?>
		</div>
	</div>
	
	<?=$this->render('payment/price')?>
</div>
