<?php
namespace JetShop;


use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Payment_Method $payment_method
 */

$cash_desk = CashDesk::get();
$payment_method = $this->getRaw('payment_method');
$pm_shd = $payment_method->getShopData($cash_desk->getShopCode());

$this->setVar('payment_method', $payment_method);

$options = $payment_method->getActiveOptions( $cash_desk->getShopCode() );
?>

<div class="card bg-info">
	<div class="card-body">
		<h5 class="card-title">

			<input type="radio" name="payment_method" checked />
			<img src="<?=$pm_shd->getIcon1ThumbnailUrl(50, 50)?>" style="padding: 5px;">

			<b><?= $pm_shd->getTitle() ?></b>

			<span style="padding-left: 50px;">
				<?=$this->render('payment/price')?>
			</span>

		</h5>

		<div class="card-text">

			<?= $pm_shd->getDescription() ?>


			<?php if($options):
				$selected_option_code = $cash_desk->getSelectedPaymentMethodOption()->getCode();
				?>
				<div>
					<?php foreach($options as $option):
						$this->setVar( 'payment_method_option', $option );
						?>
						<div style="padding: 5px;">
							<?php
							if($option->getCode()==$selected_option_code):
								require 'option/selected.phtml';
							else:
								require 'option/not-selected.phtml';
							endif;
							?>
						</div>
					<?php endforeach; ?>
				</div>
			<?php endif; ?>
		</div>

	</div>
</div>
