<?php
namespace JetApplicationModule\Shop\CashDesk;


use Jet\MVC_View;
use JetApplication\Payment_Method_ShopData;

/**
 * @var MVC_View $this
 * @var Payment_Method_ShopData $method
 */

$cash_desk = CashDesk::get();
$method = $this->getRaw('payment_method');

$this->setVar('payment_method', $method);

$options = $method->getOptions();
?>

<div class="method-selected">

	<div>
		<input type="radio" name="payment_method" checked />
	</div>
	<div class="method-icon">
		<?php if(($img=$method->getIcon1ThumbnailUrl(50, 50))): ?>
			<img src="<?=$img?>" style="padding: 5px;">
		<?php endif; ?>
	</div>
	<div class="method-title">
		<b><?= $method->getTitle() ?></b>

		<div>
			<?= $method->getDescription() ?>
			
			
			<?php if($options):
				$selected_option_id = $cash_desk->getSelectedPaymentMethodOption()->getId();
				?>
				<div>
					<?php foreach($options as $option):
						$this->setVar( 'payment_method_option', $option );
						?>
						<div style="padding: 5px;">
							<?php
							if($option->getId()==$selected_option_id):
								require 'option/selected.phtml';
							else:
								require 'option/not-selected.phtml';
							endif;
							?>
						</div>
					<?php endforeach; ?>
				</div>
			<?php endif; ?>
			
		</div>
	</div>
	
	<?=$this->render('payment/price')?>

</div>
