<?php
namespace JetApplicationModule\Admin\Orders;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;
use Jet\UI_dialog;
use Jet\MVC_View;
use JetApplication\Order;

/**
 * @var MVC_View $this
 * @var Order     $order
 * @var Form $form
 */

$order = $this->getRaw( 'order' );
$form = $this->getRaw('billing_address_form');

if(!$order->isEditable()) {
	return;
}

if(!$form) {
	return;
}


$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 3
]);
$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 8
]);


$billing_address_dialog = new UI_dialog( 'billing_address_dialog', Tr::_('Update billing address'), UI_dialog::SIZE_EXTRA_LARGE );

echo $billing_address_dialog->start();
echo $form->start();

foreach($form->getFields() as $field) {
	echo $field;
}

echo $billing_address_dialog->footer();
echo UI::button_save(Tr::_('Update'));
echo $form->end();
echo $billing_address_dialog->end();
