<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\Tr;
use Jet\UI;
use Jet\MVC_View;
use Jet\UI_button;

/**
 * @var MVC_View $this
 */

?>
<?=UI::button( Tr::_('Adjust quantity / Remove item') )
	->setIcon('pen-to-square')
	->addCustomCssClass('dropdown-item')
	->setClass( UI_button::CLASS_INFO )
	->setOnClick("updateItemQty.showDialog();")?>