<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Complaints;


use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;

use Jet\MVC_View;
use JetApplication\Application_Service_Admin;


/**
 * @var MVC_View $this
 * @var Form $form
 */

$form = $this->getRaw('change_product_form');

if(!$form) {
	return;
}

$form->renderer()->setDefaultLabelWidth([	Form_Renderer::LJ_SIZE_MEDIUM => 3
]);
$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 9
]);

$form->renderer()->addJsAction('onsubmit', 'sendChangeProductForm();return false;');

echo $form->start();

foreach($form->getFields() as $field) {
	echo $field;
}
?>
		<div style="display: flex;flex-wrap:nowrap;gap: 10px;align-items: center;margin: 20px;">
			<div style="width: 150px"><?=Tr::_('Select product:')?></div>
			<div style="width: 500px;">
				<?=Application_Service_Admin::Product()->renderSelectWidget("document.getElementById('".$form->field('product')->getId()."').value=selected_item.id;sendChangeProductForm();", name: "change_product_selection")?>
			</div>
		</div>
	</div>
	<div class="modal-footer">
	<?php
echo UI::button_save(Tr::_('Update'));
echo $form->end();
