<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\DeliveryNotes;


use Jet\Form;
use Jet\Locale;
use Jet\Tr;
use JetApplication\Application_Service_Admin;
use JetApplication\Application_Service_Admin_EShopEntity_Listing;

use Jet\MVC_View;
use JetApplication\EShops;
use JetApplication\DeliveryNote;


/**
 * @var MVC_View $this
 * @var DeliveryNote     $invoice
 * @var Application_Service_Admin_EShopEntity_Listing $listing
 * @var Form $add_bl_form
 */

$invoice = $this->getRaw( 'invoice' );
?>

<div id="main-col">
	<div style="padding: 10px;display: flex;gap: 50px;">
		
		<div class="card">
			
			<div class="card-header"><b><?=Tr::_('Common information')?></b></div>
			<div class="card-body">
				
				
				<table style="margin: 10px">
					
					<?php if(EShops::isMultiEShopMode()): ?>
						<tr>
							<td><b><?=Tr::_('e-shop')?></b></td>
							<td style="padding: 3px"><?=$invoice->getEshop()->getName()?></td>
						</tr>
					<?php endif; ?>
					<?php if($invoice->getOrderId()): ?>
					<tr>
						<td nowrap=""><b><?=Tr::_('Order:')?></b></td>
						<td nowrap="" style="padding: 3px"><?=Application_Service_Admin::Order()->renderItemName(  $invoice->getOrderId() )?></td>
					</tr>
					<?php endif; ?>
					
					
					
					
					<tr>
						<td nowrap=""><b><?=Tr::_('Invoice date:')?></b></td>
						<td nowrap="" style="padding: 3px"><?= Locale::date($invoice->getInvoiceDate()) ?></td>
					</tr>
					<tr>
						<td nowrap=""><b><?=Tr::_('Due date:')?></b></td>
						<td nowrap="" style="padding: 3px"><?= Locale::date($invoice->getDueDate()) ?></td>
					</tr>
					<tr>
						<td><b><?=Tr::_('Payment method:')?></b></td>
						<td nowrap="" style="padding: 3px"><?=$invoice->getPaymentKind()?->getTitleInvoice()?></td>
					</tr>
				</table>
				
			</div>
		</div>
		
		<div class="card">
			<div class="card-header"><b><?=Tr::_('Customer')?></b></div>
			<div class="card-body">
				<?=Application_Service_Admin::Customer()->renderItemName( $invoice->getCustomerId() )?>
				<br>
				
				<?=Application_Service_Admin::Customer()->formatAddress( $invoice->getEshop(), $invoice->getCustomerAddress() )?>
				
				<table>
					<tr>
						<td><?=Tr::_('Phone:')?></td>
						<td><?=$invoice->getCustomerPhone()?></td>
					</tr>
					<tr>
						<td><?=Tr::_('e-mail:')?></td>
						<td><a href="mailto:<?=$invoice->getCustomerEmail()?>"><u><?=$invoice->getCustomerEmail()?></u></a></td>
					</tr>
				</table>
				
				
			</div>
		</div>
		
		<div class="card">
			<div class="card-header"><b><?=Tr::_('Issuer')?></b></div>
			<div class="card-body">
				
				<?=Application_Service_Admin::Customer()->formatAddress( $invoice->getEshop(), $invoice->getIssuerAddress() )?>
				<div style="font-size: 0.8rem">
					<?=$invoice->getIssuerInfo()?>
				</div>
				
			</div>
		</div>
		
		
		<div style="margin: 10px;">
		</div>
	</div>

</div>
