<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\InvoicesInAdvance;


use Jet\Locale;
use Jet\MVC_View;
use JetApplication\InvoiceInAdvance;

/**
 * @var MVC_View $this
 * @var InvoiceInAdvance $item
 */

$item = $this->getRaw('item');
?>
<?=Locale::dateAndTime( $item->getInvoiceDate() );?>

