<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\InvoicesInAdvance;


use Jet\MVC_View;
use JetApplication\Admin_Managers_EShopEntity_Listing;
use JetApplication\InvoiceInAdvance;

/**
 * @var MVC_View $this
 * @var Admin_Managers_EShopEntity_Listing $listing
 * @var InvoiceInAdvance $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');

if(!$item->isCancelled()):
?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=$item->getNumber();?></a>
<?php else: ?>
	<a href="<?=$listing->getEditUrl( $item );?>" style="text-decoration: line-through;color: red;"><?=$item->getNumber();?></a>
<?php endif;
