<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\InvoicesInAdvance;

use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\InvoiceInAdvance;

/**
 * @var MVC_View $this
 * @var InvoiceInAdvance $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::PriceFormatter()->formatWithCurrencyByHasVAT($item->hasVAT(), $item->getCurrency(), $item->getTotal() );
