<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\InvoicesInAdvance;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\InvoiceInAdvance;

/**
 * @var MVC_View $this
 * @var InvoiceInAdvance $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::PriceFormatter()->formatWithCurrencyByHasVAT($item->hasVAT(), $item->getCurrency(), $item->getTotal() );
