<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\CashDesk;


use Jet\MVC_View;
use JetApplication\Payment_Method;
use JetApplication\EShop_Managers;

/**
 * @var MVC_View $this
 * @var Payment_Method $method
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');

$pricelist = $cash_desk->getPricelist();
$method = $this->getRaw('payment_method');

?>
<div class="price">
<?php if($method->getDefaultPrice($pricelist)!=$method->getPrice($pricelist)):?>
	<div class="price-standard"><?=EShop_Managers::PriceFormatter()->formatWithCurrency($method->getDefaultPrice($pricelist), $pricelist );?></div>
<?php endif; ?>
	<div class="price-final"><?=EShop_Managers::PriceFormatter()->formatWithCurrency($method->getPrice($pricelist), $pricelist );?></div>
</div>