<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\Form;
use Jet\Navigation_MenuSet;
use Jet\Navigation_Menu;
use Jet\Navigation_Menu_Item;
use Jet\Tr;
use Jet\UI;
use Jet\UI_icon;
use Jet\MVC_View;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 * @var Form $signatures_form
 */

$signatures_form = $this->getRaw('admin_signatures_form');



$showMenu = function( Navigation_Menu $menu, callable $separator_renderer, callable $item_renderer ) {
	$separator_allowed = false;
	
	$count = count($menu->getItems());
	$i=0;
	foreach( $menu->getItems() as $item ) {
		$i++;
		$is_last = $i==$count;
		
		if( $item->getSeparatorBefore() ) {
			if($separator_allowed) {
				$separator_renderer();
			}
			
			$separator_allowed = false;
		}
		
		$item_renderer( $item );
		$separator_allowed = true;
		
		if($is_last) {
			break;
		}
		
		if( $item->getSeparatorAfter() ) {
			$separator_renderer();
			$separator_allowed = false;
		}
	}
};

$_menus = Navigation_MenuSet::get('admin')->getMenus();

$menus = [];
foreach($_menus as $menu) {
	if($menu->getItems()) {
		$menus[] = $menu;
	}
}

?>
<div class="col-md-12 main-col">
	<div style="display: grid;grid-template-columns: repeat(5, 1fr); gap: 20px;margin-top: 20px;margin-bottom: 30px;">


	<?php foreach( $menus as $menu ): ?>
		<div style="padding: 5px" class="card card-body shadow">
			<h5 style="margin: 10px;"><?=$menu->getLabel()?></h5>
			<div class="dropdown-divider"></div>
			
		<?php $showMenu(
			menu: $menu,
			separator_renderer: function() {
				?><div class="dropdown-divider"></div><?php
			},
			item_renderer: function( Navigation_Menu_Item $item) {
				?>
				
				<div style="display: grid;grid-template-columns: 40px 1fr;align-items: center;margin: 10px;">
					<div><a href="<?=$item->getUrl()?>" style="color: #363636"><?=UI::icon( $item->getIcon() )->setSize( UI_icon::SIZE_LARGE )?></a></div>
					<div><a href="<?=$item->getUrl()?>"><?=$item->getLabel()?></a></div>
				</div>
				<?php
			}
		); ?>
		</div>
	<?php endforeach; ?>
	</div>
	
	<div class="card">
		<div class="card-header"><?= Tr::_('Your signature')?></div>
		<div class="card-body">
			<div>
				<?=$signatures_form->start()?>
				
				<?php foreach( EShops::getList() as $eshop):
					$signatures_form->field('/signature/'.$eshop->getKey())->input()->addCustomCssStyle('height: 250px;')
					?>
					<?=$eshop->getName()?>:
					<?=$signatures_form->field('/signature/'.$eshop->getKey())->input()?>
					<br>
				<?php endforeach; ?>
				
				<?=UI::button_save()?>
				
				<?=$signatures_form->end()?>
			</div>
			
		</div>
	</div>
	<br><br><br>
</div>