<?php
namespace JetApplicationModule\Admin\Content\Article\Articles;

use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Admin_Managers;


/**
 * @var MVC_View $this
 * @var Listing_Filter_Author $filter
 */

$listing = $this->getRaw( 'listing' );
$filter = $this->getRaw('filter');
$filter_form = $listing->getFilterForm();
$field = $filter_form->field( 'author' );
$field->input()->addJsAction( 'onchange', 'this.form.submit()' );

echo Admin_Managers::EntityListing()->renderListingFilter(
	filter:      $filter,
	title:       Tr::_('Author'),
	form_fields: [$field],
	is_active:   $field->getValue(),
	renderer:    function() use ($field) {
		?>
		<?= $field->input() ?>
		<?php
	}
);
