<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Listing;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;

/**
 * @var MVC_View $this
 * @var Listing  $listing
 */

$listing = $this->getRaw( 'listing' );
$entity_manager = $listing->getEntityManager();
$grid = $listing->getGrid();

$filter_enabled = (bool)$listing->getFilterWhere();
?>

<?php require 'list/buttons.phtml';?>

<div style="margin: 10px;display: flex;align-items: center;gap: 20px;padding: 10px;">

	<a href="" onclick="Filter.toggle();return false;" class="btn btn-primary">
		<?=UI::icon('caret-down')->setId('filter_caret_down')->addCustomCssStyle('display:'.(!$filter_enabled?'':'none'))?>
		<?=UI::icon('caret-up')->setId('filter_caret_up')->addCustomCssStyle('display:'.($filter_enabled?'':'none'))?>
		<?=Tr::_('Filter', dictionary: Tr::COMMON_DICTIONARY)?>
	</a>

	<a href="" onclick="DisplayedColumnsSetting.toggle();return false;" class="btn btn-info">
		<?=UI::icon('caret-down')->setId('column_schema_settings_caret_down')?>
		<?=UI::icon('caret-up')->setId('column_schema_settings_caret_up')->addCustomCssStyle('display:none')?>
		<?=Tr::_('Displayed columns setting', dictionary: Tr::COMMON_DICTIONARY)?>
	</a>
	
</div>


<?php require 'list/filter.phtml';?>
<?php require 'list/grid_schema.phtml';?>

<div id="main-col">
	<?=$grid->render();?>
</div>

