<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Listing;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_dialog;

/**
 * @var MVC_View $this
 * @var Listing  $listing
 */

$listing = $this->getRaw( 'listing' );
$entity_manager = $listing->getEntityManager();
$grid = $listing->getGrid();

$filter_form = $listing->getFilterForm();

$filter_is_active = false;

foreach($listing->getFilters() as $filter){
	if($filter->getKey()==Listing_Filter_Search::KEY){
		continue;
	}
	
	if($filter->isActive()){
		$filter_is_active = true;
	}
}

$grid->footer()->setPrepend(
	$this->render('list/buttons/footer')
);

?>
<style>
	.list_operation_menu_item {
		cursor: pointer;
		border: 1px solid #c9c9c9;
		padding: 10px;
		margin: 10px;
		border-radius: 3px;
	}

	.list_operation_menu_item.selected {
		background-color: #eaeaea;
		font-weight: bolder;
	}
	
	.list_operation_form_area {
		display: none;
	}
	
	.list_operation_form_area.selected {
		display: block;
	}
</style>

<script>
	const Filter = {
		filter_visible: <?=json_encode($filter_is_active)?>,

		toggle: ()=>{
			if(Filter.filter_visible) {
				Filter.filter_visible = false;

				$('#filter_caret_down').show();
				$('#filter_caret_up').hide();

				$('#filter').hide();

			} else {
				Filter.filter_visible = true;

				$('#filter_caret_up').show();
				$('#filter_caret_down').hide();

				$('#filter').show();

			}
		},

		reset: ( element_ids, reset_value )=> {
			for(let c=0;c<element_ids.length;c++) {
				$('#'+element_ids[c]).val(reset_value);
			}

			document.getElementById('<?=$filter_form->getId()?>').submit();
		}
	};
	
	const List = {
		selectAll: () => {
			const chb = document.getElementsByClassName('listing-select-checkbox');
			
			for (let i = 0; i < chb.length; i++) {
				chb[i].checked = true;
			}
		},
		unselectAll: () => {
			const chb = document.getElementsByClassName('listing-select-checkbox');

			for (let i = 0; i < chb.length; i++) {
				chb[i].checked = false;
			}
		},
		
		getSelectedIds: () => {
			const chb = document.getElementsByClassName('listing-select-checkbox');

			let ids = [];
			
			for (let i = 0; i < chb.length; i++) {
				if(chb[i].checked) {
					ids.push( chb[i]['dataset']['id'] );
				}
			}
			
			return ids;
		}
	};
	
	const ListOperation = {
		showDialog: () => {
			$('#perform_operation_dialog').modal('show');

			ListOperation.actualizeSelectedIds();
		},
		select: ( key ) => {
			const selected_items = document.getElementById('list_operation_menu').querySelector('.selected');
			if(selected_items) {
				selected_items.classList.remove('selected');
			}

			const selected_forms = document.getElementById('list_operation_forms').querySelector('.selected');
			if(selected_forms) {
				selected_forms.classList.remove('selected');
			}
			
			
			document.getElementById('list_operation_menu_item_'+key).classList.add('selected');
			document.getElementById('list_operation_form_area_'+key).classList.add('selected');
			
			ListOperation.actualizeSelectedIds();
		},
		
		actualizeSelectedIds: ()=> {
			const selected_ids = document.getElementById('list_operation_forms').querySelectorAll('.selected_ids');

			const ids = List.getSelectedIds().join(',');
			
			selected_ids.forEach( input => input.value = ids );

		}
	};
</script>



<?php require 'list/buttons.phtml';?>

<?=$filter_form->start()?>

<div class="card shadow-sm" style="margin: 10px;padding: 0px;">
	<div style="display: flex;align-items: center;gap: 20px;">
		
		<?=$listing->filter(Listing_Filter_Search::KEY)?->renderForm()?>

		<a href="" onclick="Filter.toggle();return false;" class="btn btn-primary">
			<?=UI::icon('caret-down')->setId('filter_caret_down')->addCustomCssStyle('display:'.(!$filter_is_active?'':'none'))?>
			<?=UI::icon('caret-up')->setId('filter_caret_up')->addCustomCssStyle('display:'.($filter_is_active?'':'none'))?>
			<?=Tr::_('Filter', dictionary: Tr::COMMON_DICTIONARY)?>
		</a>

		<a href="" onclick="DisplayedColumnsSetting.toggle();return false;" class="btn btn-link">
			<?=UI::icon('caret-down')->setId('column_schema_settings_caret_down')?>
			<?=UI::icon('caret-up')->setId('column_schema_settings_caret_up')->addCustomCssStyle('display:none')?>
			<?=Tr::_('Displayed columns setting', dictionary: Tr::COMMON_DICTIONARY)?>
		</a>
		
	</div>
</div>


<div id="filter" style="display: <?=$filter_is_active?'block':'none'?>;margin-left: 50px;margin-right: 50px;margin-bottom: 50px;" class="card card-body shadow">
	<div>
		<?php
		foreach($listing->getFilters() as $filter):
			if($filter->getKey()==Listing_Filter_Search::KEY) {
				continue;
			}
			echo  $filter->renderForm();
		endforeach;
		?>
	</div>
</div>


<?=$filter_form->end()?>


<?php require 'list/grid_schema.phtml';?>

<div id="main-col">
	<?=$grid->render();?>
</div>

<?php foreach($listing->getHandlers() as $handler):
	echo $handler->renderDialog();
endforeach;

echo $this->render('list/operations/dialog');
