<?php
namespace JetApplicationModule\Admin\Orders;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use Jet\UI_dialog;

use Jet\MVC_View;


/**
 * @var MVC_View $this
 * @var Form $form
 * @var Order $order
 */

$order = $this->getRaw('order');
if(!$order->isEditable()) {
	return;
}

$form = $this->getRaw('cancel_order_form');

$dialog = new UI_dialog( 'cancel_order_dialog', Tr::_('Cancel order'), UI_dialog::SIZE_LARGE );

$form->field('comment')->input()->addCustomCssStyle("height:400px");
$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 12
]);
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 12
]);


echo $dialog->start();
echo $form->start();

foreach($form->getFields() as $field) {
	echo $field;
}

echo $dialog->footer();
	echo UI::button_delete(Tr::_('Cancel order'))->setType(UI_button::TYPE_SUBMIT);
echo $form->end();
echo $dialog->end();
