<?php

namespace JetApplication\Installer;

use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View $this
 * @var Form $form
 */

$form = $this->getRaw('form');


?>

<?=$form->start()?>

	<?php foreach($form->getFields() as $field):
		if(!str_starts_with($field->getName(), 'currency_')) {
			continue;
		}
		?>
		<div style="display: grid;grid-template-columns: 200px 100px;align-items: center;gap: 10px;margin: 10px;">
			<?=$field->label()?>
			<?=$field->input()?>
		</div>
	<?php endforeach; ?>

	<?=$form->field('strategy')?>

	<br><br>
	<?= Installer::buttonNextSubmit(); ?>

<?=$form->end()?>
