<?php
namespace JetShopModule\Admin\Catalog\PropertyGroups;

use JetShop\PropertyGroup as PropertyGroup;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View   $this
 * @var PropertyGroup       $property_group
 */
$property_group = $this->getRaw( 'property_group' );
?>
<div class="col d-flex justify-content-center">

	<div class="card" style="margin-top:50px;">
		<div class="card-body">
			<p>
				<?=Tr::_( 'Do you really want to delete this property group?' );?>
				<br/>
				<a href="<?=$property_group->getEditURL();?>" style="font-weight: bolder;font-size: 20px;"><?=$property_group->getInternalName();?> (<?=$property_group->getId();?>)</a>
			</p>

			<div style="display: inline-block;width: 50%">
				<?= UI::button_goBack()->setUrl(Http_Request::currentURI(unset_GET_params: ['id', 'action'])) ?>
			</div>
			<div style="display: inline-block;width: 45%;text-align: right">
				<form action="<?= Http_Request::currentURI() ?>" method="post">
					<input type="hidden" name="delete" value="yes">
					<?= UI::button_delete()->setType( 'submit' ) ?>
				</form>
			</div>
		</div>
	</div>
</div>
