<?php
namespace JetApplicationModule\Admin\Catalog\PropertyGroups;

use JetApplication\Admin_Managers;
use JetApplication\KindOfProduct;
use JetApplication\PropertyGroup;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var PropertyGroup $property_group
 * @var KindOfProduct[] $kinds
 */
$property_group = $this->getRaw( 'property_group' );
$kinds = $this->getRaw('kinds');

?>
<div class="col d-flex justify-content-center">
	
	<div class="card" style="margin-top:50px;">
		<div class="card-body">
			<p>
				<?=Tr::_( 'It is mot possible tp delete this property group.' );?>
				<br/>
				<a href="<?=$property_group->getEditURL();?>" style="font-weight: bolder;font-size: 20px;"><?=$property_group->getInternalName();?> (<?=$property_group->getId();?>)</a>
			</p>
			
			<p>
				<?=Tr::_( 'It is used by following kinds of product:' );?>
				<ul>
					<?php foreach($kinds as $kind): ?>
						<li><?=Admin_Managers::KindOfProduct()->showName($kind->getId())?></li>
					<?php endforeach; ?>
				</ul>
			</p>
			
			<div style="display: inline-block;width: 50%">
				<?= UI::button_goBack()->setUrl(Http_Request::currentURI(unset_GET_params: ['id', 'action'])) ?>
			</div>
		</div>
	</div>
</div>
