<?php
namespace JetShop;

use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Product $product
 */

$product = $this->getRaw('product');
?>
<div class="availability">
	<?php /* $product->getDeliveryText(($product->getProductsQuantity() >= 10) ? SKLADEM_10AVIC . sklonovaniKusu(10) : SKLADEM_.' ' . $product->getProductsQuantity() . ' ' . sklonovaniKusu($product->getProductsQuantity()) ) */ ?>
</div>
