<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\CashDesk;



use Jet\MVC_View;
use JetApplication\Payment_Method;

/**
 * @var MVC_View $this
 * @var Payment_Method $method
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');
$method = $this->getRaw('payment_method');

$this->setVar('payment_method', $method);
?>

<div class="method" onclick="CashDesk.payment.select('<?= $method->getId() ?>')">
	<div class="method-radio-btn">
		<input type="radio" name="payment_method" onclick="setTimeout(function(){CashDesk.payment.select('<?= $method->getId() ?>')}, 10);return false;" />
	</div>
	<div class="method-icon">
		<?php if(($img=$method->getIcon1ThumbnailUrl(50, 50))): ?>
			<img src="<?=$img?>">
		<?php endif; ?>
	</div>
	<div class="method-title">
		<b><?= $method->getTitle() ?></b><br>
		<div>
			<?= $method->getDescription() ?>
		</div>
	</div>
	
	<?=$this->render('payment/price')?>
</div>
