<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\WarehouseManagement\LossOrDestruction;


use Jet\Http_Request;
use Jet\Tr;

use Jet\MVC_View;
use Jet\Form;
use Jet\UI;
use Jet\UI_button;
use JetApplication\WarehouseManagement_LossOrDestruction;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var WarehouseManagement_LossOrDestruction  $item
 */

$item = $this->getRaw('item');

if(
	$item->getId() &&
	$item->getStatus()->editable()
) {
	
	echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
	echo UI::button(Tr::_('Done'))->setUrl(Http_Request::currentURL(['action'=>'done']))->setClass(UI_button::CLASS_SUCCESS);
	
	echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
	echo UI::button(Tr::_('Cancel'))->setUrl(Http_Request::currentURL(['action'=>'cancel']))->setClass(UI_button::CLASS_DANGER);

}