<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\Marketing\DeliveryFeeDiscount;

use Jet\MVC_View;
use JetApplication\Delivery_Method;
use JetApplication\Marketing_DeliveryFeeDiscount;


/**
 * @var MVC_View $this
 * @var Marketing_DeliveryFeeDiscount $item
 */

$item = $this->getRaw('item');
echo Delivery_Method::getScope()[$item->getDeliveryMethodId()];
