<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Marketing\DeliveryFeeDiscount;


use Jet\MVC_View;
use JetApplication\Delivery_Method;
use JetApplication\Marketing_DeliveryFeeDiscount;


/**
 * @var MVC_View $this
 * @var Marketing_DeliveryFeeDiscount $item
 */

$item = $this->getRaw('item');
echo Delivery_Method::getScope()[$item->getDeliveryMethodId()]??$item->getDeliveryMethodId();
