<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Signposts;


use Jet\MVC_View;
use JetApplication\Application_Service_Admin;
use JetApplication\Signpost;

/**
 * @var MVC_View $this
 * @var Signpost $item
 */
$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
<div style="display: flex;align-items: center">
	<?=Application_Service_Admin::EntityEdit()->renderPreviewButton( $item );?>
	<a href="<?=$listing->getEditUrl( $item );?>" style="padding: 10px;"><?=$item->getInternalName()?></a>
</div>
