<?php
namespace JetApplicationModule\EShop\B2B\CashDesk;

use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Order;
use JetApplication\Application_Service_EShop;

/**
 * @var MVC_View $this
 * @var Order $order
 */


$order = $this->getRaw('order');

$payment_info = $order->getPaymentMethod()->generateFinalPageInfoText( $order );
$delivery_info = $order->getDeliveryMethod()->generateFinalPageInfoText( $order );
?>

	<div style="padding: 2%;">
		<h1><?=Tr::_('Your order has been accepted. Thank you!');?></h1>

		<div style="padding-top: 10px;padding-bottom:10px;font-size: 1.2rem;"><?=Tr::_('Order number: <b>%ORDER_NO%</b>', ['ORDER_NO'=>$order->getNumber()]);?></div>

		<p><?=Tr::_('On Your contact e-mail address was sent an email confirming your order.<br /><br />Have a nice day.')?></p>
		
		
		<?=$payment_info?>
		<?=$delivery_info?>

	</div>

<?=Application_Service_EShop::AnalyticsManager()?->purchase( $order )?>