<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\CashDesk;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\EShop_Managers;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */

$cash_desk = $this->getRaw('cash_desk');

if($cash_desk->getCurrentStep()!=CashDesk::STEP_CONFIRM) {
	return;
}

$special_requirements_form = $cash_desk->getSpecialRequirementsForm();
$special_requirements_form->setAction('?action=confirm_save_special_requirements');

$special_requirements_form->renderer()->addJsAction('onsubmit', 'CashDesk.confirm.saveSpecialRequirement();return false;');

$special_requirements_form->field('special_requirements')->input()->addJsAction('onchange', 'CashDesk.confirm.saveSpecialRequirement();');
?>
<span class="step-title"><?=Tr::_('Almost done')?></span>

<?=$special_requirements_form->start()?>
	<?=$special_requirements_form->field('special_requirements')->input()->addCustomCssStyle('height:100px;')?>
<?=$special_requirements_form->end()?>
<br>

<?php foreach($cash_desk->getAgreeFlags() as $code=>$flag):
	$this->setVar( 'flag', $flag );
	?>
<div id="agree_flag_area_<?=$code?>">
	<?=$this->render('confirm/agree_flag')?>
</div>
<?php endforeach; ?>

<div class="continue-button-area" id="cash_desk_order_send_button_area">
	<?=UI::button(Tr::_('Place order'))->setOnclick('CashDesk.confirm.send()')->setClass('success')?>
</div>

<?=EShop_Managers::Analytics()?->addDeliveryInfo( $cash_desk )?>
<?=EShop_Managers::Analytics()?->addPaymentInfo( $cash_desk )?>
