<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\CashDesk;


use Jet\Tr;
use Jet\UI;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');

if($cash_desk->getCurrentStep()!=CashDesk::STEP_DELIVERY):
	require 'delivery/has_been_selected.phtml';
	return;
endif;

	$delivery_methods = $cash_desk->getAvailableDeliveryMethods();
	$selected_delivery_method = $cash_desk->getSelectedDeliveryMethod();
	
	$has_personal_takeover = false;
	
	foreach ( $delivery_methods as $delivery_method ) {
		if($delivery_method->isPersonalTakeover()) {
			$has_personal_takeover = true;
		}
	}
?>
<span class="step-title"><?= Tr::_('Please select delivery method') ?></span>

<div class="methods">
<?php
if($has_personal_takeover) {
	require 'delivery/method/personal_takeover.phtml';
}
?>

<?php foreach ( $delivery_methods as $delivery_method ):

	$this->setVar( 'delivery_method', $delivery_method );

	if($delivery_method->isPersonalTakeover()) {
		continue;
	}

	if($delivery_method->getId()==$selected_delivery_method->getId()) {
		require 'delivery/method/selected.phtml';
	} else {
		require 'delivery/method/not-selected.phtml';
	}
	?>
	
<?php endforeach; ?>
</div>

<div class="continue-button-area">
	<?=UI::button(Tr::_('Continue'))->setOnclick('CashDesk.delivery.continue()')->setClass('primary')?>
</div>
