<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\CashDesk;


use Jet\MVC_View;
use JetApplication\Order_Item;
use JetApplication\Application_Service_EShop;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');

$order = $cash_desk->getOrder();

?>
<?php foreach($order->getItems() as $item): ?>
<div class="item">
	<div class="title"><?=$item->getTitle()?></div>
	<div class="price">
		<?php if( !($item->getType()==Order_Item::ITEM_TYPE_DISCOUNT && $item->getTotalAmount()==0) ): ?>
			<?=Application_Service_EShop::PriceFormatter()->formatWithCurrency($item->getTotalAmount())?>
		<?php endif; ?>
	</div>
</div>
<?php endforeach; ?>

<div class="total"><?=Application_Service_EShop::PriceFormatter()->formatWithCurrency($order->getTotalAmount_WithVAT())?></div>

