<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\WarehouseManagement\ReceiptOfGoods;


use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Application_Service_Admin;
use JetApplication\Supplier;
use JetApplication\Supplier_GoodsOrder;
use JetApplication\WarehouseManagement_ReceiptOfGoods_Item;
use JetApplication\WarehouseManagement_ReceiptOfGoods;

/**
 * @var MVC_View   $this
 * @var WarehouseManagement_ReceiptOfGoods $rcp
 * @var Controller_Main $controller
 * @var Supplier_GoodsOrder $order
 */

$controller = $this->getController();

$order_number = $this->getString('order_number');
$order = $this->getRaw('order');


$rcp = $this->getRaw('item');



$form = $rcp->getEditForm();
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 2
]);
$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 2
]);

?>
<div id="main-col">
	<?=$form->start()?>

	<div class="card card-body" style="margin: 10px;">
		<div class="row">
			<div class="col-md-2" style="padding: 15px"><?=Tr::_('Supplier:')?></div>
			<div class="col-md-2" style="font-weight: bolder;padding: 15px;"><?=Supplier::getScope()[$rcp->getSupplierId()]?></div>
		</div>
		<?=$form->field('currency_code')?>
		<?=$form->field('receipt_date')?>
		<?=$form->field('suppliers_bill_type')?>
		<?=$form->field('suppliers_bill_number')?>
		<?=$form->field('order_number')?>
		<div class="row">
			<div class="col-md-2" style="padding: 15px"></div>
			<div class="col-md-2" style="padding: 15px;">
				<?=$rcp->getStatus()->showAdmin()?>
			</div>
		</div>
	</div>

	<div class="card card-body" style="margin: 10px;">
		<?=$form->getCommonMessage()?>

		<h4><?=Tr::_('Items')?></h4>

		<table class="table table-striped">
			<thead>
			<tr>
				<th><?=Tr::_('Product name')?></th>
				<th><?=Tr::_('EAN')?></th>
				<th><?=Tr::_('Internal code')?></th>
				<th><?=Tr::_('Supplier code')?></th>

				<th><?=Tr::_('Sector')?></th>
				<th><?=Tr::_('Rack')?></th>
				<th><?=Tr::_('Position')?></th>

				<th><?=Tr::_('Number of units')?></th>
				<th></th>
				<th><?=Tr::_('Price per unit')?></th>
				<th><?=Tr::_('Total price')?></th>
			</tr>
			</thead>
			<?php
			$showItem = function( WarehouseManagement_ReceiptOfGoods_Item $item ) use ($form) {
				$p_id = $item->getProductId();
				?>
				<tr style="<?php if(!$item->getUnitsReceived()):?>opacity: 0.5<?php endif;?>">
					<td><?=Application_Service_Admin::Product()->renderItemName($item->getProductId())?></td>
					<td><?=$item->getProductEan()?></td>
					<td><?=$item->getProductInternalCode()?></td>
					<td><?=$item->getProductSupplierCode()?></td>

					<td><?=$form->field('/item_'.$p_id.'/sector')->input()?></td>
					<td><?=$form->field('/item_'.$p_id.'/rack')->input()?></td>
					<td><?=$form->field('/item_'.$p_id.'/position')->input()?></td>

					<td>
						<?php
						$input = $form->field('/item_'.$p_id.'/qty')->input();
						$input->addJsAction('onchange', "calcItem({$p_id})");
						$input->addCustomCssStyle("width: 150px;");
						$input->addCustomCssClass('qty');
						
						echo $input;
						?>
					</td>
					<td><?=$item->getMeasureUnit()?->getName()?></td>
					<td>
						<?php
						$input = $form->field('/item_'.$p_id.'/price_per_unit')->input();
						$input->addJsAction('onchange', "calcItem({$p_id})");
						$input->addCustomCssStyle("width: 150px;");
						$input->addCustomCssClass('price_per_unit');
						
						echo $input;
						?>
					</td>
					<td>
						<?php
						$input = $form->field('/item_'.$p_id.'/total_price')->input();
						$input->addCustomCssStyle("width: 150px;");
						$input->addCustomCssClass('total_price');
						
						echo $input;
						?>
					</td>
				</tr>
				<?php
			};
			
			foreach($rcp->getItems() as $item):
				if($item->getUnitsReceived()) {
					$showItem( $item );
				}
			endforeach;
			foreach($rcp->getItems() as $item):
				if(!$item->getUnitsReceived()) {
					$showItem( $item );
				}
			endforeach;
			?>
			<tfoot>
			<tr>
				<td colspan="7"></td>
				<td><input type="number" name="number_of_units" id="number_of_units" class="form-control" style="width: 150px;" readonly></td>
				<td colspan="2"></td>
				<td><input type="number" name="total_price" id="total_price" class="form-control" style="width: 150px;" readonly></td>
			</tr>
			</tfoot>
		</table>
	</div>

	<div class="card card-body" style="margin: 10px;">
		<?php
		$form->field('notes')->label()->setWidth([
			Form_Renderer::LJ_SIZE_MEDIUM => 1
		]);
		$form->field('notes')->input()->setWidth([
			Form_Renderer::LJ_SIZE_MEDIUM => 10
		]);
		?>
		<?=$form->field('notes')?>
	</div>

	<br><br><br>
	
	<?=Application_Service_Admin::EntityEdit()->renderEventHistory( $rcp, true )?>
	
	
</div>
	
<script>
	function calcItem( id ) {
		let qty = $('#edit_form_____item_'+id+'___qty').val();
		let price_per_unit = $('#edit_form_____item_'+id+'___price_per_unit').val();
		
		$('#edit_form_____item_'+id+'___total_price').val( qty*price_per_unit );

		calcSum();
	}
	
	function calcSum() {
		let total_number_of_units = 0.0;

		$('.qty').each( function (index, element) {
			total_number_of_units += element.value*1;
		} );
		$('#number_of_units').val( total_number_of_units );


		let total_price = 0.0;

		$('.total_price').each( function (index, element) {
			total_price += element.value*1;
		} );
		$('#total_price').val( total_price );
	}
	
	calcSum();
</script>