<?php
namespace JetApplicationModule\EShop\ReturnsOfGoods;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use JetApplication\EShop_Managers;
use JetApplication\ReturnOfGoods;
use JetApplication\Product_EShopData;

/**
 * @var MVC_View   $this
 * @var Form $edit_form
 * @var Product_EShopData $product
 * @var ReturnOfGoods $return
 */

$return = $this->getRaw('return');
$edit_form = $this->getRaw('form');
$product = $return->getProduct();
$edit_form->field('problem_description')->input()->addCustomCssStyle('width:100%;height:300px');
$edit_form->field('problem_description')->input()->addJsAction('onblur', "JetAjaxForm.submit(this.form.id)");

echo EShop_Managers::CustomerSection()?->showMenu('return-of-goods');
?>
<div class="customer-section-container">
<div class="card">
	<div class="card-body">
		<h5 class="card-title"><?=Tr::_('Finish return of goods request')?></h5>


		<div class="return-of-goods-product">
			<div>
				<?php if($product->getImg(0)): ?>
					<a href="<?=$product->getURL()?>"><img src="<?=$product->getImgThumbnailUrl(0, 50, 50)?>"></a>
				<?php endif; ?>
			</div>
			<div><a href="<?=$product->getURL()?>"><?=$product->getName()?></a></div>
		</div>
		
		<?=$edit_form->start()?>
		<div>
			<?=$edit_form->field('problem_description')?>
		</div>
		<?=$edit_form->end()?>
		
		<div id="finish-btn">
			<?=$this->render('detail/unfinished/finish-btn');?>
		</div>
	</div>
</div>
</div>