<?php
namespace JetShopModule\Admin\Catalog\Categories;


use JetShop\Exports_Module;
use Jet\Mvc_View;
use JetShop\Shops_Shop;

/**
 * @var Mvc_View $this
 * @var Exports_Module $selected_exp
 * @var Shops_Shop $selected_exp_shop
 */


$selected_exp = $this->getRaw('selected_exp');
$selected_exp_shop = $this->getRaw('selected_exp_shop');

$category = $this->getRaw('category');

?>
<?=$this->render('lj_start')?>
	<?php if($selected_exp): ?>
		<legend><?=$selected_exp->getTitle()?> - <?=$selected_exp_shop->getName()?></legend>
		<?=$selected_exp->handleCategorySettings( $category, $selected_exp_shop )?>
	<?php endif; ?>
<?=$this->render('lj_end')?>