<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Form;
use Jet\Tr;
use Jet\Mvc_View;
use JetShop\Category;
use JetShop\Shops;

/**
 * @var Mvc_View   $this
 */

$category = Controller_Main::getCurrentCategory();
$form = $category->getEditForm();
$form->setDefaultLabelWidth([Form::LJ_SIZE_MEDIUM=>2]);
$form->setDefaultFieldWidth([Form::LJ_SIZE_MEDIUM=>8]);
?>
<?=$this->render('lj_start')?>

<?=$form->start();?>


		<?php if(($references=$category->getReferences())): ?>
		<fieldset>
			<legend class="sub"><?=Tr::_('References')?></legend>
			<ul>
				<?php foreach($references as $r): ?>
					<li><a href="<?=$r->getEditURL()?>" target="_blank"><?=Category::renderIcon($r->getType())?> <?=$r->_getPathName()?></a></li>
				<?php endforeach; ?>
			</ul>
		</fieldset>

		<?php endif; ?>

		<?php foreach(Shops::getList() as $shop):
			$shop_code= $shop->getCode();
			$shop_data = $category->getShopData( $shop_code );
			?>
			<?=$shop_data->renderShopDataBlock_start()?>

				<fieldset>
					<legend class="sub"><?=Tr::_('Main data')?></legend>

					<?=$form->field('/shop_data/'.$shop_code.'/is_active')?>

					<?=$form->field('/shop_data/'.$shop_code.'/name')?>
					<?=$form->field('/shop_data/'.$shop_code.'/second_name')?>
					<?=$form->field('/shop_data/'.$shop_code.'/description')?>
				</fieldset>

				<fieldset>
					<legend class="sub"><?=Tr::_('SEO')?></legend>
					<?=$form->field('/shop_data/'.$shop_code.'/seo_h1')?>
					<?=$form->field('/shop_data/'.$shop_code.'/seo_title')?>
					<?=$form->field('/shop_data/'.$shop_code.'/seo_description')?>
					<?=$form->field('/shop_data/'.$shop_code.'/seo_keywords')?>
					<?=$form->field('/shop_data/'.$shop_code.'/internal_fulltext_keywords')?>
				</fieldset>
			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach; ?>

<?=$form->end();?>

<?=$this->render('lj_end')?>






