<?php

namespace JetApplicationModule\Carrier\Stores;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Carrier_DeliveryPoint;
use JetApplication\WarehouseManagement_Warehouse;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Carrier_DeliveryPoint[] $points
 * @var ?Carrier_DeliveryPoint $new_point
 * @var ?Carrier_DeliveryPoint $selected_point
 */

$points = $this->getRaw('points');

$new_point = $this->getRaw('new_point');

$form = null;

$add_form = $new_point?->getAddForm();

$selected_point = $this->getRaw('selected_point');

if($selected_point) {
	$form = $selected_point->getEditForm();
} else {
	if($new_point) {
		$form = $new_point->getAddForm();
	}
}

if($form) {
	$form->renderer()->setDefaultLabelWidth([
		Form_Renderer::LJ_SIZE_MEDIUM => 2
	]);
	$form->renderer()->setDefaultFieldWidth([
		Form_Renderer::LJ_SIZE_MEDIUM => 6
	]);
}

$days = [
'monday',
'tuesday',
'wednesday',
'thursday',
'friday',
'saturday',
'sunday',
];

?>
<div style="display: grid;grid-template-columns: 1fr 2fr;gap: 10px">
	<div>
		<table class="table table-striped">
			<?php foreach($points as $p): ?>
			<tr>
				<?php if($p->getId()==$selected_point?->getId()): ?>
					<td><b><?=$p->getId()?></b></td>
					<td><b><?=$p->getPointCode()?></b></td>
				<?php else: ?>
					<td><a href="<?=Http_Request::currentURI(['point'=>$p->getId()])?>"><?=$p->getId()?></a></td>
					<td><a href="<?=Http_Request::currentURI(['point'=>$p->getId()])?>"><?=$p->getPointCode()?></a></td>
				<?php endif; ?>
				<td>
					<?=$p->getName()?><br>
					<?=$p->getStreet()?><br>
					<?=$p->getZip()?> <?=$p->getTown()?><br>
					<?=$p->getCountry()?><br>
					<br>
					<?php if($p->getDedicatetWarehouseId()): ?>
						<?=Tr::_('Dedicated warehouse: %WH%', [
								'WH' => WarehouseManagement_Warehouse::getScope()[$p->getDedicatetWarehouseId()] ?? '?'
						])?>
					<?php endif; ?>
				</td>
			</tr>
			<?php endforeach; ?>
		</table>
		
		<?=UI::button_create(Tr::_('New store / internal delivery point'))->setUrl(Http_Request::currentURI(['new_point'=>'new_point'], ['point']))?>
	</div>
	<div>
		<?php
		if($form):
			echo $form->start();
			
			echo $form->field('point_code');
			echo $form->field('point_type');
			echo $form->field('is_active');
			echo $form->field('name');
			echo $form->field('street');
			echo $form->field('town');
			echo $form->field('zip');
			echo $form->field('country');
			echo $form->field('latitude');
			echo $form->field('longitude');
			echo $form->field('dedicatet_warehouse_id');
			
			?>
			<div class="row">
				<div class="col-md-10">
					<b><?=Tr::_('Opening hours')?></b>
					
					<table>
					<?php foreach($days as $day): ?>
						<tr>
							<td style="padding: 5px;"><?=$day?></td>
							<td style="padding: 5px;"><?=$form->field('/'.$day.'/open_1')->input()?></td>
							<td style="padding: 5px;"><?=$form->field('/'.$day.'/close_1')->input()?></td>
							<td style="padding: 5px;">&nbsp;&nbsp;&nbsp;</td>
							<td style="padding: 5px;"><?=$form->field('/'.$day.'/open_2')->input()?></td>
							<td style="padding: 5px;"><?=$form->field('/'.$day.'/close_2')->input()?></td>
							
						</tr>
					<?php endforeach; ?>
					</table>
				</div>
			</div>
		
			<div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-6">
					<?=UI::button_save()?>
				</div>
			</div>
			<?php
			echo $form->end();
		endif;
		?>
	</div>
	
</div>

