<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\OrderDispatch\DoDispatch;


use JetApplication\Admin_Managers;
use JetApplication\OrderDispatch;
use Jet\MVC_View;

/**
 * @var MVC_View   $this
 * @var OrderDispatch $dispatch
 */

$dispatch = $this->getRaw('dispatch');

echo Admin_Managers::Context()->showContext( $dispatch->getContext() );