<?php
namespace JetApplicationModule\Admin\OrderDispatch\DoDispatch;
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\OrderDispatch;


/**
 * @var MVC_View   $this
 * @var OrderDispatch $dispatch
 */

$dispatch = $this->getRaw('dispatch');
?>
<?=$dispatch->getRecipientFirstName()?> <?=$dispatch->getRecipientSurname()?><br>
<?=$dispatch->getRecipientStreet()?><br>
<?=$dispatch->getRecipientCountry()?><br>
<?=$dispatch->getRecipientZip()?> <?=$dispatch->getRecipientTown()?><br>
<?=Tr::_('Phone number: %phone%', ['phone'=>$dispatch->getRecipientPhone()])?><br>
<?=Tr::_('E-mail: <a href="mailto:%email%">%email%</a>', ['email'=>$dispatch->getRecipientEmail()])?>
