<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\OrderDispatch\DoDispatch;


use JetApplication\OrderDispatch;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_badge;

/**
 * @var MVC_View   $this
 * @var OrderDispatch $dispatch
 */

$dispatch = $this->getRaw('dispatch');

echo match ($dispatch->getStatus()) {
	OrderDispatch::STATUS_PENDING => UI::badge(
		UI_badge::PRIMARY,
		Tr::_( 'Awaiting processing' )
	)->addCustomCssStyle("padding: 10px"),
	
	OrderDispatch::STATUS_PREPARED_CONSIGNMENT_NOT_CREATED => UI::badge(
		UI_badge::INFO,
		Tr::_( 'Waiting for consignment to be created at the carrier' )
	)->addCustomCssStyle("padding: 10px"),
	
	OrderDispatch::STATUS_PREPARED_CONSIGNMENT_CREATE_PROBLEM => UI::badge(
		UI_badge::DANGER,
		Tr::_( 'Consignment creation problem' )
	)->addCustomCssStyle("padding: 10px"),
	
	OrderDispatch::STATUS_PREPARED_CONSIGNMENT_CREATED => UI::badge(
		UI_badge::SUCCESS,
		Tr::_( 'Ready to send' )
	)->addCustomCssStyle("padding: 10px"),
	
	
	OrderDispatch::STATUS_SENT => UI::badge(
		UI_badge::SUCCESS,
		Tr::_( 'Sent' )
	)->addCustomCssStyle("padding: 10px"),
	
	OrderDispatch::STATUS_ON_THE_WAY => UI::badge(
		UI_badge::SUCCESS,
		Tr::_( 'On the way' )
	)->addCustomCssStyle("padding: 10px"),
	
	
	OrderDispatch::STATUS_DELIVERED => UI::badge(
		UI_badge::SUCCESS,
		Tr::_( 'Delivered' )
	)->addCustomCssStyle("padding: 10px"),
	
	
	OrderDispatch::STATUS_RETURNING => UI::badge(
		UI_badge::DANGER,
		Tr::_( 'Returning' )
	)->addCustomCssStyle("padding: 10px"),
	
	OrderDispatch::STATUS_RETURNED => UI::badge(
		UI_badge::DANGER,
		Tr::_( 'Returned' )
	)->addCustomCssStyle("padding: 10px"),
	
	
	OrderDispatch::STATUS_LOST => UI::badge(
		UI_badge::DANGER,
		Tr::_( 'Lost' )
	)->addCustomCssStyle("padding: 10px"),
	
	
	OrderDispatch::STATUS_CANCEL => UI::badge(
		UI_badge::WARNING,
		Tr::_( 'Cancellation in progress' )
	)->addCustomCssStyle("padding: 10px"),
	
	OrderDispatch::STATUS_CANCELED => UI::badge(
		UI_badge::DANGER,
		Tr::_( 'Cancelled' )
	)->addCustomCssStyle("padding: 10px"),
	
	default => $dispatch->getStatus(),
};

