<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;

/**
 * @var MVC_View $this
 */

$event = $this->getRaw('event');
$event_data = $this->getRaw('event_data');

if($event_data):
?>

<script>fbq('track', '<?=$event?>', <?=json_encode($event_data)?>);</script>

<?php else: ?>

<script>fbq('track', '<?=$event?>');</script>

<?php endif;
