<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;

/**
 * @var MVC_View $this
 */

$fb_id = $this->getRaw('id');
if(!$fb_id) {
	return;
}
?>
<!-- Facebook Pixel Code -->
<script>
	!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
		n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
		n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
		t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
		document,'script','https://connect.facebook.net/en_US/fbevents.js');

	fbq('init', '<?= $fb_id ?>');

	if(!window['CookieSettingHandlers']) {
		window['CookieSettingHandlers'] = [];
	}

	window['CookieSettingHandlers'].push(( state )=>{
		if(state.marketing) {
			fbq('consent', 'grant');
		}
	});

</script>
<noscript><img height="1" width="1" style="display:none" src=https://www.facebook.com/tr?id=<?= $fb_id ?>&ev=PageView&noscript=1/></noscript>
<!-- End Facebook Pixel Code -->

