<?php
namespace JetApplication;

use JetShop\Core_Admin_EntityManager_WithEShopData_Controller;

abstract class Admin_EntityManager_WithEShopData_Controller extends Core_Admin_EntityManager_WithEShopData_Controller
{

}