<?php
namespace JetApplication;

use JetShop\Core_Admin_EntityManager_WithEShopData_Interface;

interface Admin_EntityManager_WithEShopData_Interface extends Core_Admin_EntityManager_WithEShopData_Interface {

}