<?php
namespace JetShopModule\Admin\Catalog\Properties;

use JetShop\Property;

use Jet\UI;
use Jet\UI_dataGrid;
use Jet\UI_button;

use Jet\Tr;
use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Form         $filter_form
 */
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );
$router = $this->getController()->getControllerRouter();


$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( Property $item ) use ( $router ) {
		if( ( $delete_uri = $router->action('delete_property')->URI( $item->getId() ) ) ):
			echo UI::button_delete(' ')->setUrl( $delete_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
			echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
		endif;
		if( ( $edit_uri = $router->action('edit_property_main')->URI( $item->getId() ) ) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;

	}
);
$c_edit->addCustomCssStyle( 'width:200px;' );

$grid->getColumn( 'id' )->addCustomCssStyle( 'width:120px;' );

$grid->getColumn( 'id' )->setRenderer(
	function( Property $item ) use ( $router ) {
		$edit_uri = $router->action('edit_property_main')->URI( $item->getId() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getId();?></a>
		<?php
	}
);


$grid->getColumn( 'internal_name' )->setRenderer(
	function( Property $item ) use ( $router ) {
		$edit_uri = $router->action('edit_property_main')->URI( $item->getId() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getInternalName();?></a>
		<?php
	}
);
$grid->getColumn( 'type' )->setRenderer(
	function( Property $item ) use ( $router ) {
		echo $item->getTypeTitle();
	}
);
$grid->getColumn( 'type' )->addCustomCssStyle( 'width:120px;' );


$grid->getColumn( 'internal_description' )->setRenderer(
	function( Property $item ) use ( $router ) {
		echo nl2br($item->getInternalNotes());
	}
);

?>

<?=$filter_form->start()?>
<div class="row toolbar">
	<?php if( ( $add_uri = $router->action('add_property')->URI() ) ): ?>
		<div class="col-md-2 col-sm-12">

			<div class="dropdown">
				<button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<?= UI::icon( 'plus' ) ?> <?= Tr::_( 'Create a new Property' ) ?>
				</button>
				<div class="dropdown-menu" style="padding: 10px;">
					<?php foreach(Property::getTypes() as $type=>$label): ?>
						<a class="dropdown-item" href="<?=$router->action('add_property')->URI( $type )?>" ><?=$label?></a>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
	<?php endif; ?>

	<div class="col-md-3 col-sm-12">
		<?=$filter_form->field('search')->input()?>
	</div>
	<div class="col-md-4 col-sm-12">
	</div>

</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
