<?php
namespace JetApplicationModule\Admin\Catalog\Properties;

use Jet\UI;

use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View     $this
 * @var Listing $listing
 */
$router = $this->getController()->getControllerRouter();

$listing = $this->getRaw( 'listing' );
$grid = $listing->getGrid();
$filter_form = $listing->getFilterForm();



$grid->getColumn( '_edit_' )->addCustomCssStyle( 'width:200px;' );
$grid->getColumn( 'id' )->addCustomCssStyle( 'width:120px;' );
$grid->getColumn( 'type' )->addCustomCssStyle( 'width:120px;' );

?>

<?=$filter_form->start()?>
<div class="row toolbar">
	<?php if( ( $add_uri = $router->action('add_property')->URI() ) ): ?>
		<div class="col-md-2 col-sm-12">

			<div class="dropdown">
				<button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<?= UI::icon( 'plus' ) ?> <?= Tr::_( 'Create a new Property' ) ?>
				</button>
				<div class="dropdown-menu" style="padding: 10px;">
					<?php foreach(Property::getTypes() as $type=>$label): ?>
						<a class="dropdown-item" href="<?=$router->action('add_property')->URI( $type )?>" ><?=$label?></a>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
	<?php endif; ?>

	<div class="col-md-3 col-sm-12">
		<?=$listing->filter(Listing_Filter_Search::KEY)->renderForm()?>
	</div>
	<div class="col-md-4 col-sm-12">
	</div>

</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
