<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\MoneyRefunds;

use Jet\Http_Request;
use Jet\MVC_View;
use JetApplication\MoneyRefund;

/**
 * @var MVC_View $this
 * @var MoneyRefund $money_refund
 */

$money_refund = $this->getRaw( 'money_refund' );

foreach( $money_refund->getStatus()->getPossibleFutureStates() as $state ):

	$btn = $state->getButton();

	echo $btn->setUrl( Http_Request::currentURI(['set_status'=>get_class($state->getStatus())]) );
endforeach;