<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Categories;


use Jet\MVC_View;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View   $this
 */

echo $this->render('lj_start');
	echo Admin_Managers::Image()->renderStandardManagement();
echo $this->render('lj_end');