<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Categories;


use JetApplication\Application_Service_Admin;

/**
 *
 * @var Controller_Main $controller
 */
$controller = $this->controller;

$category = $controller->getCurrentItem();

if(
	!$category ||
	!$category->getId()
) {
	return;
}

echo Application_Service_Admin::EntityEdit()->renderPreviewButton( $category );
