<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Products;


use Jet\MVC_View;
use JetApplication\Application_Service_Admin;
use JetApplication\Product;

/**
 * @var MVC_View $this
 * @var Product $item
 */

$item = $this->getRaw('item');

echo Application_Service_Admin::KindOfProduct()->renderItemName( $item->getKindId() );

