<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;
use JetApplication\Admin_Managers_Entity_Listing;
use JetApplication\Shops;

/**
 * @var MVC_View $this
 * @var Product $item
 * @var Admin_Managers_Entity_Listing $listing
 */

$item = $this->getRaw('item');
$listing = $this->getRaw('listing');


$edit_uri = $listing->getEditUrl($item);

$showShopLink = function( Product $item ) {
	?>
	<div style="padding: 8px;">
		<?php foreach(Shops::getListSorted() as $shop): ?>
			<a href="<?=$item->getShopData($shop)->getURL()?>" target="_blank" style="padding-left: 10px;"><?=UI::icon('eye')?> <?=$shop->getShopName()?></a>
		<?php endforeach; ?>
	</div>
	<?php
};
?>
<a href="<?=$edit_uri;?>"><?=$item->getAdminTitle();?></a>

<?php $showShopLink( $item ); ?>

<?php if($item->isVariantMaster()): ?>
	<br>
	<table>
		<thead>
		<tr>
			<th colspan="2"><?=Tr::_('Variants')?></th>
		</tr>
		</thead>
		<?php foreach($item->getVariants() as $variant): ?>
			<tr>
				<td><?=$variant->renderActiveState() ?></td>
				<td>
					<a href="<?=$variant->getEditURL()?>"><?=$variant->getAdminTitle()?></a>
					<?php $showShopLink( $variant ); ?>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
<?php endif; ?>

<?php if( $item->isSet() ): ?>
<br>
<table>
	<thead>
	<tr>
		<th colspan="2"><?=Tr::_('Set items')?></th>
	</tr>
	</thead>
	<?php foreach($item->getSetItems() as $set_item):
		$set_item_product = Product::get($set_item->getItemProductId());
		
		if(!$set_item_product) {
			?>
			<tr>
				<td></td>
				<td><?=UI_messages::createDanger(Tr::_('Unknown product %ID%', ['ID'=>$set_item->getItemProductId()]))->setCloseable(false)?></td>
			</tr>
			<?php
			continue;
		}
		
		?>
		<tr>
			<td><?=$set_item_product->renderActiveState()?></td>
			<td>
				<a href="<?=$set_item_product->getEditURL()?>"><?=$set_item_product->getAdminTitle()?></a>
				<?php $showShopLink( $set_item_product ); ?>
			</td>
		</tr>
	<?php endforeach; ?>
</table>
<?php endif; ?>