<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI_messages;
use JetApplication\Admin_Managers;
use JetApplication\Admin_Managers_Entity_Listing;
use JetApplication\Shops;

/**
 * @var MVC_View $this
 * @var Product $item
 * @var Admin_Managers_Entity_Listing $listing
 */

$item = $this->getRaw('item');
$listing = $this->getRaw('listing');


$edit_uri = $listing->getEditUrl($item);

$img = $item->getShopData(Shops::getCurrent())->getImgThumbnailUrl(0, 120, 120);
?>

<div style="display: flex;align-items: center">
	<?=Admin_Managers::EntityEdit_WithShopData()->renderPreviewButton( $item );?>
	
	<div style="padding: 5px;display: grid;grid-template-columns: 140px 1fr">
		<div style="padding: 5px;">
			<?php if($img):?>
			<img src="<?=$img?>">
			<?php endif; ?>
		</div>
		<div>
			<a href="<?=$edit_uri;?>"><?=$item->getAdminTitle();?></a>
			<div style="display: grid;grid-template-columns: 100px 1fr;">
				<?php if($item->getInternalCode()): ?>
					<div><?=Tr::_('Internal code:')?></div>
					<div><?=$item->getInternalCode()?></div>
				<?php endif; ?>
				
				<?php if($item->getEan()): ?>
					<div><?=Tr::_('EAN:')?></div>
					<div><?=$item->getEan()?></div>
				<?php endif; ?>
			</div>
		</div>
		
		
	</div>
</div>



<?php if($item->isVariantMaster()): ?>
	<br>
	<table>
		<thead>
		<tr>
			<th colspan="2"><?=Tr::_('Variants')?></th>
		</tr>
		</thead>
		<?php foreach($item->getVariants() as $variant): ?>
			<tr>
				<td><?=$variant->renderActiveState() ?></td>
				<td>
					<div style="display: flex;align-items: center">
						<?=Admin_Managers::EntityEdit_WithShopData()->renderPreviewButton( $variant );?>
						&nbsp;&nbsp;
						<a href="<?=$variant->getEditURL()?>"><?=$variant->getAdminTitle()?></a>
					</div>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
<?php endif; ?>

<?php if( $item->isSet() ): ?>
<br>
<table>
	<thead>
	<tr>
		<th colspan="2"><?=Tr::_('Set items')?></th>
	</tr>
	</thead>
	<?php foreach($item->getSetItems() as $set_item):
		$set_item_product = Product::get($set_item->getItemProductId());
		
		if(!$set_item_product) {
			?>
			<tr>
				<td></td>
				<td><?=UI_messages::createDanger(Tr::_('Unknown product %ID%', ['ID'=>$set_item->getItemProductId()]))->setCloseable(false)?></td>
			</tr>
			<?php
			continue;
		}
		
		?>
		<tr>
			<td><?=$set_item_product->renderActiveState()?></td>
			<td>
				<?=Admin_Managers::EntityEdit_WithShopData()->renderPreviewButton( $set_item_product );?>
				&nbsp;&nbsp;
				<a href="<?=$set_item_product->getEditURL()?>"><?=$set_item_product->getAdminTitle()?></a>
			</td>
		</tr>
	<?php endforeach; ?>
</table>
<?php endif; ?>