<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Products;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Pricelists;
use JetApplication\Product;

/**
 * @var MVC_View $this
 * @var Product $item
 */

$item = $this->getRaw('item');

?>
<div style="display: grid;justify-content:left;grid-template-columns: auto auto;gap: 10px;">
<?php foreach(Pricelists::getList() as $pricelist): ?>
	<div><?=$pricelist->getName()?></div>
	
	<div style="font-weight: bolder;"><?=Admin_Managers::PriceFormatter()->formatWithCurrency( $pricelist, $item->getPrice( $pricelist ) )?></div>
<?php endforeach; ?>
</div>