<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ProformaInvoices;


use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Admin_Managers;
use JetApplication\ProformaInvoice;

/**
 * @var MVC_View $this
 * @var ProformaInvoice[] $invoices
 */

$invoices = $this->getRaw('invoices');
if(!count($invoices)) {
	return;
}

$price_formatter = Admin_Managers::PriceFormatter();
?>
<table class="table table-striped">
	<thead>
		<tr>
			<th style="width: 200px"></th>
			<th style="width: 200px"><?=Tr::_('Number')?></th>
			<th style="width: 200px"><?=Tr::_('Date')?></th>
			<th style="width: 200px"><?=Tr::_('Total')?></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($invoices as $invoice): ?>
		<tr>
			<td><?=Tr::_('Proforma Invoice')?></td>
			<td>
				<?php if(!$invoice->isCancelled()): ?>
					<a href="<?=$invoice->getEditUrl();?>"><?=$invoice->getNumber();?></a>
				<?php else: ?>
					<a href="<?=$invoice->getEditUrl();?>" style="text-decoration: line-through;color: red;"><?=$invoice->getNumber();?></a>
				<?php endif; ?>
			</td>
			<td>
				<?=Locale::date(  $invoice->getInvoiceDate() ); ?>
			</td>
			<td>
				<?=$price_formatter->formatWithCurrencyByHasVAT($invoice->hasVAT(), $invoice->getCurrency(), $invoice->getTotal())?>
			</td>
			<td></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
