<?php
namespace JetApplicationModule\Admin\Catalog\PropertyGroups;

use JetApplication\Admin_Managers;
use JetApplication\PropertyGroup as PropertyGroup;

use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use JetApplication\Shops_Shop;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var PropertyGroup     $property_group
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 1 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );

$property_group = $this->getRaw( 'property_group' );
$router = $this->getController()->getControllerRouter();
?>


<?=$form->start()?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()?>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>
		<br>
		<?=Admin_Managers::UI()->renderEntityActivation( $property_group, !$form->getIsReadonly() )?>
		<?=$form->field('internal_name');?>
		<?=$form->field('internal_notes');?>
		
		<?php
		Admin_Managers::UI()->renderShopDataBlocks(
			form: $form,
			renderer: function( Shops_Shop $shop, string $shop_key ) use ($property_group, $form) : void {
				?>
				<fieldset>
					<legend class="sub"><?=Tr::_('Main data')?></legend>
					
					<?=Admin_Managers::UI()->renderEntityShopDataActivation( $property_group, $shop, !$form->getIsReadonly() )?>
					<?php
					echo $form->field('/shop_data/'.$shop_key.'/label');
					echo $form->field('/shop_data/'.$shop_key.'/description');
					
					?>
				</fieldset>
			<?php }); ?>

	</div>
</div>

<?=$form->end()?>
