<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\Complaints;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use Jet\UI_messages;
use JetApplication\Complaint;

/**
 * @var MVC_View  $this
 * @var Complaint $complaint
 */

$complaint = $this->getRaw('complaint');
?>

<div class="complaints-description">
<?php if($complaint->canBeFinished()): ?>
	<?=UI::button( Tr::_('Finish entering the complaint') )->setUrl( Http_Request::currentURI(['finish'=>1]) )->setClass(UI_button::CLASS_SUCCESS)?>
	<?php
else:
	if(count($complaint->getImages())<$complaint->getMinimalImageCount()): ?>
		<div class="complaints-description">
		<?=UI_messages::createInfo( Tr::_('Please upload at least %m% pictures.', ['m'=>$complaint->getMinimalImageCount()]) )?>
		</div>
	<?php endif;
	
	if(strlen($complaint->getProblemDescription())<$complaint->getMinimalProblemDescriptionLength()): ?>
		<div class="complaints-description">
		<?=UI_messages::createInfo( Tr::_('Please provide a sufficiently detailed description of the problem.', ['m'=>$complaint->getMinimalProblemDescriptionLength()]) )?>
		</div>
	<?php endif;
endif;
?>
</div>
