<?php
namespace JetApplicationModule\Admin\Customers;

use JetApplication\Customer as Customer;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View   $this
 * @var Customer       $customer
 */
$customer = $this->getRaw( 'customer' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( 'Do you really want to delete this customer?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $customer->getId() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$customer->getEmail();?> (<?=$customer->getEmail();?>)</a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>