<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Customers;


use Jet\Locale;
use JetApplication\Admin_Managers;
use JetApplication\Admin_Managers_EShopEntity_Edit;
use JetApplication\Customer as Customer;

use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use JetApplication\CustomerBlacklist;
use JetApplication\EMailMarketing;
use JetApplication\EMailMarketing_Subscribe_Log;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Customer     $customer
 * @var Admin_Managers_EShopEntity_Edit $edit_manager
 */


$customer = $this->getRaw( 'customer' );
$edit_manager = $this->getRaw('edit_manager' );

$eshop = $customer->getEshop();

$mailing_subscribe_events = EMailMarketing_Subscribe_Log::get( $customer->getEshop(), $customer->getEmail() );

echo $edit_manager->renderToolbar();
?>
<div id="main-col">
		<legend><?=Tr::_('Main data')?></legend>

		<table class="table">
			<tr>
				<td style="width: 150px"><?=Tr::_('Shop:')?></td>
				<td><?=$eshop->getName()?></td>
			</tr>
			<tr>
				<td><?=Tr::_('Registration:');?></td>
				<td>
					<?=Locale::getCurrentLocale()->formatDateAndTime($customer->getRegistrationDateTime())?><br>
					<?=$customer->getRegistrationIp()?>
				</td>
			</tr>
			<tr>
				<td><?=Tr::_('E-Mail:')?></td>
				<td><a href="mailto:<?=$customer->getEmail()?>"><?=$customer->getEmail()?></a></td>
			</tr>
			<tr>
				<td><?=Tr::_('Name:')?></td>
				<td><?=$customer->getName()?></td>
			</tr>
			<tr>
				<td><?=Tr::_('Phone:')?></td>
				<td><?=$customer->getPhoneNumber()?></td>
			</tr>
			<tr>
				<td></td>
				<td>
					<?php
					/**
					 * @var CustomerBlacklist $bl_detail
					 */
					if(CustomerBlacklist::customerIsBlacklisted( $customer->getEmail(), load_details: true, details: $bl_detail )): ?>
					<div class="alert alert-danger" role="alert" style="font-size: 1.4rem">
						<?=UI::icon('skull-crossbones')?> <?=Tr::_('Customer is blacklisted')?>
					</div>
					
					
					<?=Locale::dateAndTime($bl_detail->getCreated())?>
					<br>
					<?=nl2br($bl_detail->getDescription())?>
					<?php endif; ?>
					
				</td>
			</tr>
		</table>


		<legend><?=Tr::_('Addresses')?></legend>
		<fieldset>
		<?php foreach($customer->getAddresses() as $address): ?>
			<div class="card" style="width: 400px;height: 190px;float: left;margin: 10px;">
				<div class="card-body">
					<p class="card-text">
						<?=Admin_Managers::Customer()->formatAddress( $customer->getEshop(), $address )?>
					</p>
				</div>
			</div>
		<?php endforeach; ?>

		</fieldset>
		<br/>

		<legend><?=Tr::_('Orders')?></legend>
		<fieldset>
			<?=Admin_Managers::Order()->showOrdersOfCustomer( $customer )?>
		</fieldset>
		
		<?=EMailMarketing::SubscriptionManager()->showStatus( $customer->getEshop(), $customer->getEmail() )?>
	
</div>

