<?php
namespace JetShopModule\Admin\Customers;

use JetShop\Customer as Customer;

use Jet\UI;
use Jet\UI_dataGrid;
use Jet\UI_button;

use Jet\Tr;
use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Form         $filter_form
 */
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );
$router = $this->getController()->getControllerRouter();


$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( Customer $item ) use ( $router ) {
		if( ( $edit_uri = $router->action('edit')->URI( $item->getId() ) ) ):
			echo UI::button_edit(Tr::_('view'))->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;
	}
);
$c_edit->addCustomCssStyle( 'width:100px;' );

$grid->getColumn( 'id' )->addCustomCssStyle( 'width:120px;' );

$grid->getColumn( 'email' )->setRenderer(
	function( Customer $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getId() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getEmail();?></a>
		<?php
	}
);
$grid->getColumn( 'email' )->addCustomCssStyle( 'width:250px;' );

$grid->getColumn( 'id' )->setRenderer(
	function( Customer $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getId() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getId();?></a>
		<?php
	}
);

$grid->getColumn( 'shop_code' )->setRenderer(
	function( Customer $item ) use ( $router ) {
		echo $item->getShop()->getShopName();
	}
);
$grid->getColumn('shop_code')->addCustomCssStyle('width:150px');

$grid->getColumn( 'first_name' )->setRenderer(
	function( Customer $item ) use ( $router ) {
		echo $item->getFirstName();
	}
);
$grid->getColumn('first_name')->addCustomCssStyle('width:250px');

$grid->getColumn( 'surname' )->setRenderer(
	function( Customer $item ) use ( $router ) {
		echo $item->getSurname();
	}
);
//$grid->getColumn('surname')->setCssStyle('width:250px');

?>

<?=$filter_form->start()?>
<div class="row toolbar">
	<div class="col-md-3 col-sm-12">
		<?= $filter_form->field( 'search' )->input() ?>
	</div>
	<div class="col-md-4 col-sm-12">
		<table>
			<tr>
				<td><?=$filter_form->field('shop')->label()?></td>
				<td><?=$filter_form->field('shop')->input()->addJsAction('onchange', 'this.form.submit()')?></td>
			</tr>
		</table>
	</div>

</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
