<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Marketing\PromoAreas;

use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );


echo $form->field( 'relevance_mode' );
echo $form->field( 'promo_area_id' );
echo $form->field( 'html' );
