<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Catalog\SetProductPrices;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

/**
 * @var MVC_View   $this
 */
?>
<div id="main-col">
	
	<?=$this->getRaw('tabs')?>

	<div style="display: grid;grid-template-columns: 200px 1fr; align-items: center;gap: 10px;margin: 10px;">
		<?=$this->render('select'); ?>
		
		<div></div>
		<div>
		<?php
		echo UI::button(Tr::_('Export'))
			->setUrl(Http_Request::currentURI(set_GET_params: ['export'=>'export']))
			->setClass(UI_button::CLASS_PRIMARY);
		?>
		</div>
	</div>
</div>