<?php
namespace JetApplicationModule\Admin\Catalog\SetProductPrices;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI_tabs;
use JetApplication\Brand;
use JetApplication\Pricelists;
use JetApplication\Pricelist;
use JetApplication\Supplier;

/**
 * @var MVC_View   $this
 * @var UI_tabs $tabs
 * @var ?Pricelist $selected_pricelist
 */
$tabs = $this->getRaw('tabs');


$selected_pricelist = $this->getRaw('selected_pricelist')?:null;
$selected_pricelist_code = $selected_pricelist?->getCode();


$product_identifiers = $this->getRaw('product_identifiers');
$product_identifier = $this->getString('product_identifier');

$select_by_scope = $this->getRaw('select_by_scope');
$select_by = $this->getString('select_by');
?>

	<div><b><?=Tr::_('Pricelist:')?></b></div>

	<div style="display: flex;gap: 10px;">
	<?php foreach(Pricelists::getList() as $pricelist):
		if($pricelist->getCode()==$selected_pricelist_code): ?>
			<div><b class="btn btn-success"><?=$pricelist->getName()?></b></div>
		<?php else:  ?>
			<div><a href="<?=Http_Request::currentURI(set_GET_params: ['pricelist'=>$pricelist->getCode()], unset_GET_params: ['do_it', 'price_list'])?>" class="btn btn-light"><?=$pricelist->getName()?></a></div>
		<?php endif;
	endforeach; ?>
	</div>


	<div><b><?=Tr::_('Select by:')?></b></div>
	
	<div style="display: flex;gap: 10px;">
	<?php foreach($select_by_scope as $idf=>$name):
		if($select_by==$idf): ?>
			<div><b class="btn btn-success"><?=$name?></b></div>
		<?php else:  ?>
			<div><a href="<?=Http_Request::currentURI(set_GET_params: ['select_by'=>$idf], unset_GET_params: ['do_it', 'price_list'])?>" class="btn btn-light"><?=$name?></a></div>
		<?php endif;
	endforeach; ?>
	</div>
	
	<?php if($select_by=='supplier'): ?>
		<div><b><?=Tr::_('Supplier:')?></b></div>

		<div>
			<form method="get">
				<input type="hidden" name="pricelist" value="<?=$selected_pricelist_code?>">
				<input type="hidden" name="product_identifier" value="<?=$product_identifier?>">
				<input type="hidden" name="select_by" value="<?=$select_by?>">

				<select name="supplier" onchange="this.form.submit()" class="form-control">
					<option></option>
					<?php foreach(Supplier::getScope() as $id=>$name):
						if($id==$this->getInt('supplier_id')):
							?><option value="<?=$id?>" selected><?=$name?></option><?php
						else:
							?><option value="<?=$id?>"><?=$name?></option><?php
						endif;
					endforeach; ?>
				</select>
			</form>
		</div>
	<?php endif; ?>
	
	
	<?php if($select_by=='brand'): ?>
		<div><b><?=Tr::_('Brand:')?></b></div>

		<div>
			<form method="get">
				<input type="hidden" name="pricelist" value="<?=$selected_pricelist_code?>">
				<input type="hidden" name="product_identifier" value="<?=$product_identifier?>">
				<input type="hidden" name="select_by" value="<?=$select_by?>">

				<select name="brand" onchange="this.form.submit()" class="form-control">
					<option></option>
					<?php foreach(Brand::getScope() as $id=>$name):
						if($id==$this->getInt('brand_id')):
							?><option value="<?=$id?>" selected><?=$name?></option><?php
						else:
							?><option value="<?=$id?>"><?=$name?></option><?php
						endif;
					endforeach; ?>
				</select>
			</form>
		</div>
	<?php endif; ?>

	
	
<?php if($product_identifiers): ?>
	<div><b><?=Tr::_('Product identifier:')?></b></div>
	
	<div style="display: flex;gap: 10px;">
	<?php foreach($product_identifiers as $idf=>$name):
		if($product_identifier==$idf): ?>
			<div><b class="btn btn-success"><?=$name?></b></div>
		<?php else:  ?>
			<div><a href="<?=Http_Request::currentURI(set_GET_params: ['product_identifier'=>$idf], unset_GET_params: ['do_it', 'price_list'])?>" class="btn btn-light"><?=$name?></a></div>
		<?php endif;
	endforeach; ?>
	</div>
<?php endif; ?>










