<?php
namespace JetApplicationModule\Admin\Entity\WithEShopData;

use Jet\MVC_View;
use Jet\UI;
use JetApplication\Admin_Entity_WithEShopData_Interface;
use JetApplication\Entity_WithEShopData;

/**
 * @var MVC_View $this
 * @var Entity_WithEShopData|Admin_Entity_WithEShopData_Interface     $item
 */
$item = $this->getRaw('item');
?>
<?=$item->getAdminTitle()?> <a href="<?=$item->getEditURL()?>"><?=UI::icon('link')?></a>
