<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Form;
use Jet\Tr;
use Jet\MVC_View;
use JetShop\Category;
use JetShop\Shops;

/**
 * @var MVC_View   $this
 * @var Category   $new_category
 */

$new_category = $this->getRaw('new_category');
$form = $new_category->getAddForm();
$form->setDefaultLabelWidth([Form::LJ_SIZE_MEDIUM=>2]);
$form->setDefaultFieldWidth([Form::LJ_SIZE_MEDIUM=>8]);

?>


<?=$this->render('lj_start')?>
<br/>
	<?=$form->start();?>

		<?=$form->field('target_category_id')?>

		<div class="form-group row" style="padding-bottom: 30px">
			<label class="col-md-2 col-form-label"><?=Tr::_('Target category:')?></label>
			<div class="col-md-8">
				<?=Category::renderSelectCategoryWidget("$('#add_form__target_category_id').val(selected_item.id);", 0 )?>
			</div>
		</div>


		<?php foreach(Shops::getList() as $shop):
			$shop_key = $shop->getKey();
			$shop_data = $new_category->getShopData( $shop );
			?>
			<?=$shop_data->renderShopDataBlock_start()?>

				<fieldset>
					<legend class="sub"><?=Tr::_('Main data')?></legend>

					<?=$form->field('/shop_data/'.$shop_key.'/is_active')?>

					<?=$form->field('/shop_data/'.$shop_key.'/name')?>
					<?=$form->field('/shop_data/'.$shop_key.'/second_name')?>

				</fieldset>

			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach; ?>

	<?=$form->end();?>

<?=$this->render('lj_end')?>

