<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Catalog\Categories;


use Jet\MVC_View;
use Jet\UI;
use JetApplication\Category;

/**
 * @var MVC_View   $this
 * @var Category $new_category
 */

$new_category = $this->getRaw('new_category');

$form_id = $new_category->getAddForm()->getId();
?>
<?=UI::button_save()->setOnclick("$('#$form_id').submit();")?>
