<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\UI;
use Jet\Form;
use Jet\Tr;
use Jet\Mvc;
use Jet\Mvc_View;
use JetShop\Category;
use JetShop\Shops;
use JetShopAdmin\Shop_Admin;

/**
 * @var Mvc_View   $this
 * @var Category   $new_category
 */

$new_category = $this->getRaw('new_category');
$form = $new_category->getAddForm();
$form->setDefaultLabelWidth([Form::LJ_SIZE_MEDIUM=>2]);
$form->setDefaultFieldWidth([Form::LJ_SIZE_MEDIUM=>8]);

?>


<?=$this->render('lj_start')?>
<br/>
<?=$form->start();?>
		<?php foreach(Shops::getList() as $shop):
			$shop_id= $shop->getId();
			$shop_data = $new_category->getShopData( $shop_id );
			?>
			<?=$shop_data->renderShopDataBlock_start()?>

				<fieldset>
					<legend class="sub"><?=Tr::_('Main data')?></legend>

					<?=$form->field('/shop_data/'.$shop_id.'/is_active')?>

					<?=$form->field('/shop_data/'.$shop_id.'/name')?>
					<?=$form->field('/shop_data/'.$shop_id.'/second_name')?>
					<?=$form->field('/shop_data/'.$shop_id.'/description')?>
				</fieldset>

				<fieldset>
					<legend class="sub"><?=Tr::_('SEO')?></legend>
					<?=$form->field('/shop_data/'.$shop_id.'/seo_h1')?>
					<?=$form->field('/shop_data/'.$shop_id.'/seo_title')?>
					<?=$form->field('/shop_data/'.$shop_id.'/seo_description')?>
					<?=$form->field('/shop_data/'.$shop_id.'/seo_keywords')?>
					<?=$form->field('/shop_data/'.$shop_id.'/internal_fulltext_keywords')?>
				</fieldset>

			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach; ?>
<?=$form->end();?>

<?=$this->render('lj_end')?>

