<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\ShoppingCart;


use Jet\UI;
use Jet\Tr;
use Jet\UI_icon;

$title = UI::icon('user')->setSize(UI_icon::SIZE_NORMAL).' '.Tr::_( 'Password reset' );

$dialog = UI::dialog('password_reset', $title);

echo $dialog->start();
?>
	<div id="password_reset_area"></div>
	<?php
echo $dialog->end();
