<?php

use Jet\UI_dialog;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var UI_dialog $d
 */
$d = $this->getRaw( 'element' );

$size_class = match ($d->getSize()) {
	UI_dialog::SIZE_DEFAULT => '',
	UI_dialog::SIZE_SMALL => 'modal-sm',
	UI_dialog::SIZE_LARGE => 'modal-lg',
	UI_dialog::SIZE_EXTRA_LARGE => 'modal-xl',
};
?>
<dialog id="<?= $d->getId() ?>">
	<div class="dialog-header">
		<div><?= $d->getTitle() ?></div>
		<button type="button" aria-label="Close" onclick="dialog.close('<?=$d->getId()?>')">&times;</button>
	</div>
	<div class="dialog-body">

