<?php
namespace JetShop;

use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View $this
 * @var ProductListing_Filter_Properties_Property_Number $filter_property
 */
$filter_property = $this->getRaw('filter_property');
$property = $filter_property->getProperty();

$filter_min  = $this->getFloat('filter_min');
$filter_max  = $this->getFloat('filter_max');


$min_value = $this->getFloat('min_value');
$max_value = $this->getFloat('max_value');


$e_id = $property->getId();

?>

<div class="group-sub-content-dim">
	<?php if( $property->getDescription() || $property->getImageMain() ): ?>
		<div class="title">
			<?=$property->getLabel(); ?>
			<?php if ($property->getDescription()): ?>
				<span class="label-description" data-tooltip title="<?= htmlspecialchars($property->getDescription() ) ?>">i</span>
			<?php endif; ?>
			<div class="group-sub-description-info" onmouseover="ProductListing.showPropertyInfo(<?=$e_id;?>);" onmouseout="ProductListing.hidePropertyInfo(<?=$e_id;?>);" style="width: 12px;height: 12px;"> </div>
		</div>
		<div class="group-sub-description-content" id="filter_property_info_<?=$e_id;?>">
			<?php if($property->getImageMain()): ?>
				<img src="<?=$property->getImageMainUrl()?>" />
			<?php endif; ?>
		</div>
		<div style="clear: both;"></div>
	<?php else: ?>
		<div class="title"><?=$property->getLabel(); ?></div>
	<?php endif; ?>


	<div class="box">
		<div>
			<span class="from">
				<span id="filter_value_from_<?= $e_id ?>"><?= $filter_min ?></span>
				<span><?= $property->getUnits() ?></span>
			</span>
			<span class="slider" id="filter_slider_range_<?= $e_id ?>"></span>
			<span class="to">
				<span id="filter_value_to_<?= $e_id ?>"><?= $filter_max ?></span>
				<span><?= $property->getUnits() ?></span>
			</span>
		</div>
	</div>

	<script type="text/javascript">

		$(function(){
			ProductListing.filter.properties.number.init(
				<?=$property->getId()?>,
				<?=$min_value; ?>,
				<?=$max_value; ?>,
				<?=$filter_min; ?>,
				<?=$filter_max; ?>
			);
		});

	</script>

</div>

