<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Form;
use Jet\Tr;
use Jet\MVC_View;
use JetShop\Category;
use JetShop\Shops;

/**
 * @var MVC_View   $this
 */

$category = Controller_Main::getCurrentCategory();
$form = $category->getEditForm();
$form->setDefaultLabelWidth([Form::LJ_SIZE_MEDIUM=>2]);
$form->setDefaultFieldWidth([Form::LJ_SIZE_MEDIUM=>8]);

?>
<?=$this->render('lj_start')?>
<?=$form->start();?>

		<?=$form->field('target_category_id')?>

		<div class="form-group row" style="padding-bottom: 30px;margin-top: 30px;">
			<label class="col-md-2 col-form-label"><?=Tr::_('Target category:')?></label>
			<div class="col-md-8">
				<?=Category::renderSelectCategoryWidget("$('#edit_form__target_category_id').val(selected_item.id);", $category->getTargetCategoryId() )?>
			</div>
		</div>

		<?php foreach(Shops::getList() as $shop):
			$shop_key = $shop->getKey();

			$shop_data = $category->getShopData( $shop );
			?>
			<?=$shop_data->renderShopDataBlock_start()?>

				<fieldset>
					<legend class="sub"><?=Tr::_('Main data')?></legend>

					<?=$form->field('/shop_data/'.$shop_key.'/is_active')?>

					<?=$form->field('/shop_data/'.$shop_key.'/name')?>
					<?=$form->field('/shop_data/'.$shop_key.'/second_name')?>
					<?=$form->field('/shop_data/'.$shop_key.'/description')?>
				</fieldset>

				<fieldset>
					<legend class="sub"><?=Tr::_('SEO')?></legend>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_disable_canonical')?>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_h1')?>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_title')?>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_description')?>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_keywords')?>
					<?=$form->field('/shop_data/'.$shop_key.'/internal_fulltext_keywords')?>
				</fieldset>
			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach; ?>

<?=$form->end();?>

<?=$this->render('lj_end')?>