<?php
namespace JetApplicationModule\Admin\Marketing\AutoOffers;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use JetApplication\Admin_Managers;
use JetApplication\Marketing_AutoOffer;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Marketing_AutoOffer $item
 */
$form = $this->getRaw('form');
$item = $this->getRaw('item');


?>
	<div class="row form-group">
		<label class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?= Tr::_('Offer:')?></label>
		<div class="col-md-8" style="padding-bottom: 10px">
			<?=Admin_Managers::Product()->renderSelectWidget(
				"$('#{$form->field('offer_product_id')->getId()}').val(selected_item.id)",
				selected_product_id: $item->getOfferProductId()
			);?>
		</div>
	</div>
<?php
echo $form->field( 'offer_product_id' );

echo $form->field( 'priority' );
echo $form->field( 'relevance_mode' );
echo $form->field( 'show_mode' );
echo $form->field( 'label' );
echo $form->field( 'description' );

