<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\WarehouseManagement\StockStatusOverview;

use Jet\Locale;
use Jet\MVC_View;
use JetApplication\WarehouseManagement_StockCard;
use JetApplication\Admin_Managers_Entity_Listing;

/**
 * @var MVC_View $this
 * @var Admin_Managers_Entity_Listing $listing
 * @var WarehouseManagement_StockCard $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=Locale::float($item->getAvailable());?></a>
<?php
