<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\WarehouseManagement\StockStatusOverview;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_badge;
use JetApplication\WarehouseManagement_StockCard;
use JetApplication\Application_Service_Admin_EShopEntity_Listing;

/**
 * @var MVC_View $this
 * @var Application_Service_Admin_EShopEntity_Listing $listing
 * @var WarehouseManagement_StockCard $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');

if($item->getCancelled()):
	echo UI::badge( UI_badge::SUCCESS, Tr::_('Cancelled') )->addCustomCssStyle('padding:10px');
else:
	echo UI::badge( UI_badge::SUCCESS, Tr::_('Active') )->addCustomCssStyle('padding:10px');
endif;
