<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\WarehouseManagement\StockStatusOverview;

use Jet\Locale;
use Jet\MVC_View;
use JetApplicationModule\Admin\Entity\Listing\Listing;

/**
 * @var MVC_View $this
 * @var Listing $listing
 * @var StockCard $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=Locale::float($item->getInStock());?></a>
<?php
