<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\WarehouseManagement\StockStatusOverview;

use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Admin_Managers;use JetApplicationModule\Admin\Entity\Listing\Listing;

/**
 * @var MVC_View $this
 * @var Listing $listing
 * @var StockCard $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<?=Admin_Managers::Product()->showName( $item->getProductId() ) ?><br>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=Tr::_('Show stock card');?></a>
<?php
