<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\WarehouseManagement\StockStatusOverview;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\WarehouseManagement_StockCard;
use JetApplication\Application_Service_Admin;
use JetApplication\Application_Service_Admin_EShopEntity_Listing;

/**
 * @var MVC_View $this
 * @var Application_Service_Admin_EShopEntity_Listing $listing
 * @var WarehouseManagement_StockCard $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<?=Application_Service_Admin::Product()->renderItemName( $item->getProductId() ) ?><br>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=Tr::_('Show stock card');?></a>
<?php
