<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\WarehouseManagement\StockStatusOverview;


use Jet\MVC_View;
use JetApplication\WarehouseManagement_Warehouse;
use JetApplication\WarehouseManagement_StockCard;
use JetApplication\Admin_Managers_EShopEntity_Listing;

/**
 * @var MVC_View $this
 * @var Admin_Managers_EShopEntity_Listing $listing
 * @var WarehouseManagement_StockCard $item
 */

$warehouses = WarehouseManagement_Warehouse::getScope();

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=$warehouses[$item->getWarehouseId()];?></a>
<?php
