<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\WarehouseManagement\StockStatusOverview;

use Jet\MVC_View;
use JetApplication\WarehouseManagement_Warehouse;
use JetApplicationModule\Admin\Entity\Listing\Listing;

/**
 * @var MVC_View $this
 * @var Listing $listing
 * @var StockCard $item
 */

$warehouses = WarehouseManagement_Warehouse::getScope();

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=$warehouses[$item->getWarehouseId()];?></a>
<?php
