<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Admin_Managers;


/**
 * @var MVC_View $this
 * @var Listing_Filter_Categories $filter
 */

$filter = $this->getRaw('filter');
$listing = $filter->getListing();
$filter_form = $listing->getFilterForm();

?>


<script>
	let productFilter = {
		addCategory: function( id )
		{
			let categories = document.getElementById('filter_form__categories');

			let new_value;
			if(categories.value.length) {
				new_value = categories.value.split(',');
				if(!new_value.includes(id)) {
					new_value.push(id);
				}

				new_value = new_value.join(',');

			} else {
				new_value = id;
			}

			categories.value = new_value;

			document.getElementById('filter_form').submit();
		},

		removeCategory: function( id )
		{
			let categories = document.getElementById('filter_form__categories');

			let new_value = '';
			if(categories.value.length) {
				new_value = categories.value.split(',');
				let _new_value = [];
				for(let i=0;i<new_value.length;i++) {
					if(new_value[i]!=id) {
						_new_value.push(new_value[i]);
					}
				}
				new_value = _new_value.join(',');
			}

			categories.value = new_value;

			document.getElementById('filter_form').submit();

		}
	};
</script>

<?php
$field = $filter_form->field('categories');

echo Admin_Managers::EntityListing()->renderListingFilter(
	filter:      $filter,
	title:       Tr::_('Categories'),
	form_fields: [$field],
	is_active:   count($filter->getSelectedCategoryIds())>0,
	renderer:    function() use ($field, $filter) {
		?>
		<?=$field->input()?>
		
		<div>
			<div style="width: 300px;">
				<?=Admin_Managers::Category()->renderSelectWidget("productFilter.addCategory(selected_item.id)")?>
			</div>
			
			<?php foreach( $filter->getSelectedCategoryIds() as $c_id ): ?>
				<div style="margin: 3px;display: inline-block;padding: 3px;">
					<?=UI::button(' '.Admin_Managers::Category()->getName( $c_id ) )
						->setIcon('trash')
						->setClass('light')
						->setSize(UI_button::SIZE_EXTRA_SMALL)
						->setOnclick("productFilter.removeCategory({$c_id})")?>
				</div>
			<?php endforeach; ?>
		</div>
		<?php
	}
);
