<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Admin_Managers;


/**
 * @var MVC_View $this
 * @var Listing_Filter_ProductType $filter
 */

$listing = $this->getRaw( 'listing' );
$filter = $this->getRaw('filter');
$filter_form = $listing->getFilterForm();
$field = $filter_form->field( 'product_type' );
$field->input()->addJsAction( 'onchange', 'this.form.submit()' );

echo Admin_Managers::EntityListing()->renderListingFilter(
	filter:      $filter,
	title:       Tr::_('Product type'),
	form_fields: [$field],
	is_active:   $field->getValue(),
	renderer:    function() use ($field) {
		?>
		<div><?= $field->input() ?></div>
		<?php
	}
);
