<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\Form_Renderer;use Jet\MVC_View;


/**
 * @var MVC_View $this
 * @var Listing_Filter_ProductType $filter
 */

$filter = $this->getRaw('filter');
$listing = $filter->getListing();
$filter_form = $listing->getFilterForm();

$field = $filter_form->field( 'product_type' );

$field->input()->addJsAction( 'onchange', 'this.form.submit()' );
//$field->label()->addCustomCssClass( 'text-right' );



$field->label()->setWidth([
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 12,
	Form_Renderer::LJ_SIZE_LARGE => 12,
]);

$field->input()->setWidth([
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 12,
	Form_Renderer::LJ_SIZE_LARGE => 12,

]);

?>
<?= $field ?>

