<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\MVC_View;
use JetApplication\Payment_Method_ShopData;
use JetApplication\Shop_Managers;

/**
 * @var MVC_View $this
 * @var Payment_Method_ShopData $method
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');

$pricelist = $cash_desk->getPricelist();
$method = $this->getRaw('payment_method');

?>
<div class="price">
<?php if($method->getDefaultPrice($pricelist)!=$method->getPrice($pricelist)):?>
	<div class="price-standard"><?=Shop_Managers::PriceFormatter()->formatWithCurrency($method->getDefaultPrice($pricelist), $pricelist->getCurrency());?></div>
<?php endif; ?>
	<div class="price-final"><?=Shop_Managers::PriceFormatter()->formatWithCurrency($method->getPrice($pricelist), $pricelist->getCurrency());?></div>
</div>