<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Invoices;



use Jet\Form_Renderer;
use Jet\Locale;
use Jet\Tr;
use Jet\UI;use JetApplication\Admin_Managers;
use JetApplication\Admin_Managers_EShopEntity_Listing;

use Jet\MVC_View;
use JetApplication\Invoice_Item;
use JetApplication\EShops;
use JetApplication\Invoice;

/**
 * @var MVC_View $this
 * @var Invoice     $invoice
 * @var Admin_Managers_EShopEntity_Listing $listing
 */

$invoice = $this->getRaw( 'invoice' );
$invoice = $invoice->getNewCorrectionInvoice();

$listing = $this->getRaw('listing');

$is_editable = $invoice->isEditable();

$price_formatter = Admin_Managers::PriceFormatter();
$product_manager = Admin_Managers::Product();
$icons = Invoice_Item::getItemIcons();

$has_VAT = $invoice->hasVAT();

$correction_form = $invoice->getCreateCorrectionInvoiceForm();

$correction_form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 12
]);
$correction_form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 12
]);

?>
<?=$correction_form->start()?>
<div class="toolbar" id="main-toolbar">
	<?=UI::button_save()?>
</div>
<div id="main-col">
	<div style="padding: 10px;display: flex;gap: 50px;">

		<div class="card">

			<div class="card-header"><b><?=Tr::_('Common information')?></b></div>
			<div class="card-body">


				<table style="margin: 10px">
					
					<?php if(EShops::isMultiEShopMode()): ?>
						<tr>
							<td><b><?=Tr::_('e-shop')?></b></td>
							<td style="padding: 3px"><?=$invoice->getEshop()->getName()?></td>
						</tr>
					<?php endif; ?>
					<?php if($invoice->getOrderId()): ?>
						<tr>
							<td nowrap=""><b><?=Tr::_('Order:')?></b></td>
							<td nowrap="" style="padding: 3px"><?=Admin_Managers::Order()->showName(  $invoice->getOrderId() )?></td>
						</tr>
					<?php endif; ?>
					

				</table>
				
				<?php
				echo $correction_form->field('payment_kind');
				echo $correction_form->field('invoice_date');
				echo $correction_form->field('date_of_taxable_supply');
				echo $correction_form->field('due_date');
				echo $correction_form->field('reason');
				
				?>
				
			</div>
		</div>

		<div class="card">
			<div class="card-header"><b><?=Tr::_('Customer')?></b></div>
			<div class="card-body">
				<?=Admin_Managers::Customer()->showName( $invoice->getCustomerId() )?>
				<br>
				
				<?=Admin_Managers::Customer()->formatAddress( $invoice->getEshop(), $invoice->getCustomerAddress() )?>

				<table>
					<tr>
						<td><?=Tr::_('Phone:')?></td>
						<td><?=$invoice->getCustomerPhone()?></td>
					</tr>
					<tr>
						<td><?=Tr::_('e-mail:')?></td>
						<td><a href="mailto:<?=$invoice->getCustomerEmail()?>"><u><?=$invoice->getCustomerEmail()?></u></a></td>
					</tr>
				</table>


			</div>
		</div>

		<div class="card">
			<div class="card-header"><b><?=Tr::_('Issuer')?></b></div>
			<div class="card-body">
				
				<?=Admin_Managers::Customer()->formatAddress( $invoice->getEshop(), $invoice->getIssuerAddress() )?>
				<div style="font-size: 0.8rem">
					<?=$invoice->getIssuerInfo()?>
				</div>

			</div>
		</div>


		<div style="margin: 10px;">
		</div>
	</div>


	<table class="table table-striped">
		<thead>
		<tr>
			<th style="width: 20px;"></th>
			<th style="width: 140px;"></th>
			<th><?=Tr::_('Item')?></th>
			
			<?php if($has_VAT): ?>
			<th style="width: 200px;"><?=Tr::_('Price per item with VAT')?></th>
			<?php endif; ?>
			<th style="width: 200px;"><?=Tr::_('Price per item without VAT')?></th>
			<th style="width: 100px;"><?=Tr::_('VAT rate')?></th>
			<th style="width: 200px;"><?=Tr::_('Total amount without VAT')?></th>
			
			<?php if($has_VAT): ?>
				<th style="width: 200px;"><?=Tr::_('Total amount with VAT')?></th>
			<?php endif; ?>
		</tr>
		</thead>
		<tbody>
		<?php
		$showItem = function( int $i, Invoice_Item $item ) use ($product_manager, $icons, $price_formatter, $invoice, $has_VAT, $correction_form) {
			?>
			<tr id="item_<?=$item->getId()?>">
				<td style="text-align: center"><?=$icons[$item->getType()]?></td>
				<td>
					<div style="display: flex;align-items: center;gap: 5px;">
						<?=$correction_form->field('/number_of_units/'.$i)->input()?>
						<b>&nbsp;<?=$item->getMeasureUnit()?->getName()?></b>
					</div>
				</td>
				<td>
					<?php if( $item->isPhysicalProduct() || $item->isVirtualProduct() ): ?>
						<a href="<?=$product_manager::getEditUrl( $item->getItemId() )?>"><?=$item->getTitle() ?></a>
					<?php else: ?>
						<?=$item->getTitle() ?>
					<?php endif; ?>
				</td>
			
				<?php if($has_VAT): ?>
				<td>
					<div style="display: flex;align-items: center;gap: 5px;">
					<?=$invoice->getCurrency()->getSymbolLeft_WithVAT()?>
					<?=$correction_form->field('/price_per_unit_with_vat/'.$i)->input()?>
					<?=$invoice->getCurrency()->getSymbolRight_WithVAT()?>
					</div>
				</td>
				<?php endif; ?>
				

				<td>
					<div style="display: flex;align-items: center;gap: 5px;">
					<?=$invoice->getCurrency()->getSymbolLeft_WithoutVAT()?>
					<?=$correction_form->field('/price_per_unit_without_vat/'.$i)->input()?>
					<?=$invoice->getCurrency()->getSymbolRight_WithoutVAT()?>
					</div>
				</td>
				
				<td>
					<div style="display: flex;align-items: center;gap: 5px;">
						<?=$correction_form->field('/vat_rate/'.$i)->input()?>
						%
					</div>
				</td>

				<td>
					<div style="display: flex;align-items: center;gap: 5px;">
						<?=$invoice->getCurrency()->getSymbolLeft_WithoutVAT()?>
						<?=$correction_form->field('/total_amount_without_vat/'.$i)->input()?>
						<?=$invoice->getCurrency()->getSymbolRight_WithoutVAT()?>
					</div>
				</td>
				<?php if($has_VAT): ?>
					<td>
						<div style="display: flex;align-items: center;gap: 5px;">
							<?=$invoice->getCurrency()->getSymbolLeft_WithVAT()?>
							<?=$correction_form->field('/total_amount_with_vat/'.$i)->input()?>
							<?=$invoice->getCurrency()->getSymbolRight_WithVAT()?>
						</div>
					</td>
				<?php endif; ?>

			</tr>
			<?php
			
			if($item->getSetItems()):
				foreach($item->getSetItems() as $set_item):
					?>
					<tr style="opacity: 0.3">
						<td style="text-align: center">
						</td>
						<td style="text-align: right"><b><?=Locale::float($set_item->getNumberOfUnits()) ?>&nbsp;<?=$set_item->getMeasureUnit()?->getName()?></b></td>
						<td>
							<a href="<?=$product_manager::getEditUrl( $set_item->getItemId() )?>"><?=$set_item->getTitle() ?></a>
						</td>




						<td><?=$price_formatter->formatWithCurrency_WithoutVAT( $invoice->getCurrency(), $set_item->getPricePerUnit_WithoutVat() )?></td>
						<td><?=$item->getVatRate()?>%</td>
						
						<td><?=$price_formatter->formatWithCurrency_WithoutVAT( $invoice->getCurrency(), $set_item->getTotalAmount_WithoutVat()*$item->getNumberOfUnits() )?></td>
						<?php if($has_VAT): ?>
							<td><?=$price_formatter->formatWithCurrency_WithVAT( $invoice->getCurrency(), $set_item->getTotalAmount_WithVat()*$item->getNumberOfUnits() )?></td>
						<?php endif; ?>



					</tr>
				<?php
				endforeach; ?>
				<tr style="opacity: 0.5">
					<td></td>
					<td></td>
					<td colspan="99">
						<i><?=Tr::_('Set discount:')?></i>
						<i><?=$price_formatter->formatWithCurrencyByHasVAT($has_VAT, $invoice->getCurrency(), $item->getSetDiscountPerUnit())?></i>
						<?php if($item->getNumberOfUnits()>1): ?> / <i><?=$price_formatter->formatWithCurrencyByHasVAT($has_VAT, $invoice->getCurrency(), $item->getSetDiscountPerUnit()*$item->getNumberOfUnits())?></i><?php endif; ?>
					</td>
				</tr>
			<?php
			endif;
		};
		?>
		
		<?php
		$i = 0;
		foreach( $invoice->getItems() as $item ):
			$i++;
			if(
				$item->getType()==Invoice_Item::ITEM_TYPE_PRODUCT ||
				$item->getType()==Invoice_Item::ITEM_TYPE_VIRTUAL_PRODUCT
			) {
				$showItem( $i, $item );
			}
		endforeach;
		
		$i = 0;
		foreach( $invoice->getItems() as $item ):
			$i++;
			if(
				$item->getType()==Invoice_Item::ITEM_TYPE_GIFT ||
				$item->getType()==Invoice_Item::ITEM_TYPE_VIRTUAL_GIFT
			) {
				$showItem( $i, $item );
			}
		endforeach;
		
		$i = 0;
		foreach( $invoice->getItems() as $item ):
			$i++;
			if(
				$item->getType()==Invoice_Item::ITEM_TYPE_SERVICE
			) {
				$showItem( $i, $item );
			}
		endforeach;
		
		$i = 0;
		foreach( $invoice->getItems() as $item ):
			$i++;
			if(
				$item->getType()==Invoice_Item::ITEM_TYPE_PAYMENT ||
				$item->getType()==Invoice_Item::ITEM_TYPE_DELIVERY
			) {
				$showItem( $i, $item );
			}
		endforeach;
		
		$i = 0;
		foreach( $invoice->getItems() as $item ):
			$i++;
			if(
				$item->getType()==Invoice_Item::ITEM_TYPE_DISCOUNT
			) {
				$showItem( $i, $item );
			}
		endforeach;
		
		
		?>
		</tbody>
	</table>
</div>
<?=$correction_form->end()?>

<script>
	const CorrectionInvoice = {
		p: null,
		
		init: (input ) => {
			let p = {
				i: input.dataset['i'],
				round_vat: input.dataset['round_vat'],
				round_with_vat: input.dataset['round_with_vat'],
				round_without_vat: input.dataset['round_without_vat'],
				vat: input.dataset['vat'],
			};
			
			p.vat_mtp = 1+(p.vat/100);
			
			p['number_of_units'] = document.getElementById('correction_invoice_form_____number_of_units___'+p['i']);
			p['price_per_unit_without_vat'] = document.getElementById('correction_invoice_form_____price_per_unit_without_vat___'+p['i']);
			p['total_amount_without_vat'] = document.getElementById('correction_invoice_form_____total_amount_without_vat___'+p['i']);
			
			<?php if($has_VAT): ?>
			p['price_per_unit_with_vat'] = document.getElementById('correction_invoice_form_____price_per_unit_with_vat___'+p['i']);
			p['total_amount_with_vat'] = document.getElementById('correction_invoice_form_____total_amount_with_vat___'+p['i']);
			<?php endif; ?>
			
			CorrectionInvoice.p = p;
		},
		
		calcNumberOfUnits: () => {
			CorrectionInvoice.p['total_amount_without_vat'].value = CorrectionInvoice.round_WithoutVAT(
				Number.parseFloat(CorrectionInvoice.p['price_per_unit_without_vat']['value']) * Number.parseFloat(CorrectionInvoice.p['number_of_units']['value'])
			);
			
			<?php if($has_VAT): ?>
			CorrectionInvoice.p['total_amount_with_vat'].value = CorrectionInvoice.round_WithVAT(
				Number.parseFloat(CorrectionInvoice.p['price_per_unit_with_vat']['value']) * Number.parseFloat( CorrectionInvoice.p['number_of_units']['value'] )
			);
			<?php endif; ?>
		},

		round_VAT: ( value ) => {
			return Number.parseFloat( value ).toFixed( CorrectionInvoice.p['round_vat'] );
		},

		round_WithVAT: ( value ) => {
			return Number.parseFloat( value ).toFixed( CorrectionInvoice.p['round_with_vat'] );
		},

		round_WithoutVAT: ( value ) => {
			return Number.parseFloat( value ).toFixed( CorrectionInvoice.p['round_without_vat'] );
		},
		
		
		calcItem_numberOfUnits: ( input ) => {
			CorrectionInvoice.init( input );
			CorrectionInvoice.calcNumberOfUnits();
		},
		
		calcItem_WithVAT: ( input ) => {
			CorrectionInvoice.init( input );

			CorrectionInvoice.p['price_per_unit_without_vat']['value'] = CorrectionInvoice.round_WithoutVAT(
				CorrectionInvoice.p['price_per_unit_with_vat']['value'] / CorrectionInvoice.p.vat_mtp
			);

			CorrectionInvoice.calcNumberOfUnits();
		},
		calcItem_WithoutVAT: ( input ) => {
			CorrectionInvoice.init( input );
			
			<?php if($has_VAT): ?>
			CorrectionInvoice.p['price_per_unit_with_vat']['value'] = CorrectionInvoice.round_WithVAT(
				CorrectionInvoice.p['price_per_unit_without_vat']['value'] * CorrectionInvoice.p.vat_mtp
			);
			<?php endif; ?>
			
			CorrectionInvoice.calcNumberOfUnits();
		}
		
	};
</script>