<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Invoices;


use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Application_Service_Admin;
use JetApplication\Invoice;

/**
 * @var MVC_View $this
 * @var Invoice[] $invoices
 */

$invoices = $this->getRaw('invoices');
if(!count($invoices)) {
	return;
}

$price_formatter = Application_Service_Admin::PriceFormatter();
?>
<table class="table table-striped">
	<thead>
	<tr>
		<th style="width: 200px"></th>
		<th style="width: 200px"><?=Tr::_('Number')?></th>
		<th style="width: 200px"><?=Tr::_('Date')?></th>
		<th style="width: 200px"><?=Tr::_('Total')?></th>
		<th></th>
	</tr>
	</thead>
	<tbody>
	<?php foreach($invoices as $invoice): ?>
		<tr>
			<td>
				<?php if($invoice->getIsCorrectionInvoice()): ?>
					<span class="text-info"><?=Tr::_('Correction Invoice')?></span>
				<?php else: ?>
					<?php if(!$invoice->hasCorrections()): ?>
						<span class="text-danger"><?=Tr::_('Invoice')?></span>
					<?php else: ?>
						<span class="text-success"><?=Tr::_('Invoice')?></span>
					<?php endif; ?>
				<?php endif; ?>
				
			</td>
			<td>
				<?php if($invoice->getIsCorrectionInvoice()): ?>
					<a href="<?=$invoice->getEditUrl();?>" class="text-info"><?=$invoice->getNumber();?></a>
				<?php else: ?>
					<?php if(!$invoice->hasCorrections()): ?>
						<a href="<?=$invoice->getEditUrl();?>"><?=$invoice->getNumber();?></a>
					<?php else: ?>
						<a href="<?=$invoice->getEditUrl();?>" class="text-danger"><?=$invoice->getNumber();?></a>
					<?php endif; ?>
				<?php endif; ?>
			</td>
			<td>
				<?=Locale::date(  $invoice->getInvoiceDate() ); ?>
			</td>
			<td>
				<?=$price_formatter->formatWithCurrencyByHasVAT($invoice->hasVAT(), $invoice->getCurrency(), $invoice->getTotal())?>
			</td>
			<td></td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
