<?php

namespace JetApplicationModule\EShop\Analytics\Service\GA4;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\MVC_View;use Jet\UI;
use Jet\UI_messages;

/**
 * @var MVC_View $this
 * @var Form $form
 */

$form = $this->getRaw('form');

$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 10
]);
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 2
]);


foreach( UI_messages::get(context: 'CC') as $message ):
	echo $message;
endforeach;

echo $form->getCommonMessage();

echo $form->start();

echo $form->field('google_id');

?>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<?=UI::button_save()?>
		</div>
	</div>
	<?php
echo $form->end();