<?php
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var EShop $eshop
 */

$eshop = $this->getRaw('eshop');
$form = $this->getRaw('form');
$eshop_key = $eshop->getKey();
?>
<fieldset>
	<legend class="sub"><?=Tr::_('Main data')?></legend>
	
	<?=$form->field('/eshop_data/'.$eshop_key.'/name');?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/second_name');?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/description');?>
</fieldset>
<fieldset>
	<legend class="sub"><?=Tr::_('SEO')?></legend>
	
	<?=$form->field('/eshop_data/'.$eshop_key.'/seo_title');?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/seo_description');?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/seo_keywords');?>
</fieldset>
