<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\ReturnsOfGoods;


use Jet\Http_Request;
use Jet\Tr;
use Jet\UI_button;
use Jet\UI;
?>

<?=UI::button(Tr::_('Resend return of goods confirmation e-mail'))->setClass(UI_button::CLASS_INFO)
	->setUrl(Http_Request::currentURI(['send_email'=>'confirm']))
	->setIcon('envelope-circle-check')?>
