<?php
namespace JetApplicationModule\Admin\Services\Services;

use JetApplication\Services_Service;

use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use JetApplication\Services_Service_ShopData;
use JetApplication\Shops;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Services_Service     $service
 */

$service = $this->getRaw( 'service' );
?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>

		<?php if(!$service->getIsNew()):
			foreach(Shops::getListSorted() as $shop):
				echo $service->getShopData( $shop )->renderImageWidgets( Services_Service_ShopData::getImageClasses(), !$service->getEditForm()->getIsReadonly() );
			endforeach;
		endif; ?>
	</div>
</div>



