<?php
namespace JetShopModule\Admin\Services\Services;

use JetShop\Services_Service;

use Jet\UI;
use Jet\Mvc_View;
use Jet\Form;
use Jet\Tr;
use JetShop\Shops;

/**
 * @var Mvc_View $this
 * @var Form     $form
 * @var Services_Service     $service
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 1 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 4 ] );

$service = $this->getRaw( 'service' );
?>

<?=$form->start()?>
<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()?>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>
		<br/>

		<?=$form->field( 'internal_name' )?>
		<?=$form->field( 'code' )?>
		<?=$form->field( 'group' )?>
		<?=$form->field( 'kind' )?>
		<?=$form->field( 'internal_description' )?>


		<?php foreach(Shops::getList() as $shop):
			$shop_id= $shop->getId();

			$shop_data = $service->getShopData( $shop_id );
			?>
			<?=$shop_data->renderShopDataBlock_start()?>

			<fieldset>
				<legend class="sub"><?=Tr::_('Main data')?></legend>

				<?=$form->field('/shop_data/'.$shop_id.'/is_active')?>
				<?=$form->field('/shop_data/'.$shop_id.'/default_price')?>
				<?=$form->field('/shop_data/'.$shop_id.'/vat_rate')?>
				<?=$form->field('/shop_data/'.$shop_id.'/priority')?>
				<?=$form->field('/shop_data/'.$shop_id.'/title')?>
				<?=$form->field('/shop_data/'.$shop_id.'/description')?>
				<?=$form->field('/shop_data/'.$shop_id.'/description_short')?>

			</fieldset>

			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach; ?>
	</div>
</div>

<?=$form->end()?>
