<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Marketing\AutoOffers;


use Jet\MVC_View;
use JetApplication\Application_Service_Admin;
use JetApplication\Marketing_AutoOffer;


/**
 * @var MVC_View $this
 * @var Marketing_AutoOffer $item
 */

$item = $this->getRaw('item');
echo Application_Service_Admin::Product()->renderItemName( $item->getOfferProductId() );
