<?php
namespace JetApplicationModule\MarketPlaceIntegration\Mall;

use Jet\Form;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\MarketplaceIntegration_Module_Controller_ProductSettings;


/**
 * @var MVC_View   $this
 * @var Form $form
 * @var MarketplaceIntegration_Module_Controller_ProductSettings $controller
 */

$controller = $this->getController();

$product = $controller->getProduct();
$marketplace = $controller->getMarketplace();
$eshop = $controller->getEshop();
$editable = $controller->getEditable();

$labels = $this->getRaw('labels');
$form = $this->getRaw('form');
?>

<?=$controller->getTabs()?>
<br>
	
	<div class="toolbar">
		<?php if($editable): ?>
			<?=UI::button( Tr::_('Actualize list of labels'))->setClass(UI_button::CLASS_PRIMARY)->setUrl(Http_Request::currentURI(['actualize_list_of_labels'=>'1']))?>
		<?php endif; ?>
	</div>


<?=$form->start()?>
<table class="table table-striped">
	<thead>
	<tr>
		<th></th>
		<th><?=Tr::_('From')?></th>
		<th><?=Tr::_('Till')?></th>
	</tr>
	</thead>
<?php foreach($labels as $id=>$label): ?>
<tr>
	<td><?=$form->field('/label/'.$id.'/active')->input()?></td>
	<td><?=$form->field('/label/'.$id.'/from')->input()?></td>
	<td><?=$form->field('/label/'.$id.'/till')->input()?></td>
</tr>
<?php endforeach; ?>
</table>
	<?php if($editable): ?>
	<div style="position: fixed;right: 10px;bottom: 10px;">
		<?=UI::button_save()?>
	</div>
<?php endif; ?>

<?=$form->end()?>