<?php
namespace JetApplicationModule\MarketPlaceIntegration\Mall;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\UI;
use JetApplication\MarketplaceIntegration_Module_Controller_ProductSettings;


/**
 * @var MVC_View   $this
 * @var Form $form
 * @var MarketplaceIntegration_Module_Controller_ProductSettings $controller
 */

$controller = $this->getController();

$product = $controller->getProduct();
$marketplace = $controller->getMarketplace();
$eshop = $controller->getEshop();
$editable = $controller->getEditable();

$form = $this->getRaw('form');
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 2
])
?>
<?=$controller->getTabs()?>
<br>

<?=$form->start()?>

	<?php foreach($form->getFields() as $field):
	echo $field;
	endforeach; ?>

	<?php if($editable): ?>
<div class="form-group row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<?=UI::button_save()?>
	</div>
</div>
	
	<?php endif; ?>

<?=$form->end()?>