<?php
namespace JetApplicationModule\Admin\WarehouseManagement\ReceiptOfGoods;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\MVC_View;
use Jet\UI;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View   $this
 * @var Form $add_form
 */

$add_form = $this->getRaw('add_form');
$add_form->renderer()->setDefaultLabelWidth([Form_Renderer::LJ_SIZE_MEDIUM=>1]);
$add_form->renderer()->setDefaultFieldWidth([Form_Renderer::LJ_SIZE_MEDIUM=>4]);

$add_form->renderer()->addJsAction('onsubmit', 'ReceiptOfGoods.addItem();return false;');
?>

<?=$add_form->start();?>

	<?=$add_form->getCommonMessage()?>

	<?=$add_form->field('product_id')?>

	<div class="form-group row">
		<label class="col-md-1 col-form-label"><?=Tr::_('Product:')?></label>
		<div class="col-md-4">
			<?=Admin_Managers::Product()->renderSelectWidget(
				"$('#add_form__product_id').val(selected_item.id);",
				(int)$add_form->field('product_id')->getValue()
			)?>
		</div>
	</div>

	<?=$add_form->field('count')?>
	<?=$add_form->field('context_type')?>
	<?=$add_form->field('context')?>
	<?=$add_form->field('price')?>
	<?=$add_form->field('internal_description')?>

	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-4">
			<?=UI::button_create('Add')->setType('submit')->setClass('success')?>
		</div>
	</div>


<?=$add_form->end();?>
