<?php
namespace JetShopModule\Admin\WarehouseManagement\ReceiptOfGoods;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\UI;
use Jet\UI_button;
use JetShop\Product;
use JetShop\WarehouseManagement_Item_Event;

/**
 * @var MVC_View   $this
 * @var WarehouseManagement_Item_Event[] $items
 */

$items = $this->getRaw('items');

$count = 0;
?>

<table class="table table-striped">
	<?php foreach($items as $i=>$item):
		$product = Product::get($item->getProductId());
		if(!$product) {
			continue;
		}

		$count++;
		?>
	<tr>
		<td style="width: 100px;"><?=UI::button_delete('')->setUrl(Http_Request::currentURI(['action'=>'delete','index'=>$i]))->setSize(UI_button::SIZE_SMALL)?></td>
		<td style="width: 150px;"><?=$item->getCount()?>x</td>
		<td><?=$product->getAdminTitle()?></td>
		<td><?=$item->getContextType()?> : <?=$item->getContext()?></td>
		<td><?=$item->getPrice()?></td>
	</tr>
	<?php endforeach; ?>
</table>

<?php if($count): ?>
	<?=UI::button_create('Done')->setUrl(Http_Request::currentURI(['action'=>'done']))->setClass('success')?>
<?php endif; ?>
