<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\ProductQuestions;

use Jet\MVC_View;
use Jet\UI_messages;
use JetApplication\ProductQuestion;

/**
 * @var MVC_View $this
 * @var ProductQuestion $item
 */

$item = $this->getRaw('item');

if( $item->getIsNew() ) {
	return;
}

if($item->isSpam()) {
	echo UI_messages::createDanger('SPAM')->setCloseable(false);
}

echo Plugin::get( Plugin_SetStatus_Main::KEY )?->renderButton();
echo Plugin::get( Plugin_ForceStatus_Main::KEY )?->renderButton();