<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Catalog\ProductQuestions;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\ProductQuestion;

/**
 * @var MVC_View $this
 * @var ProductQuestion $item
 */

$item = $this->getRaw('item');

if(
	!$item->isEditable()
) {
	return;
}
?>
&nbsp;&nbsp;&nbsp;&nbsp;
<?=UI::button( Tr::_('Answered - display') )
	->setUrl( Http_Request::currentURI(set_GET_params: ['action'=>'answer_display']) )
	->setClass(UI_button::CLASS_SUCCESS);?>

<?=UI::button( Tr::_('Answered - do not display') )
	->setUrl( Http_Request::currentURI(set_GET_params: ['action'=>'answer_do_not_display']) )
	->setClass(UI_button::CLASS_INFO);?>

&nbsp;&nbsp;&nbsp;&nbsp;
<?=UI::button( Tr::_('Not answered') )
	->setUrl( Http_Request::currentURI(set_GET_params: ['action'=>'not_answered']) )
	->setClass(UI_button::CLASS_DANGER)?>
