<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Events\ProductQuestion\Rejected;


use Jet\MVC_View;
use JetApplication\ProductQuestion;

/**
 * @var MVC_View $this
 * @var ProductQuestion $event
 * @var Main $handler
 */

$event = $this->getRaw('event');
$handler = $this->getRaw('handler');
