<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ManageAccess\Administrators\Roles;

use Jet\Data_Text;
use Jet\Form_Field_Select;
use Jet\Locale;
use Jet\MVC;
use Jet\MVC_Page_Interface;
use Jet\Navigation_MenuSet;use Jet\UI;
use JetApplication\Application_Admin;
use JetApplication\Auth_Administrator_User;
use JetApplication\Auth_Administrator_Role;
use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Auth_Administrator_Role $role
 * @var Form $form
 * @var array $available_privileges_list
 */
$role = $this->getRaw( 'role' );
$form = $this->getRaw( 'form' );
$available_privileges_list = $this->getRaw( 'available_privileges_list' );

$form->renderer()->setDefaultLabelWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 1] );
$form->renderer()->setDefaultFieldWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 4] );

?>

<?= $form->start() ?>
<div class="toolbar" id="main-toolbar">
	<?= UI::button_goBack()->setUrl( $this->getString( 'list_url' ) ) ?>

	<?php if( !$form->getIsReadonly() ): ?>
		<?= UI::button_save() ?>
	<?php endif; ?>
</div>

<div id="main-col">
	<?= $form->field( 'id' ) ?>
	<?= $form->field( 'name' ) ?>
	<?= $form->field( 'description' ) ?>

	<fieldset>
		<legend><?= Tr::_( 'Privileges' ); ?></legend>
		<?php
			/**
			 * @var Form_Field_Select $fl
			 */
			$fl = $form->field( 'privileges' );
			$fl->input()->addCustomCssStyle( 'height:600px' );
			
			//echo $fl->row()->start();
			//echo $fl->label();
			//echo $fl->container()->start();
				
			$fl->input()->setBaseCssClass( 'form-control' );
			if( $fl->getLastErrorCode() ) {
				$fl->input()->addCustomCssClass( 'is-invalid' );
			}
					
			$pages = [];
			
				$showPriv = function( MVC_Page_Interface $page ) use ( $fl ) {
					$privilege = Auth_Administrator_Role::PRIVILEGE_VISIT_PAGE.'|'.$page->getId();
					$selected = $fl->optionIsSelected($privilege) ? ' selected="selected"' : '';
					?>
					<option value="<?=$privilege?>"  <?=$selected?> style="margin-left: 30px;"><?=$page->getTitle()?></option>
					<?php
					foreach($page->getContent() as $content):
						$module = $content->getModuleInstance();
						if(!$module) {
							continue;
						}
						
						foreach($module->getModuleManifest()->getACLActions() as $action=>$action_name):
							$privilege = Auth_Administrator_Role::PRIVILEGE_MODULE_ACTION.'|'.$module->getModuleManifest()->getName().':'.$action;
							$selected = $fl->optionIsSelected($privilege) ? ' selected="selected"' : '';
							?>
							<option value="<?=Data_Text::htmlSpecialChars($privilege)?>" <?=$selected?> style="margin-left: 60px;opacity: 0.8;font-size: 0.8rem"><?=$action_name?></option>
						<?php
						endforeach;
					endforeach;
					
				};
				?>
				<select <?=$fl->input()->renderTagAttributes()?>>
					<?php foreach( Navigation_MenuSet::get('admin')->getMenus() as $menu ):
						?>
						<optgroup label="<?=$menu->getLabel()?>" style="margin-bottom: 20px;">
							<?php foreach($menu->getItems( false ) as $item):
								$page = MVC::getPage( $item->getPageId(), base_id: Application_Admin::getBase()->getId() );
								
								$pages[] = $page->getId();
								
								$showPriv( $page );
							endforeach; ?>
						</optgroup>
					<?php endforeach; ?>
					<optgroup label="<?=Tr::_('Other')?>">
						<?php
						
						$showPriv( Application_Admin::getBase()->getHomepage(Locale::getCurrentLocale()) );
						
						foreach(Application_Admin::getBase()->getHomepage(Locale::getCurrentLocale())->getChildren() as $page):
							if(in_array($page->getId(), $pages)) {
								continue;
							}
							
							$showPriv( $page );
						endforeach; ?>
					</optgroup>
				</select>
				<?php
				echo $fl->getLastErrorMessage();
				//echo $fl->container()->end();
				//echo $fl->row()->end();
		 ?>
	</fieldset>


	<?php if( $role && count( $role->getUsers() ) ): ?>
		<fieldset style="margin-top: 30px">
			<legend><?= Tr::_( 'Users' ); ?></legend>
			<table class="table table-striped">
				<thead>
				<tr>
					<th><?= Tr::_( 'ID' ); ?></th>
					<th><?= Tr::_( 'Username' ); ?></th>
					<th><?= Tr::_( 'Name' ); ?></th>
					<th></th>
				</tr>
				</thead>
				<tbody>
				<?php foreach( $role->getUsers() as $user ):
					/**
					 * @var Auth_Administrator_User $user
					 */
					?>
					<tr>
						<td nowrap="">
							<a href="<?=MVC::getPage('administrators-users')->getURL(GET_params: ['id'=>$user->getId()])?>"><?= $user->getId(); ?></a>
						</td>
						<td nowrap="">
							<a href="<?=MVC::getPage('administrators-users')->getURL(GET_params: ['id'=>$user->getId()])?>"><?= $user->getUsername(); ?></a>
						</td>
						<td nowrap="">
							<a href="<?=MVC::getPage('administrators-users')->getURL(GET_params: ['id'=>$user->getId()])?>"><?= $user->getName(); ?></a>
						</td>
						<td style="width: 100%"></td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		</fieldset>
	<?php endif; ?>

</div>
<?= $form->end() ?>
