<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ManageAccess\Administrators\Roles;


use Jet\UI;

use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Listing $listing
 */
$listing = $this->getRaw( 'listing' );
$grid = $listing->getGrid();
$filter_form = $listing->getFilterForm();

$router = $this->getController()->getControllerRouter();

$grid->getColumn( 'id' )->addCustomCssStyle( 'width:120px;' );
$grid->getColumn( '_edit_' )->addCustomCssStyle( 'width:180px;' );
?>

<?= $filter_form->start() ?>
<div class="toolbar" style="display: grid;grid-template-columns: 2fr 3fr 9fr;">
	<div>
		<?php if( ($add_uri = $router->action( 'add' )->URI()) ): ?>
			<?= UI::button_create( Tr::_( 'Create a new Role' ) )->setUrl( $add_uri ) ?>
		<?php endif; ?>
	</div>
	<div>
		<?=$listing->filter(Listing_Filter_Search::KEY)->renderForm()?>
	</div>
	<div>
	
	</div>
</div>
<?= $filter_form->end() ?>

<div id="main-col">
		<?= $grid->render(); ?>
</div>
