<?php
namespace JetApplicationModule\Admin\Entity\WithEShopData;

use Jet\MVC_View;
use Jet\UI;
use JetApplication\EShopEntity_Admin_Interface;
use JetApplication\EShopEntity_WithEShopData;

/**
 * @var MVC_View $this
 * @var EShopEntity_WithEShopData|EShopEntity_Admin_Interface     $item
 */
$item = $this->getRaw('item');
?>
<?=$item->getAdminTitle()?> <a href="<?=$item->getEditUrl()?>"><?=UI::icon('link')?></a>
