<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Entity\Edit;


use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View $this
 */
$id = $this->getInt('id');
?>
<b class="bg-danger"><?=Tr::_('Unknown item %ID%', ['ID'=>$id], dictionary: Tr::COMMON_DICTIONARY)?></b>
