<?php
namespace JetApplicationModule\Admin\Orders;

use Jet\Locale;
use Jet\Tr;
use Jet\MVC_View;
use Jet\UI_messages;
use JetApplication\Order;

/**
 * @var MVC_View $this
 * @var Order     $order
 */

$order = $this->getRaw( 'order' );

$history = $order->getHistory();
?>
	
	<table class="table table-striped">
		<thead>
		<tr>
			<th style="width: 150px;"><?=Tr::_('Date and time')?></th>
			<th style="width: 250px;"></th>
			<th></th>
		</tr>
		</thead>
		<tbody>
		<?php foreach($history as $event):
			$handler = $event->getHandlerModule();
			if(!$handler) {
				continue;
			}
			?>
			<tr>
				<td>
					<?=Locale::dateAndTime( $event->getDateAdded() )?>
					<br>
					<?=$event->getAdministrator() ?>
				</td>
				<td><div style="padding: 10px;font-weight: bolder;<?=$handler->getEventStyle()?>"><?=$handler->showEventName()?></div></td>
				<td>
					<?php if(!$event->getHandled()):
						//TODO:
						?>
						<?=UI_messages::createDanger( $event->getErrorMessage() ) ?>
					<?php endif; ?>
					
					<?=$handler->showEventDetails(); ?>
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
