<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Orders;


use Jet\Locale;
use Jet\Tr;
use Jet\UI_badge;
use Jet\UI_button;
use JetApplication\Application_Service_Admin;
use JetApplication\Application_Service_Admin_EShopEntity_Listing;

use Jet\UI;
use Jet\MVC_View;
use JetApplication\Application_Service_EShop;
use JetApplication\Order_Item;
use JetApplication\Order;
use JetApplication\Product;
use JetApplication\Product_Availability;

/**
 * @var MVC_View $this
 * @var Order     $order
 * @var Application_Service_Admin_EShopEntity_Listing $listing
 */

$order = $this->getRaw( 'order' );
$listing = $this->getRaw('listing');


$price_formatter = Application_Service_Admin::PriceFormatter();
$product_manager = Application_Service_Admin::Product();
$icons = Order_Item::getItemIcons();


?>

	
	<table class="table table-striped">
		<thead>
		<tr>
			<th style="width: 20px;"></th>
			<th style="width: 60px;"></th>
			<th><?=Tr::_('Item')?></th>
			<th><?=Tr::_('Code')?></th>

			<th><?=Tr::_('Availability - in the moent of purchase')?></th>
			<th><?=Tr::_('Availability - current')?></th>
			
			<?php /*
			<th><?=Tr::_('Not available')?></th>
			*/ ?>

			
			<th style="width: 100px;"><?=Tr::_('VAT')?></th>
			<th style="width: 200px;"><?=Tr::_('Price per item<br><span style="font-weight: normal">without VAT</span>')?></th>
			<th style="width: 200px;"><?=Tr::_('Price per item<br><span style="font-weight: normal">with VAT</span>')?></th>
			<th style="width: 200px;"><?=Tr::_('Total amount<br><span style="font-weight: normal">without VAT</span>')?></th>
			<th style="width: 200px;"><?=Tr::_('Total amount<br><span style="font-weight: normal">with VAT</span>')?></th>
		</tr>
		</thead>
		<tbody>
		<?php
		$showItem = function( Order_Item $item ) use ($product_manager, $icons, $price_formatter, $order) {
			if( $item->isPhysicalProduct() || $item->isVirtualProduct() ):
				$p = Product::get($item->getItemId());
			else:
				$p = null;
			endif;
			?>
			<tr id="item_<?=$item->getId()?>">
				<td style="text-align: center"><?=$icons[$item->getType()]?></td>
				<td style="text-align: right"><b><?=Locale::float($item->getNumberOfUnits()) ?>&nbsp;<?=$item->getMeasureUnit()?->getName()?></b></td>
				<td>
					
					<?php if( $p ): ?>
						<a href="<?=$product_manager::getEditUrl( $item->getItemId() )?>"><?=$item->getTitle() ?></a>
						
						<?php  if($order->getDispatched() || $order->getDelivered()): ?>
							<div style="display: flex;gap: 10px;">
								<?php
								if(($create_complaint_URL = Application_Service_EShop::Complaints()->generateCreateURL( $order, $item ))):
									echo
									UI::button( Tr::_('to claim goods') )->setUrl( $create_complaint_URL )
										->setClass(UI_button::CLASS_SECONDARY)->setSize(UI_button::SIZE_EXTRA_SMALL)
										->setCustomTagAttribute('target', '_blank');
								endif;
								
								if(($create_return_URL = Application_Service_EShop::ReturnOfGoods()->generateCreateURL( $order, $item ))):
									echo UI::button( Tr::_('return goods') )->setUrl( $create_return_URL )
										->setClass(UI_button::CLASS_SECONDARY)->setSize(UI_button::SIZE_EXTRA_SMALL)
										->setCustomTagAttribute('target', '_blank');
								endif;
								?>
							</div>
						<?php endif; ?>
					
					<?php else: ?>
						<?=$item->getTitle() ?>
					<?php endif; ?>
				</td>
				

				<td>
					<?php if( $p ): ?>
						<a href="<?=$product_manager::getEditUrl( $item->getItemId() )?>"><?=$p->getInternalCode()?></a>
					<?php endif; ?>
				</td>

				<td>
					<?php if( $item->isPhysicalProduct() ):
						if( $item->getNumberOfUnitsAvailable()>0 ):
							echo UI::badge( UI_badge::SUCCESS, Tr::_('Available: %units%', ['units' => $item->getNumberOfUnitsAvailable()]) );
						
							if($item->getAvailableUnitsPromisedDeliveryDate()):
								echo '<div style="font-size: 0.8rem">';
								echo Tr::_('Promised delivery data: %date%', ['date'=>Locale::date($item->getAvailableUnitsPromisedDeliveryDate())]);
								echo '</div>';
							endif;
						endif;
						if( $item->getNumberOfUnitsNotAvailable()>0 ):
							echo UI::badge( UI_badge::INFO, Tr::_('Not available: %units%', ['units' => $item->getNumberOfUnitsNotAvailable()]) );
						
							echo '<div style="font-size: 0.8rem">';
							echo $item->getDeliveryTemInfo()?->getDeliveryInfoTextWhenNotAvailableTranslated();
							echo '</div>';
						endif;
						?>
					<?php endif; ?>
				</td>
				

				<td>
					<?php if( $item->isPhysicalProduct() ):
						$avl = Product_Availability::get( $order->getAvailability(), $item->getItemId() );
					
						if($avl->getNumberOfAvailable()>=$item->getNumberOfUnits()):
							echo UI::badge( UI_badge::SUCCESS, Tr::_('Available') );
						else:
							echo UI::badge( UI_badge::INFO, Tr::_('Not available') );
						endif;
					endif; ?>
				</td>
				
				<td><?=$item->getVatRate()?>%</td>
				<td><?=$price_formatter->formatWithCurrency_WithoutVAT( $order->getCurrency(), $item->getPricePerUnit_WithoutVat() )?></td>
				<td><?=$price_formatter->formatWithCurrency_WithVAT( $order->getCurrency(), $item->getPricePerUnit_WithVat() )?></td>
				<td><?=$price_formatter->formatWithCurrency_WithoutVAT( $order->getCurrency(), $item->getTotalAmount_WithoutVat() )?></td>
				<td><?=$price_formatter->formatWithCurrency_WithVAT( $order->getCurrency(), $item->getTotalAmount_WithVat() )?></td>
			</tr>
			<?php
			
			if($item->getSetItems()):
				foreach($item->getSetItems() as $set_item):
					?>
					<tr style="opacity: 0.3">
						<td style="text-align: center">
						</td>
						<td style="text-align: right"><b><?=Locale::float($set_item->getNumberOfUnits()) ?>&nbsp;<?=$set_item->getMeasureUnit()?->getName()?></b></td>
						<td>
							<a href="<?=$product_manager::getEditUrl( $set_item->getItemId() )?>"><?=$set_item->getTitle() ?></a>
						</td>
						<td>
							<?php if( $item->isPhysicalProduct() || $item->isVirtualProduct() ):
								$p = Product::get($set_item->getItemId());
								?>
								<a href="<?=$product_manager::getEditUrl( $set_item->getItemId() )?>"><?=$p?->getInternalCode()?></a>
							<?php endif; ?>

						</td>
						<td>
							<?php if( $item->isPhysicalProduct() ):
								if( $set_item->getNumberOfUnitsAvailable()>0 ):
									echo UI::badge( UI_badge::SUCCESS, Tr::_('Available: %units%', ['units' => $set_item->getNumberOfUnitsAvailable()]) );
									
									if($set_item->getAvailableUnitsPromisedDeliveryDate()):
										echo '<div style="font-size: 0.8rem">';
										echo Tr::_('Promised delivery data: %date%', ['date'=>Locale::date($set_item->getAvailableUnitsPromisedDeliveryDate())]);
										echo '</div>';
									endif;
								endif;
								if( $set_item->getNumberOfUnitsNotAvailable()>0 ):
									echo UI::badge( UI_badge::INFO, Tr::_('Not available: %units%', ['units' => $set_item->getNumberOfUnitsNotAvailable()]) );
									
									echo '<div style="font-size: 0.8rem">';
									echo $set_item->getDeliveryTemInfo()?->getDeliveryInfoTextWhenNotAvailableTranslated();
									echo '</div>';
								endif;
								?>
							<?php endif; ?>
						</td>
						
						<td>
							<?php if( $item->isPhysicalProduct() ):
								$avl = Product_Availability::get( $order->getAvailability(), $set_item->getItemId() );
								
								if($avl->getNumberOfAvailable()>=$item->getNumberOfUnits()):
									echo UI::badge( UI_badge::SUCCESS, Tr::_('Available') );
								else:
									echo UI::badge( UI_badge::INFO, Tr::_('Not available') );
								endif;
							endif; ?>

						</td>

						<td><?=$set_item->getVatRate()?>%</td>

						<td><?=$price_formatter->formatWithCurrency_WithoutVAT( $order->getCurrency(), $set_item->getPricePerUnit_WithoutVat() )?></td>
						<td><?=$price_formatter->formatWithCurrency_WithVAT( $order->getCurrency(), $set_item->getPricePerUnit_WithVat() )?></td>
						<td><?=$price_formatter->formatWithCurrency_WithoutVAT( $order->getCurrency(), $set_item->getTotalAmount_WithoutVat() )?></td>
						<td><?=$price_formatter->formatWithCurrency_WithVAT( $order->getCurrency(), $set_item->getTotalAmount_WithVat() )?></td>
					</tr>
				<?php
				endforeach; ?>
				<tr style="opacity: 0.5">
					<td></td>
					<td></td>
					<td colspan="5"><i><?=Tr::_('Set discount:')?></i></td>
					<td><i><?=$price_formatter->formatWithCurrency_WithoutVAT( $order->getCurrency(), $item->getSetDiscountPerUnit_Wo_VAT() )?></i></td>
					<td><i><?=$price_formatter->formatWithCurrency_WithVAT($order->getCurrency(), $item->getSetDiscountPerUnit())?></i></td>
					<td><i><?=$price_formatter->formatWithCurrency_WithoutVAT($order->getCurrency(), $item->getSetDiscountPerUnit_Wo_VAT()*$item->getNumberOfUnits())?></i></td>
					<td><i><?=$price_formatter->formatWithCurrency_WithVAT($order->getCurrency(), $item->getSetDiscountPerUnit()*$item->getNumberOfUnits())?></i></td>
				</tr>
				<?php
			endif;
		};
		?>
		
		<?php
		foreach( $order->getItems() as $item ):
			if(
				$item->getType()==Order_Item::ITEM_TYPE_PRODUCT ||
				$item->getType()==Order_Item::ITEM_TYPE_VIRTUAL_PRODUCT
			) {
				$showItem( $item );
			}
		endforeach;
		
		foreach( $order->getItems() as $item ):
			if(
				$item->getType()==Order_Item::ITEM_TYPE_GIFT ||
				$item->getType()==Order_Item::ITEM_TYPE_VIRTUAL_GIFT
			) {
				$showItem( $item );
			}
		endforeach;
		
		foreach( $order->getItems() as $item ):
			if(
				$item->getType()==Order_Item::ITEM_TYPE_SERVICE
			) {
				$showItem( $item );
			}
		endforeach;
		
		foreach( $order->getItems() as $item ):
			if(
				$item->getType()==Order_Item::ITEM_TYPE_PAYMENT ||
				$item->getType()==Order_Item::ITEM_TYPE_DELIVERY
			) {
				$showItem( $item );
			}
		endforeach;
		
		foreach( $order->getItems() as $item ):
			if(
				$item->getType()==Order_Item::ITEM_TYPE_DISCOUNT
			) {
				$showItem( $item );
			}
		endforeach;
		
		
		?>
		</tbody>
	</table>


<?php
$showSummary = function( $wo_VAT, $w_VAT ) use ($order, $price_formatter) {
	?>
	<div style="opacity: 0.5"><?=$price_formatter->formatWithCurrency_WithoutVAT($order->getCurrency(), $wo_VAT)?> <?=Tr::_('without VAT')?></div>
	<div><?=$price_formatter->formatWithCurrency_WithVAT($order->getCurrency(), $w_VAT)?> <?=Tr::_('with VAT')?></div>
	<?php
};
?>
	
	<div style="display: grid;grid-template-columns: 1fr 500px;">
		<div>
		
		</div>
		<div>
			<table class="table table">
				<tr>
					<td style="width: 20px"><?=$icons[Order_Item::ITEM_TYPE_PRODUCT]?></td>
					<td><?=Tr::_('Products:')?></td>
					<td style="width: 200px;">
						<?php $showSummary( $order->getProductAmount_WithoutVAT(), $order->getProductAmount_WithVAT() ); ?>
					</td>
				</tr>
				<tr>
					<td style="width: 20px"><?=$icons[Order_Item::ITEM_TYPE_SERVICE]?></td>
					<td><?=Tr::_('Services:')?></td>
					<td>
						<?php $showSummary( $order->getServiceAmount_WithoutVAT(), $order->getServiceAmount_WithVAT() ); ?>
					</td>
				</tr>
				<tr>
					<td style="width: 20px"><?=$icons[Order_Item::ITEM_TYPE_DELIVERY]?></td>
					<td><?=Tr::_('Delivery:')?></td>
					<td>
						<?php $showSummary( $order->getDeliveryAmount_WithoutVAT(), $order->getDeliveryAmount_WithVAT() ); ?>
					</td>
				</tr>
				<tr>
					<td style="width: 20px"><?=$icons[Order_Item::ITEM_TYPE_PAYMENT]?></td>
					<td><?=Tr::_('Payment:')?></td>
					<td>
						<?php $showSummary( $order->getPaymentAmount_WithoutVAT(), $order->getPaymentAmount_WithVAT() ); ?>
					</td>
				</tr>
				<tr>
					<td style="width: 20px"><?=$icons[Order_Item::ITEM_TYPE_DISCOUNT]?></td>
					<td><?=Tr::_('Discounts:')?></td>
					<td>
						<?php $showSummary( $order->getDiscountAmount_WithoutVAT(), $order->getDiscountAmount_WithVAT() ); ?>
					</td>
				</tr>
				<tr>
					<td><?=UI::icon('calculator')?></td>
					<td style="font-weight: bolder;font-size: 1.2rem" nowrap=""><?=Tr::_('Total amount:')?></td>
					<td style="font-weight: bolder;font-size: 1.2rem" nowrap="">
						<?php $showSummary( $order->getTotalAmount_WithoutVAT(), $order->getTotalAmount_WithVAT() ); ?>
					</td>
				</tr>
			</table>
		</div>
	
	</div>
