<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Orders;


use Jet\Form;
use Jet\Locale;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Application_Service_Admin;
use JetApplication\Application_Service_Admin_EShopEntity_Listing;

use Jet\MVC_View;
use JetApplication\MarketplaceIntegration;
use JetApplication\EShops;
use JetApplication\Order;


/**
 * @var MVC_View $this
 * @var Order     $order
 * @var Application_Service_Admin_EShopEntity_Listing $listing
 * @var Form $add_bl_form
 */

$order = $this->getRaw( 'order' );
?>

	<div style="padding: 10px;display: flex">
		<?php if($order->getImportSource()):
			$mp = MarketplaceIntegration::getOrderHandler( $order );
			?>
		<div style="margin: 10px" class="card">

			<div class="card-header"><b><?=Tr::_('Order import source')?></b></div>
			<div class="card-body">
				<div>
				<?=$order->getImportSource()?><br>
				<i><?=$order->getImportRemoteId()?></i>
				</div>
				
				<?php $mp?->handleOrderDetail( $order ) ?>
				
			</div>
		</div>
		<?php endif; ?>
		
		<div style="margin: 10px" class="card">
			
			<div class="card-header"><b><?=Tr::_('Common information')?></b></div>
			<div class="card-body">
				
				<?=$order->getStatus()->showAdmin()?>
				
				<table style="margin: 10px">
					<?php if($order->getSplitSourceOrderId()): ?>
					<tr>
						<td style="font-weight: bolder;font-size: 1.1rem"><?=Tr::_('Comes from a split order:')?></td>
						<td style="font-weight: bolder;font-size: 1.1rem"><?=Application_Service_Admin::Order()->renderItemName($order->getSplitSourceOrderId())?></td>
					</tr>
					<?php endif; ?>
					
					<?php if($order->getJoinedWithOrderId()): ?>
						<tr>
							<td style="font-weight: bolder;font-size: 1.1rem"><?=Tr::_('Joined with order:')?></td>
							<td style="font-weight: bolder;font-size: 1.1rem"><?=Application_Service_Admin::Order()->renderItemName($order->getJoinedWithOrderId())?></td>
						</tr>
					<?php endif; ?>
					
					
					<?php if(EShops::isMultiEShopMode()): ?>
						<tr>
							<td><b><?=Tr::_('e-shop')?></b></td>
							<td><?=$order->getEshop()->getName()?></td>
						</tr>
					<?php endif; ?>
					<tr>
						<td nowrap=""><b><?=Tr::_('Purchase date and time:')?></b></td>
						<td nowrap="" style="padding: 3px"><?= Locale::dateAndTime($order->getDatePurchased()) ?></td>
					</tr>
					<?php /*
					<tr>
						<td nowrap=""><b><?=Tr::_('IP address:')?></b></td>
						<td nowrap="" style="padding: 3px"><?= $order->getIpAddress() ?></td>
					</tr>
					*/ ?>
					<tr>
						<td><b><?=Tr::_('Delivery method:')?></b></td>
						<td nowrap="" style="padding: 3px"><?=$order->getDeliveryMethod()?->getTitle()?></td>
					</tr>
					<tr>
						<td><b><?=Tr::_('Payment method:')?></b></td>
						<td nowrap="" style="padding: 3px"><?=$order->getPaymentMethod()?->getTitle()?></td>
					</tr>
					<?php /*
					<tr>
						<td><b><?=Tr::_('Indicative total weight:')?></b></td>
						<td nowrap="" style="padding: 3px"><?=Locale::float($order->getTotalWeightOfProducts())?></td>
					</tr>
					<tr>
						<td><b><?=Tr::_('Indicative total volume:')?></b></td>
						<td nowrap="" style="padding: 3px"><?=Locale::float($order->getTotalVolumeOfProducts())?></td>
					</tr>
					*/ ?>
					
					<tr>
						<td><b><?=Tr::_('Payment required:')?></b></td>
						<td nowrap="" style="padding: 3px"><?=Tr::_($order->getPaymentRequired() ? 'yes' : 'no')?></td>
					</tr>
					
					<?php if($order->getPaymentRequired()): ?>
					<tr>
						<td><b><?=Tr::_('Paid:')?></b></td>
						<td nowrap="" style="padding: 3px"><?=Tr::_($order->getPaid() ? 'yes' : 'no')?></td>
					</tr>
						
						<?php if(
							!$order->getPaid() &&
							!$order->getDispatched() &&
							!$order->getDelivered()
						): ?>
							<tr>
								<td><b><?=Tr::_('Payment page URL:')?></b></td>
								<td nowrap="" style="padding: 3px">
									<script>
										function copyPaymentURL() {
											const i = document.getElementById('payment_URL_link');
											i.select();
											i.setSelectionRange(0, 99999);
											navigator.clipboard.writeText(i.value);
										}
									</script>
									<div style="justify-content:left;display: grid;grid-template-columns: auto auto auto;align-items: center;gap: 10px;">
										<?=UI::button(' ')->setOnClick("copyPaymentURL();")->setClass(UI_button::CLASS_LINK)->setCustomTagAttribute('title', Tr::_('Copy URL'))->setIcon('copy')?>
										<input id="payment_URL_link" type="text" value="<?=$order->getPaymentPageURL()?>" class="form-control" readonly>
										<a href="<?=$order->getPaymentPageURL()?>" target="_blank"><?=UI::icon('link')?></a>
									</div>
								</td>
							</tr>
						<?php endif ?>
					<?php endif; ?>
					
					<tr>
						<td><b><?=Tr::_('All items available:')?></b></td>
						<td nowrap="" style="padding: 3px"><?=Tr::_($order->getAllItemsAvailable() ? 'yes' : 'no')?></td>
					</tr>

					<tr>
						<td><b><?=Tr::_('Designated warehouse:')?></b></td>
						<td nowrap="" style="padding: 3px">
							<?=$order->getWarehouse()?->getInternalName()?>
						</td>
					</tr>
					
				</table>

				<?php Application_Service_Admin::Complaint()->showOrderComplaints( $order ); ?>
				
			</div>
		</div>
		
		<div style="margin: 10px;margin-left: 80px;" class="card">
			<div class="card-header"><b><?=Tr::_('Customer')?></b></div>
			<div class="card-body">
				
				<table>
					<tr>
						<td></td>
						<td>
							<?=Application_Service_Admin::Customer()->renderItemName( $order->getCustomerId() )?>
							<br>
						</td>
					</tr>
					<tr>
						<td style="font-size: 1.2rem;font-weight: bolder"><?=Tr::_('Phone:')?></td>
						<td style="font-size: 1.2rem;font-weight: bolder"><?=$order->getPhone()?></td>
					</tr>
					<tr>
						<td><?=Tr::_('e-mail:')?></td>
						<td><a href="mailto:<?=$order->getEmail()?>"><u><?=$order->getEmail()?></u></a></td>
					</tr>
				</table>
				
				
				<?=Plugin::get( Plugin_ChangeEMailAndPhone_Main::KEY )?->renderButton()?>
				<?=Plugin::get( Plugin_Blacklist_Main::KEY )?->renderButton()?>
			</div>
		</div>
		
		<div style="margin: 10px;" class="card">
			<div class="card-header"><b><?=Tr::_('Billing address')?></b></div>
			<div class="card-body">
				<?=Application_Service_Admin::Customer()->formatAddress( $order->getEshop(), $order->getBillingAddress() )?>
				
				<?=Plugin::get( Plugin_ChangeBillingAddress_Main::KEY )?->renderButton()?>
			</div>
		</div>
		
		
		<div style="margin: 10px;" class="card">
			<div class="card-header"><b><?=Tr::_('Delivery address')?></b></div>
			<div class="card-body">
				<?=Application_Service_Admin::Customer()->formatAddress( $order->getEshop(), $order->getDeliveryAddress() )?>
				
				<?=Plugin::get( Plugin_ChangeDeliveryAddress_Main::KEY )?->renderButton()?>
			</div>
		</div>
		
		<div style="margin: 10px;">
		</div>
	</div>

