<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\MVC_View;
use Jet\Form;
use Jet\Locale;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Locale $locale
 */
$form = $this->getRaw('form');
$locale = $this->getRaw('locale');

?>
<?=$form->field('/description/'.$locale.'/name');?>
<?=$form->field('/description/'.$locale.'/about_author');?>
