<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var EShop $eshop
 */
$form = $this->getRaw('form');
$eshop = $this->getRaw('eshop');
$eshop_key = $eshop->getKey();

?>
<?=$form->field('/eshop_data/'.$eshop_key.'/name');?>
<?=$form->field('/eshop_data/'.$eshop_key.'/about_author');?>
