<?php
namespace JetApplicationModule\Shop\CashDesk;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Delivery_Method_ShopData;

/**
 * @var MVC_View $this
 * @var Delivery_Method_ShopData $delivery_method
 */

$cash_desk = CashDesk::get();


?>

<div class="method" onclick="CashDesk.delivery.personalTakeover.startSelection()">

	<div>
		<input type="radio" name="delivery_method" onclick="setTimeout(function(){CashDesk.delivery.personalTakeover.startSelection()}, 10);return false;" />
	</div>
	
	
	<div class="method-icon">
	</div>
	
	<div class="method-title">
		<b><?=Tr::_('Personal takeover')?></b>
	</div>
	
	<div></div>
</div>
