<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Properties;


use Jet\MVC_View;
use JetApplication\Property;

/**
 * @var MVC_View $this
 * @var Property $item
 */

$item = $this->getRaw('item');

echo $item->getFilterPriority();