<?php
namespace JetApplicationModule\Shop\ShoppingCart;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Pricelists;
use JetApplication\Shop_Managers;
use JetApplication\Shop_Pages;
use JetApplication\ShoppingCart_Item;

/**
 * @var MVC_View $this
 * @var ShoppingCart_Item $item
 */

$item = $this->getRaw('new_item');

$product = $item->getProduct();
?>

<div style="display: grid;grid-template-columns: 100px 300px 200px;gap: 10px;margin: 20px;align-items: center">
	<div>
		<?php if(($img=$product->getImgThumbnailUrl( 0, 100, 100))): ?>
			<img src="<?=$img?>"/>
		<?php endif; ?>
	</div>
	<div>
		<a href="<?=$product->getURL()?>"><?=$product->getFullName()?></a><br>
	</div>
	<div>
		<span class="small"><?=$item->getNumberOfUnits()?> <?=$product->getMeasureUnit()?->getName()?> x <?=Shop_Managers::PriceFormatter()->formatWithCurrency($item->getProduct()->getPrice( Pricelists::getCurrent() ))?></span><br/>
		<b><?=Shop_Managers::PriceFormatter()->formatWithCurrency($item->getAmount())?></b>

	</div>
</div>


<div style="text-align: right">
	<?=UI::button(Tr::_('Proceed to checkout'))->setUrl( Shop_Pages::ShoppingCart()->getURL() )->setClass( UI_button::CLASS_SUCCESS )?>
</div>

<?=Shop_Managers::Analytics()?->addToCart( $item )?>