<?php
use Jet\Tr;
use JetApplication\Shop_Pages;

?>
<a class="btn btn-info" href="<?= Shop_Pages::ShoppingCart()->getURL() ?>"><?= Tr::_('Shopping cart'); ?></a>
<a class="btn btn-info" onclick="CashDesk.delivery.back();return false;"><?= Tr::_('Delivery'); ?></a>
<div class="btn btn-primary"><?= Tr::_('Payment'); ?></div>
<div class="btn btn-light text-muted"><?= Tr::_('Registration'); ?></div>
<div class="btn btn-light text-muted"><?= Tr::_('Confirmation'); ?></div>