<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\SupplierGoodsOrders;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Supplier_GoodsOrder;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Supplier_GoodsOrder     $item
 */

$item = $this->getRaw('item');


if( $item->getStatus()->sendAllowed() ) {
	echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
	echo UI::button(Tr::_('Send to the supplier'))->setUrl(Http_Request::currentURL(['action'=>'send']))->setClass(UI_button::CLASS_SUCCESS);
}

if( $item->getStatus()->cancelAllowed() ) {
	echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
	echo UI::button( Tr::_( 'Cancel' ) )->setUrl( Http_Request::currentURL( ['action' => 'cancel'] ) )->setClass( UI_button::CLASS_DANGER );
}


echo Plugin::get( Plugin_SetStatus_Main::KEY )?->renderButton();

echo '&nbsp;&nbsp;&nbsp';

echo Plugin::get( Plugin_ForceStatus_Main::KEY )?->renderButton();
