<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\MVC;
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;


/**
 * @var MVC_View $this
 * @var Form     $form
 * @var EShop $eshop
 */

$eshop = $this->getRaw('eshop');
$form = $this->getRaw('form');
$eshop_key = $eshop->getKey();

$base_URL = MVC::getBase($eshop->getBaseId())->getHomepage($eshop->getLocale())->getURL();
?>
<?=$form->field('/eshop_data/'.$eshop_key.'/title')?>
<?=$form->field('/eshop_data/'.$eshop_key.'/menu_title')?>
<?=$form->field('/eshop_data/'.$eshop_key.'/breadcrumb_title')?>
<?=$form->field('/eshop_data/'.$eshop_key.'/meta_keywords')?>
<?=$form->field('/eshop_data/'.$eshop_key.'/meta_description')?>
<?=$form->field( '/eshop_data/'.$eshop_key.'/custom_layout_script' )?>
<?php
$relative_path_fragment = $form->field('/eshop_data/'.$eshop_key.'/relative_path_fragment');
?>
<?=$relative_path_fragment->row()->start()?>
<?=$relative_path_fragment->label()?>

<?=$relative_path_fragment->container()->start()?>
<div class="input-group">
	<span class="input-group-prepend" style="font-weight: bolder"><span class="input-group-text" id="base_URL"><?=$base_URL?></span></span>
	<div style="width: 500px">
		<?=$relative_path_fragment->input()?>
		<?=$relative_path_fragment->error()?>
	</div>
</div>
<?=$relative_path_fragment->container()->end()?>

<?=$relative_path_fragment->row()->end()?>

<?=$form->field('/eshop_data/'.$eshop_key.'/text')?>
