<?php
namespace JetApplicationModule\Shop\Complaints;

use Jet\Form_Field_FileImage;
use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;
use JetApplication\Complaint;

/**
 * @var MVC_View  $this
 * @var Complaint $complaint
 * @var Form_Field_FileImage $img_field
 */

$complaint = $this->getRaw('complaint');

$form = $complaint->getUploadImagesForm();
$img_field = $form->getField('image');

$form->field('image')->input()->addJsAction('onchange', 'JetAjaxForm.submit(this.form.id)');
?>
<div class="card">
	<div class="card-body">
		<h5><?=Tr::_('Images')?></h5>
		<?=$form->start()?>
		
		<div class="btn btn-light btn-upload">
			<div style="display:flex;align-items: center">
				<?=UI::icon('upload')?>&nbsp;<span><?=Tr::_('Select and upload images')?></span>
				<?=$img_field->input()?>
			</div>
		</div>
		
		<?php foreach($img_field->getProblematicFiles() as $problematic_file ):
			foreach($problematic_file->getErrors() as $err_code=>$err_msg):
				echo UI_messages::createDanger( $problematic_file->getFileName().':' . $err_msg );
			endforeach;
		endforeach; ?>
		
		
		<?=$form->end();?>
		
		
		<div style="display: grid;grid-template-columns: 100px 300px 200px 1fr;align-items: center;gap: 20px;margin: 20px;">
			<?php foreach( $complaint->getImages() as $img ):?>
				
				<div>
					<a href="<?=$img->getURL()?>" target="_blank"><img src="<?=$img->getThbURL()?>" style="max-width: 100px; height: auto"></a>
				</div>
				<div><?=$img->getName()?></div>
				<div><?=Locale::size( $img->getSize() )?></div>
				<div>
					<?php if(!$img->isLocked()):
						echo UI::button_delete(' ')->setOnClick(  "deleteImage({$img->getId()})"  );
					endif; ?>
				</div>
			
			<?php endforeach; ?>
		</div>
		
	</div>
</div>
