<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Products;


use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Controller_Main $controller
 */
$controller = $this->getController();

echo $this->controller->getEditorManager()->renderToolbar( form: $this->getRaw('form'));
