<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Products;


use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use JetApplication\Product_Box;
use JetApplication\Product;
use JetApplication\Application_Service_Admin;

/**
 * @var MVC_View   $this
 * @var Product $product
 * @var Form $form
 * @var Product_Box[] $boxes
 */

$product = $this->getRaw('item');

$editable = $this->getBool('editable');

require '_toolbar.phtml';

$form = $this->getRaw('form');
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 1
]);
$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 10
]);

$form->field('groups')->input()->addCustomCssStyle("height: 470px");
?>
<div id="main-col">
	
	<?=$this->getRaw('tabs')?>
	<br>
	
	<?=$form->start()?>
	
	<div style="display: grid;grid-template-columns: 1fr 1fr;gap: 20px;align-items:top">
		<div class="card">
			<h5 class="card-header"><?=Tr::_( 'Groups' )?></h5>
			<div class="card-body">
				<?=$form->field('groups')->input()?>
			</div>
		</div>
		<div class="card">
			<h5 class="card-header"><?=Tr::_( 'Products' )?></h5>
			<div class="card-body">
				<?=Application_Service_Admin::Product()->renderSelectProductsWidget( $form->field('accessory') )?>
			</div>
		</div>
	</div>
	
	<?=$form->end()?>
</div>