<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetShop\Category;

/**
 * @var MVC_View   $this
 */

$product = Controller_Main::getCurrentProduct();

$form = $product->getEditForm();
?>
<form id="category_add_form" method="post">
	<input type="hidden" name="action" value="add_category"/>
	<input type="hidden" name="category_id" id="category_add_form__category_id" value=""/>
</form>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<div style="display: inline-block;margin-top: -20px;">
				<table style="position: relative;top: 15px;">
					<tr>
						<td style="padding-left: 30px;font-weight: bolder;"><?=Tr::_('Add category: ')?></td>
						<td style="width: 400px;"><?=Category::renderSelectCategoryWidget("$('#category_add_form__category_id').val(selected_item.id);$('#category_add_form').submit();" )?></td>
					</tr>
				</table>

			</div>

		<?php endif; ?>

		<?=$this->render('edit/preview_button');?>
	</div>
</div>

<div class="row">

	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>

		<table class="table table-striped">
			<tbody>
			<?php foreach($product->getCategories() as $category): ?>
				<tr>
					<td style="width: 300px;">

						<?php if( !$form->getIsReadonly() ): ?>
							<form method="post" style="display: inline-block">
								<input type="hidden" name="action" value="remove_category"/>
								<input type="hidden" name="category_id" value="<?=$category->getId()?>"/>
								<?=UI::button_delete(' ')->setType('submit')?>
							</form>
						<?php endif; ?>
						<?php if($category->getId()==$product->getMainCategoryId()): ?>
							<b class="info"><?=Tr::_('Main category')?></b>
						<?php else: ?>
							<?php if( !$form->getIsReadonly() ): ?>
							<form method="post" style="display: inline-block">
								<input type="hidden" name="action" value="set_main_category"/>
								<input type="hidden" name="category_id" value="<?=$category->getId()?>"/>
								<?=UI::button(Tr::_('Set as main category'))->setClass('default')->setType('submit')?>
							</form>
							<?php endif; ?>
						<?php endif; ?>

					</td>
					<td><a href="<?=$category->getEditURL()?>" target="_blank"><?=$category->_getPathName()?></a></td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function () {
		select_category.startSelect();

	})
</script>