<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Products;


use Jet\Http_Request;
use Jet\MVC_View;
use JetApplication\Exports;
use JetApplication\Exports_Module;
use JetApplication\EShops;
use JetApplication\EShop;
use JetApplication\Product;


/**
 * @var MVC_View   $this
 * @var Product $product
 * @var Exports_Module $selected_export
 * @var EShop $selected_export_eshop
 */

$product = $this->getRaw('item');

$modules = Exports::getExportModulesList();

$selected_export = $this->getRaw('selected_export');
$selected_export_eshop = $this->getRaw('selected_export_eshop');
$selected_export_code = $this->getString('selected_export_code');
$selected_export_eshop_key = $this->getString('selected_export_eshop_key');

require '_toolbar.phtml';
?>
<div id="main-col">
	
	<?=$this->getRaw('tabs')?>
	
	<br>
	<div style="display: grid;grid-template-columns: 2fr 10fr;gap: 10px;">
		<div>
			<ul class="list-group">
				<?php foreach($modules as $module):
					foreach( EShops::getListSorted() as $eshop):
						if(!$module->isAllowedForShop($eshop)):
							continue;
						endif;
						
						$title = $module->getTitle().' - '.$eshop->getName();
						$link = Http_Request::currentURI(['export'=>$module->getCode(),'export_eshop'=>$eshop->getKey()]);
						
						if($module->getCode()==$selected_export_code && $eshop->getKey()==$selected_export_eshop_key):
							?><li class="list-group-item active"><?=$title?></li><?php
						else:
							?><li class="list-group-item"><a href="<?=$link?>"><?=$title?></a></li><?php
						endif;
					endforeach;
				endforeach; ?>
			</ul>
		</div>
		<div>
			<?php if($selected_export): ?>
				<legend><?=$selected_export->getTitle()?> - <?=$selected_export_eshop->getName()?></legend>
				<?php $selected_export->handleProductSettings( $product, $selected_export_eshop )?>
			<?php endif; ?>
		
		</div>
	</div>

</div>
