<?php
namespace JetShopModule\Admin\Catalog\Products;
use Jet\Mvc_View;
use Jet\Form;
use Jet\UI;
use Jet\Tr;
use Jet\UI_dialog;
use JetShop\Shops;

/**
 * @var Mvc_View $this
 * @var Form $images_form
 * @var Form $image_delete_form
 */

$product = Controller_Main::getCurrentProduct();

?>

<style type="text/css">
	.images_area>div {
		float: left;
	}
</style>

<script type="text/javascript">

	const ImagesHandler = {
		delete_shop_code: null,
		delete_images: null,

		_handleResponse: function( shop_code, response ) {

			for(let el_id in response['snippets']) {
				document.getElementById(el_id).innerHTML = response['snippets'][el_id];
			}

			ImagesHandler.initSort( shop_code );
		},

		initSort: function( shop_code ) {
			$('#images_'+shop_code).sortable({
				revert: true,
				stop: function() {
					ImagesHandler.saveSort( shop_code );
				}
			});
		},

		saveSort: function( shop_code ) {
			var images = [];

			$('#images_'+shop_code).find('.image-thumbnail').each(function ( i, image ) {
				images.push( $(image).data('image') );
			});

			$.ajax({
				url: '?id=<?=$product->getId()?>&page=images&action=save_sort&images='+images.join(',')+'&shop_code='+shop_code,
				dataType: "json",
				success: function( response ) {
					ImagesHandler._handleResponse(shop_code, response);
				}
			});
		},

		deleteImage: function( shop_code, image, url ) {
			ImagesHandler._delete(shop_code, [{
				image: image,
				url: url
			}]);
		},

		deleteImages: function( shop_code )
		{
			var images = [];

			$('.select_image_checkbox').each( function(i, checkbox) {
				if(checkbox.checked) {
					images.push( {
						image: checkbox.value,
						url: checkbox.dataset.url
					} );
				}
			});

			if(images.length) {
				ImagesHandler._delete(shop_code, images);
			}

		},

		_delete: function( shop_code, images ) {

			ImagesHandler.delete_shop_code = shop_code;
			ImagesHandler.delete_images = images;

			let html = '';
			for(let i=0;i<images.length;i++) {
				let image = images[i];

				html += '<div class="image-thumbnail" style="float:left;width: 180px;height: 180px;background-image: url('+image.url+');background-size: 170px auto;"></div>';
			}

			$('#image_delete_confirm_area').html( html );

			$('#delete_image_confirm').modal('show');
		},

		deleteConfirm: function () {
			let images = [];
			for(let i=0; i<ImagesHandler.delete_images.length;i++) {
				images.push(encodeURIComponent(ImagesHandler.delete_images[i].image));
			}

			$.ajax({
				url: '?id=<?=$product->getId()?>&page=images&action=delete&shop_code='+ImagesHandler.delete_shop_code+'&images='+images.join(','),
				dataType: "json",
				success: function( response ) {
					ImagesHandler._handleResponse(ImagesHandler.delete_shop_code, response);
				}
			});
			$('#delete_image_confirm').modal('hide');

		},


		upload: function( shop_code ) {
			JetAjaxForm.submitMultiUpload(
				'upload_form_'+shop_code,
				'images',
			);
		}
	};

	$(document).ready(function () {
		<?php foreach(Shops::getList() as $shop):
		$shop_code = $shop->getCode();
		 ?>
		ImagesHandler.initSort('<?=$shop_code?>');
		<?php endforeach; ?>
	})
</script>

	<div class="row toolbar" id="main-toolbar">
		<div class="col-md-12">
			<?=UI::button_goBack()?>

			<?=$this->render('edit/preview_button');?>
		</div>
	</div>

<div class="row">
	<div class="col-md-12">
		<?=$this->getRaw('tabs')?>

	<?php foreach(Shops::getList() as $shop):
		$shop_code = $shop->getCode();

		$shop_data = $product->getShopData($shop_code);
		$this->setVar('shop_code', $shop_code);
	?>
		<?=$shop_data->renderShopDataBlock_start()?>


		<div style="background-color: #f0f0f0;border-radius: 5px;margin: 10px;padding: 10px;">
			<div class="images_area" id="images_<?=$shop_code?>" style="height: 500px;overflow: auto;margin: 5px;padding: 5px;">
				<?php
				require 'images/list.phtml';
				?>
			</div>
		</div>

		<table style="width: 100%">
			<tr>
				<td>
					<form id="upload_form_<?=$shop_code?>" action="?id=<?=$product->getId()?>&page=images&action=upload&shop_code=<?=$shop_code?>">
						<div class="btn btn-light btn-upload">
							<?=UI::icon('upload')?>&nbsp;<span><?=Tr::_('Select and upload images' )?></span>
							<input type="file" multiple id="upload_files_<?=$shop_code?>" name="images[]" class="upload-button" onchange="ImagesHandler.upload('<?=$shop_code?>');">
						</div>
					</form>
				</td>
				<td align="right" style="padding: 10px">
					<?=UI::button_delete(Tr::_('Delete selected images'))->setOnclick("ImagesHandler.deleteImages('$shop_code');")?>
				</td>
			</tr>
		</table>

		<?=$shop_data->renderShopDataBlock_end()?>
		<br/>
	<?php endforeach; ?>

	</div>
</div>


<?php
$delete_dialog = new UI_dialog('delete_image_confirm', Tr::_('Do you really want to delete those images?'), 650);

echo $delete_dialog->start();
	?>
	<div id="image_delete_confirm_area" style="height: 250px;overflow: auto">

	</div>
	<?php
echo $delete_dialog->footer();
	echo UI::button_delete()->setOnclick("ImagesHandler.deleteConfirm();");
echo $delete_dialog->end();
