<?php
namespace JetApplicationModule\Admin\Catalog\Products;
use Jet\MVC_View;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View $this
 */


?>
<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=$this->render('edit/nav_button');?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>
		
		<?=Admin_Managers::Image()->renderProductImageManagement();?>
	</div>
</div>


