<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\Locale;
use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use Jet\UI;
use JetShop\Price;
use JetShop\Shops;
use JetShop\Sticker;
use JetShop\WarehouseManagement_Item;
use JetShop\WarehouseManagement_Warehouse;


/**
 * @var MVC_View   $this
 */

$product = Controller_Main::getCurrentProduct();

$form = $product->getEditForm();

$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 8 ] );



?>


<?=$form->start()?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()?>
		<?php endif; ?>

		<?=$this->render('edit/preview_button');?>
	</div>
</div>

<div class="row">

	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>

		<br/>

		<?=$form->field('is_active')?>
		<?=$form->field('ean')?>
		<?=$form->field('internal_code')?>
		<?=$form->field('brand_id')?>
		<?=$form->field('supplier_id')?>

		<legend class="sub"><?=Tr::_('Stickers')?></legend>
		<?php foreach(Sticker::getList() as $sticker): ?>
			<?=$form->field('/sticker/'.$sticker->getCode())?>
		<?php endforeach; ?>

		<?php foreach(Shops::getList() as $shop):
			$shop_key = $shop->getKey();

			$shop_data = $product->getShopData( $shop );
			?>
			<?=$shop_data->renderShopDataBlock_start()?>

			<fieldset>
				<legend class="sub"><?=Tr::_('Main data')?></legend>

				<?=$form->field('/shop_data/'.$shop_key.'/is_active')?>

				<?=$form->field('/shop_data/'.$shop_key.'/name')?>
				<?=$form->field('/shop_data/'.$shop_key.'/variant_name')?>
				<?php
				$form->field('/shop_data/'.$shop_key.'/description')->input()->addCustomCssStyle('height:600px');
				?>
				<?=$form->field('/shop_data/'.$shop_key.'/description')?>
				<?=$form->field('/shop_data/'.$shop_key.'/short_description')?>
			</fieldset>

			<fieldset>
				<legend class="sub"><?=Tr::_('SEO')?></legend>
				<?=$form->field('/shop_data/'.$shop_key.'/seo_h1')?>
				<?=$form->field('/shop_data/'.$shop_key.'/seo_title')?>
				<?=$form->field('/shop_data/'.$shop_key.'/seo_description')?>
				<?=$form->field('/shop_data/'.$shop_key.'/seo_keywords')?>
				<?=$form->field('/shop_data/'.$shop_key.'/internal_fulltext_keywords')?>
			</fieldset>

			<fieldset>
				<legend class="sub"><?=Tr::_('Price')?></legend>

				<?=$form->field('/shop_data/'.$shop_key.'/vat_rate')?>
				<?=$form->field('/shop_data/'.$shop_key.'/standard_price')?>
				<?=$form->field('/shop_data/'.$shop_key.'/action_price')?>
				<?=$form->field('/shop_data/'.$shop_key.'/action_price_valid_from')?>
				<?=$form->field('/shop_data/'.$shop_key.'/action_price_valid_till')?>
				<?=$form->field('/shop_data/'.$shop_key.'/sale_price')?>
				<?=$form->field('/shop_data/'.$shop_key.'/reset_sale_after_sold_out')?>
				<?=$form->field('/shop_data/'.$shop_key.'/deactivate_product_after_sold_out')?>

				<div class="row">
					<label class="col-md-2 col-form-label" style="font-weight: bolder;font-size: 20px;margin-top: -3px;"><?=Tr::_('Price:')?></label>
					<div class="col-md-8" style="font-weight: bolder;font-size: 25px;"><?=Price::formatWithCurrency($product->getShopData($shop)->getFinalPrice(), $shop )?></div>
				</div>

				<?php if($product->getShopData($shop)->getDiscountPercentage()>0): ?>
					<div class="row" style="opacity: 0.5">
						<label class="col-md-2 col-form-label" style="font-weight: bolder;font-size: 15px;margin-top: -3px;"><?=Tr::_('Discount:')?></label>
						<div class="col-md-8" style="font-weight: bolder;font-size: 20px;"><?=$product->getShopData($shop)->getDiscountPercentage();?>%</div>
					</div>
				<?php endif; ?>

			</fieldset>
			<fieldset>
				<legend class="sub"><?=Tr::_('Availability')?></legend>

				<?=$form->field('/shop_data/'.$shop_key.'/delivery_class_code')?>
				<?=$form->field('/shop_data/'.$shop_key.'/delivery_term_code')?>
				<?=$form->field('/shop_data/'.$shop_key.'/date_available')?>
				<div class="row">
					<label class="col-form-label col-md-2"><?=Tr::_('Stock status:')?></label>
					<div class="col-md-8">
						<table class="table table-striped">
							<tr>
								<td style="width: 150px;font-weight: bolder;"><?=Tr::_('Total available:')?></td>
								<td style="font-weight: bolder;"><?=$product->getShopData($shop)->getStockStatus()?></td>
							</tr>
							<?php foreach(WarehouseManagement_Warehouse::getList() as $warehouse):
								if(!$warehouse->hasShop($shop)) {
									continue;
								}

								$item = WarehouseManagement_Item::get($warehouse->getCode(), $product->getId());
								?>
								<tr>
									<td colspan="2">
										<b><?=$warehouse->getInternalName()?></b>
									</td>
								</tr>

								<tr>
									<td><?=Tr::_('Available:')?></td>
									<td><?=Locale::getCurrentLocale()->formatInt($item->getAvailable())?></td>
								</tr>
								<tr>
									<td><?=Tr::_('In stock:')?></td>
									<td><?=Locale::getCurrentLocale()->formatInt($item->getInStock())?></td>
								</tr>
								<tr>
									<td><?=Tr::_('Blocked:')?></td>
									<td><?=Locale::getCurrentLocale()->formatInt($item->getBlocked())?></td>
								</tr>
								<tr>
									<td><?=Tr::_('Required:')?></td>
									<td><?=Locale::getCurrentLocale()->formatInt($item->getRequired())?></td>
								</tr>
							<?php endforeach; ?>
						</table>
					</div>
				</div>
			</fieldset>



			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach; ?>


	</div>
</div>

<?=$form->end()?>
