<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\Form_Field_MultiSelect;
use Jet\MVC_View;
use Jet\Form;
use Jet\UI;
use JetShop\Category;
use JetShop\Parametrization_Group;

/**
 * @var MVC_View   $this
 */

$product = Controller_Main::getCurrentProduct();

$form = $product->getParametrizationEditForm();

$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 1 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 8 ] );

/**
 * @var Category[] $show_categories
 * @var Parametrization_Group[][] $show_groups
 */
$show_categories = [];
$show_groups = [];

foreach($product->getCategories() as $category) {
	foreach($category->getParametrizationGroups() as $group) {
		foreach($group->getProperties() as $property) {
			if(!isset($show_categories[$category->getId()])) {
				$show_categories[$category->getId()] = $category;
				$show_groups[$category->getId()] = [];
			}

			if(!isset($show_groups[$category->getId()][$group->getId()])) {
				$show_groups[$category->getId()][$group->getId()] = $group;
			}

			continue 2;
		}
	}
}

?>


<?=$form->start()?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()?>
		<?php endif; ?>

		<?=$this->render('edit/preview_button');?>
	</div>
</div>

<div class="row">

	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>

		<?php foreach($show_categories as $category): ?>
			<fieldset>
			<legend><a href="<?=$category->getParametrizationEditUrl()?>" target="_blank"><?=$category->_getPathName()?></a></legend>
			<?php foreach($show_groups[$category->getId()] as $group): ?>
				<fieldset>
					<legend class="sub"><a href="<?=$category->getParametrizationGroupEditUrl($group->getId())?>" target="_blank"><?=$group->getShopData()->getLabel()?></a></legend>
						<?php
						foreach($group->getProperties() as $property):
							$prefix = '/'.$category->getId().'/'.$group->getId().'/'.$property->getId().'/';

							$value = $form->field($prefix.'value');
							$information_in_not_available = $form->field($prefix.'information_in_not_available');

							if($value instanceof Form_Field_MultiSelect) {
								$value->input()->addCustomCssStyle('height:300px');
							}

							$value->setLabel( '<a href="'.$category->getParametrizationPropertyEditUrl( $group->getId(), $property->getId() ).'" target="_blank">'.$value->getLabel().'</a>');

							echo $value;


							?>
							<div style="opacity: 0.3;position: relative;top: -13px;">
								<?=$information_in_not_available?>
							</div>
							<?php
						endforeach;
						?>
				</fieldset>
			<?php endforeach; ?>
			</fieldset>
		<?php endforeach; ?>


	</div>
</div>

<?=$form->end()?>
