<?php
namespace JetApplicationModule\Admin\Catalog\Products;


use Jet\MVC_View;
use Jet\Form_Renderer;
use Jet\Tr;
use JetApplication\Admin_Managers;
use JetApplication\Product;

/**
 * @var MVC_View   $this
 * @var Product $product
 */

$product = $this->getRaw('item');

$form = $product->getParametersEditForm();

$this->setVar('form', $form);

$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 6 ] );

$property_manager = Admin_Managers::Property();

require '_toolbar.phtml';


$show = function( Product $product, string $main_prefix = '' ) use ($form, $property_manager) {
	$kind = $product->getKindOfProduct();
	if(!$kind) {
		return;
	}
	
	?>
		<br>
		<div class="form-group row">
			<div class="col-md-1"><?=Tr::_('Kind of product:')?></div>
			<div class="col-md-8"><?=Admin_Managers::KindOfProduct()->showName($kind->getId())?></div>
		</div>
		<br>
		<?php
		foreach( $kind->getPropertyIds() as $property_id ):
			echo $property_manager->renderProductPropertyEditFormField($form, $property_id, $main_prefix);
		endforeach;
};
?>

<?=$form->start()?>

<div id="main-col">
		<?=$this->getRaw('tabs')?>
		
		<?php if($product->isSet()):
			foreach($product->getSetItems() as $set_item):
				$set_item_product = Product::get( $set_item->getItemProductId() );
			
				if(!$set_item_product) {
					continue;
				}
				?>
				<fieldset>
					<legend><a href="<?=$set_item_product->getEditURL()?>"><?=$set_item_product->getAdminTitle()?></a></legend>
					<?php $show( $set_item_product, '/set_item/'. $set_item_product->getId()  ); ?>
				</fieldset>
				<?php
			endforeach;
			
		else:
			$show( $product );
		endif; ?>
</div>

<?=$form->end()?>
