<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\UI;
use Jet\Mvc_View;
use JetShop\Shops;

/**
 * @var Mvc_View $this
 */
$product = Controller_Main::getCurrentProduct();

?>
<div class="dropdown">
	<button class="btn btn-light dropdown-toggle" type="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		<?=UI::icon('eye');?>
	</button>
	<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
		<?php foreach( Shops::getList() as $shop ): ?>
			<div class="dropdown-item" style="padding-bottom: 10px;">
				<a href="<?=$product->getURL($shop->getCode())?>" target="_blank"><?=$shop->getName()?></a>
			</div>
		<?php endforeach; ?>
	</div>
</div>
