<?php
namespace JetShopModule\Admin\Catalog\Products;

use Jet\Form;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;
use JetShop\Product;

/**
 * @var MVC_View   $this
 */

$product = Controller_Main::getCurrentProduct();

$edit_form = $product->getSetSetupForm();
$add_form = $product->getSetAddItemForm();


$edit_form->setDefaultLabelWidth([
		Form::LJ_SIZE_MEDIUM => 2
]);
$edit_form->setDefaultFieldWidth([
	Form::LJ_SIZE_MEDIUM => 5
]);

$edit_form->field('set_strategy')->input()->addJsAction('onchange', 'toggleSetDiscount(this.options[this.selectedIndex].value)');

?>
<?=$add_form->start()?>
	<?=$add_form->field('product_id')?>
<?=$add_form->end()?>

<?=$edit_form->start()?>
<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$edit_form->getIsReadonly() ): ?>
			<?=UI::button_save()?>

			<div style="display: inline-block;margin-top: -20px;">
				<table style="position: relative;top: 15px;">
					<tr>
						<td style="padding-left: 30px;font-weight: bolder;"><?=Tr::_('Add product: ')?></td>
						<td style="width: 400px;"><?=Product::renderSelectProductWidget("$('#set_add_item_form__product_id').val(selected_item.id);$('#set_add_item_form').submit();" )?></td>
					</tr>
				</table>

			</div>

		<?php endif; ?>

		<?=$this->render('edit/preview_button');?>
	</div>
</div>

<div class="row">

	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>

		<br/>
		<?=$edit_form->field('set_strategy')?>
		<div id="set_discount_area" style="display: <?=($product->getSetStrategy()==Product::SET_STRATEGY_DISCOUNT)?'block':'none'?>">
			<?=$edit_form->field('set_discount')?>
		</div>
		<br/>

		<table class="table table-striped">
			<thead>
				<tr>
					<th style="width: 150px;"> </th>
					<th style="width: 150px;"><?=Tr::_('Count')?></th>
					<th style="width: 150px;"><?=Tr::_('Sort order')?></th>
					<th><?=Tr::_('Product')?></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($product->getSetItems() as $set_item):
				$p_id = $set_item->getItemProductId();
				$item_product = Product::get($p_id);
				if(!$item_product) {
					?>
					<tr>
						<td>
							<?php if( !$edit_form->getIsReadonly() ): ?>
								<?=UI::button_delete(Tr::_('Remove'))->setUrl(Http_Request::currentURI(['remove_item'=>$p_id]))?>
							<?php endif; ?>
						</td>
						<td></td>
						<td></td>
						<td><?=UI_messages::createDanger(Tr::_('Unknown product %ID%', ['ID'=>$set_item->getItemProductId()]))->setCloseable(false)?></td>
					</tr>
					<?php
					continue;
				}
				?>
				<tr>
					<td>
						<?php if( !$edit_form->getIsReadonly() ): ?>
							<?=UI::button_delete(Tr::_('Remove'))->setUrl(Http_Request::currentURI(['remove_item'=>$p_id]))?>
						<?php endif; ?>
					</td>
					<td><?=$edit_form->field('/p'.$p_id.'/count')->input()?></td>
					<td><?=$edit_form->field('/p'.$p_id.'/sort_order')->input()?></td>
					<td style="padding-top: 17px;"><?=$item_product->renderActiveState()?> <a href="<?=$item_product->getEditURL()?>"><?=$item_product->getAdminTitle()?></a></td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<?=$edit_form->end()?>

<script type="text/javascript">
	function toggleSetDiscount( selected_value )
	{
		if(selected_value=='<?=Product::SET_STRATEGY_DISCOUNT?>') {
			$('#set_discount_area').show();
		} else {
			$('#set_discount_area').hide();
		}
	}

</script>
