<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\Form_Renderer;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;
use JetApplication\Admin_Managers;
use JetApplication\Pricelists;
use JetApplication\Product;

/**
 * @var MVC_View   $this
 * @var Product $product
 */

$product = $this->getRaw('item');

$editable = $product->isEditable();


$edit_form = $product->getSetSetupForm();
$add_form = $product->getSetAddItemForm();


$edit_form->renderer()->setDefaultLabelWidth([
		Form_Renderer::LJ_SIZE_MEDIUM => 2
]);
$edit_form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 5
]);

$product = $this->getRaw('item');

require '_toolbar.phtml';

?>
<div id="main-col">
		<?=$this->getRaw('tabs')?>


<?php if($editable): ?>
	<?=$add_form->start()?>
		<?=$add_form->field('product_id')?>
	<?=$add_form->end()?>
<?php endif; ?>

<div class="toolbar" style="display: grid;grid-template-columns: 200px 1fr;align-items: center">
	<?php if( $editable ): ?>
			<div style="text-align: right;font-weight: bolder;"><?=Tr::_('Add product: ')?></div>
			<div style="width: 400px;"><?=Admin_Managers::Product()->renderSelectWidget(
				on_select: "$('#set_add_item_form__product_id').val(selected_item.id);$('#set_add_item_form').submit();",
				only_type_filter: [Product::PRODUCT_TYPE_REGULAR]
			)?></div>
	<?php endif; ?>
	
</div>

<?=$edit_form->start()?>
<div class="row">

	<div class="col-md-12">


		<table class="table table-striped">
			<thead>
				<tr>
					<th style="width: 150px;"> </th>
					<th style="width: 150px;"><?=Tr::_('Count')?></th>
					<th style="width: 150px;"><?=Tr::_('Sort order')?></th>
					<th><?=Tr::_('Product')?></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($product->getSetItems() as $set_item):
				$p_id = $set_item->getItemProductId();
				$item_product = Product::get($p_id);
				if(!$item_product) {
					?>
					<tr>
						<td>
							<?php if( !$edit_form->getIsReadonly() ): ?>
								<?=UI::button_delete(Tr::_('Remove'))->setUrl(Http_Request::currentURI(['remove_item'=>$p_id]))?>
							<?php endif; ?>
						</td>
						<td></td>
						<td></td>
						<td><?=UI_messages::createDanger(Tr::_('Unknown product %ID%', ['ID'=>$set_item->getItemProductId()]))->setCloseable(false)?></td>
					</tr>
					<?php
					continue;
				}
				?>
				<tr>
					<td>
						<?php if( !$edit_form->getIsReadonly() ): ?>
							<?=UI::button_delete(Tr::_('Remove'))->setUrl(Http_Request::currentURI(['remove_item'=>$p_id]))?>
						<?php endif; ?>
					</td>
					<td><?=$edit_form->field('/p'.$p_id.'/count')->input()?></td>
					<td><?=$edit_form->field('/p'.$p_id.'/sort_order')->input()?></td>
					<td style="padding-top: 17px;"><?=$item_product->renderActiveState()?> <a href="<?=$item_product->getEditUrl()?>"><?=$item_product->getAdminTitle()?></a></td>
				</tr>
			<?php endforeach; ?>
			</tbody>
			<tfoot>
			<tr>
				<td></td>
				<td>
					<?php if($editable): ?>
					<?=UI::button_save()?>
					<?php endif; ?>
				</td>
			</tr>
			</tfoot>
		</table>
		
		<h3><?=Tr::_('Price settings')?></h3>
		<?php foreach(Pricelists::getList() as $pricelist):
					$field_name_prefix = '/set_price/'.$pricelist->getCode().'/';
					
					$edit_form->field($field_name_prefix.'discount_type')->label()->setWidth([
						Form_Renderer::LJ_SIZE_MEDIUM => 2
					]);
					$edit_form->field($field_name_prefix.'discount_value')->label()->setWidth([
						Form_Renderer::LJ_SIZE_MEDIUM => 2
					]);
					$edit_form->field($field_name_prefix.'discount_type')->input()->setWidth([
						Form_Renderer::LJ_SIZE_MEDIUM => 2
					]);
					$edit_form->field($field_name_prefix.'discount_value')->input()->setWidth([
						Form_Renderer::LJ_SIZE_MEDIUM => 2
					]);
				?>
				<fieldset>
					<legend><?=$pricelist->getName()?></legend>
				<div class="row" style="padding-bottom: 10px;">
					<div class="col-md-2" style="font-weight: bolder"><?=Tr::_('Calculated price:')?></div>
					<div class="col-md-2" style="font-weight: bolder">
						<?=Admin_Managers::PriceFormatter()->formatWithCurrency( $pricelist, $product->getCalculatedSetPrice( $pricelist ) )?>
					</div>
				</div>
			
				<?=$edit_form->field($field_name_prefix.'discount_type');?>
				<?=$edit_form->field($field_name_prefix.'discount_value');?>
				<?php if(!$edit_form->getIsReadonly()): ?>
					<div class="row">
						<div class="col-md-2"></div>
						<div class="col-md-2">
							<?=UI::button_save()?>
						</div>
					</div>
				<?php endif; ?>
				<div class="row" style="padding-top: 10px;">
					<div class="col-md-2" style="font-weight: bolder;font-size: 1.2rem"><?=Tr::_('Price:')?></div>
					<div class="col-md-2" style="font-weight: bolder;font-size: 1.2rem">
						<?=Admin_Managers::PriceFormatter()->formatWithCurrency( $pricelist, $product->getPrice( $pricelist ) )?>
					</div>
				</div>
				</fieldset>
				<br>
			<?php endforeach; ?>
		
	</div>
</div>

<?=$edit_form->end()?>

</div>