<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Admin_Managers;


/**
 * @var MVC_View   $this
 * @var Product $product
 */

$product = $this->getRaw('item');

$editable = $product->isEditable();

$similar = $product->getSimilar();

require '_toolbar.phtml';
?>
<div id="main-col">

	<?=$this->getRaw('tabs')?>
		
<?php if($editable): ?>
	<div class="toolbar">
		<div><b><?=Tr::_('Add similar product:')?></b></div>
		<div style="width: 400px"><?=Admin_Managers::Product()->renderSelectWidget(on_select: "SimilarProducts.add(selected_item.id)");?></div>
	</div>
<?php endif; ?>

	<div id="similar_products_sort_area" class="card card-body">
		<?php foreach($similar as $s): ?>
		<div class="sort_item card card-body"
		     data-id="<?=$s->getSimilarProductId()?>"
		     style="display: grid;grid-template-columns: 20px 60px 1fr;grid-template-rows: 40px;align-items: center;margin: 10px;">
			<div>
				<?php if($editable):
					echo UI::icon('arrows-v');
				endif; ?>
			</div>
			<div>
				<?php if($editable && $s->getSimilarProductId()!=$product->getId()): ?>
				<?=UI::button_delete(' ')->setUrl( Http_Request::currentURI(['delete'=>$s->getSimilarProductId()]) )?>
				<?php endif;?>
			</div>
			<div><?=Admin_Managers::Product()->showName( $s->getSimilarProductId() )?></div>
		</div>
		<?php endforeach; ?>
	</div>
	
</div>

<?php if($editable): ?>
<script>
	const SimilarProducts = {
		init: () => {
			$('#similar_products_sort_area')['sortable']({
				//revert: true,
				stop: function() {
					
					let items = [];

					$('#similar_products_sort_area').find('.sort_item').each(function ( i, item ) {
						items.push( $(item).data('id') );
					});

					items = items.join(',');

					location = '<?=Http_Request::currentURI()?>&sort='+items;
				}
			});
			
		},
		
		add: ( id ) => {
			location = '<?=Http_Request::currentURI()?>&add='+id;
		}
	};

	SimilarProducts.init();
</script>

<?php endif; ?>