<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Products;


use Jet\Tr;
use Jet\MVC_View;
use Jet\UI;
use Jet\UI_button;
use Jet\UI_messages;
use Jet\UI_tabs;
use Jet\Form;
use JetApplication\Product;

/**
 * @var MVC_View $this
 * @var Product $item
 * @var UI_tabs $tabs
 * @var Form $set_price_form
 * @var Form $set_availability_form
 */

$item = $this->getRaw('item');
$tabs = $this->getRaw('tabs');

$set_price_form = $this->getRaw('set_price_form');
$set_availability_form = $this->getRaw('set_availability_form');

?>

<div style="display: inline-block">
	<?php if($item->isVariant()):
		$variant_master = $item->getVariantMasterProduct();
		?>
		<?=UI_messages::createWarning(Tr::_('This is variant of <a href="%URL%">%NAME%</a>', [
		'URL' => $variant_master->getEditUrl(),
		'NAME' => $variant_master->getAdminTitle()
	]))->setCloseable(false)?>
	<?php endif; ?>
</div>


<?php
if($set_price_form):
	echo UI::button( Tr::_('Set price'))
				->setClass(UI_button::CLASS_DANGER)
				->setOnClick("$('#set_price_dialog').modal('show')");
endif;



if($set_availability_form):
	echo UI::button( Tr::_('Set availability'))
			->setClass(UI_button::CLASS_DANGER)
			->setOnClick("$('#set_availability_dialog').modal('show')");
endif;