<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\MVC_View;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;
use Jet\UI_dialog;
use JetApplication\Product;
use JetApplication\Shops;

/**
 * @var MVC_View   $this
 * @var Product $new_variant
 */

$product = Controller_Main::getCurrentProduct();



$new_variant = $this->getRaw('new_variant');
$add_form = $new_variant->getAddVariantForm();

$add_form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
$add_form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 10 ] );


$variants_update_form = $product->getUpdateVariantsForm();

$variants = $product->getVariants();

$variant_control_properties = $product->getKind()?->getVariantSelectorProperties();

$add_dialog = UI::dialog('variant_add_dialog', Tr::_('Add variant'), UI_dialog::SIZE_LARGE);
?>
<?php require 'images/js.phtml'; ?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=$this->render('edit/nav_button');?>


		<?php if(!$add_form->getIsReadonly()): ?>
			<?=UI::button_create('Add variant')->setOnclick("$('#variant_add_dialog').modal('show')")?>
		<?php endif; ?>

		<?php if($variants && !$variants_update_form->getIsReadonly()): ?>
			<?=UI::button_save()->setOnclick("$('#".$variants_update_form->getId()."').submit()");?>
		<?php endif; ?>
	</div>
</div>


<div class="row">

	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>

		<?php if($variants): ?>
		<fieldset>
			<legend><?=Tr::_('Variants')?></legend>

			<?=$variants_update_form->start()?>
				<?php foreach($variants as $variant): ?>
			<table class="table table-striped">
				<thead>
				<tr>
					<th><a href="<?=$variant->getEditURL()?>" target="_blank"><?=$variant->getShopData()->getName()?></a></th>
					<th><?=Tr::_('Name of variant')?></th>
					
					<?php
					if($variant_control_properties):
						foreach($variant_control_properties as $property): ?>
							<th>
								<a href="<?=$property->getEditURL()?>" target="_blank"><?=$property->getInternalName()?></a>
							</th>
						<?php
						endforeach;
					endif;
					?>
					<th></th>

				</tr>
				</thead>
				<tr>
					<td nowrap="">
						<table>
							<tr>
								<td><?=Tr::_('Internal code:')?></td>
								<td><a href="<?=$property->getEditURL()?>" target="_blank"><?=$variant->getInternalCode()?></a></td>
							</tr>
							<tr>
								<td><?=Tr::_('EAN:')?></td>
								<td><a href="<?=$property->getEditURL()?>" target="_blank"><?=$variant->getEan()?></a></td>
							</tr>
							<tr>
								<td><?=Tr::_('ID:')?></td>
								<td><a href="<?=$property->getEditURL()?>" target="_blank"><?=$variant->getId()?></a></td>
							</tr>
						</table>
						
					</td>
					<td nowrap="">
						<table>
						<?php foreach(Shops::getListSorted() as $shop):
							$shop_key = $shop->getKey();
							$shop_name = $shop->getShopName(); ?>
							<tr>
								<td><?=UI::flag( $shop->getLocale() )?> <?=$shop_name?>:</td>
								<td><?=$variants_update_form->field('/'.$variant->getId().'/'.$shop_key.'/variant_name')->input()->addCustomCssStyle('width:400px;')?></td>
							</tr>

						<?php endforeach; ?>
						</table>
					</td>

					<?php
					if($variant_control_properties):
						foreach($variant_control_properties as $property): ?>
						<td>
							<?=$variants_update_form->field('/'.$variant->getId().'/'.$property->getId().'/value')->input()->addCustomCssStyle('width:400px;')?>
							<div style="opacity: 0.3;position: relative;top: -5px;width: 300px;">
							<?=$variants_update_form->field('/'.$variant->getId().'/'.$property->getId().'/information_in_not_available')->input()?>
							</div>
						</td>
					<?php
						endforeach;
					endif;
					?>

					<td width="100%">

					</td>
				</tr>
			</table>
			<?php
			$this->setVar('product', $variant);
			$this->setVar('suffix', 'variant_'.$variant->getId());
			require 'images/edit.phtml';
			?>
				<br><br><br>
			<?php endforeach; ?>
			
			<?=$variants_update_form->end()?>
		</fieldset>
		<br/>
		<?php endif; ?>
	</div>
</div>


<?php if(!$add_form->getIsReadonly()): ?>
	<?=$add_form->start()?>
	<?=$add_dialog->start()?>

	<?=$add_form->field('ean')?>
	<?=$add_form->field('internal_code')?>

	<?php foreach(Shops::getListSorted() as $shop):
		$shop_key = $shop->getKey();

		$shop_data = $product->getShopData( $shop );
		?>
		<?=$shop_data->renderShopDataBlock_start()?>

		<?=$add_form->field('/shop_data/'.$shop_key.'/variant_name')?>
		<?=$shop_data->renderShopDataBlock_end()?>
	<?php endforeach; ?>

	<?=$add_dialog->footer()?>
		<?=UI::button_save()?>
	<?=$add_dialog->end()?>
	<?=$add_form->end()?>
<?php endif; ?>
