<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Catalog\Products;


use Jet\Form;
use Jet\Http_Request;
use Jet\Locale;
use Jet\MVC_View;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use Jet\UI_dialog;
use JetApplication\Admin_Managers;
use JetApplication\Availabilities;
use JetApplication\Pricelists;
use JetApplication\EShops;
use JetApplication\EShop;
use JetApplication\Product;

/**
 * @var MVC_View   $this
 * @var Product $new_variant
 * @var Product $product
 * @var Controller_Main $controller
 */
$controller = $this->getController();

$product = $this->getRaw('item');



$new_variant = $this->getRaw('new_variant');
if($new_variant) {
	$add_form = $new_variant->getAddVariantForm();
	
	$add_form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
	$add_form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 10 ] );
	
	$add_dialog = UI::dialog('variant_add_dialog', Tr::_('Add variant'), UI_dialog::SIZE_EXTRA_LARGE);
} else {
	$add_form = null;
}



$variants_update_form = $product->getUpdateVariantsForm();

$variants_update_form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
$variants_update_form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 3 ] );


$variants = $product->getVariants();

$kind = $product->getKindOfProduct();

echo $this->controller->getEditorManager()->renderToolbar(
	form:  $variants_update_form,
	toolbar_renderer: function() use ($add_form, $product) {
		
		if($add_form) {
			echo '&nbsp;&nbsp;&nbsp;&nbsp;';
			echo UI::button_create( Tr::_('Add new variant') )
				->setOnClick("$('#variant_add_dialog').modal('show')")
				->setClass( UI_button::CLASS_SUCCESS );
		}
	}
);

$showPropertyEditForm = function( Product $product, string $main_prefix, Form $form ) {
	$kind = $product->getKindOfProduct();
	if(!$kind) {
		return;
	}
	
	$property_manager = Admin_Managers::Property();
	
	foreach( $kind->getPropertyIds() as $property_id ):
		echo $property_manager->renderProductPropertyEditFormField($form, $property_id, $main_prefix);
	endforeach;
};

?>




<div id="main-col">
		<?=$this->getRaw('tabs')?>
		
		<?php if($variants): ?>
		<?=$variants_update_form->start()?>

		<?php foreach($variants as $variant): ?>
		<div class="card shadow" style="margin: 40px;">
			<div class="card-body">

					<div style="padding-right: 20px;">
						<div style="display: flex;align-items: center;gap: 5px;">
							<div>
								<?php echo Admin_Managers::EntityEdit()->renderPreviewButton( $variant ); ?>
							</div>
							<div>
								<?=Tr::_('ID:')?><a href="<?=$variant->getEditUrl()?>" target="_blank"><?=$variant->getId()?></a>
							</div>
							<div style="padding-left: 50px;">
								<?=Admin_Managers::EntityEdit()->renderEntityActivation(
									entity: $variant,
									editable: !$variants_update_form->getIsReadonly(),
									deactivate_url_creator: function() use ($variant) : string {
										return Http_Request::currentURI([
											'deactivate_variant'=>$variant->getId()
										]);
									},
									activate_url_creator: function() use ($variant) : string {
										return Http_Request::currentURI([
											'activate_variant'=>$variant->getId()
										]);
									},
									activate_completely_url_creator: function() use ($variant) : string {
										return Http_Request::currentURI([
											'activate_variant_completely'=>$variant->getId()
										]);
									},
									deactivate_per_eshop_url_creator: function( EShop $eshop ) : string {
										return '';
									},
									activate_per_eshop_url_creator: function( EShop $eshop ) : string {
										return '';
									}
								
								);?>
							</div>
							
						</div>
						
						<div>
							<?=$variants_update_form->field('/'.$variant->getId().'/internal_name_of_variant')?>
							<?=$variants_update_form->field('/'.$variant->getId().'/internal_code')?>
							<?=$variants_update_form->field('/'.$variant->getId().'/ean')?>
							<?=$variants_update_form->field('/'.$variant->getId().'/supplier_code')?>
							<?=$variants_update_form->field('/'.$variant->getId().'/variant_priority')?>
							
						</div>
					</div>
					<div>
					</div>
				
				<div style="display: grid;grid-template-columns: 200px 1fr;gap: 10px;margin: 10px;">
					<?php foreach( EShops::getListSorted() as $eshop): ?>
						<div><?=UI::flag($eshop->getLocale())?> <?=$eshop->getName()?></div>
						<div style="display: flex;align-items: center;gap: 10px;">
							<label><?=$variants_update_form->field('/'.$variant->getId().'/'.$eshop->getKey().'/variant_name')->getLabel()?></label>
							<?=$variants_update_form->field('/'.$variant->getId().'/'.$eshop->getKey().'/variant_name')->input()?>
						</div>
					<?php endforeach; ?>
				</div>
				<br><br>
				
				<div style="display: flex;gap: 10px;">
					<?php foreach( Availabilities::getList()  as $availability): ?>
						<fieldset>
							<legend class="sub"><?=Tr::_('Availability')?> - <?=$availability->getName()?></legend>
							
							<table class="table table-striped">
								<tr>
									<td style="width: 200px;"><?=Tr::_('Number of available:');?></td>
									<td><b><?=Locale::float( $variant->getInStockQty($availability) )?> <?=$variant->getKindOfProduct()?->getMeasureUnit()?->getName()?></b></td>
								</tr>
								<tr>
									<td><?=Tr::_('Length of delivery:');?></td>
									<td><b><?=Locale::int( $variant->getLengthOfDelivery($availability) )?></b></td>
								</tr>
								<tr>
									<td><?=Tr::_('Available from:');?></td>
									<td><?=Locale::date( $variant->getAvailableFrom($availability) )?></td>
								</tr>
							</table>
						
						</fieldset>
					<?php endforeach; ?>
				</div>

				<div style="display: grid; grid-template-columns: repeat(auto-fit, 300px); gap: 20px;">
					<?php foreach(Pricelists::getList() as $pricelist):
						$price = $variant->getPriceEntity( $pricelist );
						echo Admin_Managers::PriceFormatter()->showPriceInfo( $price );
					endforeach; ?>
				</div>
				
				
				<div style="padding: 10px;padding-left: 30px;">
					<?php
					$showPropertyEditForm( $product, '/'.$variant->getId(), $variants_update_form );
					?>
				</div>

			</div>
		</div>
		<?php endforeach; ?>
			
		<?=$variants_update_form->end()?>
		<?php endif; ?>
</div>


<?php if($new_variant): ?>
	<?=$add_dialog->start()?>
	
	<?=$add_form->start()?>
	
	<?=$add_form->field('ean')?>
	<?=$add_form->field('internal_name_of_variant')?>
	<?=$add_form->field('internal_code')?>
	
	<?=Admin_Managers::EntityEdit()->renderShopDataBlocks(
		form: $add_form,
		renderer: function( EShop $eshop, string $eshop_key ) use ($add_form) : void {
			?>
			<?=$add_form->field('/eshop_data/'.$eshop_key.'/variant_name')?>
		<?php }); ?>
	
	
	<?=$add_dialog->footer()?>
		<?=UI::button_save()?>
	<?=$add_form->end()?>
	<?=$add_dialog->end()?>
<?php endif; ?>
