<?php
namespace JetApplicationModule\Admin\Complaints;

use Jet\Form;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use Jet\MVC_View;
use JetApplication\Complaint;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Complaint $complaint
 */

$complaint = $this->getRaw('complaint');
if(!$complaint->isEditable()) {
	return;
}
echo '&nbsp;';

//TODO: add states aroud dispatching like orders do

echo UI::button(Tr::_('Dispatch new goods'))
	->setClass(UI_button::CLASS_SUCCESS)
	->setIcon('truck')
	->setOnClick("$('#dispatch_new_goods_dialog').modal('show');");

