<?php
namespace JetApplicationModule\Admin\Complaints;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Complaint;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Complaint $complaint
 */

$complaint = $this->getRaw('complaint');
if(!$complaint->isEditable()) {
	return;
}

$form = $this->getRaw('dispatch_new_goods_form');

$form->field('comment')->input()->addCustomCssStyle("height:400px");
$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 12
]);
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 12
]);

$form->renderer()->addJsAction('onsubmit', "DispatchNewGoods.send();return false;");

echo $form->start();

?>
	<div style="display: grid;grid-template-columns: 200px 1fr;align-items: center">
		<div><?=Tr::_('Dispatch product:')?></div>
		<div><?=Admin_Managers::Product()->renderSelectWidget(
				"$('#{$form->field('product_id')->getId()}').val(selected_item.id)",
				$complaint->getProductId()
			); ?></div>
	</div>
	
	<?php

foreach($form->getFields() as $field) {
	echo $field;
}
?>
<div class="modal-footer">
<?=UI::button_delete(Tr::_('Dispatch new goods'))->setType(UI_button::TYPE_SUBMIT)?>
</div>
<?php
echo $form->end();
