<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Customer\Login;

?>
<script>
	const CustomerLogin = {
		login: function() {
			JetAjaxForm.submit('customer_login_form', {
				onSuccess: function() {
					location.reload();
				}
			});
		},

		logout: function() {
			JetAjaxForm.submit('customer_logout_form', {
				onSuccess: function() {
					location.reload();
				}
			});
		}
	};
</script>
