<?php

use Jet\Tr;
use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use Jet\UI_icon;

/**
 * @var MVC_View $this
 * @var Form $form
 */
$form = $this->getRaw( 'form' );
?>
<div class="card login-dialog">
	<h5 class="card-header">
		<?= Tr::_( 'Please change your password' ) ?>
	</h5>
	<?= $form->start() ?>
	<div class="card-body">

		<div class="login-warning">
			<div>
				<?= UI::icon( 'circle-xmark' )->setSize( UI_icon::SIZE_EXTRA_LARGE ) ?>
			</div>
			<div>
				<?= Tr::_( '<b>Your password expired.</b><br/>Please change your password.' ); ?>
			</div>
		</div>

		<div>
			<?= $form->field( 'password' ) ?>
			<br>
			<?= $form->field( 'password_check' ) ?>
			<br>
		</div>

		<div class="login-dialog-buttons">
			<a href="?logout" class="btn btn-light"><?= Tr::_( 'Logout' ); ?></a>
			<input type="submit" value="<?= Tr::_( 'Change password' ); ?>" class="btn btn-primary"/>
		</div>

	</div>
	<?= $form->end() ?>
</div>
