<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

/** @noinspection PhpUndefinedClassInspection */
?>
<table style="width: 100%;border-bottom: 0.5mm solid #c9c9c9;" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td style="width: 20%;height: 10mm;">
			{IF%logo}
			<img src="%logo(70,70)%">
			{logo%IF}
		</td>
		<td style="width: 80%;height: 10mm;text-align: right;vertical-align: middle;">

			<table cellpadding="2mm">
				<tr>
					<td>
						<b style="font-size: 6mm">Correction Invoice %number%</b>
						<div style="font-size: 3mm">Corrected invoice number %corrected_invoice_number%</div>
					</td>
				</tr>
			</table>
			<table cellpadding="4mm">
				<tr>
					<td>
						<b style="font-size: 6mm">Invoice %number%</b>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<table style="width: 100%;font-size: 3mm" cellspacing="2mm" cellpadding="3mm">
	<tr>
		<td style="width: 50%;border: 0.2mm solid black;">
			<table cellspacing="2mm">
				<tr>
					<td><b style="font-size: 4mm;">Issuer</b></td>
				</tr>
				<tr>
					<td style="font-size: 3mm">
						<b style="font-size: 4mm">%issuer_company_name%</b><br>
						%issuer_address_street_no%<br>
						%issuer_address_zip% %issuer_address_town%
					</td>
				</tr>
				<tr>
					<td>
						<table>
							<tr>
								<td style="width: 20mm;font-size: 3mm">Company ID:</td>
								<td style="width: 80mm;font-size: 3mm">%issuer_company_id%</td>
							</tr>
							<tr>
								<td style="width: 20mm;font-size: 3mm">VAT ID:</td>
								<td style="width: 80mm;font-size: 3mm">%issuer_company_vat_id%</td>
							</tr>
							<tr>
								<td style="width: 20mm;font-size: 3mm">Phone:</td>
								<td style="width: 80mm;font-size: 3mm">%issuer_phone%</td>
							</tr>
							<tr>
								<td style="width: 20mm;font-size: 3mm">e-mail:</td>
								<td style="width: 80mm;font-size: 3mm">%issuer_email%</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td style="font-size: 3mm">
						%issuer_info%
					</td>
				</tr>
				<tr>
					<td>
						<table>
							<tr>
								<td style="width: 30mm;font-size: 3mm">Bank name:</td>
								<td style="width: 80mm;font-size: 3mm">%issuer_bank_name%</td>
							</tr>
							<tr>
								<td style="width: 30mm;font-size: 3mm">Account number:</td>
								<td style="width: 80mm;font-size: 3mm">%issuer_bank_account%</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
		<td style="width: 50%;border: 0.2mm solid black;">
			<table cellspacing="2mm">
				<tr>
					<td><b style="font-size: 4mm;">Customer</b></td>
				</tr>
				<tr>
					<td style="font-size: 3mm">
						<b style="font-size: 4mm">%custoner_company_name%</b><br>
						<b style="font-size: 4mm">%custoner_first_name% %custoner_surname%</b><br>
						%custoner_address_street_no%<br>
						%custoner_address_zip% %custoner_address_town%
					</td>
				</tr>
				<tr>
					<td>
						<table>
							<tr>
								<td style="width: 20mm;font-size: 3mm">Company ID:</td>
								<td style="width: 80mm;font-size: 3mm">%custoner_company_id%</td>
							</tr>
							<tr>
								<td style="width: 20mm;font-size: 3mm">VAT ID:</td>
								<td style="width: 80mm;font-size: 3mm">%custoner_company_vat_id%</td>
							</tr>
							<tr>
								<td style="width: 20mm;font-size: 3mm">Phone:</td>
								<td style="width: 80mm;font-size: 3mm">%custoner_phone%</td>
							</tr>
							<tr>
								<td style="width: 20mm;font-size: 3mm">e-mail:</td>
								<td style="width: 80mm;font-size: 3mm">%custoner_email%</td>
							</tr>
						</table>
					</td>
				</tr>

			</table>
		</td>
	</tr>
</table>



<table style="width: 100%;" cellspacing="2mm">
	<tr>
		<td style="border: 0.1mm solid black;font-size: 3mm">
			
			<table cellspacing="2mm">
				<tr>
					<td valign="top">
						<table>
							{IF%has_order}
							<tr>
								<td nowrap=""><b>Order:</b></td>
								<td nowrap="" style="padding: 3px">%order_number%</td>
							</tr>
							{has_order%IF}
							
								<tr class="text-danger">
									<td><b>Correction of:</b></td>
									<td>%corrected_invoice_number%</td>
								</tr>
								<tr>
									<td><b>Reason of correction:</b></td>
									<td>%correction_reason%</td>
								</tr>

							<tr>
								<td><b>Payment method:</b></td>
								<td nowrap="" style="padding: 3px">%payment_method%</td>
							</tr>
						</table>
					</td>
					<td valign="top">
						<table>
							<tr>
								<td nowrap=""><b>Invoice date:</b></td>
								<td nowrap="" style="padding: 3px">%date_of_issue%</td>
							</tr>
							<tr>
								<td nowrap=""><b>Date of taxable supply:</b></td>
								<td nowrap="" style="padding: 3px">%date_of_taxable_supply%</td>
							</tr>
							<tr>
								<td nowrap=""><b>Due date:</b></td>
								<td nowrap="" style="padding: 3px">%due_date%</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>


<b style="font-size: 4mm">Invoice items</b>
<br>

<table style="font-size: 2.5mm;border-bottom: 0.1mm solid black;" cellspacing="0mm" cellpadding="2mm">
	<thead>
	<tr>
		<th style="width: 58mm;font-weight: bolder;">Item</th>
		<th style="width: 17mm;font-weight: bolder;"></th>
		<th style="width: 21mm;font-weight: bolder;">Price per item without VAT</th>

		<th style="width: 21mm;font-weight: bolder;">
			{IF%has_VAT}VAT per item{has_VAT%IF}
		</th>

		<th style="width: 10mm;font-weight: bolder;">VAT rate</th>

		<th style="width: 21mm;font-weight: bolder;">
			{IF%has_VAT}Price per item with VAT{has_VAT%IF}
		</th>

		<th style="width: 21mm;font-weight: bolder;">Total amount without VAT</th>

		<th style="width: 21mm;font-weight: bolder;">
			{IF%has_VAT}Total amount with VAT{has_VAT%IF}
		</th>
	</tr>
	</thead>
</table>

[%items]
<table style="font-size: 2.5mm;border-bottom: 0.1mm solid #c9c9c9;" cellspacing="0mm" cellpadding="2mm">

	<tr style="border-bottom: 2px solid red">
		<td style="width: 58mm;">%title%</td>
		<td style="width: 17mm;">%number_of_units%</td>
		<td style="width: 21mm;">%price_per_unit_without_vat%</td>

		<td style="width: 21mm">
			{IF%has_VAT}
			%price_per_unit_vat%
			{has_VAT%IF}
		</td>
		<td style="width: 10mm">%vat_rate%%</td>

		<td style="width: 21mm">
			{IF%has_VAT}
			%price_per_unit_with_vat%
			{has_VAT%IF}
		</td>

		<td style="width: 21mm">%total_amount_without_vat%</td>

		<td style="width: 21mm">
			{IF%has_VAT}
			%total_amount_with_vat%
			{has_VAT%IF}
		</td>

	</tr>
</table>
[items%]


{IF%is_paid}
<div style="color: red;font-size: 5mm;font-weight: bolder;text-align: right;">Already paid - do not pay!</div>
{is_paid%IF}

<table cellpadding="6mm" border="0">
	<tr>
		<td style="width: 80mm">
			{IF%stamp}
			<img src="%stamp%">
			{stamp%IF}
		</td>

		<td>
			<table align="right" cellpadding="1mm" cellspacing="0mm" border="0" style="font-size: 3mm;">
				<tr>
					<td style="width: 60mm">Without VAT:</td>
					<td style="width: 40mm">%total_without_vat%</td>
				</tr>
				<tr>
					<td style="width: 60mm">VAT:</td>
					<td style="width: 40mm">%total_vat%</td>
				</tr>
				<tr>
					<td style="width: 60mm">Round:</td>
					<td style="width: 40mm">%total_round%</td>
				</tr>

				<tr>
					<td style="font-weight: bolder;font-size: 5mm">Total:</td>
					<td style="font-weight: bolder;font-size: 5mm">%total%</td>
				</tr>
				<tr>
					<td style="font-weight: bolder;font-size: 5mm">Total after correction:</td>
					<td style="font-weight: bolder;font-size: 5mm">%total_after_correction%</td>
				</tr>
			</table>

		</td>
	</tr>
</table>

{IF%has_VAT}
<b style="font-size: 2mm">VAT overview</b>
<br>

<table style="font-size: 2mm;border-bottom: 0.2mm solid black;" border="0" cellpadding="2mm">
	<tr>
		<th style="width: 15mm;font-weight: bolder;">VAT rate</th>
		<th style="width: 31mm;font-weight: bolder;">Tax base</th>
		<th style="width: 31mm;font-weight: bolder;">Tax</th>
	</tr>
</table>
[%vat_overview]
<table style="font-size: 2mm;border-bottom: 0.2mm solid #c9c9c9;" border="0" cellpadding="2mm">
	<tr>
		<td style="width: 15mm">%vat_rate%%</td>
		<td style="width: 31mm">%tax_base%</td>
		<td style="width: 31mm">%tax%</td>
	</tr>
</table>
[vat_overview%]

{has_VAT%IF}