<?php
namespace JetApplicationModule\Shop\CashDesk;


use Jet\MVC_View;
use JetApplication\Payment_Method_Option_ShopData;

/**
 * @var MVC_View $this
 * @var Payment_Method_Option_ShopData $payment_method_option
 */

$cash_desk = CashDesk::get();

$payment_method_option = $this->getRaw('payment_method_option');

?>

<div class="option" onclick="CashDesk.payment.selectOption('<?= $payment_method_option->getId() ?>')">

	<div>
		<input type="radio" name="payment_method_option" onclick="setTimeout(function(){CashDesk.payment.selectOption('<?= $payment_method_option->getId() ?>')}, 10);return false;" />
	</div>
	<div>
		<?php if($payment_method_option->getImageIcon1()):?>
		<img src="<?=$payment_method_option->getIcon1ThumbnailUrl(30, 30)?>" style="padding: 5px;">
		<?php endif; ?>
	</div>
	<div class="option-title">
		<b><?= $payment_method_option->getTitle() ?></b>
		
		<?php if($payment_method_option->getDescription()): ?>
			<div>
				<?= $payment_method_option->getDescription() ?>
			</div>
		<?php endif; ?>
	</div>
</div>
