<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Content\InfoBoxes;


use Jet\MVC_View;
use Jet\Form;
use JetApplication\Content_InfoBox;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Content_InfoBox $item
 */

$form = $this->getRaw('form');
$item = $this->getRaw('item');
