<?php
namespace JetShop;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');

$products = $listing->getVisibleProducts();
?>

<?=$this->render('product_listing/list/sorting');?>
<div class="products">
	<?php
	foreach ($products as $product):
		$this->setVar('product', $product);
		echo $this->render('product_listing/list/item');
	endforeach;
	?>
</div>
<?=$this->render('product_listing/list/pagination')?>