<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;

/**
 * @var MVC_View   $this
 */
?>
<div class="card bg-light">
	<div class="card-body" id="product_listing_filter_area">
		<?=$this->render('product_listing/filter')?>
	</div>
</div>

<div class="card bg-light">
	<div id="product_listing_selected_filter_area" class="card-body">
		<?=$this->render('product_listing/filter-selected')?>
	</div>
</div>

<div id="product_listing_list">
	<?=$this->render('product_listing/list')?>
</div>