<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use JetApplication\ProductListing;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');

$products = $listing->getVisibleProducts();
?>

<?=$this->render('product_listing/list/sorting');?>
<div class="products" style="display: grid;grid-template-columns: repeat(4, 1fr)">
	<?php
	foreach ($products as $product):
		$this->setVar('product', $product);
		echo $this->render('product_listing/list/item');
	endforeach;
	?>
</div>
<?=$this->render('product_listing/list/pagination')?>