<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\UI;
use JetApplication\EShopEntity_WithEShopData_EShopData;

/**
 * @var MVC_View $this
 * @var EShopEntity_WithEShopData_EShopData $eshop_data
 */

$eshop_data = $this->getRaw('eshop_data');

if($eshop_data->isActiveForShop()): ?>
	<div><?=$this->render('entity-activation/active')?></div>
	<div><?=UI::flag($eshop_data->getEshop()->getLocale())?> <?=$eshop_data->getEshop()->getName()?></div>
	<div><?=$this->render('entity-activation/btn-deactivate')?></div>
	<div></div>
<?php else: ?>
	<div><?=$this->render('entity-activation/not-active')?></div>
	<div><?=UI::flag($eshop_data->getEshop()->getLocale())?> <?=$eshop_data->getEshop()->getName()?></div>
	<div><?=$this->render('entity-activation/btn-activate')?></div>
	<div></div>
<?php endif;




