<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\Form_Renderer;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_badge;
use Jet\UI_button;
use JetApplication\MarketplaceIntegration_Module_Controller_ProductSettings;


/**
 * @var MVC_View   $this
 * @var MarketplaceIntegration_Module_Controller_ProductSettings $controller
 */

$controller = $this->getController();

$product = $controller->getProduct();
$marketplace = $controller->getMarketplace();
$editable = $controller->getEditable();
$selling = $controller->getSelling();
$category = $controller->getCategory();
$product_join = $controller->getProductJoin();

?>

<?=$controller->getTabs()?>

<?php if($category): ?>
	<div class="toolbar">
	<span><?=$selling?
			UI::badge(UI_badge::SUCCESS, Tr::_('Offered up in the marketplace'))
			:
			UI::badge(UI_badge::DANGER, Tr::_('Not offered in the marketplace'))
		?></span>
		&nbsp;&nbsp;&nbsp;
		<?php if($editable):
			if($selling):
				echo UI::button( Tr::_('Stop selling'))->setClass(UI_button::CLASS_DANGER)->setUrl(Http_Request::currentURI(['stop_selling'=>'1']));
			else:
				echo UI::button( Tr::_('Start selling'))->setClass(UI_button::CLASS_SUCCESS)->setUrl(Http_Request::currentURI(['start_selling'=>'1']));
			endif;
			?>
		<?php endif; ?>
	</div>

	<div class="card card-body">
		<div class="row">
			<div class="col-md-2" style="padding-top: 10px;"><?=Tr::_('Connected marketplace category:')?></div>
			<div class="col-md-5" style="padding: 10px;"><b><?=$category->getCategoryId()?></b> <?=$category->getName()?></div>
		</div>
		
		
		<?php if($product_join && $editable):
			$form = $product_join->getEditForm();
			
			$form->renderer()->setDefaultFieldWidth([
				Form_Renderer::LJ_SIZE_MEDIUM => 5
			]);
			$form->renderer()->setDefaultLabelWidth([
				Form_Renderer::LJ_SIZE_MEDIUM => 2
			]);
			
			echo $form->start();
			foreach($form->getFields() as $field):
				echo $field;
			endforeach;
			?>
			<div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-5">
					<?=UI::button_save()?>
				</div>
			</div>
		
			<?php
			echo $form->end();
			?>
		<?php endif; ?>
	</div>

	
<?php endif; ?>
