<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\ReturnsOfGoods;

use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Admin_Managers_EShopEntity_Listing;
use JetApplication\ReturnOfGoods;

/**
 * @var MVC_View $this
 * @var Admin_Managers_EShopEntity_Listing $listing
 * @var ReturnOfGoods $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');

echo Admin_Managers::Product()->showName( $item->getProductId() );
