<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\ReturnsOfGoods;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\ReturnOfGoods;

/**
 * @var MVC_View $this
 * @var ReturnOfGoods $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::ReturnOfGoods()->showReturnOfGoodsStatus( $item );
