<?php
namespace JetApplicationModule\Admin\ProductFilterManager;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Property;

/**
 * @var MVC_View   $this
 * @var Form $form
 * @var Property[] $properties
 */

$category = $this->getRaw('category');
$editable = $this->getBool('editable');
$form = $this->getRaw('form');
$properties = $this->getRaw('properties');

$form->renderer()
	->setDefaultLabelWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 2] )
	->setDefaultFieldWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 3] );

?>

<?=$form->start()?>

<div id="container">
<?php if($editable):?>
<div  id="toolbar" class="toolbar">
	<div style="padding: 2px;display: flex;align-items: center">
		<div style="padding-left: 20px;padding-right: 20px;"><b><?=Tr::_('Automatic product appending filter')?></b></div>
		<div>
			<?=UI::button_save( Tr::_('Save filter settings and append products') )?>
			
			<?=UI::button(Tr::_('Disable auto append mode'))
				->setUrl( Http_Request::currentURI(['action'=>'disable_auto_append_mode']) )
				->setClass(UI_button::CLASS_DANGER)
			?>
		</div>
	</div>
</div>
<?php endif; ?>

<div id="form-area">
<?php require 'form/basic.phtml'; ?>
<?php require 'form/properties.phtml'; ?>
<?php require 'form/brands.phtml'; ?>
</div>
</div>

<?=$form->end()?>

<?php require 'js.phtml'; ?>