<?php
namespace JetApplicationModule\Admin\WarehouseManagement\TransferBetweenWarehouses;

use Jet\MVC_View;
use JetApplication\Admin_Managers_Entity_Listing;
use JetApplication\WarehouseManagement_Warehouse;

/**
 * @var MVC_View $this
 * @var Transfer $item
 * @var Admin_Managers_Entity_Listing $listing
 */

$item = $this->getRaw('item');
$listing = $this->getRaw('listing');

$edit_uri = $listing->getEditUrl($item);
?>
<a href="<?=$edit_uri?>"><?=WarehouseManagement_Warehouse::getScope()[$item->getTargetWarehouseId()]?></a>


