<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Content\Article\Articles;

use Jet\UI;
use Jet\UI_button;
use JetApplication\Admin_Managers;
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var EShop $eshop
 */

$eshop = $this->getRaw('eshop');
$eshop_key = $eshop->getKey();
$category_ids = $this->getRaw('category_ids');
?>
<table class="table table-striped">
	<?php foreach($category_ids as $c_id):
		$c_id = (int) $c_id;
		?>
	<tr>
		<?php if(Main::getCurrentUserCanEdit()): ?>
		<td style="width: 20px;">
			<?=UI::button_delete(' ')->setSize(UI_button::SIZE_EXTRA_SMALL)->setOnClick("Catgories_{$eshop_key}.remove({$c_id});")?>
		</td>
		<?php endif; ?>
		
		<td><?=Admin_Managers::Category()->renderItemName( $c_id )?></td>
	</tr>
	<?php endforeach; ?>
</table>
