<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Content\Article\Articles;

use Jet\Tr;
use JetApplication\Application_Service_Admin;
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var EShop $eshop
 */
$form = $this->getRaw('form');
$eshop = $this->getRaw('eshop');
$eshop_key = $eshop->getKey();


?>
<?=$form->field('/eshop_data/'.$eshop_key.'/title');?>
<?=$form->field('/eshop_data/'.$eshop_key.'/seo_title');?>
<?=$form->field('/eshop_data/'.$eshop_key.'/perex');?>
<?=$form->field('/eshop_data/'.$eshop_key.'/text');?>

<div class="form-group row">
	<div class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?= Tr::_('Categories:')?></div>
	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
		<?= /** @noinspection PhpParamsInspection */
		Application_Service_Admin::Category()->renderSelectCategoriesWidget( $form->field('/eshop_data/'.$eshop_key.'/_category_ids') )?>
		<br><br><br><br><br><br>
		<br><br><br><br><br><br>
	</div>
</div>

