<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Content\Article\Articles;

use Jet\Http_Request;
use Jet\Tr;
use JetApplication\Application_Service_Admin;
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var EShop $eshop
 */
$form = $this->getRaw('form');
$eshop = $this->getRaw('eshop');
$eshop_key = $eshop->getKey();

$cf = $form->field('/eshop_data/'.$eshop_key.'/_category_ids');
$cf_id = $cf->getId();

$this->setVar('category_ids', $cf->getValue() ? explode(',', $cf->getValue()): [] );
?>
<?=$form->field('/eshop_data/'.$eshop_key.'/title');?>
<?=$form->field('/eshop_data/'.$eshop_key.'/seo_title');?>
<?=$form->field('/eshop_data/'.$eshop_key.'/perex');?>
<?=$form->field('/eshop_data/'.$eshop_key.'/text');?>
<?=$form->field('/eshop_data/'.$eshop_key.'/_category_ids');?>

<div class="form-group row">
	<div class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?= Tr::_('Categories:')?></div>
	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
		<?php if( Main::getCurrentUserCanEdit() ): ?>
		<?= Application_Service_Admin::Category()->renderSelectWidget("Catgories_{$eshop_key}.add(selected_item.id);", name: 'add_category_'.$eshop_key)?>
		<?php endif ?>
		
		<div id="categoeies_<?=$eshop_key?>">
			<?=$this->render('edit/main/categories')?>
		</div>
		<br><br><br><br><br><br>
		<br><br><br><br><br><br>
	</div>
</div>

<?php if( Main::getCurrentUserCanEdit() ): ?>
<script>
	const Catgories_<?=$eshop_key?> = {
		getCurrent: () => {
			let ids = document.getElementById('<?=$cf_id?>').value;
			if(!ids) {
				return [];
			}
			
			return ids.split(',');
		},
		actualize: ( ids ) => {
			ids = ids.join(',');
			document.getElementById('<?=$cf_id?>').value = ids;
			$('#categoeies_<?=$eshop_key?>').load( '<?=Http_Request::currentURI()?>&show_categories='+ids+'&eshop=<?=$eshop_key?>' );
		},
		add: (id) => {
			id = id+'';
			
			let current = Catgories_<?=$eshop_key?>.getCurrent();
			if(current.includes(id)) {
				return;
			}
			current.push(id);
			Catgories_<?=$eshop_key?>.actualize( current );
		},
		remove: (id) => {
			id = id+'';
			
			let current = Catgories_<?=$eshop_key?>.getCurrent();

			console.debug(current, current.includes(id));
			
			if(!current.includes(id)) {
				return;
			}

			
			current.splice(current.indexOf(id), 1);
			
			Catgories_<?=$eshop_key?>.actualize( current );
		}
	};
</script>
<?php endif ?>