<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\WarehouseManagement\LossOrDestruction;


use Jet\MVC_View;
use JetApplication\Application_Service_Admin;
use JetApplication\Application_Service_Admin_EShopEntity_Listing;
use JetApplication\WarehouseManagement_LossOrDestruction;

/**
 * @var MVC_View $this
 * @var WarehouseManagement_LossOrDestruction $item
 * @var Application_Service_Admin_EShopEntity_Listing $listing
 */

$item = $this->getRaw('item');
$listing = $this->getRaw('listing');

echo Application_Service_Admin::Product()->renderItemName( $item->getProductId() );