<?php
namespace JetApplicationModule\Admin\WarehouseManagement\LossOrDestruction;

use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\WarehouseManagement_LossOrDestruction;

/**
 * @var MVC_View $this
 * @var WarehouseManagement_LossOrDestruction $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::PriceFormatter()->formatWithCurrency_WithoutVAT( $item->getCurrency(), $item->getTotal() );


