<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\WarehouseManagement\LossOrDestruction;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\WarehouseManagement_LossOrDestruction;

/**
 * @var MVC_View $this
 * @var WarehouseManagement_LossOrDestruction $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::PriceFormatter()->formatWithCurrency_WithoutVAT( $item->getCurrency(), $item->getTotal() );


