<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\MagicTags;


use Jet\MVC_View;
use JetApplication\Marketing_ProductSticker;
use JetApplication\Pricelists;
use JetApplication\Product_EShopData;
use JetApplication\Application_Service_EShop;

/**
 * @var MVC_View   $this
 * @var Product_EShopData $product
 */
$product = $this->getRaw('product');

$stickers = Marketing_ProductSticker::getProductStickers( $product->getId() );
$pricelist = Pricelists::getCurrent();
$URL = $product->getURL();

?>

<div class="product_listing_item">
	<div class="product_listing_item_stickers">
		<?php foreach($stickers as $sticker): ?>
			
			<div class="product_listing_item_sticker" style="background-color: <?=$sticker->getColorBackground();?>;color: <?=$sticker->getColorText()?>;">
				<?php if($sticker->getImageProductListing()): ?>
					<div class="product_listing_item_sticker_image"><img src="<?=$sticker->getImageProductListingThumbnailUrl(20, 20)?>"></div>
				<?php endif; ?>
				<div class="product_listing_item_sticker_text"><?=$sticker->getText()?></div>
			</div>
		
		<?php endforeach; ?>
	</div>
	
	
	<div class="product_listing_item_images">
		<a href="<?=$URL?>" class="product_listing_item_main_image">
			<?php if($product->getImageURL(0)): ?>
				<img src="<?=$product->getImageThumbnailUrl( 0, 220, 220 )?>"/>
			<?php endif; ?>
		</a>
	</div>
	
	<div class="product_listing_item_title"><a href="<?= $URL ?>"><?= $product->getFullName() ?></a></div>
	
	
	<div class="product_listing_item_price">
		<div class="product_listing_item_price_standard">
			<?php if ($product->getPriceBeforeDiscount( $pricelist )): ?>
				<?= Application_Service_EShop::PriceFormatter()->formatWithCurrency( $product->getPriceBeforeDiscount( $pricelist ) ) ?>
			<?php endif; ?>
		</div>
		<div class="product_listing_item_price_final"><?= Application_Service_EShop::PriceFormatter()->formatWithCurrency( $product->getPrice( $pricelist ) ) ?></div>
	</div>
	
	<div class="product_listing_item_reviews">
		<?php
		echo Application_Service_EShop::ProductReviews()?->renderRank( $product );
		?>
	</div>

</div>

