<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\Catalog;


use Jet\MVC_View;

/**
 * @var MVC_View $this
 */

?>

<form method="GET" onsubmit="return false;">
	<?=$this->render('filter/basic');?>
	<?=$this->render('filter/price');?>
	<?=$this->render('filter/properties');?>
	<?=$this->render('filter/brands');?>
</form>

