<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\Catalog;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\ProductListing;

/**
 * @var MVC_View   $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');
?>

<?=UI::button(Tr::_('Price'))->setIcon('')->setOnClick("listing.UI.goToFilter('f_price')");?>

<?php foreach($listing->getProperties() as $property):
	if($property->getIsDefaultFilter()):
		echo UI::button( $property->getLabel() )->setIcon('')->setOnClick("listing.UI.goToFilter('f_property_{$property->getId()}')");
	endif;
endforeach; ?>

<?=UI::button(Tr::_('Brand'))->setIcon('')->setOnClick("listing.UI.goToFilter('f_brands')");?>

<?=UI::button(Tr::_('All filters'))->setIcon('sliders')->setOnClick("listing.UI.showFilter()");?>
