<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Catalog;


use Jet\MVC_View;
use JetApplication\ProductListing;
use JetApplication\EShop_Managers;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');

$products = $listing->getVisibleProducts();
?>

<?=$this->render('list/sorting');?>
<div class="product_listing_list_products">
	<?php
	foreach ($products as $product):
		$this->setVar('product', $product);
		echo $this->render('list/item');
	endforeach;
	?>
</div>
<?=$this->render('list/pagination')?>
<?=EShop_Managers::Analytics()?->viewProductsList(
	$listing,
	category_name: $this->getString('c_name'),
	category_id: $this->getInt('c_id')
)?>
