<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\Catalog;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\ProductListing;

/**
 * @var MVC_View   $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');
?>

<div id="product_listing_default_filter_area">
	<?=$this->render('filter-default')?>
</div>


<div id="product_listing_selected_filter_area">
	<?=$this->render('filter-selected')?>
</div>

<div id="product_listing_list">
	<?=$this->render('list')?>
</div>

<div id="product_listing_filter_area" style="display: none;">
		<div id="product_listing_filter_area_top_buttons">
			<?=UI::button(Tr::_('Close filter'))->setIcon('chevron-left')->setOnClick("listing.UI.hideFilter()");?>
			
			<?php if($listing->getFilter()->isActive()):?>
			<?=UI::button(Tr::_('Cancel filter'))->setIcon('circle-xmark')->setOnClick("listing.cancelFilter()")->setClass(UI_button::CLASS_LIGHT)?>
			<?php endif; ?>
		</div>
		
		<div id="product_listing_filter" onscroll="listing.UI.mainContainerScroll( this )">
			<?=$this->render('filter')?>
		</div>
		
		<div id="product_listing_filter_area_bottom_buttons">
			<?=UI::button(Tr::_('Show products (%cnt%)', ['cnt'=> count($listing->getFilteredMap()->getProductIds()) ]))->setOnClick("listing.UI.hideFilter()");?>
		</div>
</div>