<?php
namespace JetApplicationModule\Shop\Customer\CustomerSection;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\Form;
use JetApplication\Customer;

/**
 * @var MVC_View   $this
 * @var Form $form
 */

$customer = Customer::getCurrentCustomer();

$form = $this->getRaw('form');

echo $this->getRaw('tabs');

if($form):
	echo $form->start();
	?>
	<div style="display: grid;grid-template-columns: 200px 300px;gap: 10px;align-items: center;margin: 10px;">
	<?php
		echo $form->field('first_name');
		echo $form->field('surname');
		echo $form->field('email');
		echo $form->field('phone');
	?>
		<div></div>
		<div><?=UI::button_save()?></div>
	</div>
	<?php
	echo $form->end();
else:
	?>
	<div class="card card-body" style="margin: 20px;display: grid;grid-template-columns: 100px 1fr;">
		<div></div>
		<?=$customer->getName()?><br>
		<div><?=Tr::_('e-mail:')?></div>
		<?=$customer->getEmail()?><br>
		<div><?=Tr::_('Phone:')?></div>
		<?=$customer->getPhoneNumber()?>
		<div></div>
		<div>
			<a href="<?=Http_Request::currentURL(['edit'=>'basic-info'])?>"><?=UI::icon('edit')?> <?=Tr::_('Edit')?></a>
		</div>
	</div>
	<?php
endif;
?>
