<?php
namespace JetApplicationModule\Shop\Customer\CustomerSection;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Customer;

/**
 * @var MVC_View   $this
 */

$customer = Customer::getCurrentCustomer();
?>

<?=$this->getRaw('tabs')?>

<div class="card card-body" style="margin: 20px;">
<?php if($customer->getMailingSubscribed()): ?>
	<div><?=Tr::_('You are subscribed to our newsletter')?></div>
	
	<div style="margin: 20px;">
		<?=UI::button(Tr::_('Unsubscribe'))
			->setUrl(Http_Request::currentURL(set_GET_params: ['unsubscribe'=>1]))
			->setClass(UI_button::CLASS_DANGER)
		?>
	</div>
<?php else: ?>
	<div><?=Tr::_('Unfortunately you are not subscribed to our newsletter')?></div>
	
	
	<div style="margin: 20px;">
		<?=UI::button(Tr::_('Subscribe'))
			->setUrl(Http_Request::currentURL(set_GET_params: ['subscribe'=>1]))
			->setClass(UI_button::CLASS_SUCCESS)
		?>
	</div>
<?php endif; ?>
</div>