<?php
namespace JetApplicationModule\Shop\Customer\CustomerSection;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Order;
use JetApplication\Shop_Managers;

/**
 * @var MVC_View   $this
 * @var Order $order
 */

$order = $this->getRaw('order');

$billing_address = $order->getBillingAddress();
$delivery_address = $order->getBillingAddress();
?>

<?=$this->getRaw('tabs')?>

<div style="padding: 20px">
	<?=UI::button( Tr::_('Orders'))->setUrl( Http_Request::currentURL(unset_GET_params: ['order']) )->setIcon('chevron-left');?>
	

	<div style="display: grid;grid-template-columns: 1fr 1fr;gap: 20px;margin: 20px;">
		<div class="card card-body">
			<h5 class="card-title"><?=Tr::_('Billing address')?></h5>
			
			<?php if( $billing_address->getCompanyName() ): ?>
				<?=$billing_address->getCompanyName()?><br>
				<?=$billing_address->getCompanyId()?><br>
				<?=$billing_address->getCompanyVatId()?><br>
			<?php endif?>
			
			<?=$billing_address->getFirstName()?> <?=$billing_address->getSurname()?><br>
			<?=$billing_address->getAddressStreetNo()?><br/>
			<?=$billing_address->getAddressZip()?> <?=$billing_address->getAddressTown()?>
		</div>
		
		<div class="card card-body">
			<h5 class="card-title"><?=Tr::_('Delivery address')?></h5>
			
			<?php if( $delivery_address->getCompanyName() ): ?>
				<?=$delivery_address->getCompanyName()?><br>
				<?=$delivery_address->getCompanyId()?><br>
				<?=$delivery_address->getCompanyVatId()?><br>
			<?php endif?>
			
			<?=$delivery_address->getFirstName()?> <?=$delivery_address->getSurname()?><br>
			<?=$delivery_address->getAddressStreetNo()?><br/>
			<?=$delivery_address->getAddressZip()?> <?=$delivery_address->getAddressTown()?>
		</div>
		
	</div>
	
	<div class="card card-body" style="margin: 20px;">
		<h5 class="card-title"><?=Tr::_('Items')?></h5>
		
		<table>
			<?php foreach($order->getItems() as $item): ?>
				<tr>
					<td style="width: 30px">
						<?php
						if($item->getNumberOfUnits()!=1):
							echo $item->getNumberOfUnits().' '.$item->getMeasureUnit()?->getName();
						endif;
						?>
					</td>
					<td style="width: 500px"><?=$item->getTitle()?></td>
					<td style="width: 150px"><?=Shop_Managers::PriceFormatter()->formatWithCurrency($item->getTotalAmount())?></td>
				</tr>
			<?php endforeach; ?>
			<tr>
				<td></td>
				<td></td>
				<td><b><?=Shop_Managers::PriceFormatter()->formatWithCurrency($order->getTotalAmount())?></b></td>
			</tr>
		</table>
	</div>
</div>
