<?php
namespace JetApplicationModule\Shop\Customer\CustomerSection;

use Jet\Http_Request;
use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Order;
use JetApplication\Shop_Managers;

/**
 * @var MVC_View   $this
 * @var Order[] $orders
 */

$orders = $this->getRaw('orders');

?>

<?=$this->getRaw('tabs')?>



<?php foreach($orders as $order): ?>
<div class="card" style="display: grid;grid-template-columns: 0.7fr 1fr 0.5fr;margin: 20px;border: 1px solid rgba(0, 0, 0, .125);border-radius: 5px;padding: 20px;">
	
	<div></div>
	<div><b><?=Tr::_('Items')?></b></div>
	<div></div>
	
	
	<div>
		<div style="display: grid;grid-template-columns: 0.8fr 2fr;gap: 10px;align-items: center">
			<div><b><?=Tr::_('Number')?></b></div>
			<div><a href="<?=Http_Request::currentURL(set_GET_params: ['order'=>$order->getNumber()])?>"><?=$order->getNumber()?></a></div>

			<div><b><?=Tr::_('Purchased')?></b></div>
			<div><?=Locale::dateAndTime( $order->getDatePurchased() )?></div>

			<div><b><?=Tr::_('Status')?></b></div>
			<div><?=$order->getStatus()?->getTitle()?></div>
			
		</div>
	</div>

	<div style="display: grid;grid-template-columns: 0.2fr 1fr 0.3fr">
		<?php foreach($order->getItems() as $item): ?>

		<div><?=$item->getNumberOfUnits().' '.$item->getMeasureUnit()?->getName();?></div>
		<div><?=$item->getTitle()?></div>
		<div><?=Shop_Managers::PriceFormatter()->formatWithCurrency($item->getTotalAmount())?></div>

		<?php endforeach; ?>
	</div>
	
	
	<div style="font-weight: bolder;font-size: 1.5rem">
		<?=Shop_Managers::PriceFormatter()->formatWithCurrency( $order->getTotalAmount() )?>
	</div>
</div>
<?php endforeach; ?>
