<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Catalog;


use Jet\MVC_View;
use JetApplication\Product_EShopData;
use JetApplication\Application_Service_EShop;

/**
 * @var MVC_View $this
 * @var Product_EShopData $product
 */

$product = $this->getRaw('product');
?>
<div class="buy-btn">
	<?=Application_Service_EShop::ShoppingCart()->renderBuyButton_detail( $product );?>
</div>

