<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Catalog;


use Jet\IO_File;
use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Files;
use JetApplication\Product_KindOfFile_EShopData;
use JetApplication\Product_EShopData;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 * @var Product_EShopData $product
 */

$product = $this->getRaw('product');

if($product->isVariant()) {
	$product = $product->getVariantMasterProduct();
}

$files = $product->getFiles();

if(!$files) {
	return;
}

$kind_of_file_ids = [];
foreach($files as $file) {
	$k_id = $file->getKindOfFileId();
	if(!in_array($k_id, $kind_of_file_ids)) {
		$kind_of_file_ids[] = $k_id;
	}
}


$kind_of_files = Product_KindOfFile_EShopData::getActiveList(
	$kind_of_file_ids,
	EShops::getCurrent()
);

$manager = Files::Manager();

foreach($files as $i=>$file):
	$kind = $kind_of_files[$file->getKindOfFileId()]??null;
	if(!$kind) {
		unset($files[$i]);
		continue;
	}
	$path = $manager->getFilePath( $product::getEntityType(), $product->getId(), $file->getFile() );
	
	if(!IO_File::exists( $path )) {
		unset($files[$i]);
		continue;
	}
endforeach;

if(!$files) {
	return;
}
?>
<div class="files">
	<h5><?=Tr::_('Download files:')?></h5>
	<div class="list">
		<?php foreach($files as $file):
			$kind = $kind_of_files[$file->getKindOfFileId()]??null;
			?>
			<div>
				<?php if($kind->getImageMain()): ?>
				<img src="<?=$kind->getImageMainThumbnailURL(20,20)?>">
				<?php endif; ?>
				<?=$kind->getName()?>:
			</div>
			<div>
				<a href="<?=$file->getURL()?>"><?=$file->getFile()?></a><br>
				<?=Locale::size( $file->getSize() )?>
			</div>
	
		<?php endforeach; ?>
	</div>
</div>