<?php
namespace JetApplicationModule\EShop\Catalog;

use Jet\Locale;
use Jet\MVC_View;
use JetApplication\Pricelists;
use JetApplication\Product_EShopData;
use JetApplication\EShop_Managers;

/**
 * @var MVC_View $this
 * @var Product_EShopData $product
 */

$product = $this->getRaw('product');
$pricelist = Pricelists::getCurrent();

$units = $product->getMeasureUnit()?->getName();
if($units) {
	$units = ' / '.$units;
}
?>

<div class="price">
	<?php if($product->getDiscountPercentage($pricelist)):?>
		<div class="before-discount"><?= EShop_Managers::PriceFormatter()->formatWithCurrency( $product->getPriceBeforeDiscount( $pricelist ) ) ?></div>
	<?php endif; ?>
	
	<div class="price">
		<?= EShop_Managers::PriceFormatter()->formatWithCurrency( $product->getPrice( $pricelist ) ) ?> <?=$units?>
	</div>
	
	<?php if($product->getDiscountPercentage($pricelist)):?>
		<div class="discount-prc">-<?=Locale::int(floor($product->getDiscountPercentage($pricelist)))?>%</div>
	<?php endif; ?>
</div>
<?=EShop_Managers::PromoAreas()?->renderArea('product-info', [$product->getId()])?>

