<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Catalog;


use Jet\Locale;
use Jet\MVC_View;
use JetApplication\Pricelists;
use JetApplication\Product_EShopData;
use JetApplication\Application_Service_EShop;

/**
 * @var MVC_View $this
 * @var Product_EShopData $product
 */

$product = $this->getRaw('product');
$pricelist = Pricelists::getCurrent();

$units = $product->getMeasureUnit()?->getName();
if($units) {
	$units = ' / '.$units;
}
?>

<div class="price">
	<?php if($product->getDiscountPercentage($pricelist)):?>
		<div class="before-discount"><?= Application_Service_EShop::PriceFormatter()->formatWithCurrency( $product->getPriceBeforeDiscount( $pricelist ) ) ?></div>
	<?php endif; ?>
	
	<div class="price">
		<?= Application_Service_EShop::PriceFormatter()->formatWithCurrency( $product->getPrice( $pricelist ) ) ?> <?=$units?>
	</div>
	
	<?php if($product->getDiscountPercentage($pricelist)):?>
		<div class="discount-prc">-<?=Locale::int(floor($product->getDiscountPercentage($pricelist)))?>%</div>
	<?php endif; ?>
</div>
<?=Application_Service_EShop::PromoAreas()?->renderArea('product-info', [$product->getId()])?>

