<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\Catalog;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Product_EShopData;

/**
 * @var MVC_View $this
 * @var Product_EShopData $product
 */

$product = $this->getRaw('product');

$similar = $product->getSimilarProducts();

if(!$similar) {
	return;
}

$kind = $product->getKind();


$title = $kind?->getSimilarProductSelectDescription();
if(!$title) {
	$title = Tr::_('Similar products');
}
?>
<h3 class="variants-title"><?=$title?></h3>

<div class="variants">
	<?php foreach($similar as $s):
		if($s->getId()==$product->getId()):
			?>
			<div class="variant-selected">
				<img src="<?= $s->getImageThumbnailUrl( 0, 150, 150 ) ?>"/>
				<b><?=$s->getFullName()?></b>
			</div>
		<?php
		else:
			?>
			<div class="variant">
				<a href="<?=$s->getURL()?>" title="<?= $s->getVariantName() ?>">
					<img src="<?= $s->getImageThumbnailUrl( 0, 150, 150 ) ?>"/>
				</a>
				<a href="<?=$s->getURL()?>"><?=$s->getFullName()?></a>
			</div>
		<?php
		endif;
	endforeach; ?>
</div>
