<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use JetApplication\EShopEntity_Basic;
use JetApplication\EShopEntity_Admin_Interface;

use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var EShopEntity_Basic|EShopEntity_Admin_Interface     $item
 */

$form = $this->getRaw('form');
$item = $this->getRaw('item');