<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Marketing\PaymentFeeDiscount;


use Jet\MVC_View;
use JetApplication\Payment_Method;
use JetApplication\Marketing_PaymentFeeDiscount;


/**
 * @var MVC_View $this
 * @var Marketing_PaymentFeeDiscount $item
 */

$item = $this->getRaw('item');
echo Payment_Method::getScope()[$item->getPaymentMethodId()]??$item->getPaymentMethodId();
