<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ProformaInvoices;


use Jet\MVC_View;
use JetApplication\Application_Service_Admin;
use JetApplication\ProformaInvoice;

/**
 * @var MVC_View $this
 * @var ProformaInvoice $item
 */

$item = $this->getRaw('item');

echo Application_Service_Admin::PriceFormatter()->formatWithCurrencyByHasVAT($item->hasVAT(), $item->getCurrency(), $item->getTotal() );
