<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Content\MagicTags;


use Jet\Form;
use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Application_Service_Admin;
use JetApplication\Content_MagicTag;

/**
 * @var MVC_View   $this
 * @var Content_MagicTag[]  $list
 * @var Form[] $forms
 */

$list = $this->getRaw('list');
$forms = $this->getRaw('forms');
$generated = '';
?>
<style>
	.magic_tag_link.selected a {
		font-weight: bolder;
		color: black;
	}
</style>
<script>
	const MagicTag = {
		select: (id) => {
			$('.magic_tag_form').hide();
			$('#magic_tag_'+id).show();
			$('#generated').val( '' );
			$('.magic_tag_link').removeClass('selected');
			$('#magic_tag_list_'+id).addClass('selected');
		},
		generate: ( form_id ) => {
			JetAjaxForm.submit( form_id, {
				showProgressIndicator: () => {},
				hideProgressIndicator: () => {},
				onProgress: () => {},
				onSuccess: (form, data) => {
					$('#generated').val( data['generated'] );
				}
			} );
		},
		copy: () => {
			const element = document.getElementById('generated');

			element.select();
			element.setSelectionRange(0, 99999);

			document['execCommand']("copy");
			
		}
	}
</script>
<div style="display: grid;grid-template-columns: 1fr 3fr;gap: 10px;margin: 10px;">
	<div style="padding-top: 10px;padding-bottom: 10px;">
		<table class="table table-striped">
			<?php foreach($list as $mt): ?>
			<tr>
				<td class="magic_tag_link" id="magic_tag_list_<?=$mt->getId()?>">
					<a href="" onclick="MagicTag.select('<?=$mt->getId()?>');return false;"><?=$mt->getTitle()?></a>
					<br>
					<?=$mt->getDescription()?>
				</td>
			</tr>
			<?php endforeach; ?>
		</table>
	</div>
	<div style="padding: 10px;">
		<?php foreach($list as $mt):
			$form = $forms[$mt->getId()];
			$form->renderer()->setDefaultLabelWidth([
				Form_Renderer::LJ_SIZE_MEDIUM => 12
			]);
			$form->renderer()->setDefaultFieldWidth([
				Form_Renderer::LJ_SIZE_MEDIUM => 12
			]);
			$form->renderer()->addJsAction('onsubmit', "MagicTag.generate(this.id);;return false;");
			?>
			<div id="magic_tag_<?=$mt->getId()?>" style="display: none;" class="magic_tag_form">
				<h4><?=$mt->getTitle()?></h4>
				<p><?=$mt->getDescription()?></p>
			<?=$form->start()?>
				<?php foreach($form->getFields() as $field):
					echo $field;
				
					if(str_starts_with($field->getName(), 'product_id:')):
						?>
						<div class="row" style="align-items: center">
							<div class="col-md-12"><?=$field->getLabel()?></div>
							<div class="col-md-12" style="padding: 15px">
								<?=Application_Service_Admin::Product()->renderSelectWidget(
									on_select: "document.getElementById('{$field->getId()}').value=selected_item.id",
									name: $mt->getId()."_select_product"
								)?>
							</div>
						</div>
						<?php
					endif;
					
					
					if(str_starts_with($field->getName(), 'category_id:')):
						?>
						<div class="row" style="align-items: center">
							<div class="col-md-12"><?=$field->getLabel()?></div>
							<div class="col-md-12" style="padding: 15px">
								<?=Application_Service_Admin::Category()->renderSelectWidget(
									on_select: "document.getElementById('{$field->getId()}').value=selected_item.id",
									name: $mt->getId()."_select_category"
								)?>
							</div>
						</div>
						<?php
					endif;
					
					
				endforeach; ?>

			<div style="text-align: right">
				<?=UI::button(Tr::_('Generate'))->setClass(UI_button::CLASS_PRIMARY)->setIcon('play')->setType(UI_button::TYPE_SUBMIT)?>
			</div>
			<?=$form->end()?>
			</div>
		
		
		<?php endforeach; ?>

		<div class="card card-body" style="margin-top: 20px;">
			<textarea style="border: none;background-color: transparent;" id="generated" onclick="MagicTag.copy();"></textarea>
		</div>
	</div>
</div>
