<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Content\MagicTags;


use Jet\Form;
use Jet\Form_Renderer;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Admin_Managers;
use JetApplication\Content_MagicTag;

/**
 * @var MVC_View   $this
 * @var Content_MagicTag[]  $list
 * @var Form $form
 */

$list = $this->getRaw('list');
$selected_tag_id = $this->getString('selected_tag_id');
$form = $this->getRaw('form');
$generated = $this->getRaw('generated');
?>
<div id="main-col" style="display: grid;grid-template-columns: 1fr 3fr;gap: 10px">
	<div>
		<table class="table table-striped">
			<?php foreach($list as $mt): ?>
			<tr>
				<td>
					<?php if($mt->getId()==$selected_tag_id): ?>
						<b><?=$mt->getTitle()?></b>
					<?php else: ?>
						<a href="<?=Http_Request::currentURI(['tag'=>$mt->getId()])?>"><?=$mt->getTitle()?></a>
					<?php endif; ?>
					<br>
					<?=$mt->getDescription()?>
				</td>
			</tr>
			<?php endforeach; ?>
		</table>
	</div>
	<div>
		<?php if($form):
			$form->renderer()->setDefaultLabelWidth([
				Form_Renderer::LJ_SIZE_MEDIUM => 2
			]);
			$form->renderer()->setDefaultFieldWidth([
				Form_Renderer::LJ_SIZE_MEDIUM => 5
			]);
			?>
			<?=$form->start()?>
				<?php foreach($form->getFields() as $field):
					echo $field;
				
					if(str_starts_with($field->getName(), 'product_id:')):
						?>
						<div class="row" style="align-items: center">
							<div class="col-md-2"><?=$field->getLabel()?></div>
							<div class="col-md-5" style="padding: 15px"><?=Admin_Managers::Product()->renderSelectWidget("document.getElementById('{$field->getId()}').value=selected_item.id")?></div>
						</div>
						<?php
					endif;
					
					
					if(str_starts_with($field->getName(), 'category_id:')):
						?>
						<div class="row" style="align-items: center">
							<div class="col-md-2"><?=$field->getLabel()?></div>
							<div class="col-md-5" style="padding: 15px"><?=Admin_Managers::Category()->renderSelectWidget("document.getElementById('{$field->getId()}').value=selected_item.id")?></div>
						</div>
						<?php
					endif;
					
					
				endforeach; ?>

			<div class="row" style="align-items: center">
				<div class="col-md-2"></div>
				<div class="col-md-5" style="padding: 15px">
					<?=UI::button(Tr::_('Generate'))->setClass(UI_button::CLASS_PRIMARY)->setIcon('play')->setType(UI_button::TYPE_SUBMIT)?>
					
				</div>
			</div>
			<?=$form->end()?>
		
			<?php if($generated): ?>
			<div class="card card-body"><textarea style="border: none;background-color: transparent;"><?=$generated?></textarea></div>
			<?php endif ?>
		
		<?php endif;?>
	</div>
</div>
