<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Marketing\LandingPages;


use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\Form;
use JetApplication\Application_Service_Admin;
use JetApplication\Marketing_LandingPage;

/**
 * @var MVC_View   $this
 * @var Marketing_LandingPage $item
 * @var Form $form
 */

$item = $this->getRaw('item');
$editable = $item->isEditable();

$form = $this->getRaw('form');
$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 8 ] );

echo $this->controller->getEditorManager()->renderToolbar(
	$this->getRaw('form'),
	function() use ($item) {
		require 'toolbar.phtml';
	}
);

echo Application_Service_Admin::EntityEdit()->renderEditorTools( $item );
?>
<div id="main-col">
	<?=$this->getRaw('tabs')?>
	<br>
	<?=$form->start()?>
	<?=$form->field('landing_page_title')?>
	<?=$form->field('landing_page_description')?>
	<?=$form->field('landing_page_url')?>
	<?=$form->field('landing_page_html')?>
	
	<?=$form->end()?>
</div>