<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\UI;
use Jet\Form;
use Jet\Tr;
use Jet\Mvc_View;
use JetShop\Category;
use JetShop\Parametrization_Property;
use JetShop\Parametrization_Property_Option;
use JetShop\Shops;
use JetShopAdmin\Shop_Admin;
use JetShop\Parametrization_Group;

/**
 * @var Mvc_View   $this
 * @var Parametrization_Property_Option $new_option
 * @var Form $form
 */
$new_option = $this->getRaw('new_option');

$form = $new_option->getAddForm();
$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 2
]);

echo $this->render('lj_start');
echo '</br>';

echo $form->start();


echo $form->field('is_active');


foreach(Shops::getList() as $shop):
	$shop_id= $shop->getId();

	$shop_data = $new_option->getShopData( $shop_id );

	$form->field('/shop_data/'.$shop_id.'/filter_label')->input()->addJsAction('onchange', "urlPathPart.afterNameChanged(this.value, '".$form->field('/shop_data/'.$shop_id.'/url_param')->getId()."', '".$shop_id."');");
	$form->field('/shop_data/'.$shop_id.'/filter_label')->input()->addJsAction('onchange', "$('#".$form->field('/shop_data/'.$shop_id.'/product_detail_label')->getId()."').val(this.value);");
	$form->field('/shop_data/'.$shop_id.'/url_param')->input()->addJsAction('onchange', "urlPathPart.afterPathPartChanged(this, '".$shop_id."')");
	?>
	<?=$shop_data->renderShopDataBlock_start()?>
		<fieldset>
			<legend class="sub"><?=Tr::_('Main data')?></legend>

			<?=$form->field('/shop_data/'.$shop_id.'/is_active')?>
			<?=$form->field('/shop_data/'.$shop_id.'/filter_label')?>
			<?=$form->field('/shop_data/'.$shop_id.'/product_detail_label')?>
			<?=$form->field('/shop_data/'.$shop_id.'/url_param')?>
			<?=$form->field('/shop_data/'.$shop_id.'/description')?>
		</fieldset>

		<fieldset>
			<legend class="sub"><?=Tr::_('SEO')?></legend>
			<?=$form->field('/shop_data/'.$shop_id.'/seo_h1')?>
			<?=$form->field('/shop_data/'.$shop_id.'/seo_title')?>
			<?=$form->field('/shop_data/'.$shop_id.'/seo_description')?>
			<?=$form->field('/shop_data/'.$shop_id.'/alternative_category_description')?>
			<?=$form->field('/shop_data/'.$shop_id.'/alternative_category_description_strategy')?>
			<?=$form->field('/shop_data/'.$shop_id.'/internal_fulltext_keywords')?>
		</fieldset>


	<?=$shop_data->renderShopDataBlock_end()?>
<?php endforeach;



echo $form->end();

echo $this->render('lj_end');