<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\OAuth\Manager;


use Jet\MVC;
use Jet\MVC_View;
use JetApplication\EShop_OAuth_BackendModule;

/**
 * @var MVC_View   $this
 * @var EShop_OAuth_BackendModule $module
 */
$module = $this->getRaw('module');
?>

<form method="post" action="<?=$module->getHandlerUrl()?>">
	<input type="hidden" name="login" value=""/>
	<input type="hidden" name="redirect_page_id" value="<?=MVC::getPage()->getId()?>"/>
	<input type="hidden" name="path_fragments" value="<?=MVC::getRouter()->getUsedUrlPath()?>"/>
	
	<?=$module->_renderLoginButton()?>
	
</form>
