<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Signposts;


use Jet\Http_Request;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Signpost;

echo '&nbsp;';
echo UI::button('Sort signposts')
	->setClass(UI_button::CLASS_INFO)
	->setOnClick("sortSignposts.openDialog();");

$dialog = UI::dialog('sort_signposts', Tr::_('Sort signposts'));

$sing_posts = Signpost::fetchInstances();
$sing_posts->getQuery()->setOrderBy('priority');

echo $dialog->start();

?>
	<div style="overflow: auto;">
		<div id="signpost-sort">
			<?php foreach($sing_posts as $sp):
				?>
				<div class="sortable-item card card-body" data-id="<?=$sp->getId()?>" style="margin: 10px;padding: 5px;">
					<div style="display: flex;align-items: center;gap: 20px;">
						<?=UI::icon('arrows-v')?>
						<a href="<?=$sp->getEditUrl()?>"><?=$sp->getAdminTitle()?></a>
					</div>
				</div>
			<?php endforeach; ?>
		</div>
	</div>
<?=$dialog->footer(); ?>
<?=UI::button_save()->setOnClick("sortSignposts.setSort()")?>
<?=$dialog->end(); ?>

<script>
	const sortSignposts = {
		openDialog: function () {
			$('#sort_signposts').modal('show');


			$('#signpost-sort')['sortable']({
				stop: function () {
				}

			});

		},

		setSort: function () {
			const values = [];

			$('#signpost-sort').find('.sortable-item').each(function (i, item) {
				values.push($(item).data('id'));
			});
			
			location.href = '<?=Http_Request::currentURI(['sort_signposts'=>''])?>'+values.join(',');

		}
	};
</script>

