<?php
namespace JetApplicationModule\Shop\FulltextSearch;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Category_ShopData;
use JetApplication\Shop_Managers_ProductListing;

/**
 * @var MVC_View   $this
 * @var Shop_Managers_ProductListing $products
 * @var Category_ShopData[] $categories
 */

$products = $this->getRaw('products');
$categories = $this->getRaw('categories');

?>

<br>
<div class="card">
	<form method="get">
	<div class="card-body">

		<div style="display: flex;align-items: center;max-width: 900px;">
			<div style="text-align: right;padding-right: 10px;">
				<b><?=Tr::_('Search:')?></b>
			</div>
			<input type="search" name="q" class="form-control"
			       value="<?=$this->getString('q')?>"
			       style="border-top-right-radius: 0;border-bottom-right-radius: 0;"
			>
			<button type="submit" class="btn btn-light" style="border-top-left-radius: 0;border-bottom-left-radius: 0;padding: 3px;">
				<div style="display: flex;align-items: center;padding: 3px;">
					<?=UI::icon('search')?>
				</div>

			</button>
		</div>
	</div>
	</form>
</div>

<br><br>

<?php if( $categories ): ?>
	<h2><?=Tr::_('Categories')?></h2>
	<div class="categories">
	<?php foreach($categories as $item): ?>
		<div class="category">
			<div class="category-image">
				<?php if($item->getImageMain()): ?>
					<a href="<?=$item->getUrl()?>" ><img src="<?=$item->getImageMainThumbnailUrl(150, 150)?>"></a>
				<?php endif; ?>
			</div>
			<div class="category-name">
				<a href="<?=$item->getUrl()?>"><?=$item->getName()?></a>
			</div>
		</div>
	<?php endforeach; ?>
	</div>
<?php endif; ?>

<?php if($products): ?>
	<h2><?=Tr::_('Products')?></h2>

	<?=$products->render()?>
<?php endif; ?>
