<?php
use Jet\MVC;
use Jet\UI;
use JetApplication\Shop_Pages;

$page = Shop_Pages::Search();

if(MVC::getPage()->getId()==$page->getId()) {
	return;
}
?>
<script>
	const search = {
		timer: null,
		
		whisper: async ( value )=> {

			if(value.length<=3) {
				visibility.hide( 'search_whisperer' );

				return;
			}
			
			if(search.timer) {
				clearTimeout(search.timer);
				search.timer = null;
			}
			
			visibility.show( 'search_whisperer' );

			const r = await fetch('<?=Shop_Pages::SearchWhisperer()->getURL()?>?q='+encodeURIComponent( value ));
			const response = await r.text();
			
			document.getElementById('search_whisperer').innerHTML = response;
		},
		hide: ()=> {
			search.timer = setTimeout(function () {
				visibility.hide( 'search_whisperer' );
				document.getElementById('search_whisperer').innerHTML = '';
			}, 1500);
		},

		resultFocus: ()=>{
			if(search.timer) {
				clearTimeout(search.timer);
				search.timer = null;
			}
		}
		
		
	};
</script>

<div style="display: grid;grid-template-columns: 1fr 500px 1fr">
	<div>
	
	</div>
	<form method="get" action="<?= $page->getURL()?>">
		

		<div style="display: flex;align-items: center;">
			<input type="search" name="q" value="" class="form-control"
			       onkeyup="search.whisper( this.value );"
			       onblur="search.hide()"
			       autocomplete="off"
			       style="border-top-right-radius: 0;border-bottom-right-radius: 0;"
			>
			<button type="submit" class="btn btn-light" style="border-top-left-radius: 0;border-bottom-left-radius: 0;padding: 3px;">
				<div style="display: flex;align-items: center;padding: 3px;">
					<?=UI::icon('search')?>
				</div>
				
			</button>
		</div>

		<div
			class="card card-body"
			style="position: absolute;display: none;left: 10%;width: 80%;margin-top: 10px;z-index: 99999;text-align: left"
			id="search_whisperer"
			onmouseover="search.resultFocus()"
			onclick="search.resultFocus()"
			onmouseout="search.hide()"
		></div>
	
	</form>
	<div></div>
</div>
