<?php
namespace JetShopModule\Admin\Orders;

use JetShop\Order as Order;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View   $this
 * @var Order       $order
 */
$order = $this->getRaw( 'order' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( 'Do you really want to delete this order?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $order->getId() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$order->getId();?> (<?=$order->getId();?>)</a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>