<?php
namespace JetApplicationModule\Admin\Orders;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Admin_Managers;
use JetApplication\Order;

/**
 * @var MVC_View $this
 * @var Order     $order
 */

$order = $this->getRaw( 'order' );

require 'edit/js.phtml';
require 'edit/toolbar.phtml';

?>
<div id="main-col">
	<div id="o_main" class="o_anchor"></div>
	<div class="o_section">
		<?php require 'edit/main.phtml'; ?>
	</div>

	
	<div style="position: relative;"><div id="o_items" class="o_anchor"></div></div>
	<fieldset class="o_section">
		<legend><?=UI::icon('list')?> <?=Tr::_('Order items')?></legend>
		<?php require 'edit/items.phtml';?>
	</fieldset>

	<div id="o_dispatch" class="o_anchor"></div>
	<fieldset class="o_section">
		<legend><?=UI::icon('boxes-packing')?> <?=Tr::_('Order dispatch')?></legend>
		<?=Admin_Managers::OrderDispatch()->showDispatches( $order->getProvidesContext() )?>
	</fieldset>

	<div id="o_invoices" class="o_anchor"></div>
	<fieldset class="o_section">
		<legend><?=UI::icon('file-invoice-dollar')?> <?=Tr::_('Invoices')?></legend>
		
		<?=Admin_Managers::Invoice()->showOrderInvoices( $order )?>
		<?=Admin_Managers::InvoiceInAdvance()->showOrderInvoices( $order )?>
		<?=Admin_Managers::DeliveryNote()->showOrderInvoices( $order )?>
		
	</fieldset>

	<div id="o_history" class="o_anchor"></div>
	<fieldset class="o_section">
		<legend><?=UI::icon('clock-rotate-left')?> <?=Tr::_('Order history')?></legend>
		<div id="order-history">
		<?php require 'edit/history.phtml';?>
		</div>
	</fieldset>

	<div id="o_sent_emails" class="o_anchor"></div>
	<fieldset class="o_section">
		<legend><?=UI::icon('envelope-circle-check')?> <?=Tr::_('Sent e-mails')?></legend>
		
		<div id="sent-emails">
			<?php require 'edit/sent-emails.phtml'; ?>
		</div>
	</fieldset>

	

	<br><br><br><br>
</div>

<style>
	.o_section {
		padding: 10px;
		margin-bottom: 50px;
	}
	
	.o_anchor {
		position: relative;
		top: -80px;
	}
</style>

<?php
foreach(Handler::getHandlers() as $handler):
	echo $handler->renderDialog();
endforeach;
?>
