<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Orders;


use Jet\MVC_View;
use JetApplication\Order;

/**
 * @var MVC_View $this
 * @var Order $order
 */
$order = $this->getRaw('order');

$status = $order->getStatus();
?>
<div class="order-status order-status-<?=$status?->getCode()?>">
	<?=$status?->getTitle()?>
</div>

