<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Orders;


use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Admin_Managers;
use JetApplication\CustomerBlacklist;
use JetApplication\Order_Item;
use JetApplication\EShops;
use JetApplication\Order;

/**
 * @var MVC_View $this
 * @var Order     $order
 */

$order = $this->getRaw( 'order' );

$price_formatter = Admin_Managers::PriceFormatter();

$product_manager = Admin_Managers::Product();


$icons = [
	Order_Item::ITEM_TYPE_PRODUCT         => UI::icon( 'box' )->setTitle( Tr::_( 'Product' ) ),
	Order_Item::ITEM_TYPE_VIRTUAL_PRODUCT => UI::icon( 'box' )->setTitle( Tr::_( 'Virtual product' ) ),
	Order_Item::ITEM_TYPE_SERVICE         => UI::icon( 'handshake-angle' )->setTitle( Tr::_( 'Service' ) ),
	Order_Item::ITEM_TYPE_GIFT            => UI::icon( 'hand-holding-heart' )->setTitle( Tr::_( 'Gift' ) ),
	Order_Item::ITEM_TYPE_VIRTUAL_GIFT    => UI::icon( 'hand-holding-heart' )->setTitle( Tr::_( 'Virtual gift' ) ),
	Order_Item::ITEM_TYPE_PAYMENT         => UI::icon( 'money-bills' )->setTitle( Tr::_( 'Payment' ) ),
	Order_Item::ITEM_TYPE_DELIVERY        => UI::icon( 'truck-ramp-box' )->setTitle( Tr::_( 'Delivery' ) ),
	Order_Item::ITEM_TYPE_DISCOUNT        => UI::icon( 'arrow-down' )->setTitle( Tr::_( 'Discount' ) ),
];

?>

<div style="display: grid;grid-template-columns: 1fr 1fr;gap: 10px;margin: 10px;">
	<div class="card">
		<div class="card-header"><b><?=Tr::_('Common information')?></b></div>
		<div class="card-body">
			
			<?=$order->getStatus()->showAdmin()?>
			
			<table style="margin: 10px">
				<?php if(EShops::isMultiEShopMode()): ?>
					<tr>
						<td><b><?=Tr::_('e-shop')?></b></td>
						<td><?=$order->getEshop()->getName()?></td>
					</tr>
				<?php endif; ?>
				<tr>
					<td nowrap=""><b><?=Tr::_('Purchase date and time:')?></b></td>
					<td nowrap="" style="padding: 3px"><?= Locale::dateAndTime($order->getDatePurchased()) ?></td>
				</tr>
				<tr>
					<td nowrap=""><b><?=Tr::_('IP address:')?></b></td>
					<td nowrap="" style="padding: 3px"><?= $order->getIpAddress() ?></td>
				</tr>
				<tr>
					<td><b><?=Tr::_('Delivery method:')?></b></td>
					<td nowrap="" style="padding: 3px"><?=$order->getDeliveryMethod()?->getTitle()?></td>
				</tr>
				<tr>
					<td><b><?=Tr::_('Payment method:')?></b></td>
					<td nowrap="" style="padding: 3px"><?=$order->getPaymentMethod()?->getTitle()?></td>
				</tr>
				<tr>
					<td><b><?=Tr::_('Indicative total weight:')?></b></td>
					<td nowrap="" style="padding: 3px"><?=Locale::float($order->getTotalWeightOfProducts())?></td>
				</tr>
				<tr>
					<td><b><?=Tr::_('Indicative total volume:')?></b></td>
					<td nowrap="" style="padding: 3px"><?=Locale::float($order->getTotalVolumeOfProducts())?></td>
				</tr>
			</table>
			
			<?php Admin_Managers::Complaint()->showOrderComplaints( $order ); ?>
		</div>
	</div>
	
	<div class="card">
		<div class="card-header"><b><?=Tr::_('Customer')?></b></div>
		<div class="card-body">
			
			<table>
				<tr>
					<td></td>
					<td>
						<?=Admin_Managers::Customer()->renderItemName( $order->getCustomerId() )?>
						<br>
					</td>
				</tr>
				<tr>
					<td style="font-size: 1.2rem;font-weight: bolder"><?=Tr::_('Phone:')?></td>
					<td style="font-size: 1.2rem;font-weight: bolder"><?=$order->getPhone()?></td>
				</tr>
				<tr>
					<td><?=Tr::_('e-mail:')?></td>
					<td><?=$order->getEmail()?></td>
				</tr>
			</table>
			
			
			
			<?php
			/**
			 * @var CustomerBlacklist $bl_detail
			 */
			if(CustomerBlacklist::customerIsBlacklisted( $order->getEmail(), load_details: true, details: $bl_detail )): ?>
				<div class="alert alert-danger" role="alert" style="font-size: 1.4rem">
					<?=UI::icon('skull-crossbones')?> <?=Tr::_('Customer is blacklisted')?>
				</div>
				
				
				<?=Locale::dateAndTime($bl_detail->getCreated())?>
				<br>
				<?=nl2br($bl_detail->getDescription())?>
			
			<?php endif; ?>
		</div>
	</div>
	
	<div class="card">
		<div class="card-header"><b><?=Tr::_('Billing address')?></b></div>
		<div class="card-body">
			<?=Admin_Managers::Customer()->formatAddress( $order->getEshop(), $order->getBillingAddress() )?>
		</div>
	</div>
	
	
	<div class="card">
		<div class="card-header"><b><?=Tr::_('Delivery address')?></b></div>
		<div class="card-body">
			<?=Admin_Managers::Customer()->formatAddress( $order->getEshop(), $order->getDeliveryAddress() )?>
		</div>
	</div>
	
</div>


<?php require 'edit/items.phtml'; ?>


<script>
	window.print();
</script>