<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Listing;


use Jet\Http_Request;
use Jet\Tr;
use Jet\UI;
use Jet\MVC_View;
use Jet\UI_button;
use JetApplication\Application_Service_Admin;

/**
 * @var MVC_View $this
 * @var Listing  $listing
 */

$listing = $this->getRaw( 'listing' );
$entity_manager = $listing->getEntityManager();
$grid = $listing->getGrid();

$listing_manager = Application_Service_Admin::EntityListing();

$add_uri_creator = $listing_manager->getCreateUriCreator();

$add_uri = $add_uri_creator();


if(
	!$entity_manager::getCurrentUserCanCreate() &&
	!count($listing->getExportTypes()) &&
	!$listing_manager->getCustomBtnRenderer()
) {
	?>
	<br>
	<?php
	return;
}

?>
<div class="toolbar" id="main-toolbar">
	<?php
	if( $entity_manager::getCurrentUserCanCreate() ):
		if( ($create_btn_renderer=$listing_manager->getCreateBtnRenderer()) ):
			echo $create_btn_renderer();
		else:
		?>
		&nbsp;&nbsp;
		<?=UI::button_create('')->setUrl( $add_uri )->setClass(UI_button::CLASS_SUCCESS)?>
		<?php
		endif;
	endif;
	
	if( ($custom_btn_renderer=$listing_manager->getCustomBtnRenderer()) ):
		echo $custom_btn_renderer();
	endif;
	
	foreach($listing->getHandlers() as $handler):
		echo $handler->renderButton();
	endforeach;
	
	
	if(count($listing->getExportTypes())): ?>
	&nbsp;&nbsp;
	<div class="dropdown">
		<button class="btn btn-secondary dropdown-toggle" type="button" id="export-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<?=Tr::_('Export', dictionary: Tr::COMMON_DICTIONARY)?>
		</button>
		<div class="dropdown-menu" aria-labelledby="export-menu">
			<?php foreach($listing->getExportTypes() as $type=>$title): ?>
				<a class="dropdown-item" href="<?=Http_Request::currentURI(['export'=>$type])?>"><?=$title?></a>
			<?php endforeach; ?>
		</div>
	</div>
	<?php endif; ?>

</div>
