<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Listing;


use Jet\Http_Request;
use Jet\UI;
use Jet\Tr;
use Jet\MVC_View;
use Jet\UI_button;

/**
 * @var MVC_View     $this
 * @var Listing      $listing
 */
$listing = $this->getRaw('listing');

$selected_schema = Listing_Schema::getSelectedSchemaDefinition();

$col_titles = [];
foreach($listing->getColumns() as $col) {
	if(!$col->isMandatory()) {
		$col_titles[$col->getKey()] = $col->getTitle();
	}
}

$save_as_new_dialog = UI::dialog('save_new_col_schema_dialog', 'Save as new schema');

$update_dialog = UI::dialog('update_schema_dialog', 'Update schema');

$add_form = Listing_Schema::getAddSchemaForm();
$update_form = $selected_schema->getUpdateSchemaForm();

?>



<div id="column_schema_settings" style="display: none;margin-left: 50px;margin-right: 50px;margin-bottom: 50px;" class="card card-body shadow">

	<div style="display: grid;grid-template-columns: 300px 1fr;align-items: center">
		<div class="dropdown">
			<button class="btn btn-light dropdown-toggle" type="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<?=Tr::_('Predefined schemas', dictionary: Tr::COMMON_DICTIONARY)?>
			</button>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				<?php foreach( Listing_Schema::getList() as $schema ): ?>
					<div class="dropdown-item" style="padding-bottom: 10px;">
						<a href="<?=$schema->getURL()?>"><?=$schema->getName()?></a>
					</div>
				<?php endforeach; ?>
			</div>
		</div>

		<div><?=Tr::_('Current schema <b>%SCHEMA%</b>', ['SCHEMA'=>$selected_schema->getName()], dictionary: Tr::COMMON_DICTIONARY)?></div>
	</div>




	<div style="padding: 10px;" class="row">
		<div class="col-12 col-lg-6">
			<div class="card">
				<div class="card-header bg-info"><?=Tr::_('Available columns', dictionary: Tr::COMMON_DICTIONARY)?></div>
				<div class="list-group" id="columns_not_selected">
				</div>
			</div>
			
		</div>

		<div class="col-12 col-lg-6">
			<div class="card">
				<div class="card-header bg-success"><?=Tr::_('Selected columns', dictionary: Tr::COMMON_DICTIONARY)?></div>
				
				<div id="columns_selected" class="list-group" style="padding: 10px;">
				</div>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-12 col-lg-6">
		</div>
		<div class="col-12 col-lg-6">
			<?=UI::button(Tr::_('Set', dictionary: Tr::COMMON_DICTIONARY))->setOnClick("DisplayedColumnsSetting.set()")->setClass(UI_button::CLASS_PRIMARY)->setIcon('check')?>
			<?=UI::button(Tr::_('Update current schema', dictionary: Tr::COMMON_DICTIONARY))->setOnClick("DisplayedColumnsSetting.updateCurrentSchema()")->setClass(UI_button::CLASS_PRIMARY)->setIcon('save')?>
			<?=UI::button(Tr::_('Save as new schema', dictionary: Tr::COMMON_DICTIONARY))->setOnClick("DisplayedColumnsSetting.saveNewSchema()")->setClass(UI_button::CLASS_PRIMARY)->setIcon('save')?>
			<br><br>
		</div>
	</div>
</div>



<?=$save_as_new_dialog->start()?>
<?=$add_form->start()?>
	<?=$add_form->field('cols')?>
	<?=$add_form->field('name')?>
<?=$save_as_new_dialog->footer()?>
	<?=UI::button_save('')?>
<?=$add_form->end()?>
<?=$save_as_new_dialog->end()?>


<?=$update_dialog->start()?>
<?=$update_form->start()?>
	<?=$update_form->field('cols')?>
	<?=$update_form->field('name')?>
<?=$update_dialog->footer()?>
	<?=UI::button_save('')?>
<?=$update_form->end()?>
<?=$update_dialog->end()?>



<script>
	const DisplayedColumnsSetting = {
		settings_visible: false,

		visible_cols: <?=json_encode(Listing_Schema::getCurrentColSchema())?>,
		all_columns: <?=json_encode($col_titles)?>,
		URL: <?=json_encode(Http_Request::currentURI([Listing_Schema::SCHEMA_GET_PARAM=>'SCHEMA']))?>,

		toggle: ()=>{
			if(DisplayedColumnsSetting.settings_visible) {
				DisplayedColumnsSetting.settings_visible = false;

				$('#column_schema_settings_caret_down').show();
				$('#column_schema_settings_caret_up').hide();

				$('#column_schema_settings').hide();

			} else {
				DisplayedColumnsSetting.settings_visible = true;

				DisplayedColumnsSetting.actualizeSelected();

				$('#column_schema_settings_caret_up').show();
				$('#column_schema_settings_caret_down').hide();

				$('#column_schema_settings').show();

			}
		},

		selectCol: ( key )=> {
			if(DisplayedColumnsSetting.visible_cols.indexOf(key)<0) {
				DisplayedColumnsSetting.visible_cols.push(key);
				DisplayedColumnsSetting.actualizeSelected();
			}
		},

		unselectCol: ( key )=> {
			DisplayedColumnsSetting.visible_cols = DisplayedColumnsSetting.visible_cols.filter(function (col) {
				return key!=col;
			});
			DisplayedColumnsSetting.actualizeSelected();
		},


		actualizeSelected: ()=> {

			let not_visible_cols = [];
			let visible_cols = DisplayedColumnsSetting.visible_cols;
			for(let col in DisplayedColumnsSetting.all_columns) {
				if(visible_cols.indexOf(col)<0) {
					not_visible_cols.push(col);
				}
			}

			let not_visible_cols_html = '';
			for(let i=0;i<not_visible_cols.length;i++) {
				let col = not_visible_cols[i];
				let title = DisplayedColumnsSetting.all_columns[col];

				not_visible_cols_html += '<div class="list-group-item display_column_item" '
					+' ><button class="btn btn-success btn-sm" onclick="DisplayedColumnsSetting.selectCol(\''+col+'\')"><?=UI::icon('plus');?></button> '+title+'</div>';
			}

			let visible_cols_html = '';
			for(let i=0;i<visible_cols.length;i++) {
				let col = visible_cols[i];
				let title = DisplayedColumnsSetting.all_columns[col];

				visible_cols_html += '<div class="list-group-item display_column_item" '
					+' data-key="'+col+'"'
					+' ><button class="btn btn-danger btn-sm" onclick="DisplayedColumnsSetting.unselectCol(\''+col+'\')"><?=UI::icon('minus');?></button> <?=UI::icon('up-down')?> '+title+'</div>';
			}

			$('#columns_not_selected').html( not_visible_cols_html );

			const columns_selected = $('#columns_selected');
			columns_selected.html( visible_cols_html );

			columns_selected['sortable']({
				//handle: 'div.list-group-item',
				stop: function() {

					let schema = [];
					$('#columns_selected').find('.list-group-item').each( function(i, item) {
						schema.push( $(item).data('key') );
					});

					DisplayedColumnsSetting.visible_cols = schema;
				}

			});

		},

		set: ()=> {
			const schema = DisplayedColumnsSetting.visible_cols.join(<?=json_encode(rawurlencode(Listing_Schema::COLS_SEPARATOR))?>);
			location = DisplayedColumnsSetting.URL.replace('SCHEMA', schema);
		},

		saveNewSchema: ()=> {
			$('#<?=$add_form->field('cols')->getId()?>').val( DisplayedColumnsSetting.visible_cols.join('<?=Listing_Schema::COLS_SEPARATOR?>') );
			$('#<?=$save_as_new_dialog->getId()?>').modal('show');
		},

		updateCurrentSchema: ()=> {
			$('#<?=$update_form->field('cols')->getId()?>').val( DisplayedColumnsSetting.visible_cols.join('<?=Listing_Schema::COLS_SEPARATOR?>') );
			$('#<?=$update_dialog->getId()?>').modal('show');
		}
	};

	DisplayedColumnsSetting.actualizeSelected();

</script>
