<?php
namespace JetApplicationModule\Shop\ProductQuestions;

use Jet\MVC_View;
use Jet\Form;use Jet\UI;

/**
 * @var MVC_View   $this
 * @var Form $form
 */

$form = $this->getRaw('form');

$form->renderer()->addJsAction('onsubmit', "return false;");

$form->field( 'question' )->input()->addCustomCssStyle('height:300px');

echo $form->start();
?>
<div style="display: grid;grid-template-columns: 200px 500px;gap: 10px;">
<?php
if($form->fieldExists('author_name')) {
	echo $form->field('author_name');
}
if($form->fieldExists('author_email')) {
	echo $form->field( 'author_email' );
}

echo $form->field('question');
?>
	<div></div>
	<div><?=UI::button_save()->setOnClick("NewQuestion.send();")?></div>
</div>
<?php
echo $form->end();