<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Compare;


use Jet\Factory_MVC;
use Jet\MVC_View;
use JetApplication\KindOfProduct_EShopData;
use JetApplication\Product_EShopData;
use JetApplication\EShop_Managers;

/**
 * @var MVC_View   $this
 * @var Product_EShopData[] $products
 */

$kinds = $this->getRaw('kinds');
$products = $this->getRaw('products');

$groups = [];
$properties = [];

$property_view = Factory_MVC::getViewInstance( EShop_Managers::Catalog()->getViewsDir() );


$showProperty = function( $property_id, $product ) use (&$properties, $property_view) {
	$property = $properties[$property_id];
	$property->assocToProduct( $product->getEntityId() );
	
	$property_view->setVar('property', $property);
	$v = $property_view->render('product/detail/parameters/'.$property->getType());
	?>
	<tr>
		<td nowrap=""><?=$property->getLabel()?>:</td>
		<td style="width: 100%"><?=$v?></td>
	</tr>
	<?php
};


foreach($kinds as $k):
	/**
	 * @var KindOfProduct_EShopData $kind_of_product
	 */
	$kind_of_product = $k['kind'];
	$product_ids = $k['product_ids'];
	
	?>
<h2><?=$kind_of_product?->getName()?></h2>
<table>
	<tr>
		<?php
		foreach($product_ids as $p_id):
			$product = $products[$p_id];
			
			$layout = $kind_of_product?->getProductDetailLayout( $groups, $properties )??[];
			?>
			<td>
				<table class="table table-striped">
					<?php foreach($layout as $k=>$v):
						if(is_array($v)):
							$group_id = $k;
							$property_ids = $v;
							
							$group = $groups[$group_id];
							?>
							<tr>
								<td colspan="2"><b><?=$group->getLabel()?></b></td>
							</tr>
							<?php
							foreach($v as $property_id):
								$showProperty( $property_id, $product );
							endforeach;
						else:
							$showProperty( $v, $product );
						endif;
					endforeach; ?>
				</table>
				
			</td>
			<?php
		endforeach;
		?>
	</tr>
</table>
	<?php
endforeach;

