<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\UI;
use Jet\UI_button;
use JetApplication\EShop_Pages;

/**
 * @var MVC_View $this
 */

echo UI::button( '&nbsp;'.count($this->getRaw('product_ids')) )
	->setIcon('scale')
	->setClass( UI_button::CLASS_LIGHT )
	->setUrl( EShop_Pages::Compare()->getURL() );

