<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\MVC_Page_Interface;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var MVC_Page_Interface $page
 */
$page = $this->getRaw('page');

?>
<script>
	const Compare = {
		select: async (id) => {
			const r = await fetch('<?=$page->getURL(GET_params: ['select'=>''])?>'+id);
			const response = await r.json();

			for(let el_id in response['snippets']) {
				document.getElementById(el_id).innerHTML = response['snippets'][el_id];
			}
		},
		unselect: async (id) => {
			const r = await fetch('<?=$page->getURL(GET_params: ['unselect'=>''])?>'+id);
			const response = await r.json();

			for(let el_id in response['snippets']) {
				document.getElementById(el_id).innerHTML = response['snippets'][el_id];
			}
		}

	}
</script>
<style>

</style>