<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View $this
 * @var Form     $form
 */

$form = $this->getRaw('form');

if($form->fieldExists('decimal_places')) {
	echo $form->field('decimal_places');
}

echo $form->field('is_filter');
echo $form->field('is_default_filter');
echo $form->field('filter_priority');

