<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use Jet\Locale;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Locale $locale
 */
$form = $this->getRaw('form');
$locale = $this->getRaw('locale');
$locale = $locale->toString();


?>
<fieldset>
	<legend class="sub"><?=Tr::_('Main data')?></legend>
	<?php
	echo $form->field('/description/'.$locale.'/label');
	echo $form->field('/description/'.$locale.'/description');
	
	if($form->fieldExists('/description/'.$locale.'/bool_yes_description')) {
		echo $form->field('/description/'.$locale.'/bool_yes_description');
	}
	
	if($form->fieldExists('/description/'.$locale.'/units')) {
		echo $form->field( '/description/' . $locale . '/units' );
	}
	?>
</fieldset>
