<?php
namespace JetApplicationModule\Admin\Marketing\LandingPages;

use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );


echo $form->field( 'eshop' );
echo $form->field( 'internal_name' );
echo $form->field( 'internal_code' );
echo $form->field( 'internal_notes' );
echo $form->field( 'is_active' );
echo $form->field( 'active_from' );
echo $form->field( 'active_till' );