<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\EShopAnalyticsTester;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;
use JetApplication\Application_Service_EShop_AnalyticsService;
use JetApplication\EShop;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 * @var EShop $eshop
 * @var ?Application_Service_EShop_AnalyticsService $selected_service
 * @var array<string,Application_Service_EShop_AnalyticsService> $services
 * @var array<Test> $tests
 */

$selected_eshop = $this->getRaw('eshop');
$selected_service = $this->getRaw('service');
$selected_service_id = $this->getRaw('service_id');
$services = $this->getRaw('services');

$tests = $this->getRaw('tests');

$_services = [];
foreach($services as $service_id=>$service):
	$name = $service->getModuleManifest()->getName();
	$name = str_replace('EShop.Analytics.Service.', '', $name);
	$_services[$service_id] = $name;
endforeach;

asort($_services);
?>
<style>
	.test {
		display: grid;
		grid-template-columns: 200px 1fr;
		gap: 20px;
		margin: 20px;
	}

	.test .title {
		font-weight: bolder;
	}

	.module-list {
		background-color: #eeeeee;
	}

	.search {
		background-color: #eeeeee;
	}

	.module-list-item {
		margin: 10px;
		border: 1px solid #c2c2c2;
		border-radius: 5px;
		padding: 10px;
	}


	.module-list-item-selected {
		margin: 10px;
		border-left: 1px solid #999999;
		border-top: 1px solid #999999;
		border-bottom: 1px solid #999999;
		border-top-left-radius: 5px;
		border-bottom-left-radius: 5px;
		padding: 10px;
		font-weight: bolder;
		position: relative;
		left: 11px;
		background-image: linear-gradient(90deg, #f9f9f9 10%, #ffffff 90%);
	}
	
	.shop-select {
		display: flex;
		gap: 0px;
		background-color: #eeeeee;
	}

	.shop-select-item-selected {
		background-color: #ffffff;
		padding: 10px;
		margin-left: 5px;
		margin-right: 5px;
		border-left: 1px solid #666666;
		border-top: 1px solid #666666;
		border-right: 1px solid #666666;
		position: relative;
		top: 1px;
	}

	.shop-select-item {
		background-color: #f8f8f8;
		padding: 10px;
		margin-left: 5px;
		margin-right: 5px;
	}
	
</style>

<div style="display: grid;grid-template-columns: 250px 1fr;grid-template-rows: 40px 1fr;height: 100%">

	<div class="search"></div>

	<div class="shop-select">
		<?php if( EShops::isMultiEShopMode() ):
			foreach( EShops::getList() as $eshop):
				if($eshop->getKey()==$selected_eshop->getKey()): ?>
					<div class="shop-select-item-selected">
						<?=UI::flag( $eshop->getLocale() )?>
						<?=$eshop->getName()?>
					</div>
				<?php else: ?>
					<div class="shop-select-item">
						<a href="<?=Http_Request::currentURI(['eshop'=>$eshop->getKey()])?>">
							<?=UI::flag( $eshop->getLocale() )?>
							<?=$eshop->getName()?>
						</a>
					</div>
				<?php endif;
			endforeach;
		endif; ?>
	</div>


	<div class="module-list">
		<div class="signpost-title">
			<h4></h4>
			<hr>
		</div>
		<?php foreach($_services as $service_id=>$name):
			?>
			<?php if($selected_service_id==$service_id): ?>
				<div class="module-list-item-selected">
					<b><?=$name?></b>
				</div>
			<?php else: ?>
				<div class="module-list-item">
					<a href="<?=Http_Request::currentURI(['service'=>$service_id])?>"><?=$name?></a>
				</div>
			<?php endif; ?>
		<?php endforeach; ?>
	</div>


	<div style="padding: 20px;border: 1px solid #999999">
		<?php if($selected_service): ?>
			<h2><?=$selected_service->getModuleManifest()->getName()?></h2>
			<hr>
			<?php
			
			if(!$selected_service->getEnabled()):
				?>
				<div style="padding: 20px">
					<?=UI_messages::createInfo( Tr::_('This service is not enabled for this e-shop') )?>
				</div>
				<?php
			endif;
			
			
			if(!$selected_service->getTestingAllowed()): ?>
				<div style="padding: 20px">
					<?=UI_messages::createInfo( Tr::_('Testing is not allowed for this service') )?>
				</div>
			<?php endif; ?>
		
			<?php foreach($tests as $test):
				$result = $test->performTest();
				?>
				<div class="test card card-body">
					<div class="title"><?=$test->getTitle()?></div>
					<div class="result-code">
						<?php if($result): ?>
							<textarea style="width: 100%;" class="form-control" rows="<?=substr_count($result, "\n")+1?>"><?=$result?></textarea>
						<?php else:
							echo UI::icon('ban');
						endif; ?>
					</div>
				</div>
			<?php endforeach; ?>
		<?php endif; ?>
	</div>
</div>


