<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Categories;


use Jet\Form_Renderer;
use Jet\Tr;
use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\EShop;
use JetApplication\Category;

/**
 * @var MVC_View   $this
 * @var Category   $new_category
 */

$new_category = $this->getRaw('new_category');
$form = $new_category->getAddForm();
$form->renderer()->setDefaultLabelWidth([Form_Renderer::LJ_SIZE_MEDIUM=>2]);
$form->renderer()->setDefaultFieldWidth([Form_Renderer::LJ_SIZE_MEDIUM=>8]);

?>


<?=$this->render('lj_start')?>
<br/>
<?=$form->start();?>

	<?=Admin_Managers::EntityEdit()->renderEntityFormCommonFields( $form );?>

	<?=Admin_Managers::EntityEdit()->renderShopDataBlocks(
		form: $form,
		renderer: function( EShop $eshop, string $eshop_key ) use ($new_category, $form) : void {
			?>
			<fieldset>
				<legend class="sub"><?=Tr::_('Main data')?></legend>
				
				<?=$form->field('/eshop_data/'.$eshop_key.'/name')?>
				<?=$form->field('/eshop_data/'.$eshop_key.'/second_name')?>
				<?=$form->field('/eshop_data/'.$eshop_key.'/description')?>
			</fieldset>
			
			<fieldset>
				<legend class="sub"><?=Tr::_('SEO')?></legend>
				<?=$form->field('/eshop_data/'.$eshop_key.'/seo_title')?>
				<?=$form->field('/eshop_data/'.$eshop_key.'/seo_description')?>
				<?=$form->field('/eshop_data/'.$eshop_key.'/seo_keywords')?>
			</fieldset>
		<?php }); ?>

<?=$form->end();?>

<?=$this->render('lj_end')?>

