<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Catalog\Categories;


use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View               $this
 * @var Controller_Main $controller
 */

$controller = $this->controller;
$current_node = $controller->getCurrentNode();

?>
<div class="sub-toolbar">
	<form method="get">
		
			<div style="display: flex;align-items: center;gap: 10px;">
				<div><?=Tr::_('Order by:')?></div>
				<div>
					<select name="sort" onchange="this.form.submit()" style="width: 100%">
						<?php foreach($this->getRaw('sort_scope') as $val=>$label): ?>
							<option value="<?=$val?>"<?=$val==$this->getString('sort') ? ' selected' : '' ?>><?=$label?></option>
						<?php endforeach; ?>
					</select>
				</div>
			</div>
			<?php /*
			<div style="display: flex;align-items: center;gap: 10px;">
				<div><?=Tr::_('Is active:')?></div>
				<div>
					
					<select name="active" onchange="this.form.submit()" style="width: 100%">
						<?php foreach($this->getRaw('active_filter_scope') as $val=>$label): ?>
							<option value="<?=$val?>"<?=$val==$this->getString('active_filter') ? ' selected' : '' ?>><?=$label?></option>
						<?php endforeach; ?>
					</select>
				
				</div>
			</div>
            */ ?>
	</form>
</div>
