<?php
namespace JetApplicationModule\Admin\Catalog\Categories;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;

/**
 * @var MVC_View               $this
 * @var Controller_Main $controller
 */

$controller = $this->controller;
?>
	</div>
</div>


<?php if(Main::getCurrentUserCanEdit() && $this->getBool('allow_to_sort') ):
	$dialog = UI::dialog('sort_categories', Tr::_('Sort categories') );

	?>
	<?=$dialog->start()?>
	<div style="overflow: auto;">
		<div class="sortable" id="categories-sort">
			<?php foreach($controller->getCurrentNode()->getChildren() as $node):
				?>
				<div class="sortable-item" data-id="<?=$node->getId()?>">
					<i class="property-option-move"></i>
					<?=$node->getLabel()?>
				</div>
			<?php endforeach; ?>
		</div>
	</div>
	<?=$dialog->footer()?>
	<form action="<?=Http_Request::currentURI(['action'=>'save_sort'])?>" method="post">
		<input type="hidden" name="categories_sort_order" id="categories_sort_order" />
		<?=UI::button_save()?>
	</form>
	<?=$dialog->end()?>

<script type="text/javascript">
	const sortCategories = {
		openDialog: function () {
			sortCategories.setSort();
			$('#sort_categories').modal('show');


			$('#categories-sort')['sortable']({
				stop: function () {
					sortCategories.setSort();
				}

			});

		},

		setSort: function () {
			const values = [];

			$('#categories-sort').find('.sortable-item').each(function (i, item) {
				values.push($(item).data('id'));
			});

			$('#categories_sort_order').val(values.join('|'));

		}
	};
</script>

<?php endif; ?>
