<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Categories;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Admin_Managers;
use JetApplication\Category;

/**
 * @var MVC_View $this
 * @var Controller_Main $controller
 */
$controller = $this->controller;
$category = $controller->getCurrentItem();

$toolbar = $this->getRaw('toolbar');

?>

<div class="toolbar" id="main-toolbar" style="display: grid;grid-template-columns: 1.1fr 5fr;align-items: center;gap: 10px;margin: 0px;padding: 0px;">
	<div style="display: grid;grid-template-columns: 60% 1fr;padding: 5px;">
		<?php if(Main::getCurrentUserCanEdit()): ?>

			<div>
				<?php if( $this->getBool('allow_to_sort') ): ?>
				<?=UI::button(Tr::_('Sort categories'))
					->setOnclick('sortCategories.openDialog()')
					->setIcon('sort');
				?>
				<?php endif; ?>
			</div>
			<div style="text-align: right">
				<?php if( Main::getCurrentUserCanCreate() ): ?>
				<?=UI::button_create( Tr::_('Create') )
					->setUrl( Http_Request::currentURI(['action' => 'create']));
				?>
				<?php endif; ?>
			</div>
		<?php endif; ?>
	</div>
	<div style="display: flex;align-items: center;gap: 10px;">
		<?php if(Main::getCurrentUserCanEdit()):
			if($toolbar):
				echo $this->render($toolbar);
			endif;

			echo '&nbsp;&nbsp;&nbsp;';

			echo $this->render('edit/preview');
		endif; ?>
	</div>
</div>

<?php if($category): ?>
<div style="position: fixed;right: 2px;top: 100px;z-index: 999;">
	<?=Admin_Managers::TODO()?->renderTool( Category::getEntityType(), $category->getId() );?>
</div>
<?php endif; ?>


<div id="main-col" style="display: grid;grid-template-columns: 1.1fr 5fr;gap: 10px;padding: 0px;">
	<div class="tree">
		<?php require 'search.phtml'; ?>
		<?php require 'filter.phtml'; ?>
		<?php require 'tree.phtml'; ?>
	</div>
	<div>
		<?=$this->getRaw('tabs')?>
		<div style="width: 95%">