<?php
namespace JetApplicationModule\Admin\Catalog\Categories;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\UI;

/**
 * @var MVC_View $this
 * @var Controller_Main $controller
 */
$controller = $this->controller;
$category = $controller->getCurrentItem();

$toolbar = $this->getRaw('toolbar');

?>


<div class="row toolbar" id="main-toolbar">
	<div class="col-md-2">
		<?php if(Main::getCurrentUserCanEdit()): ?>
		<div style="display: grid;grid-template-columns: 60% 1fr;">
			<div>
				<?php if( $this->getBool('allow_to_sort') ): ?>
				<?=UI::button('Sort categories')
					->setOnclick('sortCategories.openDialog()')
					->setIcon('sort');
				?>
				<?php endif; ?>
			</div>
			<div style="text-align: right">
				<?php if( Main::getCurrentUserCanCreate() ): ?>
				<?=UI::button_create('Create')
					->setUrl( Http_Request::currentURI(['action' => 'create']));
				?>
				<?php endif; ?>
			</div>
		</div>
		<?php endif; ?>

	</div>
	<div class="col-md-10">
		<?php if(Main::getCurrentUserCanEdit()):
			if($toolbar):
				echo $this->render($toolbar);
			endif;

			echo '&nbsp;&nbsp;&nbsp;';

			echo $this->render('category/edit/preview');
		endif; ?>
	</div>
</div>

<script>
	function searchResult( id ) {
		let URL = '<?=Http_Request::currentURI(['id'=>'ID'])?>';
		URL = URL.replace('ID', id);
		
		location = URL;
	}
</script>

<div class="row h-100" id="main-col" style="margin-top: -10px;">
	<div class="col-2 tree">
		<?php require 'search.phtml'; ?>
		<?php require 'filter.phtml'; ?>
		<?php require 'tree.phtml'; ?>
	</div>
	<div class="col-10">
		<?=$this->getRaw('tabs')?>
