<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\UI;
use JetApplication\Admin_Managers;
use JetApplication\Category;

?>
<div class="toolbar" style="display: grid;grid-template-columns: 30px 1fr;align-items: center">

		<div style="text-align: center">
			<?=UI::icon('search');?>
		</div>
		<div>
			<?=Admin_Managers::FulltextSearch()->renderWhisperer(
				name: 'search_category',
				entity_type: Category::getEntityType(),
				on_select: "searchResult(selected_item.object_id)"
			)?>
		</div>

</div>