<?php

use Jet\UI;
use JetApplication\Admin_Managers;
use JetApplicationModule\Admin\Catalog\Categories\Category;

?>
<div class="toolbar" style="display: grid;grid-template-columns: 30px 1fr;align-items: center">

		<div style="text-align: center">
			<?=UI::icon('search');?>
		</div>
		<div>
			<?=Admin_Managers::FulltextSearch()->renderWhisperer(
				name: 'search_category',
				entity_type: Category::getEntityType(),
				on_select: "searchResult(selected_item.object_id)"
			)?>
		</div>

</div>