<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\Catalog\Categories;


use Jet\Data_Tree_Node;
use Jet\UI;
use Jet\MVC_View;

/**
 * @var MVC_View               $this
 * @var Controller_Main $controller
 */

$controller = $this->controller;
$current_node = $controller->getCurrentNode();

$editURL = function( int $id ) : string
{
	return $this->getController()->getControllerRouter()->action('edit')->URI($id);
};

$showCategory = function( Data_Tree_Node $node ) use ($editURL, $controller) {
	$is_active = $node->getData()['is_active'];

	$tree_icon = 'file';

	$selected = $node->getId()==$controller->getCurrentCategoryId();


	if($node->getHasChildren()) {
		$tree_icon = 'folder';

		if($selected) {
			$tree_icon = 'folder-open';
		}
	}

	$text_decoration = 'none';

	if(!$is_active) {
		$text_decoration = 'line-through';
	}

	$name = $node->getLabel();
	if(!$name) {
		$name = '???';
	}
	
	if($selected):
		?>
		<li class="selected" style="text-decoration: <?=$text_decoration?>;">
			<span class="icon"><?=UI::icon($tree_icon)?></span>
			<?=$name?>
		</li>
		<?php
	else:
		?>
		<li style="text-decoration: <?=$text_decoration?>;">
			<a href="<?=$editURL((int)$node->getId())?>">
				<span class="icon"><?=UI::icon($tree_icon)?></span>
				<?=$name?>
			</a>
		</li>
		<?php
	endif;
};
?>
<ul>
	<?php if( $controller->getCurrentCategoryId() ): ?>
		<li><a href="<?=$editURL((int)$current_node->getParentId())?>">..</a></li>
		<?php $showCategory( $current_node ); ?>

		<ul>
		<?php
		foreach($current_node->getChildren() as $node):
			$showCategory( $node );
		endforeach;
		?>
		</ul>
	<?php else:
		foreach($current_node->getChildren() as $node):
			$showCategory( $node );
		endforeach;
	endif; ?>
</ul>



