<?php
namespace JetApplicationModule\Admin\WarehouseManagement\ReceiptOfGoods;

use Jet\Locale;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var ReceiptOfGoods $item
 */

$item = $this->getRaw('item');
?>
<div style="display: grid;grid-template-columns: 40px 1fr;gap: 10px; align-items: center;font-size: 0.7rem">
	<?php foreach($item->getItems() as $item):
		if(!$item->getUnitsReceived()) {
			continue;
		}
		?>
		<div><?=Locale::float($item->getUnitsReceived())?> <?=$item->getMeasureUnit()?->getName()?></div>
		<div><?=$item->getProductName()?></div>
	<?php endforeach; ?>
</div>
