<?php
namespace JetApplicationModule\Admin\WarehouseManagement\ReceiptOfGoods;

use Jet\Locale;
use Jet\MVC_View;
use JetApplication\Admin_Managers_Entity_Listing;

/**
 * @var MVC_View $this
 * @var ReceiptOfGoods $item
 * @var Admin_Managers_Entity_Listing $listing
 */

$item = $this->getRaw('item');
$listing = $this->getRaw('listing');

$edit_uri = $listing->getEditUrl($item);
?>
<a href="<?=$edit_uri?>"><?=Locale::date($item->getReceiptDate())?></a>


