<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\WarehouseManagement\ReceiptOfGoods;


use Jet\MVC_View;
use JetApplication\Admin_Managers_EShopEntity_Listing;
use JetApplication\WarehouseManagement_ReceiptOfGoods;

/**
 * @var MVC_View $this
 * @var WarehouseManagement_ReceiptOfGoods $item
 * @var Admin_Managers_EShopEntity_Listing $listing
 */

$item = $this->getRaw('item');

echo $item->getSuppliersBillNumber();
