<?php
namespace JetApplicationModule\Admin\WarehouseManagement\ReceiptOfGoods;

use Jet\MVC_View;
use JetApplication\Admin_Managers_Entity_Listing;
use JetApplication\Supplier;

/**
 * @var MVC_View $this
 * @var ReceiptOfGoods $item
 * @var Admin_Managers_Entity_Listing $listing
 */

$item = $this->getRaw('item');
$listing = $this->getRaw('listing');

$supplier = Supplier::get( $item->getSupplierId() );
if(!$supplier) {
	return;
}

echo $supplier->getCompanyName();