<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\CashDesk;


use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\EShop_Managers;

$oauth = EShop_Managers::OAuth();

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');

$form = $cash_desk->getSetEMailForm();

$form->renderer()->addJsAction('onsubmit', 'CashDesk.customer.email.set();return false;');

$form->renderer()->setDefaultLabelWidth([
		Form_Renderer::LJ_SIZE_MEDIUM => '12'
]);

$form->renderer()->setDefaultFieldWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => '12'
]);

$email_field = $form->field('email');


$email_field->renderer()->setCustomRenderer(function() use ( $email_field ) {
	?>
<div class="form-field">
	<label><?=$email_field->getLabel()?></label>
	<div><?=$email_field->input().$email_field->error()?></div>
</div>
	<?php
	
});
?>


<span class="step-title"><?=Tr::_("Please tell us your e-mail or log-in using your Google or Facebook account.")?></span>
<?=$form->start()?>

	<?=$form->field('email')?>

<div class="continue-button-area">
	<?=UI::button('Continue')->setClass('primary')->setType('submit')?>
</div>
<?=$form->end()?>


<?php if($oauth):
	foreach($oauth->getOAuthModules() as $oauth_module): ?>
		<?=$oauth->renderLoginButton( $oauth_module );?>
	<?php endforeach;
endif;


