<?php
namespace JetApplicationModule\EShop\CashDesk;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');
?>
<div id="cash_desk_billing_address">
	<?php if(!$cash_desk->getPhoneHasBeenSet()):
		require 'logged_in/phone.phtml';
	else:
		require 'logged_in/phone_has_been_set.phtml';
		require 'billing_address.phtml';
	endif; ?>
	
</div>

<div id="cash_desk_delivery_address">
	<?php
	if($cash_desk->getPhoneHasBeenSet()):
		require('delivery_address.phtml');
	endif;
	?>
</div>
