<?php
namespace JetApplicationModule\EShop\CashDesk;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');

if($cash_desk->getNoRegistration()):
	require 'registration/no_registration.phtml';
endif;

require 'registration/email_and_phone_has_been_set.phtml';
?>
<div id="cash_desk_billing_address">
	<?php require('billing_address.phtml'); ?>
</div>

<div id="cash_desk_delivery_address">
	<?php require('delivery_address.phtml'); ?>
</div>

