<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\EventViewer\Exports;


use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Event    $item
 * @var Listing  $listing
 */
$item = $this->getRaw( 'item' );
$listing = $this->getRaw( 'listing' );
?>
<a href="<?=$listing->getItemURI($item->getId())?>"><?=$item->getEvent();?></a>

