<?php
namespace JetShopModule\Admin\Catalog\Products;
use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use Jet\UI;
use JetShop\Product;
use JetShop\Shops_Shop;

/**
 * @var MVC_View $this
 * @var Shops_Shop $shop
 * @var Form $images_form
 * @var Form $image_delete_form
 * @var Product $product
 */

$product = $this->getRaw('product');
$suffix = $this->getString('suffix');

for( $i=0; $i<Product::$max_image_count; $i++ ):
	$image = $product->getImageRaw( $i );

	if(!$image) {
		continue;
	}

	$url = $product->getImageUrlRaw( $i );
	$thb_url = $product->getImageThumbnailUrlRaw(150,150, $i);

	?>

	<div style="width: 180px;height: 210px;float: left;margin: 5px;border: 1px solid #c9c9c9;border-radius: 5px;background-color:#ffffff;">
		<div class="image-thumbnail" data-image="<?=$i?>" style="background-image: url(<?=$thb_url?>);width: 160px;height: 160px;position: relative">
			<div style="position: absolute;bottom: 5px;right: 5px;">
				<input type="checkbox" value="<?=$i?>" data-url="<?=$url?>" class="select_image_checkbox"/>
			</div>
		</div>
		<div style="width: 180px;height: 55px;padding: 5px;">
			<table style="width: 100%">
				<tr>
					<td style="width: 30px;">
						<?=UI::icon('exchange-alt')?>
					</td>
					<td style="width: 30px;">
						<a href="<?=$url?>" download target="_blank"><?=UI::icon('download')->setTitle(Tr::_('Download image'))?></a>
					</td>
					<td style="padding-right: 5px; text-align: right">
						<a href="javascript:ImageHandlers['<?=$suffix?>'].deleteImage('<?=$i?>', '<?=$url?>');"><?=UI::icon('trash')->setTitle(Tr::_('Delete image'))?></a>
					</td>
				</tr>
			</table>
		</div>
	</div>

<?php endfor; ?>

