<?php
namespace JetApplicationModule\Admin\Catalog\Suppliers;

use JetApplication\Supplier;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use Jet\UI;

/**
 * @var MVC_View   $this
 * @var Form       $form
 * @var Supplier    $supplier
 */
$form = $this->getRaw( 'form' );

$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 8 ] );

$supplier = $this->getRaw( 'supplier' );

?>
<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()->setOnclick("$('#".$form->getId()."').submit();")?>
		<?php endif; ?>
	</div>
</div>

<div class="row">

	<div class="col-md-12" id="main-col">

		<?=$form->start()?>
		<?=$form->field( 'name' )?>

		<?=$form->end()?>


	</div>
</div>

