<?php
namespace JetShopModule\Admin\Catalog\Suppliers;

use Jet\Http_Request;
use JetShop\Supplier;

use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View   $this
 * @var Supplier    $supplier
 */
$supplier = $this->getRaw( 'supplier' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( 'Do you really want to delete this Supplier?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $supplier->getId() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$supplier->getName();?></a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>