<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Content\InfoBoxes;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Content_InfoBox;

/**
 * @var MVC_View $this
 * @var Content_InfoBox $item
 */

$item = $this->getRaw('item');

if($item->isEditable()) {
	echo Admin_Managers::Image()->commonImageManager( 'info_box', $item->getId() );
}
