<?php

use Jet\UI_messages_message;
use Jet\UI_messages;
use Jet\UI;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var UI_messages_message $m
 */
$m = $this->getRaw( 'element' );

$icon = $m->getIcon();

if( !$icon ) {
	$icons_map = [
		UI_messages::C_INFO    => 'info-circle',
		UI_messages::C_SUCCESS => 'thumbs-up',
		UI_messages::C_WARNING => 'exclamation-circle',
		UI_messages::C_DANGER  => 'thumbs-down',
	];

	$icon = $icons_map[$m->getClass()];
}

$id = '__message__' . md5( $m->getMessage() . microtime( true ) );

?>
	<div class="alert alert-<?= $m->getClass() ?>" role="alert" id="<?= $id ?>">
		<?=UI::icon( $icon );?>
		<span><?= $m->getMessage() ?></span>
	</div>
