<?php
namespace JetApplicationModule\Admin\Orders;

use Jet\Form;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

use Jet\MVC_View;


/**
 * @var MVC_View $this
 * @var Form $form
 * @var Order $order
 */

$order = $this->getRaw('order');

if( !$order->isEditable()) {
	return;
}

echo UI::button(Tr::_('Join order'))
	->setClass(UI_button::CLASS_INFO)
	->setIcon('arrows-to-circle')
	->addCustomCssClass('dropdown-item')
	->setOnClick("joinOrder.showDialog();");



