<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Orders;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View $this
 */

$this_order = $this->getRaw('this_order');
$join_order = $this->getRaw('join_order');

$order_manager = Admin_Managers::Order();

$join_order_name = $order_manager->showName($join_order->getId());
?>
<ul>
	<li><?=Tr::_('Items from order <b>%join_order_number%</b> will be moved to order <b>%this_order_number%</b>.', [
		'join_order_number' => $join_order_name,
		'this_order_number' => $this_order->getNumber()
	])?></li>
	<li><?=Tr::_('Order <b>%join_order_number%</b> will be cancelled.', [
			'join_order_number' => $join_order_name
		])?></li>
</ul>

<div style="text-align: right">
	<?=UI::button( Tr::_('Join order') )
		->setUrl( Http_Request::currentURI(['join_order'=>$join_order->getId()], unset_GET_params: ['join_order_search']) )
		->setClass(UI_button::CLASS_DANGER)?>
</div>