<?php
namespace JetApplicationModule\Admin\Complaints;

use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Admin_Managers;


/**
 * @var MVC_View $this
 * @var Listing_Filter_Status $filter
 */

$filter = $this->getRaw('filter');

$field = $filter->getListing()->getFilterForm()->field( 'status' );

$field->input()->addJsAction( 'onchange', 'this.form.submit()' );

echo Admin_Managers::EntityListing()->renderListingFilter(
	filter:      $filter,
	title:       Tr::_('Complaint status'),
	form_fields: [$field],
	is_active:   $field->getValue(),
	renderer:    function() use ( $field ) {
		?>
		<div>
			<?=$field->input()?>
		</div>
		<?php
	}
);
