<?php
namespace JetApplicationModule\Admin\Catalog\KindsOfProduct;

use Jet\UI;

use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View     $this
 * @var Listing $listing
 */
$router = $this->getController()->getControllerRouter();

$listing = $this->getRaw( 'listing' );
$grid = $listing->getGrid();
$filter_form = $listing->getFilterForm();


$grid->getColumn( '_edit_' )->addCustomCssStyle( 'width:200px;' );
$grid->getColumn( 'id' )->addCustomCssStyle( 'width:120px;' );
?>

<?=$filter_form->start()?>
<div class="row toolbar">
	<?php if( ( $add_uri = $router->action('add')->URI() ) ): ?>
		<div class="col-md-2 col-sm-12">
			<?=UI::button_create( Tr::_( 'Create a new Kind of product' ) )->setUrl( $add_uri )?>
		</div>
	<?php endif; ?>

	<div class="col-md-3 col-sm-12">
		<?=$listing->filter(Listing_Filter_Search::KEY)->renderForm()?>
	</div>
	<div class="col-md-4 col-sm-12">
	</div>

</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
