<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Events\SupplierGoodsOrder\GoodsReceived;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Admin_Managers;
use JetApplication\Order_Event;

/**
 * @var MVC_View $this
 * @var Order_Event $event
 * @var Main $handler
 */

$event = $this->getRaw('event');
$handler = $this->getRaw('handler');

$rcp = $event->getContext();
if(!$rcp) {
	return;
}

echo Tr::_('Receipt of goods: ');
echo Admin_Managers::ReceiptOfGoods()->renderItemName( $rcp );

//echo nl2br( $event->getNoteForCustomer() );