<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Marketing\GiftProduct;


use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_badge;
use JetApplication\Application_Service_Admin;
use JetApplication\Marketing_Gift_Product;


/**
 * @var MVC_View $this
 * @var Marketing_Gift_Product $item
 */

$item = $this->getRaw('item');

$gift_product = $item->getGiftProduct();
if(!$gift_product) {
	return;
}

$available = $gift_product->getNumberOfAvailable( $item->getEshop()->getDefaultAvailability() );

echo Application_Service_Admin::Product()->renderItemName( $gift_product->getId() );
echo '<br>';


if($gift_product->isActive()):
	echo UI::badge(UI_badge::SUCCESS, Tr::_('Active'));
else:
	echo UI::badge(UI_badge::DANGER, Tr::_('Not active'));
endif;
echo '<br>';

echo Tr::_('Available: %avl%', ['avl'=>Locale::float($available)]);
echo '<br>';

