<?php
namespace JetApplicationModule\Admin\ReturnsOfGoods;

use Jet\Tr;
use Jet\MVC_View;
use JetApplication\ReturnOfGoods_ChangeHistory;
use JetApplication\ReturnOfGoods_Note;

/**
 * @var MVC_View $this
 * @var ReturnOfGoods     $return
 */

$return = $this->getRaw( 'return' );

$history = $return->getHistory();
?>
<fieldset style="padding: 10px;">
	<legend><?=Tr::_('Return of goods history')?></legend>
	
	<table class="table table-striped">
		<thead>
		<tr>
			<th style="width: 150px;"><?=Tr::_('Date and time')?></th>
			<th style="width: 250px;"><?=Tr::_('Status')?></th>
			<th><?=Tr::_('Notes')?></th>
			<th style="width: 50px;"><?=Tr::_('Sent to customer')?></th>
			<th style="width: 150px;"><?=Tr::_('Author')?></th>
		</tr>
		</thead>
		<tbody>
		<?php foreach($history as $item):
			$this->setVar('history_item', $item);
			?>
			<tr>
				<?php
				if($item instanceof ReturnOfGoods_Note) {
					require 'history/note.phtml';
				}
				
				if($item instanceof ReturnOfGoods_ChangeHistory) {
					require 'history/change.phtml';
				}
				?>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</fieldset>
