<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ReturnsOfGoods;


use Jet\Locale;
use Jet\Tr;
use Jet\MVC_View;
use Jet\UI_messages;
use JetApplication\ReturnOfGoods;

/**
 * @var MVC_View $this
 * @var ReturnOfGoods     $return
 */

$return = $this->getRaw( 'return' );

$history = $return->getHistory();
?>

<table class="table table-striped">
	<thead>
	<tr>
		<th style="width: 150px;"><?=Tr::_('Date and time')?></th>
		<th style="width: 250px;"></th>
		<th></th>
	</tr>
	</thead>
	<tbody>
	<?php foreach($history as $event):
		$handler = $event->getHandlerModule();
		if(!$handler) {
			continue;
		}
		?>
		<tr>
			<td>
				<?=Locale::dateAndTime( $event->getDateAdded() )?>
				<br>
				<?=$event->getAdministrator() ?>
			</td>
			<td><div style="padding: 10px;font-weight: bolder;<?=$handler->getEventStyle()?>"><?=$handler->showEventName()?></div></td>
			<td>
				<?php if(!$event->getHandled()):
					//TODO:
					?>
					<?=UI_messages::createDanger( $event->getErrorMessage() ) ?>
				<?php endif; ?>
				
				<?=$handler->showEventDetails(); ?>
			</td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
