<?php
namespace JetApplicationModule\Admin\ReturnsOfGoods;

use Jet\Form;
use Jet\Locale;
use Jet\Tr;
use JetApplication\Admin_Managers;
use JetApplication\Admin_Managers_Entity_Listing;

use Jet\MVC_View;
use JetApplication\Shops;


/**
 * @var MVC_View $this
 * @var ReturnOfGoods     $return
 * @var Admin_Managers_Entity_Listing $listing
 * @var Form $add_bl_form
 */

$return = $this->getRaw( 'return' );
?>

<div id="main-col">
	<div style="padding: 10px;display: flex">
		<div style="margin: 10px" class="card">
			
			<div class="card-header"><b><?=Tr::_('Common information')?></b></div>
			<div class="card-body">
				
				<?=Admin_Managers::ReturnOfGoods()->showReturnOfGoodsStatus( $return )?>
				
				<table style="margin: 10px">
					<?php if(Shops::isMultiShopMode()): ?>
						<tr>
							<td><b><?=Tr::_('Shop')?></b></td>
							<td><?=$return->getShop()->getShopName()?></td>
						</tr>
					<?php endif; ?>
					<tr>
						<td nowrap=""><b><?=Tr::_('Purchase date and time:')?></b></td>
						<td nowrap="" style="padding: 3px"><?= Locale::dateAndTime($return->getDateStarted()) ?></td>
					</tr>
					<tr>
						<td nowrap=""><b><?=Tr::_('IP address:')?></b></td>
						<td nowrap="" style="padding: 3px"><?= $return->getIpAddress() ?></td>
					</tr>
					<tr>
						<td nowrap=""><b><?=Tr::_('Order:')?></b></td>
						<td nowrap="" style="padding: 3px"><?=Admin_Managers::Order()->showName($return->getOrderId())?></td>
					</tr>
				</table>
			</div>
		</div>
		
		<div style="margin: 10px;margin-left: 80px;" class="card">
			<div class="card-header"><b><?=Tr::_('Customer')?></b></div>
			<div class="card-body">
				
				<table>
					<tr>
						<td></td>
						<td>
							<?=Admin_Managers::Customer()->showName( $return->getCustomerId() )?>
							<br>
						</td>
					</tr>
					<tr>
						<td style="font-size: 1.2rem;font-weight: bolder"><?=Tr::_('Phone:')?></td>
						<td style="font-size: 1.2rem;font-weight: bolder"><?=$return->getPhone()?></td>
					</tr>
					<tr>
						<td><?=Tr::_('e-mail:')?></td>
						<td><a href="mailto:<?=$return->getEmail()?>"><u><?=$return->getEmail()?></u></a></td>
					</tr>
				</table>
				
				<?=Handler::getHandler( Handler_ChangeEMailAndPhone_Main::KEY )?->renderButton()?>
			</div>
		</div>
		
		<div style="margin: 10px;" class="card">
			<div class="card-header"><b><?=Tr::_('Delivery address')?></b></div>
			<div class="card-body">
				<?=Admin_Managers::Customer()->formatAddress( $return->getShop(), $return->getDeliveryAddress() )?>
				<?=Handler::getHandler( Handler_ChangeDeliveryAddress_Main::KEY )?->renderButton()?>
			</div>
		</div>
		
		<div style="margin: 10px;">
		</div>
	</div>

</div>
