<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ReturnsOfGoods;


use Jet\Form;
use Jet\Locale;
use Jet\Tr;
use JetApplication\Application_Service_Admin;
use JetApplication\Application_Service_Admin_EShopEntity_Listing;

use Jet\MVC_View;
use JetApplication\EShops;
use JetApplication\ReturnOfGoods;

/**
 * @var MVC_View $this
 * @var ReturnOfGoods     $return
 * @var Application_Service_Admin_EShopEntity_Listing $listing
 * @var Form $add_bl_form
 */

$return = $this->getRaw( 'return' );
?>


	<div style="display: flex">
		<div style="margin: 10px" class="card">
			
			<div class="card-header"><b><?=Tr::_('Common information')?></b></div>
			<div class="card-body">
				
				<?=$return->getStatus()->showAdmin()?>
				
				<table style="margin: 10px">
					<?php if(EShops::isMultiEShopMode()): ?>
						<tr>
							<td><b><?=Tr::_('e-shop')?></b></td>
							<td><?=$return->getEshop()->getName()?></td>
						</tr>
					<?php endif; ?>
					<tr>
						<td nowrap=""><b><?=Tr::_('Purchase date and time:')?></b></td>
						<td nowrap="" style="padding: 3px"><?= Locale::dateAndTime($return->getDateStarted()) ?></td>
					</tr>
					<tr>
						<td nowrap=""><b><?=Tr::_('IP address:')?></b></td>
						<td nowrap="" style="padding: 3px"><?= $return->getIpAddress() ?></td>
					</tr>
					<tr>
						<td nowrap=""><b><?=Tr::_('Order:')?></b></td>
						<td nowrap="" style="padding: 3px"><?=Application_Service_Admin::Order()->renderItemName($return->getOrderId())?></td>
					</tr>
				</table>
			</div>
		</div>
		
		<div style="margin: 10px;margin-left: 80px;" class="card">
			<div class="card-header"><b><?=Tr::_('Customer')?></b></div>
			<div class="card-body">
				
				<table>
					<tr>
						<td></td>
						<td>
							<?=Application_Service_Admin::Customer()->renderItemName( $return->getCustomerId() )?>
							<br>
						</td>
					</tr>
					<tr>
						<td style="font-size: 1.2rem;font-weight: bolder"><?=Tr::_('Phone:')?></td>
						<td style="font-size: 1.2rem;font-weight: bolder"><?=$return->getPhone()?></td>
					</tr>
					<tr>
						<td><?=Tr::_('e-mail:')?></td>
						<td><a href="mailto:<?=$return->getEmail()?>"><u><?=$return->getEmail()?></u></a></td>
					</tr>
				</table>
				
				<?=Plugin::get( Plugin_ChangeEMailAndPhone_Main::KEY )?->renderButton()?>
			</div>
		</div>
		
		<div style="margin: 10px;" class="card">
			<div class="card-header"><b><?=Tr::_('Delivery address')?></b></div>
			<div class="card-body">
				<?=Application_Service_Admin::Customer()->formatAddress( $return->getEshop(), $return->getDeliveryAddress() )?>
				<?=Plugin::get( Plugin_ChangeDeliveryAddress_Main::KEY )?->renderButton()?>
			</div>
		</div>
		
		<div style="margin: 10px;">
		</div>
	</div>

