<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ReturnsOfGoods;


use JetApplication\Application_Service_Admin_EShopEntity_Listing;

use Jet\UI;
use Jet\MVC_View;
use JetApplication\ReturnOfGoods;

/**
 * @var MVC_View $this
 * @var ReturnOfGoods     $return
 * @var Application_Service_Admin_EShopEntity_Listing $listing
 */

$return = $this->getRaw( 'return' );
$listing = $this->getRaw('listing');

$is_editable = $return->isEditable();

$prev_url = $listing->getPrevEditUrl( $return->getId() );
$next_url = $listing->getNextEditUrl( $return->getId() );

?>
<div class="toolbar" id="main-toolbar" style="display: grid;grid-template-columns: 1fr;gap:10px;">
	<div style="display: flex;align-items: center;gap: 10px;">
		<div>
			<?=UI::button_goBack()?>
		</div>
		
		<div style="padding-left:20px;width: 80px;text-align: center">
			<?php if($prev_url): ?>
				<?=UI::button(' ')->setIcon('chevron-left')->setUrl($prev_url)?>
			<?php endif; ?>
		</div>
		
		
		<div style="padding-left: 10px;padding-right: 10px;text-align: center;font-size: 1.5rem;">
			<b><?=$return->getNumber()?></b>
		</div>
		
		<div style="width: 50px;text-align: center">
			<?php if($next_url): ?>
				<?=UI::button(' ')->setIcon('chevron-right')->setUrl($next_url)?>
			<?php endif; ?>
		</div>
		
		<?=Plugin::get( Plugin_Note_Main::KEY )->renderButton()?>
		<?=Plugin::get( Plugin_SendMailConfirmation_Main::KEY )->renderButton()?>
		<?=Plugin::get( Plugin_SetStatus_Main::KEY )->renderButton()?>
		
		<?=Plugin::get(Plugin_MoneyRefund_Main::KEY)?->renderButton()?>
		
		<?=Plugin::get( Plugin_ForceStatus_Main::KEY )->renderButton()?>
	
	</div>
</div>