<?php
namespace JetApplicationModule\Shop\ShoppingCart;

use Jet\MVC_View;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Shop_Managers;

/**
 * @var MVC_View $this
 */

$cart = Shop_Managers::ShoppingCart()->getCart();

?>
<table class="table table-striped">
	<?php foreach($cart->getItems() as $item):
		$product = $item->getProduct();
		?>
		<tr>
			<td style="width: 90px;">
				<img src="<?=$product->getImgThumbnailUrl(0, 90, 90)?>"/>
			</td>
			<td>
				<a href="<?=$product->getURL()?>"><?=$product->getFullName()?></a>
			</td>
			<td style="width: 30px">
				<?=UI::button_delete(' ')->setOnclick('ShoppingCart.remove('.$product->getId().');')->setSize(UI_button::SIZE_SMALL)?>
			</td>
			<td style="width: 60px;">
				<input type="number" step="1" value="<?=$item->getQuantity()?>" style="width: 50px;" onchange="ShoppingCart.setQty(<?=$product->getId()?>, this.value)">
			</td>
			<td style="width: 10%">
				<span class="small"><?=Shop_Managers::PriceFormatter()->formatWithCurrency($item->getProduct()->getPrice())?></span><br/>
			</td>
			<td style="width: 10%">
				<b><?=Shop_Managers::PriceFormatter()->formatWithCurrency($item->getAmount())?></b>
			</td>
		</tr>
	<?php endforeach; ?>
	<tfoot>
		<tr>
			<td colspan="6" style="font-weight: bolder;text-align:right;font-size: 1.5rem"><?=Shop_Managers::PriceFormatter()->formatWithCurrency($cart->getAmount())?></td>
		</tr>
	</tfoot>
</table>
