<?php
namespace JetApplicationModule\Shop\ShoppingCart;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Pricelists;
use JetApplication\Shop_Managers;

/**
 * @var MVC_View $this
 */

$cart = Shop_Managers::ShoppingCart()->getCart();

?>
<div style="display: grid;grid-template-columns: 90px 1fr 200px 30px 130px 10% 12%;align-items: center;gap: 10px">
	<?php foreach($cart->getItems() as $item):
		$product = $item->getProduct();
		$mu = $product->getMeasureUnit();
		$delivery_info = $product->getDeliveryInfo( $cart->getAvailability() );
		?>

		<div>
			<img src="<?=$product->getImgThumbnailUrl(0, 90, 90)?>"/>
		</div>
		<div>
			<a href="<?=$product->getURL()?>"><?=$product->getFullName()?></a>
		</div>
		<div>
			<?php if($item->getNumberOfUnits()<=$delivery_info->getNumberOfUnitsAvailable()): ?>
				<span class="availability_in_stock"><?=Tr::_('In stock')?></span>
			<?php else:
				$avl = $delivery_info->getNumberOfUnitsAvailable();
				if($avl<=0) {
					$avl = 0;
				}
				
				if($avl>0): ?>
					<?=$avl.' '.$mu?->getName()?> <span class="availability_in_stock"><?=Tr::_('In stock')?></span><br>
				<?php endif; ?>
				
				<?=($item->getNumberOfUnits()-$avl).' '.$mu?->getName()?> <span class="availability_<?=$delivery_info->getSituation()?>"><?=$delivery_info->getDeliveryInfoTextTranslated()?></span><br>
			<?php endif ?>
		</div>
		<div>
			<?=UI::button_delete(' ')->setOnclick('ShoppingCart.remove('.$product->getId().');')->setSize(UI_button::SIZE_SMALL)?>
		</div>
		<div>
			<input type="number" step="<?=$mu?->getNumberStep()??1?>" <?php if(!$mu?->isIsDecimalNumber()):?> oninput="this.value=(parseInt(this.value)||0)"<?php endif; ?> value="<?=$item->getNumberOfUnits()?>" style="width: 50px;" onchange="ShoppingCart.setQty(<?=$product->getId()?>, this.value)">
			<?=$mu?->getName()?>
		</div>
		<div class="small">
			<?=Shop_Managers::PriceFormatter()->formatWithCurrency($item->getProduct()->getPrice( Pricelists::getCurrent() ))?> / <?=$mu?->getName()?>
		</div>
		<div>
			<b><?=Shop_Managers::PriceFormatter()->formatWithCurrency($item->getAmount())?></b>
		</div>

	<?php endforeach; ?>

	<div style="grid-column: span 6">
	
	</div>
	<div style="font-weight: bolder;font-size: 1.5rem">
		<?=Shop_Managers::PriceFormatter()->formatWithCurrency($cart->getAmount())?>
	</div>
	
</div>

