<?php
namespace JetShop;

use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Customer $user
 */

$user = $this->getRaw('user');
?>
Vítejte v systému!

Zde jsou vaše přihlašovací údaje:

	Uživatelské jméno: <?=$user->getUsername()?>

	Heslo: <?=$this->getString('password')?>

	Vaše jméno: <?=$user->getName()?>

	Váš e-mail: <?=$user->getEmail()?>


Po přihlášení si prosím změňte heslo

Přejeme příjemný den