<?php
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Entity_WithCodeAndShopData_ShopData;
use JetApplication\Entity_WithIDAndShopData_ShopData;

/**
 * @var MVC_View $this
 * @var Entity_WithCodeAndShopData_ShopData|Entity_WithIDAndShopData_ShopData $shop_data
 */

$shop_data = $this->getRaw('shop_data');
?>
<div style="padding: 10px;">
	<?php if($shop_data->isActiveForShop()):?>
		<span class="btn btn-success"><?= UI::icon('check');?> <?=Tr::_('Active')?> </span>
	<?php else: ?>
		<span class="btn btn-danger"><?= UI::icon('circle-xmark');?> <?=Tr::_('Not active')?></span>
	<?php endif; ?>
</div>


