<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\ProductListing;

/**
 * @var MVC_View   $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');
?>

<?=UI::button(Tr::_('Price'))->setIcon('')->setOnClick("listing.UI.goToFilter('f_price')");?>

<?php foreach($listing->getProperties() as $property):
	if($property->getIsDefaultFilter()):
		echo UI::button( $property->getLabel() )->setIcon('')->setOnClick("listing.UI.goToFilter('f_property_{$property->getId()}')");
	endif;
endforeach; ?>

<?=UI::button(Tr::_('Brand'))->setIcon('')->setOnClick("listing.UI.goToFilter('f_brands')");?>

<?=UI::button(Tr::_('All filters'))->setIcon('sliders')->setOnClick("listing.UI.showFilter()");?>
