<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use JetApplication\ProductListing;
use JetApplication\Shop_Managers;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');

$products = $listing->getVisibleProducts();
?>

<?=$this->render('list/sorting');?>
<div class="product_listing_list_products">
	<?php
	foreach ($products as $product):
		$this->setVar('product', $product);
		echo $this->render('list/item');
	endforeach;
	?>
</div>
<?=$this->render('list/pagination')?>
<?=Shop_Managers::Analytics()?->viewProducts(
	$products,
	category_name: $this->getString('c_name'),
	category_id: $this->getInt('c_id')
)?>
