<?php
namespace JetApplicationModule\Admin\Entity\Edit\WithShopData;

use JetApplication\Admin_Entity_WithShopData_Interface;
use JetApplication\Admin_Managers;
use JetApplication\Entity_WithShopData;
use JetApplication\Shops_Shop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Entity_WithShopData|Admin_Entity_WithShopData_Interface     $item
 */
$form = $this->getRaw( 'form' );
$item = $this->getRaw( 'item' );

$common_data_fields_renderer = $this->getRaw('common_data_fields_renderer');
$shop_data_fields_renderer = $this->getRaw('shop_data_fields_renderer');

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 3,
	Form_Renderer::LJ_SIZE_LARGE => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 8,
	Form_Renderer::LJ_SIZE_LARGE => 8
] );

?>
<?=$form->start()?>

<?php require 'toolbar.phtml'; ?>

<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>
		<br>
		
		<?=Admin_Managers::UI()->renderEntityActivation(
			entity: $item,
			editable: !$form->getIsReadonly(),
		);?>
		
		<?=Admin_Managers::UI()->renderEntityFormCommonFields( $form );?>
		
		<?php
		if($common_data_fields_renderer) {
			$common_data_fields_renderer( $item, $form );
		}
		
		Admin_Managers::UI()->renderShopDataBlocks(
			form: $form,
			renderer: function( Shops_Shop $shop, string $shop_key ) use ($item, $form, $shop_data_fields_renderer) : void {
				$shop_data = $item->getShopData( $shop );
				
				echo Admin_Managers::UI()->renderEntityShopDataActivation(
					entity: $item,
					shop: $shop,
					editable: !$form->getIsReadonly(),
				);
				
				if($shop_data_fields_renderer) {
					$shop_data_fields_renderer( $shop, $shop_key, $item, $form );
				}
			}); ?>

	</div>
</div>

<?=$form->end()?>
