<?php
namespace JetApplicationModule\Admin\Entity\Edit\WithShopData;

use JetApplication\Admin_Entity_WithShopData_Interface;
use JetApplication\Admin_Managers;
use JetApplication\Entity_WithShopData;
use JetApplication\Shops_Shop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Entity_WithShopData|Admin_Entity_WithShopData_Interface     $item
 * @var Main $module
 */
$form = $this->getRaw( 'form' );
$item = $this->getRaw( 'item' );

$module = $this->getRaw('module');

$common_data_fields_renderer = $this->getRaw('common_data_fields_renderer');
$shop_data_fields_renderer = $this->getRaw('shop_data_fields_renderer');

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 3,
	Form_Renderer::LJ_SIZE_LARGE => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 8,
	Form_Renderer::LJ_SIZE_LARGE => 8
] );

?>

<?php require 'toolbar.phtml'; ?>


<div id="main-col">
		<?php
		echo $this->getRaw('tabs');
		if($module->getActivationDisabled()) {
			echo '<br>';
		}
		
		echo $module->renderEntityActivation(
					entity: $item,
					editable: !$form->getIsReadonly(),
				);
		
		echo $form->start();
		
		echo $module->renderEntityFormCommonFields( $form );
		
		if($common_data_fields_renderer) {
			$common_data_fields_renderer( $item, $form );
		}
		
		$module->renderShopDataBlocks(
			form: $form,
			renderer: function( Shops_Shop $shop, string $shop_key ) use ($item, $form, $shop_data_fields_renderer, $module) : void {
				$shop_data = $item->getShopData( $shop );
				
				?>
				<div style="display: flex;align-items: center">
					<div><?=$module->renderEntityShopDataActivation(
							entity: $item,
							shop: $shop,
							editable: !$form->getIsReadonly(),
						)?></div>
					<div>
						<?=$module->getTimerDisabled() || $form->getIsReadonly() ? '' : Admin_Managers::Timer()?->renderIcon( $item, $shop )?>
					</div>
				</div>
				<?php
				
				if($shop_data_fields_renderer) {
					$shop_data_fields_renderer( $shop, $shop_key, $item, $form );
				}
			});
		
		echo $form->end();
		?>
</div>

<?=Admin_Managers::Timer()?->renderIntegration()?>