<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use JetApplication\Payment_Method_Price;
use JetApplication\Admin_Managers;
use JetApplication\Payment_Method;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Payment_Method $item
 * @var Form $set_price_form
 */

$item = $this->getRaw( 'item' );
$form = $this->getRaw('form');

$form->field( 'delivery_methods' )->input()->addCustomCssStyle('height: 300px');

$form->field( 'backend_module_name' )->input()->addJsAction('onchange', 'reloadPaymentMethodSpecification(this.options[this.selectedIndex].value);');
?>
<!--suppress JSCheckFunctionSignatures -->
<script>
	async function reloadPaymentMethodSpecification( module_name ) {
		const response = await fetch('<?=Http_Request::currentURI(['action' =>'get_payment_method_specification'])?>&module='+encodeURIComponent(module_name));
		const options = await response.json();
		
		const select = document.getElementById('<?=$form->field( 'backend_module_payment_method_specification' )->getId()?>');

		while (select.options.length > 0) {
			select.remove(0);
		}
		
		for( let opt in options ) {
			const option = new Option(options[opt], opt);
			select.add( option );
		}
	}
</script>

<?=$form->field('erp_id')?>
<?=$form->field('kind' )?>
<?=$form->field('backend_module_name' )?>
<?=$form->field('backend_module_payment_method_specification' )?>
<?=$form->field('delivery_methods' )?>
<?=$form->field('discount_is_not_allowed')?>
<?=$form->field('free_payment_limit')?>
<?=$form->field('priority')?>
<div class="form-group row">
	<label class="col-form-label col-xs-12 col-sm-12 col-md-3 col-lg-2"><?=Tr::_('Price:')?></label>
	<div class="col-md-8">
		<div style="display: grid; grid-template-columns: repeat(auto-fit, 300px); gap: 20px;">
			<?php foreach( $item->getEshop()->getPricelists() as $pricelist):
				$price = Payment_Method_Price::get( $pricelist, $item->getId() );
				
				echo Admin_Managers::PriceFormatter()->showPriceInfo( $price );
			endforeach; ?>

		</div>
	</div>
</div>
<br><br>

<?=$form->field('title')?>
<?=$form->field('description')?>
<?=$form->field('description_short')?>
<?=$form->field('confirmation_email_info_text')?>
<?=$form->field( 'order_final_page_info_text')?>

