<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use JetApplication\Payment_Method;
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var EShop $eshop
 * @var Payment_Method $item
 */

$item = $this->getRaw('item');
$eshop = $this->getRaw('eshop');
$form = $this->getRaw('form');
$eshop_key = $eshop->getKey();
?>
<fieldset>
	<legend class="sub"><?=Tr::_('Main data')?></legend>
	
	<?=$form->field('/eshop_data/'.$eshop_key.'/discount_is_not_allowed')?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/free_payment_limit')?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/priority')?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/title')?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/description')?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/description_short')?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/confirmation_email_info_text')?>
</fieldset>

