<?php
namespace JetApplicationModule\Events\Order\MessageForCustomer;

use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Order_Event;
use JetApplication\Order_Note;

/**
 * @var MVC_View $this
 * @var Order_Event $event
 * @var Main $handler
 * @var Order_Note $note
 */

$event = $this->getRaw('event');
$handler = $this->getRaw('handler');

$note = $event->getContext();
if(!$note) {
	return;
}

echo Admin_Managers::Note()?->showNote( $note );
