<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Marketing\PromoAreas;


use Jet\MVC_View;
use JetApplication\Marketing_PromoArea;

/**
 * @var MVC_View   $this
 * @var Marketing_PromoArea $area
 */

$area_code = $this->getString('area_code');
$area = $this->getRaw('area');

echo $area->getHtml();
