<?php
namespace JetShopModule\Shop\Login;

use Jet\Tr;
use Jet\UI;

$form = Main::getLoginForm();

$form->tag()->addJsAction('onsubmit', 'CustomerLogin.login();return false;');
?>
<?=$form->start()?>
	<?=$form->getCommonMessage()?>
	<?=$form->field('email')?>
	<?=$form->field('password')?>
	<div class="text-right">
		<?=UI::button(Tr::_('I forget my password'))->setClass('link')->setOnclick('CustomerLogin.passwordReset.start();')?>
		<?=UI::button(Tr::_('Sign in'))->setClass('success')->setOnclick('CustomerLogin.login();')?>
	</div>
<?=$form->end()?>
