<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 */

$cash_desk = CashDesk::get();

$selected_method = $cash_desk->getSelectedDeliveryMethod();

if(!$selected_method->isPersonalTakeover()) {
	$selected_method = null;
}

if($selected_method) {
	require 'personal_takeover/selected.phtml';
} else {
	require 'personal_takeover/not-selected.phtml';
}


