<?php
namespace JetShop;


use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Delivery_Method $delivery_method
 */

$cash_desk = CashDesk::get();
$delivery_method = $this->getRaw('delivery_method');
$dm_shop_data = $delivery_method->getShopData($cash_desk->getShop());

$this->setVar('delivery_method', $delivery_method);
?>

<div class="card bg-info" onclick="CashDesk.delivery.select('<?= $delivery_method->getCode() ?>')">
	<div class="card-body">
		<h5 class="card-title">

			<input type="radio" name="delivery_method" checked onclick="setTimeout(function(){CashDesk.delivery.select('<?= $delivery_method->getCode() ?>')}, 10);return false;" />
			<img src="<?=$dm_shop_data->getIcon1ThumbnailUrl(50, 50)?>" style="padding: 5px;">

			<b><?= $dm_shop_data->getTitle() ?></b>

			<span style="padding-left: 50px;">
				<?=$this->render('delivery/price')?>
			</span>

		</h5>

		<div class="card-text">
			<?= $dm_shop_data->getDescription() ?>
		</div>

	</div>
</div>
