<?php
namespace JetApplicationModule\Admin\Entity\Edit\Simple;

use Jet\UI;
use JetApplication\Admin_Entity_Common_Interface;
use JetApplication\Entity_Common;

use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Entity_Common|Admin_Entity_Common_Interface     $item
 */
$form = $this->getRaw( 'form' );
$item = $this->getRaw( 'item' );

$common_data_fields_renderer = $this->getRaw('common_data_fields_renderer');
$shop_data_fields_renderer = $this->getRaw('shop_data_fields_renderer');

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 3,
	Form_Renderer::LJ_SIZE_LARGE => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 8,
	Form_Renderer::LJ_SIZE_LARGE => 8
] );
?>


<?=$form->start()?>

<div class="toolbar" id="main-toolbar">
	<?=UI::button_goBack()?>
	
	<?=UI::button_save()->setOnclick("$('#".$form->getId()."').submit();")?>
</div>


<div id="main-col">
		<?php
		$common_data_fields_renderer( $item, $form );
		?>
</div>

<?=$form->end()?>
