<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\UI_tabsJS_tab;
use JetApplication\EShop;

/**
 * @var MVC_View $this
 * @var EShop $eshop
 * @var UI_tabsJS_tab $tab
 */

$eshop = $this->getRaw('eshop');
$tab = $this->getRaw('tab');

echo $tab->content()->end();
