<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\UI_tabsJS_tab;
use Jet\UI;
use Jet\Tr;
use JetApplication\EShops;
use JetApplication\EShop;
use Jet\Form;
use JetApplication\Managers_General;

/**
 * @var MVC_View $this
 * @var EShop $eshop
 * @var UI_tabsJS_tab $tab
 * @var Form $form
 */

$eshop = $this->getRaw('eshop');
$eshop_key = $eshop->getKey();
$form = $this->getRaw('form');

$tab = $this->getRaw('tab');

echo $tab->content()->start();

if(
	EShops::isMultiEShopMode() &&
	$form &&
	!$form->getIsReadonly()
):
?>
<div style="padding: 5px;padding-bottom: 15px">
	<?php
	echo UI::button( Tr::_('Copy', dictionary: Tr::COMMON_DICTIONARY ) )
		->setOnClick("UI_EShopBlock.copyContentStart('{$eshop_key}', this.form, false );")
		->setIcon('copy');
	
	if( Managers_General::Translator()):
		echo UI::button( Tr::_('Copy and translate', dictionary: Tr::COMMON_DICTIONARY) )
			->setOnClick("UI_EShopBlock.copyContentStart('{$eshop_key}', this.form, true );")
			->setIcon('earth-europe');
	endif;
	?>
</div>
<?php
endif;