<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\UI_tabsJS_tab;
use Jet\UI;
use Jet\Tr;
use JetApplication\EShops;
use JetApplication\EShop;

/**
 * @var MVC_View $this
 * @var EShop $eshop
 * @var UI_tabsJS_tab $tab
 */

$eshop = $this->getRaw('eshop');
$eshop_key = $eshop->getKey();

$tab = $this->getRaw('tab');

echo $tab->content()->start();

if(EShops::isMultiEShopMode()):
?>
<div style="padding: 5px;padding-bottom: 15px">
	<?=UI::button( Tr::_('Copy', dictionary: Tr::COMMON_DICTIONARY ) )
		->setOnClick("UI_EShopBlock.copyContentStart('{$eshop_key}', this.form);")
		->setIcon('copy')?>
</div>
<?php
endif;