<?php
use Jet\MVC_View;
use Jet\UI_tabsJS;
use JetApplication\EShop;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 * @var EShop $eshop
 * @var UI_tabsJS $tabs
 */

$eshop = $this->getRaw('eshop');
$tabs = $this->getRaw('tabs');

if(EShops::isMultiEShopMode()):
	foreach( EShops::getList() as $eshop) {
		$tabs->tab( $eshop->getKey() )->addJsAction('onclick', "UI_EShopBlock.onSelect('".$eshop->getKey()."');");
	}
	
	?>
	<script>
		
		const UI_EShopBlock = {
			onSelect: ( eshop_key ) => {
				Cookies.set('selected_eshop_block_key', eshop_key, undefined, '/');
			},
			
			init: () => {
				let tab = Cookies.get('selected_eshop_block_key');

				if(tab) {
					$('.nav-tabs a[href="#' + tab + '"]').tab('show');
				}
			}
		};
		
	</script>
<?php
endif;


echo $tabs->start();