<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\MoneyRefunds;


use Jet\Locale;
use Jet\Tr;
use Jet\MVC_View;
use Jet\UI_messages;
use JetApplication\MoneyRefund;

/**
 * @var MVC_View $this
 * @var MoneyRefund     $money_refund
 */

$money_refund = $this->getRaw( 'money_refund' );

$history = $money_refund->getHistory();
?>

<table class="table table-striped">
	<thead>
	<tr>
		<th style="width: 200px;"><?=Tr::_('Date and time')?></th>
		<th style="width: 250px;"></th>
		<th></th>
		<th style="width: 200px;"><?=Tr::_('Administrator')?></th>
	</tr>
	</thead>
	<tbody>
	<?php foreach($history as $event):
		$handler = $event->getHandlerModule();
		if(!$handler) {
			continue;
		}
		?>
		<tr>
			<td>
				<?=Locale::dateAndTime( $event->getDateAdded() )?>
			</td>
			<td><div style="padding: 10px;font-weight: bolder;<?=$handler->getEventStyle()?>"><?=$handler->showEventName()?></div></td>
			<td>
				<?php if(!$event->getHandled()): ?>
					<?=UI_messages::createDanger( $event->getErrorMessage() ) ?>
				<?php endif; ?>
				
				<?=$handler->showEventDetails(); ?>
			</td>
			<td>
				<?=$event->getAdministrator() ?>
			</td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
