<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\Complaints;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Admin_Managers;
use JetApplication\CustomerBlacklist;

/**
 * @var MVC_View $this
 * @var Complaint $item
 */

$item = $this->getRaw('item');
?>
<?php if($item->getDeliveryCompanyName()): ?>
<?=$item->getDeliveryCompanyName()?><br>
<?php endif; ?>
<?=$item->getDeliveryFirstName()?> <?=$item->getDeliverySurname()?> (<?=Admin_Managers::Customer()->showName( $item->getCustomerId() )?>)<br>
<a href="mailto:<?=$item->getEmail()?>"><?=$item->getEmail()?></a><br>
<?=$item->getPhone()?><br>


<?php if( CustomerBlacklist::customerIsBlacklisted( $item->getEmail() ) ): ?>
	<div class="alert alert-danger" role="alert">
		<?=UI::icon('skull-crossbones')?> <?=Tr::_('Customer is blacklisted')?>
	</div>
<?php endif; ?>
