<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\Complaints;

use Jet\MVC_View;
use JetApplicationModule\Admin\Entity\Listing\Listing;

/**
 * @var MVC_View $this
 * @var Listing $listing
 * @var Complaint $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');
?>
	<a href="<?=$listing->getEditUrl( $item );?>"><?=$item->getNumber();?></a>
<?php
