<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Complaints;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Admin_Managers_EShopEntity_Listing;
use JetApplication\Complaint;

/**
 * @var MVC_View $this
 * @var Admin_Managers_EShopEntity_Listing $listing
 * @var Complaint $item
 */

$listing = $this->getRaw('listing');
$item = $this->getRaw('item');

echo Admin_Managers::Product()->showName( $item->getProductId() );
