<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Complaints;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Complaint;

/**
 * @var MVC_View $this
 * @var Complaint $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::Complaint()->showComplaintStatus( $item );
