<?php
namespace JetApplicationModule\Admin\Payment\Methods;

use Jet\Form;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\UI;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View   $this
 * @var Form $form
 */

$image_manager = Admin_Managers::Image();
?>
<div class="toolbar" id="main-toolbar">
	<?=UI::button_goBack()->setUrl(Http_Request::currentURI(set_GET_params: ['page'=>'options'], unset_GET_params: ['option_id']))?>
</div>

<div id="main-col">
		
		<?php
		echo $this->getRaw('tabs');
		
		echo $image_manager->renderStandardManagement();
		?>
</div>
