<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Payment\Methods;


use Jet\Form;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\UI;
use JetApplication\Application_Service_Admin;

/**
 * @var MVC_View   $this
 * @var Form $form
 */

$image_manager = Application_Service_Admin::Image();
?>
<div class="toolbar" id="main-toolbar">
	<?=UI::button_goBack()->setUrl(Http_Request::currentURI(set_GET_params: ['page'=>'options'], unset_GET_params: ['option']))?>
</div>

<div id="main-col">
		
		<?php
		echo $this->getRaw('tabs');
		
		echo $image_manager->renderStandardManagement();
		?>
</div>
