<?php
namespace JetApplicationModule\Admin\Payment\Methods;

use Jet\Form;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\UI;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View   $this
 * @var Form $form
 */

$image_manager = Admin_Managers::Image();
?>
<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()->setUrl(Http_Request::currentURI(set_GET_params: ['page'=>'options'], unset_GET_params: ['option_id']))?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		
		<?php
		echo $this->getRaw('tabs');
		
		echo $image_manager->renderStandardManagement();
		?>
	</div>
</div>
