<?php
namespace JetApplicationModule\Admin\Payment\Methods;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\EShop;

/**
 * @var MVC_View   $this
 * @var Form $form
 * @var PaymentMethod $method
 * @var PaymentMethod_Option $option
 */
$method = $this->getRaw('method');
$option = $this->getRaw('option');

$form = $option->getEditForm();
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 2
]);

echo $form->start();

?>
<?=Admin_Managers::UI()->renderEntityToolbar($form)?>

	
	<div id="main-col">
			<?=$this->getRaw('tabs')?>
			<br>
			
			<?=Admin_Managers::EntityEdit_WithEShopData()->renderEntityActivation( $option, !$form->getIsReadonly() )?>
			<?=Admin_Managers::EntityEdit_WithEShopData()->renderEntityFormCommonFields($form)?>
			<?=Admin_Managers::EntityEdit_WithEShopData()->renderShopDataBlocks(
				form: $form,
				renderer: function( EShop $eshop, string $eshop_key ) use ($option, $form) : void {
					?>
					<fieldset>
						<?=$form->field('/eshop_data/'.$eshop_key.'/title')?>
						<?=$form->field('/eshop_data/'.$eshop_key.'/description')?>
					</fieldset>
				<?php }); ?>
		
	</div>
	
	<?php
echo $form->end();

