<?php
namespace JetApplicationModule\Admin\Payment\Methods;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Shops_Shop;

/**
 * @var MVC_View   $this
 * @var Form $form
 * @var PaymentMethod $method
 * @var PaymentMethod_Option $option
 */
$method = $this->getRaw('method');
$option = $this->getRaw('option');

$form = $option->getEditForm();
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 2
]);

echo $form->start();

?>
<?=Admin_Managers::UI()->renderEntityToolbar($form)?>

	
	<div class="row">
		<div class="col-md-12" id="main-col">
			<?=$this->getRaw('tabs')?>
			<br>
			
			<?=Admin_Managers::UI()->renderEntityActivation( $option, !$form->getIsReadonly() )?>
			<?=Admin_Managers::UI()->renderEntityFormCommonFields($form)?>
			<?php
			
			Admin_Managers::UI()->renderShopDataBlocks(
				form: $form,
				renderer: function( Shops_Shop $shop, string $shop_key ) use ($option, $form) : void {
					?>
					<fieldset>
						<legend class="sub"><?=Tr::_('Main data')?></legend>
						
						<?=Admin_Managers::UI()->renderEntityShopDataActivation( $option, $shop, !$form->getIsReadonly() )?>
						
						<?=$form->field('/shop_data/'.$shop_key.'/title')?>
						<?=$form->field('/shop_data/'.$shop_key.'/description')?>
					</fieldset>
				<?php }); ?>
		
		</div>
	</div>
	
	<?php
echo $form->end();

