<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Payment\Methods;


use Jet\Form;
use Jet\Form_Renderer;
use Jet\MVC_View;
use JetApplication\Application_Service_Admin;
use JetApplication\Payment_Method;
use JetApplication\Payment_Method_Option;


/**
 * @var MVC_View   $this
 * @var Form $form
 * @var Payment_Method $method
 * @var Payment_Method_Option $option
 */
$method = $this->getRaw('method');
$option = $this->getRaw('option');

$form = $option->getEditForm();
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 2
]);

echo $form->start();

?>
<?=Application_Service_Admin::UI()->renderEntityToolbar($form)?>

	
	<div id="main-col">
			<?=$this->getRaw('tabs')?>
			<br>
			
			<?=Application_Service_Admin::EntityEdit()->renderEntityActivation( $option, !$form->getIsReadonly() )?>
			<?=Application_Service_Admin::EntityEdit()->renderEntityFormCommonFields($form)?>
		
			<?=$form->field('title');?>
			<?=$form->field('description');?>
		
	</div>
	
	<?php
echo $form->end();

