<?php
namespace JetShop;

use Jet\MVC_View;
use Jet\UI;
use Jet\Tr;
use Jet\Form;

/**
 * @var MVC_View   $this
 * @var Form $upload_form
 * @var Images_ShopDataInterface $shop_data
 * @var Shops_Shop $shop
 */
$image_class = $this->getString('image_class');
$shop = $this->getRaw('shop');
$shop_data = $this->getRaw('shop_data');

$entity = $shop_data->getImageEntity();

if($this->getBool('editable')) {
	$upload_form = $shop_data->getImageUploadForm( $image_class );
} else {
	$upload_form = false;
}

if($upload_form) {
	$image_field = $upload_form->field('image');
	$image_field->input()
		->addJsAction('onchange', "Images.uploadImage(this.form.id, '{$entity}', '{$image_class}', '{$shop->getKey()}')");
}
?>

<td style="padding: 10px;">
	<legend class="sub"><?=$this->getRaw('title')?></legend>

	<div id="image_<?=$entity?>_<?=$image_class?>_<?=$shop->getKey()?>">
		<?=$this->render('image-widget/image')?>
	</div>


	<?php if($upload_form && !$upload_form->getIsReadonly()): ?>
		<?=$upload_form->start()?>
		<div class="btn btn-light btn-upload">
			<?=UI::icon('upload')?>&nbsp;<span><?=Tr::_('Select and upload image', [], Tr::COMMON_DICTIONARY)?></span>
			<?=$image_field->input()?>
		</div>
		<?=$upload_form->end()?>
	<?php endif; ?>
</td>


