<?php
namespace JetApplication;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;

/**
 * @var MVC_View $this
 */

$selected_product_id = $this->getInt('selected_product_id');
$selected_product = Product::get($selected_product_id);
$filter = $this->getRaw('filter');
$only_active = $this->getBool('only_active');
$name = $this->getString('name');
$on_select = $this->getRaw('on_select');

?>

<script type="text/javascript">
	let <?=$name?> = new function() {
		let _this = this;

		this.init = function() {
			let whisperer = new Whisperer(
				'<?=$name?>_input',
				'<?=$name?>_whisperer',
				'<?=Product::getManageModule()->getProductSelectWhispererUrl($filter, $only_active)?>&whisper='
			);

			whisperer.init();

			whisperer.onItemSelect = function ( item_node ) {
				let selected_item = {
					id: item_node.data('id'),
					name: item_node.data('name'),
					url: item_node.data('url')
				};

				whisperer.hide();

				$('#<?=$name?>_selected_area').html(selected_item.name);

				$('#<?=$name?>_whisperer_area').hide();
				$('#<?=$name?>_selected_area').show();

				$('#<?=$name?>_selected_edit_link').show();

				$('#<?=$name?>_selected_edit_link').attr('href', selected_item.url);

				_this.onSelect( selected_item );
			};

		};

		this.startSelect = function() {
			$('#<?=$name?>_selected_area').hide();
			$('#<?=$name?>_whisperer_area').show();
			$('#<?=$name?>_input').val('');
			$('#<?=$name?>_input').focus();
		};

		this.onSelect = function( selected_item ) {
			<?=$on_select?>
		};

	};

	$(document).ready( function() {
		<?=$name?>.init();
	} );
</script>


<div style="display: table;width: 100%">
	<div style="display: table-row">
		<div class="select_item_selected_edit_link_area" style="display: table-cell;padding-right: 5px;width: 20px;" id="<?=$name?>_selected_edit_link_area">
			<?php if($selected_product): ?>
				<a href="<?=$selected_product->getEditURL()?>" id="<?=$name?>_selected_edit_link" target="_blank"><?=UI::icon('edit')?></a>
			<?php else: ?>
				<a href="" id="<?=$name?>_selected_edit_link" style="display: none;" target="_blank"><?=UI::icon('edit')?></a>
			<?php endif; ?>
		</div>
		<div class="select_item_selected_area form-control" style="display: table-cell" onclick="<?=$name?>.startSelect()" id="<?=$name?>_selected_area">
			<?php if($selected_product): ?>
				<?=$selected_product->getAdminTitle()?>
			<?php else: ?>
				<?=Tr::_('... select product ...', [], Tr::COMMON_DICTIONARY);?>
			<?php endif; ?>
		</div>
		<div class="select_item_whisperer_area" style="display: none" id="<?=$name?>_whisperer_area">
			<input id="<?=$name?>_input" style="width: 100%;" class="form-control">
			<div class="search-whisperer-area">
				<div id="<?=$name?>_whisperer">
				</div>
			</div>

		</div>
	</div>
</div>

