<?php
namespace JetShop;

use Jet\MVC_View;

/**
 * @var MVC_View   $this
 */

$items = Category_Menu::getItems(0, Category::CATEGORY_TYPE_REGULAR);
?>

<h1>Homepage</h1>

<?php foreach($items as $item): ?>
	<a href="<?=$item->getUrl()?>" style="font-size: 14px;font-weight: bolder"><?=$item->getLabel()?></a>
	<br/>
	<?php foreach($item->getChildren() as $s_item): ?>
		<a href="<?=$s_item->getUrl()?>" style="font-size: 10px;"><?=$s_item->getLabel()?></a>
	<?php endforeach; ?>
	<br/>
<?php endforeach; ?>
