<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Invoices;



use Jet\Http_Request;
use Jet\Tr;
use Jet\UI_button;
use JetApplication\Admin_Managers_EShopEntity_Listing;

use Jet\UI;
use Jet\MVC_View;
use JetApplication\Invoice;

/**
 * @var MVC_View $this
 * @var Invoice     $invoice
 * @var Admin_Managers_EShopEntity_Listing $listing
 */

$invoice = $this->getRaw( 'invoice' );
$listing = $this->getRaw('listing');

$is_editable = $invoice->isEditable();

$prev_url = $listing->getPrevEditUrl( $invoice->getId() );
$next_url = $listing->getNextEditUrl( $invoice->getId() );

?>
<div class="toolbar" id="main-toolbar">
	<div>
		<?=UI::button_goBack()?>
	</div>
	
	<div style="padding-left:20px;width: 80px;text-align: center">
		<?php if($prev_url): ?>
			<?=UI::button(' ')->setIcon('chevron-left')->setUrl($prev_url)?>
		<?php endif; ?>
	</div>
	
	
	<div style="padding-left: 10px;padding-right: 10px;text-align: center;font-size: 1.5rem;">
		
		<?php if($invoice->getIsCorrectionInvoice()): ?>
			<b class="text-danger" style="font-size: 1.2rem"><?=$invoice->getNumber()?></b>
			<div style="font-size: 0.9rem;"><?=Tr::_('Correction of: <a href="%URL%">%NUMBER%</a>', [
					'URL' => Invoice::get($invoice->getCorrectionOfInvoiceId())->getEditUrl(),
					'NUMBER'=>$invoice->getCorrectionOfInvoiceNumber()
				])?></div>
			
		<?php else: ?>
			<?php if($invoice->hasCorrections()): ?>
				<b style="text-decoration: line-through;"><?=$invoice->getNumber()?></b>
			<?php else: ?>
				<b><?=$invoice->getNumber()?></b>
			<?php endif; ?>
		<?php endif; ?>

	</div>
	
	<div style="width: 50px;text-align: center">
		<?php if($next_url): ?>
			<?=UI::button(' ')->setIcon('chevron-right')->setUrl($next_url)?>
		<?php endif; ?>
	</div>

	<div style="display: flex;gap: 100px;">
		<?=UI::button(Tr::_('PDF'))
			->setIcon('print')
			->setUrl(Http_Request::currentURI(['handle'=>'show_pdf']))
			->setCustomTagAttribute('target', '_blank')
		?>
		<?=UI::button(Tr::_('Send by e-mail to the customer'))
			->setIcon('at')
			->setClass( UI_button::CLASS_INFO )
			->setUrl(Http_Request::currentURI(['handle'=>'send']))
		?>

		<?php if(Main::getCurrentUserCanEdit() && !$invoice->getIsCorrectionInvoice()): ?>
			<?=UI::button(Tr::_('Create correction invoice'))
				->setIcon('pen-to-square')
				->setClass( UI_button::CLASS_DANGER )
				->setUrl( Http_Request::currentURI(['action'=>'create_correction_invoice']) )?>
		<?php endif; ?>
	</div>
</div>
