<?php
namespace JetApplicationModule\Admin\System\OrderStatus;

use JetApplication\Order_Status as OrderStatus;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View   $this
 * @var OrderStatus       $order_status
 */
$order_status = $this->getRaw( 'order_status' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( 'Do you really want to delete this order status?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $order_status->getCode() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$order_status->getInternalName();?> (<?=$order_status->getInternalName();?>)</a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>