<?php
namespace JetShopModule\Admin\System\OrderStatus;

use JetShop\Order_Status as OrderStatus;

use Jet\UI;
use Jet\UI_dataGrid;
use Jet\UI_button;

use Jet\Tr;
use Jet\MVC_View;
use Jet\Form;
use JetShop\Order_Status_Kind;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Form         $filter_form
 */
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );
$router = $this->getController()->getControllerRouter();


$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( OrderStatus $item ) use ( $router ) {
		if( ( $edit_uri = $router->action('edit')->URI( $item->getCode() ) ) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;
		/*
		echo '&nbsp;';
		if( ( $delete_uri = $router->action('delete')->URI( $item->getCode() ) ) ):
			echo UI::button_delete()->setUrl( $delete_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;
		*/
	}
);
$c_edit->addCustomCssStyle( 'width:200px;' );

$grid->getColumn( 'code' )->addCustomCssStyle( 'width:120px;' );

$grid->getColumn( 'internal_name' )->setRenderer(
	function( OrderStatus $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getCode() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getInternalName();?></a>
		<?php
	}
);
$grid->getColumn( 'internal_name' )->addCustomCssStyle( 'width:220px;' );

$grid->getColumn( 'code' )->setRenderer(
	function( OrderStatus $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getCode() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getCode();?></a>
		<?php
	}
);

$grid->getColumn( 'internal_description' )->setRenderer(
	function( OrderStatus $item ) use ( $router ) {
		echo nl2br($item->getInternalName());
	}
);

$grid->getColumn( 'kind' )->setRenderer(
	function( OrderStatus $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getCode() );
		?>
		<a href="<?=$edit_uri;?>"><?=Order_Status_Kind::get($item->getKind())->getTitle()?></a>
		<?php
	}
);
$grid->getColumn( 'kind' )->addCustomCssStyle( 'width:220px;' );
?>

<?=$filter_form->start()?>
<div class="row toolbar">
	<?php if( ( $add_uri = $router->action('add')->URI() ) ): ?>
		<div class="col-md-2 col-sm-12">
			<?=UI::button_create( Tr::_( 'Create a new Order Status' ) )->setUrl( $add_uri )?>
		</div>
	<?php endif; ?>

	<div class="col-md-3 col-sm-12">
		<?= $filter_form->field( 'search' )->input() ?>
	</div>
	<div class="col-md-4 col-sm-12">
	</div>

</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
