<?php
namespace JetApplicationModule\Admin\Content\Article\Articles;

use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Content_Article;

/**
 * @var MVC_View $this
 * @var Content_Article $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::EntityEdit_WithEShopData()->renderPreviewButton( $item );

if($item->isEditable()) {
	echo Admin_Managers::Image()->commonImageManager( 'info_page', $item->getId() );
}
