<?php
namespace JetShopModule\Admin\Catalog\DeliveryTerms;

use Jet\Http_Request;
use JetShop\DeliveryTerm;

use Jet\UI;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View   $this
 * @var DeliveryTerm    $delivery_term
 */
$delivery_term = $this->getRaw( 'delivery_term' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( 'Do you really want to delete this delivery term?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $delivery_term->getId() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$delivery_term->getName();?></a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>