<?php
namespace JetShopModule\Admin\Catalog\DeliveryTerms;

use JetShop\DeliveryTerm;
use Jet\Mvc_View;
use Jet\Form;
use Jet\UI;

/**
 * @var Mvc_View   $this
 * @var Form       $form
 * @var DeliveryTerm    $delivery_term
 */
$form = $this->getRaw( 'form' );

$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 8 ] );
?>



<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()->setOnclick("$('#".$form->getId()."').submit();")?>
		<?php endif; ?>
	</div>
</div>

<div class="row">

	<div class="col-md-12" id="main-col">

		<?=$form->start()?>
		<?=$form->field( 'name' )?>

		<?=$form->end()?>

	</div>
</div>

