<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use Jet\Locale;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Locale $locale
 */
$form = $this->getRaw('form');
$locale = $this->getRaw('locale');
$locale_str = $locale->toString();

$form->field('/description/'.$locale_str.'/url_param')->setIsReadonly(true);
?>
<fieldset>
	<legend class="sub"><?=Tr::_('Main data')?></legend>
	
	<?=$form->field('/description/'.$locale_str.'/name');?>
	<?=$form->field('/description/'.$locale_str.'/second_name');?>
	<?=$form->field('/description/'.$locale_str.'/description');?>
	<?=$form->field('/description/'.$locale_str.'/url_param');?>
</fieldset>
<fieldset>
	<legend class="sub"><?=Tr::_('SEO')?></legend>
	
	<?=$form->field('/description/'.$locale_str.'/seo_title');?>
	<?=$form->field('/description/'.$locale_str.'/seo_description');?>
	<?=$form->field('/description/'.$locale_str.'/seo_keywords');?>
</fieldset>
