<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var EShop $eshop
 */
$form = $this->getRaw('form');
$eshop = $this->getRaw('eshop');
$eshop_key = $eshop->getKey();

$form->field('/eshop_data/'.$eshop_key.'/url_param')->setIsReadonly(true);
?>
<fieldset>
	<legend class="sub"><?=Tr::_('Main data')?></legend>
	
	<?=$form->field('/eshop_data/'.$eshop_key.'/name');?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/second_name');?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/description');?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/url_param');?>
</fieldset>
<fieldset>
	<legend class="sub"><?=Tr::_('SEO')?></legend>
	
	<?=$form->field('/eshop_data/'.$eshop_key.'/seo_title');?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/seo_description');?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/seo_keywords');?>
</fieldset>
