<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\DeliveryNotes;

use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\DeliveryNote;

/**
 * @var MVC_View $this
 * @var DeliveryNote $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::PriceFormatter()->formatWithCurrencyByHasVAT( $item->hasVAT(), $item->getCurrency(), $item->getTotal() );
