<?php
use Jet\MVC_View;
use Jet\Form;


/**
 * @var MVC_View $this
 * @var Form     $form
 */

$form = $this->getRaw('form');

echo $form->field( 'eshop' );
echo $form->field( 'internal_name' );
echo $form->field( 'internal_code' );
echo $form->field( 'internal_notes' );

echo $form->field( 'active_from' );
echo $form->field( 'active_till' );
echo $form->field( 'priority' );
echo $form->field( 'relevance_mode' );


echo $form->field( 'color_text' );
echo $form->field( 'color_background' );
echo $form->field( 'priority' );
echo $form->field( 'text' );
