<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\MVC_View;
use JetApplication\Order;

/**
 * @var MVC_View $this
 * @var Order $order
 */

$id = $this->getRaw('id');
$order = $this->getRaw('order');

?>
<script type="text/javascript">
	(function(w,d,s,u,n,k,c,t){w.ZboziConversionObject=n;w[n]=w[n]||function(){
		(w[n].q=w[n].q||[]).push(arguments)};w[n].key=k;c=d.createElement(s);
		t=d.getElementsByTagName(s)[0];c.async=1;c.src=u;t.parentNode.insertBefore(c,t)
	})(window,document,"script","https://www.zbozi.cz/conversion/js/conv-v3.js","zbozi","<?=$id?>");

	zbozi("setOrder",{
		"orderId": "<?=$order->getNumber()?>"
	});

	zbozi("send");
</script>
