<?php
namespace JetShopModule\Admin\Catalog\Stencils;

use Jet\Mvc_View;
use Jet\Form;
use Jet\Tr;
use Jet\UI;
use JetShop\Shops;
use JetShop\Stencil;
use JetShop\Stencil_Option;
use JetShop\Stencil_Option_ShopData;

/**
 * @var Mvc_View          $this
 * @var Stencil           $stencil
 * @var Stencil_Option    $option
 */
$stencil = $this->getRaw( 'stencil' );
$option = $this->getRaw('option');

$form = $option->getEditForm();

$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 4 ] );

$tabs = UI::tabsJS('option_tabs', [
	'tab_main' => Tr::_('Main data'),
	'tab_images' => Tr::_('Images')
]);
?>



<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()->setUrl( $stencil->getEditURL() )?>

		<?php if(!$form->getIsReadonly()): ?>
		<?=UI::button_save()->setOnclick("$('#".$form->getId()."').submit();")?>
		<?php endif; ?>
	</div>
</div>

<div class="row">

	<div class="col-md-12" id="main-col">

		<?=$tabs?>
		<?=$tabs->contentStart()?>
			<?=$tabs->getTab('tab_main')->contentStart()?>
				<?=$form->start()?>

				<?php foreach(Shops::getList() as $shop):
					$shop_id = $shop->getId();

					$form->field('/shop_data/'.$shop_id.'/filter_label')->input()->addJsAction('onchange', "urlPathPart.afterNameChanged(this.value, '".$form->field('/shop_data/'.$shop_id.'/url_param')->getId()."', '".$shop_id."');");
					$form->field('/shop_data/'.$shop_id.'/filter_label')->input()->addJsAction('onchange', "$('#".$form->field('/shop_data/'.$shop_id.'/product_detail_label')->getId()."').val(this.value);");
					$form->field('/shop_data/'.$shop_id.'/url_param')->input()->addJsAction('onchange', "urlPathPart.afterPathPartChanged(this, '".$shop_id."')");

					$shop_data = $option->getShopData( $shop_id );
					?>
					<?=$shop_data->renderShopDataBlock_start()?>

					<fieldset>
						<legend class="sub"><?=Tr::_('Main data')?></legend>

						<?=$form->field('/shop_data/'.$shop_id.'/is_active')?>
						<?=$form->field('/shop_data/'.$shop_id.'/filter_label')?>
						<?=$form->field('/shop_data/'.$shop_id.'/product_detail_label')?>
						<?=$form->field('/shop_data/'.$shop_id.'/url_param')?>
						<?=$form->field('/shop_data/'.$shop_id.'/description')?>
					</fieldset>

					<fieldset>
						<legend class="sub"><?=Tr::_('SEO')?></legend>
						<?=$form->field('/shop_data/'.$shop_id.'/internal_fulltext_keywords')?>
					</fieldset>
					<?=$shop_data->renderShopDataBlock_end()?>
				<?php endforeach; ?>
				<?=$form->end()?>
			<?=$tabs->getTab('tab_main')->contentEnd()?>
			<?=$tabs->getTab('tab_images')->contentStart()?>
				<?php
				foreach(Shops::getList() as $shop):
					$shop_id = $shop->getId();

					echo $option->getShopData( $shop_id )->renderImageWidgets( Stencil_Option_ShopData::getImageClasses() );
				endforeach;
				?>
			<?=$tabs->getTab('tab_images')->contentEnd()?>
		<?=$tabs->contentEnd()?>



	</div>
</div>

