<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\NumberSeriesManager;


use Jet\Form_Renderer_Field_Label;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Form;
use Jet\UI;
use Jet\UI_messages;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 * @var Form[] $forms
 */

$forms = $this->getRaw('forms');
$entities = $this->getRaw('entities');


$showForm = function( Form $form ) : void
{
	$form->renderer()->setDefaultFieldWidth([
		Form_Renderer_Field_Label::LJ_SIZE_MEDIUM => 2
	]);
	$form->renderer()->setDefaultLabelWidth([
		Form_Renderer_Field_Label::LJ_SIZE_MEDIUM => 2
	]);
	
	$form->setAction( Http_Request::currentURI().'#'.$form->getId() );
	
	echo $form->start();
	echo $form->field('counter_class');
	echo $form->field('prefix');
	echo $form->field('pad_length');
	?>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-2">
			<?=UI::button_save()?>
		</div>
	</div>
	<?php
	echo $form->end();
};

foreach( UI_messages::get(context: 'CC') as $message ):
	echo $message;
endforeach;


foreach($entities as $entity):
	$e = $entity['entity'];
	?>
	<fieldset>
		<legend><?=$entity['title']?></legend>
		
		<?php if($entity['per_eshop']): ?>
			<?php foreach( EShops::getList() as $eshop): ?>
			<div class="card">
				<div class="card-header">
					<?=UI::flag($eshop->getLocale())?> <?=$eshop->getName()?>
				</div>
				<div class="card-body">
					<?php $showForm( $forms[$e.'_'.$eshop->getKey()] ); ?>
				</div>
			</div>
			<br><br>
			<?php endforeach; ?>
		<?php else:
			$showForm( $forms[$e] );
		endif; ?>
	</fieldset>
	<br><br>
	<?php
endforeach;