<?php
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Entity_WithShopData_ShopData;

/**
 * @var MVC_View $this
 * @var Entity_WithShopData_ShopData $shop_data
 */

$shop_data = $this->getRaw('shop_data');
?>
<div style="padding: 10px;">
	<?php if($shop_data->isActiveForShop()): ?>
		<span class="btn btn-success"><?= UI::icon('check');?> <?=Tr::_('Active')?> </span>
		<a href="<?= $this->getRaw('deactivate_url') ?>" class="btn btn-danger"><?=Tr::_('Deactivate')?></a>
	<?php else: ?>
		<span class="btn btn-danger"><?= UI::icon('circle-xmark');?> <?=Tr::_('Not active')?></span>
		<a href="<?= $this->getRaw('activate_url') ?>" class="btn btn-success"><?=Tr::_('Activate')?></a>
	<?php endif; ?>
</div>


