<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\Tr;
use JetApplication\EShop_Pages;

?>
<a class="step-prev" href="<?= EShop_Pages::ShoppingCart()->getURL()?>"><?= Tr::_('Shopping cart'); ?></a>
<a class="step-prev" onclick="CashDesk.delivery.back();return false;"><?= Tr::_('Delivery'); ?></a>
<a class="step-prev" onclick="CashDesk.payment.back();return false;"><?= Tr::_('Payment'); ?></a>
<a class="step-prev" onclick="CashDesk.customer.registration.back();return false;"><?= Tr::_('Registration'); ?></a>
<div class="step-current"><?= Tr::_('Confirmation'); ?></div>