<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\Tr;
use JetApplication\EShop_Pages;

?>
<a class="step-prev" href="<?= EShop_Pages::ShoppingCart()->getURL()?>"><?= Tr::_('Shopping cart'); ?></a>
<div class="step-current"><?= Tr::_('Delivery'); ?></div>
<div class="step-next"><?= Tr::_('Payment'); ?></div>
<div class="step-next"><?= Tr::_('Registration'); ?></div>
<div class="step-next"><?= Tr::_('Confirmation'); ?></div>