<?php
namespace JetApplication;

use JetShop\Core_EShopEntity_HasProductsRelation_Interface;

interface EShopEntity_HasProductsRelation_Interface extends Core_EShopEntity_HasProductsRelation_Interface
{
}