<?php
namespace JetShopModule\Admin\Catalog\Categories;


use Jet\Form;
use Jet\Tr;
use Jet\Mvc_View;
use JetShop\Parametrization_Property;
use JetShop\Shops;

/**
 * @var Mvc_View   $this
 * @var Parametrization_Property $new_property
 * @var Form $form
 */
$new_property = $this->getRaw('new_property');

$form = $new_property->getAddForm();
$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 2
]);


echo $this->render('lj_start');
	echo '</br>';
	echo $form->start();


		echo $form->field('is_active');

		echo $form->field('allow_display');
		echo $form->field('allow_filter');
		echo $form->field('allow_compare');

		if($form->fieldExists('stencil_id')) {
			echo $form->field('stencil_id');
		}
		if($form->fieldExists('decimal_places')) {
			echo $form->field('decimal_places');
		}

		if($form->fieldExists('is_variant_selector')) {
			echo $form->field('is_variant_selector');
		}

		foreach(Shops::getList() as $shop):
			$shop_code= $shop->getCode();
			$shop_data = $new_property->getShopData( $shop_code );

			$form->field('/shop_data/'.$shop_code.'/label')->input()->addJsAction('onchange', "urlPathPart.afterNameChanged(this.value, '".$form->field('/shop_data/'.$shop_code.'/url_param')->getId()."', '".$shop_code."')");
			$form->field('/shop_data/'.$shop_code.'/url_param')->input()->addJsAction('onchange', "urlPathPart.afterPathPartChanged(this, '".$shop_code."')");
			?>
			<?=$shop_data->renderShopDataBlock_start()?>

			<fieldset>
				<legend class="sub"><?=Tr::_('Main data')?></legend>
				<?php
				echo $form->field('/shop_data/'.$shop_code.'/is_active');
				echo $form->field('/shop_data/'.$shop_code.'/label');
				echo $form->field('/shop_data/'.$shop_code.'/description');

				if($form->fieldExists('/shop_data/'.$shop_code.'/bool_yes_description')) {
					echo $form->field('/shop_data/'.$shop_code.'/bool_yes_description');
				}

				echo $form->field('/shop_data/'.$shop_code.'/url_param');
				echo $form->field('/shop_data/'.$shop_code.'/units');
				?>
			</fieldset>

			<fieldset>
				<legend class="sub"><?=Tr::_('SEO')?></legend>
				<?php
				echo $form->field('/shop_data/'.$shop_code.'/seo_h1');
				echo $form->field('/shop_data/'.$shop_code.'/seo_h1_strategy');
				echo $form->field('/shop_data/'.$shop_code.'/seo_title');
				echo $form->field('/shop_data/'.$shop_code.'/seo_title_strategy');
				echo $form->field('/shop_data/'.$shop_code.'/seo_description');
				echo $form->field('/shop_data/'.$shop_code.'/seo_description_strategy');
				?>
			</fieldset>
			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach;



	echo $form->end();
echo $this->render('lj_end');