<?php
namespace JetShop;

use Jet\Mvc_View;
/**
 * @var Mvc_View $this
 * @var Order $order
 */

$order = $this->getRaw('order');

$payment_method = $order->getPaymentMethod();
$delivery_method = $order->getDeliveryMethod();

$show_delivery = true;

if($delivery_method->isEDelivery()) {
	$show_delivery = false;
}

?>


<table width="100%" cellspacing="0" cellpadding="0" style="font-size:13px;">
	<tr>
		<td>Dobrý den,<br /><br />Vaše objednávka číslo <strong><?=$order->getId()?></strong> byla zaznamenána a o dalším průběhu Vás budeme informovat.<br /><br /><br /></td>
	</tr>
</table>
