<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\MVC_View;
use Jet\Form;
use JetApplication\Marketing_PromoAreaDefinition;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Marketing_PromoAreaDefinition     $item
 */

$form = $this->getRaw('form');
$item = $this->getRaw('item');


