<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_messages;
use JetApplication\Category;
use JetApplication\Product;

/**
 * @var MVC_View     $this
 * @var Listing      $listing
 * @var Listing_Operation_Categorize $operation
 * @var Product[] $products
 */
$listing = $this->getRaw('listing');
$operation = $this->getRaw('operation');
$products = $this->getRaw('products');

$category = $operation->getCategory();
$error = $operation->getErrorMessage();
?>


<input type="hidden" name="category_id" id="category_id">

<?php if($error): ?>
	<?=UI_messages::createDanger($error)?>
<?php endif; ?>

<label><?=Tr::_('Select category:')?></label>
<?=Category::renderSelectCategoryWidget("$('#category_id').val(selected_item.id)", $category ? $category->getId() : 0 )?>

<br>
<?=UI::button_save(Tr::_('Categorize'))?>
<br><br><br><br><br><br><br><br><br><br>

