<?php
namespace JetShopModule\Exports\GoogleShopping;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;use Jet\UI;
use Jet\UI_button;
use JetShop\Category;
use JetShop\Parametrization_Property;

/**
 * @var MVC_View   $this
 * @var ?GoogleCategory $export_category
 * @var Form $category_form
 * @var Form $param_form
 * @var Category $category
 */

$category = $this->getRaw('category');
$category_form = $this->getRaw('category_form');
$export_category = $this->getRaw('export_category');

$category_form->setDefaultLabelWidth( [Form::LJ_SIZE_MEDIUM => 2] );
$category_form->setDefaultFieldWidth( [Form::LJ_SIZE_MEDIUM => 4] );

$param_form = $this->getRaw('param_form');
$param_form->setDefaultLabelWidth( [Form::LJ_SIZE_MEDIUM => 2] );
$param_form->setDefaultFieldWidth( [Form::LJ_SIZE_MEDIUM => 4] );


$dialog = UI::dialog('select_google_category', Tr::_('Select Google category'), 500);
?>
<script type="text/javascript">
	let googleCategorySelect = {
		openDialog: function() {
			$('#select_google_category').modal('show');
		},
		select: function(id) {
			$('#select_google_category_categories').load('<?=Http_Request::currentURI()?>&google_category='+id);
		},

		confirm: function (id, name) {
			$('#google_cate_settings__export_category').val(id);
			$('#selected_google_category_name').html(name);
			$('#select_google_category').modal('hide');
		}
	};
</script>

<h2><?=Tr::_('Category')?></h2>
<?=$category_form->start()?>
	<?=$category_form->field('export_category')?>
	<div class="row">
		<label class="col-form-label col-md-2 text-right"><?=Tr::_('Google category:')?></label>
		<div class="col-md-10">
			<?=UI::button(Tr::_('Select category'))
				->setIcon('folder-open')
				->setClass('info')
				->setSize(UI_button::SIZE_SMALL)
				->setOnclick('googleCategorySelect.openDialog()')?>


			<span id="selected_google_category_name" class="badge badge-light"><?=$export_category?$export_category->getFullName():''?></span>
		</div>
	</div>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-10" style="padding: 10px;">
			<?=UI::button_save()?>
		</div>
	</div>
<?=$category_form->end()?>

<?=$dialog->start()?>
	<div style="height: 400px;overflow: auto;" id="select_google_category_categories">
		<?=$this->render('category_settings/dialog/categories');?>
	</div>
<?=$dialog->end()?>
<hr>





<h2><?=Tr::_('Parametrization')?></h2>

<?=$param_form->start()?>
<?php foreach( $category->getParametrizationGroups() as $p_group ):
	if(!count($p_group->getProperties())) {
		continue;
	}
	?>
	<div class="row">
		<div class="col-md-4"><b><?=$p_group->getShopData()->getLabel()?></b></div>
	</div>
	<?php foreach($p_group->getProperties() as $p_property):
		$field = $param_form->field('g'.$p_group->getId().'-p'.$p_property->getId());

		$field->label()->addCustomCssClass('text-right');

		echo $field;

		if($p_property->getType()==Parametrization_Property::PROPERTY_TYPE_OPTIONS):
			foreach($p_property->getOptions() as $p_option):

				$field = $param_form->field('g'.$p_group->getId().'-p'.$p_property->getId().'-o'.$p_option->getId());
				?>
				<div class="row">
					<div class="col-md-2"></div>
					<?=$field->label()?>
				</div>
				<div class="row">
					<div class="col-md-2"></div>
					<div class="col-md-4"><?=$field->input()?></div>
				</div>
				<?php
			endforeach;
		endif;
		?>
		<br>
		<?php
	endforeach;
endforeach; ?>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-4">
			<?=UI::button_save()?>
			<br><br><br>
		</div>
	</div>

<?=$param_form->end()?>