<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\MoneyRefunds;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\MoneyRefund;

/**
 * @var MVC_View $this
 * @var MoneyRefund $item
 */

$item = $this->getRaw('item');

echo Admin_Managers::MoneyRefund()->showMoneyRefundStatus( $item );
