<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use JetApplication\Brand_ShopData;
use JetApplication\ProductListing;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');


$filter = $listing->getFilter()->getBrandsFilter();
if(!$filter->getIsActive()) {
	return;
}

$brand_ids = $filter->getSelectedBrandIds();


$brands = Brand_ShopData::getActiveList( $brand_ids );

foreach($brands as $brand): ?>
	<button
		type="button"
		onclick="listing.filter.brands.cancel(<?=$brand->getId()?>)"
		class="btn btn-xs btn-info"
	><i class="fa-regular fa-circle-xmark"></i> <?=$brand->getName()?></button>
<?php endforeach;
