<?php
namespace JetApplicationModule\Shop\Catalog;

use Jet\MVC_View;
use Jet\Tr;
use JetApplication\ProductListing;
use JetApplication\Shop_Managers;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');

$filter = $listing->getFilter()->getPriceFilter();
if(!$filter->getIsActive()) {
	return;
}

$min = $filter->getMinPrice();
$max = $filter->getMaxPrice();

$min = $min?:$listing->getInitialMap()->getMinPrice();
$max = $max?:$listing->getInitialMap()->getMaxPrice();


?>
	<button
		type="button"
		onclick="listing.filter.price.cancel()"
		class="btn btn-xs btn-info"
	>
		<i class="fa-regular fa-circle-xmark"></i>
		<?=Tr::_('Price:')?>
		<?=Shop_Managers::PriceFormatter()->formatWithCurrency($min)?> - <?=Shop_Managers::PriceFormatter()->formatWithCurrency($max)?>
	</button>
