<?php
namespace JetApplicationModule\EShop\ShoppingCart;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Pricelists;
use JetApplication\EShop_Managers;
use JetApplication\EShop_Pages;

$cart = EShop_Managers::ShoppingCart()->getCart();

$shopping_cart_status_dialog = UI::dialog('shopping-cart-status-dialog', UI::icon('shopping-cart').' '.Tr::_('Shopping cart'));


echo UI::button( '&nbsp;'.$cart->getNumberOfUnits() )->setIcon('shopping-cart')->setClass(UI_button::CLASS_LIGHT)->setOnClick("dialog.open('shopping-cart-status-dialog');");
?>

<?=$shopping_cart_status_dialog->start()?>

	<?php if($cart->getNumberOfUnits()>0): ?>
			<?php foreach($cart->getItems() as $item):
				$product = $item->getProduct();
				$mu = $product->getMeasureUnit();
				?>
			<div class="item">
				<div class="image">
					<img src="<?=$product->getImageThumbnailUrl( 0, 50, 50)?>"/>
				</div>
				<div class="name">
					<a href="<?=$product->getURL()?>"><?=$product->getFullName()?></a>
				</div>
				<div class="price-per-unit">
					<?=$item->getNumberOfUnits()?> <?=$mu?->getName()?> x <?=EShop_Managers::PriceFormatter()->formatWithCurrency($item->getProduct()->getPrice( Pricelists::getCurrent() ))?>
				</div>
				<div class="total">
					<?=EShop_Managers::PriceFormatter()->formatWithCurrency($item->getAmount())?>
				</div>
			</div>
			
			<?php endforeach; ?>

		<div class="buttons">
			<?=UI::button()->setClass('success')->setUrl(
				EShop_Pages::ShoppingCart()->getURL()
			)->setLabel(Tr::_('Proceed to checkout')
			)?>
			
		</div>
	<?php else: ?>
		<b><?=Tr::_('Shopping cart is empty');?></b>
	<?php endif; ?>

<?=$shopping_cart_status_dialog->end()?>

