<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\ShoppingCart;


use Jet\UI;
use Jet\UI_dialog;

$dialog = UI::dialog('shopping_cart_popup', '', UI_dialog::SIZE_LARGE);

echo $dialog->start();
?>
	<div id="shopping_cart_popup_content"></div>
<?php
echo $dialog->end();
