<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\ShoppingCart;


use Jet\MVC_View;

/**
 * @var MVC_View $this
 */
?>
<div id="shopping_cart_page">
	<div id="shopping-cart">
		<?=$this->render('shopping_cart_page/shopping_cart')?>
	</div>
</div>