<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Marketing\Banners;


use Jet\Http_Request;
use Jet\UI;
use JetApplication\Application_Service_Admin;

use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use JetApplication\Marketing_Banner;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Marketing_Banner   $item
 */
$form = $this->getRaw( 'form' );
$item = $this->getRaw( 'item' );
$group = $item->getGroup();

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 2,
	Form_Renderer::LJ_SIZE_LARGE => 1
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 8,
	Form_Renderer::LJ_SIZE_LARGE => 8
] );

require 'select.phtml';
?>


<?=$form->start()?>

<div class="toolbar" id="main-toolbar">
	<?=UI::button_goBack()->setUrl(Http_Request::currentURI(unset_GET_params: ['create']))?>
	&nbsp;&nbsp;
	<?=UI::button_save()->setOnclick("$('#".$form->getId()."').submit();")?>
</div>


<div id="main-col">
	<?=Application_Service_Admin::EntityEdit()->renderEntityFormCommonFields( $form );?>
	
	<?=$form->field('active_from')?>
	<?=$form->field('active_till')?>
	<?php if($group->getHasText()):
		echo $form->field('text');
		if($group->getHasColor()):
			echo $form->field('text_color');
		endif;
	endif; ?>
	<?=$form->field('URL')?>
	<?=$form->field('nofollow')?>
	<?=$form->field('open_in_new_window')?>

</div>

<?=$form->end()?>
