<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Marketing\Banners;


use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI_tabs;
use JetApplication\EShops;
use JetApplication\EShop;

/**
 * @var MVC_View   $this
 * @var UI_tabs $tabs
 * @var ?EShop $selected_eshop
 */
$tabs = $this->getRaw('tabs');

$selected_eshop = $this->getRaw('selected_eshop')?:null;
$selected_eshop_key = $selected_eshop?->getKey();

?>

<?php if( EShops::isMultiEShopMode() ): ?>
	<div style="display: flex;align-items: center;margin: 10px;">
		<div style="padding: 5px;width: 150px;"><b><?=Tr::_('Shop:')?></b></div>
		
		<?php foreach( EShops::getListSorted() as $eshop):
			if($eshop->getKey()==$selected_eshop_key): ?>
				<div style="padding: 5px"><b class="btn btn-success"><?=$eshop->getName()?></b></div>
			<?php else:  ?>
				<div style="padding: 5px"><a href="<?=Http_Request::currentURI(set_GET_params: ['eshop'=>$eshop->getKey()], unset_GET_params: ['do_it', 'price_list'])?>" class="btn btn-light"><?=$eshop->getName()?></a></div>
			<?php endif;
		endforeach; ?>
	</div>
<?php endif; ?>

<?=$tabs?>
