<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\ProductReviews;


use Jet\Locale;
use Jet\MVC_View;
use Jet\Form;
use JetApplication\Admin_Managers;
use JetApplication\ProductReview;


/**
 * @var MVC_View $this
 * @var Form     $form
 * @var ProductReview $item
 */

$form = $this->getRaw('form');
$item = $this->getRaw('item');

$form->field('positive_characteristics')->input()->addCustomCssStyle('height:200px');
$form->field('negative_characteristics')->input()->addCustomCssStyle('height:200px');
$form->field('summary')->input()->addCustomCssStyle('height:400px');
$form->field('our_comments')->input()->addCustomCssStyle('height:400px');



?>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		
		<div class="card card-body">
			<?=$item->getEshop()->getName()?> / <?=Locale::dateAndTime($item->getCreated())?>
			<div style="padding: 10px;">
				<?=Admin_Managers::Product()->renderItemName( $item->getProductId() ) ?>
			</div>
			
			<?=$item->getStatus()->showAdmin()?>
		</div>
		<br>
	</div>
</div>

<?=$form->field('author_name')?>
<?=$form->field('author_email')?>

<?=$form->field('positive_characteristics')?>
<?=$form->field('negative_characteristics')?>
<?=$form->field('summary')?>

<?=$form->field('our_comments')?>

<br><br><br>
<?=Admin_Managers::EntityEdit()->renderEventHistory($item, true)?>