<?php
namespace JetApplicationModule\Admin\OrderDispatch\DoDispatch;

use Jet\Http_Request;
use Jet\Mvc_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\OrderDispatch;

/**
 * @var Mvc_View $this
 * @var OrderDispatch $dispatch
 */

$dispatch = $this->getRaw('dispatch');


echo UI::button(Tr::_('Confirm cancellation'))
	->setUrl( Http_Request::currentURI(['action'=>'confirm_cancellation']) )
	->setClass( UI_button::CLASS_INFO );


