<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\OrderDispatch\DoDispatch;


use Jet\Http_Request;
use Jet\Mvc_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\OrderDispatch;

/**
 * @var Mvc_View $this
 * @var OrderDispatch $dispatch
 */

$dispatch = $this->getRaw('dispatch');

echo UI::button(Tr::_('Create consignment'))->setUrl( Http_Request::currentURI(['action'=>'create_consignment']) )
		->setClass( UI_button::CLASS_SUCCESS );


echo UI::button(Tr::_('Rollback - reopen and edit again'))->setUrl( Http_Request::currentURI(['action'=>'rollback']) );
echo UI::button(Tr::_('Rollback - reopen and edit again (ignore errors)'))->setUrl( Http_Request::currentURI(['action'=>'rollback','ignore_error'=>true]) );
