<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\TODO;

use Jet\Auth;
use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Auth_Administrator_User;

/**
 * @var MVC_View $this
 * @var Item[] $items
 */

$entity_type = $this->getRaw('entity_type');
$entity_id = $this->getRaw('entity_id');


$items = $this->getRaw('items');

$items = Item::getItems( $entity_type, $entity_id );

?>

<?php foreach($items as $item):
	
	$edit_form = $item->getEditForm();
	$edit_form->renderer()->addJsAction('onsubmit', "TODO.editSave({$item->getId()});return false;");
	
	?>
<div class="card card-body" style="margin-top: 10px;margin-bottom: 10px;">
	<div id="todo_item_detail_<?=$item->getId()?>">
		<div style="display: grid;grid-template-columns: 30px 1fr 0.8fr 1fr 30px;margin: 5px;align-items: center;gap: 10px;">
			<div>
				<?=UI::button( ' ' )
					->setOnClick("TODO.edit({$item->getId()});")
					->setIcon('edit')
					->setClass(UI_button::CLASS_LIGHT)
					->setSize(UI_button::SIZE_EXTRA_SMALL)?>
			</div>
			<?=$item->getPriorityTag()?>
			<div style="opacity: 0.4;font-size: 0.8rem"><?=Locale::dateAndTime( $item->getCreatedDateTime() )?></div>
			<div style="opacity: 0.7;font-size: 0.8rem"><?=$item->getCreatedByUserName()?></div>
			<div>
				<?=UI::button( ' ' )
					->setOnClick("TODO.done({$item->getId()});")
					->setIcon('check')
					->setClass(UI_button::CLASS_SUCCESS)
					->setSize(UI_button::SIZE_EXTRA_SMALL)?>
			</div>
		</div>
		
		<?=nl2br( $item->getTask() )?>

		<div style="opacity: 0.5;padding: 10px;">
			<?php
			if($item->getVisibleFor()=='ALL'):
				echo Tr::_('Visible for all');
			elseif($item->getVisibleFor()=='|'.Auth::getCurrentUser()->getId().'|'):
				echo Tr::_('My private');
			else:
				$visible_form = trim( $item->getVisibleForm(), '|' );
				$visible_form = explode( '|', $visible_form );
				
				foreach( $visible_form as $user_id ):
					$user = Auth_Administrator_User::get( $user_id );
					if(!$user) {
						continue;
					}
					
					echo trim($user->getName())? $user->getName() : $user->getUsername();
					echo '&nbsp;&nbsp;&nbsp;';
				endforeach;
			endif;
			?>
		</div>
	</div>

	<div id="todo_item_edit_<?=$item->getId()?>" style="display: none;">
		<div>
			<?=UI::button( ' ' )
				->setOnClick("TODO.edit({$item->getId()});")
				->setIcon('xmark')
				->setClass(UI_button::CLASS_LIGHT)
				->setSize(UI_button::SIZE_EXTRA_SMALL)?>
		</div>
		<?php
		
		echo $edit_form->start();
		
		echo $edit_form->field('priority');
		echo $edit_form->field('visible_for');
		echo $edit_form->field('task');
		
		echo UI::button_save();
		echo $edit_form->end();
		
		?>
	</div>

</div>
<?php endforeach; ?>


