<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 */

$cash_desk = CashDesk::get();

$delivery_method = $cash_desk->getSelectedDeliveryMethod();

$this->setVar('delivery_method', $delivery_method);
?>

<div class="method-has-been-selected">
	<div><b><?= Tr::_('Delivery method') ?></b></div>
	<div>
		<?=UI::button(Tr::_('Change selection'))->setOnclick("CashDesk.delivery.back();")->setClass('link')->setSize(UI_button::SIZE_SMALL)?>
		<?= $delivery_method->getTitle() ?>
	</div>
	
	<div>
	<?php if($delivery_method->isPersonalTakeover()):
		$place = $cash_desk->getSelectedPersonalTakeoverPlace();
		?>
			<b><?=$place->getName()?></b><br>
			<?=$place->getStreet()?><br>
			<?=$place->getZip()?>  <?=$place->getTown()?>
	<?php endif; ?>
	</div>

	<div><?=$this->render('delivery/price')?></div>
</div>
