<?php
namespace JetApplication;

use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 */

$cash_desk = CashDesk::get();

$delivery_method = $cash_desk->getSelectedDeliveryMethod();

$dm_shd = $delivery_method->getShopData($cash_desk->getShop());

$this->setVar('delivery_method', $delivery_method);
?>
<br/>
<div class="card">

	<div class="card-body bg-light">
		<div><b><?= Tr::_('Delivery method') ?></b></div>
		<div><?= $dm_shd->getTitle() ?> </div>

		<?php if($delivery_method->isPersonalTakeover()):
			$place = $cash_desk->getSelectedPersonalTakeoverPlace();
			?>
			<div style="padding: 10px;font-size: 10px;">
				<b><?=$place->getName()?></b><br>
				<?=$place->getStreet()?><br>
				<?=$place->getZip()?>  <?=$place->getTown()?>
			</div>
		<?php endif; ?>

		<div><?=$this->render('delivery/price')?></div>

		<?=UI::button(Tr::_('Change selection'))->setOnclick("CashDesk.delivery.back();")->setClass('link')->setSize(UI_button::SIZE_SMALL)?>
	</div>
</div>
