<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\MVC_View;
use JetApplication\Delivery_Method_ShopData;
use JetApplication\Shop_Managers;

/**
 * @var MVC_View $this
 * @var Delivery_Method_ShopData $method
 */

$cash_desk = CashDesk::get();

$method = $this->getRaw('delivery_method');

?>
<div class="price">
	<?php if($method->getDefaultPrice()!=$method->getPrice()):?>
		<div class="price-standard"><?=Shop_Managers::PriceFormatter()->formatWithCurrency($method->getDefaultPrice());?></div>
	<?php endif; ?>
	<div class="price-final"><?=Shop_Managers::PriceFormatter()->formatWithCurrency($method->getPrice());?></div>
</div>