<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Shop_Managers;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');
$pricelist = $cash_desk->getPricelist();

$step = $cash_desk->getCurrentStep();
?>


<dialog id="select_personal_takeover_point_dialog" tabindex="-1" style="width: 100%;height: 100vh">

	<div class="dialog-header">
		<h5><?=Tr::_('Selected personal takeover place')?></h5>
		<button type="button" aria-label="Close" onclick="dialog.close('select_personal_takeover_point_dialog')">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
	<div class="dialog-body" id="select_personal_takeover_point_dialog_body">
		<div id="personal_takeover_filter" style="display: grid;grid-template-columns: 1fr; grid-template-rows: 40px 1fr 2fr;">
			<div>
				<b><?=Tr::_('Where do you want to send the package?')?></b>
				
				<div style="display: grid;grid-template-columns: 1fr 40px;grid-template-rows: 40px;">
					<div>
						
						<input type="text" id="select_personal_takeover_point_search_input" placeholder="" style="width: 100%;height: 40px;" />
						<div style="position: relative">
							<div  id="select_personal_takeover_point_search_result" class="whisperer-items" style="display: none;">
							</div>
						</div>
						
					</div>
					<div>
						<?=UI::button(' ')->setOnClick("CashDesk.delivery.personalTakeover.resetSearch();")->setIcon('xmark');?>
					</div>
				</div>
				
			</div>

			<div>
			</div>
			
			
			<div>
					<b><?=Tr::_('Available delivery methods')?></b>
					<?php foreach($cash_desk->getAvailableDeliveryMethods() as $method):
						if(!$method->isPersonalTakeover()) {
							continue;
						}
						?>
						<div
							style="display: grid;grid-template-columns: 20px 50px 1fr 100px;align-items: center;gap: 10px;margin: 10px;"
							onclick="CashDesk.delivery.personalTakeover.selectMethod(<?=$method->getId()?>)"
						>
							<div>
								<input
									type="checkbox"
									value="<?=$method->getId()?>" checked
									class="personal_takeover_method"
									onchange="this.checked=!this.checked;CashDesk.delivery.personalTakeover.actualizeMethodsSelection();"
								>
							</div>
							<div>
								<?php if(($img=$method->getIcon1ThumbnailUrl(50, 50))): ?>
									<img src="<?=$img?>" style="padding: 5px;">
								<?php endif; ?>
							</div>
							<div><?=$method->getTitle()?></div>
							<div><?=Shop_Managers::PriceFormatter()->formatWithCurrency( $method->getPrice($pricelist), $pricelist->getCurrency() )?></div>
						</div>
					<?php endforeach; ?>
					
				
			</div>
		</div>
		<div id="personal_takeover_map">
		</div>
	</div>

</dialog>

<dialog id="select_personal_takeover_selected_point_dialog" tabindex="-1">
	<div class="dialog-header">
		<h5></h5>
		<button type="button" aria-label="Close" onclick="dialog.close('select_personal_takeover_selected_point_dialog')">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
	<div class="dialog-body" id="personal_takeover_point">
	
	</div>

</dialog>

