<?php
namespace JetApplicationModule\Shop\Complaints;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Product_ShopData;

/**
 * @var MVC_View   $this
 * @var Form $enter_problem_form
 * @var Product_ShopData $product
 */

$enter_problem_form = $this->getRaw('enter_problem_form');
$product = $this->getRaw('product');
$enter_problem_form->field('problem_description')->input()->addCustomCssStyle('width:800px;height:300px');

?>
<?=$enter_problem_form->start()?>
	
	<div class="card" style="margin: 10px;">
		<div class="card-body">
			<h5 class="card-title"><?=Tr::_('New complaint')?></h5>
			

			<div style="display: grid;grid-template-columns: 60px 1fr;gap: 5px;margin: 10px;align-items: center">
				<div>
					<?php if($product->getImg(0)): ?>
						<a href="<?=$product->getURL()?>"><img src="<?=$product->getImgThumbnailUrl(0, 50, 50)?>"></a>
					<?php endif; ?>
				</div>
				<div><a href="<?=$product->getURL()?>"><?=$product->getName()?></a></div>
			</div>

			
			
			<div style="display: grid;;gap:10px;grid-template-columns: 250px 400px;">
				<?=$enter_problem_form->field('problem_description')?>
				<div></div>
				<div>
					<?=UI::button( Tr::_('Continue') )->setType(UI_button::TYPE_SUBMIT)->setClass(UI_button::CLASS_PRIMARY)?>
				</div>
			</div>
		</div>
	</div>

<?=$enter_problem_form->end()?>