<?php

use Jet\UI_button;
use Jet\UI;
use Jet\MVC_View;
use Jet\UI_icon;

/**
 * @var MVC_View $this
 * @var UI_button $b
 */
$b = $this->getRaw( 'element' );

if( !$b->getClass() ) {
	$b->setClass( UI_button::CLASS_LIGHT );
}


$label = trim($b->getLabel());
$label = $label ? '&nbsp;'.$label : '';
$icon = $b->getIcon() ? UI::icon( $b->getIcon() )->setSize( UI_icon::SIZE_NORMAL) : '';

$b->setBaseCssClass( 'btn btn-'.$b->getClass().' btn-'.$b->getSize() );

if( $b->getUrl() ):
	?><a href="<?= $b->getUrl() ?>" <?=$b->renderTagAttributes()?>>
	<div class="btn-content">
		<?=$icon?>
		<?=$label?>
	</div>
	</a> <?php
else:
	?><button type="<?= $b->getType() ?>" <?=$b->renderTagAttributes()?>>
		<div class="btn-content">
			<?=$icon?>
			<?=$label?>
		</div>
	</button> <?php
endif;
