<?php

use Jet\IO_File;
use Jet\UI_icon;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var UI_icon $i
 */
$i = $this->getRaw( 'element' );

$res = '';

$style = '';


$i->setBaseCssClass('icon icon-'. $i->getSize() );
$i->setCustomTagAttribute('title', $i->getTitle());

$icon = $i->getIcon();
if( str_contains( $icon, '.' ) ){
	return;
}

$icon_path = __DIR__.'/icons/'.$icon.'.svg';


if(!IO_File::isReadable($icon_path)) {
	echo 'missing icon:'.$icon;
	return;
}

$svg_icon = IO_File::read( $icon_path );

?>
<span <?=$i->renderTagAttributes()?> style="background-image:url('data:image/svg+xml;base64,<?=base64_encode($svg_icon)?>');"></span>