<?php
namespace JetApplicationModule\Shop\ShoppingCart;
use Jet\Tr;
use Jet\UI;
use JetApplication\Shop_Managers;

$cart = Shop_Managers::ShoppingCart()->getCart();
?>
<div class="dropdown" style="display: inline-block">
	<button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		<?=UI::icon('shopping-cart')?> <?=$cart->getQuantity()?>
	</button>
	<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
		<div class="dropdown-item" style="padding-bottom: 10px;">
			<?php if($cart->getQuantity()>0): ?>
				<table class="table table-striped">
					<?php foreach($cart->getItems() as $item):
						$product = $item->getProduct();
						?>
					<tr>
						<td>
							<img src="<?=$product->getImgThumbnailUrl( 0, 50, 50)?>"/>
						</td>
						<td>
							<a href="<?=$product->getURL()?>"><?=$product->getFullName()?></a>
						</td>
						<td>
							<span class="small"><?=$item->getQuantity()?>x <?=Shop_Managers::PriceFormatter()->formatWithCurrency($item->getProduct()->getPrice())?></span><br/>
							<b><?=Shop_Managers::PriceFormatter()->formatWithCurrency($item->getAmount())?></b>
						</td>
					</tr>
					<?php endforeach; ?>
				</table>

				<?=UI::button()->setClass('success')->setUrl(
						Shop_Managers::ShoppingCart()->getCartPageURL()
					)->setLabel(Tr::_('Proceed to checkout')
				)?>
			<?php else: ?>
				<b><?=Tr::_('Shopping cart is empty');?></b>
			<?php endif; ?>
		</div>
	</div>
</div>

