<?php
namespace JetShop;
use Jet\Tr;
use Jet\UI;

$cart = ShoppingCart::get();
?>
<div class="dropdown" style="display: inline-block">
	<button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		<?=UI::icon('shopping-cart')?> <?=$cart->getQuantity()?>
	</button>
	<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
		<div class="dropdown-item" style="padding-bottom: 10px;">
			<?php if($cart->getQuantity()>0): ?>
				<table class="table table-striped">
					<?php foreach($cart->getItems() as $item):
						$product = $item->getProduct();
						?>
					<tr>
						<td>
							<img src="<?=$product->getImageThumbnailUrl(50, 50)?>"/>
						</td>
						<td>
							<a href="<?=$product->getURL()?>"><?=$product->getName()?></a>
						</td>
						<td>
							<span class="small"><?=$item->getQuantity()?>x <?=Price::formatWithCurrency($item->getPricePerItem())?></span><br/>
							<b><?=Price::formatWithCurrency($item->getAmount())?></b>
						</td>
					</tr>
					<?php endforeach; ?>
				</table>

				<?=UI::button()->setClass('success')->setUrl(ShoppingCart::getCartPageURL())->setLabel(Tr::_('Proceed to checkout'))?>
			<?php else: ?>
				<b><?=Tr::_('Shopping cart is empty');?></b>
			<?php endif; ?>
		</div>
	</div>
</div>

