<?php

use JetApplication\Shop_Managers;
?>
<script>
	const ShoppingCart = {
		base_URL: '<?=Shop_Managers::ShoppingCart()->getCartPageURL()?>',

		buy: function( product_id, qty ) {

			$.ajax({
				type: "GET",
				url: ShoppingCart.base_URL+'?buy='+product_id+'&gty='+qty,
				dataType:'json',
				beforeSend: function(){
				},
				success: function( response ) {

					ShoppingCart._handleResponse( response );

					if(response['ok']) {
						$('#shopping_cart_popup').modal('show');
					}
				},
				complete: function(){
				}
			});
		},


		increment: function( product_id ) {
			let qty = $('#cart_quantity_'+product_id).val();
			qty++;

			ShoppingCart.setQty( product_id, qty );
		},

		decrement: function( product_id ) {
			let qty = $('#cart_quantity_'+product_id).val();
			qty--;

			ShoppingCart.setQty( product_id, qty );
		},

		setQty: function(product_id, qty ) {
			$.ajax({
				type: "GET",
				url: ShoppingCart.base_URL+'?set_qty='+product_id+'&gty='+qty,
				dataType:'json',
				beforeSend: function(){
				},
				success: function( response ) {
					ShoppingCart._handleResponse( response );
				},
				complete: function(){
				}
			});
		},

		remove: function( product_id ) {
			$.ajax({
				type: "GET",
				url: ShoppingCart.base_URL+'?remove='+product_id,
				dataType:'json',
				beforeSend: function(){
				},
				success: function( response ) {
					ShoppingCart._handleResponse( response );
				},
				complete: function(){
				}
			});
		},


		_handleResponse: function (response) {
			for( let id in response['snippets'] ) {
				$('#'+id).html(response['snippets'][id]);
			}

			if(!response['ok']) {
				//TODO:
			}
		}

	};
</script>