<?php
namespace JetApplicationModule\Shop\ShoppingCart;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\ShoppingCart_Item;
use JetApplication\Shop_Managers;

/**
 * @var MVC_View $this
 * @var ShoppingCart_Item $item
 */

$item = $this->getRaw('new_item');

$product = $item->getProduct();
?>

<table>
	<tr>
		<td rowspan="2">
			<?php if(($img=$product->getImgThumbnailUrl( 0, 100, 100))): ?>
				<img src="<?=$img?>"/>
			<?php endif; ?>
		</td>
		<td>
			<a href="<?=$product->getURL()?>"><?=$product->getName()?></a>
		</td>
	</tr>
	<tr>
		<td><?=$product->getShortDescription()?></td>
	</tr>
</table>

<div class="modal-footer">
	<?=UI::button()->setUrl( Shop_Managers::ShoppingCart()->getCartPageURL() )->setLabel(Tr::_('Proceed to checkout'))->setClass('success')?>
</div>