<?php
namespace JetShop;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;

/**
 * @var MVC_View $this
 * @var ShoppingCart_Item $new_item
 */

$item = $this->getRaw('new_item');

$product = $item->getProduct();
?>

<table>
	<tr>
		<td rowspan="2">
			<img src="<?=$product->getImageThumbnailUrl(100, 100)?>"/>
		</td>
		<td>
			<a href="<?=$product->getURL()?>"><?=$product->getName()?></a>
		</td>
	</tr>
	<tr>
		<td><?=$product->getShortDescription()?></td>
	</tr>
</table>

<div class="modal-footer">
	<?=UI::button()->setUrl(ShoppingCart::getCartPageURL())->setLabel(Tr::_('Proceed to checkout'))->setClass('success')?>
</div>