<?php
namespace JetApplication;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;

/**
 * @var MVC_View $this
 */

$dm_code = Discounts::getActiveModule('Order.Discounts.Code');
?>
<div class="row">
	<div class="col-md-2">
	</div>
	<div class="col-md-8">
		<div id="shopping_cart">
			<?=$this->render('shopping_cart_page/items')?>
		</div>

		<div class="container-fluid">
			<div class="row">
				<div class="col-md-8">

				</div>
				<div class="col-md-4 text-right">
					<?php if($dm_code): ?>
						<?=$dm_code->ShoppingCart_handle()?>
					<?php endif; ?>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12 text-right">
					<?=UI::button(Tr::_('Order'))->setUrl(CashDesk::getCashDeskPageURL())->setClass('success')?>
				</div>
			</div>
		</div>



	</div>
	<div class="col-md-2">
	</div>
</div>
