<?php
namespace JetShopModule\Admin\Delivery\Classes;

use JetShop\Delivery_Class;
use Jet\UI;
use Jet\Mvc_View;
use Jet\Form;
use JetShop\Delivery_Kind;
use JetShop\Delivery_Method;

/**
 * @var Mvc_View $this
 * @var Form     $form
 * @var Delivery_Class     $delivery_class
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 1 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 4 ] );


$_delivery_methods = Delivery_Method::getList();
$delivery_methods = [];

foreach(Delivery_Kind::getScope() as $kind=>$kind_title) {
	$delivery_methods[$kind] = [];
}

foreach($_delivery_methods as $dc) {
	$delivery_methods[$dc->getKind()][] = [
		'code' => $dc->getCode(),
		'name' => $dc->getInternalName()
	];
}

$form->field('kind')->input()->addJsAction('onchange', 'actualizeDeliveryMethods()');

$form->field('delivery_methods')->input()->addCustomCssStyle('height: 400px');

?>


<?=$form->start()?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()?>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=$form->field( 'internal_name' )?>
		<?=$form->field( 'code' )?>
		<?=$form->field( 'kind' )?>
		<?=$form->field( 'delivery_methods' )?>
		<?=$form->field( 'internal_description' )?>

	</div>
</div>

<?=$form->end()?>


<script type="text/javascript">
	const delivery_methods = <?=json_encode($delivery_methods)?>;

	function actualizeDeliveryMethods()
	{
		const kind = $('#edit_form__kind').val();
		const select = $('#edit_form__delivery_methods');
		const selected = select.val();

		let cnt = select[0].options.length;
		let i = 0;
		for(i=0; i<cnt;i++) {
			select[0].remove(0);
		}

		for(i=0; i<delivery_methods[kind].length;i++) {
			let option = new Option(delivery_methods[kind][i]['name'], delivery_methods[kind][i]['code'] );
			select[0].add( option );
		}

		select.val(selected);

	}

	actualizeDeliveryMethods();
</script>