<?php
namespace JetShopModule\Admin\Delivery\Classes;

use JetShop\Delivery_Class;
use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Delivery_Class     $delivery_class
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 1 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );



$form->field('delivery_methods')->input()->addCustomCssStyle('height: 400px');

?>


<?=$form->start()?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()?>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=$form->field( 'internal_name' )?>
		<?=$form->field( 'code' )?>
		<?=$form->field( 'delivery_methods' )?>
		<?=$form->field( 'internal_description' )?>

	</div>
</div>

<?=$form->end()?>

