<?php
namespace JetApplicationModule\Admin\Delivery\Classes;

use JetApplication\Delivery_Class;
use Jet\UI;
use Jet\UI_dataGrid;
use Jet\UI_button;

use Jet\Tr;
use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Form         $filter_form
 */
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );
$router = $this->getController()->getControllerRouter();


$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( Delivery_Class $item ) use ( $router ) {
		if( ( $edit_uri = $router->action('edit')->URI( $item->getCode() ) ) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;
		echo '&nbsp;';
		if( ( $delete_uri = $router->action('delete')->URI( $item->getCode() ) ) ):
			echo UI::button_delete()->setUrl( $delete_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;

	}
);
$c_edit->addCustomCssStyle( 'width:200px;' );


$grid->getColumn( 'internal_name' )->setRenderer(
	function( Delivery_Class $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getCode() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getInternalName();?></a>
		<?php
	}
);
$grid->getColumn( 'internal_name' )->addCustomCssStyle( 'width:400px;' );

$grid->getColumn( 'code' )->setRenderer(
	function( Delivery_Class $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getCode() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getCode();?></a>
		<?php
	}
);
$grid->getColumn( 'code' )->addCustomCssStyle( 'width:200px;' );



$grid->getColumn( 'kinds' )->setRenderer(
	function( Delivery_Class $item ) use ( $router ) {
		foreach($item->getKinds() as $kind) {
			echo $kind->getTitle().'<br>';
		}
	}
);
$grid->getColumn( 'kinds' )->addCustomCssStyle( 'width:200px;' );

$grid->getColumn( 'delivery_methods' )->setRenderer(
	function( Delivery_Class $item ) use ( $router ) {

		foreach($item->getDeliveryMethods() as $method) {
			echo $method->getInternalName().'<br>';
		}
	}
);

?>

<?=$filter_form->start()?>
<div class="row toolbar">
	<?php if( ( $add_uri = $router->action('add')->URI() ) ): ?>
		<div class="col-md-2 col-sm-12">
			<?=UI::button_create( Tr::_( 'Create a new Delivery Class' ) )->setUrl( $add_uri )?>
		</div>
	<?php endif; ?>

	<div class="col-md-3 col-sm-12">
		<?= $filter_form->field( 'search' )->input() ?>
	</div>
	<div class="col-md-4 col-sm-12">
	</div>

</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
