<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\CashDesk;


use Jet\MVC_View;
use JetApplication\Delivery_Method;
use JetApplication\Carrier_DeliveryPoint;
use JetApplication\EShop_Managers;

/**
 * @var MVC_View $this
 * @var Carrier_DeliveryPoint $point
 * @var Delivery_Method $method
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');
$pricelist = $cash_desk->getPricelist();

$c = $this->getInt('c');
$point = $this->getRaw('point');
$method = $this->getRaw('method');

$icon = '';
if($method->getIcon1()) {
	$icon = $method->getIcon1ThumbnailUrl(50, 50);
}
?>
<div
	data-id="<?=$method->getId()?>:<?=$point->getPointCode()?>"
	data-type="place"
	class="whisperer-item<?=($c==1?' whisperer-item-selected':'')?>"
>
	<div class="place_search_result_item">
		<div class="image">
			<?php if($icon): ?>
			<img src="<?=$icon?>" title="<?=$method->getTitle()?>" alt="<?=$method->getTitle()?>" />
			<?php endif; ?>
		</div>
		<div class="address">
			<?=$point->getName()?><br />
			<?=$point->getStreet()?><br />
			<?=$point->getZip()?>  <?=$point->getTown()?>
		</div>
		<div class="price">
			<?= EShop_Managers::PriceFormatter()->formatWithCurrency( $method->getPrice($pricelist), $pricelist )?>
		</div>
	</div>
</div>
