<?php
namespace JetShopModule\Admin\Catalog\Stickers;

use JetShop\Shops;
use JetShop\Sticker;
use Jet\Mvc_View;
use Jet\Form;
use Jet\Tr;
use Jet\UI;


/**
 * @var Mvc_View   $this
 * @var Form       $form
 * @var Sticker    $sticker
 */
$form = $this->getRaw( 'form' );

$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 8 ] );

$sticker = $this->getRaw( 'sticker' );

?>



<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()->setOnclick("$('#".$form->getId()."').submit();")?>
		<?php endif; ?>
	</div>
</div>

<div class="row">

	<div class="col-md-12" id="main-col">

		<?=$form->start()?>
		<?=$form->field( 'name' )?>

		<?php foreach(Shops::getList() as $shop):
			$shop_code = $shop->getCode();

			$shop_data = $sticker->getShopData( $shop_code );
			?>
			<?=$shop_data->renderShopDataBlock_start()?>

			<fieldset>
				<legend class="sub"><?=Tr::_('Main data')?></legend>

				<?=$form->field('/shop_data/'.$shop_code.'/is_active')?>

				<?=$form->field('/shop_data/'.$shop_code.'/name')?>
				<?=$form->field('/shop_data/'.$shop_code.'/second_name')?>
				<?=$form->field('/shop_data/'.$shop_code.'/description')?>
			</fieldset>

			<fieldset>
				<legend class="sub"><?=Tr::_('SEO')?></legend>
				<?=$form->field('/shop_data/'.$shop_code.'/seo_h1')?>
				<?=$form->field('/shop_data/'.$shop_code.'/seo_title')?>
				<?=$form->field('/shop_data/'.$shop_code.'/seo_description')?>
				<?=$form->field('/shop_data/'.$shop_code.'/seo_keywords')?>
				<?=$form->field('/shop_data/'.$shop_code.'/internal_fulltext_keywords')?>
			</fieldset>
			<?=$shop_data->renderShopDataBlock_end()?>
		<?php endforeach; ?>
		<?=$form->end()?>


	</div>
</div>

