<?php
namespace JetApplicationModule\Admin\Catalog\Stickers;

use Jet\Http_Request;

use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View   $this
 * @var Sticker    $sticker
 */
$sticker = $this->getRaw( 'sticker' );
$router = $this->getController()->getControllerRouter();

?>

<div class="col d-flex justify-content-center">

	<div class="card" style="margin-top:50px;">
		<div class="card-body">
			<p>
				<?=Tr::_( 'Do you really want to delete this sticker?' );?>
				<br/>
				<a href="<?=$router->action('edit')->URI( $sticker->getCode() );?>"
				   style="font-weight: bolder;font-size: 20px;"><?=$sticker->getInternalName();?></a>
			</p>

			<div style="display: inline-block;width: 50%">
				<?= UI::button_goBack() ?>
			</div>
			<div style="display: inline-block;width: 45%;text-align: right">
				<form action="<?= Http_Request::currentURI() ?>" method="post">
					<input type="hidden" name="delete" value="yes">
					<?= UI::button_delete()->setType( 'submit' ) ?>
				</form>
			</div>
		</div>
	</div>
</div>