<?php
namespace JetShopModule\Admin\Catalog\Stickers;

use Jet\Http_Request;
use JetShop\Sticker;

use Jet\UI;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View   $this
 * @var Sticker    $sticker
 */
$sticker = $this->getRaw( 'sticker' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( 'Do you really want to delete this sticker?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $sticker->getId() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$sticker->getName();?></a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>