<?php
namespace JetShopModule\Admin\Catalog\Stickers;

use Jet\Form;
use JetShop\Sticker;

use Jet\UI_dataGrid;
use Jet\UI;
use Jet\UI_button;

use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View        $this
 * @var UI_dataGrid     $grid
 * @var Form            $filter_form
 */
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );
$router = $this->getController()->getControllerRouter();



$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( Sticker $item ) use ( $router ) {
		if( ( $delete_uri = $router->action('delete')->URI( $item->getCode() ) ) ):
			echo UI::button_delete(' ')->setUrl( $delete_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;
		echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
		if( ( $edit_uri = $router->action('edit')->URI( $item->getCode() ) ) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;

	}
);
$c_edit->addCustomCssStyle( 'width:180px;' );


$grid->getColumn( 'internal_name' )->setRenderer(
	function( Sticker $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getCode() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getInternalName();?></a>
		<?php
	}
);

$grid->getColumn( 'code' )->addCustomCssStyle( 'width:220px;' );
$grid->getColumn( 'code' )->setRenderer(
	function( Sticker $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getCode() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getCode();?></a>
		<?php
	}
);



?>
<?=$filter_form->start()?>
<div class="row toolbar">
	<div class="col-xs-5 col-md-2">
		<?php if( ( $add_uri = $router->action('add')->URI() ) ): ?>
			<?=UI::button_create( Tr::_( 'Create a new Sticker' ) )->setUrl( $add_uri )?>
		<?php endif; ?>
	</div>
	<div class="col-xs-7 col-md-3">
		<?= $filter_form->field( 'search' )->input() ?>
	</div>
</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
