<?php
use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View $this
 * @var Form     $form
 */

$form = $this->getRaw('form');
?>
<?=$form->field( 'currency_code' )?>

<?=$form->field( 'is_virtual' )?>

<?=$form->field( 'address_name' )?>
<?=$form->field( 'address_street_no' )?>
<?=$form->field( 'address_town' )?>
<?=$form->field( 'address_zip' )?>
<?=$form->field( 'address_country' )?>

<?=$form->field( 'internal_email' )?>
<?=$form->field( 'internal_phone' )?>

<?=$form->field( 'public_email' )?>
<?=$form->field( 'public_phone' )?>
