<?php
namespace JetApplicationModule\Shop\ShoppingCart;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Product_ShopData;
use JetApplication\ShoppingCart;

/**
 * @var MVC_View $this
 * @var Product_ShopData $product
 * @var ShoppingCart $cart
 */

$product = $this->getRaw('product');
$cart = $this->getRaw('cart');

$gifts = $cart->getAvailableProductGifts( $product );
$mu = $product->getMeasureUnit();

$p_id = $product->getEntityId();

$delivery_info = $product->getDeliveryInfo();
?>
	<?php if( !$product->isVirtual() ): ?>
	<div class="availability">
		<?php if( $delivery_info->getNumberOfUnitsAvailable()>0 ): ?>
			<?=Tr::_('Availability:')?>
			<span class="availability_in_stock"><?=Tr::_('In stock')?></span>
		<?php else : ?>
			<?=Tr::_('Availability:')?>
			<span class="availability_<?=$delivery_info->getSituation()?>"><?=$delivery_info->getDeliveryInfoTextTranslated()?></span>
		<?php endif; ?>
	</div>
	<?php endif; ?>

	<?php if($delivery_info->allowToOrder()): ?>
		<div style="display: flex;gap: 5px;align-items: center;margin: 10px;">
			<div><input type="number" value="1" step="<?=$mu?->getNumberStep()??1?>" <?php if(!$mu?->isIsDecimalNumber()):?> oninput="this.value=(parseInt(this.value)||0)"<?php endif; ?> style="width: 60px" id="qty_<?=$product->getId()?>"></div>
			<div><?=$mu?->getName()?></div>
			<div><?=UI::button(Tr::_('Buy'))->setOnclick("ShoppingCart.buy({$p_id},document.getElementById('qty_{$p_id}').value);")->setClass(UI_button::CLASS_SECONDARY)->setSize(UI_button::SIZE_SMALL)?></div>
		</div>
		<?php


		if($gifts):
			?>
		<div style="padding: 10px">
			<b><?=Tr::_('Gift:')?></b>
			<br>
			
			<?php foreach($gifts as $gift): ?>
				<?=$gift->getGiftProduct()->getName();?><br>
			<?php endforeach; ?>
		</div>
		<?php
		endif;
	endif;