<?php
namespace JetApplicationModule\Shop\ShoppingCart;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Product_ShopData;

/**
 * @var MVC_View $this
 * @var Product_ShopData $product
 */

$product = $this->getRaw('product');

if(
	$product->getMeasureUnit()?->isIsDecimalNumber() ||
	!$product->getDeliveryInfo()->getAllowToOrderMore()
) {
	return;
}


echo UI::button(Tr::_('Buy'))->setOnclick('ShoppingCart.buy('.$product->getEntityId().',1);')->setClass(UI_button::CLASS_SECONDARY)->setSize(UI_button::SIZE_NORMAL);