<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Complaints;


use Jet\Locale;
use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use JetApplication\Complaint;
use JetApplication\EShop_Managers;
use JetApplication\Product_EShopData;

/**
 * @var MVC_View   $this
 * @var Form $edit_form
 * @var Product_EShopData $product
 * @var Complaint $complaint
 */

$complaint = $this->getRaw('complaint');
$edit_form = $this->getRaw('form');
$product = $complaint->getProduct();

echo EShop_Managers::CustomerSection()?->showMenu('complaints');
?>
<div class="customer-section-container">
<div class="card">
	<div class="card-body">
		<h5 class="card-title"><?=Tr::_('Complaint %n%', ['n'=>$complaint->getNumber()])?></h5>

		<div class="complaints-product">
			<div>
				<?php if($product->getImage(0)): ?>
					<a href="<?=$product->getURL()?>"><img src="<?=$product->getImageThumbnailUrl(0, 50, 50)?>"></a>
				<?php endif; ?>
			</div>
			<div><a href="<?=$product->getURL()?>"><?=$product->getName()?></a></div>
		</div>
		
		<?=$this->render('complaint-status')?><br>
		<br>


		<div class="card card-body complaints-description">
			<?=nl2br( $complaint->getProblemDescription() )?>
		</div>
		
		<div id="complaint-images" class="card card-body">
			<h5><?=Tr::_('Images')?></h5>
			
			<?php foreach( $complaint->getImages() as $img ):?>
				<div class="complaint-image">
					<div class="image">
						<a href="<?=$img->getURL()?>" target="_blank"><img src="<?=$img->getThbURL()?>"></a>
					</div>
					<div class="name"><?=$img->getName()?></div>
					<div class="size"><?=Locale::size( $img->getSize() )?></div>
					<div class="delete">
					</div>
				</div>
			<?php endforeach; ?>
		</div>
	</div>
</div>

</div>