<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Complaints;


use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use JetApplication\Complaint;
use JetApplication\Application_Service_EShop;
use JetApplication\Product_EShopData;

/**
 * @var MVC_View   $this
 * @var Form $edit_form
 * @var Product_EShopData $product
 * @var Complaint $complaint
 */

$complaint = $this->getRaw('complaint');
$edit_form = $this->getRaw('form');
$product = $complaint->getProduct();
$edit_form->field('problem_description')->input()->addCustomCssStyle('width:100%;height:300px');
$edit_form->field('problem_description')->input()->addJsAction('onblur', "JetAjaxForm.submit(this.form.id)");
$edit_form->field('delivery_of_claimed_goods_code')->input()->addJsAction('onblur', "JetAjaxForm.submit(this.form.id)");
$edit_form->field('complaint_type_code')->input()->addJsAction('onblur', "JetAjaxForm.submit(this.form.id)");
$edit_form->field('preferred_solution_code')->input()->addJsAction('onblur', "JetAjaxForm.submit(this.form.id)");

echo Application_Service_EShop::CustomerSection()?->showMenu('complaints');
?>
<div class="customer-section-container">
<div class="card">
	<div class="card-body">
		<h5 class="card-title"><?=Tr::_('Finish complaint')?></h5>


		<div class="complaints-product">
			<div>
				<?php if($product->getImage(0)): ?>
					<a href="<?=$product->getURL()?>"><img src="<?=$product->getImageThumbnailUrl(0, 50, 50)?>"></a>
				<?php endif; ?>
			</div>
			<div><a href="<?=$product->getURL()?>"><?=$product->getName()?></a></div>
		</div>
		
		<?=$edit_form->start()?>
		<div style="justify-content:left;display: grid;grid-template-columns: auto auto;gap: 10px;align-items: center;margin: 10px;">
			<?=$edit_form->field('delivery_of_claimed_goods_code')?>
			<?=$edit_form->field('complaint_type_code')?>
			<?=$edit_form->field('preferred_solution_code')?>
		</div>
		<div>
			<?=$edit_form->field('problem_description')?>
		</div>
		<?=$edit_form->end()?>
		
		<?=$this->render('detail/edit/images')?>
		
		<div id="finish-btn">
			<?=$this->render('detail/unfinished/finish-btn');?>
		</div>
	</div>
</div>
</div>