<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\Form;
use Jet\Http_Request;

/**
 * @var MVC_View $this
 * @var Form     $form
 */

$form = $this->getRaw('form');

$form->field( 'delivery_methods' )->input()->addCustomCssStyle('height: 300px');

$form->field( 'backend_module_name' )->input()->addJsAction('onchange', 'reloadPaymentMethodSpecification(this.options[this.selectedIndex].value);');
?>
<!--suppress JSUnresolvedReference, JSCheckFunctionSignatures -->
<script>
	async function reloadPaymentMethodSpecification( module_name ) {
		const response = await fetch('<?=Http_Request::currentURI(['action' =>'get_payment_method_specification'])?>&module='+encodeURIComponent(module_name));
		const options = await response.json();

		const select = document.getElementById('<?=$form->field( 'backend_module_payment_method_specification' )->getId()?>');

		while (select.options.length > 0) {
			select.remove(0);
		}

		for( let opt in options ) {
			const option = new Option(options[opt], opt);

			select.add( option );
			//alert(options[opt]);
		}
	}
</script>

<?=$form->field('erp_id')?>
<?=$form->field('kind' )?>
<?=$form->field('backend_module_name' )?>
<?=$form->field('backend_module_payment_method_specification' )?>
<?=$form->field('title')?>
