<?php

use JetApplication\Shop_Pages;

?>
<script>
	const PasswordReset = {
		base_URL: '<?=Shop_Pages::ResetPassword()->getURL()?>',
		start: async ( known_email ) => {
			const r = await fetch(PasswordReset.base_URL);
			const response = await r.text();
			
			document.getElementById('password_reset_area').innerHTML = response;

			dialog.open('password_reset');

			if(known_email) {
				document.getElementById('password_reset_enter_email__email').value  =known_email;
				PasswordReset.sendEmail();
			}
		},

		sendEmail: () => {
			JetAjaxForm.submit('password_reset_enter_email');
		},

		validateCode: () => {
			JetAjaxForm.submit('reset_password_validate_code', {
				onSuccess: function( form, response_data ) {
					if(response_data['reload']) {
						location.reload();
					}
				}
			});
		}
	}
</script>