<?php
namespace JetApplicationModule\Admin\Catalog\KindsOfProduct;

use JetApplication\KindOfProduct as KindOfProduct;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View   $this
 * @var KindOfProduct       $kind_of_product
 */
$kind_of_product = $this->getRaw( 'kind_of_product' );
?>
<div class="col d-flex justify-content-center">

	<div class="card" style="margin-top:50px;">
		<div class="card-body">
			<p>
				<?=Tr::_( 'Do you really want to delete this kind of product?' );?>
				<br/>
				<a href="<?=$kind_of_product->getEditURL()?>" style="font-weight: bolder;font-size: 20px;"><?=$kind_of_product->getInternalName();?> (<?=$kind_of_product->getId();?>)</a>
			</p>

			<div style="display: inline-block;width: 50%">
				<?= UI::button_goBack() ?>
			</div>
			<div style="display: inline-block;width: 45%;text-align: right">
				<form action="<?= Http_Request::currentURI() ?>" method="post">
					<input type="hidden" name="delete" value="yes">
					<?= UI::button_delete()->setType( 'submit' ) ?>
				</form>
			</div>
		</div>
	</div>
</div>
