<?php
namespace JetShopModule\Admin\Catalog\Properties;

use JetShop\KindOfProduct;
use JetShop\Product;
use JetShop\Category;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var KindOfProduct $kind_of_product
 * @var Product[] $products
 * @var Category[] $categories
 */
$kind_of_product = $this->getRaw( 'kind_of_product' );
$products = $this->getRaw('products');
$categories = $this->getRaw('categories');

?>
<div class="col d-flex justify-content-center">
	
	<div class="card" style="margin-top:50px;">
		<div class="card-body">
			<p>
				<?=Tr::_( 'It is mot possible tp delete this kind of product.' );?>
				<br/>
				<a href="<?=$kind_of_product->getEditURL();?>" style="font-weight: bolder;font-size: 20px;"><?=$kind_of_product->getInternalName();?> (<?=$kind_of_product->getId();?>)</a>
			</p>
			
			<?php if($products): ?>
			<p>
				<?=Tr::_( 'It is used by following products:' );?>
				<ul>
					<?php foreach($products as $p): ?>
						<li><a href="<?=$p->getEditURL()?>"><?=$p->getAdminTitle()?></a></li>
					<?php endforeach; ?>
				</ul>
			</p>
			<?php endif; ?>
			
			<?php if($categories): ?>
			<p>
				<?=Tr::_( 'It is used by following categories:' );?>
				<ul>
					<?php foreach($categories as $c): ?>
						<li><a href="<?=$c->getEditURL()?>"><?=$c->getPathName()?></a></li>
					<?php endforeach; ?>
				</ul>
			</p>
			<?php endif; ?>
			
			<div style="display: inline-block;width: 50%">
				<?= UI::button_goBack()->setUrl(Http_Request::currentURI(unset_GET_params: ['id', 'action'])) ?>
			</div>
		</div>
	</div>
</div>
