<?php
namespace JetApplicationModule\Admin\ImageManager;
use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Form;
use Jet\UI;
use Jet\Tr;
use Jet\UI_dialog;

/**
 * @var MVC_View $this
 * @var Form $images_form
 * @var Form $image_delete_form
 */

$product = $this->getRaw('product');

$editable = $this->getBool('editable');
?>

<style>
	.images_area>div {
		float: left;
	}
</style>
<?php if($editable):
	$upload_form = $this->getRaw('upload_form');

	$image_field = $upload_form->field('image');
	$image_field->input()->addJsAction('onchange', "ProductImagesHandler.upload()");

?>
<div class="toolbar" style="display: grid;grid-template-columns: 1fr 1fr;align-items: center">
	<div>
		<?=$upload_form->start()?>
		<div class="btn btn-light btn-upload">
			<?=UI::icon('upload')?>&nbsp;<span><?=Tr::_('Select and upload images')?></span>
			<?=$image_field->input()?>
		</div>
		<?=$upload_form->end()?>
	</div>
	<div style="text-align: right;padding-right: 10px;">
		<?=UI::button_delete(Tr::_('Delete selected images'))->setOnclick("ProductImagesHandler.deleteImages();")?>
	</div>
</div>
<?php endif; ?>

<div style="background-color: #f0f0f0;border-radius: 5px;margin: 10px;padding: 10px;">
	<div class="images_area" id="images_list" style="height: 500px;overflow: auto;margin: 5px;padding: 5px;">
		<?php
		require 'product-images-management/list.phtml';
		?>
	</div>
</div>



<?php if($editable):

	$delete_dialog = new UI_dialog('delete_image_confirm', Tr::_('Do you really want to delete those images?'), UI_dialog::SIZE_LARGE );
	
	echo $delete_dialog->start();
		?>
		<div id="image_delete_confirm_area" style="height: 250px;overflow: auto">
		
		</div>
		<?php
	echo $delete_dialog->footer();
		echo UI::button_delete()->setOnclick("ProductImagesHandler.deleteConfirm();");
	echo $delete_dialog->end();
	
	?>
	
	<script type="text/javascript">
		let ProductImagesHandler = new function() {

			this.delete_images = null;

			const handler = this;

			this._handleResponse = function( response ) {

				for(let el_id in response['snippets']) {
					document.getElementById(el_id).innerHTML = response['snippets'][el_id];
				}

				handler.initSort();
			};

			this.initSort = function() {

				$('#images_list')['sortable']({
					revert: true,
					stop: function() {
						handler.saveSort();
					}
				});
			};

			this.saveSort = function() {
				let images = [];

				$('#images_list').find('.image-thumbnail').each(function ( i, image ) {
					images.push( $(image).data('image') );
				});

				$.ajax({
					url: '<?=Http_Request::currentURI(['action'=>'save_sort'])?>&images='+images.join(','),
					dataType: "json",
					success: function( response ) {
						handler._handleResponse(response);
					}
				});
			};

			this.deleteImage = function( image, url ) {
				handler._delete([{
					image: image,
					url: url
				}]);
			};

			this.deleteImages = function()
			{
				let images = [];

				$('#images_list .select_image_checkbox').each( function(i, checkbox) {
					if(checkbox.checked) {
						images.push( {
							image: checkbox.value,
							url: checkbox.dataset.url
						} );
					}
				});

				if(images.length) {
					handler._delete(images);
				}
			};

			this._delete = function( images ) {

				handler.delete_images = images;

				let html = '';
				for(let i=0;i<images.length;i++) {
					let image = images[i];

					html += '<div class="image-thumbnail" style="float:left;width: 180px;height: 180px;background-image: url('+image.url+');background-size: 170px auto;"></div>';
				}

				$('#image_delete_confirm_area').html( html );

				$('#delete_image_confirm').modal('show');
			};

			this.deleteConfirm = function () {
				let images = [];
				for(let i=0; i<handler.delete_images.length;i++) {
					images.push(encodeURIComponent(handler.delete_images[i].image));
				}

				$.ajax({
					url: '<?=Http_Request::currentURI(['action'=>'delete'])?>&images='+images.join(','),
					dataType: "json",
					success: function( response ) {
						handler._handleResponse(response);
					}
				});
				$('#delete_image_confirm').modal('hide');

			};


			this.upload = function() {
				JetAjaxForm.submitMultiUpload(
					'<?=$upload_form->getId()?>',
					'<?=$image_field->getName()?>',
				);
			};

			handler.initSort();
		};
	</script>
<?php endif; ?>
