<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ImageManager;


use Jet\MVC_View;
use JetApplication\Application_Service_Admin;
use JetApplication\Application_Service_Admin_Image;
use JetApplication\EShop;

/**
 * @var MVC_View   $this
 * @var Application_Service_Admin_Image|Main $image_manager
 */
$image_manager = $this->getRaw('manager');
$UI_manager = Application_Service_Admin::UI();




if($image_manager->getEshopSyncMode()):
	foreach( $image_manager->getDefinedImages() as $image):
		echo $image_manager->renderImageWidgets( $image->getEshop() );
		break;
	endforeach;
else:
	echo '<br>';
	echo Application_Service_Admin::EntityEdit()->renderShopDataBlocks(
		inline_mode: true,
		renderer: function( EShop $eshop, string $eshop_key ) use ($image_manager) : void {
			echo $image_manager->renderImageWidgets( $eshop );
		});
	
endif;


echo $image_manager->renderMain();
?>
<br><br><br>
