<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\ImageManager;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Admin_Managers_Image;
use JetApplication\EShops;
use JetApplication\EShop;

/**
 * @var MVC_View   $this
 * @var Admin_Managers_Image|Main $image_manager
 */
$image_manager = $this->getRaw('manager');
$UI_manager = Admin_Managers::UI();

if($image_manager->getEshopSyncMode()):
	foreach( EShops::getList() as $eshop):
		echo $image_manager->renderImageWidgets( $eshop );
		break;
	endforeach;
else:
	echo '<br>';
	echo Admin_Managers::EntityEdit()->renderShopDataBlocks(
		inline_mode: true,
		renderer: function( EShop $eshop, string $eshop_key ) use ($image_manager) : void {
			echo $image_manager->renderImageWidgets( $eshop );
		});
	
endif;


echo $image_manager->renderMain();
?>
<br><br><br>
