<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Orders;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Application_Service_Admin;
use JetApplication\CustomerBlacklist;
use JetApplication\Order;

/**
 * @var MVC_View $this
 * @var Order $item
 */

$item = $this->getRaw('item');

$address = $item->getBillingAddress();
if($item->getImportSource()) {
	$address = $item->getDeliveryAddress();
}

?>

<?php if($address->getCompanyName()): ?>
<?=$address->getCompanyName()?><br>
<?php endif; ?>
<?=$address->getFirstName()?> <?=$address->getSurname()?>
<?php if(!$item->getImportSource()): ?>
(<?=Application_Service_Admin::Customer()->renderItemName( $item->getCustomerId() )?>)<br>
<?php endif; ?>


<a href="mailto:<?=$item->getEmail()?>"><?=$item->getEmail()?></a><br>
<?=$item->getPhone()?><br>


<?php if( CustomerBlacklist::customerIsBlacklisted( $item->getEmail() ) ): ?>
	<div class="alert alert-danger" role="alert">
		<?=UI::icon('skull-crossbones')?> <?=Tr::_('Customer is blacklisted')?>
	</div>
<?php endif; ?>
