<?php
namespace JetApplicationModule\Admin\OrderDispatch\DoDispatch;

use Jet\Mvc_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\OrderDispatch;

/**
 * @var Mvc_View $this
 * @var OrderDispatch $dispatch
 */

$dispatch = $this->getRaw('dispatch');


$dimension_units = $dispatch->getDimensionsUnits();
$volume_units = $dispatch->getVolumeUnits();
$weight_units = $dispatch->getWeightUnits();


$form = $dispatch->getAddPacketForm();

$form->renderer()->addJsAction('onsubmit', 'addPacket();return false;');
$form->field('type')->input()->addJsAction('onchange', "Packets.setPacketDefaults( this.form, this.options[this.selectedIndex].value )");
?>

	
	<?=$form->start()?>
	<div class="packages-form-row">
		<div></div>
		<div>
			<?=$form->field('type')->input()?>
		</div>
		
		<?php if($form->fieldExists('weight')): ?>
			<div><?=Tr::_('Weight:')?></div>
			<div class="packages-field">
				<div>
					<?php $form->field('weight')->input()->addJsAction('onkeydown', "if(event.code=='Enter' || event.code=='NumpadEnter') {Packets.addPacket(true);}") ?>
					<?=$form->field('weight')->input()?>
					<?=$form->field('weight')->error()?>
				</div>
				<div><?=$weight_units?></div>
			</div>
		<?php else: ?>
			<div style="grid-column: span 2"></div>
		<?php endif; ?>
		
		
		
		<?php if($form->fieldExists('size_w')): ?>
			<div><?=Tr::_('Width:')?></div>
			<div class="packages-field">
				<div>
					<?=$form->field('size_w')->input()?>
					<?=$form->field('size_w')->error()?>
				</div>
				<div><?=$dimension_units?></div>
			</div>
		<?php else: ?>
			<div style="grid-column: span 2"></div>
		<?php endif; ?>
		
		<?php if($form->fieldExists('size_h')): ?>
			<div><?=Tr::_('Height:')?></div>
			<div class="packages-field">
				<div>
					<?=$form->field('size_h')->input()?>
					<?=$form->field('size_h')->error()?>
				</div>
				<div><?=$dimension_units?></div>
			</div>
		<?php else: ?>
			<div style="grid-column: span 2"></div>
		<?php endif; ?>
		
		<?php if($form->fieldExists('size_l')): ?>
			<div><?=Tr::_('Length:')?></div>
			<div class="packages-field">
				<div>
					<?=$form->field('size_l')->input()?>
					<?=$form->field('size_l')->error()?>
				</div>
				<div><?=$dimension_units?></div>
			</div>
		<?php else: ?>
			<div style="grid-column: span 2"></div>
		<?php endif; ?>
		
		<div><?=Tr::_('Internal note:')?></div>
		<div>
			<?=$form->field('note')->input()?>
			<?=$form->field('note')->error()?>
		</div>
		
		
		<div>
			<?=UI::button_create(' ')
				->addJsAction('onkeydown', "Packets.onAddPackageKeyPress();return false;")
				->setOnClick("Packets.addPacket()")
				->setClass( UI_button::CLASS_SUCCESS )
			?>
		</div>
	</div>
	<?=$form->end()?>

