<?php
namespace JetApplicationModule\Admin\Delivery\Deadlines;

use JetApplication\Delivery_Method;

use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use JetApplication\Delivery_Method_ShopData;
use JetApplication\Shops;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Delivery_Method     $delivery_deadline
 */

$delivery_deadline = $this->getRaw( 'delivery_deadline' );
?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>

		<?php if(!$delivery_deadline->getIsNew()): ?>
			<?php foreach(Shops::getListSorted() as $shop):
				echo $delivery_deadline->getShopData( $shop )->renderImageWidgets( Delivery_Method_ShopData::getImageClasses(), !$delivery_deadline->getEditForm()->getIsReadonly() );
			endforeach; ?>
		<?php endif; ?>
	</div>
</div>



