<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\KindsOfProduct;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Admin_Managers;
use JetApplication\KindOfProduct_Property;

/**
 * @var MVC_View   $this
 * @var KindOfProduct_Property $property
 */

$editable = $this->getBool('editable');
$p = $this->getRaw('property');
?>
	
	<div
		class="list-group-item sortable-item property<?=$this->getBool('property_in_group')?' property-in-group':''?>"
		data-id="<?=$p->getPropertyId()?>"
		style="display: grid;grid-template-columns: 20px 200px 200px 170px 170px 200px 1fr;align-items: center">
		<div>
			<?php if($editable): ?>
				<?=UI::icon('up-down')?>
			<?php endif; ?>
		</div>
		<div>
			<?=Admin_Managers::Property()->showName( $p ) ?>
		</div>
		<div>
			<?=Admin_Managers::Property()->renderActiveState( $p ) ?>
		</div>
		<div>
			<?=Admin_Managers::Property()->showType( $p->getPropertyType() ) ?>
		</div>
		
		<div>
			<?php if($p->canBeVariantSelector()): ?>
				<?php if( $editable ): ?>
					<label><input type="checkbox" <?=$p->getIsVariantSelector()?' checked':''?> onchange="setIsVariantMaster(<?=$p->getPropertyId()?> ,this.checked)"> <?=Tr::_('Is variant selector')?></label>
				<?php else: ?>
					<label><input type="checkbox" disabled <?=$p->getIsVariantSelector()?' checked':''?>> <?=Tr::_('Is variant selector')?></label>
				<?php endif; ?>
			<?php endif; ?>
		</div>
		<div>
			<?php if( $editable ): ?>
				<label><input type="checkbox" <?=$p->getShowOnProductDetail()?' checked':''?> onchange="setShowOnProductDetail(<?=$p->getPropertyId()?> ,this.checked)"> <?=Tr::_('Show on product detail')?></label>
			<?php else: ?>
				<label><input type="checkbox" disabled <?=$p->getShowOnProductDetail()?' checked':''?>> <?=Tr::_('Show on product detail')?></label>
			<?php endif; ?>
		</div>
		
		<div style="text-align: right">
			<?php if($editable): ?>
				<?=UI::button_delete(' ')->setSize(UI_button::SIZE_EXTRA_SMALL )->setOnClick( "removeProperty({$p->getGroupId()}, {$p->getPropertyId()})" )?>
			<?php endif; ?>
		</div>
	</div>
