<?php
namespace JetApplicationModule\Admin\Content\Email\Templates;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\UI;
use Jet\Tr;

use JetApplication\Admin_Managers;
use JetApplication\Shops;

/**
 * @var MVC_View $this
 * @var EmailTemplateText $item
 */

$item = $this->getRaw('item');

if(!$item->isEditable()) {
	return;
}
?>
&nbsp;&nbsp;&nbsp;&nbsp;

<script>
	function sendTestEmail( shop_key ) {
		let email = document.getElementById('test-email-address').value;
		if(!email) {
			return;
		}
		
		location = '<?=Http_Request::currentURI(['action'=>'send_test_email'])?>&shop='+shop_key+'&email='+encodeURIComponent( email );
	}
</script>

<?php if(Shops::isMultiShopMode()): ?>
	<div class="dropdown">
		<button class="btn btn-info dropdown-toggle" type="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<?=UI::icon('eye');?> <?=Tr::_('Preview e-mail')?>
		</button>
		<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			<?php foreach( Shops::getListSorted() as $shop ):
				$URL = Http_Request::currentURI(['action'=>'email_preview','shop'=>$shop->getKey()]);
				?>
				<a class="dropdown-item" href="<?=$URL?>" target="_blank">
					<?=UI::icon('arrow-up-right-from-square')->addCustomCssStyle('opacity:0.5');?>
					<?=$shop->getShopName()?>
				</a>
			<?php endforeach; ?>
		</div>
	</div>

	<div style="display: inline-block;margin-left: 20px;">
		<input
			type="email"
			id="test-email-address"
			class="form-control"
			style="width: 250px"
			placeholder="<?=Tr::_('send test e-mail to ...')?>"
		>
	</div>

	<div class="dropdown">
		<button class="btn btn-info dropdown-toggle" type="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<?=UI::icon('at');?> <?=Tr::_('Send test e-mail')?>
		</button>
		<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			<?php foreach( Shops::getListSorted() as $shop ): ?>
				<a class="dropdown-item" href="#" onclick="sendTestEmail('<?=$shop->getKey()?>');">
					<?=$shop->getShopName()?>
				</a>
			<?php endforeach; ?>
		</div>
	</div>

	<div class="dropdown">
		<button class="btn btn-info dropdown-toggle" type="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<?=UI::icon('at');?> <?=Tr::_('Download e-mail message file')?>
		</button>
		<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			<?php foreach( Shops::getListSorted() as $shop ):
				$URL = Http_Request::currentURI(['action'=>'download_message_file','shop'=>$shop->getKey()]);
				?>
				<a class="dropdown-item" href="<?=$URL?>" target="_blank">
					<?=UI::icon('arrow-up-right-from-square')->addCustomCssStyle('opacity:0.5');?>
					<?=$shop->getShopName()?>
				</a>
			<?php endforeach; ?>
		</div>
	</div>



<?php
else:
	$shop = Shops::getDefault();
	$URL = Http_Request::currentURI(['action'=>'email-preview','shop'=>$shop->getKey()]);
	?>
	<a href="<?=$URL?>" target="_blank" class="btn btn-info"><?=UI::icon('eye');?> <?=Tr::_('Preview e-mail')?></a>

	<div style="display: inline-block;margin-left: 20px;">
		<input
			type="email"
			id="test-email-address"
			class="form-control"
			style="width: 250px"
			placeholder="<?=Tr::_('send test e-mail to ...')?>"
		>
	</div>

	<a href="#" class="btn btn-info" onclick="sendTestEmail('<?=$shop->getKey()?>');"><?=UI::icon('at');?> <?=Tr::_('Send test e-mail')?></a>
	<?php
	$URL = Http_Request::currentURI(['action'=>'download_message_file','shop'=>$shop->getKey()]);
	?>
	<a href="<?=$URL?>" target="_blank" class="btn btn-info"><?=UI::icon('at');?> <?=Tr::_('Download e-mail message file')?></a>
	<?php
endif;

echo Admin_Managers::Image()->commonImageManager( 'EMail_TemplateText', $item->getId() );
