<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

/**
 * @var MVC_View $this
 */
if(!$this->getRaw('deactivate_url')) {
	return;
}

echo UI::button(Tr::_('Deactivate', dictionary: Tr::COMMON_DICTIONARY))
	->setUrl( $this->getRaw('deactivate_url') )
	->setClass( UI_button::CLASS_DANGER )
	->setSize( UI_button::SIZE_EXTRA_SMALL );
