<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

/**
 * @var MVC_View $this
 */

$URL = $this->getRaw('activate_completely_url');

if(!$URL) {
	return;
}

echo UI::button(Tr::_('Activate completely', dictionary: Tr::COMMON_DICTIONARY))
	->setUrl( $URL )
	->setClass( UI_button::CLASS_INFO )
	->setSize( UI_button::SIZE_EXTRA_SMALL );
