<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\Tr;
?>
<div class="card card-body" style="margin-bottom: 20px;">
	
	<h4><?= Tr::_('Activation status', dictionary: Tr::COMMON_DICTIONARY)?></h4>
	<div style="display: grid;justify-content:left ;grid-template-columns: auto auto auto auto;gap: 10px;align-items: center;margin: 10px;">
	
	