<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\Tr;
use Jet\UI;
?>
<span class="bg-danger text-white" style="border-radius: 10px;padding-left: 10px;padding-right: 10px;padding-top: 3px;padding-bottom: 3px;"><?= UI::icon('circle-xmark');?> <?=Tr::_('Not active', dictionary: Tr::COMMON_DICTIONARY)?></span>
