<?php
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\EShopEntity_WithEShopData;

/**
 * @var MVC_View $this
 * @var EShopEntity_WithEShopData $entity
 */

$entity = $this->getRaw('entity');
?>

<div>
	<?php if($entity->isActive()):
		echo $this->render('entity-activation/active');
	else:
		echo $this->render('entity-activation/not-active');
	endif; ?>
</div>
<div><b><?=Tr::_('Master switch', dictionary: Tr::COMMON_DICTIONARY)?></b></div>
<div></div>
<div></div>

