<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Http_Request;
use Jet\UI;
use Jet\Tr;
use Jet\Mvc_View;

/**
 * @var Mvc_View   $this
 */

$title = $this->getRaw('sort_title');
$sort_action = $this->getRaw('sort_action');
$items = $this->getRaw('sort_items');

if(!$items) {
	return;
}

$dialog = UI::dialog('sort_dialog', Tr::_($title), 400);
	?>
	<?=$dialog->start()?>
	<div style="overflow: auto;">
		<div class="sortable" id="sort_items">
			<?php foreach($items as $id=>$title): ?>
				<div class="sortable-item" data-id="<?=$id?>">
					<i class="property-option-move"></i>
					<?=$title?>
				</div>
			<?php endforeach; ?>
		</div>
	</div>
	<?=$dialog->footer()?>
	<form action="<?=Http_Request::currentURI(['action'=>$sort_action])?>" method="post">
		<input type="hidden" name="sort_order" id="sort_order" />
		<?=UI::button_save()?>
	</form>
	<?=$dialog->end()?>

	<script type="text/javascript">

		var paramSort = {
			openDialog: function () {
				paramSort.setSort();
				$('#sort_dialog').modal('show');


				$('#sort_items').sortable({
					stop: function() {
						paramSort.setSort();
					}
				});

			},

			setSort: function() {
				var values = [];

				$('#sort_items').find('.sortable-item').each( function(i, item) {
					values.push($(item).data('id'));
				});

				$('#sort_order').val(values.join('|'));

			}
		};
	</script>
