<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Delivery\Methods;


use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\Delivery_Method;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 * @var Delivery_Method $item
 */

$item = $this->getRaw('item');

foreach( EShops::getList() as $eshop):
	if($item->getEshopData( $eshop )->getFreeDeliveryLimit()==0) {
		continue;
	}
	
	echo $eshop->getName().': '.Admin_Managers::PriceFormatter()->formatWithCurrency(
		$eshop->getDefaultPricelist(),
		$item->getEshopData( $eshop )->getFreeDeliveryLimit()
	);
	echo '<br>';
endforeach;
