<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Delivery\Methods;


use Jet\MVC_View;
use JetApplication\Application_Service_Admin;
use JetApplication\Delivery_Method;

/**
 * @var MVC_View $this
 * @var Delivery_Method $item
 */

$item = $this->getRaw('item');
$eshop = $item->getEshop();

if(count($eshop->getPricelists())>1):
?>
<div style="display: grid;justify-content:left;grid-template-columns: auto auto;gap: 10px;">
<?php foreach($eshop->getPricelists() as $pricelist): ?>
	<div><?=$pricelist->getName()?></div>
	
	<div style="font-weight: bolder;"><?=Application_Service_Admin::PriceFormatter()->formatWithCurrency(
		$pricelist,
		$item->getPrice( $pricelist )
	);?></div>
<?php endforeach; ?>
</div>
<?php else:
	
	$pricelist = $item->getEshop()->getDefaultPricelist();
	?>
	<div style="font-weight: bolder;"><?=Application_Service_Admin::PriceFormatter()->formatWithCurrency(
			$pricelist,
			$item->getPrice( $pricelist )
		);?></div>
<?php endif; ?>
