<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Delivery\Methods;


use Jet\MVC_View;
use JetApplication\Delivery_Method;

/**
 * @var MVC_View $this
 * @var Delivery_Method $item
 */

$item = $this->getRaw('item');

echo $item->getTitle();
