<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\MVC_View;
use JetApplication\Customer;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');


if(
	$cash_desk->getCurrentStep()==CashDesk::STEP_DELIVERY ||
	$cash_desk->getCurrentStep()==CashDesk::STEP_PAYMENT
) {
	return;
}

if(Customer::getCurrentCustomer()) {
	require  'customer/logged_in.phtml';

} else {

	if( !$cash_desk->getEmailHasBeenSet() ) {
		require  'customer/email.phtml';
	} else {
		if( !$cash_desk->getCustomerRegisterOrNotBeenSet() ) {

			if( ($cst = Customer::getByEmail($cash_desk->getEmailAddress())) ) {
				require  'customer/exists_login.phtml';
			} else {
				require  'customer/registration/set_password.phtml';
			}
		} else {
			if(!$cash_desk->getPhoneHasBeenSet()) {
				require  'customer/registration/phone.phtml';
			} else {
				require  'customer/registration.phtml';
			}
		}
	}
}

