<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\MVC_View;
use Jet\SysConf_URI;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');


?>
<style>
	#cash_desk_overview {
		padding: 20px;
	}
	
	.method, .method-selected {
		display: grid;
		grid-template-columns: 20px 70px 1fr 150px;align-items: center;
		padding: 10px;
		border-radius: 5px;
		margin: 15px;
	}
	
	.method-selected {
		background-color: #dcdbdb;
	}

	.option, .option-selected {
		display: grid;
		grid-template-columns: 20px 50px 1fr;align-items: center;
		padding: 5px;
		border-radius: 5px;
		margin: 5px;
	}

	.option-selected {
		background-color: #969696;
	}
	
	
	.method-has-been-selected {
		display: grid;
		grid-template-columns: 200px 1fr 1fr 100px;align-items: center
	}
	
	.step-block {
		background-color: #f8f9fa;
		border: 1px solid #dedede;
		border-radius: 5px;
		padding: 10px;
		margin-top: 20px;
		margin-bottom: 20px;
	}
	
	.selected-contact {
		display: grid;
		grid-template-columns: 200px 300px 1fr;
		margin-bottom: 20px;
	}
	
	.step-title {
		font-weight: bolder;
		font-size: 1.2rem;
	}
	
	.continue-button-area {
		padding: 5px;
		text-align: right;
	}
	
	.price-standard {
		text-decoration: line-through;
	}
	
	.price-final {
		font-weight: bolder;
	}
	
	.method-icon {
		padding: 5px;
	}

	.method-title {
		padding: 5px;
	}
	
	.method-title>div{
		font-size: 0.8rem;
	}
	
	.addresses {
		display: grid;
		padding-left: 10%;
		padding-right: 10%;
		grid-template-columns: 1fr 1fr 1fr;
		grid-gap: 10px;
		margin-bottom: 20px;
	}
	
	.address {
		padding: 10px;
		background-color: #ffffff;
		border: 1px solid #dedede;
		border-radius: 5px;
	}

	.address-selected {
		padding: 10px;
		background-color: #bebebe;
		border: 1px solid #dedede;
		border-radius: 5px;
	}
	
	.address-field {
		display: grid;
		grid-template-columns: 1fr 4fr;
		margin: 5px;
		align-items: center;
	}
	
	
	#select_personal_takeover_point_dialog_body {
		display: grid;
		grid-template-columns: 2fr 8fr;
		grid-template-rows: 100%
	}

	
	.whisperer-items {
		position: absolute;
		top: 0px;
		left: 0px;
		height: 400px;
		background-color: #ffffff;
		overflow: auto;
		z-index: 999999;
		border: 1px solid #a1a1a1;
	}
	
	.whisperer-item {
	
	}
	
	.whisperer-item-selected {
		background-color: #b2b2b2
	}
	
	
	.place_search_result_item {
		display: grid;
		grid-template-columns: 60px 1fr 60px;
		gap: 5px;
		margin: 5px;
	}
	
	.place_search_result_item_image {
	
	}
	
	.place_search_result_item_address {
		white-space: nowrap;
		overflow: hidden;
	}
	
	.place_search_result_item_price {
		color: #6c6c6c;
	}
	
	
	
</style>
<script type="text/javascript" src="//maps.google.com/maps/api/js?key=<?=$cash_desk->getConfig()->getMapAPIKey()?>"></script>
<script type="text/javascript" src="<?=SysConf_URI::getJs()?>GMmarkerclusterer.js"></script>

<?php
require 'js/Whisperer.phtml';
require 'js/AddressWhisperer.phtml';
require 'js/CashDesk.phtml';
require 'js/CashDesk/delivery.phtml';
require 'js/CashDesk/delivery/personalTakeover.phtml';
require 'js/CashDesk/payment.phtml';
require 'js/CashDesk/customer/email.phtml';
require 'js/CashDesk/customer/phone.phtml';
require 'js/CashDesk/customer/registration.phtml';
require 'js/CashDesk/customer/billingAddress.phtml';
require 'js/CashDesk/customer/deliveryAddress.phtml';
require 'js/CashDesk/confirm.phtml';
?>

<script>
CashDesk.delivery.personalTakeover.map = {
	center: {
		lat: <?=$cash_desk->getConfig()->getMapCenterLat()?>,
		lon: <?=$cash_desk->getConfig()->getMapCenterLon()?>,
	},
	default_zoom: <?=$cash_desk->getConfig()->getMapDefaultZoom()?>
};


<?php if($cash_desk->isBillingAddressEditable()): ?>
CashDesk.customer.billingAddress.initEdit();
<?php endif; ?>
<?php if($cash_desk->isDeliveryAddressEditable()): ?>
CashDesk.customer.deliveryAddress.initEdit();
<?php endif; ?>

</script>
