<?php
namespace JetApplicationModule\Shop\CashDesk;

use JetApplication\Shop_Managers;

$cash_desk = CashDesk::get();

$order = $cash_desk->getOrder();

?>
<div class="overview">
	<table class="table table-table">
		<?php foreach($order->getItems() as $item): ?>
		<tr>
			<td style="width: 50px;">
			
			</td>
			<td><?=$item->getTitle()?></td>
			<td style="width: 120px;">
				<?=Shop_Managers::PriceFormatter()->formatWithCurrency($item->getTotalAmount())?>
			</td>
		</tr>
		<?php endforeach; ?>
		<tr>
			<td></td>
			<td></td>
			<td style="font-size: 2er;font-weight: bolder"><?=Shop_Managers::PriceFormatter()->formatWithCurrency($order->getTotalAmount())?></td>
		</tr>
	</table>
</div>