<?php
namespace JetApplicationModule\Shop\CashDesk;

use Jet\MVC_View;
use JetApplication\Order_Item;
use JetApplication\Shop_Managers;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');

$order = $cash_desk->getOrder();

?>
<div class="overview">
	<table class="table table-table">
		<?php foreach($order->getItems() as $item): ?>
		<tr>
			<td style="width: 50px;">
			
			</td>
			<td><?=$item->getTitle()?></td>
			<td style="width: 120px;">
				<?php if( !($item->getType()==Order_Item::ITEM_TYPE_DISCOUNT && $item->getTotalAmount()==0) ): ?>
					<?=Shop_Managers::PriceFormatter()->formatWithCurrency($item->getTotalAmount())?>
				<?php endif; ?>
			</td>
		</tr>
		<?php endforeach; ?>
		<tr>
			<td style="font-size: 2em;font-weight: bolder;text-align: right" colspan="3"><?=Shop_Managers::PriceFormatter()->formatWithCurrency($order->getTotalAmount())?></td>
		</tr>
	</table>
</div>