<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\UI;
use Jet\UI_tabsJS_tab;
use JetApplication\EShops;
use Jet\Locale;
use Jet\Tr;
use Jet\Form;
use JetApplication\Application_Service_General;

/**
 * @var MVC_View $this
 * @var UI_tabsJS_tab $tab
 * @var Locale $locale
 * @var Form $form
 */

$tab = $this->getRaw('tab');
$locale = $this->getRaw('locale');
$form = $this->getRaw('form');

echo $tab->content()->start();

if(
	EShops::isMultilanguageMode() &&
	$form &&
	!$form->getIsReadonly()
):
?>
<div style="padding: 5px;padding-bottom: 15px">
	<?php
	echo UI::button( Tr::_('Copy', dictionary: Tr::COMMON_DICTIONARY) )
		->setOnClick("UI_DescriptionBlock.copyContentStart('{$locale}', this.form, false );")
		->setIcon('copy');
	
	if( Application_Service_General::Translator()):
		echo UI::button( Tr::_('Copy and translate', dictionary: Tr::COMMON_DICTIONARY) )
			->setOnClick("UI_DescriptionBlock.copyContentStart('{$locale}', this.form, true );")
			->setIcon('earth-europe');
	endif;
	?>
</div>
<?php
endif;