<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use Jet\UI_tabsJS;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 * @var UI_tabsJS $tabs
 */

$tabs = $this->getRaw('tabs');

if(EShops::isMultiEShopMode()):
	foreach( EShops::getAvailableLocales() as $locale) {
		$tabs->tab( $locale->toString() )->addJsAction('onclick', "UI_DescriptionBlock.onSelect('".$locale->toString()."');");
	}
	
	$copy_dialog = UI::dialog('copy_dialog', Tr::_('Copy', dictionary: Tr::COMMON_DICTIONARY));
	
	echo $copy_dialog->start();
	?>
	<h5><?=Tr::_('Source locale', dictionary: Tr::COMMON_DICTIONARY)?></h5>
	<div style="display: grid;grid-template-columns: 20px auto; gap: 10px;align-items: center;margin: 20px;">
		<?php foreach( EShops::getAvailableLocales() as $locale): ?>
		<div><input type="radio" name="__copy_source_locale" id="__copy_source_locale_<?=$locale?>" value="<?=$locale?>" class="__copy_source" onclick="UI_DescriptionBlock.copyContentSourceSelected('<?=$locale?>');"></div>
		<div><label for="__copy_source_locale_<?=$locale?>" style="margin: 0px;padding: 0px;"><?=UI::flag( $locale )?> <?=$locale->getLanguageName( $locale )?></label></div>
		<?php endforeach; ?>
	</div>

	<h5><?=Tr::_('Target locale', dictionary: Tr::COMMON_DICTIONARY)?></h5>
	<div style="display: grid;grid-template-columns: 20px auto; gap: 10px;align-items: center;margin: 20px;">
		<?php foreach( EShops::getAvailableLocales() as $locale): ?>
			<div><input type="checkbox" name="__copy_target_locale_<?=$locale?>" id="__copy_target_locale_<?=$locale?>" value="<?=$locale?>" class="__copy_target"></div>
			<div><label for="__copy_target_locale_<?=$locale?>" style="margin: 0px;padding: 0px;"><?=UI::flag( $locale )?> <?=$locale->getLanguageName( $locale )?></label></div>
		<?php endforeach; ?>
	</div>

	<?php
	echo $copy_dialog->footer();
		echo UI::button( Tr::_('Copy', dictionary: Tr::COMMON_DICTIONARY) )
			->setOnClick("UI_DescriptionBlock.copyContent();")
			->setClass( UI_button::CLASS_PRIMARY );
	echo $copy_dialog->end();
	?>
	<script>
		
		const UI_DescriptionBlock = {
			copy_form: null,
			
			onSelect: ( locale ) => {
				Cookies.set('selected_description_locale', locale, undefined, '/');
			},
			
			init: () => {
				let tab = Cookies.get('selected_description_locale');

				if(tab) {
					$('.nav-tabs a[href="#' + tab + '"]').tab('show');
				}
			},
			
			copyContentStart: ( source_locale, form) => {
				UI_DescriptionBlock.copy_form = form;
				
				[...document.getElementsByClassName('__copy_source')].forEach( ( el ) => {
					el.checked = el.value == source_locale;
				} );

				[...document.getElementsByClassName('__copy_target')].forEach( ( el ) => {
					el.checked = el.value != source_locale;
					el.disabled = !el.checked;
				} );
				
				$('#copy_dialog').modal('show');
			},

			copyContentSourceSelected: ( source_locale ) => {
				[...document.getElementsByClassName('__copy_target')].forEach( ( el ) => {
					el.checked = el.value != source_locale;
					el.disabled = !el.checked;
				} );
			},
			
			copyContent: () => {
				let source_eshop = '';
				let target_locales = [];
				
				[...document.getElementsByClassName('__copy_source')].forEach( ( el ) => {
					if(el.checked) {
						source_eshop = el.value;
					}
				} );

				[...document.getElementsByClassName('__copy_target')].forEach( ( el ) => {
					if(
						el.checked &&
						el.value!=source_eshop
					) {
						target_locales.push( el.value );
					}
				} );

				let source_data = {};
				[...UI_DescriptionBlock.copy_form.elements].forEach( ( el ) => {
					if(el.name.startsWith('description['+source_eshop+'][')) {
						let name = el.name.substring( ('description['+source_eshop+']').length );
						name = name.replace('[', '');
						name = name.replace(']', '');


						switch(el.type) {
							case 'checkbox':
							case 'radio':
								source_data[name] = el.checked;
								break;
							case 'select-one':
								source_data[name] = el.options[el.selectedIndex].value;
								break;
							case 'select-multiple':
								source_data[name] = [];
								[...el.options].forEach( ( option ) => {
									if(option.selected) {
										source_data[name].push( option.value );
									}
								} );
								break;
							default:
								source_data[name] = el.value;
								break;
						}

					}
				} );

				[...UI_DescriptionBlock.copy_form.elements].forEach( ( el ) => {
					[...target_locales].forEach( ( target_locale ) => {
						if(el.name.startsWith('description['+target_locale+'][')) {
							let name = el.name.substring( ('description['+target_locale+']').length );
							name = name.replace('[', '');
							name = name.replace(']', '');

							switch(el.type) {
								case 'checkbox':
								case 'radio':
									el.checked = source_data[name];
									break;
								case 'select-one':
									[...el.options].forEach( ( option ) => {
										option.selected = source_data[name] == option.value;
									} );
									break;
								case 'select-multiple':
									[...el.options].forEach( ( option ) => {
										option.selected = source_data[name].includes( option.value );
									} );
									break;
								default:
									el.value = source_data[name];
									break;
							}
						}
					} );
				} );

				$('#copy_dialog').modal('hide');
			}
		};
		
	</script>
<?php
endif;


echo $tabs->start();
