<?php
namespace JetApplicationModule\Admin\Entity\Edit\WithShopData;

use JetApplication\Admin_Entity_WithShopData_Interface;
use JetApplication\Entity_WithShopData;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;

/**
 * @var MVC_View   $this
 * @var Entity_WithShopData|Admin_Entity_WithShopData_Interface     $item
 */
$item = $this->getRaw( 'item' );
?>
<div class="col d-flex justify-content-center">

	<div class="card" style="margin-top:50px;">
		<div class="card-body">
			<p>
				<?=$this->getRaw('message')?>
				<br/>
				<a href="<?=$item->getEditURL();?>" style="font-weight: bolder;font-size: 20px;"><?=$item->getAdminTitle();?></a>
			</p>

			<div style="display: inline-block;width: 50%">
				<?= UI::button_goBack()->setUrl(Http_Request::currentURI(unset_GET_params: ['id', 'action'])) ?>
			</div>
			<div style="display: inline-block;width: 45%;text-align: right">
				<form action="<?= Http_Request::currentURI() ?>" method="post">
					<input type="hidden" name="delete" value="yes">
					<?= UI::button_delete()->setType( 'submit' ) ?>
				</form>
			</div>
		</div>
	</div>
</div>
