<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\Complaints;


use Jet\MVC_View;
use JetApplication\Complaint;

/**
 * @var MVC_View   $this
 * @var Complaint $complaint
 */
$complaint = $this->getRaw('complaint');

echo $complaint->getStatus()?->getTitle();