<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\ShoppingCart;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\CashDesk;
use JetApplication\Discounts_Code;
use JetApplication\EShop_Pages;
use JetApplication\Application_Service_EShop;
use JetApplication\Marketing_DeliveryFeeDiscount;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */

$cash_desk = $this->getRaw('cash_desk');

$cart = $cash_desk->getCart();

if($cart->getNumberOfUnits()<1):
	echo $this->render('shopping_cart_page/empty');
	return;
endif;


$dm_code = Discounts_Code::getModule( $cash_desk->getEshop() );

$dm_free_delivery = Marketing_DeliveryFeeDiscount::getModule( $cash_desk->getEshop() );

$available_gifts = $cart->getAvailableCartGifts();
$selected_gift_ids = $cart->getSelectedCartGiftIds();

$selected_product_gifts = $cart->getSelectedProductGifts();

?>
<?=$this->render('shopping_cart_page/items')?>

<?php if($available_gifts || $selected_product_gifts): ?>

<h3><?=Tr::_('Gifts')?></h3>
<div id="shopping-cart-gifts">
<?php foreach($selected_product_gifts as $gift): ?>
	<div></div>
	<div><img src="<?=$gift->getGiftProduct()->getImageThumbnailUrl(0, 50, 50)?>"></div>
	<div><?=$gift->getGiftProduct()->getName()?></div>
<?php endforeach; ?>


<?php foreach($available_gifts as $gift):
	$gift_id = $gift->getGiftProductId();
	?>

	<?php if($gift->getAutoAppend()): ?>
		<div></div>
		<div><img src="<?=$gift->getGiftProduct()->getImageThumbnailUrl(0, 50, 50)?>"></div>
		<div><?=$gift->getGiftProduct()->getName()?></div>
	<?php else: ?>
		<?php if(in_array($gift_id, $selected_gift_ids)): ?>
			<div><input type="checkbox" checked value="<?=$gift_id?>" onclick="ShoppingCart.Gifts.unselect(<?=$gift_id?>);"></div>
			<div><img src="<?=$gift->getGiftProduct()->getImageThumbnailUrl(0, 50, 50)?>"></div>
			<div><?=$gift->getGiftProduct()->getName()?></div>
		<?php else: ?>
			<div><input type="checkbox" value="<?=$gift_id?>" onclick="ShoppingCart.Gifts.select(<?=$gift_id?>);"></div>
			<div><img src="<?=$gift->getGiftProduct()->getImageThumbnailUrl(0, 50, 50)?>"></div>
			<div><?=$gift->getGiftProduct()->getName()?></div>
		<?php endif; ?>
	<?php endif; ?>
	
<?php endforeach; ?>
</div>
<?php endif; ?>


<?=Application_Service_EShop::AutoOffers()?->handleShoppingCart( $cash_desk )?>


<div class="shopping-cart-discount-modules">
	<div>
		<?=$dm_free_delivery?->handleShoppingCart( $cash_desk )?>
	</div>
	<div>
		<?=$dm_code?->handleShoppingCart( $cash_desk )?>
	</div>
</div>


<div class="shopping-cart-buy-button-area">
	<?=UI::button(Tr::_('Order'))->setUrl( EShop_Pages::CashDesk()->getURL() )->setClass('success')?>
</div>


<?=Application_Service_EShop::AnalyticsManager()?->viewCart( $cart )?>