<?php
namespace JetShopModule\Admin\WarehouseManagement\Warehouses;

use JetShop\WarehouseManagement_Warehouse as Warehouse;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View   $this
 * @var Warehouse       $warehouse
 */
$warehouse = $this->getRaw( 'warehouse' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( 'Do you really want to delete this warehouse?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $warehouse->getCode() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$warehouse->getInternalName();?> (<?=$warehouse->getInternalName();?>)</a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>