<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\Admin\WarehouseManagement\Warehouses;


use JetApplication\Admin_Managers;
use JetApplication\WarehouseManagement_Warehouse as Warehouse;

use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Warehouse     $warehouse
 */
$form = $this->getRaw( 'form' );

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 1 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 4 ] );

$warehouse = $this->getRaw( 'warehouse' );
$router = $this->getController()->getControllerRouter();
?>
<?=$form->start()?>

<?=Admin_Managers::EntityEdit()->renderEntityToolbar($form)?>

<div id="main-col">
		
		<?=Admin_Managers::EntityEdit()->renderEntityFormCommonFields($form)?>
		<?=$form->field( 'eshops' )?>
		<?=$form->field( 'address_street_no' )?>
		<?=$form->field( 'address_country' )?>
		<?=$form->field( 'address_town' )?>
		<?=$form->field( 'address_zip' )?>
</div>

<?=$form->end()?>
