<?php
namespace JetApplicationModule\Admin\WarehouseManagement\Warehouses;

use JetApplication\Shops;
use JetApplication\WarehouseManagement_Warehouse as Warehouse;

use Jet\UI;
use Jet\UI_dataGrid;
use Jet\UI_button;

use Jet\Tr;
use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Form         $filter_form
 */
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );
$router = $this->getController()->getControllerRouter();


$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( Warehouse $item ) use ( $router ) {
		if( ( $edit_uri = $router->action('edit')->URI( $item->getCode() ) ) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;
	}
);
$c_edit->addCustomCssStyle( 'width:100px;' );

$grid->getColumn( 'code' )->setRenderer(
	function( Warehouse $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getCode() );

		if(!$item->getIsActive()):
			echo '<span class="badge badge-danger">';
			echo UI::icon('times')->setTitle(Tr::_('Is not active'));
			echo '</span>';
		else:
			echo '<span class="badge badge-success">';
			echo UI::icon('check')->setTitle(Tr::_('Is active'));
			echo '</span>';
		endif;

		?>
		<a href="<?=$edit_uri;?>"><?=$item->getCode();?></a>
		<?php
	}
);
$grid->getColumn( 'code' )->addCustomCssStyle( 'width:250px;' );

$grid->getColumn( 'internal_name' )->setRenderer(
	function( Warehouse $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getCode() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getInternalName();?></a>
		<?php
	}
);
$grid->getColumn( 'internal_name' )->addCustomCssStyle( 'width:350px;' );

$grid->getColumn( 'internal_description' )->setRenderer(
	function( Warehouse $item ) use ( $router ) {
		?>
		<?=nl2br($item->getInternalDescription());?>
		<?php
	}
);

$grid->getColumn( 'shops' )->setRenderer(
	function( Warehouse $item ) use ( $router ) {
		foreach( $item->getShopKeys() as $key) {
			echo Shops::get($key)->getShopName().'<br>';
		}
	}
);
$grid->getColumn( 'shops' )->addCustomCssStyle( 'width:250px;' );
?>

<?=$filter_form->start()?>
<div class="row toolbar">
	<?php if( ( $add_uri = $router->action('add')->URI() ) ): ?>
		<div class="col-md-2 col-sm-12">
			<?=UI::button_create( Tr::_( 'Create a new Warehouse' ) )->setUrl( $add_uri )?>
		</div>
	<?php endif; ?>

	<div class="col-md-3 col-sm-12">
		<?= $filter_form->field( 'search' )->input() ?>
	</div>
	<div class="col-md-4 col-sm-12">
	</div>

</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
