<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Form;
use Jet\MVC_View;
use JetShop\Shops;
use JetShop\Parametrization_Property_Option;
use JetShop\Parametrization_Property_Option_ShopData;

/**
 * @var MVC_View   $this
 * @var Parametrization_Property_Option $option
 * @var Form $form
 */
$option = Controller_Main::getCurrentParamPropertyOption();

echo $this->render('lj_start');

	foreach(Shops::getList() as $shop):
		echo $option->getShopData( $shop )->renderImageWidgets( Parametrization_Property_Option_ShopData::getImageClasses(), !$option->getEditForm()->getIsReadonly() );
	endforeach;

echo $this->render('lj_end');