<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Form;
use Jet\Tr;
use Jet\MVC_View;
use JetShop\Shops;
use JetShop\Parametrization_Property_Option;

/**
 * @var MVC_View   $this
 * @var Parametrization_Property_Option $option
 * @var Form $form
 */
$option = Controller_Main::getCurrentParamPropertyOption();
$property = Controller_Main::getCurrentParamProperty();

$form = $option->getEditForm();
$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 2
]);

?>
<?=$this->render('lj_start')?>

<?php if($property->isInherited()): ?>
	<h4 class="inherited"><?=Tr::_('Inherited')?></h4>
<?php endif; ?>


<?php
echo $form->start();

echo $form->field('is_active');

foreach(Shops::getList() as $shop):
	$shop_key= $shop->getKey();

	$shop_data = $option->getShopData( $shop );

	$form->field('/shop_data/'.$shop_key.'/filter_label')->input()->addJsAction('onchange', "urlPathPart.afterNameChanged(this.value, '".$form->field('/shop_data/'.$shop_key.'/url_param')->getId()."', '".$shop_key."');");
	$form->field('/shop_data/'.$shop_key.'/filter_label')->input()->addJsAction('onchange', "$('#".$form->field('/shop_data/'.$shop_key.'/product_detail_label')->getId()."').val(this.value);");
	$form->field('/shop_data/'.$shop_key.'/url_param')->input()->addJsAction('onchange', "urlPathPart.afterPathPartChanged(this, '".$shop_key."')");

	echo $shop_data->renderShopDataBlock_start();
		?>
		<fieldset>
			<legend class="sub"><?=Tr::_('Main data')?></legend>

			<?=$form->field('/shop_data/'.$shop_key.'/is_active')?>
			<?=$form->field('/shop_data/'.$shop_key.'/filter_label')?>
			<?=$form->field('/shop_data/'.$shop_key.'/product_detail_label')?>
			<?=$form->field('/shop_data/'.$shop_key.'/url_param')?>
			<?=$form->field('/shop_data/'.$shop_key.'/description')?>
		</fieldset>

		<?php if($form->fieldExists('/shop_data/'.$shop_key.'/seo_h1')): ?>
		<fieldset>
			<legend class="sub"><?=Tr::_('SEO')?></legend>
			<?=$form->field('/shop_data/'.$shop_key.'/seo_h1')?>
			<?=$form->field('/shop_data/'.$shop_key.'/seo_title')?>
			<?=$form->field('/shop_data/'.$shop_key.'/seo_description')?>
			<?=$form->field('/shop_data/'.$shop_key.'/alternative_category_description')?>
			<?=$form->field('/shop_data/'.$shop_key.'/alternative_category_description_strategy')?>
			<?=$form->field('/shop_data/'.$shop_key.'/internal_fulltext_keywords')?>
		</fieldset>
		<?php endif; ?>
		<?php
	echo $shop_data->renderShopDataBlock_end();
endforeach;

echo $form->end();
?>

<?=$this->render('lj_end')?>