<?php
namespace JetShopModule\Admin\Services\Services;

use JetShop\Services_Service;

use Jet\Http_Request;
use Jet\UI;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View   $this
 * @var Services_Service       $service
 */
$service = $this->getRaw( 'service' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( 'Do you really want to delete this service?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $service->getCode() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$service->getInternalName();?> (<?=$service->getInternalName();?>)</a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>