<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Payment\Methods;


use Jet\MVC_View;
use JetApplication\Application_Service_Admin;
use JetApplication\Payment_Method;

/**
 * @var MVC_View $this
 * @var Payment_Method $item
 */

$item = $this->getRaw('item');
$eshop = $item->getEshop();

echo Application_Service_Admin::PriceFormatter()->formatWithCurrency(
	$eshop->getDefaultPricelist(),
	$item->getFreePaymentLimit()
);
