<?php
/**
 *
 * @copyright
 * @license
 * @author
 */
namespace JetApplicationModule\Admin\Payment\Methods;

use Jet\MVC_View;
use JetApplication\Admin_Managers;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 * @var PaymentMethod $item
 */

$item = $this->getRaw('item');

foreach( EShops::getList() as $eshop):
	if($item->getEshopData( $eshop )->getFreePaymentLimit()==0) {
		continue;
	}
	
	echo $eshop->getName().': '.Admin_Managers::PriceFormatter()->formatWithCurrency(
		$eshop->getDefaultPricelist(),
		$item->getEshopData( $eshop )->getFreePaymentLimit()
	);
	echo '<br>';
endforeach;
