<?php
namespace JetApplicationModule\Admin\Catalog\Products;

use Jet\Http_Request;
use Jet\MVC;
use Jet\UI_dataGrid;
use Jet\MVC_View;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Listing      $listing
 */
$grid = $this->getRaw( 'grid' );
$listing = $this->getRaw('listing');


$grid->footer()->setPrepend( $this->render('list/grid/footer') );

$GET = Http_Request::GET();
?>
<form action="<?=MVC::getPage()->getURL()?>" method="get" id="listing_operation_form">
	<?php foreach($GET->getRawData() as $key=>$val): ?>
	<input type="hidden" name="=<?=$key?>" value="<?=$GET->getString($key)?>">
	<?php endforeach; ?>
	<input type="hidden" name="listing_operation" value="" id="listing_operation">
<?=$grid->render();?>
</form>