<?php
namespace JetApplication;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Product $product
 */

$product = $this->getRaw('product');
?>
<?php /* if( $brand ): ?>
	<div class="manufacturer">
		<div class="left">
			<?= VYROBCE_ ?><a href="<?= $manufacturer->getUrl() ?>"><?= $manufacturer->getManufacturersName() ?></a>
		</div>
		<?php if( $manufacturer->getManufacturersImage() ): ?>
			<div class="right"
			     style="background-image:url(<?= DIR_WS_IMAGES . $manufacturer->getManufacturersImage() ?>)"></div>
		<?php endif; ?>
	</div>
<?php endif; */ ?>
