<?php
namespace JetShop;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Product $product
 */

$product = $this->getRaw('product');
?>
<?php /* if( $product->getIsComparable() ): ?>
	<div class="right">
		<div class="benefits">
			<?php if( $product->getIsComparable() ): ?>
				<span class="compare" data-products-id="<?= $product->getId() ?>" onclick="compareProducts.addProductToCompareList(this);">
					<span class="icon"></span>
					<span class="text"><?= POROVNAT ?></span>
				</span>
			<?php endif; ?>
		</div>
	</div>
<?php endif;*/ ?>
