<?php
namespace JetShop;

use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Product $product
 */

$product = $this->getRaw('product');
?>
<div class="price">
	<div class="row">
		<div class="cell"><?=Tr::_('Naše cena:') ?></div>
		<div class="cell final"><?= Price::formatWithCurrency( $product->getFinalPrice() ) ?></div>
	</div>
	<?php if( $product->getActionPrice() ): ?>
		<div class="row">
			<div class="cell"><?=Tr::_('Běžná cena:')?></div>
			<div class="cell normal"><?= Price::formatWithCurrency( $product->getStandardPrice() ) ?></div>
		</div>
	<?php endif; ?>
</div>
