<?php
namespace JetShopModule\Shop\Catalog;

use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View $this
 */

$product = Controller_Main::getProduct();

/*
if ($product_info->getReviewsCount() < 1) return;

$rank = $product_info->getReviewsRank();
$count = $product_info->getReviewsCount();
?>

<div class="product-rank">
	<div class="stars" style="background-position:0 <?= (((100-$rank)/10)*-18) ?>px"></div>
	<!--<div class="value"><?= $rank ?>%</div>-->
	<div class="count" id="scroll_product_tab_reviews"><span><?= TEXT_ALL_REVIEWS ?></span> (<?= $count ?>)</div>
</div>
*/