<?php
namespace JetShop;

use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Product $product
 */

$product = $this->getRaw('product');
?>
<div class="socials">

	<ul class="social-likes">
		<li class="facebook" title="Sdílet na Facebooku"></li>
		<li class="twitter" title="Sdílet na Twitteru"></li>
	</ul>
	<div class="options">
		<div class="link" data-send-products-link="<?= $product->getId() ?>"><?=Tr::_('Poslat odkaz') ?></div>
		<div class="questions" id="scroll_product_tab_questions"><?=Tr::_('Otázky a odpovědi') ?></div>
	</div>
</div>