<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\WithEShopData;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\EShopEntity_Admin_Interface;
use JetApplication\EShopEntity_WithEShopData;
use JetApplication\EShops;

/**
 * @var MVC_View $this
 * @var EShopEntity_WithEShopData|EShopEntity_Admin_Interface     $item
 */
$item = $this->getRaw('item');

$eshops = EShops::getListSorted();

if($item->isActive()):
	?><span class="badge badge-success"> <?=Tr::_('Active', dictionary: Tr::COMMON_DICTIONARY)?> </span> <?php
else:
	?><span class="badge badge-danger"><?=Tr::_('Not active', dictionary: Tr::COMMON_DICTIONARY)?></span> <?php
endif;

if( count($eshops)>1 ):
	foreach( $eshops as $eshop):
		if($item->getEshopData($eshop)->isActiveForShop()):
			?><span class="badge badge-success"><?=$eshop->getName()?></span> <?php
		else:
			?><span class="badge badge-danger"><?=$eshop->getName()?></span> <?php
		endif;
	endforeach;
endif;
