<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Edit;


use Jet\Locale;
use JetApplication\EShopEntity_Admin_Interface;
use JetApplication\Admin_Managers;
use JetApplication\EShopEntity_Definition;
use JetApplication\EShopEntity_WithEShopData;

use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use JetApplication\EShop;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var EShopEntity_WithEShopData|EShopEntity_Admin_Interface     $item
 */
$form = $this->getRaw( 'form' );
$item = $this->getRaw( 'item' );

$common_data_fields_renderer = $this->getRaw('add_common_data_fields_renderer');
$eshop_data_fields_renderer = $this->getRaw('add_eshop_data_fields_renderer');
$description_fields_renderer = $this->getRaw('add_description_fields_renderer');

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 3,
	Form_Renderer::LJ_SIZE_LARGE => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 8,
	Form_Renderer::LJ_SIZE_LARGE => 8
] );
?>


<?=$form->start()?>

<?php require 'add/toolbar.phtml'; ?>


<div id="main-col">
		<?php
		echo $this->render('entity-form-common-fields');
		
		
		if($common_data_fields_renderer) {
			$common_data_fields_renderer( $item, $form );
		}
		
		
		if($item instanceof EShopEntity_WithEShopData) {
			if(EShopEntity_Definition::get($item)->getDescriptionMode()) {
				if($description_fields_renderer) {
					echo Admin_Managers::EntityEdit()->renderDescriptionBlocks(
						form: $form,
						renderer: function( Locale $locale, string $locale_str ) use ($item, $form, $description_fields_renderer ) : void {
							$description_fields_renderer( $locale, $locale_str, $item, $form );
						});
					
				}
			} else {
				if($eshop_data_fields_renderer) {
					echo Admin_Managers::EntityEdit()->renderShopDataBlocks(
						form: $form,
						renderer: function( EShop $eshop, string $eshop_key ) use ($form, $item, $eshop_data_fields_renderer) : void {
							$eshop_data_fields_renderer( $eshop, $eshop_key, $item, $form );
						});
				}
			}
			
		}
		?>
	
</div>

<?=$form->end()?>
