<?php
namespace JetApplicationModule\Admin\Entity\Edit;

use Jet\Locale;
use Jet\UI;
use JetApplication\EShopEntity_Admin_Interface;
use JetApplication\Admin_Managers;
use JetApplication\EShopEntity_WithEShopData;

use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use JetApplication\EShop;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var EShopEntity_WithEShopData|EShopEntity_Admin_Interface     $item
 */
$form = $this->getRaw( 'form' );
$item = $this->getRaw( 'item' );

$common_data_fields_renderer = $this->getRaw('common_data_fields_renderer');
$eshop_data_fields_renderer = $this->getRaw('eshop_data_fields_renderer');
$description_fields_renderer = $this->getRaw('description_fields_renderer');

$form->setAutocomplete( false );
$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 3,
	Form_Renderer::LJ_SIZE_LARGE => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 8,
	Form_Renderer::LJ_SIZE_LARGE => 8
] );
?>


<?=$form->start()?>

<div class="toolbar" id="main-toolbar">
	<?=UI::button_goBack()?>
	
	<?=UI::button_save()->setOnclick("$('#".$form->getId()."').submit();")?>
</div>


<div id="main-col">
		<?=Admin_Managers::EntityEdit()->renderEntityFormCommonFields( $form );?>
		
		<?php
		if($common_data_fields_renderer) {
			$common_data_fields_renderer( $item, $form );
		}
		
		
		if($item instanceof EShopEntity_WithEShopData) {
			if($eshop_data_fields_renderer) {
				echo Admin_Managers::EntityEdit()->renderShopDataBlocks(
					form: $form,
					renderer: function( EShop $eshop, string $eshop_key ) use ($form, $item, $eshop_data_fields_renderer) : void {
						$eshop_data_fields_renderer( $eshop, $eshop_key, $item, $form );
					});
			}
			
			if($description_fields_renderer) {
				echo Admin_Managers::EntityEdit()->renderDescriptionBlocks(
					form: $form,
					renderer: function( Locale $locale, string $locale_str ) use ($item, $form, $description_fields_renderer ) : void {
						$description_fields_renderer( $locale, $locale_str, $item, $form );
					});
				
			}
		}
		?>
	
</div>

<?=$form->end()?>
