<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

namespace JetApplicationModule\Admin\Entity\Edit;

use Jet\MVC_View;
use JetApplication\Application_Service_Admin;
use JetApplication\EShopEntity_Basic;

/**
 * @var MVC_View $this
 * @var EShopEntity_Basic $item
 */

$item = $this->getRaw('item');


if(!$item->getId() || !$item->isEditable()) {
	return;
}
?>
<div style="position: fixed;top: 60px;right: 2px;z-index: 998;">
	<?=Application_Service_Admin::Image()?->commonImageManager( $item::getEntityType(), $item->getId() );?>
	<?=Application_Service_Admin::Document()?->commonDocumentManager( $item::getEntityType(), $item->getId() );?>
	<?=Application_Service_Admin::MagicTags()?->renderTool();?>
</div>
