<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\Form;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Form $form
 */
$form = $this->getRaw('form');
$item = $this->getRaw('item');

$schema = [
	'eshop',
	'internal_name',
	'internal_code',
	'internal_notes',
	'active_from',
	'active_till',
];


foreach($schema as $f) {
	if($form->fieldExists($f)) {
		echo $form->field($f);
	}
}