<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Edit;

use Jet\Locale;
use Jet\Tr;
use Jet\MVC_View;
use Jet\UI_messages;
use JetApplication\EShopEntity_Event;

/**
 * @var MVC_View $this
 * @var EShopEntity_Event[]     $history
 */

$history = $this->getRaw( 'history' );
?>

<table class="table table-striped">
	<thead>
	<tr>
		<th style="width: 200px;"><?=Tr::_('Date and time')?></th>
		<th style="width: 250px;"></th>
		<th></th>
		<th style="width: 200px;"><?=Tr::_('Administrator')?></th>
	</tr>
	</thead>
	<tbody>
	<?php foreach($history as $event):
		$handler = $event->getHandlerModule();
		if(!$handler) {
			continue;
		}
		?>
		<tr>
			<td>
				<?=Locale::dateAndTime( $event->getDateAdded() )?>
			</td>
			<td><div class="event <?=$handler->getEventCSSClass()?>"><?=$handler->showEventName()?></div></td>
			<td>
				<?php if($event->getInternalNote()): ?>
				<div class="card card-body">
					<b><?=Tr::_('Internal notes')?></b>
					<br>
					<?=nl2br($event->getInternalNote())?>
				</div>
				<?php endif; ?>
				<?php if($event->getNoteForCustomer()): ?>
					<div class="card card-body">
						<b><?=Tr::_('Notes for customer')?></b>
						<br>
						<?=nl2br($event->getInternalNote())?>
					</div>
				<?php endif; ?>
				
				<?php if(!$event->getHandled()): ?>
					<?=UI_messages::createDanger( $event->getErrorMessage() ) ?>
				<?php endif; ?>
				
				<?php
				$details = $handler->showEventDetails();
				if($details):
					?>
					<div class="card card-body"><?=$details?></div>
					<?php
				endif;
				?>
			</td>
			<td>
				<?=$event->getAdministrator() ?>
			</td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
