<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Entity\Edit;

use Jet\Http_Headers;
use Jet\Http_Request;
use Jet\Locale;
use Jet\Tr;
use Jet\MVC_View;
use Jet\UI;
use Jet\UI_button;
use Jet\UI_messages;
use JetApplication\EShopEntity_Event;

/**
 * @var MVC_View $this
 * @var EShopEntity_Event[]     $history
 */

$history = $this->getRaw( 'history' );

$show_full = $this->getBool('shop_full');
?>
<?php if($show_full): ?>
<fieldset class="o_section">
	<legend><?=UI::icon('clock-rotate-left')?> <?=Tr::_('History')?></legend>
	<div id="event-history">
<?php endif; ?>

<table class="table table-striped">
	<thead>
	<tr>
		<th style="width: 200px;"><?=Tr::_('Date and time')?></th>
		<th style="width: 250px;"></th>
		<th></th>
		<th style="width: 200px;"><?=Tr::_('Administrator')?></th>
	</tr>
	</thead>
	<tbody>
	<?php
	$GET = Http_Request::GET();
	$handle_event_again = $GET->getInt('handle_event_again');
	$close_event = $GET->getInt('close_event');
	
	foreach($history as $event):
		$handler = $event->getHandlerModule();
		if(!$handler) {
			continue;
		}
		
		if(!$event->getHandled()) {
			if($handle_event_again==$event->getId()) {
				$event->handle();
				Http_Headers::reload(unset_GET_params: ['handle_event_again']);
			}
			if($close_event==$event->getId()) {
				$event->setHandled(true);
				$event->save();
				Http_Headers::reload(unset_GET_params: ['close_event']);
			}
		}
		?>
		<tr>
			<td>
				<?=Locale::dateAndTime( $event->getDateAdded() )?>
			</td>
			<td><div class="event <?=$handler->getEventCSSClass()?>"><?=$handler->showEventName()?></div></td>
			<td>
				<?php if($event->getInternalNote()): ?>
				<div class="card card-body">
					<b><?=Tr::_('Internal notes')?></b>
					<br>
					<?=nl2br($event->getInternalNote())?>
				</div>
				<?php endif; ?>
				<?php if($event->getNoteForCustomer()): ?>
					<div class="card card-body">
						<b><?=Tr::_('Notes for customer')?></b>
						<br>
						<?=nl2br($event->getNoteForCustomer())?>
					</div>
				<?php endif; ?>
				
				<?php if(!$event->getHandled()):
					echo UI_messages::createDanger( $event->getErrorMessage() );
				
					echo UI::button( Tr::_('Handle again') )
						->setUrl(Http_Request::currentURI(['handle_event_again'=>$event->getId()]))
						->setClass( UI_button::CLASS_INFO )
						->setOnClick("return confirm('".Tr::_('Really?')."')")
						->setSize( UI_button::SIZE_EXTRA_SMALL );
					
					echo "&nbsp;&nbsp;&nbsp;&nbsp;";
					
					echo UI::button( Tr::_('Close event') )
						->setUrl(Http_Request::currentURI(['close_event'=>$event->getId()]))
						->setClass( UI_button::CLASS_PRIMARY )
						->setOnClick("return confirm('".Tr::_('Really?')."')")
						->setSize( UI_button::SIZE_EXTRA_SMALL );
					
				endif; ?>
				
				<?php
				$details = $handler->showEventDetails();
				if($details):
					?>
					<div class="card card-body"><?=$details?></div>
					<?php
				endif;
				?>
			</td>
			<td>
				<?=$event->getAdministrator() ?>
			</td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>

<?php if($show_full): ?>
	</div>
</fieldset>
<?php endif; ?>
