<?php
namespace JetApplicationModule\Admin\Catalog\Brands;

use JetApplication\Admin_Managers;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;
use JetApplication\Shops_Shop;

/**
 * @var MVC_View   $this
 * @var Form       $form
 * @var Brand    $brand
 */
$form = $this->getRaw( 'form' );

$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 8 ] );

$brand = $this->getRaw( 'brand' );

?>



<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()->setOnclick("$('#".$form->getId()."').submit();")?>
		<?php endif; ?>
	</div>
</div>

<div class="row">

	<div class="col-md-12" id="main-col">

		<?=$form->start()?>
		<?=$form->field( 'internal_name' )?>
		<?=$form->field( 'internal_notes' )?>

		<?php
		Admin_Managers::UI()->renderShopDataBlocks(
		form: $form,
		renderer: function( Shops_Shop $shop, string $shop_key ) use ($brand, $form) : void {
			?>
				<fieldset>
					<legend class="sub"><?=Tr::_('Main data')?></legend>
					
					<?=$form->field('/shop_data/'.$shop_key.'/name')?>
					<?=$form->field('/shop_data/'.$shop_key.'/second_name')?>
					<?=$form->field('/shop_data/'.$shop_key.'/description')?>
				</fieldset>
				
				<fieldset>
					<legend class="sub"><?=Tr::_('SEO')?></legend>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_h1')?>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_title')?>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_description')?>
					<?=$form->field('/shop_data/'.$shop_key.'/seo_keywords')?>
					<?=$form->field('/shop_data/'.$shop_key.'/internal_fulltext_keywords')?>
				</fieldset>
		<?php }); ?>
		
		<?=$form->end()?>


	</div>
</div>

