<?php
namespace JetShopModule\Admin\Catalog\Brands;

use Jet\Http_Request;
use JetShop\Brand;

use Jet\UI;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View   $this
 * @var Brand    $brand
 */
$brand = $this->getRaw( 'brand' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( 'Do you really want to delete this brand?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $brand->getId() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$brand->getName();?></a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>