<?php
namespace JetShopModule\Admin\Catalog\Brands;

use JetShop\Brand;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;
use JetShop\Brand_ShopData;
use JetShop\Shops;

/**
 * @var MVC_View   $this
 * @var Form       $form
 * @var Brand    $brand
 */
$form = $this->getRaw( 'form' );

$form->renderer()->setDefaultLabelWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 2 ] );
$form->renderer()->setDefaultFieldWidth( [ Form_Renderer::LJ_SIZE_MEDIUM => 8 ] );

$brand = $this->getRaw( 'brand' );

$tabs = UI::tabsJS('brand_tabs', [
	'tab_main' => Tr::_('Main data'),
	'tab_images' => Tr::_('Images')
]);

?>



<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()->setOnclick("$('#".$form->getId()."').submit();")?>
		<?php endif; ?>
	</div>
</div>

<div class="row">

	<div class="col-md-12" id="main-col">

		<?=$tabs->start()?>
		
			<?=$tabs->getTab('tab_main')->content()->start()?>
				<?=$form->start()?>
				<?=$form->field( 'name' )?>

				<?php foreach(Shops::getListSorted() as $shop):
					$shop_key = $shop->getKey();

					$shop_data = $brand->getShopData( $shop );
					?>
					<?=$shop_data->renderShopDataBlock_start()?>

					<fieldset>
						<legend class="sub"><?=Tr::_('Main data')?></legend>

						<?=$form->field('/shop_data/'.$shop_key.'/is_active')?>

						<?=$form->field('/shop_data/'.$shop_key.'/name')?>
						<?=$form->field('/shop_data/'.$shop_key.'/second_name')?>
						<?=$form->field('/shop_data/'.$shop_key.'/description')?>
					</fieldset>

					<fieldset>
						<legend class="sub"><?=Tr::_('SEO')?></legend>
						<?=$form->field('/shop_data/'.$shop_key.'/seo_h1')?>
						<?=$form->field('/shop_data/'.$shop_key.'/seo_title')?>
						<?=$form->field('/shop_data/'.$shop_key.'/seo_description')?>
						<?=$form->field('/shop_data/'.$shop_key.'/seo_keywords')?>
						<?=$form->field('/shop_data/'.$shop_key.'/internal_fulltext_keywords')?>
					</fieldset>
					<?=$shop_data->renderShopDataBlock_end()?>
				<?php endforeach; ?>
				<?=$form->end()?>
			<?=$tabs->getTab('tab_main')->content()->end()?>
			<?=$tabs->getTab('tab_images')->content()->start()?>
				<?php
				foreach(Shops::getListSorted() as $shop):
					echo $brand->getShopData( $shop )->renderImageWidgets( Brand_ShopData::getImageClasses(), !$form->getIsReadonly() );
				endforeach;
				?>
			<?=$tabs->getTab('tab_images')->content()->end()?>
		<?=$tabs->end()?>

	</div>
</div>

