<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Analytics\Service\JetAnalytics;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Main $module
 * @var Report $report
 */

$module = $this->getRaw('module');
$report = $this->getRaw('report');

echo $module->renderSelectEShop();

echo $module->renderChart_Line_DaysPerEShop( $this->getRaw('data') );

