<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\Catalog\Products;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Product_KindOfFile;
use JetApplication\Product;

/**
 * @var MVC_View $this
 * @var Product $product
 */

$editable = $this->getBool('editable');
$product = $this->getRaw('product');

$kind_of_files = Product_KindOfFile::getScope();

foreach( $product->getFiles() as $file ):
	$key = $file->getId();

	$url = $file->getURL();
	$kind = $kind_of_files[$file->getKindOfFileId()]??'';
	
	if($editable):
		?>
		
		<div
			style="margin: 5px;padding:10px; border: 1px solid #c9c9c9;border-radius: 5px;background-color:#ffffff;display: grid;grid-template-columns: auto auto auto 150px auto 1fr;gap:10px;align-items: center;"
		>
			<div class="file" data-file="<?=$key?>">
				<input type="checkbox" value="<?=$key?>"
				data-file="<?=$key?>"
				data-url="<?=$url?>"
				data-name="<?=$file->getFile()?>"
				data-kind="<?=$kind?>"
				class="select_file_checkbox"/></div>
			<div style="padding-right: 10px;"><?=UI::icon('up-down')?></div>
			<div style="padding-right: 10px;"><a href="<?=$url?>" download target="_blank"><?=UI::icon('download')->setTitle(Tr::_('Download file'))?></a></div>
			
			<div style="padding-right: 20px;opacity: 0.5"><?=$kind?></div>
			<div style="padding-right: 20px;"><?=$file->getFile()?></div>
			<div style="text-align: right"><a
					class="btn btn-danger btn-xs"
					data-file="<?=$key?>"
					data-url="<?=$url?>"
					data-name="<?=$file->getFile()?>"
					data-kind="<?=$kind?>"
					onclick="ProductFilesHandler.deleteFile(this);return false;"
				><?=UI::icon('trash')->setTitle(Tr::_('Delete file'))?></a></div>
		</div>
	<?php
	else:
		?>
		<div
			style="margin: 5px;padding:10px; border: 1px solid #c9c9c9;border-radius: 5px;background-color:#ffffff;display: grid;grid-template-columns:500px 150px;align-items: center;"
		>
			<div><?=$file->getFile()?></div>
			<div><?=$kind?></div>
		</div>
	
	<?php
	endif;
endforeach; ?>

