<?php
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var EShop $eshop
 */
$form = $this->getRaw('form');
$eshop = $this->getRaw('eshop');
$eshop_key = $eshop->getKey();
?>
<fieldset>
	<legend class="sub"><?=Tr::_('Main data')?></legend>
	
	<?=$form->field('/eshop_data/'.$eshop_key.'/name');?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/variant_select_description');?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/similar_product_select_description');?>
	<?=$form->field('/eshop_data/'.$eshop_key.'/description');?>
</fieldset>
