<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Form;
use Jet\MVC_View;
use JetShop\Parametrization_Property;
use JetShop\Parametrization_Property_ShopData;
use JetShop\Shops;

/**
 * @var MVC_View   $this
 * @var Parametrization_Property $property
 * @var Form $form
 */
$property = Controller_Main::getCurrentParamProperty();

echo $this->render('lj_start');

	foreach(Shops::getList() as $shop):
		echo $property->getShopData( $shop )->renderImageWidgets( Parametrization_Property_ShopData::getImageClasses(), !$property->getEditForm()->getIsReadonly() );
	endforeach;

echo $this->render('lj_end');