<?php
namespace JetShopModule\Admin\Catalog\Categories;

use Jet\Form;
use Jet\Tr;
use Jet\Mvc_View;
use JetShop\Parametrization_Property_ShopData;
use JetShop\Shops;

/**
 * @var Mvc_View   $this
 * @var Form $form
 */
$property = Controller_Main::getCurrentParamProperty();

$form = $property->getEditForm();
$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 2
]);

?>
<?=$this->render('lj_start')?>
<?php if($property->isInherited()): ?>
	<h4 class="inherited"><?=Tr::_('Inherited')?></h4>
<?php endif; ?>

<?php
	echo $form->start();


	echo $form->field('is_active');

	echo $form->field('allow_display');
	echo $form->field('allow_filter');
	echo $form->field('allow_compare');

	if($form->fieldExists('stencil_id')) {
		echo $form->field('stencil_id');
	}
	if($form->fieldExists('decimal_places')) {
		echo $form->field('decimal_places');
	}

	if($form->fieldExists('is_variant_selector')) {
		echo $form->field('is_variant_selector');
	}

	foreach(Shops::getList() as $shop):
		$shop_id= $shop->getId();
		$shop_data = $property->getShopData( $shop_id );

		$form->field('/shop_data/'.$shop_id.'/label')->input()->addJsAction('onchange', "urlPathPart.afterNameChanged(this.value, '".$form->field('/shop_data/'.$shop_id.'/url_param')->getId()."', '".$shop_id."')");
		$form->field('/shop_data/'.$shop_id.'/url_param')->input()->addJsAction('onchange', "urlPathPart.afterPathPartChanged(this, '".$shop_id."')");

		echo $shop_data->renderShopDataBlock_start();

		?>
		<fieldset>
			<legend class="sub"><?=Tr::_('Main data')?></legend>
			<?php
			echo $form->field('/shop_data/'.$shop_id.'/is_active');
			echo $form->field('/shop_data/'.$shop_id.'/label');
			echo $form->field('/shop_data/'.$shop_id.'/description');

			if($form->fieldExists('/shop_data/'.$shop_id.'/bool_yes_description')) {
				echo $form->field('/shop_data/'.$shop_id.'/bool_yes_description');
			}

			echo $form->field('/shop_data/'.$shop_id.'/url_param');
			echo $form->field('/shop_data/'.$shop_id.'/units');
			?>
		</fieldset>

		<fieldset>
			<legend class="sub"><?=Tr::_('SEO')?></legend>
			<?php
			echo $form->field('/shop_data/'.$shop_id.'/seo_h1');
			echo $form->field('/shop_data/'.$shop_id.'/seo_h1_strategy');
			echo $form->field('/shop_data/'.$shop_id.'/seo_title');
			echo $form->field('/shop_data/'.$shop_id.'/seo_title_strategy');
			echo $form->field('/shop_data/'.$shop_id.'/seo_description');
			echo $form->field('/shop_data/'.$shop_id.'/seo_description_strategy');
			?>
		</fieldset>
		<?php
		echo $shop_data->renderShopDataBlock_end();
	endforeach;

	echo $form->end();

echo $this->render('lj_end');