<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\Admin\ManageAccess\Administrators\Roles;


use JetApplication\Auth_Administrator_Role as Role;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Role $item
 */

$item = $this->getRaw('item');
?>
<?= $item->getDescription(); ?>
