<?php
namespace JetApplicationModule\Admin\Orders;

use Jet\Form;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;

use Jet\MVC_View;


/**
 * @var MVC_View $this
 * @var Order     $order
 * @var Form $form
 */

$order = $this->getRaw( 'order' );
$form = $this->getRaw('delivery_address_form');


if(!$order->isEditable()) {
	return;
}

?>
<div style="text-align: center;padding: 10px;">
<?=UI::button(Tr::_('Edit'))->setIcon('pen-to-square')
	->setClass(UI_button::CLASS_PRIMARY)
	->setOnClick("$('#delivery_address_dialog').modal('show');")?>
</div>

