<?php
namespace JetApplicationModule\Exports\Heureka;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\KindOfProduct;
use JetApplication\Property;

/**
 * @var MVC_View   $this
 * @var ?HeurekaCategory $export_category
 * @var Form $category_form
 * @var Form $param_form
 * @var KindOfProduct $kind_of_product
 */

$kind_of_product = $this->getRaw('kind_of_product');
$category_form = $this->getRaw('category_form');
$export_category = $this->getRaw('export_category');

$category_form->renderer()->setDefaultLabelWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 2] );
$category_form->renderer()->setDefaultFieldWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 4] );

$param_form = $this->getRaw('param_form');
$param_form->renderer()->setDefaultLabelWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 2] );
$param_form->renderer()->setDefaultFieldWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 4] );


$dialog = UI::dialog('select_heureka_category', Tr::_('Select Heureka category'));
?>
<script type="text/javascript">
	let heurekaCategorySelect = {
		openDialog: function() {
			$('#select_heureka_category').modal('show');
		},
		select: function(id) {
			$('#select_heureka_category_categories').load('<?=Http_Request::currentURI()?>&heureka_category='+id);
		},

		confirm: function (id, name) {
			$('#heureka_cate_settings__export_category').val(id);
			$('#selected_heureka_category_name').html(name);
			$('#select_heureka_category').modal('hide');
		}
	};
</script>

<h2><?=Tr::_('Category')?></h2>
<?=$category_form->start()?>
	<?=$category_form->field('export_category')?>
	<div class="row">
		<label class="col-form-label col-md-2 text-right"><?=Tr::_('Heureka category:')?></label>
		<div class="col-md-10">
			<?=UI::button(Tr::_('Select category'))
				->setIcon('folder-open')
				->setClass('info')
				->setSize(UI_button::SIZE_SMALL)
				->setOnclick('heurekaCategorySelect.openDialog()')?>


			<span id="selected_heureka_category_name" class="badge badge-light"><?=$export_category?$export_category->getFullName():''?></span>
		</div>
	</div>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-10" style="padding: 10px;">
			<?=UI::button_save()?>
		</div>
	</div>
<?=$category_form->end()?>

<?=$dialog->start()?>
	<div style="height: 400px;overflow: auto;" id="select_heureka_category_categories">
		<?=$this->render('kind_of_product_settings/dialog/categories');?>
	</div>
<?=$dialog->end()?>
<hr>





<h2><?=Tr::_('Parameters')?></h2>

<?=$param_form->start()?>
<?php foreach( $kind_of_product->getPropertyIds() as $p_property ):
	
		$field = $param_form->field( $p_property->getId() );

		$field->label()->addCustomCssClass('text-right');

		echo $field;

		if($p_property->getType()==Property::PROPERTY_TYPE_OPTIONS):
			foreach($p_property->getOptions() as $p_option):

				$field = $param_form->field($p_property->getId().'-o'.$p_option->getId());
				?>
				<div class="row">
					<div class="col-md-2"></div>
					<?=$field->label()?>
				</div>
				<div class="row">
					<div class="col-md-2"></div>
					<div class="col-md-4"><?=$field->input()?></div>
				</div>
				<?php
			endforeach;
		endif;
		?>
		<br>
		<?php
	
endforeach; ?>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-4">
			<?=UI::button_save()?>
			<br><br><br>
		</div>
	</div>

<?=$param_form->end()?>