<?php
namespace JetApplicationModule\Admin\Delivery\Methods;

use JetApplication\Delivery_Method;

use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use JetApplication\Delivery_Method_ShopData;
use JetApplication\Shops;

/**
 * @var MVC_View $this
 * @var Form     $form
 * @var Delivery_Method     $delivery_method
 */

$delivery_method = $this->getRaw( 'delivery_method' );
?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>

	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
		<?=$this->getRaw('tabs')?>

		<?php if(!$delivery_method->getIsNew()):
			foreach(Shops::getListSorted() as $shop):
				echo $delivery_method->getShopData( $shop )->renderImageWidgets( Delivery_Method_ShopData::getImageClasses(), $delivery_method->getEditForm()->getIsReadonly() );
			endforeach;
		endif; ?>
	</div>
</div>



