<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Catalog;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Marketing_ProductSticker;
use JetApplication\Pricelists;
use JetApplication\Product_EShopData;
use JetApplication\EShop_Managers;

/**
 * @var MVC_View $this
 * @var Product_EShopData $product
 */

$c_id = $this->getInt('c_id');
$product = $this->getRaw('product');

if($c_id) {
	$URL = $product->getURL().'?c='.$c_id;
} else {
	$URL = $product->getURL();
}

$stickers = Marketing_ProductSticker::getProductStickers( $product->getId() );
$pricelist = Pricelists::getCurrent();

$units = $product->getMeasureUnit()?->getName();
if($units) {
	$units = ' / '.$units;
}

?>

<div class="product_listing_item">
	<div class="product_listing_item_stickers">
		<?php foreach($stickers as $sticker): ?>
			
			<div class="product_listing_item_sticker" style="background-color: <?=$sticker->getColorBackground();?>;color: <?=$sticker->getColorText()?>;">
				<?php if($sticker->getImageProductListing()): ?>
					<div class="product_listing_item_sticker_image"><img src="<?=$sticker->getImageProductListingThumbnailUrl(20, 20)?>"></div>
				<?php endif; ?>
				<div class="product_listing_item_sticker_text"><?=$sticker->getText()?></div>
			</div>
		
		<?php endforeach; ?>
	</div>
	
	
	<div class="product_listing_item_images">
		<a href="<?=$URL?>" class="product_listing_item_main_image">
			<?php if($product->getImageURL(0)): ?>
				<img src="<?=$product->getImageThumbnailUrl( 0, 220, 220 )?>"/>
			<?php endif; ?>
		</a>
	</div>

	<div class="product_listing_item_title"><a href="<?= $URL ?>"><?= $product->getFullName() ?></a></div>
	

	<div class="product_listing_item_price">
		<div class="product_listing_item_price_standard">
			<?php if ($product->getPriceBeforeDiscount( $pricelist )): ?>
			<?= EShop_Managers::PriceFormatter()->formatWithCurrency( $product->getPriceBeforeDiscount( $pricelist ) ) ?>
			<?php endif; ?>
		</div>
		<div class="product_listing_item_price_final">
			<?= EShop_Managers::PriceFormatter()->formatWithCurrency( $product->getPrice( $pricelist ) ) ?> <?=$units?>
		</div>
	</div>

	<div class="product_listing_item_buy_buttons">

		<?php if ($product->isVariantMaster()): ?>
			<?=UI::button(Tr::_('Select variant'))->setUrl($URL)->setClass(UI_button::CLASS_SECONDARY)->setSize(UI_button::SIZE_NORMAL)?>
		<?php else: ?>
			<?=EShop_Managers::ShoppingCart()->renderBuyButton_listing( $product )?>
		<?php endif; ?>
	</div>
	
	<div class="product_listing_item_compare_buttons">
		<?=EShop_Managers::Wishlist()?->renderProductButton( $product ) ?>
		<?=EShop_Managers::Compare()?->renderProductButton( $product ) ?>
	</div>
	
	<div class="product_listing_item_reviews">
		<?=EShop_Managers::ProductReviews()?->renderRank( $product );?>
	</div>

</div>

