<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicaTionModule\EShop\Catalog;


use Jet\UI;
use Jet\MVC_View;
use JetApplication\ProductListing;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');

$paginator = $listing->getPaginator();

$pages = $paginator->getPagesURL();

if(count($pages)<2) {
	return;
}


$s_index = $paginator->getCurrentPageNo() - 3;
$e_index = $paginator->getCurrentPageNo() + 3;
if( $s_index < 1 ) {
	$e_index = $e_index + ($s_index * -1) + 1;
	$s_index = 1;
}

if( $e_index > count( $pages ) ) {
	$e_index = count( $pages );
	$s_index = $e_index - 6;
	if( $s_index < 1 ) {
		$s_index = 1;
	}
}
?>

<div class="product_listing_pagination">
<nav>
	
	<ul class="pagination">
		<?php if( ($p_URL = $paginator->getPrevPageURL()) ): ?>
			<li class="page-item">
				<a class="page-link" href="<?= $paginator->getFirstPageURL() ?>"
				   onclick="listing.page(1);return false"
				   aria-label="<?= UI::_( 'Firts' ) ?>">
					<?= UI::icon( 'first-page' ) ?>
				</a>
			</li>
			<li class="page-item">
				<a class="page-link" href="<?= $p_URL ?>" aria-label="<?= UI::_( 'Previous' ) ?>"
				   onclick="listing.page(<?=$paginator->getPrevPageNo()?>);return false"
				>
					<?= UI::icon( 'prev-page' ) ?>
				</a>
			</li>
		<?php endif ?>
		
		
		<?php
		for( $p_no = $s_index; ($p_no <= $e_index && isset( $pages[$p_no] )); $p_no++ ):
			$p_URL = $pages[$p_no];
			
			?>
			<?php if( $p_no == $paginator->getCurrentPageNo() ): ?>
			<li class="page-item active"><a class="page-link" href="<?= $p_URL ?>"><?= $p_no ?></a></li>
		<?php else: ?>
			<li class="page-item"><a class="page-link" href="<?= $p_URL ?>"
			                         onclick="listing.page(<?=$p_no?>);return false"><?= $p_no ?></a></li>
		<?php endif; ?>
		<?php endfor; ?>
		
		
		<?php if( ($p_URL = $paginator->getNextPageURL()) ): ?>
			<li class="page-item">
				<a class="page-link" href="<?= $p_URL ?>" aria-label="<?= UI::_( 'Next' ) ?>"
				   onclick="listing.page(<?=$paginator->getNextPageNo()?>);return false"
				>
					<?= UI::icon( 'next-page' ) ?>
				</a>
			</li>
			<li class="page-item">
				<a class="page-link" href="<?= $paginator->getLastPageURL() ?>"
				   onclick="listing.page(<?=$paginator->getPagesCount()?>);return false"
				   aria-label="<?= UI::_( 'Last' ) ?>">
					<?= UI::icon( 'last-page' ) ?>
				</a>
			</li>
		<?php endif ?>
	
	</ul>
</nav>

</div>