<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
namespace JetApplicationModule\EShop\Catalog;


use Jet\MVC_View;
use Jet\Tr;
use JetApplication\ProductListing;

/**
 * @var MVC_View $this
 * @var ProductListing $listing
 */

$listing = $this->getRaw('listing');
?>
<div id="product_listing_sort">
	<div id="product_listing_sort_title"><?=Tr::_('Sort:')?></div>
	<?php foreach($listing->getSorters() as $sorter): ?>

		<?php if($sorter->getIsSelected()):?>
			<div id="product_listing_selected_sorter" data-key="<?=$sorter->getKey()?>"><?=$sorter->getLabel()?></div>
		<?php else: ?>
			<button type="button" class="product_listing_sort_btn" onclick="listing.sort('<?=$sorter->getKey()?>');"><?=$sorter->getLabel()?></button>
		<?php endif; ?>

	<?php endforeach; ?>
</div>
