<?php
namespace JetApplicationModule\Admin\Catalog\Properties;

use Jet\Form;
use Jet\MVC_View;
use Jet\UI;
use JetApplication\Admin_Managers;

/**
 * @var MVC_View   $this
 * @var Form $form
 */

$image_manager = Admin_Managers::Image();
?>
<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?=UI::button_goBack()?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">
	
	<?php
	echo $this->getRaw('tabs');
	echo $image_manager->renderStandardManagement();
	?>
	</div>
</div>

