<?php
namespace JetApplicationModule\Admin\Catalog\Categories;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\Tr;
use Jet\MVC_View;
use Jet\UI;
use JetApplication\Property;
use JetApplication\Shops;

/**
 * @var MVC_View   $this
 * @var Form $form
 * @var Property $property
 */
$property = $this->getRaw('property');

$form = $property->getEditForm();
$form->renderer()->setDefaultLabelWidth([
	Form_Renderer::LJ_SIZE_MEDIUM => 2
]);

echo $form->start();

?>
	<div class="row toolbar" id="main-toolbar">
		<div class="col-md-12">
			<?=UI::button_goBack()?>
			
			<?php if( !$form->getIsReadonly() ): ?>
				<?=UI::button_save()?>
			<?php endif; ?>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12" id="main-col">
			<?=$this->getRaw('tabs')?>
			<br>
			<?php
			
			echo $form->field('is_active');
			echo $form->field('internal_name');
			echo $form->field('internal_notes');
			
			if($form->fieldExists('decimal_places')) {
				echo $form->field('decimal_places');
			}
			
			
			foreach(Shops::getListSorted() as $shop):
				$shop_key = $shop->getKey();
				$shop_data = $property->getShopData( $shop );
				
				$form->field('/shop_data/'.$shop_key.'/label')->input()->addJsAction('onchange', "urlPathPart.afterNameChanged(this.value, '".$form->field('/shop_data/'.$shop_key.'/url_param')->getId()."', '".$shop_key."')");
				$form->field('/shop_data/'.$shop_key.'/url_param')->input()->addJsAction('onchange', "urlPathPart.afterPathPartChanged(this, '".$shop_key."')");
				
				echo $shop_data->renderShopDataBlock_start();
				
				?>
				<fieldset>
					<legend class="sub"><?=Tr::_('Main data')?></legend>
					<?php
					echo $form->field('/shop_data/'.$shop_key.'/is_active');
					echo $form->field('/shop_data/'.$shop_key.'/label');
					echo $form->field('/shop_data/'.$shop_key.'/description');
					
					if($form->fieldExists('/shop_data/'.$shop_key.'/bool_yes_description')) {
						echo $form->field('/shop_data/'.$shop_key.'/bool_yes_description');
					}
					
					echo $form->field('/shop_data/'.$shop_key.'/url_param');
					echo $form->field('/shop_data/'.$shop_key.'/units');
					?>
				</fieldset>
				
				<?php
				echo $shop_data->renderShopDataBlock_end();
			endforeach;
			?>

		</div>
	</div>

<?php
echo $form->end();

