<?php

use Jet\UI_tabsJS;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var UI_tabsJS $t
 */
$t = $this->getRaw( 'element' );

if(!$t->getId()) {
	$t->setId( 'tab_'.uniqid() );
}

$GLOBALS['__current_js_tabs'] = $t->getId();
?>
<div class="tabs-container" id="<?=$t->getId()?>_container">
	<ul class="tabs-tabs" id="<?=$t->getId()?>_tabs_container">
		<?php foreach( $t->getTabs() as $tab ):
			echo $tab;
		endforeach; ?>
	</ul>
