<?php
/**
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license EUPL 1.2  https://eupl.eu/1.2/en/
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use JetApplication\EShop;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var EShop $eshop
 */
$form = $this->getRaw('form');
$eshop = $this->getRaw('eshop');
$eshop_key = $eshop->getKey();


?>
<fieldset>
	<legend class="sub"><?=Tr::_('Main data')?></legend>
	<?php
	echo $form->field('/eshop_data/'.$eshop_key.'/label');
	echo $form->field('/eshop_data/'.$eshop_key.'/description');
	
	if($form->fieldExists('/eshop_data/'.$eshop_key.'/bool_yes_description')) {
		echo $form->field('/eshop_data/'.$eshop_key.'/bool_yes_description');
	}
	
	if($form->fieldExists('/eshop_data/'.$eshop_key.'/units')) {
		echo $form->field( '/eshop_data/' . $eshop_key . '/units' );
	}
	if($form->fieldExists('/eshop_data/'.$eshop_key.'/url_param')) {
		echo $form->field( '/eshop_data/' . $eshop_key . '/url_param' );
	}
	?>
</fieldset>
