<?php
namespace JetApplicationModule\Shop\CashDesk;


use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Customer;

/**
 * @var MVC_View $this
 * @var CashDesk $cash_desk
 */
$cash_desk = $this->getRaw('cash_desk');

$customer = Customer::getCurrentCustomer();
$billing_address_hash = $cash_desk->getBillingAddress()->getHash();
?>
<div class="addresses">
<?php foreach( $customer->getAddresses() as $address): ?>

	<div class="<?=$billing_address_hash==$address->getHash()?'address-selected':'address'?>" onclick="CashDesk.customer.billingAddress.select(<?=$address->getId()?>)">
			<?php if(
				$cash_desk->isCompanyOrder() &&
				$address->getCompanyName()
			): ?>
				<?=$address->getCompanyName()?><br>
				<?=$address->getCompanyId()?><br>
				<?=$address->getCompanyVatId()?><br>
			<?php endif?>

			<?=$address->getFirstName()?> <?=$address->getSurname()?><br>
			<?=$address->getAddressStreetNo()?><br/>
			<?=$address->getAddressZip()?> <?=$address->getAddressTown()?>

			<div class="continue-button-area">
				<?=UI::button(Tr::_('Select this address'))->setOnclick(" ")->setClass('link')?>
			</div>
	</div>

<?php endforeach; ?>
</div>
