<?php
namespace JetApplication;


use Jet\Tr;
use Jet\UI;

$cash_desk = CashDesk::get();

$customer = Customer::getCurrentCustomer();
$billing_address_hash = $cash_desk->getBillingAddress()->getHash();
?>
<div class="row" style="margin-bottom: 20px;">
	<div class="col-md-2"></div>
	<div class="col-md-10">
		<?php foreach($customer->getAddresses() as $ba): ?>
			<div class="card" style="width: 300px;height: 200px;margin:5px;float: left" onclick="CashDesk.customer.billingAddress.select(<?=$ba->getId()?>)">
				<div class="card-body<?=$billing_address_hash==$ba->getHash()?' bg-info':''?>">
					<p class="card-text">
						<?php if($cash_desk->isCompanyOrder()): ?>
							<?=$ba->getCompanyName()?><br>
							<?=$ba->getCompanyId()?><br>
							<?=$ba->getCompanyVatId()?><br>
						<?php endif?>

						<?=$ba->getFirstName()?> <?=$ba->getSurname()?><br>
						<?=$ba->getAddressStreetNo()?><br/>
						<?=$ba->getAddressZip()?> <?=$ba->getAddressTown()?>

						<div class="text-right">
							<?=UI::button(Tr::_('Select this address'))->setOnclick("CashDesk.customer.billingAddress.select({$ba->getId()}")->setClass('link')?>
						</div>
					</p>
				</div>
			</div>

		<?php endforeach; ?>

	</div>
</div>
